### ISSUE TITLE
Build error with 3.0.12 - Module Federation Plugin has been initialized using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#10013]
This appears like it might be an example of #9289. Although that issue seems fixed, perhaps having an incompatible `nbdime` installed breaks the build?

In any case, I thought I'd post the error in case anyone else is seeing similar:
```
$ jupyter lab build
[LabBuildApp] JupyterLab 3.0.12
[LabBuildApp] Building in /home/user/conda-envs/dev/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] WARNING | The extension "nbdime-jupyterlab" is outdated.

Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-u1201pg9.log
$                                                   
$ cat /tmp/jupyterlab-debug-u1201pg9.log
[LabBuildApp] Building in /home/user/conda-envs/dev/share/jupyter/lab
[LabBuildApp] Node v14.15.4

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] WARNING | The extension "nbdime-jupyterlab" is outdated.

[LabBuildApp] > node /home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.58s.

[LabBuildApp] > node /home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /home/user/conda-envs/dev/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.33s.

[LabBuildApp] > node /home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] Failed to load '/home/user/conda-envs/dev/share/jupyter/lab/staging/webpack.prod.minimize.config.js' config
[webpack-cli] Invalid configuration object. Module Federation Plugin has been initialized using a configuration object that does not match the API schema.
 - configuration.shared should be one of these:
   [non-empty string | object { <key>: object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? } | non-empty string }, ...] | object { <key>: object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? } | non-empty string }
   -> Modules that should be shared in the share scope. When provided, property names are used to match requested modules in this compilation.
   Details:
    * configuration.shared['jupyter-dataserializers'].import should be one of these:
      false | non-empty string
      -> Provided module that should be provided to share scope. Also acts as fallback module if no shared module is found in share scope or version isn't valid. Defaults to the property name.
      Details:
       * configuration.shared['jupyter-dataserializers'].import should be false.
         -> No provided or fallback module.
       * configuration.shared['jupyter-dataserializers'].import should be a non-empty string.
         -> A module that should be shared in the share scope.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 166, in start
    raise e

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 163, in start
    app_options=app_options, production = production, minimize=self.minimize)

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 470, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 678, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
$ 
```

**Comment by dhirschfeld** [comment]
Having removed `nbdime` I'm still seeing this error.

Turning on debug output shows that this occurs in the minimize stage and points the finger at 'jupyter-dataserializers':
```
Step 9/24 : RUN jupyter lab build --debug -y && jupyter lab clean -y
 ---> Running in 36e589aed220
/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
[LabBuildApp] Searching ['/home/user', '/home/user/.jupyter', '/home/user/conda-envs/dev/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /home/user/conda-envs/dev/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /home/user/.jupyter
[LabBuildApp] Looking for jupyter_config in /home/user
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /home/user/conda-envs/dev/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /home/user/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /home/user
[LabBuildApp] JupyterLab 3.0.12
[LabBuildApp] Building in /home/user/conda-envs/dev/share/jupyter/lab
[LabBuildApp] Node v14.15.4

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @blueprintjs/core@3.41.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.41.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 34.08s.

[LabBuildApp] > node /home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
-\|/-\|/-\|/-[LabBuildApp] 
[LabBuildApp] > node /home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
Done in 4.67s.

[LabBuildApp] > node /home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
-\|/-\|/-\|/-\|/-\|/-\|/-\|/[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] Failed to load '/home/user/conda-envs/dev/share/jupyter/lab/staging/webpack.prod.minimize.config.js' config
[webpack-cli] Invalid configuration object. Module Federation Plugin has been initialized using a configuration object that does not match the API schema.
 - configuration.shared should be one of these:
   [non-empty string | object { <key>: object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? } | non-empty string }, ...] | object { <key>: object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? } | non-empty string }
   -> Modules that should be shared in the share scope. When provided, property names are used to match requested modules in this compilation.
   Details:
    * configuration.shared['jupyter-dataserializers'].import should be one of these:
      false | non-empty string
      -> Provided module that should be provided to share scope. Also acts as fallback module if no shared module is found in share scope or version isn't valid. Defaults to the property name.
      Details:
       * configuration.shared['jupyter-dataserializers'].import should be false.
         -> No provided or fallback module.
       * configuration.shared['jupyter-dataserializers'].import should be a non-empty string.
         -> A module that should be shared in the share scope.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 166, in start
    raise e

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 163, in start
    app_options=app_options, production = production, minimize=self.minimize)

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 470, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

[LabBuildApp]   File "/home/user/conda-envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 678, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
Build failed.
```

**Comment by dhirschfeld** [comment]
If I specify `--no-minimize` then it fails with the same error in `run build:prod`

**Comment by jasongrout** [comment]
What extensions do you have installed?

**Comment by dhirschfeld** [comment]
> What extensions do you have installed? 

A lot! 😁 

I'll see if I can knock up a docker image to repro it...

**Comment by dhirschfeld** [comment]
[WIP] Repro environment: [env.txt](https://github.com/jupyterlab/jupyterlab/files/6331103/env.txt)

**Comment by dhirschfeld** [comment]
mamba create -n test-jlab-build --file https://github.com/jupyterlab/jupyterlab/files/6331103/env.txt

```
~/code via  base
❯ conda activate test-jlab-build

~/code via  test-jlab-build
❯ node --version
v14.15.4

~/code via  test-jlab-build
❯ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.22.0
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : 3.0.14
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5

~/code via  test-jlab-build
❯ jupyter lab build --debug
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @blueprintjs/core@3.42.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.42.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.6.0" has unmet peer dependency "crypto@1.0.1".
warning "nbdime-jupyterlab > nbdime@6.1.0" has unmet peer dependency "codemirror@^5.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 62.80s.

[LabBuildApp] > node /home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
-[LabBuildApp] yarn run v1.21.1
$ /home/dhirschfeld/miniforge3/envs/test-jlab-build/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] > node /home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/staging/yarn.js
-[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.6.0" has unmet peer dependency "crypto@1.0.1".
warning "nbdime-jupyterlab > nbdime@6.1.0" has unmet peer dependency "codemirror@^5.0.0".
[5/5] Building fresh packages...
Done in 6.98s.

[LabBuildApp] > node /home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
\[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] Failed to load '/home/dhirschfeld/miniforge3/envs/test-jlab-build/share/jupyter/lab/staging/webpack.prod.minimize.config.js' config
[webpack-cli] Invalid configuration object. Module Federation Plugin has been initialized using a configuration object that does not match the API schema.
 - configuration.shared should be one of these:
   [non-empty string | object { <key>: object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? } | non-empty string }, ...] | object { <key>: object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? } | non-empty string }
   -> Modules that should be shared in the share scope. When provided, property names are used to match requested modules in this compilation.
   Details:
    * configuration.shared['jupyter-dataserializers'].import should be one of these:
      false | non-empty string
      -> Provided module that should be provided to share scope. Also acts as fallback module if no shared module is found in share scope or version isn't valid. Defaults to the property name.
      Details:
       * configuration.shared['jupyter-dataserializers'].import should be false.
         -> No provided or fallback module.
       * configuration.shared['jupyter-dataserializers'].import should be a non-empty string.
         -> A module that should be shared in the share scope.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/labapp.py", line 166, in start
    raise e

[LabBuildApp]   File "/home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/labapp.py", line 163, in start
    app_options=app_options, production = production, minimize=self.minimize)

[LabBuildApp]   File "/home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/commands.py", line 470, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

[LabBuildApp]   File "/home/dhirschfeld/miniforge3/envs/test-jlab-build/lib/python3.7/site-packages/jupyterlab/commands.py", line 678, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-a8q0dh7f.log
[LabBuildApp] Exiting application: JupyterLab
```

**Comment by dhirschfeld** [comment]
ping @jasongrout - the above `conda` environment reproduced the same error in a separate environment in my WSL terminal.

**Comment by dhirschfeld** [comment]
Still seeing this with 3.0.14 :/

**Comment by jasongrout** [comment]
From the error message, it looks like some package is causing the 'jupyter-dataserializers' sharing config to be set incorrectly. I don't have a dev environment handy right now to be more precise, but if you look in the build directory and search for 'jupyter-dataserializers', it should pull up the sharing config that is actually being used from the webpack config that is generated. A key next step is finding what that `jupyter-dataserializers` sharing config looks like (in particular, it seems it is complaining about the import key).

My first guess is that one of the installed extensions has a misconfiguration for jupyter-dataserializers in its package.json. My second guess is that there is a bug in the build system causing the build system to generate a wrong config from some corner case in some config for jupyter-dataserializers.

**Comment by dhirschfeld** [comment]
Thanks for the help @jasongrout! I'm not really sure what I'm looking at but the mentions of  `jupyter-dataserializers` are below:

<details>
<summary><tt><b>package.json</b></tt></summary>

```json
            "jupyter-scales": {
                "extension": "lib/plugin",
                "outputDir": "lab-dist/jupyter-scales",
                "sharedPackages": {
                    "@jupyter-widgets/base": {
                        "bundled": false,
                        "singleton": true
                    },
                    "jupyter-datawidgets": {
                        "bundled": true,
                        "singleton": true
                    },
                    "jupyter-dataserializers": {
                        "bundled": true,
                        "singleton": true
                    }
                },
                "discovery": {
                    "kernel": [
                        {
                            "kernel_spec": {
                                "language": "^python"
                            },
                            "base": {
                                "name": "ipyscales"
                            },
                            "managers": [
                                "pip",
                                "conda"
                            ]
                        }
                    ]
                }
            },
```
</details>


<details>
<summary><tt><b>yarn.lock</b></tt></summary>

```yarn.lock
jupyter-dataserializers@^2.3.0:
  version "2.3.0"
  resolved "https://registry.yarnpkg.com/jupyter-dataserializers/-/jupyter-dataserializers-2.3.0.tgz#9ae2f8aeae9de4094cb7f454dff2767a6100e511"
  integrity sha512-juXyhDOBYDyziSRcPiRPUXFaAJ1iC3YHoddgd1jJNRfhKynPGKqBXrMVPMXHBO4YiqMZs6kPHpOpJUXsdxRnMg==
  dependencies:
    "@jupyter-widgets/base" "^1 || ^2 || ^3 || ^4"
    ndarray "^1.0.18"
    pako "^1.0.6"

jupyter-datawidgets@^5.4.0:
  version "5.4.0"
  resolved "https://registry.yarnpkg.com/jupyter-datawidgets/-/jupyter-datawidgets-5.4.0.tgz#9449ed7d9973f980e2fa2fa3aa97bb907480c193"
  integrity sha512-iy7c3ty5nbSP2DsPi7iwHVV0y7l8MpzBfR6a+swR+yfj135ebHE0dVPsyuk+Rfa7GjG3CGgo7Lk3mRJs4/Wdtw==
  dependencies:
    "@jupyter-widgets/base" "^1 || ^2 || ^3 || ^4"
    jupyter-dataserializers "^2.3.0"
    ndarray "^1.0.18"

"jupyter-scales@file:../extensions/jupyter-scales-3.2.0.tgz":
  version "3.2.0"
  resolved "file:../extensions/jupyter-scales-3.2.0.tgz#42a2246076abb9a1c890396ede586194ea01d15b"
  dependencies:
    "@jupyter-widgets/base" "^2.0.1 || ^3 || ^4"
    "@phosphor/coreutils" "^1.3.0"
    chromabar "^0.7.0"
    d3-interpolate "^2.0.0"
    d3-scale "^3.1.0"
    d3-scale-chromatic "^2.0.0"
    d3-selection "^1.4.0"
    jupyter-dataserializers "^2.3.0"
    jupyter-datawidgets "^5.4.0"
    ndarray "^1.0.18"
```
</details>


...I'll see if removing `ipyscales` fixes the problem!

**Comment by dhirschfeld** [comment]
Yup, that was it:
```
webpack 5.31.2 compiled successfully in 1778 ms
Done in 41.21s.
```

Thanks again for your help @jasongrout - I'll open an issue in the `ipyscales` repo...
