### ISSUE TITLE
change yarn registry need delete staging/yarn.lock 

### ISSUE THREAD

**Issue by rrwang05** [jupyterlab/jupyterlab#10027]
**env:**
jupyter --version
  jupyter core     : 4.7.1
  jupyter-notebook : 6.3.0
  qtconsole        : 5.0.3
  ipython          : 7.21.0
  ipykernel        : 5.3.4
  jupyter client   : 6.1.12
  jupyter lab      : 3.0.11
  nbconvert        : 6.0.7
  ipywidgets       : 7.6.3
  nbformat         : 5.1.2
  traitlets        : 5.0.5

yarn set registry as "https://registry.npm.taobao.org/"
Node v14.15.4

**then run :**
jupyter lab clean
 jupyter lab build

**there show error:**

[LabBuildApp] Building in /root/anaconda3/share/jupyter/lab
  2 [LabBuildApp] Node v14.15.4

  4 [LabBuildApp] Yarn configuration loaded.
  5 [LabBuildApp] Building jupyterlab assets (production, minimized)
  6 [LabBuildApp] > node /root/anaconda3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
  7 [LabBuildApp] yarn install v1.21.1
  8 [1/5] Validating package.json...
  9 [2/5] Resolving packages...
 10 [3/5] Fetching packages...
 11 error An unexpected error occurred: "https://registry.npm.taobao.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.15.3.tgz: Request failed \"404 Not Found\"".
 12 info If you think this is a bug, please open a bug report with the information provided in "/root/anaconda3/share/jupyter/lab/staging/yarn-error.log".
 13 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 14
 15 [LabBuildApp] npm dependencies failed to install
 16 [LabBuildApp] Traceback (most recent call last):
 17
 18 [LabBuildApp]   File "/root/anaconda3/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
 19     yield
 20
 21 [LabBuildApp]   File "/root/anaconda3/lib/python3.8/site-packages/jupyterlab/labapp.py", line 166, in start
 22     raise e
 23
 24 [LabBuildApp]   File "/root/anaconda3/lib/python3.8/site-packages/jupyterlab/labapp.py", line 162, in start
 25     build(name=self.name, version=self.version,
 26
 27 [LabBuildApp]   File "/root/anaconda3/lib/python3.8/site-packages/jupyterlab/commands.py", line 469, in build
 28     return handler.build(name=name, version=version, static_url=static_url,
 29
 30 [LabBuildApp]   File "/root/anaconda3/lib/python3.8/site-packages/jupyterlab/commands.py", line 669, in build
 31     raise RuntimeError(msg)
 32
 33 [LabBuildApp] RuntimeError: npm dependencies failed to install
 34
 35 [LabBuildApp] Exiting application: JupyterLab

then I change delete yarn registry

**then redo :**
jupyter lab clean
 jupyter lab build

and there still showed error info like above.

last, I deleted file staging/yarn.lock and it worked.

### Proposed Solution
may i just run some command like clean.... , then can delete .lock file?

**Comment by jasongrout** [comment]
It sounds like your yarn registry doesn't have the same packages as the official yarn registry? In that case, yes, deleting the yarn.lock is needed to rebuild the requirements from what is available in your yarn registry.

Perhaps having a flag to `jupyter lab clean` that refreshes the yarn.lock would be good? `jupyter lab clean --refresh-lockfile` or something?

**Comment by adaaaaaa** [comment]
have almost the same error...have you fix it?
