### ISSUE TITLE
Out of Memory Error in Running Build

### ISSUE THREAD

**Issue by sirinath** [jupyterlab/jupyterlab#10158]
I ran 

```
 C:\WINDOWS\system32>jupyter lab build
[LabBuildApp] JupyterLab 3.0.14
[LabBuildApp] Building in C:\ProgramData\Miniconda3\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  C:\Users\sirin\AppData\Local\Temp\jupyterlab-debug-xay1g1on.log
```

Since I got an error I ran

```
C:\WINDOWS\system32>jupyter lab build --dev-build=False --minimize=False
[LabBuildApp] JupyterLab 3.0.14
[LabBuildApp] Building in C:\ProgramData\Miniconda3\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (production, not minimized)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  C:\Users\sirin\AppData\Local\Temp\jupyterlab-debug-8zaip5s9.log
```

Respective error logs:

```
[LabBuildApp] Building in C:\ProgramData\Miniconda3\share\jupyter\lab
[LabBuildApp] Node v15.14.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.6.0" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
Done in 167.03s.

[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.6.0" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 19.74s.

[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] [31mModuleNotFoundError: Module not found: Error: Can't resolve '@bokeh/jupyter_bokeh/style/index.js' in 'C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build'
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\Compilation.js:1672:28
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:712:13
    at eval (eval at create (C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:628:24
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:782:8
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:902:5
resolve '@bokeh/jupyter_bokeh/style/index.js' in 'C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build'
  Parsed request is a module
  using description file: C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build\node_modules doesn't exist or is not a directory
      looking for modules in C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules
        existing directory C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh
          using description file: C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\package.json (relative path: .)
            using description file: C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\package.json (relative path: ./style/index.js)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js.wasm doesn't exist
              as directory
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js doesn't exist
      C:\ProgramData\Miniconda3\share\jupyter\lab\node_modules doesn't exist or is not a directory
      C:\ProgramData\Miniconda3\share\jupyter\node_modules doesn't exist or is not a directory
      C:\ProgramData\Miniconda3\share\node_modules doesn't exist or is not a directory
      looking for modules in C:\ProgramData\Miniconda3\node_modules
        C:\ProgramData\Miniconda3\node_modules\@bokeh\jupyter_bokeh doesn't exist
      C:\ProgramData\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory[39m
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\labapp.py", line 166, in start
    raise e

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\labapp.py", line 162, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\commands.py", line 469, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\commands.py", line 678, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

```

and

```
[LabBuildApp] Building in C:\ProgramData\Miniconda3\share\jupyter\lab
[LabBuildApp] Node v15.14.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, not minimized)
[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.07s.

[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.6.0" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
Done in 40.25s.

[LabBuildApp] > node C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.config.js
[webpack-cli] [31mModuleNotFoundError: Module not found: Error: Can't resolve '@bokeh/jupyter_bokeh/style/index.js' in 'C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build'
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\Compilation.js:1672:28
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:712:13
    at eval (eval at create (C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:628:24
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:782:8
    at C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:902:5
resolve '@bokeh/jupyter_bokeh/style/index.js' in 'C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build'
  Parsed request is a module
  using description file: C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\ProgramData\Miniconda3\share\jupyter\lab\staging\build\node_modules doesn't exist or is not a directory
      looking for modules in C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules
        existing directory C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh
          using description file: C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\package.json (relative path: .)
            using description file: C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\package.json (relative path: ./style/index.js)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js.wasm doesn't exist
              as directory
                C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules\@bokeh\jupyter_bokeh\style\index.js doesn't exist
      C:\ProgramData\Miniconda3\share\jupyter\lab\node_modules doesn't exist or is not a directory
      C:\ProgramData\Miniconda3\share\jupyter\node_modules doesn't exist or is not a directory
      C:\ProgramData\Miniconda3\share\node_modules doesn't exist or is not a directory
      looking for modules in C:\ProgramData\Miniconda3\node_modules
        C:\ProgramData\Miniconda3\node_modules\@bokeh\jupyter_bokeh doesn't exist
      C:\ProgramData\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory[39m
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\labapp.py", line 166, in start
    raise e

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\labapp.py", line 162, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\commands.py", line 469, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "C:\ProgramData\Miniconda3\lib\site-packages\jupyterlab\commands.py", line 678, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/out-of-memory-error-in-running-build/8914/1

**Comment by agoose77** [comment]
This isn't actually an OOM error according to the error logs; the OOM error is only mentioned by Jupyter because it (was) is a common cause for builds to fail. 

Yarn reports that `C:\ProgramData\Miniconda3\share\jupyter\lab\staging\node_modules` doesn't exist. I'm really NAE on this stuff, but I suspect something's awry with the staging directory. 

Could you run `dir C:\ProgramData\Miniconda3\share\jupyter\lab\staging` in a terminal?

**Comment by sirinath** [comment]
I get:

```
C:\>dir C:\ProgramData\Miniconda3\share\jupyter\lab\staging
 Volume in drive C has no label.
 Volume Serial Number is 640B-32DF

 Directory of C:\ProgramData\Miniconda3\share\jupyter\lab\staging

26/04/2021  06:25 PM    <DIR>          .
26/04/2021  06:25 PM    <DIR>          ..
26/04/2021  06:24 PM                68 .yarnrc
26/04/2021  06:24 PM             3,875 bootstrap.js
26/04/2021  06:25 PM    <DIR>          build
26/04/2021  06:24 PM             6,642 index.js
26/04/2021  06:24 PM    <DIR>          linked_packages
26/04/2021  06:25 PM    <DIR>          node_modules
26/04/2021  06:24 PM            14,036 package.json
26/04/2021  06:24 PM             1,417 publicpath.js
26/04/2021  09:46 AM    <DIR>          templates
26/04/2021  06:24 PM             9,873 webpack.config.js
26/04/2021  06:24 PM               577 webpack.prod.config.js
26/04/2021  06:24 PM             1,003 webpack.prod.minimize.config.js
26/04/2021  06:24 PM         5,094,799 yarn.js
26/04/2021  06:24 PM           374,196 yarn.lock
              10 File(s)      5,506,486 bytes
               6 Dir(s)  99,431,518,208 bytes free
```

**Comment by agoose77** [comment]
OK, looking at the errors again, the directory in question does exist. It seems to me like your `bokeh` installation might be broken. Is it possible for you to create this virtualenvironment? Alternatively, you could manually clean this up. Try uninstalling the bokeh labextension and then rebuilding.

**Comment by sirinath** [comment]
How do I manually clean up?

**Comment by agoose77** [comment]
To start with, try just uninstalling the bokeh extension and seeing if you can perform a rebuild. If not, you might need to manually remove the files from `node_modules`

**Comment by sirinath** [comment]
It works after removing it.

**Comment by agoose77** [comment]
Fab, then I'll mark this issue as answered.
