### ISSUE TITLE
Updating with pip on Ubuntu got jupyter-packaging version error

### ISSUE THREAD

**Issue by paulathomas** [jupyterlab/jupyterlab#10166]
pip gave me this error:

ERROR: jupyterlab-server 2.5.0 has requirement jupyter-packaging<2,~=0.9, but you'll have jupyter-packaging 0.7.12 which is incompatible. 

Stupidly, perhaps, did a rebuild of Jupyter lab. Ever since I get:

Traceback (most recent call last):                                                                                        File "/usr/local/bin/jupyter-lab", line 5, in <module>                                                                    from jupyterlab.labapp import main                                                                                    File "/usr/local/lib/python3.8/dist-packages/jupyterlab/__init__.py", line 7, in <module>                                 from .labapp import LabApp                                                                                            File "/usr/local/lib/python3.8/dist-packages/jupyterlab/labapp.py", line 15, in <module>                                  from jupyterlab_server import slugify, WORKSPACE_EXTENSION                                                            File "/usr/local/lib/python3.8/dist-packages/jupyterlab_server/__init__.py", line 4, in <module>                          from .app import LabServerApp                                                                                         File "/usr/local/lib/python3.8/dist-packages/jupyterlab_server/app.py", line 10, in <module>                              from ._version import __version__                                                                                     File "/usr/local/lib/python3.8/dist-packages/jupyterlab_server/_version.py", line 1, in <module>                          from jupyter_packaging import get_version_info                                                                      ImportError: cannot import name 'get_version_info' from 'jupyter_packaging' (/usr/local/lib/python3.8/dist-packages/jupyter_packaging/__init__.py)                                   

Whenever I try to run jupyterlab.

**Comment by agoose77** [comment]
@paulathomas can you run `pip --version`?

**Comment by paulathomas** [comment]
pip 20.1.1 from /usr/lib/python3/dist-packages/pip (python 3.8)    

anyio==2.0.2
argon2-cffi==20.1.0
arrow==1.0.3
async-generator==1.10
attrs==20.3.0
Automat==20.2.0
Babel==2.9.0
backcall==0.2.0
beautifulsoup4==4.9.3
bleach==3.3.0
blinker==1.4
bokeh==2.3.1
Brotli==1.0.9
Cartopy==0.19.0.post1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cloud-init==21.1
colorama==0.4.4
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==3.4.7
cupshelpers==1.0
cycler==0.10.0
dash==1.20.0
dash-core-components==1.16.0
dash-html-components==1.1.3
dash-renderer==1.9.1
dash-table==4.11.3
dbus-python==1.2.16
decorator==5.0.7
defer==1.0.6
defusedxml==0.7.1
distro==1.5.0
distro-info==0.0.0
echo==0.5
entrypoints==0.3
ezodf==0.3.2
fake-useragent==0.1.11
Flask==1.1.2
Flask-Compress==1.9.0
future==0.18.2
gitdb==4.0.5
GitPython==3.1.12
httplib2==0.19.1
hyperlink==21.0.0
idna==3.1
importlib-metadata==4.0.1
incremental==21.3.0
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.18.0
jeepney==0.6.0
Jinja2==2.11.3
json5==0.9.5
jsonpatch==1.32
jsonpointer==2.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-packaging==0.7.12
jupyter-server==1.4.1
jupyterlab==3.0.14
jupyterlab-pygments==0.1.2
jupyterlab-server==2.5.0
keyring==23.0.1
kiwisolver==1.3.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.3
lazr.uri==1.0.5
lxml==4.6.3
macaroonbakery==1.3.1
MarkupSafe==1.1.1
matplotlib==3.4.1
mistune==0.8.4
more-itertools==8.7.0
nbclassic==0.2.5
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
netifaces==0.10.9
notebook==6.3.0
numpy==1.20.2
oauthlib==3.1.0
packaging==20.9
pandas==1.2.4
pandas-ods-reader==0.0.7
pandocfilters==1.4.3
parso==0.8.2
patsy==0.5.1
pbr==5.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
plotly==4.14.3
praw==7.2.0
prawcore==2.0.0
prometheus-client==0.10.1
prompt-toolkit==3.0.18
protobuf==3.15.8
psutil==5.8.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycparser==2.20
pycups==2.0.1
Pygments==2.8.1
PyGObject==3.38.0
PyHamcrest==2.0.2
PyJWT==2.0.1
pymacaroons==0.13.0
PyNaCl==1.4.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyRFC3339==1.1
pyrsistent==0.17.3
pyserial==3.5
pyshp==2.1.3
PySocks==1.7.1
python-apt==2.1.3+ubuntu1.3
python-dateutil==2.8.1
python-debian==0.1.39
pytz==2021.1
pyxdg==0.27
PyYAML==5.4.1
pyzmq==22.0.3
QtPy==1.9.0
requests==2.25.1
requests-unixsocket==0.2.0
retrying==1.3.3
scipy==1.6.3
seaborn==0.11.1
SecretStorage==3.3.1
Send2Trash==1.5.0
service-identity==18.1.0
Shapely==1.7.1
simplejson==3.17.2
six==1.15.0
smmap==3.0.5
sniffio==1.2.0
sos==4.1
soupsieve==2.1
SQLAlchemy==1.3.22
ssh-import-id==5.11
statsmodels==0.12.2
stem==1.8.0
systemd-python==234
tcl-kernel==0.0.5
terminado==0.9.4
testpath==0.4.4
testresources==2.0.1
tornado==6.1
traitlets==5.0.5
Twisted==21.2.0
typing-extensions==3.7.4.3
ubuntu-advantage-tools==24.4
ufw==0.36
unattended-upgrades==0.1
update-checker==0.18.0
urllib3==1.26.4
wadllib==1.3.5
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.58.0
Werkzeug==1.0.1
zipp==3.4.1
zope.interface==5.4.0

**Comment by paulathomas** [comment]
Solved it! |I missed out jupyter-packaging from my updatable packag4es list. Updated now and it will be on the list from now!

**Comment by agoose77** [comment]
Excellent! Glad that everything worked out :)

The newer version of `pip` (>=20.3) introduces a new resolver by default that should stop this happening again.

It might also be worth checkout out some of the Python package management tools like `poetry`, `pipenv`, or `flit` (among others). They take care of making sure that you update all of your dependencies together without introducing incompatible versions, and some other useful features as well. Personally I recommend `poetry`.

**Comment by agoose77** [comment]
Closing this issue now that it has been resolved.
