### ISSUE TITLE
Debugger in broken state

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10502]
## Description

The debugger can be in a broken state that results in the toolbar buttons not to appear.

![debug_feat_missing](https://user-images.githubusercontent.com/8435071/123780062-1495e900-d8d3-11eb-8b76-5a9ef33de9ac.gif)

## Reproduce

1. Open a notebook
2. Start the debugger
3. Set a breakpoint
4. Run the cell with the breakpoint
5. Hit `Terminate`
6. Close the notebook without saving
7. Open the notebook (the kernel was not shutdown)
8. The switch button is not added

## Expected behavior

The switch button should be added and activated

## Context

I tracked the error down to 
https://github.com/jupyterlab/jupyterlab/blob/36713c57e28f1d974e90ee819e64e790b1dbeff8/packages/debugger/src/handler.ts#L369

`this._service.hasStoppedThreads()` is actually true when it should have been false.

And when closing the notebook, the following errors are raised in the browser console:

```
TypeError: panel is null
    addCommands index.ts:1360
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    WidgetTracker widgettracker.ts:144
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    _onInstanceDisposed restorablepool.ts:314
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    node_modules jlab_core.4ce36f7fa5554ca95073.js:23612
    dispose panel.ts:160
    _revealed mainareawidget.ts:80
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    node_modules jlab_core.4ce36f7fa5554ca95073.js:23612
    dispose widget.ts:342
    dispose widget.ts:1180
    dispose panel.ts:159
    onClose widgetmanager.ts:318
    messageHook widgetmanager.ts:232
    invokeHook index.es6.js:427
    passed index.es6.js:183
    every index.es6.js:1596
    sendMessage index.es6.js:182
    node_modules jlab_core.4ce36f7fa5554ca95073.js:23927
    node_modules jlab_core.4ce36f7fa5554ca95073.js:32918
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29925
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29627
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29779
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29621

   exceptionHandler index.es6.js:211
    invokeSlot index.es6.js:462
    emit index.es6.js:416
    emit index.es6.js:99
    WidgetTracker widgettracker.ts:144
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    _onInstanceDisposed restorablepool.ts:314
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    dispose index.es6.js:909
    dispose panel.ts:160
    _revealed mainareawidget.ts:80
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    dispose index.es6.js:909
    dispose widget.ts:342
    dispose widget.ts:1180
    dispose panel.ts:159
    onClose widgetmanager.ts:318
    messageHook widgetmanager.ts:232
    invokeHook index.es6.js:427
    passed index.es6.js:183
    every index.es6.js:1596
    sendMessage index.es6.js:182
    close index.es6.js:1224
    _onTabCloseRequested index.es6.js:10215
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    _evtMouseUp index.es6.js:7222
    handleEvent index.es6.js:6924
    (Async: EventListener.handleEvent)
    _evtMouseDown index.es6.js:7076
    handleEvent index.es6.js:6918
```
```
Uncaught (in promise) Error: Canceled future for debug_request message before replies were done
    dispose future.ts:192
    _clearKernelState default.ts:1094
    _clearKernelState default.ts:1093
    dispose default.ts:257
    dispose default.ts:219
    dispose sessioncontext.tsx:610
    dispose context.ts:198
    _widgetDisposed widgetmanager.ts:402
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    node_modules jlab_core.4ce36f7fa5554ca95073.js:23612
    dispose panel.ts:160
    _revealed mainareawidget.ts:80
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    node_modules jlab_core.4ce36f7fa5554ca95073.js:23612
    dispose widget.ts:342
    dispose widget.ts:1180
    dispose panel.ts:159
    onClose widgetmanager.ts:318
    messageHook widgetmanager.ts:232
    invokeHook index.es6.js:427
    passed index.es6.js:183
    every index.es6.js:1596
    sendMessage index.es6.js:182
    node_modules jlab_core.4ce36f7fa5554ca95073.js:23927
    node_modules jlab_core.4ce36f7fa5554ca95073.js:32918
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    node_modules jlab_core.4ce36f7fa5554ca95073.js:21489
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29925
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29627
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29779
    node_modules jlab_core.4ce36f7fa5554ca95073.js:29621

    displayDefinedVariables service.ts:296
    InterpretGeneratorResume self-hosted:1487
    AsyncFunctionThrow self-hosted:695
    (Async: async)
    iopubMessage handler.ts:167
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    onIOPubMessage default.ts:365
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    _handleMessage default.ts:1407
    AsyncFunctionNext self-hosted:690
    (Async: async)
    _msgChain default.ts:1489
    (Async: promise callback)
    _onWSMessage default.ts:1486
    (Async: EventHandlerNonNull)
    _createSocket default.ts:1251
    (Async: setTimeout handler)
    _reconnect default.ts:1438
    reconnect default.ts:513
    restart default.ts:481
    InterpretGeneratorResume self-hosted:1487
    AsyncFunctionNext self-hosted:690
    (Async: async)
    restartKernel sessioncontext.tsx:633
    restart sessioncontext.tsx:1295
    InterpretGeneratorResume self-hosted:1487
    AsyncFunctionNext self-hosted:690
    (Async: async)
    restartKernel index.ts:2412
    delegateExecute index.ts:822
    execute index.es6.js:372
    triggerActiveItem index.es6.js:5017
    _evtMouseUp index.es6.js:5353
    handleEvent index.es6.js:5163
    (Async: EventListener.handleEvent)
    onBeforeAttach index.es6.js:5188
    processMessage index.es6.js:1367
    invokeHandler index.es6.js:442
    sendMessage index.es6.js:178
    attach index.es6.js:1763
    openRootMenu index.es6.js:5925
    open index.es6.js:5143
    _openChildMenu index.es6.js:12090
    _evtMouseMove index.es6.js:12041
    handleEvent index.es6.js:11868
```

**Comment by fcollonval** [comment]
Ok there is a kernel issue implied (ipykernel v6 rc2):

```
[IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 280, in process_control
    await result
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 832, in debug_request
    reply_content = json_clean(reply_content)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 142, in json_clean
    out[str(k)] = json_clean(v)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 142, in json_clean
    out[str(k)] = json_clean(v)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 128, in json_clean
    return [json_clean(x) for x in obj]
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 128, in <listcomp>
    return [json_clean(x) for x in obj]
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 142, in json_clean
    out[str(k)] = json_clean(v)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 148, in json_clean
    raise ValueError("Can't clean for JSON: %r" % obj)
ValueError: Can't clean for JSON: <function add at 0x7f1efa2198b0>
```

The tested cell is:

```py
def add(a, b):
    c = a + b
    return c

add(3, 2)
```

with the breakpoint set at `c = a + b`.

That said - the frontend should be resilient to that.

**Comment by fcollonval** [comment]
> xeus-python 0.12.5 does not raise the error.

**Comment by krassowski** [comment]
It looks like this is the root cause of https://github.com/jupyterlab/jupyterlab/issues/16973 too.
