### ISSUE TITLE
ImportError: The Jupyter Server requires tornado >=6.1.0

### ISSUE THREAD

**Issue by ManPython** [jupyterlab/jupyterlab#10529]
## Description
Trying run app
`jupyter lab --ip=127.0.0.1 --port 7777`
I have error, that not have sense, coz exist reqiments
`ImportError: The Jupyter Server requires tornado >=6.1.0`

## Reproduce

Error what I got:

 ```
$ jupyter lab --ip=127.0.0.1 --port 7777
Traceback (most recent call last):
  File "/./.venv/p37/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 53, in <module>
    assert tornado.version_info >= MIN_TORNADO
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/./.venv/p37/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/./.venv/p37/lib/python3.7/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/./.venv/p37/lib/python3.7/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/./.venv/p37/lib/python3.7/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/./.venv/p37/lib/python3.7/site-packages/jupyterlab_server/app.py", line 7, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/./.venv/p37/lib/python3.7/site-packages/jupyter_server/extension/application.py", line 21, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/./.venv/p37/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 57, in <module>
    ) from e
ImportError: The Jupyter Server requires tornado >=6.1.0
(p37) [ManPython@x]:<~>$ pip install --upgrade tornado
Requirement already satisfied: tornado 
```

## Expected behavior
Run jupyterlab

## Context

- Operating System and version: LNX
- Browser and version: FF
- JupyterLab version: 3.0.16

```
Requirement already satisfied: jupyterlab in /./.venv/p37lib/python3.7/site-packages (3.0.16)
Requirement already satisfied: ipython in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (7.25.0)
Requirement already satisfied: jupyterlab-server~=2.3 in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (2.6.0)
Requirement already satisfied: jupyter-server~=1.4 in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (1.9.0)
Requirement already satisfied: nbclassic~=0.2 in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (0.3.1)
Requirement already satisfied: packaging in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (20.9)
Requirement already satisfied: jinja2>=2.1 in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (3.0.1)
Requirement already satisfied: tornado>=6.1.0 in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (6.1)
Requirement already satisfied: jupyter-core in /./.venv/p37lib/python3.7/site-packages (from jupyterlab) (4.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /./.venv/p37lib/python3.7/site-packages (from jinja2>=2.1->jupyterlab) (2.0.1)
Requirement already satisfied: jupyter-client>=6.1.1 in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (6.1.12)
Requirement already satisfied: nbconvert in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (6.1.0)
Requirement already satisfied: websocket-client in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (1.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (5.0.5)
Requirement already satisfied: Send2Trash in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (1.7.1)
Requirement already satisfied: argon2-cffi in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (20.1.0)
Requirement already satisfied: anyio<4,>=3.1.0 in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (3.2.1)
Requirement already satisfied: requests-unixsocket in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (0.2.0)
Requirement already satisfied: pyzmq>=17 in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (22.1.0)
Requirement already satisfied: ipython-genutils in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (0.2.0)
Requirement already satisfied: prometheus-client in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (0.11.0)
Requirement already satisfied: nbformat in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (5.1.3)
Requirement already satisfied: terminado>=0.8.3 in /./.venv/p37lib/python3.7/site-packages (from jupyter-server~=1.4->jupyterlab) (0.10.1)
Requirement already satisfied: idna>=2.8 in /./.venv/p37lib/python3.7/site-packages (from anyio<4,>=3.1.0->jupyter-server~=1.4->jupyterlab) (2.8)
Requirement already satisfied: sniffio>=1.1 in /./.venv/p37lib/python3.7/site-packages (from anyio<4,>=3.1.0->jupyter-server~=1.4->jupyterlab) (1.2.0)
Requirement already satisfied: typing-extensions in /./.venv/p37lib/python3.7/site-packages (from anyio<4,>=3.1.0->jupyter-server~=1.4->jupyterlab) (3.10.0.0)
Requirement already satisfied: python-dateutil>=2.1 in /./.venv/p37lib/python3.7/site-packages (from jupyter-client>=6.1.1->jupyter-server~=1.4->jupyterlab) (2.8.1)
Requirement already satisfied: babel in /./.venv/p37lib/python3.7/site-packages (from jupyterlab-server~=2.3->jupyterlab) (2.9.1)
Requirement already satisfied: requests in /./.venv/p37lib/python3.7/site-packages (from jupyterlab-server~=2.3->jupyterlab) (2.22.0)
Requirement already satisfied: jsonschema>=3.0.1 in /./.venv/p37lib/python3.7/site-packages (from jupyterlab-server~=2.3->jupyterlab) (3.2.0)
Requirement already satisfied: json5 in /./.venv/p37lib/python3.7/site-packages (from jupyterlab-server~=2.3->jupyterlab) (0.9.6)
Requirement already satisfied: importlib-metadata in /./.venv/p37lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab) (2.1.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /./.venv/p37lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /./.venv/p37lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab) (21.2.0)
Requirement already satisfied: six>=1.11.0 in /./.venv/p37lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab) (1.16.0)
Requirement already satisfied: setuptools in /./.venv/p37lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab) (57.0.0)
Requirement already satisfied: notebook<7 in /./.venv/p37lib/python3.7/site-packages (from nbclassic~=0.2->jupyterlab) (6.4.0)
Requirement already satisfied: ipykernel in /./.venv/p37lib/python3.7/site-packages (from notebook<7->nbclassic~=0.2->jupyterlab) (5.5.5)
Requirement already satisfied: ptyprocess in /./.venv/p37lib/python3.7/site-packages (from terminado>=0.8.3->jupyter-server~=1.4->jupyterlab) (0.7.0)
Requirement already satisfied: cffi>=1.0.0 in /./.venv/p37lib/python3.7/site-packages (from argon2-cffi->jupyter-server~=1.4->jupyterlab) (1.14.5)
Requirement already satisfied: pycparser in /./.venv/p37lib/python3.7/site-packages (from cffi>=1.0.0->argon2-cffi->jupyter-server~=1.4->jupyterlab) (2.20)
Requirement already satisfied: pytz>=2015.7 in /./.venv/p37lib/python3.7/site-packages (from babel->jupyterlab-server~=2.3->jupyterlab) (2021.1)
Requirement already satisfied: zipp>=0.5 in /./.venv/p37lib/python3.7/site-packages (from importlib-metadata->jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab) (3.4.1)
Requirement already satisfied: pexpect>4.3 in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (4.8.0)
Requirement already satisfied: pickleshare in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (0.7.5)
Requirement already satisfied: pygments in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (2.9.0)
Requirement already satisfied: decorator in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (5.0.9)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (3.0.19)
Requirement already satisfied: backcall in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (0.18.0)
Requirement already satisfied: matplotlib-inline in /./.venv/p37lib/python3.7/site-packages (from ipython->jupyterlab) (0.1.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /./.venv/p37lib/python3.7/site-packages (from jedi>=0.16->ipython->jupyterlab) (0.8.2)
Requirement already satisfied: wcwidth in /./.venv/p37lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyterlab) (0.2.5)
Requirement already satisfied: mistune<2,>=0.8.1 in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (0.8.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (0.5.3)
Requirement already satisfied: jupyterlab-pygments in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (0.1.2)
Requirement already satisfied: bleach in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (3.3.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (1.4.3)
Requirement already satisfied: defusedxml in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (0.7.1)
Requirement already satisfied: testpath in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (0.5.0)
Requirement already satisfied: entrypoints>=0.2.2 in /./.venv/p37lib/python3.7/site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab) (0.3)
Requirement already satisfied: nest-asyncio in /./.venv/p37lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.4->jupyterlab) (1.5.1)
Requirement already satisfied: async-generator in /./.venv/p37lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.4->jupyterlab) (1.10)
Requirement already satisfied: webencodings in /./.venv/p37lib/python3.7/site-packages (from bleach->nbconvert->jupyter-server~=1.4->jupyterlab) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in /./.venv/p37lib/python3.7/site-packages (from packaging->jupyterlab) (2.4.7)
Requirement already satisfied: certifi>=2017.4.17 in /./.venv/p37lib/python3.7/site-packages (from requests->jupyterlab-server~=2.3->jupyterlab) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /./.venv/p37lib/python3.7/site-packages (from requests->jupyterlab-server~=2.3->jupyterlab) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /./.venv/p37lib/python3.7/site-packages (from requests->jupyterlab-server~=2.3->jupyterlab) (1.25.11)

```
<details><summary>Troubleshoot Output</summary>
<pre>
`jupyter lab --ip=127.0.0.1 --port 7777 --debug` give me this same error like in desctiption
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
`jupyter lab --ip=127.0.0.1 --port 7777 --debug` give me this same error like in desctiption
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Not running on browser due to the error.
</pre>
</details>

**Comment by fcollonval** [comment]
Hey @ManPython could you delete and recreate your virtual environment? It looks like a strange interaction that will be really though and specific to your installation to tackle.

**Comment by ManPython** [comment]
> 
> 
> Hey @ManPython could you delete and recreate your virtual environment? It looks like a strange interaction that will be really though and specific to your installation to tackle.

You mind `/./.venv/p37lib/` not  `/./.venv/p37/lib/` ? It's my mistake of replacing string due long path.

**Comment by ManPython** [comment]
Also I broken more.. 
I uninstalled tornado, and got problem with `ImportError: cannot import name 'gen' from 'tornado' (unknown location)`
Then I copied tornado from other venv.

```
ImportError: The Jupyter Server requires tornado >=6.1.0
$ pip install tornado
Requirement already satisfied: tornado in p37/lib/python3.7/site-packages (6.0.4)
$ pip install tornado --upgrade
Requirement already satisfied: tornado in p37/lib/python3.7/site-packages (6.0.4)
Collecting tornado
  Using cached tornado-6.1-cp37-cp37m-freebsd_12_2_release_p2_amd64.whl
Installing collected packages: tornado
  Attempting uninstall: tornado
    Found existing installation: tornado 6.0.4
    Uninstalling tornado-6.0.4:
      Successfully uninstalled tornado-6.0.4
Successfully installed tornado-6.1
```
Then
```
jupyter lab --ip=127.0.0.1 --port 8989
Traceback (most recent call last):
  File "/./.venv/p37//bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/./.venv/p37//lib/python3.7/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/./.venv/p37//lib/python3.7/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/./.venv/p37//lib/python3.7/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/./.venv/p37//lib/python3.7/site-packages/jupyterlab_server/app.py", line 7, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/./.venv/p37//lib/python3.7/site-packages/jupyter_server/extension/application.py", line 21, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/./.venv/p37//lib/python3.7/site-packages/jupyter_server/serverapp.py", line 77, in <module>
    from jupyter_server.services.kernels.kernelmanager import MappingKernelManager, AsyncMappingKernelManager
  File "/./.venv/p37//lib/python3.7/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 20, in <module>
    from jupyter_client.multikernelmanager import MultiKernelManager, AsyncMultiKernelManager
ImportError: cannot import name 'AsyncMultiKernelManager' from 'jupyter_client.multikernelmanager' (/./.venv/p37//lib/python3.7/site-packages/jupyter_client/multikernelmanager.py)
```
https://github.com/nteract/papermill/issues/486

**Comment by ManPython** [comment]
This issue can be closed I think. Don't know what reason was for this exactly but solved. ;]

**Comment by ChenxiSSS** [comment]
I think it is due to the fact that the `conda` use a lower version of `tornado`, and the virtualenv use a higher version of `tornado`.

**Comment by ManPython** [comment]
If this info can help, I not used Conda, just pure python and pip. The issue is old.
