### ISSUE TITLE
Jupyterlab cannot start

### ISSUE THREAD

**Issue by Leon14451** [jupyterlab/jupyterlab#10576]
When i run `jupyter-lab`, it print strange error, `invalid literal for int() with base 10: 'tcp://172.16.116.62:8888'`, i don't know this ip from where, because it's not my node ip. It's similar to #5385 but not same.

I have reinstalled different versions many times. 3.0.0, 3.0.16, 2.0.0.

This is the whole error i get.

```
# jupyter-lab --debug
[D 2021-07-08 12:54:29.331 ServerApp] Searching ['/data/workhome', '/root/.jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2021-07-08 12:54:29.331 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2021-07-08 12:54:29.331 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2021-07-08 12:54:29.331 ServerApp] Looking for jupyter_config in /root/.jupyter
[D 2021-07-08 12:54:29.331 ServerApp] Looking for jupyter_config in /data/workhome
[D 2021-07-08 12:54:29.332 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2021-07-08 12:54:29.332 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2021-07-08 12:54:29.333 ServerApp] Looking for jupyter_server_config in /root/.jupyter
[D 2021-07-08 12:54:29.333 ServerApp] Looking for jupyter_server_config in /data/workhome
[D 2021-07-08 12:54:29.335 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2021-07-08 12:54:29.335 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /usr/local/etc/jupyter/jupyter_server_config.d/nbclassic.json
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2021-07-08 12:54:29.336 ServerApp] Paths used for configuration of jupyter_server_config: 
        /root/.jupyter/jupyter_server_config.json
[D 2021-07-08 12:54:29.351 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'nbclassic': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2021-07-08 12:54:29.352 ServerApp] jupyterlab | extension was successfully linked.
[D 2021-07-08 12:54:29.362 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'nbclassic': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[W 2021-07-08 12:54:29.365 ServerApp] invalid literal for int() with base 10: 'tcp://172.16.116.62:8888'
[D 2021-07-08 12:54:29.365 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'nbclassic': True}>}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1025, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/usr/local/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'localhost' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'port'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
    serverapp.initialize(
  File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2052, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1578, in init_webapp
    self.web_app = ServerWebApplication(
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 193, in __init__
    settings = self.init_settings(
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 274, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1028, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/usr/local/lib/python3.8/site-packages/traitlets/traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 776, in port_default
    return int(os.getenv(self.port_env, self.port_default_value))
ValueError: invalid literal for int() with base 10: 'tcp://172.16.116.62:8888'
```

**Comment by jasongrout** [comment]
> ValueError: invalid literal for int() with base 10: 'tcp://172.16.116.62:8888'

From this error, it looks like somewhere you have your port being set to a whole address 'tcp://172.16.116.62:8888', instead of something like `8888`. If I were you trying to track down this, I'd search your configuration or try to find out where it is getting `tcp://172.16.116.62:8888`, and why it is trying to set the port to that address.

**Comment by jasongrout** [comment]
As a test, you might try giving the port explicitly with `--port 8888` in the command line. I think this should override whatever config is setting the port to that bad value.

**Comment by Leon14451** [comment]
> As a test, you might try giving the port explicitly with `--port 8888` in the command line. I think this should override whatever config is setting the port to that bad value.

Yes, it works correctly. And also, i'm interested in where my port being set?

The Jupyterlab installs on python official docker image, and no config file exist.

```
# cat /etc/jupyter/jupyter_server_config.json
cat: /etc/jupyter/jupyter_server_config.json: No such file or directory
# cat /usr/local/etc/jupyter/jupyter_server_config.d/jupyterlab.json
{
  "ServerApp": {
    "jpserver_extensions": {
      "jupyterlab": true
    }
  }
}
# cat /usr/local/etc/jupyter/jupyter_server_config.d/nbclassic.json
{
    "ServerApp": {
        "jpserver_extensions": {
            "nbclassic": true
        }
    }
}# cat /usr/local/etc/jupyter/jupyter_server_config.json
cat: /usr/local/etc/jupyter/jupyter_server_config.json: No such file or directory
# cat /root/.jupyter/jupyter_server_config.json
cat: /root/.jupyter/jupyter_server_config.json: No such file or directory

# grep -rn "172.16.116.62" /etc
# grep -rn "172.16.116.62" /usr
# grep -rn "172.16.116.62" /root
# grep -rn "172.16.116.62" /
just some permission error
```

So i confirm `'tcp://172.16.116.62:8888'` not exists in my system files. It should be generated by program? 
Any suggestion is better. I'll keep on debugging.

**Comment by Leon14451** [comment]
New progress, it's not jupyter's fault anyway. Although i'm working on who did this. 

root@jupyter-0:/opt/spark/work-dir# export | grep JUPYTER
declare -x JUPYTER_PORT="tcp://172.16.116.62:8888"
declare -x JUPYTER_PORT_2222_TCP="tcp://172.16.116.62:2222"
declare -x JUPYTER_PORT_2222_TCP_ADDR="172.16.116.62"
declare -x JUPYTER_PORT_2222_TCP_PORT="2222"
declare -x JUPYTER_PORT_2222_TCP_PROTO="tcp"
declare -x JUPYTER_PORT_7777_TCP="tcp://172.16.116.62:7777"
declare -x JUPYTER_PORT_7777_TCP_ADDR="172.16.116.62"
declare -x JUPYTER_PORT_7777_TCP_PORT="7777"
declare -x JUPYTER_PORT_7777_TCP_PROTO="tcp"
declare -x JUPYTER_PORT_8888_TCP="tcp://172.16.116.62:8888"
declare -x JUPYTER_PORT_8888_TCP_ADDR="172.16.116.62"
declare -x JUPYTER_PORT_8888_TCP_PORT="8888"
declare -x JUPYTER_PORT_8888_TCP_PROTO="tcp"
declare -x JUPYTER_SERVICE_HOST="172.16.116.62"
declare -x JUPYTER_SERVICE_PORT="8888"
declare -x JUPYTER_SERVICE_PORT_8844_TCP="tcp://172.16.237.146:8844"
declare -x JUPYTER_SERVICE_PORT_8844_TCP_ADDR="172.16.237.146"
declare -x JUPYTER_SERVICE_PORT_8844_TCP_PORT="8844"
declare -x JUPYTER_SERVICE_PORT_8844_TCP_PROTO="tcp"
declare -x JUPYTER_SERVICE_PORT_8888_TCP="tcp://172.16.237.146:8888"
declare -x JUPYTER_SERVICE_PORT_8888_TCP_ADDR="172.16.237.146"
declare -x JUPYTER_SERVICE_PORT_8888_TCP_PORT="8888"
declare -x JUPYTER_SERVICE_PORT_8888_TCP_PROTO="tcp"
declare -x JUPYTER_SERVICE_PORT_BLOCKMANAGER="7777"
declare -x JUPYTER_SERVICE_PORT_DRIVER="2222"
declare -x JUPYTER_SERVICE_PORT_HTTP="8888"
declare -x JUPYTER_SERVICE_SERVICE_HOST="172.16.237.146"
declare -x JUPYTER_SERVICE_SERVICE_PORT="8888"
declare -x JUPYTER_SERVICE_SERVICE_PORT_DRIVER_PORT="8844"
declare -x JUPYTER_SERVICE_SERVICE_PORT_JUPYTER_PORT="8888"

Maybe my kubernetes provider? Keep working and closing this issue.

**Comment by Leon14451** [comment]
The final truth:
https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables

A service named jupyter exist in the same namespace of my pod on kubernetes.

And thanks, @jasongrout
