### ISSUE TITLE
Question: Can I use jupyterlab services package from nodejs

### ISSUE THREAD

**Issue by idling-mind** [jupyterlab/jupyterlab#10634]
Hi,
  I browsed through the nodejs example [here](https://github.com/jupyterlab/jupyterlab/tree/master/packages/services/examples/node). It uses a python script to start the jupyter notebook server. My question is if it's possible to connect to an already started notebook session from node?

I tried by passing `baseUrl` also as part of the `options`. However, I got the following error.

```
16 Jul 10:19:28 - Error: Can only be used for notebook server requests
    at Object.handleRequest (C:\Users\idling-mind\.node-red\externalModules\node_modules\@jupyterlab\services\lib\serverconnection.js:177:19)
    at Object.makeRequest (C:\Users\idling-mind\.node-red\externalModules\node_modules\@jupyterlab\services\lib\serverconnection.js:77:24)
    at Object.startNew (C:\Users\idling-mind\.node-red\externalModules\node_modules\@jupyterlab\services\lib\kernel\restapi.js:55:64)
    at KernelManager.startNew (C:\Users\idling-mind\.node-red\externalModules\node_modules\@jupyterlab\services\lib\kernel\manager.js:152:39)
```

I am trying to connect [Node-RED](https://nodered.org/) to a jupyter-kernel.

Thanks

**Comment by jasongrout** [comment]
Yes, but the services package assumes it is connecting to a notebook server, not directly to a kernel (not sure which you are trying to do based on your question). You'll need to pass the services manager a serverConnection setting: 
https://github.com/jupyterlab/jupyterlab/blob/0aed1cca194f5724d95c7d7896682eaacb8be925/packages/services/src/basemanager.ts#L101
https://github.com/jupyterlab/jupyterlab/blob/0aed1cca194f5724d95c7d7896682eaacb8be925/packages/services/src/serverconnection.ts#L53
