### ISSUE TITLE
CI broken by jupyter-server v1.10.0

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10682]
## Description

With the publication of jupyter-server v1.10.0, one @jupyterlab/services examples is broken in the CI:

```
****************************************
Starting node test in /home/runner/work/jupyterlab/jupyterlab/packages/services/examples/node
****************************************
Traceback (most recent call last):
  File "/home/runner/work/jupyterlab/jupyterlab/packages/services/examples/node/main.py", line 45, in <module>
    NodeApp.launch_instance()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 525, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 487, in initialize_server
    jpserver_extensions = {cls.get_extension_package(): True}
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 178, in get_extension_package
    if is_namespace_package(parts[0]):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_server/utils.py", line 391, in is_namespace_package
    spec = importlib.util.find_spec(namespace)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: __main__.__spec__ is None
Traceback (most recent call last):
  File "examples/test_examples.py", line 62, in <module>
    main()
  File "examples/test_examples.py", line 49, in main
    subprocess.check_call([sys.executable, runner], cwd=cwd)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.8.11/x64/bin/python', '/home/runner/work/jupyterlab/jupyterlab/packages/services/examples/node/main.py']' returned non-zero exit status 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

Example: https://github.com/jupyterlab/jupyterlab/runs/3141134662?check_suite_focus=true

The PR that introduces the code: https://github.com/jupyter-server/jupyter_server/pull/523

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyter-server/jupyter_server/pull/556
