### ISSUE TITLE
Update to jupyterlab==3.1.0 breaks application installation for jupyterlab-requirements

### ISSUE THREAD

**Issue by pacospace** [jupyterlab/jupyterlab#10716]
## Description

from Pipfile: https://github.com/thoth-station/jupyterlab-requirements/blob/master/Pipfile moved to new jupyterlab 3.1.0, running `jupyter --version`

```
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : not installed
ipython          : 7.25.0
ipykernel        : 6.0.3
jupyter client   : 6.1.12
jupyter lab      : 3.1.0
nbconvert        : 6.1.0
ipywidgets       : not installed
nbformat         : 5.1.3
traitlets        : 5.0.5
```

and update packages.json from https://github.com/thoth-station/jupyterlab-requirements/blob/db8f97eda948d916f4a7abae10e13b60523d3bde/package.json#L54 to:
```
  "dependencies": {
    "@jupyterlab/application": "^3.1.0",
    "@jupyterlab/launcher": "^3.1.0",
    "@jupyterlab/console": "^3.1.0",
    "@jupyterlab/logconsole": "^3.1.0",
    "@jupyterlab/mainmenu": "^3.1.0",
    "@jupyterlab/nbformat": "^3.1.0",
    "@jupyterlab/notebook": "^3.1.0",
    "@jupyterlab/services": "^6.1.0",
    "@jupyterlab/translation": "^3.1.0",
    "@lumino/algorithm": "^1.6.0",
    "@lumino/application": "^1.22.0",
    "@lumino/coreutils": "^1.8.0",
    "@lumino/datagrid": "^0.27.0",
    "@lumino/disposable": "^1.7.0",
    "@lumino/widgets": "^1.19.0",
    "@types/lodash": "^4.14.165",
    "@types/node": "^16.0.0",
    "axios": "^0.21.1",
    "js-logger": "^1.6.1",
    "jupyterlab_toastify": "^4.1.3",
    "yarn-deduplicate": "^3.1.0"
  }
```
## Reproduce

1. Clone jupyterlab-requirements repo: https://github.com/thoth-station/jupyterlab-requirements
2. Update Pipfile with jupyterlab>=3.1.0
3. Run `pipenv install && pipenv shell`
4. Update package.sjon with the changes shown above
5. Run `pip install -ve . --no-cache-dir`

The installation will fail.

## Expected behavior

Installation is successfull as it was before moving to jupyterlab 3.1.0

## Context

- Operating System and version: Fedora 33 python 3.8
- Browser and version: Chrome
- JupyterLab version: 3.1.0

<details><summary>Command Line Output</summary>
<pre>
   > jlpm install
    yarn install v1.21.1
    [1/4] Resolving packages...
    warning @jupyterlab/builder > @jupyterlab/buildutils > verdaccio > request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
    warning @jupyterlab/builder > @jupyterlab/buildutils > npm-cli-login > npm-registry-client > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning @jupyterlab/builder > @jupyterlab/buildutils > verdaccio > verdaccio-audit > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning @jupyterlab/builder > @jupyterlab/buildutils > verdaccio > @verdaccio/readme > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning @jupyterlab/builder > @jupyterlab/buildutils > verdaccio > request > har-validator@5.1.5: this library is no longer supported
    warning @jupyterlab/builder > @jupyterlab/buildutils > verdaccio > @verdaccio/readme > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
    [2/4] Fetching packages...
    info fsevents@2.3.2: The platform "linux" is incompatible with this module.
    info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning "@jupyterlab/application > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
    warning "@jupyterlab/application > @jupyterlab/ui-components@3.1.0" has unmet peer dependency "react@^17.0.1".
    warning " > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
    warning " > jupyterlab_toastify@4.1.3" has unmet peer dependency "react@^16.0.0 || ^17.0.0".
    warning " > jupyterlab_toastify@4.1.3" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
    warning "jupyterlab_toastify > @fortawesome/react-fontawesome@0.1.14" has unmet peer dependency "react@>=16.x".
    warning "jupyterlab_toastify > react-toastify@6.2.0" has unmet peer dependency "react@>=16".
    warning "jupyterlab_toastify > react-toastify > react-transition-group@4.4.1" has unmet peer dependency "react@>=16.6.0".
    warning "jupyterlab_toastify > react-toastify > react-transition-group@4.4.1" has unmet peer dependency "react-dom@>=16.6.0".
    warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0" has unmet peer dependency "typanion@*".
    warning "@jupyterlab/builder > @jupyterlab/buildutils > npm-cli-login > snyk > @snyk/snyk-cocoapods-plugin > @snyk/cli-interface@2.11.1" has incorrect peer dependency "@snyk/dep-graph@1.19.2".
    warning "@jupyterlab/builder > @jupyterlab/buildutils > npm-cli-login > snyk > @snyk/snyk-cocoapods-plugin > @snyk/cli-interface@2.11.1" has incorrect peer dependency "@snyk/graphlib@2.1.9-patch".
    warning "@jupyterlab/builder > @jupyterlab/buildutils > npm-cli-login > snyk > @snyk/snyk-cocoapods-plugin > @snyk/cli-interface@2.11.1" has incorrect peer dependency "tslib@^1.9.3".
    warning " > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
    warning " > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
    warning Workspaces can only be enabled in private projects.
    warning Workspaces can only be enabled in private projects.
    warning Workspaces can only be enabled in private projects.
    [4/4] Building fresh packages...
    success Saved lockfile.
    $ jlpm run clean && jlpm run build:prod
    yarn run v1.21.1
    $ jlpm run clean:lib
    $ rimraf lib tsconfig.tsbuildinfo
    Done in 1.31s.
    yarn run v1.21.1
    $ jlpm run build:lib && jlpm run build:labextension
    $ tsc
    node_modules/@jupyterlab/application/lib/frontend.d.ts(31,167): error TS2344: Type 'T' does not satisfy the constraint 'Widget'.
      Type 'IShell' is not assignable to type 'Widget'.
        The types of 'title.owner.layout.removeWidget' are incompatible between these types.
          Type '(widget: import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/widget").Widget) => void' is not assignable to type '(widget: import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/widget").Widget) => void'.
            Types of parameters 'widget' and 'widget' are incompatible.
              Type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/widget").Widget' is not assignable to type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/widget").Widget'.
                Types of property 'title' are incompatible.
                  Type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/title").Title<import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/widget").Widget>' is not assignable to type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/title").Title<import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/widget").Widget>'.
                    Types have separate declarations of a private property '_label'.
    node_modules/@jupyterlab/application/lib/frontend.d.ts(55,14): error TS2416: Property 'contextMenu' in type 'JupyterFrontEnd<T, U>' is not assignable to the same property in base type 'Application<T>'.
      Type 'ContextMenuSvg' is missing the following properties from type 'ContextMenu': _groupByTarget, _sortBySelector
    node_modules/@jupyterlab/application/lib/frontend.d.ts(103,89): error TS2344: Type 'T' does not satisfy the constraint 'Widget'.
      Type 'IShell' is not assignable to type 'Widget'.
        Types of property 'title' are incompatible.
          Type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/title").Title<import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/widget").Widget>' is not assignable to type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/title").Title<import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/widget").Widget>'.
    src/index.ts(51,5): error TS2322: Type 'Token<ICommandPalette>' is not assignable to type 'Token<any>'.
      Types have separate declarations of a private property '_tokenStructuralPropertyT'.
    src/index.ts(52,5): error TS2322: Type 'Token<IMainMenu>' is not assignable to type 'Token<any>'.
      Types have separate declarations of a private property '_tokenStructuralPropertyT'.
    src/index.ts(53,5): error TS2322: Type 'Token<INotebookTracker>' is not assignable to type 'Token<any>'.
      Types have separate declarations of a private property '_tokenStructuralPropertyT'.
    src/index.ts(181,43): error TS2322: Type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/commands/types/index").CommandRegistry' is not assignable to type 'import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/commands/types/index").CommandRegistry'.
      Types have separate declarations of a private property '_startTimer'.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/fmurdaca/work/aicoe/jupyterlab-requirements/setup.py", line 113, in <module>
        setuptools.setup(**setup_args)
      File "/tmp/pip-build-env-umvq3u0k/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-umvq3u0k/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in run
        [self.run_command(cmd) for cmd in cmds]
      File "/tmp/pip-build-env-umvq3u0k/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-umvq3u0k/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 274, in run
        c.run()
      File "/tmp/pip-build-env-umvq3u0k/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 379, in run
        run(npm_cmd + ['install'], cwd=node_package)
      File "/tmp/pip-build-env-umvq3u0k/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 225, in run
        return subprocess.check_call(cmd, **kwargs)
      File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-env-umvq3u0k/overlay/bin/jlpm', 'install']' returned non-zero exit status 1.
ERROR: Command errored out with exit status 1: /home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/fmurdaca/work/aicoe/jupyterlab-requirements/setup.py'"'"'; __file__='"'"'/home/fmurdaca/work/aicoe/jupyterlab-requirements/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 393, in run
    installed = install_given_reqs(
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 77, in install_given_reqs
    requirement.install(
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 763, in install
    install_editable_legacy(
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/pip/_internal/operations/install/editable_legacy.py", line 44, in install_editable
    call_subprocess(
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/fmurdaca/work/aicoe/jupyterlab-requirements/setup.py'"'"'; __file__='"'"'/home/fmurdaca/work/aicoe/jupyterlab-requirements/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-8e2mt5l6'
</pre>
</details>

**Comment by fcollonval** [comment]
Hey @pacospace 

Yarn is not solving the @lumino/widgets module correctly and you end up with a subversion used by `@lumino/application` and by the root common packages.

```
/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/widget").Widget) => void' is not assignable to type '(widget: import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/widget
```

I suggest you update the `@lumino` dependencies too.

> You should be able to do so with `yarn upgrade --scope @lumino`

> Side comment: at first look it is strange to have `@types/*` and `yarn-deduplicate` packages as dependencies. They probably belong to _devDependencies_.

**Comment by pacospace** [comment]
> Hey @pacospace
> 
> Yarn is not solving the @lumino/widgets module correctly and you end up with a subversion used by `@lumino/application` and by the root common packages.
> 
> ```
> /home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/widgets/types/widget").Widget) => void' is not assignable to type '(widget: import("/home/fmurdaca/work/aicoe/jupyterlab-requirements/node_modules/@lumino/application/node_modules/@lumino/widgets/types/widget
> ```
> 
> I suggest you update the `@lumino` dependencies too.
> 
> > You should be able to do so with `yarn upgrade --scope @lumino`
> 
> > Side comment: at first look it is strange to have `@types/*` and `yarn-deduplicate` packages as dependencies. They probably belong to _devDependencies_.

Thanks @fcollonval removed some unusued @lumino libraries and updating @lumino/widgets to latest did the trick! Thank you a lot!
