### ISSUE TITLE
Toolbar error when opening the file editor on 4.0.0a4

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10872]
## Description

There are issues on master relating to toolbar, which might be the root cause of the https://github.com/jupyterlab/jupyterlab/pull/10868#issuecomment-901369268

## Reproduce

1. Open a new empty file editor
2. Open console
3. See error in the console:

```
index.ts:863 Uncaught TypeError: extender[label] is not a function
    at Object.delegateLabel (index.ts:863)
    at caption (index.ts:648)
    at CommandRegistry.caption (index.es6.js:242)
    at Object.propsFromCommand (toolbar.tsx:863)
    at Object.children (toolbar.tsx:659)
    at UseSignal.render (vdom.ts:256)
    at finishClassComponent (react-dom.development.js:17485)
    at updateClassComponent (react-dom.development.js:17435)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
delegateLabel @ index.ts:863
caption @ index.ts:648
CommandRegistry.caption @ index.es6.js:242
propsFromCommand @ toolbar.tsx:863
(anonymous) @ toolbar.tsx:659
render @ vdom.ts:256
finishClassComponent @ react-dom.development.js:17485
updateClassComponent @ react-dom.development.js:17435
beginWork @ react-dom.development.js:19073
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22779
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
Component.setState @ react.development.js:365
UseSignal.slot @ vdom.ts:252
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
CommandRegistry.notifyCommandChanged @ index.es6.js:147
(anonymous) @ index.tsx:491
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
(anonymous) @ shell.ts:1416
(anonymous) @ index.es6.js:519
step @ index.es6.js:75
(anonymous) @ index.es6.js:56
(anonymous) @ index.es6.js:49
__awaiter @ index.es6.js:45
factory @ index.es6.js:517
Poll._execute @ index.es6.js:371
execute @ index.es6.js:310
requestAnimationFrame (async)
(anonymous) @ index.es6.js:314
step @ index.es6.js:75
(anonymous) @ index.es6.js:56
fulfilled @ index.es6.js:46
Promise.then (async)
step @ index.es6.js:48
(anonymous) @ index.es6.js:49
__awaiter @ index.es6.js:45
Poll.schedule @ index.es6.js:274
Debouncer.invoke @ index.es6.js:592
_onLayoutModified @ shell.ts:1377
_onCurrentChanged @ shell.ts:1360
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
FocusTracker._setWidgets @ index.es6.js:12514
FocusTracker._evtFocus @ index.es6.js:12532
FocusTracker.handleEvent @ index.es6.js:12495
_focusContent @ mainareawidget.ts:245
onActivateRequest @ mainareawidget.ts:166
Widget.processMessage @ index.es6.js:1401
invokeHandler @ index.es6.js:442
sendMessage @ index.es6.js:187
runMessageLoop @ index.es6.js:492
requestAnimationFrame (async)
enqueueMessage @ index.es6.js:461
postMessage @ index.es6.js:229
Widget.update @ index.es6.js:1209
set @ index.es6.js:8244
TabBar._evtMouseDown @ index.es6.js:8722
TabBar.handleEvent @ index.es6.js:8540
Show 13 more frames
react-dom.development.js:20085 The above error occurred in the <UseSignal> component:

    at UseSignal (http://localhost:8854/static/lab/packages_ui-components_lib_index_js.01e719bc4f74d236be47.js:3037:9)
    at CommandToolbarButtonComponent (http://localhost:8854/static/lab/packages_ui-components_lib_index_js.01e719bc4f74d236be47.js:2636:125)
```

![Screenshot from 2021-08-18 20-27-42](https://user-images.githubusercontent.com/5832902/129960372-043cd270-846c-4ced-bf9a-a783c4028952.png)

## Expected behavior

No errors.

## Context

- Browser and version: Chrome 92
- JupyterLab version: 4.0.0a4

**Comment by krassowski** [comment]
CC @fcollonval

**Comment by fcollonval** [comment]
The modification in the toolbar generation, creates an asynchronous race that can result it that error.

**Comment by fcollonval** [comment]
Running with a break point on the `extender[label]` line don't raise that error but others from bad react update call:

![image](https://user-images.githubusercontent.com/8435071/131498322-5265020b-6346-40cd-9c9b-2d6ec2d0106d.png)
