### ISSUE TITLE
Cannot open the cloned notebook (File Load Error for <filename.ipynb> Unhandled error)

### ISSUE THREAD

**Issue by wanburana** [jupyterlab/jupyterlab#10892]
## Description

When I tried to open the clone notebook, this happened
![image](https://user-images.githubusercontent.com/66191669/130429054-40367e73-0a2d-4120-9f1e-16303ddfff7b.png)

When I looked at my command line, this error show up

```
    Traceback (most recent call last):
      File "C:\Users\msi\Anaconda3\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\handlers.py", line 248, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\manager.py", line 520, in create_checkpoint
        return self.checkpoints.create_checkpoint(self, path)
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\filecheckpoints.py", line 59, in create_checkpoint
        self._copy(src_path, dest_path)
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\fileio.py", line 245, in _copy
        copy2_safe(src, dest, log=self.log)
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\fileio.py", line 47, in copy2_safe
        shutil.copyfile(src, dst)
      File "C:\Users\msi\Anaconda3\lib\shutil.py", line 261, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\msi\\My study\\AIT Coursework\\AT82.01 Computer Programming for Data Science and Artificial Intelligence\\Python-for-DS-AI\\Lectures\\02-MLScratch\\03-Naive Bayesian\\.ipynb_checkpoints\\01 - Supervised Learning - Classification - Naive Bayesian - Gaussian-checkpoint.ipynb'
[W 2021-08-23 17:00:07.499 ServerApp] Unhandled error
```
It  worked perfectly when I import it to Colab, so the notebook file is not corrupted.

I still don't understand what is the problem, not having a checkpoint file shouldnt be the problem in the first place.

## Expected behavior
Notebook opened successfully

<details><summary>Command Line Output</summary>
<pre>
    Traceback (most recent call last):
      File "C:\Users\msi\Anaconda3\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\handlers.py", line 248, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\manager.py", line 520, in create_checkpoint
        return self.checkpoints.create_checkpoint(self, path)
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\filecheckpoints.py", line 59, in create_checkpoint
        self._copy(src_path, dest_path)
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\fileio.py", line 245, in _copy
        copy2_safe(src, dest, log=self.log)
      File "C:\Users\msi\Anaconda3\lib\site-packages\jupyter_server\services\contents\fileio.py", line 47, in copy2_safe
        shutil.copyfile(src, dst)
      File "C:\Users\msi\Anaconda3\lib\shutil.py", line 261, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\msi\\My study\\AIT Coursework\\AT82.01 Computer Programming for Data Science and Artificial Intelligence\\Python-for-DS-AI\\Lectures\\02-MLScratch\\03-Naive Bayesian\\.ipynb_checkpoints\\01 - Supervised Learning - Classification - Naive Bayesian - Gaussian-checkpoint.ipynb'
[W 2021-08-23 17:00:07.499 ServerApp] Unhandled error
</pre>
</details>

**Comment by wanburana** [comment]
solved, the problem is too long filepath, renaming some folder solve the issue
