### ISSUE TITLE
A problem with the new version

### ISSUE THREAD

**Issue by liaoran** [jupyterlab/jupyterlab#10960]
Jupyterlab version: 3.1.9
Python version: 3.8.11
OS: Ubuntu 20.04.02
Question: 
When I use jupyter lab, it gives me an error, the information is as follows:
```
Traceback (most recent call last):
  File "/home/programmer/anaconda3/envs/rapids/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/home/programmer/anaconda3/envs/rapids/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/home/programmer/anaconda3/envs/rapids/lib/python3.8/site-packages/jupyterlab/labapp.py", line 19, in <module>
    from nbclassic.shim import NBClassicConfigShimMixin
  File "/home/programmer/anaconda3/envs/rapids/lib/python3.8/site-packages/nbclassic/__init__.py", line 1, in <module>
    from .notebookapp import NotebookApp
  File "/home/programmer/anaconda3/envs/rapids/lib/python3.8/site-packages/nbclassic/notebookapp.py", line 45, in <module>
    from jupyter_server.transutils import _i18n
ImportError: cannot import name '_i18n' from 'jupyter_server.transutils' (/home/programmer/anaconda3/envs/rapids/lib/python3.8/site-packages/jupyter_server/transutils.py)
```

**Comment by liaoran** [comment]
I passed conda install -c coda-forge jupyterlab, and there was no problem at startup.
