### ISSUE TITLE
Rendering on "special variables" and "function variables" should not be possible/break the debugger

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#11009]
## Description

The new variable renderer for the debugger should not show when hovering over "special variables" or "function variables".
Clicking on "function variables" leads to a traceback in xeus-kernel, while clicking on "special variables" freezes the GUI

## Reproduce

1. Open JupyterLab 4.0a
2. Activate the debugger
3. Set a breakpoint and run the cell with the breakpoint
4. See that  the button for "rendering" is visible for special categories "special variables" and "function variables" and not only the actual variables

![Screenshot from 2021-09-04 12-55-06](https://user-images.githubusercontent.com/5832902/132093749-40275060-7fbe-4e5d-9547-e8e5ba7e5371.png)

## Expected behavior

- do not show the loop icon on hover over "special variables" and "function variables"
- kernels should do some sanity check on the variables to avoid syntax errors

## Context

- JupyterLab version: 4.0.0a7

```
Error processing internal command.
Traceback (most recent call last):
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 419, in evaluate_expression
    compiled = compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    function variables_repr_data,function variables_repr_metada = (get_ipython().display_formatter.format(function variables))
             ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 1676, in process_internal_commands
    int_cmd.do_it(self)
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 542, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1331, in internal_set_expression_json
    result = pydevd_vars.evaluate_expression(py_db, frame, exec_code, is_exec=True)
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 371, in new_func
    return _run_with_unblock_threads(original_func, py_db, curr_thread, frame, expression, is_exec)
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 339, in _run_with_unblock_threads
    return _run_with_interrupt_thread(original_func, py_db, curr_thread, frame, expression, is_exec)
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 310, in _run_with_interrupt_thread
    return original_func(py_db, frame, expression, is_exec)
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 421, in evaluate_expression
    Exec(_expression_to_evaluate(expression), updated_globals, frame.f_locals)
  File "/home/krassowski/miniconda3/envs/xeus-python/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 1
    function variables_repr_data,function variables_repr_metada = (get_ipython().display_formatter.format(function variables))
             ^
SyntaxError: invalid syntax
```

**Comment by krassowski** [comment]
Related: rendering of lists is now broken on master

![broken-rendering-of-lists-2](https://user-images.githubusercontent.com/5832902/132093843-9ef54969-2d8c-49a2-adf0-ccc3eed20d94.gif)
