### ISSUE TITLE
Classic Notebook 'Tree' View Not Spawning Terminals

### ISSUE THREAD

**Issue by tonybutzer** [jupyterlab/jupyterlab#11495]
## Description

I can run linux terminals from jupyter lab - but when using the pulldown from classic tree view - the terminal DOES NOT spawn = I get this stack trace:

```
TypeError: initialize() missing 1 required positional argument: 'name'
ServerApp - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/http1connection.py", line 273, in _read_message
    delegate.finish()
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/routing.py", line 268, in finish
    self.delegate.finish()
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/web.py", line 2290, in finish
    self.execute()
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/web.py", line 2309, in execute
    self.handler = self.handler_class(
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/web.py", line 233, in __init__
    self.initialize(**kwargs)  # type: ignore
TypeError: initialize() missing 1 required positional argument: 'name'
```

## Reproduce

0. Start jupyter lab - connect with firefox or google chrome - connect like
1. http://10.12.69.13:8888/tree
1. Go to new terminal
2. no joy :-(

## Expected behavior

I expected a terminal in linux amazon linux specifically

## Context

- Operating System and version: 
```
(base) ec2-user@ip-10-12-69-13:~$ uname -a
Linux ip-10-12-69-13.us-west-2.compute.internal 4.14.252-195.483.amzn2.x86_64 #1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(base) ec2-user@ip-10-12-69-13:~$ cat /etc/*ele*
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
cpe:2.3:o:amazon:amazon_linux:2
(base) ec2-user@ip-10-12-69-13:~$
```
- Browser and version: 
- JupyterLab version: 
- I am using JupyterLab version **3.2.4**

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2021-11-18 15:07:05.422 ServerApp] New terminal with automatic name: 7
ServerApp - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/http1connection.py", line 273, in _read_message
    delegate.finish()
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/routing.py", line 268, in finish
    self.delegate.finish()
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/web.py", line 2290, in finish
    self.execute()
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/web.py", line 2309, in execute
    self.handler = self.handler_class(
  File "/home/ec2-user/miniconda3/envs/tony/lib/python3.9/site-packages/tornado/web.py", line 233, in __init__
    self.initialize(**kwargs)  # type: ignore
TypeError: initialize() missing 1 required positional argument: 'name'

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
The `/tree` endpoint is provided by [nbclassic](https://github.com/jupyterlab/nbclassic) not jupyterlab. The error you get suggests that you have an incompatible version of tornado installed. What is the result of running `pip check` in your environment? What is the version of nbclassic? What is the version of tornado?

You may also have conflicting versions of jupyterlab/nbclassic installed in the conda environment and outside of it. More information such as the troubleshoot for which the bug issue templates asks would be needed to have a better guess on what went wrong with your installation.
