### ISSUE TITLE
Infinite loop of errors happening sporadically

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyterlab#11498]
## Description

When running a dev build of JupyterLab's master branch locally with `jupyter lab --dev-mode --collaborative`, I sometimes get a never ending error stack:

```
index.es6.js:142 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at Object.scrollIntoViewIfNeeded (index.es6.js:142)
    at render.tsx:278
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushPassiveEffects (react-dom.development.js:23447)
scrollIntoViewIfNeeded @ index.es6.js:142
(anonymous) @ render.tsx:278
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
updateContainer @ react-dom.development.js:25482
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26037
render @ react-dom.development.js:26103
(anonymous) @ vdom.ts:80
renderDOM @ vdom.ts:73
onUpdateRequest @ vdom.ts:48
Widget.processMessage @ index.es6.js:1355
invokeHandler @ index.es6.js:444
sendMessage @ index.es6.js:180
runMessageLoop @ index.es6.js:495
requestAnimationFrame (async)
enqueueMessage @ index.es6.js:463
postMessage @ index.es6.js:231
Widget.update @ index.es6.js:1211
TabBar._onTitleChanged @ index.es6.js:9106
invokeSlot @ index.es6.js:461
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
set @ index.es6.js:822
_onCurrentChanged @ shell.ts:1418
invokeSlot @ index.es6.js:461
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
FocusTracker._setWidgets @ index.es6.js:12600
FocusTracker._evtFocus @ index.es6.js:12618
FocusTracker.handleEvent @ index.es6.js:12581
onAfterDetach @ dialog.tsx:259
Widget.processMessage @ index.es6.js:1399
invokeHandler @ index.es6.js:444
sendMessage @ index.es6.js:180
detach @ index.es6.js:1792
Widget.dispose @ index.es6.js:929
dispose @ dialog.tsx:139
_resolve @ dialog.tsx:414
resolve @ dialog.tsx:182
_evtClick @ dialog.tsx:292
handleEvent @ dialog.tsx:214
react-dom.development.js:20085 The above error occurred in the <NotebookHeading> component:

    at NotebookHeading (http://localhost:8888/static/lab/packages_toc_lib_index_js.4c0b1e16250dfe57aef5.js:1898:56)
    at li
    at TOCItem (http://localhost:8888/static/lab/packages_toc_lib_index_js.4c0b1e16250dfe57aef5.js:2903:1)
    at ul
    at div
    at TOCTree (http://localhost:8888/static/lab/packages_toc_lib_index_js.4c0b1e16250dfe57aef5.js:2961:1)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
updateContainer @ react-dom.development.js:25482
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26037
render @ react-dom.development.js:26103
(anonymous) @ vdom.ts:80
renderDOM @ vdom.ts:73
onUpdateRequest @ vdom.ts:48
Widget.processMessage @ index.es6.js:1355
invokeHandler @ index.es6.js:444
sendMessage @ index.es6.js:180
runMessageLoop @ index.es6.js:495
requestAnimationFrame (async)
enqueueMessage @ index.es6.js:463
postMessage @ index.es6.js:231
Widget.update @ index.es6.js:1211
TabBar._onTitleChanged @ index.es6.js:9106
invokeSlot @ index.es6.js:461
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
set @ index.es6.js:822
_onCurrentChanged @ shell.ts:1418
invokeSlot @ index.es6.js:461
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
FocusTracker._setWidgets @ index.es6.js:12600
FocusTracker._evtFocus @ index.es6.js:12618
FocusTracker.handleEvent @ index.es6.js:12581
onAfterDetach @ dialog.tsx:259
Widget.processMessage @ index.es6.js:1399
invokeHandler @ index.es6.js:444
sendMessage @ index.es6.js:180
detach @ index.es6.js:1792
Widget.dispose @ index.es6.js:929
dispose @ dialog.tsx:139
_resolve @ dialog.tsx:414
resolve @ dialog.tsx:182
_evtClick @ dialog.tsx:292
handleEvent @ dialog.tsx:214
react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at Toolbar (http://localhost:8888/static/lab/packages_toc_lib_index_js.4c0b1e16250dfe57aef5.js:2294:13)
    at div
    at TOCTree (http://localhost:8888/static/lab/packages_toc_lib_index_js.4c0b1e16250dfe57aef5.js:2961:1)
```

The error shows up again and again until my browser tab eventually crashes.

The error seems to show up because `props.area` is `null` here: https://github.com/jupyterlab/jupyterlab/blob/master/packages/toc/src/generators/notebook/render.tsx#L279

Maybe because the queryselector did not find anything here? https://github.com/jupyterlab/jupyterlab/blob/master/packages/toc/src/generators/notebook/render.tsx#L102

## Reproduce

I am not sure how to reproduce it. It seems to happen randomly.

## Expected behavior

No error

## Context

- Operating System and version: Fedora Linux 35 
- Browser and version: Chromium: 95.0.4638.69 (Official Build) (64-bit) 
- JupyterLab version: master 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by martinRenou** [comment]
This has been fixed by https://github.com/jupyterlab/jupyterlab/pull/11356
