### ISSUE TITLE
Document more conda-forge dependencies for development on a clean system

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#11616]
## Description

On a fresh macOS system (m1, Monterey), I have to install the following conda-forge packages to set up a development environment, so that `pip install -ve .` does not install any new python packages via pip and so that the initial build completes:

`micromamba create -n devjlab jupyterlab_server notebook yarn pango pkg-config glib`

I'm not sure if this is documented anywhere how to get a dev environment from a fresh system, but I wanted to at least make an issue about it.

## Reproduce

1.  Run `pip install -ve .` from a fresh jlab checkout on a new macos system.

## Expected behavior

[Instructions for setting up a new development environment](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#setting-up-a-local-development-environment) may mention these other dependencies needed on a clean system.

## Context

- Operating System and version: MacOS Monterey
- JupyterLab version: 4.0 prerelease (current master)

**Comment by 3coins** [comment]
Installing `yarn` with `conda` ends up adding node v17 which fails to build the project (`jlpm run build`). 
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/Users/piyushjain/jupyterlab-test/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.update (/Users/piyushjain/jupyterlab-test/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/Users/piyushjain/jupyterlab-test/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (/Users/piyushjain/jupyterlab-test/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/Users/piyushjain/jupyterlab-test/node_modules/webpack/lib/NormalModule.js:954:10)
    at /Users/piyushjain/jupyterlab-test/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/Users/piyushjain/jupyterlab-test/node_modules/webpack/lib/NormalModule.js:763:11)
    at /Users/piyushjain/jupyterlab-test/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```
Make sure you have latest patched node (>=14 <=16) installed either directly or via [NVM](https://github.com/nvm-sh/nvm#installing-and-updating). Also, I did not find the need for `jupyterlab_server` and `notebook` as they were installed with the source install.

This is what worked for me:
```sh
conda create -n jlab pango pkg-config glib
```
