### ISSUE TITLE
3.2.8: sphinx fails on rendering man page

### ISSUE THREAD

**Issue by kloczek** [jupyterlab/jupyterlab#11893]
## Description
Looks like it is some issue with rendering man page.

## Reproduce
Run `/usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx` in source tree root.

## Expected behavior
man page should be generated

## Context
sphinx 4.3.2

Here is the output of the rendering man page:
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.2
making output directory... done
Building jupyterlab API docs
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > typedoc@0.21.2" has unmet peer dependency "typescript@4.0.x || 4.1.x || 4.2.x || 4.3.x".
warning " > @jupyterlab/ui-components@3.2.8" has unmet peer dependency "react@^17.0.1".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/example-federated-middle > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/codemirror > y-codemirror@3.0.1" has unmet peer dependency "yjs@^13.5.17".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/ui-components > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/galata > svgo-loader@2.2.2" has unmet peer dependency "svgo@^1.0.0".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0-rc.12" has unmet peer dependency "typanion@*".
warning "workspace-aggregator-f00ed2f8-f89f-4e22-baac-856bdc31498a > @jupyterlab/ui-components > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
$ node scripts/ensure-buildutils.js

> @jupyterlab/buildutils@3.2.8 clean
> rimraf lib && rimraf tsconfig.tsbuildinfo


> @jupyterlab/buildutils@3.2.8 build
> tsc


> @jupyterlab/builder@3.2.8 clean
> rimraf lib && rimraf tsconfig.tsbuildinfo


> @jupyterlab/builder@3.2.8 build
> tsc

Done in 54.49s.
yarn run v1.21.1
$ cd packages/metapackage && jlpm run build
/bin/sh: line 1: jlpm: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exception occurred:
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', '/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.2.8/docs/source/../../jupyterlab/staging/yarn.js', 'build:packages']' returned non-zero exit status 127.
The full traceback has been saved in /tmp/sphinx-err-x_yx4qye.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@ss-desktop SPECS]$ cat /tmp/sphinx-err-x_yx4qye.log
# Sphinx version: 4.3.2
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 169, in run
    app = Sphinx(self.source_dir, self.config_dir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 251, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.2.8/docs/source/conf.py", line 279, in setup
    build_api_docs(app.outdir)
  File "/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.2.8/docs/source/conf.py", line 120, in build_api_docs
    check_call(jlpm + ["build:packages"], cwd=root)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', '/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.2.8/docs/source/../../jupyterlab/staging/yarn.js', 'build:packages']' returned non-zero exit status 127.
```

**Comment by kloczek** [comment]
Closing as https://github.com/jupyterlab/jupyterlab/issues/12151 better describes issue.

**Comment by kloczek** [comment]
That still does not provide any solution for typical packagin procedure.
