### ISSUE TITLE
Comment option for CSVTable

### ISSUE THREAD

**Issue by barronh** [jupyterlab/jupyterlab#11902]
### Problem

When opening a CSV file in CSVTable, there is no option for a "comment character." Comments are common in scientific datasets where metadata about columns are important and has no natural place in a CSV. When comments are at the beginning of a file, CSVTable creates one big line for each row.

This is related to #8876, but not identical. In #8876, the number of columns changes between rows. In this case, the number of columns might be constant but is not appropriately diagnosed from any row preceded by a comment character.

A comment character could defer "first line" assessment of the number of columns.

Below is an example dataset that would open as a single column.

```
# This file is an arbitrary dataset to illustrate the problem
# The units of value are micrograms/m**3
date,lon,lat,value
2020-01-01 00:00:00Z,-97.0,40,5.00
2020-01-01 01:00:00Z,-97.0,40,6.00
```

Ideally, the columns would be based on the first line that did not start with a `#`.

The solution to #8876 would likely address many instances here, but perhaps not all.

### Proposed Solution

I propose adding a Comment option in addition to the Delimiter option. The default could be `#` or None. If None, standard parsing would occur. When set, the CSV would be reparsed ignoring comment lines when diagnosing columns.

Comment lines should still be shown; just not be used to parse the file.

### Additional context

Many CSV parsers have this capability include pandas, which allows for a comment character.

Thanks to anyone willing to take this on!

**Comment by kush-ptl** [comment]
Hi, @mchhatwal and I would like to work on this issue.

**Comment by krassowski** [comment]
@kush-ptl please feel welcome to work on this issue. Please open a pull request against the master branch with proposed changes when ready (or earlier if you would like to receive early feedback - you can use [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/)). We have [contributing guidelines](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html) in our documentation.

**Comment by mchhatwal** [comment]
@krassowski We are currently attempting to launch Jupyter Lab in dev mode but are being met with Error 500: Internal Server Error consistently. Below is an example of the error produced. For reference, jupyter lab's extensions seem to be loading fine before the error is produced.

```
[I 2022-04-19 19:33:09.645 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-04-19 19:33:09.663 ServerApp] nbclassic | extension was successfully linked.
[I 2022-04-19 19:33:10.138 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-04-19 19:33:10.194 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-04-19 19:33:10.195 LabApp] Running JupyterLab in dev mode
[I 2022-04-19 19:33:10.195 LabApp] JupyterLab extension loaded from /Users/meharc/Desktop/jupyterlab/jupyterlab
[I 2022-04-19 19:33:10.195 LabApp] JupyterLab application directory is /Users/meharc/Desktop/jupyterlab/dev_mode
[I 2022-04-19 19:33:22.703 LabApp] You're running JupyterLab from source.
    If you're working on the TypeScript sources of JupyterLab, try running
    
        jupyter lab --dev-mode --watch
    
    
    to have the system incrementally watch and build JupyterLab for you, as you
    make changes.
    
[I 2022-04-19 19:33:22.711 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-04-19 19:33:22.726 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-04-19 19:33:22.728 ServerApp] Serving notebooks from local directory: /Users/meharc/Desktop/jupyterlab
[I 2022-04-19 19:33:22.728 ServerApp] Jupyter Server 1.16.0 is running at:
[I 2022-04-19 19:33:22.728 ServerApp] http://localhost:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
[I 2022-04-19 19:33:22.728 ServerApp]  or http://127.0.0.1:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
[I 2022-04-19 19:33:22.728 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-04-19 19:33:22.739 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/meharc/Library/Jupyter/runtime/jpserver-29761-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
     or http://127.0.0.1:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
[E 2022-04-19 19:33:24.474 ServerApp] Uncaught exception GET /lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_server/extension/handler.py", line 15, in get_template
        return self.settings[env].get_template(name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/environment.py", line 1000, in get_template
        return self._load_template(name, globals)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/environment.py", line 959, in _load_template
        template = self.loader.load(self, name, self.make_globals(globals))
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: index.html
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tornado/web.py", line 1878, in wrapper
        return method(self, *args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyterlab_server/handlers.py", line 158, in get
        tpl = self.render_template("index.html", page_config=page_config)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 525, in render_template
        template = self.get_template(name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_server/extension/handler.py", line 17, in get_template
        return super().get_template(name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 521, in get_template
        return self.settings["jinja2_env"].get_template(name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/environment.py", line 1000, in get_template
        return self._load_template(name, globals)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/environment.py", line 959, in _load_template
        template = self.loader.load(self, name, self.make_globals(globals))
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: index.html
[E 2022-04-19 19:33:24.546 ServerApp] Could not open static file ''
[E 2022-04-19 19:33:24.550 LabApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
    }
[E 2022-04-19 19:33:24.642 LabApp] 500 GET /lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410 (::1) 87.88ms referer=None
[W 2022-04-19 19:33:24.694 ServerApp] 404 GET /static/lab/style/bootstrap.min.css (::1) 28.20ms referer=http://localhost:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
[W 2022-04-19 19:33:24.696 ServerApp] 403 GET /static/lab/style/index.css (::1): style/index.css is not in root static directory
[W 2022-04-19 19:33:24.701 ServerApp] 403 GET /static/lab/style/index.css (::1) 31.39ms referer=http://localhost:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
[W 2022-04-19 19:33:24.704 ServerApp] 403 GET /static/lab/style/bootstrap-theme.min.css (::1): style/bootstrap-theme.min.css is not in root static directory
[W 2022-04-19 19:33:24.707 ServerApp] 403 GET /static/lab/style/bootstrap-theme.min.css (::1) 3.35ms referer=http://localhost:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
[W 2022-04-19 19:33:24.719 ServerApp] 403 GET /static/lab/logo/logo.png (::1): logo/logo.png is not in root static directory
[W 2022-04-19 19:33:24.720 ServerApp] 403 GET /static/lab/logo/logo.png (::1) 1.81ms referer=http://localhost:8888/lab?token=deab763e954166b067877e28a0b49d05d6020cd74e14e410
[W 2022-04-19 19:33:24.874 ServerApp] 403 GET /static/lab/favicon.ico (::1): favicon.ico is not in root static directory
[W 2022-04-19 19:33:24.875 ServerApp] 403 GET /static/lab/favicon.ico (::1) 1.98ms referer=http://localhost:8888/lab
```

**Comment by krassowski** [comment]
This usually occurs when the lab development assets are not built. Please try the following commands:

```
jlpm run build  # Build the dev mode assets
jlpm run build:core  # Build the core mode assets
jupyter lab build  # Build the app dir assets
```

from https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#installing-jupyterlab

**Comment by mchhatwal** [comment]
We had attempted to run the jlpm build commands for quite a while but were met with a variety of issues. The biggest of these is that our target python is python3, while Jupyter Lab is attempting to run programs in python. Is there any way you know to get around this issue?

**Comment by krassowski** [comment]
> The biggest of these is that our target python is python3, while Jupyter Lab is attempting to run programs in python. Is there any way you know to get around this issue?

This sound like you are using a system-wide installation. The contribution guidelines recommend setting up a conda environment (again, see https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#installing-jupyterlab), but using any other virtual environment would work as well.

**Comment by mchhatwal** [comment]
Hello, we have been able to now run the program and implement a few changes we believe should address this problem. Unfortunately, dev mode is not reflecting any of our changes, making it difficult to test. 

We are currently running the command "jupyter lab --dev-mode". Can anyone please share any ideas about what may be causing the lack of update to the dev environment?

**Comment by Rahasyapandey** [comment]
Hi, I would like to work on this issue.

**Comment by terminalchai** [comment]
I’m working on this and will open a PR with a comment-character option for CSVTable, keeping comment lines visible while excluding them from header/column detection.

**Comment by DishaL17** [comment]
Hi, I would like to work on this issue. Is it still available?
