### ISSUE TITLE
Check release job is broken

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#11933]
## Description

The check release [job on the CI](https://github.com/jupyterlab/jupyterlab/actions/workflows/check-release.yml) is not working since a hour.

```bash
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-djmq9_gc/pyrsistent_7f01281cf3094749b2af81d844a15049/setup.py", line 52, in <module>
        setup(
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/setuptools/command/build_py.py", line 56, in run
        self.build_package_data()
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/setuptools/command/build_py.py", line 127, in build_package_data
        srcfile in self.distribution.convert_2to3_doctests):
    AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'
```

**Comment by fcollonval** [comment]
Maybe related: https://github.com/rspeer/langcodes/issues/44

It seems it comes from setuptools in the temporary virtual env being different of the one in the active environment.

**Comment by bollwyvl** [comment]
Gross.

I guess either lab needs to pick a line in the sand in as to `setuptools` version in `build-system`.

Alternately, this could be applied in `jupyter-packaging`, and then raising the minimum pin....

**Comment by bollwyvl** [comment]
Hm, appears to perhaps be related to `jsonschema -> pyrsistent` (source of everlasting joy).

**Comment by fcollonval** [comment]
A similar issue was reported [there](https://github.com/pypa/setuptools/pull/2721#issuecomment-913864288)

It was due to two versions of setuptools being installed simultaneously.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter-server/jupyter_releaser/pull/251
