### ISSUE TITLE
Jupyter lab crashes instantly

### ISSUE THREAD

**Issue by Nitish-Naineni** [jupyterlab/jupyterlab#12071]
Each time I launch jupyter lab, it shows the following on the browser

>Server Connection Error
>A connection to the Jupyter server could not be established. JupyterLab will continue trying to reconnect. Check your network >connection or Jupyter server configuration.

The is what it shows in the terminal:

```

(def) PS C:\Users\naine> jupyter-lab
[W 2022-02-16 16:56:54.564 ServerApp] The module 'jupyterlab_code_formatter' could not be found. Are you sure the extension is installed?
[I 2022-02-16 16:56:54.576 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-02-16 16:56:55.013 ServerApp] The module 'jupyterlab_code_formatter' could not be found. Are you sure the extension is installed?
[I 2022-02-16 16:56:55.013 ServerApp] nbclassic | extension was successfully linked.
[I 2022-02-16 16:56:55.040 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-02-16 16:56:55.041 LabApp] JupyterLab extension loaded from C:\Users\naine\def\lib\site-packages\jupyterlab
[I 2022-02-16 16:56:55.041 LabApp] JupyterLab application directory is C:\Users\naine\def\share\jupyter\lab
[I 2022-02-16 16:56:55.044 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-02-16 16:56:55.044 ServerApp] Serving notebooks from local directory: C:\Users\naine
[I 2022-02-16 16:56:55.044 ServerApp] Jupyter Server 1.13.5 is running at:
[I 2022-02-16 16:56:55.044 ServerApp] http://localhost:8888/lab?token=c2aab1ce84650e2b406752ecf2cae6c2f7b959cf2f6be9ad
[I 2022-02-16 16:56:55.044 ServerApp]  or http://127.0.0.1:8888/lab?token=c2aab1ce84650e2b406752ecf2cae6c2f7b959cf2f6be9ad
[I 2022-02-16 16:56:55.045 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-02-16 16:56:55.087 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/naine/AppData/Roaming/jupyter/runtime/jpserver-12616-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=c2aab1ce84650e2b406752ecf2cae6c2f7b959cf2f6be9ad
     or http://127.0.0.1:8888/lab?token=c2aab1ce84650e2b406752ecf2cae6c2f7b959cf2f6be9ad
[I 2022-02-16 16:56:59.639 LabApp] Build is up to date
[W 2022-02-16 16:57:12.690 ServerApp] Notebook Documents/CSE 546 Reinforcement Learning/Assignment-1/spring22_rl_lec_3_RL_Env_Demo.ipynb is not trusted
[I 2022-02-16 16:57:17.052 ServerApp] Kernel started: da697361-e70f-4a07-8293-6e3be3addbcb
[I 2022-02-16 16:57:17.056 ServerApp] Kernel started: c37b38d5-8bf4-43de-909c-6716a3f56008
[W 2022-02-16 16:57:18.138 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x00000218563C1310>
Traceback (most recent call last):
  File "C:\Users\naine\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\naine\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\naine\def\Scripts\jupyter-lab.exe\__main__.py", line 7, in <module>
  File "C:\Users\naine\def\lib\site-packages\jupyter_server\extension\application.py", line 577, in launch_instance
    serverapp.start()
  File "C:\Users\naine\def\lib\site-packages\jupyter_server\serverapp.py", line 2694, in start
    self.start_ioloop()
  File "C:\Users\naine\def\lib\site-packages\jupyter_server\serverapp.py", line 2680, in start_ioloop
    self.io_loop.start()
  File "C:\Users\naine\def\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\naine\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\naine\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1875, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

```
Sometimes randomly (1 in 20) it does launch and works without any issue. 

Things i have tried so far:
1. have tried `jupyter lab clean --all`
2. Uninstall and reinstall jupyter lab
3. remove the virtual env and try in a new environment 
4. remove all packages installed using pip and reinstall necessary packages
5. reinstall python

**Comment by jweill-aws** [comment]
What version of Windows are you using? #11934 concerns a similar error ("pop from an empty deque") on Windows 11. Yours might be a duplicate.

**Comment by Nitish-Naineni** [comment]
Im am using windows 11.

**Comment by vherasme** [comment]
I am using Windows 10 Enterprise, I have seen this a couple of times:
```
[W 2022-11-22 10:52:58.459 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x0000022F360C74C0>
```
