### ISSUE TITLE
ModuleNotFoundError: No module named 'traitlets.utils.descriptions'

### ISSUE THREAD

**Issue by charlesxu90** [jupyterlab/jupyterlab#12094]
## Description
I'm using Python 3.6 with default jupyter-lab version. The error comes I believe it's a dependency problem, probably traitlets version is not matching with jupyter-lab  version.

traitlets version: 4.2.0
Jupyterlab version: 3.2.9

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by agoose77** [comment]
The error message suggests that something expects `traitlets>=5`, whereas you have `traitlets<5`. I created a container from `python:3.6.15-buster` and ran `pip install jupyterlab`:
```Dockerfile
FROM python:3.6.15-buster
RUN pip install jupyterlab
```
When invoking `jupyterlab` inside the container, it launches successfully. This suggests that the default solve for JupyterLab correctly pulls in IPython<7 (which is the package that is probably setting the `traitlets` upper bound.

So, it seems like you might have a broken environment. Do you use a dependency manager like `pdm`/`pipenv`/`poetry`? These help avoid breaking your environment by determining a valid solve for your required set of packages.

Also, are you using a virtual-environment / Conda environment?

The solution here, I think, is to recreate your environment and see whether you still have the issue. You can fix this by hand, but it's much easier just to re-create the environment.

**Comment by charlesxu90** [comment]
I'm using Python 3.6 in conda environment. 

I tried to install traitlest 5. But seems traitlest 5 requires later python versions.
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - traitlets=5 -> python[version='>=3.7,<3.8.0a0|>=3.7|>=3.8,<3.9.0a0']

Your python: python=3.6

```

If true, then this is very unfriendly for python 3.6 users.

**Comment by charlesxu90** [comment]
I also tried to install traitlest version 5 from pip with command ` pip install  traitlets==5`, it cannot find a suitable version.

```
ERROR: Could not find a version that satisfies the requirement traitlets==5 (from versions: 0.0.1, 0.0.2, 4.0.0.dev0, 4.0.0, 4.1.0b1, 4.1.0, 4.2.0, 4.2.1, 4.2.2, 4.3.0b1, 4.3.0, 4.3.1, 4.3.2, 4.3.3.dev0, 4.3.3)
ERROR: No matching distribution found for traitlets==5

```

**Comment by charlesxu90** [comment]
BTW, it might not be the problem. I have another python 3.6 environment which is using  traitlets 4.3.3, the same version as my current environment. The jupyter versions of that is shown below.
```
 $ jupyter --version 
Selected Jupyter core packages...
IPython          : 7.16.1
ipykernel        : 5.5.5
ipywidgets       : 7.6.5
jupyter_client   : **7.1.0**
jupyter_core     : 4.8.1
jupyter_server   : **1.13.1**
jupyterlab       : **3.2.5**
nbclient         : 0.5.9
nbconvert        : 6.0.7
nbformat         : 5.1.3
notebook         : 6.3.0
qtconsole        : not installed
traitlets        : 4.3.3
```
For my current environment, the packages are shown below.

```
 $ jupyter --version  
Selected Jupyter core packages...
IPython          : 7.16.1
ipykernel        : 5.5.5
ipywidgets       : 7.6.5
jupyter_client   : **7.1.2**
jupyter_core     : 4.8.1
jupyter_server   : **1.13.2**
jupyterlab       : **3.2.9**
nbclient         : 0.5.9
nbconvert        : 6.0.7
nbformat         : 5.1.3
notebook         : 6.3.0
qtconsole        : not installed
traitlets        : 4.3.3
```
Only minor versions is different. I'm not sure if that causes the problem.

**Comment by charlesxu90** [comment]
I tried to reinstall the packages to jupyter_client   : **7.1.0** and jupyter_server   : **1.13.1** the problem solved.
```
 conda install -c conda-forge jupyter_client=7.1.0 jupyter_server=1.13.1  --force-reinstall
```

**Comment by agoose77** [comment]
`traitlets>=5` is not available for Python 3.6, which is why you're unable to install it.
> If true, then this is very unfriendly for python 3.6 users.

Python 3.6 is quite old now (5 years), so it's gradually being dropped by developers. You should consider upgrading your Python.

It looks like `jupyter_server==1.13.2` is the release that adds this bug. I'll file a report in the mean-time :)

**Comment by agoose77** [comment]
Hmm, it seems like this actually isn't a bug - you shouldn't have been able to install `jupyter_server==1.13.2` for 3.6. I'm not sure why this happened without further context, but it seems like resetting your environment worked.

**Comment by charlesxu90** [comment]
It's strange. I tried to rebuild a new environment using conda. The same problem occurs.

**Comment by jasongrout** [comment]
> Python 3.6 is quite old now (5 years),

In fact, Python 3.6 has now reached end-of-life and is no longer supported by Python either: https://endoflife.date/python

**Comment by agoose77** [comment]
> In fact, Python 3.6 has now reached end-of-life and is no longer supported by Python either: https://endoflife.date/python

Huh, I missed this. Even stronger case for upgrading then :)

**Comment by vwbusguy** [comment]
I'm currently seeing this on Python 3.9 using the Jupyter docker images:

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/opt/conda/lib/python3.9/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyter_server.serverapp import flags
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 83, in <module>
    from jupyter_server.services.sessions.sessionmanager import SessionManager
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 22, in <module>
    from jupyter_server.traittypes import InstanceFromClasses
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/traittypes.py", line 7, in <module>
    from traitlets.utils.descriptions import describe
ModuleNotFoundError: No module named 'traitlets.utils.descriptions'
```

**Comment by jasongrout** [comment]
Can you open a new issue in the jupyter_server project, where the error is?

https://github.com/jupyter-server/jupyter_server

**Comment by charlesxu90** [comment]
Problem solved using following command.
```
conda install -c conda-forge jupyter_client=7.1.0 jupyter_server=1.13.1  --force-reinstall
```

**Comment by znmeb** [comment]
I am on an NVIDIA Jetson and am running in a `conda`/`mamba `environment via `Mambaforge`. The environment requires both `JupyterLab `from `conda-forge` and `PyTorch `from an NVIDIA-supplied wheel installed with `pip`. I'm constrained to Python 3.6 because NVIDIA only supply a PyTorch wheel for 3.6. 

I haven't pinned JupyterLab to a specific version, and this is what the `conda` dependency solver gave me:

```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 7.16.1
ipykernel        : 5.5.5
ipywidgets       : not installed
jupyter_client   : 7.1.2
jupyter_core     : 4.8.1
jupyter_server   : 1.13.2
jupyterlab       : 3.3.4
nbclient         : 0.5.9
nbconvert        : 6.0.7
nbformat         : 5.1.3
notebook         : 6.3.0
qtconsole        : not installed
traitlets        : 4.3.3
```

For reference, here's the YAML environment file I used to create the environment via `conda env create -f`:

```
name: cusignal-dev
channels:
  - conda-forge
  - nvidia
  - numba
  - c4aarch64
dependencies:
  - python=3.6
  - jupyterlab
  - scipy>=1.5.0
  - numpy
  - matplotlib
  - numba>=0.49
  - pytest
  - pytest-benchmark
  - sphinx
  - pydata-sphinx-theme
  - sphinx-copybutton
  - numpydoc
  - ipython
  - pip
  - pip:
    - cupy>=9.0.0
  ```

I can pin the `JupyterLab `version to something older that uses `traitlets` 4.3.3. Questions:

1. What's the newest JupyterLab version that will work with `traitlets` 4.3.3?
2. Shouldn't the dependency solver of `Mambaforge ` either figured that out for me or told me I couldn't build the environment?

**Comment by znmeb** [comment]
I have a workaround for anyone brought here from a web search for the error as I was: pin `jupyter_server` 

```
jupyter_server<1.13.2
```
