### ISSUE TITLE
3.3.0: sphinx build depends on installed `jupyterlab`

### ISSUE THREAD

**Issue by kloczek** [jupyterlab/jupyterlab#12151]
## Description
Looks like `jupyterlab` sphinx build depends on jlpm from $PATH when is used setuptools<>sphinx integration.

## Reproduce
Afyer build execute `build_sphinx` to generate man page.

## Expected behavior
Sphhinx build should not depend on `jlpm` command executed from $PATH,

## Context
- Operating System and version: Linux x86/64
- Browser and version: N/A
- JupyterLab version: 3.3.0

Here is man page build output:
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.4.0
making output directory... done
Building jupyterlab API docs
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > typedoc@0.21.2" has unmet peer dependency "typescript@4.0.x || 4.1.x || 4.2.x || 4.3.x".
warning " > @jupyterlab/ui-components@3.3.0" has unmet peer dependency "react@^17.0.1".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/example-federated-middle > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/codemirror > y-codemirror@3.0.1" has unmet peer dependency "yjs@^13.5.17".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/ui-components > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/galata > svgo-loader@2.2.2" has unmet peer dependency "svgo@^1.0.0".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0-rc.12" has unmet peer dependency "typanion@*".
warning "workspace-aggregator-d0925b38-b969-4e95-8a0c-35f2d33b17d7 > @jupyterlab/ui-components > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
$ node scripts/ensure-buildutils.js

> @jupyterlab/buildutils@3.3.0 clean
> rimraf lib && rimraf tsconfig.tsbuildinfo

npm notice
npm notice New minor version of npm available! 8.3.1 -> 8.5.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.2
npm notice Run npm install -g npm@8.5.2 to update!
npm notice

> @jupyterlab/buildutils@3.3.0 build
> tsc


> @jupyterlab/builder@3.3.0 clean
> rimraf lib && rimraf tsconfig.tsbuildinfo


> @jupyterlab/builder@3.3.0 build
> tsc

Done in 67.24s.
yarn run v1.21.1
$ cd packages/metapackage && jlpm run build
/bin/sh: line 1: jlpm: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exception occurred:
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', '/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.3.0/docs/source/../../jupyterlab/staging/yarn.js', 'build:packages']' returned non-zero exit status 127.
The full traceback has been saved in /tmp/sphinx-err-j0jrwq6b.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by fcollonval** [comment]
Hey @kloczek could provide more context on this one? `jlpm` is required because we are building the typescript API documentation as part of the documentation as mentioned in the log _Building jupyterlab API docs_.

**Comment by fcollonval** [comment]
I see that you are building the `man` version of the documentation. I'm not sure the current documentation is adequate for that format.

**Comment by jweill-aws** [comment]
@kloczek Any update in response to @fcollonval 's question? Also, had this been occurring with any previous version? Is it new in 3.3.0?

**Comment by jweill-aws** [comment]
@kloczek I haven't seen any response on this so far — can you please provide an update regarding @fcollonval 's question?

**Comment by kloczek** [comment]
> Hey @kloczek could provide more context on this one? `jlpm` is required because we are building the typescript API documentation as part of the documentation as mentioned in the log _Building jupyterlab API docs_.

`jlpm` is installed and provided by this module (`jupyterlab`).
Looks like content of the docs/source/copy.py s not ready to be used without actually installed `jupyterlab`.
That kind of situation is typical when `jupyterlab` is build from non-root account.

**Comment by kloczek** [comment]
> I see that you are building the `man` version of the documentation. I'm not sure the current documentation is adequate for that format.

This has nothing to do with generate documentation in exact format.
```console
[tkloczko@devel-g2v jupyterlab-3.3.4]$ /usr/bin/sphinx-build -n -T -b html docs/source build/sphinx/html
Running Sphinx v4.5.0
making output directory... done
Building jupyterlab API docs
yarn install v1.21.1
[1/4] Resolving packages...
success Already up-to-date.
$ node scripts/ensure-buildutils.js
Done in 2.25s.
yarn run v1.21.1
$ cd packages/metapackage && jlpm run build
/bin/sh: line 1: jlpm: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 237, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.3.4/docs/source/conf.py", line 278, in setup
    build_api_docs(app.outdir)
  File "/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.3.4/docs/source/conf.py", line 112, in build_api_docs
    check_call(jlpm + ["build:packages"], cwd=root)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', '/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.3.4/docs/source/../../jupyterlab/staging/yarn.js', 'build:packages']' returned non-zero exit status 127.

Exception occurred:
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', '/home/tkloczko/rpmbuild/BUILD/jupyterlab-3.3.4/docs/source/../../jupyterlab/staging/yarn.js', 'build:packages']' returned non-zero exit status 127.
The full traceback has been saved in /tmp/sphinx-err-exojbuwz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by kloczek** [comment]
Is it possible to reopen this ticket .. please?

**Comment by jweill-aws** [comment]
@kloczek Thanks for providing this extra info! I've reopened this ticket.

**Comment by kloczek** [comment]
Hopefully you would be able to reproduce that issue.
I'm 100% sure that you would be able waaay quicker find the cause.
Thank you😃

**Comment by fcollonval** [comment]
@kloczek thanks for the additional details. As I mention previously:

>  `jlpm` is required because we are building the typescript API documentation as part of the documentation as mentioned in the log _Building jupyterlab API docs_.

This is for us expected that the frontend code must be transpiled as part of the documentation generation process. We do not intent to change that at least for the HTML documentation (i.e. our only documentation target currently). So my question is what is your need? what kind of documentation are you trying to get?

**Comment by kloczek** [comment]
>  This is for us expected that the frontend code must be transpiled as part of the documentation generation process. We do not intent to change that at least for the HTML documentation (i.e. our only documentation target currently). So my question is what is your need? what kind of documentation are you trying to get?

Missing path to `jlpm` command path is output ormat indepedenent.
Please have look on the output of the command hete I'm trying to generate html.
https://github.com/jupyterlab/jupyterlab/issues/12151#issuecomment-1100117142

**Comment by fcollonval** [comment]
You must install the package doc dependencies for the project root:

```sh
pip install -e .[docs]
```

Then you should be able to generate the documentation.

**Comment by kloczek** [comment]
> ```shell
> pip install -e .[docs]
> ```

Looks like you've not beebn even tryng to reproduce that issue and giving me random answers without testing 😞 
That command theretically shoud install all documentation buil dependencies and has nothing to do with that `sphinx-build` cannot access to missing `jlpm` script.
Theoretically beacose this module has no defined `[docs]` build dependencies ..
```console
[tkloczko@devel-g2v jupyterlab-3.3.3]$ pip install -e .[docs]
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/tkloczko/rpmbuild/BUILD/jupyterlab-3.3.3
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
WARNING: jupyterlab 3.3.3 does not provide the extra 'docs'
Requirement already satisfied: nbclassic~=0.2 in /usr/lib/python3.8/site-packages (from jupyterlab==3.3.3) (0.3.6)
Requirement already satisfied: ipython in /usr/lib/python3.8/site-packages (from jupyterlab==3.3.3) (7.30.1)
Requirement already satisfied: packaging in /usr/lib/python3.8/site-packages (from jupyterlab==3.3.3) (21.3)
Requirement already satisfied: jupyterlab-server~=2.10 in /usr/lib/python3.8/site-packages (from jupyterlab==3.3.3) (2.12.0)
Requirement already satisfied: tornado>=6.1.0 in /usr/lib64/python3.8/site-packages (from jupyterlab==3.3.3) (6.1)
Requirement already satisfied: jupyter-server~=1.4 in /usr/lib/python3.8/site-packages (from jupyterlab==3.3.3) (1.16.0)
Requirement already satisfied: jinja2>=2.1 in /usr/lib/python3.8/site-packages (from jupyterlab==3.3.3) (3.1.1)
Requirement already satisfied: jupyter-core in /usr/lib/python3.8/site-packages (from jupyterlab==3.3.3) (4.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib64/python3.8/site-packages (from jinja2>=2.1->jupyterlab==3.3.3) (2.1.1)
Requirement already satisfied: terminado>=0.8.3 in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (0.13.3)
Requirement already satisfied: traitlets>=5.1.0 in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (5.1.1)
Requirement already satisfied: pyzmq>=17 in /usr/lib64/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (22.3.0)
Requirement already satisfied: argon2-cffi in /usr/lib64/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (21.1.0)
Requirement already satisfied: nbconvert>=6.4.4 in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (6.4.5)
Requirement already satisfied: prometheus-client in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (0.14.1)
Requirement already satisfied: anyio>=3.1.0 in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (3.5.0)
Requirement already satisfied: Send2Trash in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (1.8.0)
Requirement already satisfied: websocket-client in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (1.3.2)
Requirement already satisfied: nbformat>=5.2.0 in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (5.3.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/lib/python3.8/site-packages (from jupyter-server~=1.4->jupyterlab==3.3.3) (7.2.2)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/lib/python3.8/site-packages (from jupyterlab-server~=2.10->jupyterlab==3.3.3) (0.4)
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (from jupyterlab-server~=2.10->jupyterlab==3.3.3) (2.27.1)
Requirement already satisfied: jsonschema>=3.0.1 in /usr/lib/python3.8/site-packages (from jupyterlab-server~=2.10->jupyterlab==3.3.3) (4.4.0)
Requirement already satisfied: babel in /usr/lib/python3.8/site-packages (from jupyterlab-server~=2.10->jupyterlab==3.3.3) (2.9.1)
Requirement already satisfied: json5 in /usr/lib/python3.8/site-packages (from jupyterlab-server~=2.10->jupyterlab==3.3.3) (0.9.6)
Requirement already satisfied: notebook<7 in /usr/lib/python3.8/site-packages (from nbclassic~=0.2->jupyterlab==3.3.3) (6.4.8)
Requirement already satisfied: notebook-shim>=0.1.0 in /usr/lib/python3.8/site-packages (from nbclassic~=0.2->jupyterlab==3.3.3) (0.1.0)
Requirement already satisfied: pickleshare in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (0.7.5)
Requirement already satisfied: matplotlib-inline in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (0.1.3)
Requirement already satisfied: decorator in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (5.1.1)
Requirement already satisfied: backcall in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (62.0.0)
Requirement already satisfied: pygments in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (2.11.2)
Requirement already satisfied: pexpect>4.3 in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (4.8.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (3.0.29)
Requirement already satisfied: jedi>=0.16 in /usr/lib/python3.8/site-packages (from ipython->jupyterlab==3.3.3) (0.18.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.8/site-packages (from packaging->jupyterlab==3.3.3) (3.0.8)
Requirement already satisfied: sniffio>=1.1 in /usr/lib/python3.8/site-packages (from anyio>=3.1.0->jupyter-server~=1.4->jupyterlab==3.3.3) (1.2.0)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3.8/site-packages (from anyio>=3.1.0->jupyter-server~=1.4->jupyterlab==3.3.3) (3.3)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/lib/python3.8/site-packages (from jedi>=0.16->ipython->jupyterlab==3.3.3) (0.8.3)
Requirement already satisfied: pyrsistent>=0.17.2 in /usr/lib64/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.10->jupyterlab==3.3.3) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.10->jupyterlab==3.3.3) (21.4.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.10->jupyterlab==3.3.3) (5.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.8/site-packages (from jupyter-client>=6.1.12->jupyter-server~=1.4->jupyterlab==3.3.3) (2.8.2)
Requirement already satisfied: nest-asyncio>=1.5.4 in /usr/lib/python3.8/site-packages (from jupyter-client>=6.1.12->jupyter-server~=1.4->jupyterlab==3.3.3) (1.5.5)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (0.5.13)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (1.5.0)
Requirement already satisfied: testpath in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (0.6.0)
Requirement already satisfied: bleach in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (4.1.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (4.10.0)
Requirement already satisfied: defusedxml in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (0.8.4)
Requirement already satisfied: jupyterlab-pygments in /usr/lib/python3.8/site-packages (from nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (0.1.2)
Requirement already satisfied: fastjsonschema in /usr/lib/python3.8/site-packages (from nbformat>=5.2.0->jupyter-server~=1.4->jupyterlab==3.3.3) (2.15.3)
Requirement already satisfied: ipykernel in /usr/lib/python3.8/site-packages (from notebook<7->nbclassic~=0.2->jupyterlab==3.3.3) (6.13.0)
Requirement already satisfied: ipython-genutils in /usr/lib/python3.8/site-packages (from notebook<7->nbclassic~=0.2->jupyterlab==3.3.3) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.8/site-packages (from pexpect>4.3->ipython->jupyterlab==3.3.3) (0.7.0)
Requirement already satisfied: wcwidth in /usr/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyterlab==3.3.3) (0.2.5)
Requirement already satisfied: cffi>=1.0.0 in /usr/lib64/python3.8/site-packages (from argon2-cffi->jupyter-server~=1.4->jupyterlab==3.3.3) (1.15.0)
Requirement already satisfied: pytz>=2015.7 in /usr/lib/python3.8/site-packages (from babel->jupyterlab-server~=2.10->jupyterlab==3.3.3) (2022.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/lib/python3.8/site-packages (from requests->jupyterlab-server~=2.10->jupyterlab==3.3.3) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests->jupyterlab-server~=2.10->jupyterlab==3.3.3) (1.26.9)
Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi->jupyter-server~=1.4->jupyterlab==3.3.3) (2.21)
Requirement already satisfied: zipp>=3.1.0 in /usr/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema>=3.0.1->jupyterlab-server~=2.10->jupyterlab==3.3.3) (3.8.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.8/site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->jupyter-server~=1.4->jupyterlab==3.3.3) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.8/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (2.3.2.post1)
Requirement already satisfied: webencodings in /usr/lib/python3.8/site-packages (from bleach->nbconvert>=6.4.4->jupyter-server~=1.4->jupyterlab==3.3.3) (0.5.1)
Requirement already satisfied: debugpy>=1.0 in /usr/lib64/python3.8/site-packages (from ipykernel->notebook<7->nbclassic~=0.2->jupyterlab==3.3.3) (1.6.0)
Requirement already satisfied: psutil in /usr/lib64/python3.8/site-packages (from ipykernel->notebook<7->nbclassic~=0.2->jupyterlab==3.3.3) (5.9.0)
Requirement already satisfied: ply==3.11 in /usr/lib/python3.8/site-packages (from pycparser->cffi>=1.0.0->argon2-cffi->jupyter-server~=1.4->jupyterlab==3.3.3) (3.11)
Installing collected packages: jupyterlab
  Running setup.py develop for jupyterlab
Successfully installed jupyterlab
```

**Comment by fcollonval** [comment]
True in 3.x branch the dependencies were unfortunately set in a separate conda environment file: https://github.com/jupyterlab/jupyterlab/blob/3.3.x/docs/environment.yml

Once you get the current python package install, you must have `jlpm` in your path as it is an entry point of the package:

https://github.com/jupyterlab/jupyterlab/blob/7d43b7ad23460a80f80a21c00a00d74c19b88008/setup.cfg#L63

**Comment by kloczek** [comment]
I'm not sure from where is executet `jlpm` .. what about that that module not by running that generated on build scrip but by `python -m jupyterlab.jlpmapp` with altered `sys.path`? 🤔 (just for copy.py)

**Comment by jweill-aws** [comment]
@kloczek Once you've run the commands listed in [the docs' installation section](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#installing-jupyterlab), you should have `jlpm` in your path.

**Comment by kloczek** [comment]
Thank you for advice however I want to build `jupyterlab` module on system cut off from public network and do not relay on unknown/unverified chunks of random software.
All what I'm installing is installed out of rpm packages build by my build systems.

I'm trying to render only `jupyterlab` documentation and to "save the World".
If that simple process scanning existing in source tree python code do generate such documentation has been so overcomplicates that is really bad 😞 
Please make that process KISS principle compliant.

**Comment by jweill-aws** [comment]
As noted in the docs: "The `jlpm` command is a JupyterLab-provided, locked version of the [yarn](https://classic.yarnpkg.com/en/) package manager. If you have `yarn` installed already, you can use the `yarn` command when developing, and it will use the local version of `yarn` in `jupyterlab/yarn.js` when run in the repository or a built application directory."

**Comment by kloczek** [comment]
> As noted in the docs: "The jlpm command is a JupyterLab-provided, locked version of the [yarn](https://classic.yarnpkg.com/en/) package manager.

And as I wrote more than one time that command is not available yet because that script is generated during install process and documentation rendering process described in copy.py does not care on which stage build system is. Do you see the problem here?
Just try to have look outside of the pure python are and try to find single project which documentation rendering process depends on exactly that software already installed in the system resources.
People everywhere are trying to avoid that kind of loops because it creates difficulties on bootstrapping.
In case of that module it is no possible to build and install it with documentation without such loops.
Even sphinx documentation is possible to generate without installed sphinx by just pointing over $PYTHONPATH to directory inside source tree.

Q: is it really necessary to use nodejs to generate python module documentation?
Raw sphinx is not enough?

**Comment by jweill-aws** [comment]
May 5 triage notes: As the home page for this project suggests, only 2.7% of the JupyterLab package is Python. The vast majority of this package is written in JavaScript and in TypeScript. Creating our documentation in NodeJS is consistent with our build tooling for the rest of the package for this largely web-based application.

I am closing this issue because it does not pass our [triage expectations](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#submitting-a-pull-request-contribution) for the JupyterLab project. If you still feel strongly about adding this feature, you can submit a pull request to update the documentation build toolchain.

**Comment by kloczek** [comment]
So this python moduyle is writtej in java scrip and this is why it has documentation which can be generated using sphinx? 🤔 
You provided me bogur procedure wythout trying to reproduce reported issu and at rhe and you've closed the ticket bucause sometbig which is completly not related to the ticket.

Really thank you and I'm really sorry to waste your time ..
