### ISSUE TITLE
Unhandled Promise Rejections - Kernel Autorestarting

### ISSUE THREAD

**Issue by matthart-sisense** [jupyterlab/jupyterlab#12200]
Hi, 

I am using `@jupyterlab/services` version `6.0.9`. I am experiencing an issue with the Kernel autorestarting when you try and execute code that causes and OOM exception. The Kernel status is getting in a state where the following unhandled promise rejections are causing our application to crash because we can only catch the rejections at the NodeJS process level. 

```
Canceled future for kernel_info_request message before replies were done
    at KernelShellFutureHandler.dispose (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/future.js:179:31)
    at /usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:982:20
    at Map.forEach (<anonymous>)
    at KernelConnection._clearKernelState (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:981:23)
    at /usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:1177:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

```
Kernel connection disconnected
    at KernelConnection.fulfill (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:507:31)
    at invokeSlot (/usr/src/app/node_modules/@lumino/signaling/dist/index.js:463:22)
    at Object.emit (/usr/src/app/node_modules/@lumino/signaling/dist/index.js:420:21)
    at Signal.exports.Signal.Signal.emit (/usr/src/app/node_modules/@lumino/signaling/dist/index.js:103:21)
    at KernelConnection._updateConnectionStatus (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:1127:39)
    at KernelConnection.dispose (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:311:14)
    at KernelConnection._updateStatus (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:956:18)
    at KernelConnection.handleShutdown (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:549:14)
    at KernelConnection.shutdown (/usr/src/app/node_modules/@jupyterlab/services/lib/kernel/default.js:538:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Things I have tried: 

- Wait for the status of the kernelConnection to be 'connected' and 'idle' before we try sending in further code for execution
- Call `interrupt()` on the Kernel connection and then `shutdown()` on the connection to then. spin up a new connection. This results in the "Kernel connection disconnected", which I believe is due to the `interrupt()` call not properly terminating all async tasks, which was reported [here](https://github.com/jupyterlab/jupyterlab/issues/12194). This means our call to `shutdown()` is going to set the status to `disconnected` and the the async call to `reconnect` when the Kernel is autorestarting is probably not terminated immediately by the `interrupt()` call.
- Upgraded to version  `@jupyterlab/services` to `6.3.1`

Curious if anyone is aware of the best way to handle Kernel crashes due to OOM exceptions? Thanks.

**Comment by jweill-aws** [comment]
Triage notes: Add `catch` that can log something to the console? This won't fix the problem if we have no unhandled inaccessible promise.

Can you share an example of code that reliably causes an OOM error so that we can test any fix against it?

**Comment by krassowski** [comment]
To be frank the fact that there is no way to handle this rejection is frustrating. It causes issues in our tests with random tests marked as failing or random/cryptic error logs (due to issue in jest https://github.com/jestjs/jest/issues/9210)  and slows down development.

https://github.com/jupyterlab/jupyterlab/blob/5598b3ac105cd879c23e04ef6a8a677cf208cacc/packages/services/src/kernel/future.ts#L195-L199

https://github.com/jupyterlab/jupyterlab/blob/5598b3ac105cd879c23e04ef6a8a677cf208cacc/packages/services/src/kernel/future.ts#L55-L57

So far I found that this can be suppressed in tests with:

```ts
// @ts-ignore
future['_done']['reject'] = () => {}
```

**Comment by krassowski** [comment]
Of note, this caused a lot of confusion and annoyance downstream:
- https://github.com/microsoft/vscode-jupyter/issues/9741
- https://github.com/microsoft/vscode-jupyter/issues/13081

I think that we should make kernel restart NOT throw this error (unhandled rejection). I think it is fair enough to special-case kernel shutdown/restart so that this nicer error message (warning) is logged in the console instead.

**Comment by krassowski** [comment]
Well, this clearly does not work like this:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/fe340caa-997c-4330-8290-15192a31b972)
