### ISSUE TITLE
Errors in performance test documentation

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#12216]
## Description

In the [performance testing docs](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#performance-testing), there are a couple of errors:

`jupyter lab --dev --NotebookApp.token=''  --no-browser` is meant to start "the dev build", but the option is actually `--dev-mode`, not `--dev`.

Modifying the command above, then running `jlpm run lighthouse --view`, I get an error:

```
% jlpm run lighthouse --view
yarn run v1.22.17
$ lighthouse http://localhost:8888/ --chrome-flags='--headless' --emulated-form-factor=none --throttling-method=provided --only-categories performance --view
  LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +1ms
  LH:ChromeLauncher Waiting for browser..... +508ms
  LH:ChromeLauncher Waiting for browser....... +505ms
  LH:ChromeLauncher Waiting for browser......... +503ms
  LH:ChromeLauncher Waiting for browser........... +506ms
  LH:ChromeLauncher Waiting for browser...........✓ +1ms
  LH:ChromeLauncher Killing Chrome instance 69739 +2ms
Runtime error encountered: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md
Error: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md
    at assertValidFlags (/Users/jweill/git/jupyterlab/node_modules/lighthouse/lighthouse-core/config/config.js:147:11)
    at new Config (/Users/jweill/git/jupyterlab/node_modules/lighthouse/lighthouse-core/config/config.js:193:7)
    at generateConfig (/Users/jweill/git/jupyterlab/node_modules/lighthouse/lighthouse-core/index.js:65:10)
    at lighthouse (/Users/jweill/git/jupyterlab/node_modules/lighthouse/lighthouse-core/index.js:43:18)
    at runLighthouse (file:///Users/jweill/git/jupyterlab/node_modules/lighthouse/lighthouse-cli/run.js:244:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fcollonval** [comment]
Fixed by #12215
