### ISSUE TITLE
Server failure on the CI

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#12211]
## Description

```
Traceback (most recent call last):

  File "/usr/share/miniconda/envs/_test/lib/python3.10/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]

KeyError: 'labextensions_path'


During handling of the above exception, another exception occurred:
An error occurred.
traitlets.config.configurable.MultipleInstanceError: An incompatible sibling of 'ServerApp' is already instanciated as singleton: InstallLabExtensionApp
See the log file for details:  /tmp/jupyterlab-debug-wn8ak91a.log


Traceback (most recent call last):

  File "/usr/share/miniconda/envs/_test/lib/python3.10/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]

KeyError: 'serverapp'

```

It is likely related to the latest jupyter_server release.

**Comment by fcollonval** [comment]
For example: https://github.com/jupyterlab/jupyterlab/runs/5538903803

**Comment by fcollonval** [comment]
New version of jupyter-server (1.15.3) will revert the PR that likely breaks the CI: https://github.com/jupyter-server/jupyter_server/pull/733

**Comment by jtpio** [comment]
Thanks for tracking this :+1:

**Comment by fcollonval** [comment]
Solved by https://github.com/jupyter-server/jupyter_server/pull/734
