### ISSUE TITLE
Issue when releasing JupyterLab 4.0.0a23

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#12324]
## Description

Opening this to leave a trace of the issue that is currently happening while trying to release 4.0.0a23 with the releaser.

The "Full Release" workflow started to fail during the "Publish Release" step. In that situation, one can use the "Publish Release" workflow and give it the URL to the draft GitHub Release to resume the process from there.

However a dozen of runs of the "Publish Release" workflow haven't helped so far, even after waiting a couple of hours.

## Reproduce

Here is an example run for reference: https://github.com/jtpio/jupyter_releaser/runs/5772374297?check_suite_focus=true

```
COMMAND: /tmp/tmpxvof53ln/bin/pip install -q dist/jupyterlab-4.0.0a23.tar.gz
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.10/x64/bin/jupyter-releaser", line 33, in <module>
    sys.exit(load_entry_point('jupyter-releaser', 'console_scripts', 'jupyter-releaser')())
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 101, in invoke
    super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 615, in extract_release
    lib.extract_release(
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/lib.py", line 364, in extract_release
    for tag in gh.list_tags():
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/ghapi/core.py", line 176, in list_tags
    return self.git.list_matching_refs(f'tags/{prefix}')
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/fastcore/net.py", line 111, in urlread
    with urlopen(url, data=data, headers=headers, timeout=timeout, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/fastcore/net.py", line 105, in urlopen
    return _opener.open(urlwrap(url, data=data, headers=headers), timeout=timeout)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/actions/publish_release.py", line 10, in <module>
    run(f"jupyter-releaser extract-release {release_url}")
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 72, in run
    raise e
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 64, in run
    process = tee(cmd, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/tee.py", line 172, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser extract-release https://github.com/jupyterlab/jupyterlab/releases/tag/untagged-7ba22f3a699e86e549f4' returned non-zero exit status 1.
```

![image](https://user-images.githubusercontent.com/591645/161210776-5e4a409e-45ff-4a7f-b4d8-d2d41c8a0e7e.png)

## Context

This also happened before when releasing 3.3.0 final. However it eventually managed to publish the assets after a couple of workflow restarts a couple of minutes later.

https://github.com/jupyter-server/jupyter_releaser/issues/278 tracks this issue on the releaser repo, in case there is something to do there such as handling retries.

**Comment by jtpio** [comment]
Gonna investigate a bit more, but if nothing then we can:

- revert the changelog entry commit
- revert the version bump commit
- delete the draft GitHub Release

Which should leave the repo in a clean state, so we can attempt to do another 4.0.0a23 release at another time.

**Comment by jtpio** [comment]
OK so it seems to be reproducible when trying this locally by running the `jupyter-releaser` CLI directly:

```
export GITHUB_ACCESS_TOKEN=<token>
jupyter-releaser extract-release https://github.com/jupyterlab/jupyterlab/releases/tag/untagged-7ba22f3a699e86e549f4
```

```
COMMAND: /tmp/tmpzam415n_/bin/pip install -q dist/jupyterlab-4.0.0a23.tar.gz
Traceback (most recent call last):
  File "/home/jtp/miniforge3/envs/tmp/bin/jupyter-releaser", line 10, in <module>
    sys.exit(main())
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/jupyter_releaser/cli.py", line 101, in invoke
    super().invoke(ctx)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/jupyter_releaser/cli.py", line 615, in extract_release
    lib.extract_release(
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/jupyter_releaser/lib.py", line 364, in extract_release
    for tag in gh.list_tags():
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/ghapi/core.py", line 176, in list_tags
    return self.git.list_matching_refs(f'tags/{prefix}')
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/fastcore/net.py", line 111, in urlread
    with urlopen(url, data=data, headers=headers, timeout=timeout, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/fastcore/net.py", line 105, in urlopen
    return _opener.open(urlwrap(url, data=data, headers=headers), timeout=timeout)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

**Comment by jtpio** [comment]
```
File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/lib.py", line 364, in extract_release
    for tag in gh.list_tags():
```

Yes there seems to be an issue when fetching all the tags. This is reproducible with the following code snippet:

```py
import os

from ghapi.core import GhApi

owner = 'jupyterlab'
repo = 'jupyterlab'
auth = os.getenv('GITHUB_ACCESS_TOKEN')

gh = GhApi(owner=owner, repo=repo, token=auth)

print(gh.list_tags())
```

Which gives the following output:

```
Traceback (most recent call last):
  File "/home/jtp/Downloads/lab-423-release/test.py", line 11, in <module>
    print(gh.list_tags())
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/ghapi/core.py", line 176, in list_tags
    return self.git.list_matching_refs(f'tags/{prefix}')
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/fastcore/net.py", line 111, in urlread
    with urlopen(url, data=data, headers=headers, timeout=timeout, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/site-packages/fastcore/net.py", line 105, in urlopen
    return _opener.open(urlwrap(url, data=data, headers=headers), timeout=timeout)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/jtp/miniforge3/envs/tmp/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

So probably the new `4.0.0-alpha.23` tags kind of "crossed a limit", and GitHub struggles when trying to return them all.

The `jupyterlab` repo indeed has a lot of these tags, since each npm package has one. So for each releases it's ~100 new tags.

**Comment by jtpio** [comment]
Opened a tentative fix in the releaser: https://github.com/jupyter-server/jupyter_releaser/pull/281

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter-server/jupyter_releaser/pull/281.

The 4.0.0a23 release finally went through: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0a23

**Comment by echarles** [comment]
Thx a lot @jtpio for this post-mortem analysis and for the fix. Happy that if finally went through.
