### ISSUE TITLE
Failed to set --ServerApp.terminado_settings='shell_command=/bin/zsh'

### ISSUE THREAD

**Issue by dmetasoul01** [jupyterlab/jupyterlab#12540]
## Description

I was trying to modified default shell in terminal to zsh. I've followed #4042 by passing `--NotebookApp.terminado_settings="{'shell_command': ['/bin/zsh']}"` to the `jupyter lab` command line and it worked.
However this would get two warnings, one is that I should change `NotebookApp` to `ServerApp`, and the other one is 
```
FutureWarning: --terminado_settings={'shell_command': ['/bin/zsh']} for dict-traits is deprecated in traitlets 5.0. You c
an pass --terminado_settings <key=value> ... multiple times to add items to a dict
```
So I change the command line option to `--ServerApp.terminado_settings='shell_command=["/bin/zsh"]'` but failed to open terminal with error message:
```
    Traceback (most recent call last):
      File "/home/jovyan/.local/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/jovyan/.local/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/home/jovyan/.local/lib/python3.8/site-packages/jupyter_server/auth/decorator.py", line 68, in inner
        return method(self, *args, **kwargs)
      File "/home/jovyan/.local/lib/python3.8/site-packages/jupyter_server/terminal/api_handlers.py", line 51, in post
        model = self.terminal_manager.create(**data)
      File "/home/jovyan/.local/lib/python3.8/site-packages/jupyter_server/terminal/terminalmanager.py", line 49, in create
        name, term = self.new_named_terminal(**kwargs)
      File "/home/jovyan/.local/lib/python3.8/site-packages/terminado/management.py", line 365, in new_named_terminal
        term = self.new_terminal(**kwargs)
      File "/home/jovyan/.local/lib/python3.8/site-packages/terminado/management.py", line 204, in new_terminal
        return PtyWithClients(argv, env, cwd)
      File "/home/jovyan/.local/lib/python3.8/site-packages/terminado/management.py", line 49, in __init__
        self.ptyproc = PtyProcessUnicode.spawn(**kwargs)
      File "/home/jovyan/.local/lib/python3.8/site-packages/ptyprocess/ptyprocess.py", line 207, in spawn
        raise TypeError("Expected a list or tuple for argv, got %r" % argv)

TypeError: Expected a list or tuple for argv, got '["/bin/zsh"]'
```
I've also tried shell_command=/bin/zsh , and adding quotes to key and value but none worked.
It seems that passing parameters with ServerApp prefix doesn't repr the command line string value?

## Reproduce

The full command I was using:
```bash
${HOME}/.local/bin/jupyter lab \
  --notebook-dir="${HOME}" \
  --ip=0.0.0.0 \
  --no-browser \
  --allow-root \
  --port=8888 \
  --ServerApp.terminado_settings="shell_command=['/bin/zsh']"
```

## Expected behavior

Start a terminal with zsh as shell.

## Context

- Operating System and version: 
- Browser and version: Edge
- JupyterLab version: 3.4.0

**Comment by jweill-aws** [comment]
Possibly related to #4034, although not identical.

**Comment by kangsan0420** [comment]
Still confused.. anyone has an example?
