### ISSUE TITLE
Not able to mount S3 buckets in JupyterLab

### ISSUE THREAD

**Issue by altruistcoder** [jupyterlab/jupyterlab#12795]
Hello, I have a JupyterLab docker image which I am using to run an instance of it in my openshift cluster. 
I have modified the `jupyter_notebook_config.py` by adding some custom source code which can be used to mount some S3 buckets created using an S3 compatible storage (Noobaa) in my openshift cluster itself.

But, I am getting the below error while running the image:
    
```
Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 645, in get
        value = obj._trait_values[self.name]
    KeyError: 'managers'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/services/contents/handlers.py", line 112, in get
        if await ensure_async(cm.is_hidden(path)) and not cm.allow_hidden:
      File "/opt/conda/lib/python3.9/site-packages/hybridcontents/hybridmanager.py", line 86, in _wrapper
        prefix, mgr, mgr_path = _resolve_path(path, self.managers)
      File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 686, in __get__
        return self.get(obj, cls)
      File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 648, in get
        default = obj.trait_defaults(self.name)
      File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
      File "/opt/conda/lib/python3.9/site-packages/hybridcontents/hybridmanager.py", line 175, in _managers_default
        return {
      File "/opt/conda/lib/python3.9/site-packages/hybridcontents/hybridmanager.py", line 176, in <dictcomp>
        key: mgr_cls(parent=self,
      File "/opt/conda/lib/python3.9/site-packages/s3contents/s3manager.py", line 75, in __init__
        self._fs = S3FS(
      File "/opt/conda/lib/python3.9/site-packages/s3contents/s3_fs.py", line 116, in __init__
        self.init()
      File "/opt/conda/lib/python3.9/site-packages/s3contents/s3_fs.py", line 120, in init
        self.mkdir("")
      File "/opt/conda/lib/python3.9/site-packages/s3contents/s3_fs.py", line 202, in mkdir
        self.fs.touch(path_)
      File "/opt/conda/lib/python3.9/site-packages/fsspec/asyn.py", line 86, in wrapper
        if loop[0] is None:
      File "/opt/conda/lib/python3.9/site-packages/fsspec/asyn.py", line 66, in sync
        as an attribute of the instance.
      File "/opt/conda/lib/python3.9/site-packages/fsspec/asyn.py", line 26, in _runner
      File "/opt/conda/lib/python3.9/site-packages/s3fs/core.py", line 924, in _touch
        "size": out["ContentLength"],
      File "/opt/conda/lib/python3.9/site-packages/s3fs/core.py", line 325, in _call_s3
        -------
      File "/opt/conda/lib/python3.9/site-packages/s3fs/core.py", line 473, in set_session
        if fill_cache is None:
      File "/opt/conda/lib/python3.9/site-packages/aiobotocore/session.py", line 37, in __aenter__
        self._client = await self._coro
      File "/opt/conda/lib/python3.9/site-packages/aiobotocore/session.py", line 121, in _create_client
        client = await client_creator.create_client(
      File "/opt/conda/lib/python3.9/site-packages/aiobotocore/client.py", line 46, in create_client
        return service_client
    AttributeError: 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions'
[W 2022-07-11 14:23:24.787 ServerApp] Unhandled error
```

I am not able to understand if this error is coming up because of some mere dependency conflicts or something else is breaking up.

Can you please help me in resolving this issue?

**Comment by agoose77** [comment]
I don't have time to add much here, but a quick search suggested it's a versioning issue - https://github.com/fsspec/s3fs/issues/357

It might be that this thread has a good suggestion about the resolution. You should be able to manually force the correct versions to fix it.

**Comment by jweill-aws** [comment]
Can you please share the code that you added to `jupyter_notebook_config.py`? It's not clear whether the error is originating in JupyterLab code.

**Comment by jweill-aws** [comment]
@altruistcoder Can you please provide the code that you added to `jupyter_notebook_config.py` so that we can better diagnose where your problem originates? Thanks!

**Comment by altruistcoder** [comment]
Hello, sorry for getting back on this issue so late. I actually figured out that the problem was because of some dependency conflicts. I was trying to download the **boto3**, **s3contents** and the **hybridcontents** python modules simultaneously which was causing the issue as _s3contents brings a specific version of boto3 itself_ as well.

Thus, removing the installation of **boto3** module separately fixed the issue for me.

Thanks for taking out time and providing help @agoose77 @jweill-aws.
