### ISSUE TITLE
Jupyterlab extension not reading webpack config

### ISSUE THREAD

**Issue by smejak** [jupyterlab/jupyterlab#12851]
## Description

This issue is related to errors during `jupyter labextension install .`

I am developing a Jupyterlab extension that uses node packages for interacting with Web3 applications. These node packages have triggered a number of webpack polyfill errors for stream, http, and https, all of which I have included in my `package.json` & `webpack.config.js`. 

My `package.json` has the following dependencies:
```
  "dependencies": {
    "@jupyter-widgets/base": "^1 || ^2 || ^3 || ^4",
    "@jupyter-widgets/controls": "^3.0.0",
    "@jupyterlab/application": "^3.2.3",
    "@jupyterlab/apputils": "^3.2.3",
    "@jupyterlab/launcher": "^3.1.0",
    "@jupyterlab/observables": "^4.2.3",
    "@jupyterlab/outputarea": "^3.1.0",
    "@jupyterlab/rendermime": "^3.2.8",
    "@lumino/algorithm": "^1.9.1",
    "@lumino/commands": "^1.12.0",
    "@lumino/disposable": "^1.10.1",
    "@lumino/messaging": "^1.10.1",
    "@lumino/widgets": "^1.19.0",
    "@oceanprotocol/lib": "^1.1.6",
    "assert": "^2.0.0",
    "buffer": "^6.0.3",
    "crypto-js": "^4.1.1",
    "ethers": "^5.5.3",
    "https-browserify": "^1.0.0",
    "jupyter": "^0.0.0",
    "lab": "^18.0.2",
    "lit-js-sdk": "^1.1.121",
    "node-polyfill-webpack-plugin": "^2.0.0",
    "python": "^0.0.4",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "style-loader": "^3.3.1",
    "web3": "^1.7.4",
    "web3-providers-http": "^1.7.4",
    "webpack": "^5.73.0"
  },
```

My `webpack.config.js`:
```
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');
const webpack = require("webpack");

module.exports = {
  stats: {
    errorDetails: true,
    children: true
  },
  plugins: [
    new NodePolyfillPlugin(),
    // Work around for Buffer is undefined:
    // https://github.com/webpack/changelog-v5/issues/10
    new webpack.ProvidePlugin({
      Buffer: ["buffer", "Buffer"],
    }),
    new webpack.ProvidePlugin({
      process: "process/browser",
    }),
  ],
  resolve: {
    extensions: [".tsx", ".ts", ".js", ".jsx", ".css"],
    modules: ["node_modules"],
    fallback: {
      http: require.resolve("stream-http"),
      https: require.resolve("https-browserify"),
      stream: require.resolve("stream-browserify"),
      buffer: require.resolve("buffer"),
      assert: require.resolve("assert/"),
      // "assert": false,
      // "browser": false,
    },
  },
};
```
(note: I have been trying different configs, both including/excluding polyfill, and most recently trying out plugins)

Running `jlpm && jlpm run build` produces a lot of warnings but runs without errors (although I was able to get it to run without the warnings with a different webpack.config.js, but it didn't have an effect on the main issue described here), `pip install -e .` works fine.

Running `jupyter labextension install .` produces the following error
```
>rimraf build
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'https' in '/Users/jakub/miniconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/web3-providers-http/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
    - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
    - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
    resolve.fallback: { "https": false }
```
(the error is actually longer, but it's only a specific description of the polyfill error, one line that keeps appearing is `Field 'browser' doesn't contain a valid alias configuration`).

This error is actually the same as the one I was getting from `jlpm run build` before I added `webpack.config.js`, so I'm thinking that the `rimraf build` command (which is triggered when running `jupyter labextension install .`) does not see the webpack config, but I am not sure how to resolve this. Also, packaging the entire extension into a .whl file works without error but then when I try to install it it's not properly rendering in jupyter lab.

## Reproduce

1. Go to (https://github.com/AlgoveraAI/jupyterlab_extensions/tree/dev-publish)
2. Follow installation in `Contributing to library`
3. Run `jupyter labextension install .` instead of `jupyter labextension develop --overwrite`
5. See error described above

## Expected behavior

JupyterLab extension installs and shows all menu buttons.

## Context

- Operating System and version: macOS 12.3
- Browser and version: Brave 1.41.96
- JupyterLab version: 3.4.4

**Comment by jasongrout** [comment]
I would put your polyfills in your package.json, like we do for coreutils: https://github.com/jupyterlab/jupyterlab/blob/66f83a7fffefbad0b30be0484408f93544d63363/packages/coreutils/package.json#L17-L19

See the spec for this field at https://github.com/defunctzombie/package-browser-field-spec#replace-specific-files---advanced

As an example for the error above, I would start by changing this line: https://github.com/AlgoveraAI/jupyterlab_extensions/blob/876e3a8015fd0a371c72aceb42ada2dd97c8e9d1/package.json#L133
to 
```
"https": "https-browserify"
```
and then I think you can remove the fallbacks from your webpack config.

**Comment by smejak** [comment]
@jasongrout Thank you for the reply. I have tried adding that to my package.json so it now looks like this:
```
  "browser": {
    "stream": "stream-browserify",
    "http": "stream-http",
    "https": "https-browserify"
  },
```
however, when I then remove my webpack config from package.json (since it's only needed for the fallbacks), I get the following error after running `jlpm run build`
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'http' in '/Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/lib'                                       
                                                                                                                                                                                                                      
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.                                                                                                                           
This is no longer the case. Verify if you need this module and configure a polyfill for it.                                                                                                                           
                                                                                                                                                                                                                      
If you want to include a polyfill, you need to:                                                                                                                                                                       
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'                                                                                                                               
        - install 'stream-http'                                                                                                                                                                                       
If you don't want to include a polyfill, you can use an empty module like this:                                                                                                                                       
        resolve.fallback: { "http": false }                                                                                                                                                                           
    at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/Compilation.js:2016:28                                                                                             
    at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/NormalModuleFactory.js:798:13                                                                                      
    at eval (eval at create (/Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)                                                 
    at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/NormalModuleFactory.js:270:22                                                                                      
    at eval (eval at create (/Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)                                                  
    at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/NormalModuleFactory.js:434:22                                                                                      
    at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/NormalModuleFactory.js:116:11                                                                                      
    at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/NormalModuleFactory.js:670:25  
at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve 'http' in '/Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/lib'
  Parsed request is a module
  using description file: /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/lib/node_modules doesn't exist or is not a directory
      /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/node_modules doesn't exist or is not a directory
      /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules
        single file module
          using description file: /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/package.json (relative path: ./node_modules/http)
            no extension
              /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/http doesn't exist
            .js
              /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/http.js doesn't exist.json
              /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/http.json doesn't exist
            .wasm
              /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/http.wasm doesn't exist
        /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/http doesn't exist
      /Users/jakub/Development/Algovera/Core/tests/node_modules doesn't exist or is not a directory
      /Users/jakub/Development/Algovera/Core/node_modules doesn't exist or is not a directory
      /Users/jakub/Development/Algovera/node_modules doesn't exist or is not a directory
      /Users/jakub/Development/node_modules doesn't exist or is not a directory
      /Users/jakub/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
/Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/@jupyterlab/builder/lib/build-labextension.js:100
            throw new Error(err.details);
            ^

Error: resolve 'http' in '/Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/lib'
  Parsed request is a module
  using description file: /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/lib/node_modules doesn't exist or is not a directory
      /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/web3-providers-http/node_modules doesn't exist or is not a directory
      /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/jakub/Development/Algovera/Core/tests/jupyterlab_extensions/node_modules
...

```

**Comment by jasongrout** [comment]
Ah, looking at that error more closely, it's not an error in your package, it's an error trying to deal with the web3-providers-http package. The browser field in your package.json only applies to your package, not to your dependencies. Normally I'd suggest *that* package adding the same sort of browser field to its package.json, but it seems that the readme for that package talks about these sorts of browser overrides, so maybe it's more complicated for that particular package? https://github.com/ChainSafe/web3.js

**Comment by jasongrout** [comment]
You may need to go back to customizing the webpack config resolve fallbacks for this library? Webpack recommends that the library add its own `browser` field in its package.json in its migration guide: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

We had other discussions about resolving things for dependencies at https://github.com/jupyterlab/jupyterlab/issues/9345, but I think we've landed since then on making sure the core configuration works with core, and relying on either packages having correct browser fields in their package.json files, or possibly using the custom webpack config to patch things for dependencies.

**Comment by jasongrout** [comment]
On the other hand, perhaps this PR in that project fixes things for you? https://github.com/ChainSafe/web3.js/pull/5274

**Comment by smejak** [comment]
Oh I see, so I’ll have to modify the package.json inside the node module? Is there some way to do that from webpack or the main package.json be adding a specific path to inside web3-providers-http?

**Comment by smejak** [comment]
Thank you @jasongrout. Do you think changing the web3.js package.json should solve the issue for web3-providers-http as well? I tried adding the line proposed in https://github.com/ChainSafe/web3.js/pull/5274 to the web3js package.json, which did decrease the number of warnings during `jlpm run build`, but resulted in the same error for `jupyter labextension install .`

Do you think manually changing multiple package.jsons for each module should solve the issue? I have noticed that the error log is referring to a node module installed in my conda environment, not in the repo where the rest of my extension & all my node_modules are, so I'm not sure whether I should add the `browser` field to the local node_modules or the ones in my conda env:

```
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'http' in '/Users/jakub/miniconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/web3-providers-http/lib'

```

**Comment by smejak** [comment]
Hi @jasongrout. I followed your advice on adding the "browser" config to the package.json of every node module that threw an error (there were a few, but surprisingly, they weren't in the node_modules in the project repo but rather the node modules in my conda environment). Specifically, I added this (might be more than was necessary but wanted to make sure I got everything):
```
"browser": {
    "stream": "stream-browserify",
    "http": "stream-http",
    "https": "https-browserify",
    "web3": false,
     "fs": false,
     "path": false,
     "os": false
  },
```

 Now I got `jupyter labextension install .` to run without error but then when I run jupyter lab the extension isn't rendering properly. In my console, I get the following error:
```
ReferenceError: Buffer is not defined
    at varintEncode (util.js:33:1)
    at ./node_modules/multicodec/src/varint-table.js (varint-table.js:11:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/multicodec/src/index.js (index.js:16:31)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/content-hash/src/index.js (index.js:19:16)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/web3-eth-ens/lib/lib/contentHash.js (contentHash.js:31:19)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/web3-eth-ens/lib/ENS.js (ENS.js:26:19)
main @ index.out.js:590
```

Do you have any idea on what could be the issue?

**Comment by jasongrout** [comment]
> Do you have any idea on what could be the issue?

No, sorry. It looks like it's an error in a dependency I'm not familiar with.
