### ISSUE TITLE
Jupyter-lab Can't be Started after installing Python 3.10

### ISSUE THREAD

**Issue by glanzkaiser** [jupyterlab/jupyterlab#12905]
I just install Python 3.10 from Python 3.6

I am using CAELinux

when I type `jupyter-lab, I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/home/browni/.local/lib/python3.10/site-packages/jupyterlab/labapp.py", line 14, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/home/browni/.local/lib/python3.10/site-packages/jupyterlab_server/__init__.py", line 5, in <module>
    from .app import LabServerApp
  File "/home/browni/.local/lib/python3.10/site-packages/jupyterlab_server/app.py", line 10, in <module>
    from .handlers import LabConfig, add_handlers
  File "/home/browni/.local/lib/python3.10/site-packages/jupyterlab_server/handlers.py", line 18, in <module>
    from .listings_handler import ListingsHandler, fetch_listings
  File "/home/browni/.local/lib/python3.10/site-packages/jupyterlab_server/listings_handler.py", line 8, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 40, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python3/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/lib/python3/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
browni@browni:~/Téléchargements/Python-3.10.2$ jupyter_server --version
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

```

When I type `jupyter troubleshoot I get:
```
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/snap/bin

sys.path:
	/usr/local/bin
	/usr/lib/python310.zip
	/usr/lib/python3.10
	/usr/lib/python3.10/lib-dynload
	/usr/local/lib/python3.10/dist-packages
	/usr/local/lib/python3.10/dist-packages/setuptools-63.4.0.post20220803-py3.10.egg
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.10.6 (main, Aug  2 2022, 15:11:03) [GCC 7.5.0]

platform.platform():
	Linux-5.4.0-122-generic-x86_64-with-glibc2.27

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	Package                       Version
	----------------------------- -------------------
	alabaster                     0.7.8
	apt-clone                     0.2.1
	asn1crypto                    0.24.0
	astroid                       1.6.0
	Babel                         2.4.0
	beautifulsoup4                4.6.0
	bleach                        2.1.2
	blinker                       1.4
	catfish                       1.4.4
	certifi                       2018.1.18
	chardet                       3.0.4
	click                         6.7
	cloudpickle                   0.5.2
	colorama                      0.3.7
	command-not-found             0.3
	cryptography                  2.1.4
	cupshelpers                   1.0
	cycler                        0.10.0
	decorator                     4.1.2
	defer                         1.0.6
	devscripts                    2.17.12ubuntu1.1
	distro-info                   0.18ubuntu0.18.04.1
	docutils                      0.14
	dxf2gcode                     20170925
	entrypoints                   0.2.3.post1
	feedparser                    5.2.1
	future                        0.15.2
	GDAL                          2.2.2
	gpg                           1.10.0
	html5lib                      0.999999999
	httplib2                      0.9.2
	idna                          2.6
	imagesize                     0.7.1
	ipykernel                     4.8.2
	ipython                       5.5.0
	ipython_genutils              0.2.0
	isort                         4.3.4
	jedi                          0.11.1
	Jinja2                        2.10
	jsonschema                    2.6.0
	jupyter-client                5.2.2
	jupyter-core                  4.4.0
	keyring                       10.6.0
	keyrings.alt                  3.0
	language-selector             0.1
	launchpadlib                  1.10.6
	lazr.restfulclient            0.13.5
	lazr.uri                      1.0.3
	lazy-object-proxy             1.3.1
	lightdm-gtk-greeter-settings  1.2.2
	logilab-common                1.4.1
	lxml                          4.2.1
	macaroonbakery                1.1.3
	Mako                          1.0.7
	MarkupSafe                    1.0
	mccabe                        0.6.1
	meld                          3.18.0
	menulibre                     2.2.0
	mistune                       0.8.3
	mugshot                       0.4.0
	nbconvert                     5.3.1
	nbformat                      4.4.0
	netifaces                     0.10.4
	numpy                         1.13.3
	numpydoc                      0.7.0
	oauth                         1.0.1
	oauthlib                      2.0.6
	olefile                       0.45.1
	onboard                       1.4.1
	OWSLib                        0.16.0
	PAM                           0.4.2
	pandocfilters                 1.4.2
	parso                         0.1.1
	pexpect                       4.2.1
	pickleshare                   0.7.4
	Pillow                        5.1.0
	pip                           22.2.1
	Pivy                          0.6.5a0
	plotly                        2.2.3
	prompt-toolkit                1.0.15
	protobuf                      3.0.0
	psutil                        5.4.2
	psycopg2                      2.7.4
	pycairo                       1.16.2
	pycodestyle                   2.3.1
	pycrypto                      2.6.1
	pycups                        1.9.73
	pycurl                        7.43.0.1
	pyflakes                      1.6.0
	Pygments                      2.2.0
	PyGObject                     3.26.1
	PyICU                         1.9.8
	PyJWT                         1.5.3
	pylint                        1.8.3
	pymacaroons                   0.13.0
	PyNaCl                        1.1.2
	PyOpenGL                      3.1.0
	pyparsing                     2.2.0
	pyproj                        1.9.5.1
	pyRFC3339                     1.0
	python-apt                    1.6.5+ubuntu0.7
	python-dateutil               2.6.1
	python-debian                 0.1.32
	python-debianbts              2.7.2
	python-magic                  0.4.16
	pytz                          2018.3
	pyxdg                         0.25
	PyYAML                        3.12
	pyzmq                         16.0.2
	QtAwesome                     0.4.4
	qtconsole                     4.3.1
	QtPy                          1.3.1
	reportlab                     3.4.0
	requests                      2.18.4
	requests-unixsocket           0.1.5
	roman                         2.0.0
	rope                          0.10.5
	scour                         0.36
	SecretStorage                 2.3.1
	setuptools                    63.4.0.post20220803
	sgt-launcher                  0.2.4
	simplegeneric                 0.8.1
	simplejson                    3.13.2
	six                           1.11.0
	Sphinx                        1.6.7
	spyder                        3.2.6
	ssh-import-id                 5.7
	system-service                0.3
	systemd-python                234
	testpath                      0.3.1
	tornado                       4.5.3
	traitlets                     4.3.2
	ubuntu-advantage-tools        27.9
	ubuntu-drivers-common         0.0.0
	ufw                           0.36
	unattended-upgrades           0.1
	unidiff                       0.5.4
	unity-scope-calculator        0.1
	unity-scope-chromiumbookmarks 0.1
	unity-scope-colourlovers      0.1
	unity-scope-devhelp           0.1
	unity-scope-firefoxbookmarks  0.1
	unity-scope-manpages          0.1
	unity-scope-openclipart       0.1
	unity-scope-texdoc            0.1
	unity-scope-tomboy            0.1
	unity-scope-virtualbox        0.1
	unity-scope-yelp              0.1
	unity-scope-zotero            0.1
	urllib3                       1.22
	virtualenv                    15.1.0
	wadllib                       1.3.2
	wcwidth                       0.1.7
	webencodings                  0.5
	wheel                         0.30.0
	wrapt                         1.9.0
	xcffib                        0.5.1
	xkit                          0.0.0
	zope.interface                4.3.2

```

How to solve this?

**Comment by jweill-aws** [comment]
The last line of your error output is `ModuleNotFoundError: No module named 'apt_pkg'`. I didn't see `apt_pkg` in your list of installed packages.

How did you upgrade from Python 3.6 to 3.10? If you install the Python module `apt_pkg`, do you still see the errors above?

**Comment by glanzkaiser** [comment]
Glad someone respond me.. thanks

These are the codes I use to upgrade to Python 3.10:

```
sudo apt install software-properties-common -y
		sudo add-apt-repository ppa:deadsnakes/ppa
		sudo apt-get update
		apt list | grep python3.10
		
		sudo apt-get install python3.10
		
		sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2
		
		sudo update-alternatives --config python3
		(type 2 to point to Python 3.10)
		
		git clone https://github.com/pypa/setuptools.git && cd setuptools && sudo python3.10 setup.py install
		
		sudo apt install python3.10-distutils
		curl https://bootstrap.pypa.io/get-pip.py | sudo python3
```

I think that I made a mistake by upgrading Python,   I want to revert it back to Python 3.6 and delete Python 3.10. The advice from Python expert is to never upgrade Python in Linux system.

**Comment by glanzkaiser** [comment]
The Jupyter Notebook is working again now, I fix it through Julia. Thanks
