### ISSUE TITLE
Cannot start up a kernel when debugger initialization fails (cannot disable debugger)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13069]
## Description

When debuger initialization fails kernel dies and then in a loop it attempts to restart **without** backing off the debugger setting, so it fails miserably each 5 out of 5 times. That is not JupyterLab problem. The JupyterLab problem is that there is no way to disable debugger at this point:

![debuger-failure](https://user-images.githubusercontent.com/5832902/189236581-5dfe7c67-b111-4c43-8773-838dc435259e.gif)

## Reproduce

1. Create `code.py`
2. Start JuypterLab open notebook with ipykernel
3. Start debugger
4. See errors:
    <details>

    ```
    [I 2022-09-08 23:20:00.308 ServerApp] Kernel started: a3af9f9f-9a2a-4f36-bff5-090cb19b6795
    Traceback (most recent call last):
      File "/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
        from ipykernel import kernelapp as app
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 51, in <module>
        from .ipkernel import IPythonKernel
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 19, in <module>
        from .debugger import Debugger, _is_debugpy_available
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/debugger.py", line 22, in <module>
        from debugpy.server import api  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/server/__init__.py", line 7, in <module>
        import debugpy._vendored.force_pydevd  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/force_pydevd.py", line 28, in <module>
        pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
      File "/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 379, in <module>
        from _pydev_bundle._pydev_saved_modules import thread, threading
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 91, in <module>
        import code as _code;    verify_shadowed.check(_code, ['compile_command', 'InteractiveInterpreter'])
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 75, in check
        raise DebuggerInitializationError(msg)
    _pydev_bundle._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.
    
    i.e.: the module "code" could not be imported because it is shadowed by:
    /my/jupyter/root//code.py
    Please rename this file/folder so that the original module from the standard library can be imported.
    [I 2022-09-08 23:20:03.297 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
    Traceback (most recent call last):
      File "/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
        from ipykernel import kernelapp as app
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 51, in <module>
        from .ipkernel import IPythonKernel
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 19, in <module>
        from .debugger import Debugger, _is_debugpy_available
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/debugger.py", line 22, in <module>
        from debugpy.server import api  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/server/__init__.py", line 7, in <module>
        import debugpy._vendored.force_pydevd  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/force_pydevd.py", line 28, in <module>
        pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
      File "/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 379, in <module>
        from _pydev_bundle._pydev_saved_modules import thread, threading
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 91, in <module>
        import code as _code;    verify_shadowed.check(_code, ['compile_command', 'InteractiveInterpreter'])
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 75, in check
        raise DebuggerInitializationError(msg)
    _pydev_bundle._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.
    
    i.e.: the module "code" could not be imported because it is shadowed by:
    /my/jupyter/root//code.py
    Please rename this file/folder so that the original module from the standard library can be imported.
    [I 2022-09-08 23:20:06.316 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
    Traceback (most recent call last):
      File "/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
        from ipykernel import kernelapp as app
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 51, in <module>
        from .ipkernel import IPythonKernel
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 19, in <module>
        from .debugger import Debugger, _is_debugpy_available
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/debugger.py", line 22, in <module>
        from debugpy.server import api  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/server/__init__.py", line 7, in <module>
        import debugpy._vendored.force_pydevd  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/force_pydevd.py", line 28, in <module>
        pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
      File "/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 379, in <module>
        from _pydev_bundle._pydev_saved_modules import thread, threading
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 91, in <module>
        import code as _code;    verify_shadowed.check(_code, ['compile_command', 'InteractiveInterpreter'])
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 75, in check
        raise DebuggerInitializationError(msg)
    _pydev_bundle._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.
    
    i.e.: the module "code" could not be imported because it is shadowed by:
    /my/jupyter/root//code.py
    Please rename this file/folder so that the original module from the standard library can be imported.
    [I 2022-09-08 23:20:09.335 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
    Traceback (most recent call last):
      File "/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
        from ipykernel import kernelapp as app
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 51, in <module>
        from .ipkernel import IPythonKernel
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 19, in <module>
        from .debugger import Debugger, _is_debugpy_available
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/debugger.py", line 22, in <module>
        from debugpy.server import api  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/server/__init__.py", line 7, in <module>
        import debugpy._vendored.force_pydevd  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/force_pydevd.py", line 28, in <module>
        pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
      File "/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 379, in <module>
        from _pydev_bundle._pydev_saved_modules import thread, threading
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 91, in <module>
        import code as _code;    verify_shadowed.check(_code, ['compile_command', 'InteractiveInterpreter'])
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 75, in check
        raise DebuggerInitializationError(msg)
    _pydev_bundle._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.
    
    i.e.: the module "code" could not be imported because it is shadowed by:
    /my/jupyter/root//code.py
    Please rename this file/folder so that the original module from the standard library can be imported.
    [I 2022-09-08 23:20:12.354 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
    Traceback (most recent call last):
      File "/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
        from ipykernel import kernelapp as app
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 51, in <module>
        from .ipkernel import IPythonKernel
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 19, in <module>
        from .debugger import Debugger, _is_debugpy_available
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/debugger.py", line 22, in <module>
        from debugpy.server import api  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/server/__init__.py", line 7, in <module>
        import debugpy._vendored.force_pydevd  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/force_pydevd.py", line 28, in <module>
        pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
      File "/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 379, in <module>
        from _pydev_bundle._pydev_saved_modules import thread, threading
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 91, in <module>
        import code as _code;    verify_shadowed.check(_code, ['compile_command', 'InteractiveInterpreter'])
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 75, in check
        raise DebuggerInitializationError(msg)
    _pydev_bundle._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.
    
    i.e.: the module "code" could not be imported because it is shadowed by:
    /my/jupyter/root//code.py
    Please rename this file/folder so that the original module from the standard library can be imported.
    [I 2022-09-08 23:20:15.373 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
    Traceback (most recent call last):
      File "/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
        from ipykernel import kernelapp as app
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 51, in <module>
        from .ipkernel import IPythonKernel
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 19, in <module>
        from .debugger import Debugger, _is_debugpy_available
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/ipykernel/debugger.py", line 22, in <module>
        from debugpy.server import api  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/server/__init__.py", line 7, in <module>
        import debugpy._vendored.force_pydevd  # noqa
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/force_pydevd.py", line 28, in <module>
        pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
      File "/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 379, in <module>
        from _pydev_bundle._pydev_saved_modules import thread, threading
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 91, in <module>
        import code as _code;    verify_shadowed.check(_code, ['compile_command', 'InteractiveInterpreter'])
      File "/3.9.5/envs/ipython/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py", line 75, in check
        raise DebuggerInitializationError(msg)
    _pydev_bundle._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.
    
    i.e.: the module "code" could not be imported because it is shadowed by:
    /my/jupyter/root//code.py
    Please rename this file/folder so that the original module from the standard library can be imported.
    ```
    
    </details>
5. See that there is no way in GUI to recover other than close the notebook, kill the kernel, open the notebook; the debugger toggle is disabled, there is no command in command palette

## Expected behavior

- Ideal: JupyterLab disables debugger itself it it fails to start up
- Ok: the bug icon is active when kernel dies so that the next time it is not on
- Meh: there is a command in command palette to disable the debugger

## Context

- Operating System and version: Ubuntu 22
- JupyterLab version: 3.4.6 and 4.0.0a28

**Comment by krassowski** [comment]
Closing this one for now as I think this is not due to frontend request - ipykernel will import debugger whether it is enabled or not.
