### ISSUE TITLE
Dev tools console error: `TypeError: Cannot read properties of null (reading 'model')`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13164]
## Description

The following error is logged in the dev tools console when performing operations on the cells of a notebook:

```
index.es6.js:210 TypeError: Cannot read properties of null (reading 'model')
    at NotebookAdapter._activeCellChanged (notebooklspadapter.js:307:1)
    at invokeSlot (index.es6.js:457:1)
    at Object.emit (index.es6.js:415:1)
    at Signal.emit (index.es6.js:99:1)
    at set activeCellIndex [as activeCellIndex] (widget.js:946:1)
    at Notebook.onCellRemoved (widget.js:1461:1)
    at Notebook._removeCell (widget.js:580:1)
    at widget.js:457:1
    at Array.forEach (<anonymous>)
    at Notebook._onCellsChanged (widget.js:443:1)
```

Looks like this is originating from this line:

https://github.com/jupyterlab/jupyterlab/blob/65b4d7e727aed343160d81fad7f1871758ff7f22/packages/notebook/src/notebooklspadapter.ts#L401

## Reproduce

1. Create a new notebook
2. Add some cells
3. Select All
4. Delete

https://user-images.githubusercontent.com/591645/193529799-9eb3982e-3728-409d-8588-50dcaefc6a20.mp4

## Expected behavior

There should not be an error message in the dev tools console.

## Context

- Operating System and version: Fedora 36
- Browser and version: Chromium 106
- JupyterLab version: 4.0.0a29

**Comment by jtpio** [comment]
cc @trungleduc since this might be related to https://github.com/jupyterlab/jupyterlab/pull/12534

**Comment by trungleduc** [comment]
Thanks @jtpio, I will take a loot at it.
