### ISSUE TITLE
Search broken in files for specific patterns, causes infinite error loop

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13283]
## Description

Search broken in files for specific patterns, causes infinite error loop

## Reproduce

1. Create a text file with content `a-b`
2. Open search bar; you should see:
   ![Screenshot from 2022-10-23 00-27-12](https://user-images.githubusercontent.com/5832902/197366037-eba36601-bcaf-40a4-8d13-57140388a456.png)
3. Enter `a-b` to into the searchbar
4. See the search bar gets hidden, file becomes unresponsive, and infinite flood of errors in console
    ![Screenshot from 2022-10-23 00-28-37](https://user-images.githubusercontent.com/5832902/197366066-b4a5dac5-4a0c-43b6-a119-c8d54ccfd43a.png)

Errors:

```js
Failed to parse expression a-b SyntaxError: Invalid regular expression: /a\-b/: Invalid escape (at index.js:154:1)
    at new RegExp (<anonymous>)
    at new RegExpCursor (index.js:154:1)
    at FileEditorSearchProvider._findNext (searchprovider.ts:453:18)
    at FileEditorSearchProvider._startQuery (searchprovider.ts:173:30)
    at async SearchDocumentModel._updateSearch (searchmodel.ts:269:9)
```

```js     
Uncaught Error: Objects are not valid as a React child (found: SyntaxError: Invalid regular expression: /a\-b/: Invalid escape). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13231:1)
    at reconcileChildFibers (react-dom.development.js:14133:1)
    at reconcileChildren (react-dom.development.js:16990:1)
    at updateHostComponent (react-dom.development.js:17632:1)
    at beginWork (react-dom.development.js:19080:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22779:1)
````

```js
The above error occurred in the <div> component:

    at div
    at SearchOverlay (http://127.0.0.1:8889/static/lab/packages_documentsearch_lib_index_js.1c5a630e18e6f8aace2f.js:1070:9)
````

## Expected behavior

Search works in files.

## Context

- Browser and version: Edge (Chromium)
- JupyterLab version: HEAD/4.0.0a30

**Comment by krassowski** [comment]
>> The parseQuery needs also to be safer surrounding with try-catch because it can fail easily if the user has regexp on.

So we already have try-catch here, it is just that the error handling results in React errors downstream:

![Screenshot from 2023-02-12 13-37-35](https://user-images.githubusercontent.com/5832902/218314390-2b536eab-25b7-4316-8b19-dd036df57722.png)

I bet this is because `_parsingError` should be a string but is assigned an `Error` object.

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/documentsearch/src/searchmodel.ts#L319

I will include a fix in https://github.com/jupyterlab/jupyterlab/pull/13884
