### ISSUE TITLE
Example CI is failing on master

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13481]
## Description

Recently the examples job are failing with the following error:

```
 error >> WebSocket connection to 'ws://localhost:8888/foo/api/kernels/a1b7ca87-4025-4394-91b7-917b42db4d1a/channels?session_id=fd82a883-fb34-4e78-b7a6-792d33ab0ca4' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

As we use the latest Jupyter Server v2 release candidate, it may be a side effect of https://github.com/jupyter-server/jupyter_server/pull/1047

Friendly ping to @Zsailer 

## Reproduce

See for example https://github.com/jupyterlab/jupyterlab/actions/runs/3534539836/jobs/5940893186

## Expected behavior

No error

**Comment by davidbrochart** [comment]
I opened https://github.com/jupyter-server/jupyter_server/pull/1110.

**Comment by jtpio** [comment]
Looks like the examples check is still failing consistently. For example on the latest commit on `master`: https://github.com/jupyterlab/jupyterlab/actions/runs/3685583836/jobs/6236731860

**Comment by jtpio** [comment]
> I opened [jupyter-server/jupyter_server#1110](https://github.com/jupyter-server/jupyter_server/pull/1110).

Normally the fix should have been released in `jupyter_server` now right? Should we re-open this issue?

**Comment by jtpio** [comment]
> Should we re-open this issue?

The issue is different, so we can open a new one:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/ipykernel/__init__.py", line 5, in <module>
    from .connect import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/ipykernel/connect.py", line 11, in <module>
    import jupyter_client
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/jupyter_client/__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/traitlets/__init__.py", line 4, in <module>
    from . import traitlets
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/traitlets/traitlets.py", line 44, in <module>
    import inspect
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/inspect.py", line 138, in <module>
    import dis
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/dis.py", line 244, in <module>
    _Instruction = collections.namedtuple(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/collections/__init__.py", line 498, in namedtuple
    doc = _sys.intern(f'Alias for field number {index}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab/jupyterlab/issues/13587
