### ISSUE TITLE
Possible bug in "writing docs" documentation

### ISSUE THREAD

**Issue by ericsnekbytes** [jupyterlab/jupyterlab#13548]
## Description

The JupyterLab [developer guide for writing docs](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#writing-documentation) says that to build the documentation:

> "You can create an environment to build the documentation using conda create -f environment.yml, and you can build the documentation by running make html. The entry point to the built docs will then be in docs/build/index.html."

As of commit **e658b6f28e3501968e7fe8e211677c5378be14d0** on master, there is no docs/environment.yml file. Running `pip install ".[docs]"` and running `make html` in the docs folder (in a clean clone of the Lab repo, in a new conda environment) also gives an error:

```
# Sphinx version: 5.3.0

Python version: 3.10.8 (CPython)
Docutils version: 0.19
Jinja2 version: 3.1.2
Last messages:
Loaded extensions:
Traceback (most recent call last):
File "/Users/egentry/workspace_ana/armconda/envs/docs2/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
File "/Users/egentry/workspace_ana/armconda/envs/docs2/lib/python3.10/site-packages/sphinx/application.py", line 237, in init
self.config.setup(self)
File "/Users/egentry/workspace_ana/ts/jupyterlab/docs/source/conf.py", line 380, in setup
build_api_docs(outdir)
File "/Users/egentry/workspace_ana/ts/jupyterlab/docs/source/conf.py", line 124, in build_api_docs
check_call(jlpm, cwd=str(root))
File "/Users/egentry/workspace_ana/armconda/envs/docs2/lib/python3.10/subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', '/Users/egentry/workspace_ana/ts/jupyterlab/jupyterlab/staging/yarn.js']' returned non-zero exit status 1.
/var/folders/gd/_3z74zks7dl2z3h4xn_5svxr0000gn/T/sphinx-err-j6g70s29.log (END)
```

## Expected behavior

The environment.yml file exists, allowing the conda environment to be installed, and make html in the docs folder to successfully run.

## Context

Operating System and version: MacOS 12.4
Browser and version: Version 107.0.5304.110 (Official Build) (arm64)
JupyterLab version: Version 3.5.0

**Comment by ericsnekbytes** [comment]
I can now see that, on 3.6.x branch, there's a docs/environment.yml file. If I make a new conda environment from that file on that branch, and run make html, I get:

> # Sphinx version: 5.3.0
> # Python version: 3.8.15 (CPython)
> # Docutils version: 0.17.1 release
> # Jinja2 version: 3.1.2
> # Last messages:
> 
> # Loaded extensions:
> Traceback (most recent call last):
>   File "/Users/egentry/workspace_ana/armconda/envs/jupyterlab_documentation/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
>     app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
>   File "/Users/egentry/workspace_ana/armconda/envs/jupyterlab_documentation/lib/python3.8/site-packages/sphinx/application.py", line 237, in __init__
>     self.config.setup(self)
>   File "/Users/egentry/workspace_ana/ts/jupyterlab/docs/source/conf.py", line 271, in setup
>     build_api_docs(app.outdir)
>   File "/Users/egentry/workspace_ana/ts/jupyterlab/docs/source/conf.py", line 111, in build_api_docs
>     check_call(jlpm, cwd=root)
>   File "/Users/egentry/workspace_ana/armconda/envs/jupyterlab_documentation/lib/python3.8/subprocess.py", line 364, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['node', '/Users/egentry/workspace_ana/ts/jupyterlab/docs/source/../../jupyterlab/staging/yarn.js']' returned non-zero exit status 1.
> /var/folders/gd/_3z74zks7dl2z3h4xn_5svxr0000gn/T/sphinx-err-rsrzn17p.log (END)

**Comment by fcollonval** [comment]
Thanks for reporting @ericsnekbytes 

Indeed the documentation needs to be updated to as we move away from a conda environment to use optional dependencies. But unfortunately it also requires `nodejs` that is not available as Python package. This is needed because we build the documentation of the Javascript API.
The final error you are seeing is because some nodejs dependencies have binaries that are not available for you platform. I would suggest trying to use an older version of nodejs like 16 or 18. There is a higher change the required package is available for you (no promise as ARM MacOS support is not yet vastly supported).

**Comment by fcollonval** [comment]
If you don't care about building the JavaScript API documentation, you can comment the following line:

https://github.com/jupyterlab/jupyterlab/blob/e658b6f28e3501968e7fe8e211677c5378be14d0/docs/source/conf.py#L379-L380

**Comment by ericsnekbytes** [comment]
I haven't tried commenting out the JS API docs yet, but I'm adding the error I got running on a Linux x86_64 machine, which I was expecting to work...I've now tried on m1 mac, m1 mac with rosetta, Win11 x86_64, and Linux x86_64 and it looks like they're all failing on this canvas build step. I looked at the github repo for canvas and don't see the binary that's being fetched, it gives a 404.

```
(jupyterlab_documentation) egentry@demouser-DGX-Station:~/jupyterlab/docs$ make html
Running Sphinx v5.3.0
making output directory... done
Building jupyterlab API docs
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > typedoc@0.21.2" has unmet peer dependency "typescript@4.0.x || 4.1.x || 4.2.x || 4.3.x".
warning " > @jupyterlab/ui-components@3.6.0-alpha.5" has unmet peer dependency "react@^17.0.1".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/example-federated-middle > @lumino/coreutils@1.12.1" has unmet peer dependency "crypto@1.0.1".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/codemirror > y-codemirror@3.0.1" has unmet peer dependency "yjs@^13.5.17".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/ui-components > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/galata > svgo-loader@2.2.2" has unmet peer dependency "svgo@^1.0.0".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/buildutils > verdaccio > clipanion@3.1.0" has unmet peer dependency "typanion@*".
warning "workspace-aggregator-296c8417-777a-4e6f-9ac9-bdce81f336db > @jupyterlab/ui-components > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
[-/5] ⠐ waiting...
[-/5] ⠐ waiting...
[-/5] ⠐ waiting...
[4/5] ⠐ canvas
error /home/egentry/jupyterlab/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /home/egentry/jupyterlab/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5
node-pre-gyp info using node@18.12.1 | linux | x64
node-pre-gyp info check checked for "/home/egentry/jupyterlab/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@18.12.1 (node-v108 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@18.12.1 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@18.12.1 | linux | x64
gyp info find Python using Python version 3.8.15 found at "/home/egentry/miniconda3/envs/jupyterlab_documentation/bin/python"
gyp http GET https://nodejs.org/download/release/v18.12.1/node-v18.12.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.12.1/node-v18.12.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.12.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.12.1/SHASUMS256.txt
(node:11439) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /home/egentry/miniconda3/envs/jupyterlab_documentation/bin/python
gyp info spawn args [
gyp info spawn args   '/home/egentry/jupyterlab/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/egentry/jupyterlab/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/egentry/jupyterlab/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/egentry/.cache/node-gyp/18.12.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/egentry/.cache/node-gyp/18.12.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/egentry/jupyterlab/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/egentry/.cache/node-gyp/18.12.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/egentry/jupyterlab/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/egentry/jupyterlab/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 4.15.0-122-generic
gyp ERR! command "/home/egentry/miniconda3/envs/jupyterlab_documentation/bin/node" "/home/egentry/jupyterlab/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/egentry/jupyterlab/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/egentry/jupyterlab/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /home/egentry/jupyterlab/node_modules/canvas
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/egentry/miniconda3/envs/jupyterlab_documentation/bin/node /home/egentry/jupyterlab/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/egentry/jupyterlab/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/egentry/jupyterlab/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/egentry/jupyterlab/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 4.15.0-122-generic
node-pre-gyp ERR! command "/home/egentry/miniconda3/envs/jupyterlab_documentation/bin/node" "/home/egentry/jupyterlab/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/egentry/jupyterlab/node_modules/canvas
node-pre-gyp ERR! node -v v18.12.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute '/home/egentry/miniconda3/envs/jupyterlab_documentation/bin/node /home/egentry/jupyterlab/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/egentry/jupyterlab/node_m





Exception occurred:
  File "/home/egentry/miniconda3/envs/jupyterlab_documentation/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', '/home/egentry/jupyterlab/docs/source/../../jupyterlab/staging/yarn.js']' returned non-zero exit status 1.
The full traceback has been saved in /tmp/sphinx-err-ggc4kbgn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```

**Comment by ericsnekbytes** [comment]
@fcollonval I don't see those lines in the conf.py in 3.6.x. It looks like those lines you mentioned are in master, but master is missing the environment.yml (which is why I'm on 3.6.x). Node should be available to install as a conda package, into a conda environment (the node binary just goes to the bin folder in that environment)...what did you mean by optional dependencies? I've spent a huge amount of time just trying to get the docs to build, do you know what changes are being made/what the process should be now?

**Comment by fcollonval** [comment]
Hey @ericsnekbytes 

For 3.6.x the line is

https://github.com/jupyterlab/jupyterlab/blob/288bd2da202bd8eb5e8367bc79f61a2bb20692af/docs/source/conf.py#L271

Regarding the annoying canvas package, I strongly advice using an older LTS version of nodejs (to be more specific use 16.x). Binary packages for node (and notoriously the `canvas`) are *..redacted..* :wink:

**Comment by ericsnekbytes** [comment]
@fcollonval Thanks, that change allowed me to build the extension tutorial docs locally, so I should be able to finish work on improvements/bug fixes to that page now. I would also (separately) like to document the new process so that the current "writing docs" instructions aren't broken...contributors should see working instructions on the current page, so that's my eventual goal.

**Comment by MMesch** [comment]
@fcollonval the triaging agent identified this issue as not relevant anymore. Do you think we can close it, given that the new doc building commands seem to be stated in the documentation for quite a while ago now, or is there a specific reason for keeping it open tagged as reference?
