### ISSUE TITLE
Terminal section disappears after page reload

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#13570]
## Description

In Jupyterlab v4.0.0a31, after opening a terminal and reloading the browser page, the terminal section is no longer visible.

https://user-images.githubusercontent.com/4711805/206923267-f1da5388-5b2b-463c-96cf-b4d30e80069e.mp4

## Reproduce

1. Open JupyterLab v4.0.0a31.
2. Open a terminal.
3. See the terminal listed in the terminal section.
4. Reload the browser page.
5. See that the terminal section disappeared.

## Expected behavior

The terminal section should not disappear.

## Context

- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Google Chrome 108.0.5359.98
- JupyterLab version: 4.0.0a31

**Comment by jweill-aws** [comment]
Not reproducible on JupyterLab 3.5.1; possible regression.

**Comment by krassowski** [comment]
The traceback is:

```js
ReferenceError: Cannot access 'RunningTerminal' before initialization
    at index.ts:295:50
    at Array.map (<anonymous>)
    at Object.running (index.ts:295:37)
    at new Section (index.tsx:235:37)
    at RunningSessions.addSection (index.tsx:348:20)
    at invokeSlot (index.es6.js:457:1)
    at Object.emit (index.es6.js:415:1)
    at Signal.emit (index.es6.js:99:1)
    at RunningSessionManagers.add (index.tsx:117:17)
    at addRunningSessionManager (index.ts:292:12)
```
