### ISSUE TITLE
Example CI is failing on `master` and PRs

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13587]
## Description

Similar to https://github.com/jupyterlab/jupyterlab/issues/13481

But opening a new issue since the failure is different now:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/ipykernel/__init__.py", line 5, in <module>
    from .connect import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/ipykernel/connect.py", line 11, in <module>
    import jupyter_client
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/jupyter_client/__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/traitlets/__init__.py", line 4, in <module>
    from . import traitlets
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/traitlets/traitlets.py", line 44, in <module>
    import inspect
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/inspect.py", line 138, in <module>
    import dis
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/dis.py", line 244, in <module>
    _Instruction = collections.namedtuple(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/collections/__init__.py", line 498, in namedtuple
    doc = _sys.intern(f'Alias for field number {index}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Reproduce

Happening on the latest commit on `master`: https://github.com/jupyterlab/jupyterlab/commit/0adbcfee9e5a74d9446e3a9edd969cbe656771a5

https://github.com/jupyterlab/jupyterlab/actions/runs/3685583836/jobs/6236731860

And any other PR, for example: https://github.com/jupyterlab/jupyterlab/actions/runs/3684478101/jobs/6234263009

## Expected behavior

The check should pass.

## Context

https://github.com/jupyterlab/jupyterlab/issues/13481

**Comment by fcollonval** [comment]
The error inducing the test failure is not the one resulting in the above mentioned traceback.

It is the browser console error:

```
error >> Exception opening new comm
```

The traceback is induced by the kernel being stop with `KeyboardInterrupt` (so it is _expected_ - in the sense that it can happen when the interruption happens very quickly).

**Comment by jtpio** [comment]
Closing since the `examples` check now seems to be passing on the latest `master` and new PRs.

Likely fixed by https://github.com/ipython/ipykernel/pull/1056.
