### ISSUE TITLE
HTML viewer fails to render some pages on chrome

### ISSUE THREAD

**Issue by vincent-grosbois** [jupyterlab/jupyterlab#13595]
## Description
Using ipywidgets, I managed to export some widgets to a standalone HTML file. ([test.zip](https://github.com/jupyterlab/jupyterlab/files/10232070/test.zip) )
When I open this HTML file in my browser (chrome / firefox), this works well: it shows a grid after some loading time.
When I open this HTML from JupyterLab (with "trust HTML" on), it renders well on firefox, but it fails to render properly on chrome. (while it renders correctly on chrome if I open it just from the browser without jupyter)

## Reproduce

check out the HTML file attached
- launch it from chrome browser: should work
- launch it from firefox browser: should work
- launch it from firefox browser through jupyter lab HTML viewer: should work
- launch it from chrome browser through jupyter lab HTML viewer: **does not work**
- 
In chrome console log I get the following 2 errors:
```
require.min.js:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:8888/login?next=%2Ffiles%2Fipyaggrid.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
``` (this one in yellow)
and
```
embed-amd.js:16 TypeError: Cannot read properties of undefined (reading 'AgGridModel')
    at embed-amd.js:16:586697
    at async xc.loadModelClass (embed-amd.js:16:585110)
    at async xc._make_model (embed-amd.js:16:581595)
```
(this one in red)

## Expected behavior
HTML renders correctly on chrome from jupyterlab


Note that I opened the same issue here : https://github.com/jupyter-widgets/ipywidgets/issues/3652 in case it's an ipywidget issue. But this seems now more like a jupyterlab  issue knowing that the file renders OK in chrome without jupyterlab

Can anyone help me shed some light on this? thanks !

**Comment by jweill-aws** [comment]
CORB is documented as a Chrome/Chromium feature here: https://www.chromium.org/Home/chromium-security/corb-for-developers/ . It is possible to disable CORB as a Chrome user, and it is also possible to modify the HTML we serve from JupyterLab to avoid problems with it.

I've accepted this issue, as based on the reporting you did, it seems like the problem is isolated to the htmlviewer package.

**Comment by vincent-grosbois** [comment]
Thank you!
I'm not 100% sure it's due to CORB though, the console error for this is "just" in yellow
