### ISSUE TITLE
HTML validation error in console for extension manager

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13664]
## Description

```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at a
    at li
    at p (-node_modules_react-paginate_dist_react-paginate_js-node_modules_semver_index_js.073d91b924a13a8f396f.js:548:3724)
    at ul
    at o (vendors-node_modules_react-paginate_dist_react-paginate_js-node_modules_semver_index_js.073d91b924a13a8f396f.js:548:6557)
    at div
    at div
    at ListView (/packages_extensionmanager_lib_index_js.ee6ace975db8b9f0a079.js:613:13)
```

## Reproduce

1. Open latest dev version of JupyterLab 4.0
2. Open browser console

## Expected behavior

No error

## Context

- Browser and version: Chrome
- JupyterLab version: around 4.0.0a31

**Comment by JasonWeill** [comment]
Here's an offending nested `a` tag, in the page list:

```html
<li class="break-me"><a role="button" tabindex="0"><a href="">...</a></a></li>
```
