### ISSUE TITLE
Issues running Jupyter with different Conda environments

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#13855]
Recently I have more frequently issues running JupyterLab with conda. I have a dedicated minimal environment where I start Jupyter in, but now, out of the blue, it is not finding the libraries any more. 

```
py3) swacker@galactica:~>jupyter-lab --no-browser
Traceback (most recent call last):
  File "/home/swacker/.local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/home/swacker/.local/lib/python3.8/site-packages/jupyterlab/labapp.py", line 11, in <module>
    from jupyter_core.application import JupyterApp, NoStart, base_aliases, base_flags
ModuleNotFoundError: No module named 'jupyter_core'
```

While `python -c ...` does not return an error.
`(py3) swacker@galactica:~>python -c 'import jupyter_core'`

I tried reinstalling jupyter-lab in this environment, but the error persists.

**Comment by sorenwacker** [comment]
I removed the environment completely and set it up from scratch with

    mamba create -n py3 python=3.10 jupyter
