### ISSUE TITLE
js-debugger tests are failing on master

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13903]
```
FAIL  test/session.spec.ts (63.244 s)
```

I see several errors/warnings in logs, not sure which are the source of the problem:

<details>

<summary>An update to FramesComponent inside a test was not wrapped in act</summary>

```
    console.error
      Warning: An update to FramesComponent inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at model (/home/runner/work/jupyterlab/jupyterlab/packages/debugger/src/panels/callstack/body.tsx:41:3)

      53 |   useEffect(() => {
      54 |     const updateFrames = (): void => {
    > 55 |       setSelected(model.frame);
         |       ^
      56 |       setFrames(model.frames);
      57 |     };
      58 |     model.framesChanged.connect(updateFrames);

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (../../node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at dispatchAction (../../node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at setSelected (src/panels/callstack/body.tsx:55:7)
      at invokeSlot (../../node_modules/@lumino/signaling/src/index.ts:616:12)
      at Object.emit (../../node_modules/@lumino/signaling/src/index.ts:538:9)
      at Signal.emit (../../node_modules/@lumino/signaling/src/index.ts:179:13)
      at CallstackModel.emit [as frames] (src/panels/callstack/model.ts:34:25)
      at DebuggerService._getAllFrames (src/service.ts:781:33)
      at DebuggerService.restoreState (src/service.ts:423:7)
      at Object.<anonymous> (test/debugger.spec.ts:334:7)
```

</details>

<details>

<summary>An update to BreakpointsComponent inside a test was not wrapped in act</summary>

```
    console.error
      Warning: An update to BreakpointsComponent inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at model (/home/runner/work/jupyterlab/jupyterlab/packages/debugger/src/panels/breakpoints/body.tsx:40:3)

      55 |
      56 |     const restoreBreakpoints = (_: IDebugger.Model.IBreakpoints): void => {
    > 57 |       setBreakpoints(Array.from(model.breakpoints.entries()));
         |       ^
      58 |     };
      59 |
      60 |     model.changed.connect(updateBreakpoints);
```

</details>

<details>

<summary>`KeyboardInterrupt` in `opname = ['<%r>' % (op,) for op in range(256)]` </summary>

```
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/runpy.py", line 187, in _run_module_as_main
          mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/runpy.py", line 110, in _get_module_details

      at debug (../testing/src/start_jupyter_server.ts:70:15)

    console.debug
          __import__(pkg_name)
        File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/__init__.py", line 7, in <module>
          from .serverextension import load_jupyter_server_extension  # noqa
        File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/serverextension.py", line 4, in <module>
          from jupyter_server.utils import url_path_join
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/jupyter_server/utils.py", line 24, in <module>
          from jupyter_core.utils import ensure_async
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 4, in <module>
          import asyncio
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/__init__.py", line 8, in <module>
          from .base_events import *
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/base_events.py", line 39, in <module>
          from . import coroutines
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/coroutines.py", line 5, in <module>

      at debug (../testing/src/start_jupyter_server.ts:70:15)

    console.debug
          import inspect
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/inspect.py", line 38, in <module>

      at debug (../testing/src/start_jupyter_server.ts:70:15)

    console.debug
          import dis
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/dis.py", line 8, in <module>

      at debug (../testing/src/start_jupyter_server.ts:70:15)

    console.debug
          from opcode import *
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/opcode.py", line 36, in <module>

      at debug (../testing/src/start_jupyter_server.ts:70:15)

    console.debug
          opname = ['<%r>' % (op,) for op in range(256)]
        File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/opcode.py", line 36, in <listcomp>
          opname = ['<%r>' % (op,) for op in range(256)]
      KeyboardInterrupt

      at debug (../testing/src/start_jupyter_server.ts:70:15)

```

</details>

<details>

<summary>ECONNREFUSED ::1:8888</summary>

```
    console.debug
      Jupyter Server started

      at debug (../testing/src/start_jupyter_server.ts:77:17)

    console.warn
      FetchError {
        message: 'request to http://localhost:8888/api failed, reason: connect ECONNREFUSED ::1:8888',
        type: 'system',
        errno: 'ECONNREFUSED',
        code: 'ECONNREFUSED'
      }

      350 |       } catch (e) {
      351 |         // spin until we can connect to the server.
    > 352 |         console.warn(e);
          |                 ^
      353 |         await sleep(1000);
      354 |       }
      355 |     }
```

</details>

**Comment by krassowski** [comment]
The failing assertions are:

```
protocol › #stackTrace › should return the correct stackframes
expect(received).toEqual(expected) // deep equality

Expected: 3
Received: 5
```


```
protocol › #variables › should return the variables and their values
expect(received).toEqual(expected) // deep equality

Expected: "1"
Received: "2"
```

```
protocol › #continue › should proceed to the next breakpoint
thrown: "Exceeded timeout of 10000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

    at test/session.spec.ts:288:5
    at test/session.spec.ts:287:3
    at Object.<anonymous> (test/session.spec.ts:113:1)
```

**Comment by krassowski** [comment]
This appears to be uniquely attributable to debugpy 1.6.6 release. 1.6.5 works ok. There was only one commit in that release: https://github.com/microsoft/debugpy/commit/9fd3e7223514c66822077c0ac6394da6030e5b8b. We could force `PYDEVD_USE_FRAME_EVAL`; probably worth reporting upstream.

**Comment by fcollonval** [comment]
I was looking into this one too. The crazy thing is that it depends on the Python version. I created a fresh environment with Python 3.10.9 and it fails. But with my older dev environment using Python 3.9.15, it succeeds.

> Both have debugpy 1.6.6

Related issues on debugpy:
- https://github.com/microsoft/debugpy/issues/1180
- https://github.com/microsoft/debugpy/issues/1176 (I guess this one generating a crash was a big motivation for changing the flag)

**Comment by fcollonval** [comment]
Somehow similar to https://github.com/microsoft/debugpy/issues/1180, the behavior change is only happening in Python 3.10. I opened a fix that execute those tests with Python 3.11.

**Comment by SylvainCorlay** [comment]
Ping @fabioz who may not be aware of this regression in debugpy/pydev.
