### ISSUE TITLE
Non-empty notebooks appear as blank

### ISSUE THREAD

**Issue by Kostusas** [jupyterlab/jupyterlab#13930]
## Bug Description

Opening some existing notebooks with content inside shows a blank notebook without any cells. Duplicating the notebook fixes the issue in the duplicate.

Not sure if relevant, but we first noticed the issue in jupyterlab version 3.6.0rc1. After upgrading to 3.6.1, the problem seems to appear on the notebooks that were opened before a server upgrade with the jupyter packages changing.

Also not sure if related, but the server logs show:

```python
[D 2023-02-06 13:24:10.848 SingleUserLabApp handlers:267] Failed to write message
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 265, in send
        self.write_message(message, binary=True)
      File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 336, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
```

## Expected behavior

Opening a notebook should display its existing contents.

## Context

```
jupyter --version
Selected Jupyter core packages...
IPython          : 8.9.0
ipykernel        : 6.20.2
ipywidgets       : 8.0.4
jupyter_client   : 7.4.9
jupyter_core     : 5.1.5
jupyter_server   : 2.2.1
jupyterlab       : 3.6.1
nbclient         : 0.7.2
nbconvert        : 7.2.9
nbformat         : 5.7.3
notebook         : 6.5.2
qtconsole        : not installed
traitlets        : 5.8.1
```
```
mamba list|grep ydoc
jupyter_server_ydoc       0.6.1              pyhd8ed1ab_0    conda-forge
jupyter_ydoc              0.2.2              pyhd8ed1ab_0    conda-forge
```
```
mamba list|grep y-py
y-py                      0.5.5           py310h4426083_0    conda-forge
```

**Comment by akhmerov** [comment]
I have observed the same issue. Deleting the ystore database, as recommended in https://github.com/jupyterlab/jupyterlab/issues/13890#issuecomment-1420725072 didn't work. I now see 
```python
[D 2023-02-08 12:57:05.409 SingleUserLabApp mixins:553] Notifying Hub of activity 2023-02-08T11:24:33.667314Z
[I 2023-02-08 12:57:33.456 SingleUserLabApp handlers:89] Processed 0 Y patches in one minute
[I 2023-02-08 12:57:33.456 SingleUserLabApp handlers:90] Connected Y users: 100
[I 2023-02-08 12:58:33.457 SingleUserLabApp handlers:89] Processed 0 Y patches in one minute
[I 2023-02-08 12:58:33.457 SingleUserLabApp handlers:90] Connected Y users: 100
[I 2023-02-08 12:59:33.458 SingleUserLabApp handlers:89] Processed 0 Y patches in one minute
[I 2023-02-08 12:59:33.458 SingleUserLabApp handlers:90] Connected Y users: 100
[I 2023-02-08 13:00:33.459 SingleUserLabApp handlers:89] Processed 0 Y patches in one minute
[I 2023-02-08 13:00:33.459 SingleUserLabApp handlers:90] Connected Y users: 100
[I 2023-02-08 13:01:33.461 SingleUserLabApp handlers:89] Processed 0 Y patches in one minute
[I 2023-02-08 13:01:33.461 SingleUserLabApp handlers:90] Connected Y users: 100
```
in the logs

**Comment by akhmerov** [comment]
Perhaps related: a specific file in question is a `jupytext` `.py` notebook, an inspecting its source we observed that the source was duplicated many many times.

**Comment by RikBroekhoven** [comment]
I compared the first and last instance of a `jupytext` containing many duplications and find a difference in the metadata

<img width="476" alt="image" src="https://user-images.githubusercontent.com/46322887/217533383-1c0c3589-d054-4d3a-b2ca-f80caec9b59c.png">

**Comment by RikBroekhoven** [comment]
Duplication of source can easily be replicated by keeping the specific `jupytext` kernel open and letting my system go idle

**Comment by akhmerov** [comment]
I was able to reproduce the issue, although not easily in the following way:
1. Launch jupyterlab with both RTC and jupytext enabled.
2. Open the same `.py` file as both a plaintext document and a notebook using jupytext
3. Kill and restart the browser tab to simulate an abrupt disconnect.
4. Repeat a few times if it doesn't work immediately.

After doing so I observe that
1. notebook opens as blank (empty). It is editable and I am able to create a new cell, but it is impossible to save.
2. The server logs contain the error 1 from below.
3. Deleting `.jupyter-ystore.db`, as recommended by @davidbrochart in #13890 does not fix this behavior, and results in a broken database with a missing table (error 2).
4. Deleting the `.jupyter-ystore.db` *and* restarting the server fixes the problem.

So far I was unable to reproduce the duplication of file content.

### Error 1
```python
2023-02-09 14:52:53,854 - SingleUserLabApp - ERROR - Uncaught exception GET /user/anton-akhmerov/api/yjs/json:notebook:45a52267-c1ff-4da7-9311-adaa3531ad1b (145.94.146.90)
HTTPServerRequest(protocol='http', host='anton-akhmerov.io.quantumtinkerer.group', method='GET', uri='/user/anton-akhmerov/api/yjs/json:notebook:45a52267-c1ff-4da7-9311-adaa3531ad1b', version='HTTP/1.1', remote_ip='145.94.146.90')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
    await open_result
  File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 222, in open
    if self.room.document.source != model["content"]:
  File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
    return self.get()
  File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
    metadata=meta["metadata"],
KeyError: 'metadata'
```
### Error 2
```python
[E 2023-02-09 15:04:38.786 SingleUserLabApp web:1798] Uncaught exception GET /user/anton-akhmerov/api/yjs/json:notebook:45a52267-c1ff-4da7-9311-adaa3531ad1b (145.94.146.90)
    HTTPServerRequest(protocol='http', host='anton-akhmerov.io.quantumtinkerer.group', method='GET', uri='/user/anton-akhmerov/api/yjs/json:notebook:45a52267-c1ff-4da7-9311-adaa3531ad1b', version='HTTP/1.1', remote_ip='145.94.146.90')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 227, in open
        await self.room.ystore.encode_state_as_update(self.room.ydoc)
      File "/opt/conda/lib/python3.10/site-packages/ypy_websocket/ystore.py", line 45, in encode_state_as_update
        await self.write(update)
      File "/opt/conda/lib/python3.10/site-packages/ypy_websocket/ystore.py", line 242, in write
        cursor = await db.execute(
      File "/opt/conda/lib/python3.10/site-packages/aiosqlite/core.py", line 192, in execute
        cursor = await self._execute(self._conn.execute, sql, parameters)
      File "/opt/conda/lib/python3.10/site-packages/aiosqlite/core.py", line 137, in _execute
        return await future
      File "/opt/conda/lib/python3.10/site-packages/aiosqlite/core.py", line 110, in run
        result = function()
    sqlite3.OperationalError: no such table: yupdates
```

**Comment by hbcarlos** [comment]
Hi @Kostusas. Could you remove the `.jupyter-ystore.db` file and try restarting jupyterlab?
In addition, please make sure you are using jupyterlab v3.6.x with jupyter_server_ydoc v0.6.1 and jupyter_ydoc v0.2.2.

**Comment by hbcarlos** [comment]
Hi @akhmerov and @RikBroekhoven.

If there is any problem with `jupytext` duplicating the source, that's a different issue to the one reported here.
Could you open a new issue and ping me? I'll take a look as soon as I can.

**Comment by akhmerov** [comment]
I administer the same jupyterhub, and I confirm that we have the following versions installed:
```
jupyterlab                3.6.1 
jupyter_server_ydoc       0.6.1
jupyter_ydoc              0.2.2
```
Removing `.jupyter-ystore.db` and restarting lab works, as I described in https://github.com/jupyterlab/jupyterlab/issues/13930#issuecomment-1424247367, but does not prevent the problem from reoccurring.

**Comment by akhmerov** [comment]
I was unable to reproduce duplication so far, but I did confirm that the jupytext problem resulted in blanking of the notebook.

**Comment by hbcarlos** [comment]
> Removing .jupyter-ystore.db and restarting lab works, as I described in https://github.com/jupyterlab/jupyterlab/issues/13930#issuecomment-1424247367, but does not prevent the problem from reoccurring.

`.jupyter-ystore.db` is stored in the directory where JupyterLab is launched. Every time we bump `jupyter_server_ydoc`, there could be a change in the DB, and you need to remove it. When launching JupyterLab, we create a new DB if it was removed.

We pined `jupyter_server_ydoc` in JupyterLab 3.6.x, so that should not happen again, but it could happen if you alternate launching jupyterlab v4 and v3.6 in the same directory. See:

https://github.com/jupyterlab/jupyterlab/blob/aa07756d944c9f5ae9b4036a6d6422f8ae40c06f/setup.cfg#L41-L42

**Comment by davidbrochart** [comment]
BTW, there should be no need to manually remove `.jupyter-ystore.db`, it is [automatically taken care](https://github.com/y-crdt/ypy-websocket/pull/48).

**Comment by akhmerov** [comment]
I reproduced the issue with fewer stesp:
1. Open a notebook and make a couple of edits
2. Repeatedly kill and reload the chrome tab using chrome task manager to emulate a disconnect 
3. After around 5 reloads in my case the notebook was in the empty state and impossible to "save" or "save as".

**Comment by akhmerov** [comment]
> We pined jupyter_server_ydoc in JupyterLab 3.6.x, so that should not happen again, but it could happen if you alternate launching jupyterlab v4 and v3.6 in the same directory. See:

All the cases reported in this issue were observed without changing jlab/ydoc versions.

**Comment by akhmerov** [comment]
Multiple users of our hub report this issue appearing a couple of times a day, typically after a period of inactivity. The current workaround is to:
1. Copy the file
2. Remove the original
3. Rename the file back

Still this is disruptive, and we'll disable RTC for now.

**Comment by krassowski** [comment]
A similar error was reported in #13966 but **without** `jupytext` installation.

**Comment by akhmerov** [comment]
Judging by the description of #13966 there the problem was stale ydb across upgrades. Here we have observed the problem without jupytext, without a software upgrade; merely on a disconnect.

**Comment by fperez** [comment]
Thx for tagging the other issue @akhmerov - this sounds very similar to what I reported in #14031.

**Comment by tspspi** [comment]
I'd been able to reproduce the stale ydb bug (solvable by shutting down jupyter, removing the ydb, restarting) multiple times when running with jupyterlab 3.6.1 and y-py 0.5.9 when using the lab as a single user in collaborative mode via an lossy network connection (the browser had to reconnect every few minutes due to packet loss). This has been reproducible by introducing random packet loss on the same network too.

**Comment by ryanlovett** [comment]
We are seeing a similar issue with jupyterlab 3.6.1. If I dupe the notebook or upload it to a different user's server it works fine. If I rename the notebook it also loads fine. If I rename it back to its original name, it is blank again. 

We put the [YStores in /tmp](https://github.com/berkeley-dsep-infra/tmpystore).
No jupytext.

We have a repo2docker-based [singleuser image](https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/stat159/image).

@facusapienza21

**Comment by nwalters512** [comment]
We've observed the `KeyError: 'metadata'` error described up this thread since upgrading to jupyterlab 3.6.1. We're using RTC. Here's a snippet of the error log; the error seems to print roughly once per second.

```
2023-02-28T19:04:40.743867245Z [E 2023-02-28 19:04:40.743 ServerApp] Uncaught exception GET /pl/workspace/832716/container/api/yjs/json:notebook:e6c207fd-178e-46a2-9382-1a6d88591c7f (10.0.74.117)
2023-02-28T19:04:40.743894986Z     HTTPServerRequest(protocol='http', host='us.prairielearn.com', method='GET', uri='/pl/workspace/832716/container/api/yjs/json:notebook:e6c207fd-178e-46a2-9382-1a6d88591c7f', version='HTTP/1.1', remote_ip='10.0.74.117')
2023-02-28T19:04:40.743898494Z     Traceback (most recent call last):
2023-02-28T19:04:40.743901228Z       File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
2023-02-28T19:04:40.743904139Z         await open_result
2023-02-28T19:04:40.743906599Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 222, in open
2023-02-28T19:04:40.743909262Z         if self.room.document.source != model["content"]:
2023-02-28T19:04:40.743911780Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
2023-02-28T19:04:40.743914417Z         return self.get()
2023-02-28T19:04:40.743916803Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
2023-02-28T19:04:40.743919409Z         metadata=meta["metadata"],
2023-02-28T19:04:40.743921842Z     KeyError: 'metadata'
2023-02-28T19:04:42.138444832Z [E 2023-02-28 19:04:42.137 ServerApp] Uncaught exception GET /pl/workspace/832716/container/api/yjs/json:notebook:e6c207fd-178e-46a2-9382-1a6d88591c7f (10.0.74.117)
2023-02-28T19:04:42.138478312Z     HTTPServerRequest(protocol='http', host='us.prairielearn.com', method='GET', uri='/pl/workspace/832716/container/api/yjs/json:notebook:e6c207fd-178e-46a2-9382-1a6d88591c7f', version='HTTP/1.1', remote_ip='10.0.74.117')
2023-02-28T19:04:42.138483293Z     Traceback (most recent call last):
2023-02-28T19:04:42.138487018Z       File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
2023-02-28T19:04:42.138490942Z         await open_result
2023-02-28T19:04:42.138494348Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 222, in open
2023-02-28T19:04:42.138498259Z         if self.room.document.source != model["content"]:
2023-02-28T19:04:42.138501615Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
2023-02-28T19:04:42.138505127Z         return self.get()
2023-02-28T19:04:42.138508312Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
2023-02-28T19:04:42.138512610Z         metadata=meta["metadata"],
2023-02-28T19:04:42.138516046Z     KeyError: 'metadata'
2023-02-28T19:04:43.524225518Z [E 2023-02-28 19:04:43.523 ServerApp] Uncaught exception GET /pl/workspace/832716/container/api/yjs/json:notebook:e6c207fd-178e-46a2-9382-1a6d88591c7f (10.0.74.117)
2023-02-28T19:04:43.524273490Z     HTTPServerRequest(protocol='http', host='us.prairielearn.com', method='GET', uri='/pl/workspace/832716/container/api/yjs/json:notebook:e6c207fd-178e-46a2-9382-1a6d88591c7f', version='HTTP/1.1', remote_ip='10.0.74.117')
2023-02-28T19:04:43.524290737Z     Traceback (most recent call last):
2023-02-28T19:04:43.524294220Z       File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
2023-02-28T19:04:43.524298158Z         await open_result
2023-02-28T19:04:43.524301346Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 222, in open
2023-02-28T19:04:43.524305258Z         if self.room.document.source != model["content"]:
2023-02-28T19:04:43.524308758Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
2023-02-28T19:04:43.524312077Z         return self.get()
2023-02-28T19:04:43.524315490Z       File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
2023-02-28T19:04:43.524318603Z         metadata=meta["metadata"],
2023-02-28T19:04:43.524321861Z     KeyError: 'metadata'
```

**Comment by hbcarlos** [comment]
Hi @nwalters512. Please, make sure you are using the following:

```
jupyter_ydoc~=0.2.2 
jupyter_server_ydoc>=0.6.0,<0.7.0
```

**Comment by fperez** [comment]
Here's one more data point on the behavior of this strange problem, which we're also encountering on our hub with students. I made some changes to a version-controlled notebook, `nb2.ipynb`, that I then discarded by doing a `git restore nb2.ipynb` at the terminal after having closed the file. When I reopened it, it showed up blank.  Since I have learned that renaming it helps recover, I did the following:

1. At the terminal, renamed it to `f.ipynb`. It then opened fine.
2. With `f.ipynb` open, I right-clicked on the file manager in JupyterLab, and renamed it back to `nb2.ipynb`.

After 2, the following very strange thing occurred: the tab where it was opened all of a sudden flipped back to showing `f.ipynb` on it, despite the notebook now being called `nb2`. If I hover, I see that name, but the tab reads `f`, as shown here:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/57394/225163771-6e342967-a884-4fdd-a9f1-d814a53ebb05.png">

There's some strange inconsistency occurring internally, that is manifested by this behavior. It doesn't help much, but I figured right now every bit might provide a clue to how to ultimately fix this very problematic issue (which is really making RTC borderline unusable).

**Comment by fperez** [comment]
And one more clue - on one of those "blank"  notebooks, saving stops. While normally once RTC is on, we should not need to save notebooks anymore as the yjs store takes care of saving every second, for these notebooks, the saving actions don't happen. Here's what I get when I try to close that blank notebook:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/57394/225165268-da036ddd-028a-4543-82ce-c70f1bf81548.png">

Just one more breadcrumb, in the hopes it leads somewhere useful :)

**Comment by hbcarlos** [comment]
> There's some strange inconsistency occurring internally, that is manifested by this behavior. It doesn't help much, but I figured right now every bit might provide a clue to how to ultimately fix this very problematic issue (which is really making RTC borderline unusable).

Hi @fperez! This helps a lot, thank you so much. I'll take a look.

**Comment by TwoUnderscorez** [comment]
I am having the same issue on 3.6.2 and am getting the `KeyError: 'metadata'` error. 
(I am getting a white screen with no cells, like the notebook is still loading, not an empty notebook with one cell).

**Comment by ikubay** [comment]
I'm on 3.6.3 and I also still get the error mentioned above.
KeyError: 'metadata' on the jupyterlab console, and the notebook does not load.

I've experienced this on 3.6.2 as well, on different notebooks, on both a Windows machine and currently a Linux machine running Ubuntu 20.04.

```
[E 2023-04-12 14:04:52.284 ServerApp] Uncaught exception GET /api/yjs/json:notebook:ee5cf99b-a368-42e2-8524-2d2cb94617fe?sessionId=818b8f61-71ca-4000-b17a-f9497510a0d5 (73.116.114.51)
    HTTPServerRequest(protocol='http', host='<MY HOST>', method='GET', uri='/api/yjs/json:notebook:ee5cf99b-a368-42e2-8524-2d2cb94617fe?sessionId=818b8f61-71ca-4000-b17a-f9497510a0d5', version='HTTP/1.1', remote_ip='73.116.114.51')
    Traceback (most recent call last):
      File "/home/smol/.local/lib/python3.8/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
      File "/home/smol/.local/lib/python3.8/site-packages/jupyter_server_ydoc/handlers.py", line 230, in open
        if self.room.document.source != model["content"]:
      File "/home/smol/.local/lib/python3.8/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
        return self.get()
      File "/home/smol/.local/lib/python3.8/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
        metadata=meta["metadata"],
    KeyError: 'metadata'
```

**Comment by psychemedia** [comment]
I'm seeing this with JupyterLab 4.

- populated notebooks appear as blank, but with an option to add a new cell;
- new notebooks work fine.

**Comment by LnLcFlx** [comment]
Did anyone find a workaround for this?

**Comment by grzegorz700** [comment]
I faced a similar problem in a docker-based container with jupyter lab v4.3.1. In my case scenario. With the cell output of 3*266 lines, I got a black notebook except for the last run cell (in the middle of the notebook). The temporary fix was to save the notebook and reload it. It works, but as always the complex cell outputs were gone.

After updating to the [v4.3.2](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.3.2), the problem has been fixed for me.

**Comment by krassowski** [comment]
@grzegorz700 yes this was tracked in a separate issue, https://github.com/jupyterlab/jupyterlab/issues/16978.
