### ISSUE TITLE
Cannot stop shut down server

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#14324]
## Description

In some rare occasions, hitting Ctrl-C in the backend window doesn't stop the server with JupyterLab 4.0.0b0:
```
[I 2023-04-04 14:29:55.419 ServerApp] Starting buffering for 48475078-85af-4a83-985b-56b57780af55:7cf1209c-37b7-42de-ac07-5aa593b5a91c
^C[I 2023-04-04 14:29:56.490 ServerApp] interrupted
[I 2023-04-04 14:29:56.490 ServerApp] Serving notebooks from local directory: /home/david/github/davidbrochart/yjs-widgets
    1 active kernel
    Jupyter Server 2.5.0 is running at:
    http://localhost:8888/lab
        http://127.0.0.1:8888/lab
Shutdown this Jupyter server (y/[n])? ^C[C 2023-04-04 14:29:56.876 ServerApp] received signal 2, stopping
[I 2023-04-04 14:29:56.877 ServerApp] Shutting down 6 extensions
[I 2023-04-04 14:29:56.879 ServerApp] Shutting down 1 kernel
[I 2023-04-04 14:29:56.881 ServerApp] Kernel shutdown: 48475078-85af-4a83-985b-56b57780af55
[I 2023-04-04 14:30:01.495 ServerApp] No answer for 5s:
[I 2023-04-04 14:30:01.495 ServerApp] resuming operation...
^C[C 2023-04-04 14:30:53.017 ServerApp] received signal 2, stopping
^C[C 2023-04-04 14:30:53.182 ServerApp] received signal 2, stopping
^C[C 2023-04-04 14:30:57.519 ServerApp] received signal 2, stopping
^C[C 2023-04-04 14:30:57.689 ServerApp] received signal 2, stopping
^C[C 2023-04-04 14:30:58.265 ServerApp] received signal 2, stopping
^C[C 2023-04-04 14:30:58.446 ServerApp] received signal 2, stopping
^C[C 2023-04-04 14:30:58.587 ServerApp] received signal 2, stopping
^Z
[1]+  Stopped                 jupyter lab --ServerApp.token='' --ServerApp.password='' --no-browser
```
Then, after killing `jupyter-lab` and starting it again, opening the previous notebook yields this error:
```
[E 2023-04-04 14:31:59.647 ServerApp] Uncaught exception GET /api/collaboration/room/json:notebook:a5971ff4-5352-4f04-b6d4-5cca7953ce55?sessionId=d7b727f2-1b45-4222-b1ff-632b10e93253 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/api/collaboration/room/json:notebook:a5971ff4-5352-4f04-b6d4-5cca7953ce55?sessionId=d7b727f2-1b45-4222-b1ff-632b10e93253', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/david/micromamba/envs/yjs-widgets/lib/python3.11/site-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/home/david/micromamba/envs/yjs-widgets/lib/python3.11/site-packages/jupyter_collaboration/handlers.py", line 236, in open
        if self.room.document.source != model["content"]:
           ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/yjs-widgets/lib/python3.11/site-packages/jupyter_ydoc/ybasedoc.py", line 60, in source
        return self.get()
               ^^^^^^^^^^
      File "/home/david/micromamba/envs/yjs-widgets/lib/python3.11/site-packages/jupyter_ydoc/ynotebook.py", line 213, in get
        metadata=meta["metadata"],
                 ~~~~^^^^^^^^^^^^
    KeyError: 'metadata'
```
Removing `.jupyter_ystore.db` fixes the issue.
I'm opening an issue here for greater visibility, although it's maybe in `ypy-websocket`.

## Context

- Operating System and version: Ubuntu 22.04
- Browser and version: Chrome
- JupyterLab version: 4.0.0b0

**Comment by hbcarlos** [comment]
> In some rare occasions

Did you have a document open?

When a document is open in collaborative mode, jupyterlab doesn't shut down. I believe this is because tasks are running in the background (more precisely, the one watching for file changes on disk).

After implementing a [clean-up](https://github.com/jupyterlab/jupyter_collaboration/pull/121/commits/637f1b97800c3965f93e7e379386fa11180a317b) in jupyter_collaboration (for jupyterlab 4.0.0b0) I did not see it anymore.

This is also happening in jupyterlab 3.6.x. You could try to open a PR to jupyter-server-ydoc to see if that's the problem.

**Comment by hbcarlos** [comment]
The metadata error might be related to the store's versions. I'm looking into it.

**Comment by davidbrochart** [comment]
> Did you have a document open?

Yes.

> When a document is open in collaborative mode, jupyterlab doesn't shut down.

For me it almost never happens.

**Comment by bamage00** [comment]
Any updates here guys? Any way to fix this?

**Comment by sayhar** [comment]
Still happening for me as well
