### ISSUE TITLE
Jupyterlab cannot be installed on macOS with Python 3.12 (a07)

### ISSUE THREAD

**Issue by ZXRobotum** [jupyterlab/jupyterlab#14507]
Hello all,
I am currently trying in vain to install Jupyterlab on macOS or Linux with Python 3.12a07. 
I am also unable to install this under the Virtual Environment. 

What is the reason for this? Who can possibly help me here?
Unfortunately I cannot install Python 3.11 and Python 3.12 in parallel under macOS. The tool RUST was successfully installed under the 3.12 and in this regard also no error message comes. 

Thank you in advance for your help / support.

**Comment by JasonWeill** [comment]
@ZXRobotum [We recommend installing](https://jupyterlab.readthedocs.io/en/latest/getting_started/installation.html) JupyterLab using a package manager like conda, which allows you to use a different Python version for JupyterLab. Have you tried that?

If you haven't tried this or you're unable to, what are the errors you're seeing when trying to install JupyterLab with Python 3.12a07?

**Comment by JasonWeill** [comment]
Accepting this; @blink1073 noticed that `pip` won't work with Jupyter Server with Python 3.12. Not sure whether the root cause is with JupyterLab, Jupyter Server, or somewhere else.

**Comment by blink1073** [comment]
Specifically `pip debug` didn't work, ongoing testing is in that linked PR.

**Comment by JasonWeill** [comment]
Python 3.12 is now released; is this still an issue?

**Comment by krassowski** [comment]
For as long as it is not in our test matrix it is still an issue:

https://github.com/jupyterlab/jupyterlab/blob/2ff689965169cb5df6d1860e5b5c40952ed668ba/.github/workflows/linuxtests.yml#L18

It would be helpful if someone could open a PR adding it to the matrix and checking what else may needs to be fixed upstream for us to be able to support the latest Python version :)

**Comment by mimizone** [comment]
+1
I am also interested in the compatibility with python 3.12

**Comment by JasonWeill** [comment]
This issue is still open because, as @krassowski noted, Python 3.12 is not in our test matrix: 

https://github.com/jupyterlab/jupyterlab/blob/2ff689965169cb5df6d1860e5b5c40952ed668ba/.github/workflows/linuxtests.yml#L18

@mimizone Are you having difficulty using JupyterLab with Python 3.12? If so, could you please share your OS version, CPU type (e.g., x64 or Apple Silicon), your JupyterLab version, and how you installed JupyterLab (e.g., with `pip` or `conda`)? Thanks!

**Comment by mimizone** [comment]
I haven't tried yet because I read it is not working well in different threads, and most of all I currently use the docker-stack foundation image for jupyterhub as my base, which is not tested yet on 3.12 either.

I could try to test it by generating my own image in the coming weeks.

It will be running as a container on ubuntu:22.04 x86, in k8s, jupyterlab installed with pip

**Comment by johannahaffner** [comment]
I have Python 3.12.2, and jupyter installed through brew (jupyterlab is 4.1.4). Os is Sonoma 14.3, Apple M2 chip.

I have weird minor issues, like having to use jupyter lab instead of jupyter notebook to launch, and I have to copy-paste square and curly brackets. I use it to prototype and provide examples for a package I am developing on top of jax and diffrax. The actual code runs just fine.

**Comment by krassowski** [comment]
@johannahaffner to fix the square bracket issue got to Settings → Settings Editor → JSON Settings Editor → Keyboard Shortcuts → User → paste the code from below → save

```json
{
  "shortcuts": [
    {
      "args": {},
      "command": "inline-completer:next",
      "keys": [
          "Alt ]"
      ],
      "selector": ".jp-mod-completer-enabled",
      "disabled": true
    },
    {
      "args": {},
      "command": "inline-completer:previous",
      "keys": [
          "Alt ["
      ],
      "selector": ".jp-mod-completer-enabled",
      "disabled": true
    },
    {
      "args": {},
      "command": "inline-completer:invoke",
      "keys": [
          "Alt \\"
      ],
      "selector": ".jp-mod-completer-enabled",
      "disabled": true
    }
  ]
}
```

If you have existing keyboard shortcut overrides you may want to merge them accordingly.

Apologies that this is still a problem, I tried fixing this in JupyterLab 4.1.3 but had to revert the PR as it had other side effects.

**Comment by johannahaffner** [comment]
Hi @krassowski, thank you for your help! 

I tried it - should I open the settings from within jupyter lab, or jupyter notebook? jupyter notebook does not work for me right now, I have to go through jupyter lab. From there, I can access Keyboard Shortcuts, but it gives me a table rather than code and no option to edit them.

**Comment by johannahaffner** [comment]
> square bracket issue 

By the way, it works when I am using my US keyboard. It can't handle my otherwise quite exotic one (swiss german).

**Comment by johannahaffner** [comment]
Hi @krassowski, 

I figured out that I can switch between json and UI editors using the Settings Editor Form UI, which no longer gave me a blank window when opening the JSON Settings editor.

However, pasting the code gave me the following error: 

<img width="814" alt="Screenshot 2024-03-21 at 04 17 04" src="https://github.com/jupyterlab/jupyterlab/assets/38662446/8a8357a2-f1d2-48ae-a590-644dde281b3c">

Thank you for your help!

**Comment by krassowski** [comment]
@johannahaffner you are not pasting it in the `Keyboard Shortcuts` section, but in the `Settings Editor Form UI` section:

You **are** here:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/083dfa03-b8cf-4ace-b214-f8e76406bda3)

You **should** be here:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/73587c76-260b-4033-b396-3f1ae7dee43f)

**Comment by johannahaffner** [comment]
Then I think I tried navigating in the wrong order. I always clicked on the JSON Editor link in the Keyboard Section, after first enabling the JSON Editor. 

My apologies :)

**Comment by brian-rose** [comment]
Hi, I stumbled on this thread while dealing with an installation problem on a Mac laptop (osx-arm64).

Trying to create a standalone Jupyter environment with
```
mamba create --name myjup --channel conda-forge jupyterlab
```
seems to work, but one I activate the environment and try to launch a Jupyterlab session I get
```
TypeError: create.<locals>.Validator.__init__() got an unexpected keyword argument 'registry'
```
(full traceback pasted below).

I was able to resolve this by avoiding Python 3.12, e.g. this works as expected:
```
mamba create --name myjup_py311 --channel conda-forge jupyterlab "python<3.12"
```

Would it be useful to update the [conda-forge recipe for jupyterlab](https://github.com/conda-forge/jupyterlab-feedstock?tab=readme-ov-file) to pin to python < 3.12 (at least until issues with python 3.12 are resolved)? If so, I could take a stab at opening a PR for that.

Here's a full traceback from running `jupyterlab`:
```
Traceback (most recent call last):
  File "/Users/br546577/miniconda3/envs/myjup/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyterlab/__init__.py", line 8, in <module>
    from .handlers.announcements import (
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyterlab/handlers/announcements.py", line 15, in <module>
    from jupyterlab_server.translation_utils import translator
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyterlab_server/__init__.py", line 6, in <module>
    from .app import LabServerApp
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyterlab_server/app.py", line 10, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyter_server/extension/application.py", line 17, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyter_server/serverapp.py", line 39, in <module>
    from jupyter_events.logger import EventLogger
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyter_events/__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyter_events/logger.py", line 19, in <module>
    from .schema import SchemaType
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyter_events/schema.py", line 18, in <module>
    from .validators import draft7_format_checker, validate_schema
  File "/Users/br546577/miniconda3/envs/myjup/lib/python3.12/site-packages/jupyter_events/validators.py", line 44, in <module>
    JUPYTER_EVENTS_SCHEMA_VALIDATOR = Draft7Validator(
                                      ^^^^^^^^^^^^^^^^
TypeError: create.<locals>.Validator.__init__() got an unexpected keyword argument 'registry'
```

and here is the output from `mamba list`:
```

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

# packages in environment at /Users/br546577/miniconda3/envs/myjup:
#
# Name                    Version                   Build  Channel
anyio                     4.4.0              pyhd8ed1ab_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h02f2b3b_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py312h9f69965_1    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2024.6.2             hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312h8e38eb3_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
debugpy                   1.8.1           py312h20a0b95_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.2.1              pyha770c72_0    conda-forge
importlib_metadata        7.2.1                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.4             pyh57ce528_0    conda-forge
ipython                   8.25.0             pyh707e725_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py312h81bd7bf_0    conda-forge
jsonschema                4.22.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.22.0             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312h81bd7bf_0    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.1             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.2             pyhd8ed1ab_0    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
libcxx                    17.0.6               he7857fb_1    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libexpat                  2.6.2                hebf3989_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.46.0               hfb93653_0    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
markupsafe                2.1.5           py312he37b823_0    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  hb89a1cb_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
openssl                   3.3.1                hfb2fe0b_0    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
psutil                    5.9.8           py312he37b823_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyobjc-core               10.3.1          py312hbb55c70_0    conda-forge
pyobjc-framework-cocoa    10.3.1          py312hbb55c70_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.4          h30c5eda_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py312h02f2b3b_1    conda-forge
pyzmq                     26.0.3          py312hfa13136_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.18.1          py312h552d48e_0    conda-forge
send2trash                1.8.3              pyh31c8845_0    conda-forge
setuptools                70.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.18.1             pyh31c8845_0    conda-forge
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h7e5086c_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.6.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.5                hcc0f68c_4    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
```

**Comment by krassowski** [comment]
> Would it be useful to update the [conda-forge recipe for jupyterlab](https://github.com/conda-forge/jupyterlab-feedstock?tab=readme-ov-file) to pin to python < 3.12 (at least until issues with python 3.12 are resolved)?

No, I don't think so. JupyterLab does work with Python 3.12 in general so pinning it below would break things for users for whom it works. As of three months ago JupyterLab is being tested on CI against 3.12 (since https://github.com/jupyterlab/jupyterlab/pull/16009):

https://github.com/jupyterlab/jupyterlab/blob/f3643454fd59f8f71001af262a1d8e9a82ca477c/.github/workflows/linuxtests.yml#L18

and some MacOS test run on Python 3.12 too:

https://github.com/jupyterlab/jupyterlab/blob/f3643454fd59f8f71001af262a1d8e9a82ca477c/.github/workflows/macostests.yml#L18-L20

@brian-rose your issue appears to be with  `jupyter_events` possibly having incorrect version pin on `jsonschema` package, this was also reported in https://github.com/jupyter/jupyter_core/issues/369.

**Comment by krassowski** [comment]
I opened https://github.com/jupyter/jupyter_events/issues/99 to track that issue. Since JupyterLab in general can be installed on MacOS with Python 3.12 I think this issue can be closed. For anyone facing issues with new installations, please do look at the traceback carefully to report the issue in the appropriate repository (no worries if you cannot identify it, then do report here, but reporting it to the right repo just makes it more likely that the issue will be solved promptly because the set of maintainers between libraries is not necessarily overlapping :) )

**Comment by brian-rose** [comment]
Thanks for steering the issue to the right place @krassowski!
