### ISSUE TITLE
anaconda not open jupyter  notebook

### ISSUE THREAD

**Issue by abhya944** [jupyterlab/jupyterlab#14522]
Traceback (most recent call last):
File "/Users/abhya/anaconda3/bin/jupyter-lab", line 7, in 
from jupyterlab.labapp import main
File "/Users/abhya/anaconda3/lib/python3.10/site-packages/jupyterlab/__init__.py", line 7, in 
from .serverextension import load_jupyter_server_extension
File "/Users/abhya/anaconda3/lib/python3.10/site-packages/jupyterlab/serverextension.py", line 3, in 
from jupyter_server.utils import url_path_join
File "/Users/abhya/anaconda3/lib/python3.10/site-packages/jupyter_server/utils.py", line 18, in 
from tornado.httpclient import AsyncHTTPClient, HTTPClient, HTTPRequest
File "/Users/abhya/anaconda3/lib/python3.10/site-packages/tornado/httpclient.py", line 49, in 
from tornado import httputil, stack_context
File "/Users/abhya/anaconda3/lib/python3.10/site-packages/tornado/httputil.py", line 106, in 
class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by fcollonval** [comment]
Hey @abhya944 from the error message your python environment is likely broken. It says that you have tornado version 4.x installed when you should nowadays have 6.0.x.

I would advice reinstalling anaconda and also to leverage the environment feature to avoid installing tons of packages in the python environment.
See the documentation: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html

**Comment by JasonWeill** [comment]
@abhya944 Have you tried reinstalling Anaconda and setting your environment up again?
