### ISSUE TITLE
4.0.0: pep517 based build fails

### ISSUE THREAD

**Issue by kloczek** [jupyterlab/jupyterlab#14552]
## Description
Looks like something is wrong with pep517 based build of the `jupyterlab` module.

## Reproduce
Run |/usr/bin/python3 -sBm build -w --no-isolation` in project root directory.

## Expected behavior
pep517 based build should be OK.

## Context
- Operating System and version: Linux x86/64
- Browser and version: N/A
- JupyterLab version: 4.0.0

Here is build output.
<details>

```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
* Building wheel...
INFO:hatch_jupyter_builder.utils:Running jupyter-builder
INFO:hatch_jupyter_builder.utils:Building with buildapi.builder
INFO:hatch_jupyter_builder.utils:With kwargs: {'build_cmd': 'build:prod:minimize', 'path': 'jupyterlab/staging', 'source_dir': 'jupyterlab/staging', 'build_dir': 'jupyterlab/static', 'npm': ['node', 'yarn.js']}
INFO:hatch_jupyter_builder.utils:Installing build dependencies with npm.  This may take a while...
INFO:hatch_jupyter_builder.utils:> /usr/bin/node yarn.js install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @jupyterlab/cell-toolbar-extension@npm:4.0.0 doesn't provide react (p9f939), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/console-extension@npm:4.0.0 doesn't provide react (p93164), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/csvviewer-extension@npm:4.0.0 doesn't provide react (p59eb3), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/debugger-extension@npm:4.0.0 doesn't provide react (p35159), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/documentsearch-extension@npm:4.0.0 doesn't provide react (pd900a), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/extensionmanager-extension@npm:4.0.0 doesn't provide react (pd8fd2), requested by @jupyterlab/settingregistry
➤ YN0060: │ @jupyterlab/extensionmanager@npm:4.0.0 provides react (pb859a) with version 18.2.0, which doesn't satisfy what react-paginate requests
➤ YN0002: │ @jupyterlab/filebrowser-extension@npm:4.0.0 doesn't provide react (pcc4f8), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/fileeditor-extension@npm:4.0.0 doesn't provide react (p7fdda), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/htmlviewer-extension@npm:4.0.0 doesn't provide react (p68445), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/json-extension@npm:4.0.0 doesn't provide @types/react (pcc4c9), requested by react-json-tree
➤ YN0002: │ @jupyterlab/mainmenu-extension@npm:4.0.0 doesn't provide react (p68837), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/markdownviewer-extension@npm:4.0.0 doesn't provide react (pb878f), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/metadataform-extension@npm:4.0.0 doesn't provide react (p0de78), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/metadataform@npm:4.0.0 doesn't provide @rjsf/utils (p9a078), requested by @rjsf/core
➤ YN0002: │ @jupyterlab/metadataform@npm:4.0.0 doesn't provide @rjsf/utils (p0b7d3), requested by @rjsf/validator-ajv8
➤ YN0002: │ @jupyterlab/services@npm:7.0.0 doesn't provide react (p7bfc4), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/settingeditor-extension@npm:4.0.0 doesn't provide react (pdd4b3), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/statusbar-extension@npm:4.0.0 doesn't provide react (p53e3b), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/terminal-extension@npm:4.0.0 doesn't provide react (p6dd14), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/toc-extension@npm:6.0.0 doesn't provide react (p2a413), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/translation-extension@npm:4.0.0 doesn't provide react (pe1608), requested by @jupyterlab/settingregistry
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 342ms
➤ YN0000: ┌ Fetch step
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/lib/python3.8/site-packages/hatchling/build.py", line 56, in build_wheel
    return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
  File "/usr/lib/python3.8/site-packages/hatchling/builders/plugin/interface.py", line 150, in build
    build_hook.initialize(version, build_data)
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/plugin.py", line 87, in initialize
    raise e
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/plugin.py", line 82, in initialize
    build_func(self.target_name, version, **build_kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/jupyterlab-4.0.0/buildapi.py", line 20, in builder
    npm_builder(target_name, version, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/utils.py", line 113, in npm_builder
    run([*npm_cmd, "install"], cwd=str(abs_path))
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/utils.py", line 229, in run
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/node', 'yarn.js', 'install']' died with <Signals.SIGSEGV: 11>.

ERROR Backend subprocess exited when trying to invoke build_wheel
```
</details>

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- --------
alabaster                     0.7.13
asttokens                     2.2.1
Babel                         2.12.1
backcall                      0.2.0
build                         0.10.0
charset-normalizer            3.1.0
decorator                     5.1.1
distro                        1.8.0
docutils                      0.19
editables                     0.3
exceptiongroup                1.1.1
executing                     1.2.0
gpg                           1.20.0
hatch-jupyter-builder         0.8.3
hatchling                     1.17.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.6.0
iniconfig                     2.0.0
installer                     0.7.0
ipython                       8.12.0
jedi                          0.18.2
Jinja2                        3.1.2
libcomps                      0.1.19
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
matplotlib-inline             0.1.6
mdit-py-plugins               0.3.5
mdurl                         0.1.2
myst-parser                   1.0.0
packaging                     23.1
parso                         0.8.3
pathspec                      0.11.1
pexpect                       4.8.0
pickleshare                   0.7.5
pluggy                        1.0.0
prompt-toolkit                3.0.38
ptyprocess                    0.7.0
pure-eval                     0.2.2
Pygments                      2.15.1
pyproject_hooks               1.0.0
pytest                        7.3.1
pytest-mock                   3.10.0
python-dateutil               2.8.2
pytz                          2023.2
PyYAML                        6.0
requests                      2.30.0
setuptools                    67.7.2
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        6.2.1
sphinx_autodoc_typehints      1.22.0
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.6.2
tomli                         2.0.1
traitlets                     5.9.0
trove-classifiers             2023.5.7
typing_extensions             4.5.0
urllib3                       1.26.15
wcwidth                       0.2.6
wheel                         0.40.0
zipp                          3.15.0
```
</details>

**Comment by kloczek** [comment]
Closing because looks like issue is resolved in latest 4.0.2.
