### ISSUE TITLE
4.0.0 Context menu completely broken in Chrome

### ISSUE THREAD

**Issue by phish108** [jupyterlab/jupyterlab#14553]
## Description

I accidentally upgraded to 4.0.0. 

The context menu is not working at all in Chrome. 

The download option for notebooks is missing in Safari. The new "Download as Archive" has no effect.

## Reproduce

1. Open any Folder
2. Click on a notebook
3. right click/ menu click on the selected notebook 
4. see no context menu

## Expected behavior

see a context menu

## Context

- Operating System and version: Ubuntu from Jupyter/base-notebook:2023-05-15
- Browser and version: Chrome 113.0.5672 
- JupyterLab version: 4.0.0

<details><summary>Troubleshoot Output</summary>
<pre>
no meaningful output
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
no meaningful output
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/notebook (required ^3.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/coreutils (required ^1.11.0)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/signaling (required ^1.10.0)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/rendermime (required ^3.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/codeeditor (required ^3.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 2.0.0 from @jupyterlab/application-top of shared singleton module @lumino/messaging (required ^1.10.0)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/apputils (required ^3.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/settingregistry (required ^3.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 No satisfying version (^3.6.3) of shared module @jupyterlab/nbformat found in shared scope default.
Available versions: 4.0.0 from @jupyterlab/application-top
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/disposable (required ^1.10.0)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/codemirror (required ^3.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 6.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/coreutils (required ^5.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 7.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/services (required ^6.6.3)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/widgets (required ^1.37.2)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.7dd115740677e3b366fe.js:1 Unsatisfied version 2.0.0 from @jupyterlab/application-top of shared singleton module @lumino/algorithm (required ^1.9.0)
c @ remoteEntry.7dd115740677e3b366fe.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 18.2.0 from @jupyterlab/application-top of shared singleton module react (required ^17.0.1)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/coreutils (required ^1.11.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/signaling (required ^1.10.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 18.2.0 from @jupyterlab/application-top of shared singleton module react-dom (required ^17.0.1)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.0.0 from @jupyterlab/application-top of shared singleton module @lumino/algorithm (required ^1.9.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/translation (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 7.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/services (required ^6.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/statusbar (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 No satisfying version (^3.6.0-alpha.5) of shared module @jupyterlab/nbformat found in shared scope default.
Available versions: 4.0.0 from @jupyterlab/application-top
p @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/codeeditor (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/apputils (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.0.0 from @jupyterlab/application-top of shared singleton module @lumino/messaging (required ^1.10.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 6.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/coreutils (required ^5.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/widgets (required ^1.33.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/docmanager (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/mainmenu (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.0.0 from @jupyterlab/application-top of shared singleton module @lumino/properties (required ^1.8.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/codemirror (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/commands (required ^1.19.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 No satisfying version (^3.6.0-alpha.5) of shared module @jupyterlab/docregistry found in shared scope default.
Available versions: 4.0.0 from @jupyterlab/application-top
p @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.1.1 from @jupyterlab/application-top of shared singleton module @lumino/dragdrop (required ^1.13.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/application (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/ui-components (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/statedb (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/rendermime (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 No satisfying version (^3.6.0-alpha.5) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 4.0.0 from @jupyterlab/application-top
p @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/filebrowser (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 2.0.0 from @jupyterlab/application-top of shared singleton module @lumino/domutils (required ^1.8.0)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.4318d00d399dc15e3535.js:1 Unsatisfied version 4.0.0 from @jupyterlab/application-top of shared singleton module @jupyterlab/settingregistry (required ^3.6.0-alpha.5)
f @ remoteEntry.4318d00d399dc15e3535.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 2.1.1 of shared singleton module @lumino/signaling (required ^1.4.3)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 2.1.1 of shared singleton module @lumino/widgets (required ^1.16.1)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 No satisfying version (^3.0.7) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 4.0.0 from @jupyterlab/application-top
p @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/ui-components (required ^3.0.5)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 2.0.0 of shared singleton module @lumino/messaging (required ^1.4.3)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 2.1.1 of shared singleton module @lumino/dragdrop (required ^1.7.1)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 2.0.0 of shared singleton module @lumino/domutils (required ^1.2.3)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 2.0.0 of shared singleton module @lumino/algorithm (required ^1.3.3)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/console (required ^3.0.7)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/notebook (required ^3.0.8)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 2.1.1 of shared singleton module @lumino/coreutils (required ^1.5.3)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/application (required ^3.0.8)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.311df298e19cc62c55a3.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/apputils (required ^3.0.6)
f @ remoteEntry.311df298e19cc62c55a3.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 6.0.0 of shared singleton module @jupyterlab/coreutils (required ^5.5.2)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/translation (required ^3.5.2)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 7.0.0 of shared singleton module @jupyterlab/services (required ^6.5.2)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/ui-components (required ^3.5.2)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/settingregistry (required ^3.5.2)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/apputils (required ^3.5.2)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 4.0.0 of shared singleton module @jupyterlab/filebrowser (required ^3.5.2)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 2.0.0 of shared singleton module @lumino/algorithm (required ^1.9.0)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
remoteEntry.67c142c0e3860e5c4225.js:1 Unsatisfied version 2.1.1 of shared singleton module @lumino/widgets (required ^1.33.0)
d @ remoteEntry.67c142c0e3860e5c4225.js:1
812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1 Failed to create module: package: nbdime-jupyterlab; module: ./extension
F @ 812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1
812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1 Failed to create module: package: @jupyterlab/git; module: ./extension
F @ 812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1
812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1 Error: Shared module codemirror doesn't exist in shared scope default
    at i (remoteEntry.7dd115740677e3b366fe.js:1:4660)
    at remoteEntry.7dd115740677e3b366fe.js:1:5702
    at remoteEntry.7dd115740677e3b366fe.js:1:5610
    at 8681 (remoteEntry.7dd115740677e3b366fe.js:1:6407)
    at remoteEntry.7dd115740677e3b366fe.js:1:6898
    at Array.forEach (<anonymous>)
    at E.f.consumes (remoteEntry.7dd115740677e3b366fe.js:1:6728)
    at remoteEntry.7dd115740677e3b366fe.js:1:1020
    at Array.reduce (<anonymous>)
    at E.e (remoteEntry.7dd115740677e3b366fe.js:1:998)
(anonymous) @ 812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1
812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1 Error: Shared module codemirror doesn't exist in shared scope default
    at o (remoteEntry.4318d00d399dc15e3535.js:1:6507)
    at remoteEntry.4318d00d399dc15e3535.js:1:7591
    at remoteEntry.4318d00d399dc15e3535.js:1:7499
    at 8681 (remoteEntry.4318d00d399dc15e3535.js:1:9978)
    at remoteEntry.4318d00d399dc15e3535.js:1:10797
    at Array.forEach (<anonymous>)
    at k.f.consumes (remoteEntry.4318d00d399dc15e3535.js:1:10627)
    at remoteEntry.4318d00d399dc15e3535.js:1:1174
    at Array.reduce (<anonymous>)
    at k.e (remoteEntry.4318d00d399dc15e3535.js:1:1152)
(anonymous) @ 812.15b6650fc7a389aef94f.js?v=15b6650fc7a389aef94f:1
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 Language pack 'en_US' not installed!
fetch @ jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 Starting application in workspace: "default"
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 hub-extension: Found configuration  Object
383.79cef97ee2a6919173a6.js?v=79cef97ee2a6919173a6:1 JupyterLab extension @lckr/jupyterlab_variableinspector is activated!
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 Starting WebSocket: wss://jh-staging.esi.li/user/7622/api/kernels/9e04b7af-05e5-45f8-9a94-bec757c39322
261.a2645d40e3c11f54e546.js?v=a2645d40e3c11f54e546:1 JupyterLab extension jupyter-archive is activated!
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 TypeError: Cannot read properties of undefined (reading 'then')
    at 383.79cef97ee2a6919173a6.js?v=79cef97ee2a6919173a6:1:23807
    at m (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644740)
    at Object.l [as emit] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644416)
    at a.emit (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1642253)
    at O._onCurrentChanged (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:52401)
    at m (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644740)
    at Object.l [as emit] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644416)
    at a.emit (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1642253)
    at le._setWidgets (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1769209)
    at le._evtFocus (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1769422)
e.exceptionHandler @ jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 Starting WebSocket: wss://jh-staging.esi.li/user/7622/api/kernels/9e04b7af-05e5-45f8-9a94-bec757c39322
10jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 TypeError: Path must be a string. Received undefined
    at o (5440.137dd6a0aff3f644790b.js?v=137dd6a0aff3f644790b:1:3729)
    at Object.e [as basename] (5440.137dd6a0aff3f644790b.js?v=137dd6a0aff3f644790b:1:6615)
    at Object.n [as basename] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:418069)
    at isVisible (261.a2645d40e3c11f54e546.js?v=a2645d40e3c11f54e546:1:4813)
    at g.isVisible (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1604515)
    at get isVisible [as isVisible] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1719722)
    at Object.p [as computeCollapsed] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1715999)
    at Is.onUpdateRequest (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1709768)
    at Is.processMessage (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1661940)
    at b (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1634444)
f @ jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 TypeError: Cannot read properties of undefined (reading 'then')
    at 383.79cef97ee2a6919173a6.js?v=79cef97ee2a6919173a6:1:23807
    at m (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644740)
    at Object.l [as emit] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644416)
    at a.emit (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1642253)
    at O._onCurrentChanged (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:52401)
    at m (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644740)
    at Object.l [as emit] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1644416)
    at a.emit (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1642253)
    at le._setWidgets (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1769209)
    at le._evtFocus (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1769422)
e.exceptionHandler @ jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1
jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 Starting WebSocket: wss://jh-staging.esi.li/user/7622/api/kernels/b02bd7be-da46-439a-b6e4-b15f19eaab09
8jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1 TypeError: Path must be a string. Received undefined
    at o (5440.137dd6a0aff3f644790b.js?v=137dd6a0aff3f644790b:1:3729)
    at Object.e [as basename] (5440.137dd6a0aff3f644790b.js?v=137dd6a0aff3f644790b:1:6615)
    at Object.n [as basename] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:418069)
    at isVisible (261.a2645d40e3c11f54e546.js?v=a2645d40e3c11f54e546:1:4813)
    at g.isVisible (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1604515)
    at get isVisible [as isVisible] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1719722)
    at Object.p [as computeCollapsed] (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1715999)
    at Is.onUpdateRequest (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1709768)
    at Is.processMessage (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1661940)
    at b (jlab_core.c0a86c199b5057e75c0f.js?v=c0a86c199b5057e75c0f:1:1634444)
</pre>
</details>

**Comment by phish108** [comment]
OK, it seems that the extensions are the problem.
