### ISSUE TITLE
Flaky UI tests

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14947]
## Description

The `Visual Regression Tests` and `Visual Regression Documentation` CI checks are often flaky, which makes the CI checks appear as failing.

## Reproduce

Example run for https://github.com/jupyterlab/jupyterlab/pull/14944: https://github.com/jupyterlab/jupyterlab/actions/runs/5817952284/job/15773457526?pr=14944

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/e59cfdf5-0345-4786-a953-2dd5f14c79e4)

## Expected behavior

The check should not fail that often, so maintainers can review and merge PRs with more confidence.

## Context

Flaky tests lead to maintenance burden and CI fatigue on maintainers. One has to download the Playwright repo and carefully check the errors to assess whether the failure is related to the change.

Also other maintainers might not feel confident merging PRs if one of the checks is failing (which is understandable).

**Comment by jtpio** [comment]
> Example run for #14944: https://github.com/jupyterlab/jupyterlab/actions/runs/5817952284/job/15773457526?pr=14944

In this particular run the failure is caused by a (unrelated) snapshot mismatch:

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/113518a7-e4f7-4127-bdae-4b25f0714b5e)

**Comment by jtpio** [comment]
Here is another example of a failing UI test on the latest commit on `main` at the moment: 7b1effc02bb11e237f98bdf3c888862bc183e15d

[galata-debugger-failure.webm](https://github.com/jupyterlab/jupyterlab/assets/591645/10e9f16e-3543-4a8f-9479-e7f8f70574ae)

In this case it looks like the `add` function is not properly added to the notebook, which seems to indicate this is a real issue (or race condition) in the galata tests.

**Comment by jtpio** [comment]
> In this case it looks like the `add` function is not properly added to the notebook, which seems to indicate this is a real issue (or race condition) in the galata tests.

Looks like this code does not do what it is supposed to do:

https://github.com/jupyterlab/jupyterlab/blob/7b1effc02bb11e237f98bdf3c888862bc183e15d/galata/test/jupyterlab/debugger.test.ts#L320-L324

**Comment by krassowski** [comment]
Interestingly, for a split-second the notebook area has no cells at all.

investigating in https://github.com/krassowski/jupyterlab/pull/66:
- no uncaught errors nor relevant messages in console
- the `Debugger Variables › Copy to clipboard` is the most persistent failure
- switching windowing mode from `defer` (default) to `none` or `full` solves the issue

I wonder if this might be related to https://github.com/jupyterlab/jupyterlab/pull/14865.

**Comment by krassowski** [comment]
It seems that it fails due to `isAnyActive` short-circuiting the `setCell` operation.

https://github.com/jupyterlab/jupyterlab/blob/696751e7cfbaca0d60801cef323282562b26fa1f/galata/src/helpers/notebook.ts#L1061-L1068

**Comment by jtpio** [comment]
Another failure noticed in https://github.com/jupyterlab/jupyterlab/pull/15502, which may or may not already be addressed by some of the open PRs. Logging it here for reference:

```
Error: locator.waitFor: Error: strict mode violation: locator('.jp-RunningSessions-item.jp-mod-kernel').locator('text="Python 3 (ipykernel)"') resolved to 2 elements:
    1) <span class="jp-RunningSessions-itemLabel" title="Pyth…>Python 3 (ipykernel)</span> aka getByTitle('Python 3 (ipykernel): a7477aba-511c-4abd-b938-51e1210936c2')
    2) <span class="jp-RunningSessions-itemLabel" title="Pyth…>Python 3 (ipykernel)</span> aka getByTitle('Python 3 (ipykernel): 367fa08d-ebcf-45fa-9ae3-9bccba12bf9a\n\nnotebook\nPath: notebooks/Data.ipynb')
```

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/b4a230c4-7061-4a75-a848-031ac5f49cb1)

**Comment by jtpio** [comment]
Another failure noticed in https://github.com/jupyterlab/jupyterlab/pull/15502, which may or may not already be addressed by some of the open PRs. Logging it here for reference:


```
Error: locator.waitFor: Error: strict mode violation: locator('.jp-RunningSessions-item.jp-mod-kernel').locator('text="Python 3 (ipykernel)"') resolved to 2 elements:
    1) <span class="jp-RunningSessions-itemLabel" title="Pyth…>Python 3 (ipykernel)</span> aka getByTitle('Python 3 (ipykernel): a7477aba-511c-4abd-b938-51e1210936c2')
    2) <span class="jp-RunningSessions-itemLabel" title="Pyth…>Python 3 (ipykernel)</span> aka getByTitle('Python 3 (ipykernel): 367fa08d-ebcf-45fa-9ae3-9bccba12bf9a\n\nnotebook\nPath: notebooks/Data.ipynb')
```

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/b4a230c4-7061-4a75-a848-031ac5f49cb1)

[da596a3e78624d97b4c7d6d53a35f19edf11c5a8.webm](https://github.com/jupyterlab/jupyterlab/assets/591645/dcc084fa-0b62-4269-b30d-8c025f39df6d)

**Comment by jtpio** [comment]
Another one noticed in https://github.com/jupyterlab/jupyterlab/pull/15528:

https://github.com/jupyterlab/jupyterlab/actions/runs/7206054140/job/19630151098?pr=15528

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/642171eb-9d4a-43c8-9f9c-85dd38df0d24)

**actual**

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/7ae4b5ac-9b15-4f2f-b040-967c8dd0b925)

**expected**

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/72bccd1c-c7ca-4125-bcae-3e1331ff4389)

**Comment by jtpio** [comment]
Another one noticed in https://github.com/jupyterlab/jupyterlab/pull/15996, which looks similar to the one reported above in https://github.com/jupyterlab/jupyterlab/issues/14947#issuecomment-1846903790:

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/b3a7cee0-87c1-4ded-bfb5-aa1a20c65a3f)

```
Error: locator.waitFor: Error: strict mode violation: locator('.jp-RunningSessions-item.jp-mod-kernel').locator('text="Python 3 (ipykernel)"') resolved to 2 elements:
    1) <span class="jp-RunningSessions-itemLabel" title="Pyth…>Python 3 (ipykernel)</span> aka getByTitle('Python 3 (ipykernel): b07bb759-c807-4bab-8433-fecd0cb1105b')
    2) <span class="jp-RunningSessions-itemLabel" title="Pyth…>Python 3 (ipykernel)</span> aka getByTitle('Python 3 (ipykernel): 50dbe483-bdf8-4c34-ba23-0ca7ab7d0679\n\nnotebook\nPath: notebooks/Data.ipynb')

=========================== logs ===========================
waiting for locator('.jp-RunningSessions-item.jp-mod-kernel').locator('text="Python 3 (ipykernel)"') to be visible
============================================================

  36 |         '.jp-RunningSessions-item.jp-mod-kernel >> text="Python 3 (ipykernel)"'
  37 |       )
> 38 |       .waitFor();
     |        ^
  39 |     expect(
  40 |       await page.screenshot({ clip: { y: 27, x: 0, width: 283, height: 400 } })
  41 |     ).toMatchSnapshot('interface_tabs.png');

    at /home/runner/work/jupyterlab/jupyterlab/core/galata/test/documentation/overview.test.ts:38:8
```

**Comment by krassowski** [comment]
PR https://github.com/jupyterlab/jupyterlab/pull/15845 added a wait and a timeout here: https://github.com/jupyterlab/jupyterlab/pull/15845/files#diff-4ac32d253fd046439ecdb8f1677d3cae7bc944f33e86ecaa7ec48c43b10beeb4

so maybe this one will be resolved (at least on `main`).

**Comment by krassowski** [comment]
Well, https://github.com/jupyterlab/jupyterlab/actions/runs/8364296769/job/22899282170 is not convincing

**Comment by krassowski** [comment]
This is a common one:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/598af508-32c2-4d1d-bd76-0778dd305e73)

Despite:

https://github.com/jupyterlab/jupyterlab/blob/424806be842244ef50d86cdcd8d9d70456d74c50/galata/test/jupyterlab/readonly.test.ts#L21-L26

**Comment by krassowski** [comment]
In the documentation project `shortcuts help` test is flaky

| Actual | Expected |
|--|--|
| ![shortcuts-help-actual](https://github.com/jupyterlab/jupyterlab/assets/5832902/f0ee676f-10ea-418e-bc4a-ff4d5a5cb27d) | ![shortcuts-help-expected](https://github.com/jupyterlab/jupyterlab/assets/5832902/42b70b2c-4ec5-479e-8a69-a1b572e2d5be) |

It seems that the issue is that it sometimes opens the shortcuts help before the active cell got initialized and is thus missing these shortcuts. Adding a cell operation (for example "enter edit mode" for cell 0) here could help:

https://github.com/jupyterlab/jupyterlab/blob/424806be842244ef50d86cdcd8d9d70456d74c50/galata/test/documentation/general.test.ts#L617-L626

**Comment by krassowski** [comment]
Also, this snapshot could be better framed. I could for take the popup + a margin of say 150 pixels around it

**Comment by krassowski** [comment]
https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/galata/test/documentation/customization.test.ts#L215

Should wait for idle status

| Flaky | Expected |
|--|--|
| ![customized-notebook-toolbar-actual](https://github.com/jupyterlab/jupyterlab/assets/5832902/3f83b1ae-585d-4228-a860-8ec653334068) | ![customized-notebook-toolbar-expected](https://github.com/jupyterlab/jupyterlab/assets/5832902/7774a718-0919-4610-8314-67a016218f63) |

**Comment by krassowski** [comment]
Recently these two fail often:

```
    [jupyterlab] › test/jupyterlab/notebook-run.test.ts:33:7 › Notebook Run › Run Notebook and capture cell outputs 
    [jupyterlab] › test/jupyterlab/notebook-search-highlight.test.ts:26:5 › Open and close Search dialog, then add new code cell 
```

**Comment by krassowski** [comment]
```
    [jupyterlab] › test/jupyterlab/notebook-run.test.ts:33:7 › Notebook Run › Run Notebook and capture cell outputs 
```

This is https://github.com/jupyterlab/jupyterlab/issues/15305 all over again.


| Expected | Actual |
|--|--|
| ![notebook-panel-1-expected](https://github.com/jupyterlab/jupyterlab/assets/5832902/13cdc68e-3278-421a-a4f3-739a838dbba1) | ![notebook-panel-1-actual](https://github.com/jupyterlab/jupyterlab/assets/5832902/ed7658c8-e991-463a-abce-bf8424ac91ed) |

**Comment by krassowski** [comment]
Over the past month only one test was failing on CI somewhat frequently, this is:

```
Notice:   1 failed
    [jupyterlab] › test/jupyterlab/windowed-notebook.test.ts:84:5 › should not update height when hiding 
```

But I am impressed how most of the time it worked well, thank you everyone who contributed to making it a pleasant experience!

**Comment by jtpio** [comment]
Another one noticed in https://github.com/jupyterlab/jupyterlab/pull/17395:

![Image](https://github.com/user-attachments/assets/1166fb1d-aff2-45fc-b9e0-681c119ad549)

```
Error: page.evaluate: Execution context was destroyed, most likely because of a navigation.

   at src/jupyterlabpage.ts:717

  715 |   protected waitForAppStarted = async (): Promise<void> => {
  716 |     return this.waitForCondition(() =>
> 717 |       this.page.evaluate(async () => {
      |                 ^
  718 |         if (typeof window.jupyterapp === 'object') {
  719 |           // Wait for plugins to be loaded
  720 |           await window.jupyterapp.started;
    at fn (/home/runner/work/jupyterlab/jupyterlab/galata/src/jupyterlabpage.ts:717:17)
    at Timeout.check (/home/runner/work/jupyterlab/jupyterlab/galata/src/utils.ts:183:33)
```

**Comment by jtpio** [comment]
Currently the most common failure is related to the Mermaid Diagram 19:

<img width="2284" height="1914" alt="Image" src="https://github.com/user-attachments/assets/4eab02b5-810e-442d-9b21-0a6c52f73242" />

**Comment by krassowski** [comment]
Flaky on `main`:

<img width="1000" height="1345" alt="Image" src="https://github.com/user-attachments/assets/543948b9-341c-4746-834f-495e86a13892" />

https://github.com/jupyterlab/jupyterlab/actions/runs/21733236830

**Comment by krassowski** [comment]
Some tests fail like this:

```
  - text: No results
  - 'dialog "Cannot open Could not find path: test-contextmenu" [ref=e129]':
    - generic [ref=e130]:
      - generic [ref=e131]: Cannot open
      - generic [ref=e132]: "Could not find path: test-contextmenu"
      - button "Close" [active] [ref=e135]:
        - generic "Close" [ref=e136]
```

These are the ones which use a fixed `tmpPath`. It looks like a race condition. I will try to enable workspace reset to fix it.

<img width="1000" height="2007" alt="Image" src="https://github.com/user-attachments/assets/22e8c693-4f99-41c3-b213-ea9ca8ec38ec" />

**Comment by krassowski** [comment]
Another one is an issue with cleanup:

<img width="1000" height="2007" alt="Image" src="https://github.com/user-attachments/assets/cb4e3c2d-7e4e-48ba-84ee-88cba73e660c" />

**Comment by krassowski** [comment]
For this one:

```
Error: expect(received).toEqual(expected) // deep equality

Expected: "15px"
Received: "16px"

  141 |       el => getComputedStyle(el).fontSize
  142 |     );
> 143 |     expect(newFontSize).toEqual(`${fontSize + 1}px`);
      |                         ^
  144 |   });
  145 |
  146 |   test('should Decrease Content Font Size', async ({ page }) => {
    at /home/runner/work/jupyterlab/jupyterlab/galata/test/jupyterlab/settings.test.ts:143:25
```

it sometimes clicks on the wrong thing:

<img width="840" height="631" alt="Image" src="https://github.com/user-attachments/assets/5535ac59-b6e1-4b63-a4b7-d0c0d6096c68" />

**Comment by krassowski** [comment]
One more thing - when taking a screenshot of the `cell!.locator('.jp-Editor')` it sometimes includes the shadow of the shell border, depending on how the cell was positioned in the viewport:

<img width="1990" height="1678" alt="Image" src="https://github.com/user-attachments/assets/ce29ca35-2bac-4db7-ba34-1a0922c55b70" />

Which leads to 1px difference at the bottom compared to when it is not partially hidden behind the viewport.

| Diff | Actual | Expected |
|--|--|--|
| <img width="592" height="484" alt="Image" src="https://github.com/user-attachments/assets/3151ec9d-bca1-400e-905f-056c805f4627" /> | <img width="592" height="484" alt="Image" src="https://github.com/user-attachments/assets/94fbc8aa-768b-4360-8bd6-3a6cb77f71c2" /> | <img width="592" height="484" alt="Image" src="https://github.com/user-attachments/assets/bb40b2b1-25a7-468e-a26c-a2daefdce0be" /> |
