### ISSUE TITLE
jupyterlab.upgrade_extension does not update the author and email correctly in package.json

### ISSUE THREAD

**Issue by vikramaditya91** [jupyterlab/jupyterlab#14963]
## Description

When running the `jupyterlab.upgrade_extension` it does not update the authors name and email correctly.

## Reproduce

1. Have `package.json` file with contents like this:
```json
  "license": "BSD-3-Clause",
  "author": "XYZ",
  "author_email": "abc@test.com"
 ```
 
2. Run the migration script as suggested [here](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html)
`python -m jupyterlab.upgrade_extension .`

3. The author name and email are not modified in the `package.json`

## Expected behavior

It should have changed it to 
```
  "license": "BSD-3-Clause",
  "author": {
     "name": "XYZ"
     "email": "abc@test.com"
     }
```  

### Explanation

`hatch build` does not like it when the author name and email are not specified as a dict

```
❯ hatch build
[sdist]
Traceback (most recent call last):
  File "/Users/USER/miniconda3/envs/myextension_jupyterlab/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/USER/miniconda3/envs/myextension_jupyterlab/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/__main__.py", line 6, in <module>
    sys.exit(hatchling())
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
    command(**kwargs)
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/cli/build/__init__.py", line 75, in build_impl
    for artifact in builder.build(
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 93, in build
    self.metadata.validate_fields()
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
    _ = self.version
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/metadata/core.py", line 128, in version
    self._version = self._get_version()
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/metadata/core.py", line 222, in _get_version
    core_metadata = self.core
  File "/Users/USER/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatchling/metadata/core.py", line 174, in core
    metadata_hook.update(self.core_raw_metadata)
  File "/Users/vgaonkar/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatch_nodejs_version/metadata_source.py", line 176, in update
    authors = [self._parse_person(package["author"])]
  File "/Users/vgaonkar/Library/Application Support/hatch/env/virtual/jupyter-myextension/KtqRr9cX/jupyter-myextension-build/lib/python3.10/site-packages/hatch_nodejs_version/metadata_source.py", line 140, in _parse_person
    if {"url", "email"} & person.keys():
AttributeError: 'str' object has no attribute 'keys'
```

Not sure if this is considered a bug on jupyterlab or on hatch.
It needs to be fixed because `hatch` is what jupyterlab extensions are converted to.

**Comment by vikramaditya91** [comment]
There is a conflict between what [`hatch`](https://github.com/agoose77/hatch-nodejs-version/blob/master/hatch_nodejs_version/metadata_source.py#L140) expects and what [jupyterlab](https://github.com/jupyterlab/jupyterlab/blob/main/jupyterlab/upgrade_extension.py#L140) produces.

As both 
```json
"author": "XYZ"
```
and 
```json
"author": {
"name": "XYZ"
}
```
are valid, I would change it to the second one as hatch expects only the second one.

If the core-devs of jupyter agree, I can make a PR for this

**Comment by krassowski** [comment]
I saw this too. I think this could be addressed in the `hatch-nodejs-version` package where the error originates. I had opened an issue about it https://github.com/agoose77/hatch-nodejs-version/issues/19 @agoose77 any thoughts?

**Comment by JasonWeill** [comment]
Closing in favor of upstream issue: https://github.com/agoose77/hatch-nodejs-version/issues/19

Thank you for your contribution!
