### ISSUE TITLE
Frequent "XSRF Cookies do not match Post Argument" errors

### ISSUE THREAD

**Issue by kurmasz** [jupyterlab/jupyterlab#15083]
When using the Jupyter notebook workspaces in PrairieLearn my students and I are frequently getting the error "XSRF Cookies do not match Post Argument", which (depending on when it occurs) prevents users from either launching kernels or saving files.

<img width="1680" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/397476/c8bec87b-2f28-4fdb-871d-588756272b5b">

Unfortunately, at the moment I don't have many useful details to add.

- It happens on all browsers (Chrome, Safari, Firefox)
- I don't see any pattern to when it happens.
- Refreshing the page and/or opening/closing the notebook doesn't usually fix the problem.
- Sometimes opening the workbook in a new browser works, sometimes it doesn't.
- Eventually the problem just goes away.  For example, it's not uncommon for the error to simply go away if I walk away for 5 minutes or so.

The PrairieLearn people have looked and, from what they can tell, the issue seems to be entirely in jupyter.

## Reproduce

The bug is intermittent.  It appears seemingly at random when opening a workbook.

## Expected behavior

No XSRF errors.

## Context

- Operating System and version: All.  (I use macOS 13.5)
- Browser and version: All.  (I use Chrome 116.0.5845.110)
- JupyterLab version: 2.2.9

Here is one example of some workbooks that exhibited the error. I'm not sure how to get you all access; but, I can ask the PrairieLearn people when you get a chance to dig in:  

https://us.prairielearn.com/pl/workspace/1105215
https://us.prairielearn.com/pl/workspace/1112412
https://us.prairielearn.com/pl/workspace/1112414
https://us.prairielearn.com/pl/workspace/1105701

I'll try to add details as I think of what to capture. (The challenge is that this tends to happen during class, so I usually can't stop and dig into the developer console.)

**Comment by kurmasz** [comment]
This is the error that appears in the JavaScript console:

router.js:135 Routing /lab to apputils:load-statedb failed Error: XSRF cookie does not match POST argument
    at r.create (serverconnection.js:106:28)
    at async s.save (index.js:101:19)
    at async index.js:235:35
u @ router.js:135

**Comment by JasonWeill** [comment]
@kurmasz Thanks for opening this issue! Are you sure you're running JupyterLab 2.2.9? That's a much older version, no longer maintained. If you go to Help > About JupyterLab, what version do you see there?

A few people have reported this on the Internet: (thanks @krassowski)
* https://stackoverflow.com/questions/44088615/jupyter-xsrf-cookie-does-not-match-post
* https://discourse.jupyter.org/t/how-do-i-fix-this-kernel-error-xsrf-cookie-does-not-match-post-argument/2551/4

**Comment by kurmasz** [comment]
Yes, it is 2.2.9.  If I understand correctly, the PrairieLearn team has stuck with a version since 2021 because newer versions were causing a problem.  At this point, they don't want to update the Jupyter version unless they are sure it is solving a problem.  For some reason, I seem to be the only one getting the XSRF issue, so they aren't convinced the Jupyter version is the issue.

I do think the multiple _xsrf cookies may be the source of the issue.  (However, I haven't been able intentionally re-create the bug to verify.  It only seem to pop up during class.) Do you have any idea how users end up with two cookies of the same name?  There must be some property that differs between them, right?

Also, do you have any idea what would tickle the multiple-_xsrf bug? (I'm trying to think of how to collect evidence that the bug is related to the Jupyter version for the PL team.)

**Comment by JasonWeill** [comment]
JupyterLab 2 isn't maintained at all anymore, not even for security patches, now that JupyterLab 4 is available. I would strongly recommend that all users upgrade to Lab 3 or newer, whether or not that fixes this XSRF cookie issue.

We were discussing this this morning at triage. Given that other people have encountered this issue with newer versions of JupyterLab (see links above) I'm going to accept this bug, but I don't know of a guaranteed reproduction process for this bug.

**Comment by nwalters512** [comment]
(:wave: from the PrairieLearn team) For a bit of extra context: we've been unwilling to upgrade to newer versions because of https://github.com/jupyterlab/jupyterlab/issues/14106, which was causing a very poor experience for students. Once that's been fixed, we're eager to jump to a newer version!

**Comment by kurmasz** [comment]
I was able to observe the bug in action yesterday on a student's laptop. As we suspected,
- there were two _xsrf tokens
- deleting the tokens and refreshing the page made the error go away.

The two _xsrf cookies do have two different paths:
- /
- /pl/workspace/1128433/container

![Screenshot 2023-09-14 173601 39](https://github.com/jupyterlab/jupyterlab/assets/397476/970c7f04-52f9-497e-a10f-6c844e0d5649)

**Comment by devksingh4** [comment]
It seems that the issue could be in the getCookie logic. If a cookie with the same name exists at both the root path and the current page path, then the cookie that is smaller-scoped (the cookie at the current page path) should be retrieved instead of the cookie set at the root path.

This doesn't solve the underlying issue of "why are in some cases there being cookies set at the root path" but in theory this getCookie behavior is incorrect.

**Comment by lokesh-kurre** [comment]
This probably happens when multiple user access the same notebook instance (url) each with different _xsrf token, causing a confusion a backend. So it error out saying 'XSRF token mismatch'.

Clearing the cache does solve the issue temporarily. Or you can disable xsrf token  as mentioned in [here](https://stackoverflow.com/a/75402282). 
`--NotebookApp.disable_check_xsrf=True`
Though it might cause security issue, if its not in private network.

**Comment by echuber2** [comment]
> This doesn't solve the underlying issue of "why are in some cases there being cookies set at the root path" but in theory this getCookie behavior is incorrect.

In the case of PrairieLearn (like in the last screenshot above), this might be because some questions are using the URL rewriting feature and some aren't. This is usually meant to smooth over path issues with hosting behind a reverse proxy.

[Edit] Refer to: https://prairielearn.readthedocs.io/en/latest/workspaces/#infojson
> - rewriteUrl (optional, default true): if true, the URL will be rewritten such that the workspace container will see all requests as originating from /

If the same user loads multiple workspace questions on PrairieLearn and the course staff didn't create the questions with consistent settings (could also happen across separate courses on the same domain), I can see this happening. But I haven't tested the theory further. The same rewriting was an issue for getting some of the workspace images to work with internal redirects in the first place.

**Comment by kurmasz** [comment]
If this helps: I just double-checked, and I've never explicitly set the `rewriteURL` property in an `info.json` file. 

I'm pretty sure the problem only pops up if the students have multiple Jupyter-based questions open at once.

So, do you think setting `rewriteURL` to `false` would reduce the likelihood of the issue popping up?

**Comment by reteps** [comment]
We are still experiencing this with `quay.io/jupyter/minimal-notebook:2025-08-04 (JupyterLab 4.x)` and `jupyter-collaboration==4.2.0`
