### ISSUE TITLE
Flaky `Open Sidebar tab jp-running-sessions` test

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15103]
## Description

I saw this a couple of times, for example [here](https://github.com/jupyterlab/jupyterlab/actions/runs/6130672040/job/16648118565?pr=15101). It appears that one of the tests which runs in the group before it is not shutting its kernel down properly, leading to a dangling kernel.

```
Error:   1) [jupyterlab] › test/jupyterlab/sidebars.test.ts:31:9 › Sidebars › Open Sidebar tab jp-running-sessions 
    Error: Screenshot comparison failed:

      395 pixels (ratio 0.01 of all image pixels) are different.

    Expected: /home/runner/work/jupyterlab/jupyterlab/galata/test-results/test-jupyterlab-sidebars-Sidebars-Open-Sidebar-tab-jp-running-sessions-jupyterlab/opened-sidebar-jp-running-sessions-expected.png
    Received: /home/runner/work/jupyterlab/jupyterlab/galata/test-results/test-jupyterlab-sidebars-Sidebars-Open-Sidebar-tab-jp-running-sessions-jupyterlab/opened-sidebar-jp-running-sessions-actual.png
        Diff: /home/runner/work/jupyterlab/jupyterlab/galata/test-results/test-jupyterlab-sidebars-Sidebars-Open-Sidebar-tab-jp-running-sessions-jupyterlab/opened-sidebar-jp-running-sessions-diff.png

      36 |       const position = await page.sidebar.getTabPosition(sidebarId);
      37 |       const sidebar = await page.sidebar.getContentPanel(position);
    > 38 |       expect(await sidebar.screenshot()).toMatchSnapshot(
         |                                          ^
      39 |         imageName.toLowerCase()
      40 |       );
      41 |     });

        at /home/runner/work/jupyterlab/jupyterlab/galata/test/jupyterlab/sidebars.test.ts:38:42
```

| Actual | Expected |
|--------|--------|
| ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/82417132-b2ee-4056-acac-ee5de16e83d4) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/ce7e1f40-9cea-47ef-9c75-519b964edb2e) |

**Comment by krassowski** [comment]
One problem here is that the updates to the kernels section are throttled by 100ms since https://github.com/jupyterlab/jupyterlab/pull/13792 so even if we clear the kernels, these may stick around for a while in the UI if they were just created:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/running-extension/src/kernels.tsx#L42-L47

Another potential culprit is the `cache` variable added by the same PR here:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/running/src/index.tsx#L446-L459

**Comment by krassowski** [comment]
On main it also fails because PR https://github.com/jupyterlab/jupyterlab/pull/16046 included incorrect update of the snpapshot to a state in which the shutdown label still visible but no kernels shown:

| Should be | Was committed in #16046 to `main` |
|--|--|
| ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/4b75a929-7555-4427-9155-81df8a1ae4f5) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/2aad660a-0b1c-4717-b1ac-49307e42245d) |

This is no the first time I see this discrepant state. There must be something wrong with the implementation. My best guess right now is that this is because of the `cached` variable because it is used to prevent updating the listing whereas there is no similar cache for updating the buttons:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/running/src/index.tsx#L642

**Comment by krassowski** [comment]
Importantly, the `_update` signal (which is connected to `runningChanged`) is only emitted if the running sidebar is visible due to this guard:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/running/src/index.tsx#L484-L505

**Comment by krassowski** [comment]
Ha, I was able to get into the state where the kernels list is empty but buttons are show. This happened when changing a kernel via popup. I got the following error in the console:

```
kernels.tsx:338 Uncaught TypeError: Cannot read properties of undefined (reading 'label')
    at get _summary (kernels.tsx:338:25)
    at RunningKernel.labelTitle (kernels.tsx:322:30)
    at Item (index.tsx:211:54)
```

Coming from:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/running-extension/src/kernels.tsx#L326-L335

The assumption in this method is incorrect: when `children.length != 1` it does not mean that there is 2 or more, it can be 0.

**Comment by krassowski** [comment]
The children can be empty when a kernel was already created, but sessions were no updated. This comes back to the updates for `kernels.runningChanged` and `sessions.runningChanged` invoking throttler separately rather than in unison:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/running-extension/src/kernels.tsx#L45-L47

More specifically, if a kernel exists but session is not found, the `children` property will return an empty as no session will be found that matches the kernel id, see the loop and conditional in lines 273-274:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/running-extension/src/kernels.tsx#L269-L292

 Which makes it clear why previously snapshots randomly showed a kernel spec but not any kernels connected to it.

**Comment by krassowski** [comment]
Maybe we should _never_ listen to `kernels.runningChanged` if we are only ready to update the widget when `sessions.runningChanged` emits and we do not show kernels without sessions? @afshin (as author of https://github.com/jupyterlab/jupyterlab/pull/13792) any thoughts here?

**Comment by krassowski** [comment]
Related to https://github.com/jupyterlab/jupyterlab/issues/15635. I will close that one and paste the gist here:

> The recording from the run test (sorry for poor quality) shows that indeed this element shows up twice:
> 
> ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/9a96e308-dafb-4ee8-9684-0efe4f62f756)
> 
> This is clearly a bug. Interestingly, I have never seen this outside of tests.

**Comment by krassowski** [comment]
As a confirmation of my previous finding, the `galata/test/documentation/general.test.ts-snapshots/running-layout-documentation-linux.png` snapshot got updated to:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/8527e789-b197-4688-b6e0-78ca08d8aa6e)

In #16207
