### ISSUE TITLE
Issue when launching Jupyter lab

### ISSUE THREAD

**Issue by jenil59** [jupyterlab/jupyterlab#15124]
When I am launching the jupyter lab from CMD or ANACONDA .given  error  shown.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Scripts\jupyter-lab-script.py", line 6, in <module>
    from jupyterlab.labapp import main
  File "C:\ProgramData\anaconda3\lib\site-packages\jupyterlab\__init__.py", line 7, in <module>
    from .handlers.announcements import (  # noqa
  File "C:\ProgramData\anaconda3\lib\site-packages\jupyterlab\handlers\announcements.py", line 14, in <module>
    from jupyter_server.base.handlers import APIHandler
  File "C:\ProgramData\anaconda3\lib\site-packages\jupyter_server\base\handlers.py", line 21, in <module>
    from tornado import escape, httputil, web
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\tornado\httputil.py", line 106, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by asteppke** [comment]
Hi @jenil59 

It looks like your python installation is not working as it is supposed to. Your jupyter lab is coming from anaconda installed in `C:\ProgramData\anaconda3` whereas the Tornado HTTP server is coming from `...Appdata\Roaming\Python\Python310\...`. 

So I would make sure you do not have any python in your PATH environment variable and then go through the normal `conda init` steps to setup your environment in a consistent way.

**Comment by JasonWeill** [comment]
@jenil59 Thanks for your contribution! You can follow our installation instructions here: https://jupyterlab.readthedocs.io/en/latest/getting_started/installation.html . If you notice any additional issues after following the linked guide, please open a new issue.
