### ISSUE TITLE
Save-As should use a head request (it does not need the body) and get should catch non-existing.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#15153]
It's not per-se a enhancement, but not really a bug, 

but when using JupyterLab `Save As`, the flow of the save as function is the following:

```
  async saveAs(): Promise<void> {
    ...
    try {
      ...
      await this._manager.contents.get(newPath); // this likely triggers the 404.
      await this._maybeOverWrite(newPath); // if not 404 ask do you like to overwrite.
    } catch (err) {
      ...
      await this._finishSaveAs(newPath);
    }
  }
```

I think this has 2 issues. 

1) the get is unnecessary wastefull you don't want the full content, just to know if the content exists. This is what a HEAD request is for. but...
1a)  jupyter-server does not (yet) implement HEAD for content handler. I guess it could be auto-derived from GET without sending the content.
2) The Jupyter server `get` implementation does raise a 404 non-existing from deeper in the handler:

This leads to a TB in the terminal:

```
[W 2023-09-20 17:12:47.709 ServerApp] wrote error: 'No such file or directory: .../Downloads/test.ipynb'
    Traceback (most recent call last):
      File ".../site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File ".../site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File ".../site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File ".../site-packages/jupyter_server/services/contents/filemanager.py", line 877, in get raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: .../Downloads/test.ipynb)
```

Which can make users believe something is wrong, while it's an expected 404. 

```

The following should likely catch 404, and have a clean `self.set_status(400)` and `self.finish()` to avoid tracebacks:

```
        # add try
        model = await ensure_async(
            self.contents_manager.get( //this raise
                path=path,
                type=type,
                format=format,
                content=content,
            )
        )
        # except 404, set status.
```

Same should likely be done if HEAD is added/used.

Agreed 2 of those might need to be in jupyter-server, but as this affects the JupyterLab I prefered to open this here first, and let this repo sync with upstream. 

This should also be a fairly easy issue for a new contributor both on here and upstream.

**Comment by SunSummoner** [comment]
@Carreau I would like to contribute to this issue. Can you assign it to me?

**Comment by krassowski** [comment]
@SunSummoner please feel welcome to contribute!

> Note: We do not use the "assign" feature on GitHub for "good first issue"s in this repository to avoid stale assignments.

**Comment by DcWire** [comment]
Hey @Carreau , could you explain again what is to be resolved here? Ive done some exploration and was able to reproduce the error on the console, but didn't quite understand the outcome that is to be achieved. Thanks.

**Comment by mohamed-ali-halloul** [comment]
hello can i work in this issue

**Comment by garvitdayal28** [comment]
Hi! I'm a new contributor and I'd like to work on this issue. I noticed it has the status:Blocked label—is this still waiting on the jupyter-server changes mentioned earlier, or is it ready for a PR in this repo? If it's ready, I'd love to take a crack at implementing the HEAD request logic. Thanks

**Comment by DeborahOlaboye** [comment]
Hi @Carreau , I'd like to work on this issue.

**Comment by krassowski** [comment]
@DeborahOlaboye please feel welcome to! I would suggest opening a draft PR early to signal that you started work and receive early feedback.

**Comment by DeborahOlaboye** [comment]
Alright, Thank you.

**Comment by Carreau** [comment]
And in general don't ping a specific person on an issue, i'm not particularly the right person to decide on this project;

**Comment by DeborahOlaboye** [comment]
Alright, Noted.

**Comment by jasongrout** [comment]
> This leads to a TB in the terminal:

FYI, when testing #18379, I'm not seeing a traceback for the contents request for Jupyter Server:

```
[W 2026-01-23 17:22:40.261 ServerApp] 404 GET /api/contents/nb2.ipynb?content=0&hash=0&1769214160238 (3e6f9a1676b24ff08d7525c32c2d5278@127.0.0.1) 4.24ms referer=http://localhost:8889/lab/tree/tmp/nb2.ipynb
```

**Comment by DeborahOlaboye** [comment]
> > This leads to a TB in the terminal:
> 
> FYI, when testing [#18379](https://github.com/jupyterlab/jupyterlab/pull/18379), I'm not seeing a traceback for the contents request for Jupyter Server:
> 
> ```
> [W 2026-01-23 17:22:40.261 ServerApp] 404 GET /api/contents/nb2.ipynb?content=0&hash=0&1769214160238 (3e6f9a1676b24ff08d7525c32c2d5278@127.0.0.1) 4.24ms referer=http://localhost:8889/lab/tree/tmp/nb2.ipynb
> ```

Thanks for testing @jasongrout. Just to confirm, you're seeing the clean 404 log without the traceback, which is the expected behaviour after the fix, right? The original issue reported that the traceback was appearing before this change.

**Comment by jasongrout** [comment]
> you're seeing the clean 404 log without the traceback, which is the expected behaviour after the fix, right

I don't know if this PR is what fixed the log to not have a traceback, since this PR isn't actually changing anything in practice (since we accidentally had content false by default).

What do you see? If you set content to true, do you see a traceback, but if content is false, the traceback goes away?
