### ISSUE TITLE
chrome does not open when I launch jupyter lab in the terminal

### ISSUE THREAD

**Issue by twistin** [jupyterlab/jupyterlab#15161]
I have problems to work smoothly with Jupyter lab. From the terminal I can't open the browser automatically. I can open it locally by copying the link and pasting it into the browser.
The solutions I tried were to specify the browser in the file c.ServerApp.browser = '/Applications/crhome.app' which is in the .jupyter folder. 

```
(jlab-test) sdcarr@MacBook-Pro-de-Silvino ~ % jupyter lab
[I 2023-09-26 22:56:06.706 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-09-26 22:56:06.713 ServerApp] Package jupyter_lsp took 0.0066s to import
[W 2023-09-26 22:56:06.713 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-26 22:56:06.715 ServerApp] Package jupyter_server_terminals took 0.0021s to import
[I 2023-09-26 22:56:06.715 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-09-26 22:56:06.715 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-26 22:56:06.716 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-09-26 22:56:06.717 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-09-26 22:56:06.719 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-09-26 22:56:07.233 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-09-26 22:56:07.264 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-09-26 22:56:07.265 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-09-26 22:56:07.266 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-09-26 22:56:07.266 LabApp] JupyterLab extension loaded from /Users/sdcarr/mambaforge/envs/jlab-test/lib/python3.11/site-packages/jupyterlab
[I 2023-09-26 22:56:07.266 LabApp] JupyterLab application directory is /Users/sdcarr/mambaforge/envs/jlab-test/share/jupyter/lab
[I 2023-09-26 22:56:07.267 LabApp] Extension Manager is 'pypi'.
[I 2023-09-26 22:56:07.268 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-09-26 22:56:07.268 ServerApp] Serving notebooks from local directory: /Users/sdcarr
[I 2023-09-26 22:56:07.268 ServerApp] Jupyter Server 2.7.3 is running at:
[I 2023-09-26 22:56:07.268 ServerApp] http://localhost:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
[I 2023-09-26 22:56:07.268 ServerApp]     http://127.0.0.1:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
[I 2023-09-26 22:56:07.268 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2023-09-26 22:56:07.271 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2023-09-26 22:56:07.271 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/sdcarr/Library/Jupyter/runtime/jpserver-9570-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
        http://127.0.0.1:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
[I 2023-09-26 22:56:07.492 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
^C[I 2023-09-26 22:56:47.183 ServerApp] interrupted
[I 2023-09-26 22:56:47.185 ServerApp] Serving notebooks from local directory: /Users/sdcarr
    0 active kernels
    Jupyter Server 2.7.3 is running at:
    http://localhost:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
        http://127.0.0.1:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
Shutdown this Jupyter server (y/[n])? yjupyter no[I 2023-09-26 22:56:52.187 ServerApp] No answer for 5s:
[I 2023-09-26 22:56:52.187 ServerApp] resuming operation...
tebook
^C[I 2023-09-26 22:57:20.768 ServerApp] interrupted
[I 2023-09-26 22:57:20.768 ServerApp] Serving notebooks from local directory: /Users/sdcarr
    0 active kernels
    Jupyter Server 2.7.3 is running at:
    http://localhost:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
        http://127.0.0.1:8888/lab?token=a92070fc960822e37eed5ac3b9deae997157b1a79c38e883
Shutdown this Jupyter server (y/[n])? y
[C 2023-09-26 22:57:22.967 ServerApp] Shutdown confirmed
[I 2023-09-26 22:57:22.972 ServerApp] Shutting down 4 extensions
(jlab-test) sdcarr@MacBook-Pro-de-Silvino ~ % jupyter notebook
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/__init__.py", line 27, in <module>
    from .nbextensions import install_nbextension
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/nbextensions.py", line 15, in <module>
    from jupyter_core.paths import (
ModuleNotFoundError: No module named 'jupyter_core'
(jlab-test) sdcarr@MacBook-Pro-de-Silvino ~ % jupyter --debug
--debug is only used with --paths
(jlab-test) sdcarr@MacBook-Pro-de-Silvino ~ % jupyter lab path
Application directory:   /Users/sdcarr/mambaforge/envs/jlab-test/share/jupyter/lab
User Settings directory: /Users/sdcarr/.jupyter/lab/user-settings
Workspaces directory: /Users/sdcarr/.jupyter/lab/workspaces
(jlab-test) sdcarr@MacBook-Pro-de-Silvino ~ % conda list | findstr jupyterlab
zsh: command not found: findstr
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
(jlab-test) sdcarr@MacBook-Pro-de-Silvino ~ % jupyter lab
[I 2023-09-26 23:22:18.067 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-09-26 23:22:18.076 ServerApp] Package jupyter_lsp took 0.0091s to import
[W 2023-09-26 23:22:18.076 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-26 23:22:18.080 ServerApp] Package jupyter_server_terminals took 0.0034s to import
[I 2023-09-26 23:22:18.080 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-09-26 23:22:18.080 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-26 23:22:18.080 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-09-26 23:22:18.082 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-09-26 23:22:18.084 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-09-26 23:22:18.240 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-09-26 23:22:18.272 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-09-26 23:22:18.273 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-09-26 23:22:18.274 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-09-26 23:22:18.274 LabApp] JupyterLab extension loaded from /Users/sdcarr/mambaforge/envs/jlab-test/lib/python3.11/site-packages/jupyterlab
[I 2023-09-26 23:22:18.275 LabApp] JupyterLab application directory is /Users/sdcarr/mambaforge/envs/jlab-test/share/jupyter/lab
[I 2023-09-26 23:22:18.275 LabApp] Extension Manager is 'pypi'.
[I 2023-09-26 23:22:18.276 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-09-26 23:22:18.277 ServerApp] Serving notebooks from local directory: /Users/sdcarr
[I 2023-09-26 23:22:18.277 ServerApp] Jupyter Server 2.7.3 is running at:
[I 2023-09-26 23:22:18.277 ServerApp] http://localhost:8888/lab?token=572d1bd3e68b7f0c57aff9bdcb245055da1fc7e7a3da0e34
[I 2023-09-26 23:22:18.277 ServerApp]     http://127.0.0.1:8888/lab?token=572d1bd3e68b7f0c57aff9bdcb245055da1fc7e7a3da0e34
[I 2023-09-26 23:22:18.277 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2023-09-26 23:22:18.280 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2023-09-26 23:22:18.280 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/sdcarr/Library/Jupyter/runtime/jpserver-10151-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=572d1bd3e68b7f0c57aff9bdcb245055da1fc7e7a3da0e34
        http://127.0.0.1:8888/lab?token=572d1bd3e68b7f0c57aff9bdcb245055da1fc7e7a3da0e34
[I 2023-09-26 23:22:18.482 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
```
I am on a mac m1 and the version of Jupyter Lab is 4.0.6

Does anyone have any idea how to fix this uncomfortable problem?
Thanks

**Comment by JasonWeill** [comment]
@twistin Thanks for your report! You said in your report that you had specified in the config:

```
c.ServerApp.browser = '/Applications/crhome.app'
```

On macOS, the name of the application is `Google Chrome.app`. Can you set this and try again?

```
c.ServerApp.browser = '/Applications/Google Chrome.app' 
```

**Comment by JasonWeill** [comment]
@twistin When you change the browser config, do you still see this problem?

**Comment by JasonWeill** [comment]
@twistin Because we haven't seen a response on this issue, I'm going to close this for now. Please reopen this issue or open a new one if you notice any other problems in JupyterLab. Thanks!
