### ISSUE TITLE
Error message related to the TOC when opening a notebook

### ISSUE THREAD

**Issue by HaudinFlorence** [jupyterlab/jupyterlab#15166]
## Description

This issue reports an error message appearing in the console when opening a notebook.

## Reproduce

1. Open a notebook
2. See the following error in the console:
```
toc.ts:683 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at getIdForHeading (toc.ts:683:15)
    at toc.ts:560:33
    at Array.forEach (<anonymous>)
    at findHeadingElement (toc.ts:559:35)
    at onCellInViewportChanged (toc.ts:642:9)
    at invokeSlot (index.es6.js:555:1)
    at Object.emit (index.es6.js:513:1)
    at Signal.emit (index.es6.js:112:1)
    at Notebook._onCellInViewportChanged (widget.ts:776:33)
    at invokeSlot (index.es6.js:555:1)
    ```

**Comment by JasonWeill** [comment]
@HaudinFlorence Thanks for opening this! Could you attach a sample notebook that causes this error to occur?

**Comment by HaudinFlorence** [comment]
@JasonWeill I can observe this message with the `OutputExamples.ipynb`that is in `examples/notebooks`.
![Screenshot from 2023-10-03 18-26-09](https://github.com/jupyterlab/jupyterlab/assets/99649086/2d287571-debc-4991-9652-b03774aac6c0)

**Comment by a3626a** [comment]
Here's a minimal example (I zipped it to bypass github file restriction)
[undefined-minimal.zip](https://github.com/jupyterlab/jupyterlab/files/14682015/undefined-minimal.zip)

**Comment by krassowski** [comment]
I wonder if https://github.com/jupyterlab/jupyterlab/pull/16013 might help here.

**Comment by a3626a** [comment]
@krassowski 

I'm trying to test your branch, but failing it, becuase of build issue.

1) Binder
Your branch succeed to launch, and this issue looks like fixed.
For test group, I launched main branch of jupyter lab. It failed to launch.

2) Local Environment
My local environment looks not compatible with main or your branch.
Failed `pip install -e ".[dev,test]"`

3) Docker
```
bash docker/start.sh
```
![image](https://github.com/jupyterlab/jupyterlab/assets/4434752/2b72a57d-e583-440e-91ac-75036783e168)


So I'm not sure your PR fixed this issue.

**Comment by jtpio** [comment]
@a3626a you could also download the artifacts from https://github.com/jupyterlab/jupyterlab/actions/runs/8330540819?pr=16013, extract them locally, and install the wheel directly (it corresponds to a JupyterLab built from that PR).
