### ISSUE TITLE
ipython module name conflicts with user created file leading to import error

### ISSUE THREAD

**Issue by raceychan** [jupyterlab/jupyterlab#15268]
## Description

this might or might not cuased by the fact that ipython run relative import, 
and when there is a python module in the same name existing in current module, the import mechanism mulfunctions

## Reproduce

1. in your current directory, create a 'decorator.py' file
2. in the same direcotry, create a random ipynb
3. try to run a random command in that ipynb

## Context

lsb_release -a：

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Chrome Version:
117.0.5938.152

Jupyter lab --version:
4.0.5

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
jupyter troubleshoot                                INT  base py  01:23:24 
$PATH:
        /home/race/.local/bin
        /home/race/miniconda3/bin
        /home/race/miniconda3/condabin
        /home/race/.autojump/bin
        /home/race/.codon/bin
        /home/race/.local/share/pypoetry/bin
        /home/race/anaconda3/bin
        /home/race/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/bin/remote-cli
        /home/race/.cargo/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /usr/lib/wsl/lib
        /mnt/c/Windows/system32
        /mnt/c/Windows
        /mnt/c/Windows/System32/Wbem
        /mnt/c/Windows/System32/WindowsPowerShell/v1.0
        /mnt/c/Windows/System32/OpenSSH
        /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
        /mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
        /mnt/c/WINDOWS/system32
        /mnt/c/WINDOWS
        /mnt/c/WINDOWS/System32/Wbem
        /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0
        /mnt/c/WINDOWS/System32/OpenSSH
        /mnt/c/Users/race/AppData/Local/Microsoft/WindowsApps
        /mnt/c/Users/race/AppData/Local/Programs/Microsoft VS Code/bin

sys.path:
        /home/race/.local/bin
        /home/race/miniconda3/envs/myproject/lib/python311.zip
        /home/race/miniconda3/envs/myproject/lib/python3.11
        /home/race/miniconda3/envs/myproject/lib/python3.11/lib-dynload
        /home/race/.local/lib/python3.11/site-packages
        /home/race/miniconda3/envs/myproject/lib/python3.11/site-packages

sys.executable:
        /home/race/miniconda3/envs/myproject/bin/python3

sys.version:
        3.11.2 (main, Mar 27 2023, 23:42:44) [GCC 11.2.0]

platform.platform():
        Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

which -a jupyter:
        /home/race/.local/bin/jupyter
        /home/race/miniconda3/bin/jupyter

pip list:
        Package                       Version
        ----------------------------- -----------
        aenum                         3.1.12
        aiohttp                       3.8.4
        aiosignal                     1.3.1
        annotated-types               0.5.0
        anyio                         3.6.2
        appdirs                       1.4.4
        argon2-cffi                   21.3.0
        argon2-cffi-bindings          21.2.0
        arrow                         1.3.0
        astroid                       2.15.3
        asttokens                     2.2.1
        async-lru                     2.0.4
        async-timeout                 4.0.2
        attrs                         23.1.0
        autopep8                      2.0.2
        Babel                         2.12.1
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.4
        beautifulsoup4                4.12.2
        black                         23.3.0
        bleach                        6.0.0
        brotlipy                      0.7.0
        certifi                       2023.5.7
        cffi                          1.15.1
        charset-normalizer            3.1.0
        click                         7.1.2
        colorama                      0.4.6
        cryptography                  39.0.1
        Cython                        3.0.0
        debugpy                       1.5.1
        decorator                     5.1.1
        defusedxml                    0.7.1
        dill                          0.3.6
        docstring-to-markdown         0.12
        entrypoints                   0.4
        executing                     1.2.0
        fastjsonschema                2.16.3
        flake8                        6.0.0
        flatlatex                     0.15
        flit_core                     3.8.0
        fqdn                          1.5.1
        frozenlist                    1.3.3
        fsspec                        2023.4.0
        idna                          3.4
        imagesize                     1.4.1
        importlib-metadata            6.7.0
        importlib-resources           5.12.0
        iniconfig                     2.0.0
        ipykernel                     6.15.0
        ipython                       8.12.0
        ipython-genutils              0.2.0
        ipywidgets                    8.0.6
        isoduration                   20.11.0
        isort                         5.12.0
        jedi                          0.18.2
        Jinja2                        3.1.2
        json5                         0.9.5
        jsonpointer                   2.4
        jsonschema                    4.19.1
        jsonschema-specifications     2023.7.1
        jupyter_client                7.4.9
        jupyter-console               6.6.3
        jupyter_core                  5.3.0
        jupyter-events                0.7.0
        jupyter-lsp                   2.0.1
        jupyter_server                2.7.3
        jupyter_server_terminals      0.4.4
        jupyterlab                    4.0.5
        jupyterlab-code-formatter     1.6.0
        jupyterlab-lsp                3.10.2
        jupyterlab-pygments           0.2.2
        jupyterlab_server             2.22.1
        jupyterlab-widgets            3.0.7
        lazy-object-proxy             1.6.0
        linkify-it-py                 1.0.3
        loguru                        0.7.0
        markdown-it-py                2.1.0
        MarkupSafe                    2.1.1
        matplotlib-inline             0.1.6
        mccabe                        0.7.0
        mdit-py-plugins               0.3.5
        mdurl                         0.1.2
        mistune                       2.0.5
        multidict                     6.0.4
        mypy                          1.2.0
        mypy-extensions               1.0.0
        nb-conda-kernels              2.3.1
        nbclassic                     0.5.5
        nbclient                      0.7.3
        nbconvert                     7.3.1
        nbformat                      5.8.0
        nest-asyncio                  1.5.6
        notebook                      6.5.4
        notebook_shim                 0.2.2
        overrides                     7.4.0
        packaging                     23.1
        pandocfilters                 1.5.0
        parso                         0.8.3
        pathspec                      0.11.1
        pexpect                       4.8.0
        pickleshare                   0.7.5
        Pillow                        9.5.0
        pip                           23.0.1
        pkgutil_resolve_name          1.3.10
        platformdirs                  3.2.0
        pluggy                        1.0.0
        ply                           3.11
        prometheus-client             0.16.0
        prompt-toolkit                3.0.38
        psutil                        5.9.0
        ptyprocess                    0.7.0
        pure-eval                     0.2.2
        pycodestyle                   2.10.0
        pycparser                     2.21
        pydantic                      2.0.1
        pydantic_core                 2.0.2
        pydocstyle                    6.3.0
        pyflakes                      3.0.1
        Pygments                      2.15.1
        pylint                        2.17.2
        pyOpenSSL                     23.1.1
        pyperclip                     1.8.2
        PyQt5-sip                     12.11.0
        pyrsistent                    0.19.3
        PySocks                       1.7.1
        pytest                        7.3.1
        python-dateutil               2.8.2
        python-json-logger            2.0.7
        python-lsp-jsonrpc            1.0.0
        python-lsp-server             1.7.2
        pytoolconfig                  1.2.5
        pytz                          2023.3
        PyYAML                        6.0.1
        pyzmq                         25.0.2
        qtconsole                     5.4.2
        QtPy                          2.3.1
        referencing                   0.30.2
        regex                         2023.3.23
        requests                      2.28.2
        rfc3339-validator             0.1.4
        rfc3986-validator             0.1.1
        rich                          13.3.5
        rope                          1.7.0
        rpds-py                       0.10.6
        Send2Trash                    1.8.2
        setuptools                    65.6.3
        sh                            2.0.4
        sip                           6.6.2
        six                           1.16.0
        sixelcrop                     0.1.3
        sniffio                       1.3.0
        snowballstemmer               2.2.0
        soupsieve                     2.3.2.post1
        stack-data                    0.6.2
        terminado                     0.17.1
        textual                       0.22.3
        timg                          1.1.6
        tinycss2                      1.2.1
        toml                          0.10.2
        tomli                         2.0.1
        tomlkit                       0.11.7
        tornado                       6.3
        traitlets                     5.9.0
        typer                         0.9.0
        types-python-dateutil         2.8.19.14
        typing_extensions             4.7.1
        uc-micro-py                   1.0.1
        ujson                         5.4.0
        universal_pathlib             0.0.23
        uri-template                  1.3.0
        urllib3                       1.26.15
        wcwidth                       0.2.6
        webcolors                     1.13
        webencodings                  0.5.1
        websocket-client              1.5.1
        whatthepatch                  1.0.4
        wheel                         0.38.4
        widgetsnbextension            4.0.7
        wrapt                         1.14.1
        yapf                          0.32.0
        yarl                          1.8.2
        zipp                          3.15.0

conda list:
        # packages in environment at /home/race/miniconda3:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                        main  
        _openmp_mutex             5.1                       1_gnu  
        boltons                   23.0.0          py310h06a4308_0  
        brotlipy                  0.7.0           py310h7f8727e_1002  
        bzip2                     1.0.8                h7b6447c_0  
        ca-certificates           2023.5.7             hbcca054_0    conda-forge
        certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
        cffi                      1.15.1          py310h5eee18b_3  
        charset-normalizer        2.0.4              pyhd3eb1b0_0  
        click                     8.1.3                    pypi_0    pypi
        conda                     23.5.0          py310hff52083_1    conda-forge
        conda-content-trust       0.1.3           py310h06a4308_0  
        conda-package-handling    2.1.0           py310h06a4308_0  
        conda-package-streaming   0.8.0           py310h06a4308_0  
        cryptography              39.0.1          py310h9ce1e76_2  
        frogmouth                 0.8.0                    pypi_0    pypi
        httpx                     0.24.1                   pypi_0    pypi
        idna                      3.4             py310h06a4308_0  
        importlib-metadata        6.8.0                    pypi_0    pypi
        ipython                   8.12.0                   pypi_0    pypi
        jsonpatch                 1.32               pyhd3eb1b0_0  
        jsonpointer               2.1                pyhd3eb1b0_0  
        jupyter_client            8.1.0           py310h06a4308_0  
        jupyter_core              5.3.0           py310h06a4308_0  
        lazygit                   0.38.2               ha770c72_0    conda-forge
        ld_impl_linux-64          2.38                 h1181459_1  
        libffi                    3.4.4                h6a678d5_0  
        libgcc-ng                 11.2.0               h1234567_1  
        libgomp                   11.2.0               h1234567_1  
        libsodium                 1.0.18               h7b6447c_0  
        libstdcxx-ng              11.2.0               h1234567_1  
        libuuid                   1.41.5               h5eee18b_0  
        linkify-it-py             2.0.2                    pypi_0    pypi
        loguru                    0.7.0                    pypi_0    pypi
        mdit-py-plugins           0.4.0                    pypi_0    pypi
        nb_conda_kernels          2.3.1           py310hff52083_2    conda-forge
        ncurses                   6.4                  h6a678d5_0  
        onesync                   0.1.0                    pypi_0    pypi
        openssl                   3.0.9                h7f8727e_0  
        packaging                 23.0            py310h06a4308_0  
        pip                       22.3.1          py310h06a4308_0  
        platformdirs              2.5.2           py310h06a4308_0  
        pluggy                    1.0.0           py310h06a4308_1  
        pycosat                   0.6.4           py310h5eee18b_0  
        pycparser                 2.21               pyhd3eb1b0_0  
        pygments                  2.15.1                   pypi_0    pypi
        pyopenssl                 23.0.0          py310h06a4308_0  
        pysocks                   1.7.1           py310h06a4308_0  
        python                    3.10.11              h955ad1f_3  
        python-dateutil           2.8.2              pyhd3eb1b0_0  
        python_abi                3.10                    2_cp310    conda-forge
        pyzmq                     25.1.0          py310h6a678d5_0  
        readline                  8.2                  h5eee18b_0  
        requests                  2.29.0          py310h06a4308_0  
        ruamel.yaml               0.17.21         py310h5eee18b_0  
        ruamel.yaml.clib          0.2.6           py310h5eee18b_1  
        setuptools                65.6.3          py310h06a4308_0  
        sh                        2.0.4                    pypi_0    pypi
        six                       1.16.0             pyhd3eb1b0_1  
        sqlite                    3.41.2               h5eee18b_0  
        textual                   0.30.0                   pypi_0    pypi
        tk                        8.6.12               h1ccaba5_0  
        toolz                     0.12.0          py310h06a4308_0  
        tornado                   6.2             py310h5eee18b_0  
        tqdm                      4.65.0          py310h2f386ee_0  
        traitlets                 5.7.1           py310h06a4308_0  
        typer                     0.9.0                    pypi_0    pypi
        typing-extensions         4.6.2                    pypi_0    pypi
        tzdata                    2023c                h04d1e81_0  
        uc-micro-py               1.0.2                    pypi_0    pypi
        urllib3                   1.26.16         py310h06a4308_0  
        wheel                     0.37.1             pyhd3eb1b0_0  
        xdg                       6.0.0                    pypi_0    pypi
        xz                        5.4.2                h5eee18b_0  
        zeromq                    4.3.4                h2531618_0  
        zipp                      3.16.2                   pypi_0    pypi
        zlib                      1.2.13               h5eee18b_0  
        zstandard                 0.19.0          py310h5eee18b_0

conda env:
        name: base
        channels:
          - conda-forge
          - defaults
        dependencies:
          - _libgcc_mutex=0.1=main
          - _openmp_mutex=5.1=1_gnu
          - boltons=23.0.0=py310h06a4308_0
          - brotlipy=0.7.0=py310h7f8727e_1002
          - bzip2=1.0.8=h7b6447c_0
          - ca-certificates=2023.5.7=hbcca054_0
          - certifi=2023.5.7=pyhd8ed1ab_0
          - cffi=1.15.1=py310h5eee18b_3
          - charset-normalizer=2.0.4=pyhd3eb1b0_0
          - conda=23.5.0=py310hff52083_1
          - conda-content-trust=0.1.3=py310h06a4308_0
          - conda-package-handling=2.1.0=py310h06a4308_0
          - conda-package-streaming=0.8.0=py310h06a4308_0
          - cryptography=39.0.1=py310h9ce1e76_2
          - idna=3.4=py310h06a4308_0
          - jsonpatch=1.32=pyhd3eb1b0_0
          - jsonpointer=2.1=pyhd3eb1b0_0
          - jupyter_client=8.1.0=py310h06a4308_0
          - jupyter_core=5.3.0=py310h06a4308_0
          - lazygit=0.38.2=ha770c72_0
          - ld_impl_linux-64=2.38=h1181459_1
          - libffi=3.4.4=h6a678d5_0
          - libgcc-ng=11.2.0=h1234567_1
          - libgomp=11.2.0=h1234567_1
          - libsodium=1.0.18=h7b6447c_0
          - libstdcxx-ng=11.2.0=h1234567_1
          - libuuid=1.41.5=h5eee18b_0
          - nb_conda_kernels=2.3.1=py310hff52083_2
          - ncurses=6.4=h6a678d5_0
          - openssl=3.0.9=h7f8727e_0
          - packaging=23.0=py310h06a4308_0
          - pip=22.3.1=py310h06a4308_0
          - platformdirs=2.5.2=py310h06a4308_0
          - pluggy=1.0.0=py310h06a4308_1
          - pycosat=0.6.4=py310h5eee18b_0
          - pycparser=2.21=pyhd3eb1b0_0
          - pyopenssl=23.0.0=py310h06a4308_0
          - pysocks=1.7.1=py310h06a4308_0
          - python=3.10.11=h955ad1f_3
          - python-dateutil=2.8.2=pyhd3eb1b0_0
          - python_abi=3.10=2_cp310
          - pyzmq=25.1.0=py310h6a678d5_0
          - readline=8.2=h5eee18b_0
          - requests=2.29.0=py310h06a4308_0
          - ruamel.yaml=0.17.21=py310h5eee18b_0
          - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
          - setuptools=65.6.3=py310h06a4308_0
          - six=1.16.0=pyhd3eb1b0_1
          - sqlite=3.41.2=h5eee18b_0
          - tk=8.6.12=h1ccaba5_0
          - toolz=0.12.0=py310h06a4308_0
          - tornado=6.2=py310h5eee18b_0
          - tqdm=4.65.0=py310h2f386ee_0
          - traitlets=5.7.1=py310h06a4308_0
          - tzdata=2023c=h04d1e81_0
          - urllib3=1.26.16=py310h06a4308_0
          - wheel=0.37.1=pyhd3eb1b0_0
          - xz=5.4.2=h5eee18b_0
          - zeromq=4.3.4=h2531618_0
          - zlib=1.2.13=h5eee18b_0
          - zstandard=0.19.0=py310h5eee18b_0
          - pip:
              - click==8.1.3
              - frogmouth==0.8.0
              - httpx==0.24.1
              - importlib-metadata==6.8.0
              - ipython==8.12.0
              - linkify-it-py==2.0.2
              - loguru==0.7.0
              - mdit-py-plugins==0.4.0
              - onesync==0.1.0
              - pygments==2.15.1
              - sh==2.0.4
              - textual==0.30.0
              - typer==0.9.0
              - typing-extensions==4.6.2
              - uc-micro-py==1.0.2
              - xdg==6.0.0
              - zipp==3.16.2
        prefix: /home/race/miniconda3
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
![image](https://github.com/jupyterlab/jupyterlab/assets/75417963/271d2c94-27ec-4608-ace9-2e2bdbb8094f)

</pre>
</details>

**Comment by raceychan** [comment]
```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/race/miniconda3/envs/myproject/lib/python3.11/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/race/miniconda3/envs/myproject/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 18, in <module>
    from IPython.core.application import (
  File "/home/race/miniconda3/envs/myproject/lib/python3.11/site-packages/IPython/__init__.py", line 53, in <module>
    from .terminal.embed import embed
  File "/home/race/miniconda3/envs/myproject/lib/python3.11/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/home/race/miniconda3/envs/myproject/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 72, in <module>
    from IPython.core.formatters import DisplayFormatter
  File "/home/race/miniconda3/envs/myproject/lib/python3.11/site-packages/IPython/core/formatters.py", line 19, in <module>
    from decorator import decorator
ImportError: cannot import name 'decorator' from 'decorator' (/home/race/myproject/pyprojects/pytutorial/decorator.py)
```

**Comment by krassowski** [comment]
Thanks for opening the issue. This is essentially a duplicate of https://github.com/jupyterlab/jupyterlab/issues/12914 and the actual issue is not really in JupyterLab codebase but in ipykernel/IPython.

**Comment by JasonWeill** [comment]
Closing as a duplicate of #12914. @raceychan Thank you for your contribution! You can subscribe to updates on the existing issue.
