### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by NeilGirdhar** [jupyterlab/jupyterlab#15263]
## Description
Just doing poetry update
```
Building extension in .
/home/neil/.pyenv/versions/3.12.0/lib/python3.12/site-packages/jupyterlab/debuglog.py:56: UserWarning: An error occurred.
  warnings.warn("An error occurred.")
/home/neil/.pyenv/versions/3.12.0/lib/python3.12/site-packages/jupyterlab/debuglog.py:57: UserWarning: ValueError: Extensions require a devDependency on @jupyterlab/builder@^4.0.7, you have a dependency on 3.6.1
  warnings.warn(msg[-1].strip())
/home/neil/.pyenv/versions/3.12.0/lib/python3.12/site-packages/jupyterlab/debuglog.py:58: UserWarning: See the log file for details: /tmp/jupyterlab-debug-ft68wnm7.log
  warnings.warn(f"See the log file for details: {log_path!s}")
rebuilding js and css failed
missing files: ['/home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.12/src/plotly.py/packages/python/plotly/jupyterlab_plotly/labextension/package.json']
Traceback (most recent call last):
  File "/home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.12/src/plotly.py/packages/python/plotly/setup.py", line 495, in <module>
    setup(
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 1001, in run_command
    super().run_command(command)
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.12/src/plotly.py/packages/python/plotly/setup.py", line 104, in run
    raise e
  File "/home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.12/src/plotly.py/packages/python/plotly/setup.py", line 97, in run
    self.distribution.run_command("jsdeps")
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 1001, in run_command
    super().run_command(command)
  File "/tmp/tmpm0ne3wvy/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/neil/.cache/pypoetry/virtualenvs/cmm-tspD8tmv-py3.12/src/plotly.py/packages/python/plotly/setup.py", line 190, in run
    check_call(
  File "/home/neil/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build:prod']' returned non-zero exit status 1.
```
## Context

Ubuntu 22.04, 
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.4.0
jupyter_core==5.4.0
jupyter_server==2.7.3
jupyter_server_terminals==0.4.4
jupyterlab==4.0.7
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.0

**Comment by krassowski** [comment]
1. It looks like you are building jupyterlab plotly. Latest versions should not require this, and we discourage installing source extensions as these require a build environment. Instead you can install a prebuilt extension.
2. Python 3.12 was released last week and potentially there could be some issues as we are not testing against it yet but it is likely unrelated to the issue you are seeing

**Comment by NeilGirdhar** [comment]
@krassowski Thanks for taking a look.  I've been trying to figure out what's wrong for a couple days.  I tried downgrading to Python 3.11, but ti's still broken.

Removing plotly as a dependency seems to get things building again.  It seems like tehre's some kind of hook to install extensions when certain packages are found?

**Comment by krassowski** [comment]
How are you installing plotly/JupyterLab plotly? Do you see the same in a fresh environment?

**Comment by NeilGirdhar** [comment]
@krassowski Just doing `poetry update`.  I don't know what poetry does under the hood, but my pyproject.toml dependencies were:
```
plotly = { git = "https://github.com/plotly/plotly.py.git", subdirectory = "packages/python/plotly" }
jupyter = '>=1'
```

**Comment by krassowski** [comment]
So this is the problem. You should not depend on the raw GitHub code as it needs to be complied. Instead install the appropriate packages from PyPI using pip. Please refer to plotly installation guide for JupyterLab 3+.

**Comment by NeilGirdhar** [comment]
Okay, thanks for your help.

Unfortunately, I needed to do this in order to work around some bugs that were recently fixed, but not released.
