### ISSUE TITLE
Kernel won't connect in simple venv

### ISSUE THREAD

**Issue by xaviernogueira** [jupyterlab/jupyterlab#15353]
## Description

I use `pipenv` for my virtual environment managment. All my environments use Python 3.11. In one of my environments I started using Jupyter Lab just fine. I started a new project, and made a new environment, but no matter what I try I can't connect to the kernel and get `AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports` looping out. There is a `ModuleNotFoundError: No module named 'prompt_toolkit'`. I went out of my way to add `prompt-toolkit` to the virtual environment (didn't work), and then even added it to my base Python (also didn't work).

Also great work guys! Big fan of Jupyter Lab and have had it working many times before on other machines.

## Reproduce

1. Use pipenv to recreate my environment [here](https://github.com/xaviernogueira/Data-Science-Lab/tree/main/databases/postgres). It is a deterministic build, so ideally, the same error can be found. 
2. Fire up Jupyter Lab, and try to run a notebook.
3. The kernel won't connect, and ideally you see the same print out on the consol.

## Context

- Operating System and version: Ubuntu in WSL.
- Browser and version: Firefox, opened via the token link.
- JupyterLab version: 4.0.8

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/bin
        /home/xavier/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /usr/lib/wsl/lib
        /mnt/c/Program Files/PowerShell/7
        /mnt/c/WINDOWS
        /mnt/c/WINDOWS/system32
        /mnt/c/WINDOWS/System32/Wbem
        /mnt/c/WINDOWS/System32/OpenSSH/
        /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
        /mnt/c/Windows
        /mnt/c/Windows/system32
        /mnt/c/Windows/System32/Wbem
        /mnt/c/Windows/System32/WindowsPowerShell/v1.0/
        /mnt/c/Windows/System32/OpenSSH/
        /mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/bin
        /mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/libnvvp
        /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
        /mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
        /mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2022.4.0/
        /mnt/c/Program Files/MiKTeX 2.9/miktex/bin/x64/
        /mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/
        /mnt/c/Program Files/dotnet/
        /mnt/c/ProgramData/chocolatey/bin
        /mnt/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin
        /mnt/c/Program Files/Git/cmd
        /mnt/c/Program Files/Docker/Docker/resources/bin
        /mnt/c/Program Files/PowerShell/7/
        /mnt/c/Users/xavie/AppData/Local/Microsoft/WindowsApps
        /mnt/c/Users/xavie/.dotnet/tools
        /mnt/c/Users/xavie/AppData/Local/Programs/Microsoft VS Code/bin
        /mnt/c/Users/xavie/AppData/Local/GitHubDesktop/bin
        /mnt/c/Users/xavie/AppData/Local/Programs/Python/Python311
        /mnt/c/Users/xavie/AppData/Local/Programs/Python/Python311/Scripts
        /mnt/c/Users/xavie/AppData/Roaming/Python/Python311
        /mnt/c/Users/xavie/AppData/Roaming/Python/Python311/Scripts
        /mnt/c/Users/xavie/AppData/Roaming/Python/Scripts
        /mnt/c/Users/xavie/AppData/Local/Microsoft/WinGet/Packages/BurntSushi.ripgrep.MSVC_Microsoft.Winget.Source_8wekyb3d8bbwe/ripgrep-13.0.0-x86_64-pc-windows-msvc
        /mnt/c/Users/xavie/AppData/Local/Microsoft/WinGet/Packages/sharkdp.fd_Microsoft.Winget.Source_8wekyb3d8bbwe/fd-v8.7.0-x86_64-pc-windows-msvc
        /mnt/c/Users/xavie/.cargo/bin
        /home/xavier/nvim-linux64/bin/nvim
        /mnt/c/Users/xavie/AppData/Local/Programs/Microsoft VS Code/bin
        /mnt/c/Users/xavie/AppData/Local/GitHubDesktop/bin
        /snap/bin

sys.path:
        /home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/bin
        /usr/lib/python311.zip
        /usr/lib/python3.11
        /usr/lib/python3.11/lib-dynload
        /home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages

sys.executable:
        /home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/bin/python

sys.version:
        3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]

platform.platform():
        Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

which -a jupyter:
        /home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/bin/jupyter
        /home/xavier/.local/bin/jupyter

pip list:
        Package                   Version
        ------------------------- ------------
        annotated-types           0.6.0
        anyio                     4.0.0
        argon2-cffi               23.1.0
        argon2-cffi-bindings      21.2.0
        arrow                     1.3.0
        asttokens                 2.4.1
        async-lru                 2.0.4
        attrs                     23.1.0
        Babel                     2.13.1
        backoff                   2.2.1
        bleach                    6.1.0
        certifi                   2023.7.22
        cffi                      1.16.0
        chardet                   5.2.0
        click                     8.1.7
        comm                      0.1.4
        debugpy                   1.8.0
        decorator                 5.1.1
        defusedxml                0.7.1
        docstring-to-markdown     0.13
        executing                 2.0.1
        fastjsonschema            2.18.1
        fqdn                      1.5.1
        greenlet                  3.0.1
        idna                      3.4
        ipykernel                 6.26.0
        ipython                   8.17.2
        ipython-genutils          0.2.0
        ipywidgets                8.1.1
        isoduration               20.11.0
        jedi                      0.19.1
        Jinja2                    3.1.2
        json5                     0.9.14
        jsonpointer               2.4
        jsonschema                4.19.2
        jsonschema-specifications 2023.7.1
        jupysql                   0.10.2
        jupysql-plugin            0.2.6
        jupyter_client            8.5.0
        jupyter_core              5.5.0
        jupyter-events            0.8.0
        jupyter-lsp               2.2.0
        jupyter_server            2.9.1
        jupyter_server_terminals  0.4.4
        jupyterlab                4.0.8
        jupyterlab-lsp            5.0.0
        jupyterlab-pygments       0.2.2
        jupyterlab_server         2.25.0
        jupyterlab-widgets        3.0.9
        MarkupSafe                2.1.3
        matplotlib-inline         0.1.6
        mistune                   3.0.2
        monotonic                 1.6
        nbconvert                 7.10.0
        nbformat                  5.9.2
        nest-asyncio              1.5.8
        notebook_shim             0.2.3
        numpy                     1.26.1
        overrides                 7.4.0
        packaging                 23.2
        pandas                    2.1.2
        pandocfilters             1.5.0
        parso                     0.8.3
        pexpect                   4.8.0
        pip                       23.2.1
        platformdirs              3.11.0
        ploomber-core             0.2.15
        pluggy                    1.3.0
        posthog                   3.0.2
        prettytable               3.9.0
        prometheus-client         0.18.0
        psutil                    5.9.6
        ptyprocess                0.7.0
        pure-eval                 0.2.2
        pycparser                 2.21
        pydantic                  2.4.2
        pydantic_core             2.10.1
        Pygments                  2.16.1
        python-dateutil           2.8.2
        python-json-logger        2.0.7
        python-lsp-jsonrpc        1.1.2
        python-lsp-server         1.8.2
        pytz                      2023.3.post1
        PyYAML                    6.0.1
        pyzmq                     25.1.1
        referencing               0.30.2
        requests                  2.31.0
        rfc3339-validator         0.1.4
        rfc3986-validator         0.1.1
        rpds-py                   0.12.0
        Send2Trash                1.8.2
        setuptools                68.2.2
        six                       1.16.0
        sniffio                   1.3.0
        soupsieve                 2.5
        SQLAlchemy                2.0.23
        sqlglot                   19.0.3
        sqlparse                  0.4.4
        stack-data                0.6.3
        terminado                 0.17.1
        tinycss2                  1.2.1
        tornado                   6.3.3
        traitlets                 5.13.0
        types-python-dateutil     2.8.19.14
        typing_extensions         4.8.0
        tzdata                    2023.3
        ujson                     5.8.0
        uri-template              1.3.0
        urllib3                   2.0.7
        wcwidth                   0.2.9
        webcolors                 1.13
        webencodings              0.5.1
        websocket-client          1.6.4
        wheel                     0.41.3
        widgetsnbextension        4.0.9
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Warning: program returned non-zero exit code #256
WARNING: You don't seem to have any mimeinfo.cache files.
Try running the update-desktop-database command. If you
don't have this command you should install the
desktop-file-utils package. This package is available from
http://freedesktop.org/wiki/Software/desktop-file-utils/
No applications found for mimetype: text/html
.[W 2023-11-05 01:20:57.163 ServerApp] 404 GET /api/kernels/f36abaea-e14f-490e-b9e7-de882777a9c6?1699165256151 (127.0.0.1): Kernel does not exist: f36abaea-e14f-490e-b9e7-de882777a9c6
[W 2023-11-05 01:20:57.163 ServerApp] wrote error: 'Kernel does not exist: f36abaea-e14f-490e-b9e7-de882777a9c6'
    Traceback (most recent call last):
      File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f36abaea-e14f-490e-b9e7-de882777a9c6)

...

[I 2023-11-05 01:23:25.371 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 19, in <module>
    from IPython.core.application import (  # type:ignore[attr-defined]
  File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/IPython/__init__.py", line 54, in <module>
    from .terminal.embed import embed
  File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/xavier/.local/share/virtualenvs/postgres-9ZXp_vWc/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 31, in <module>
    from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
ModuleNotFoundError: No module named 'prompt_toolkit'

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by xaviernogueira** [comment]
Update. Turns out it is a pipenv issue, not yours! False alarm. For anyone else having this issue, pipenv has trouble with the `prompt-toolkit` library. The workaround is to run `pipenv run pip install prompt-toolkit`. Somewhat of a bummer, as I love a deterministic plug-n-play env, but whatever.
