### ISSUE TITLE
Settings do not work when using `oneOf` enum

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15391]
## Description

Changing inline completer via the form UI does not work anymore after the `enum` was replaced with `oneOf` which allows to add labels that support translation.

## Reproduce

1. Go to settings 
2. Select `Inline Completer`
3. Change a setting
4. See error dialog:
   ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/ac7d9959-69fe-4fb3-8720-2018b294927a)
5. See that changing settings works via JSON editor

```python
[W 2023-11-11 18:03:05.853 LabApp] wrote error: "Failed validating input: 'always' is valid under each of {'const': 'onHover', 'title': 'On hover'}, {'const': 'never', 'title': 'Never'}, {'const': 'always', 'title': 'Always'}\n\nFailed validating 'oneOf' in schema['properties']['showWidget']:\n    {'default': 'onHover',\n     'description': 'When to show the inline completer widget.',\n     'oneOf': [{'const': 'always', 'title': 'Always'},\n               {'const': 'onHover', 'title': 'On hover'},\n               {'const': 'never', 'title': 'Never'}],\n     'title': 'Show widget',\n     'type': 'string'}\n\nOn instance['showWidget']:\n    'always'"
    Traceback (most recent call last):
      File "/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
      File "/site-packages/jupyterlab_server/settings_handler.py", line 98, in put
        raise web.HTTPError(400, validation_error % str(e)) from None
    tornado.web.HTTPError: HTTP 400: Bad Request (Failed validating input: 'always' is valid under each of {'const': 'onHover', 'title': 'On hover'}, {'const': 'never', 'title': 'Never'}, {'const': 'always', 'title': 'Always'}
    
    Failed validating 'oneOf' in schema['properties']['showWidget']:
        {'default': 'onHover',
         'description': 'When to show the inline completer widget.',
         'oneOf': [{'const': 'always', 'title': 'Always'},
                   {'const': 'onHover', 'title': 'On hover'},
                   {'const': 'never', 'title': 'Never'}],
         'title': 'Show widget',
         'type': 'string'}
    
    On instance['showWidget']:
        'always')
```

## Expected behavior

UI schema form works with `oneOf`

## Context

- JupyterLab version: 4.1.0ax (`main` branch as of https://github.com/jupyterlab/jupyterlab/commit/6053e59d84a3d59545307a2623403bafa206fd9e)

**Comment by krassowski** [comment]
Clarification: it works with JSON Setting editor if an only if the problematic property with `oneOf` is not present.

**Comment by krassowski** [comment]
So this is down to jupyterlab-server still using JSON schema draf-04 validator:

```python
from jsonschema import Draft4Validator as Validator
```

https://github.com/jupyterlab/jupyterlab_server/blob/d4d23c60126a95a57432bf7d9d3f46f6c62a8470/jupyterlab_server/settings_utils.py#L13-L13

while frontend uses `@rjsf/validator-ajv8` which no longer supports draft-04 (draft-04 was last supported in ajv6):

https://github.com/jupyterlab/jupyterlab/blob/6053e59d84a3d59545307a2623403bafa206fd9e/packages/settingeditor/src/SettingsFormEditor.tsx#L20

From [rjsf docs](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/):

> By default, the @rjsf/validator-ajv8 uses the draft-07 schema version. It is possible to use one of the other version it supports, like draft-2019-09 or draft-2020-12. NOTE: draft-2020-12 has breaking changes and hasn't been fully tested with @rjsf.

Docs for migration:
- [04 → 06](https://json-schema.org/draft-06/json-schema-release-notes)
- [07] https://json-schema.org/draft-07/json-hyper-schema-release-notes
