### ISSUE TITLE
Error querying installed extensions: Error: Unhandled error

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15396]
## Description

Extension manager in 4.1.0a3 produces: `Error querying installed extensions: Error: Unhandled error`:

Upgrading jupyterlab-server-2.25.1 does not help.

## Reproduce

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/a67f57ce-1ac4-4f1e-897b-585ecad69630)

## Expected behavior

Available extensions are shown.

## Context

- JupyterLab version: 4.1.0a3

**Comment by fcollonval** [comment]
I create a new environment with 4.1.0a3 (with only jupyterlab-pygments) and did not encounter that error. Would you be able to provide log or extensions installed to help investigating this one?

**Comment by krassowski** [comment]
```
[E 2023-11-14 11:57:52.854 ServerApp] Uncaught exception GET /lab/api/extensions?refresh=0&1699963071365 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/lab/api/extensions?refresh=0&1699963071365', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
        extensions, last_page = await self.manager.list_extensions(query, page, per_page)
      File "/jupyterlab/extensions/manager.py", line 464, in list_extensions
        await self.refresh(query, page, per_page)
      File "/jupyterlab/extensions/manager.py", line 498, in refresh
        await self._update_extensions_list(query, page, per_page)
      File "/jupyterlab/extensions/manager.py", line 674, in _update_extensions_list
        extensions = await self._get_installed_extensions()
      File "/jupyterlab/extensions/manager.py", line 574, in _get_installed_extensions
        pkg = replace(pkg, latest_version=await self.get_latest_version(pkg.name))
      File "/jupyterlab/extensions/pypi.py", line 161, in get_latest_version
        return ExtensionManager.get_semver_version(data.get("version"))
    AttributeError: 'NoneType' object has no attribute 'get'
[W 2023-11-14 11:57:52.858 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
        extensions, last_page = await self.manager.list_extensions(query, page, per_page)
      File "/jupyterlab/extensions/manager.py", line 464, in list_extensions
        await self.refresh(query, page, per_page)
      File "/jupyterlab/extensions/manager.py", line 498, in refresh
        await self._update_extensions_list(query, page, per_page)
      File "/jupyterlab/extensions/manager.py", line 674, in _update_extensions_list
        extensions = await self._get_installed_extensions()
      File "/jupyterlab/extensions/manager.py", line 574, in _get_installed_extensions
        pkg = replace(pkg, latest_version=await self.get_latest_version(pkg.name))
      File "/jupyterlab/extensions/pypi.py", line 161, in get_latest_version
        return ExtensionManager.get_semver_version(data.get("version"))
    AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by fcollonval** [comment]
Indeed I can confirm I see the same bug on binder.

**Comment by krassowski** [comment]
Locally do you see "No extensions installed" or a list of installed extensions? In an environment without any extensions (/when running in the developer mode) there is no error.
- I can not reproduce it in a clean environment with only `jupyterlab_pygments` installed
- I can reproduce in the same clean environment after `pip install jupyterlab_widgets`

**Comment by krassowski** [comment]
jupyter labextension list

```
JupyterLab v4.1.0a3
3.10.10/envs/test-a3-error/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)

   The following extensions are outdated:
        jupyterlab_pygments
        
   Consider checking if an update is available for these packages.
```

**Comment by firezym** [comment]
jupyterlab 4.1.0a3,  also get the same error "Error querying installed extensions: Error: Unhandled error"
In the server console, I see the following error. In which version will this be fixed? :)
```cmd
[E 2023-11-22 17:19:38.368 ServerApp] Uncaught exception GET /lab/api/extensions?refresh=0&1700644777546 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/lab/api/extensions?refresh=0&1700644777546', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
        extensions, last_page = await self.manager.list_extensions(query, page, per_page)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 464, in list_extensions
        await self.refresh(query, page, per_page)
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 498, in refresh
        await self._update_extensions_list(query, page, per_page)
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 674, in _update_extensions_list
        extensions = await self._get_installed_extensions()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 574, in _get_installed_extensions
        pkg = replace(pkg, latest_version=await self.get_latest_version(pkg.name))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 161, in get_latest_version
        return ExtensionManager.get_semver_version(data.get("version"))
                                                   ^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'get'
[W 2023-11-22 17:19:38.369 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
        extensions, last_page = await self.manager.list_extensions(query, page, per_page)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 464, in list_extensions
        await self.refresh(query, page, per_page)
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 498, in refresh
        await self._update_extensions_list(query, page, per_page)
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 674, in _update_extensions_list
        extensions = await self._get_installed_extensions()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 574, in _get_installed_extensions
        pkg = replace(pkg, latest_version=await self.get_latest_version(pkg.name))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ocean/miniconda3/envs/jl-ext/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 161, in get_latest_version
        return ExtensionManager.get_semver_version(data.get("version"))
                                                   ^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'get'
[E 2023-11-22 17:19:38.370 ServerApp] {
      "Host": "127.0.0.1:8888",
      "Accept": "*/*",
      "Referer": "http://127.0.0.1:8888/lab/tree/magics.ipynb",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
    }
[E 2023-11-22 17:19:38.370 ServerApp] 500 GET /lab/api/extensions?refresh=0&1700644777546 (dea26e5da8a14b1596c17c5ac828e418@127.0.0.1) 821.15ms referer=http://127.0.0.1:8888/lab/tree/magics.ipynb
```

**Comment by fcollonval** [comment]
The fix has not yet been published in a pre-release.
