### ISSUE TITLE
Windowed notebook/ToC breaks after File Changed/"Revert" dialog

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15415]
## Description

After changing the notebook in another instance/in another window/via text editor/version control system reloading it to revert to previous version with "Revert" breaks the windowed notebook. Some of the error trackabcks include:

```ts
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at NotebookWindowedLayout.detachWidget (http://127.0.0.1:8889/static/lab/packages_notebook_lib_index_js.a0899e5b2c84c0887c94.js:9919:38)
    at NotebookWindowedLayout.removeWidget (http://127.0.0.1:8889/static/lab/packages_notebook_lib_index_js.a0899e5b2c84c0887c94.js:9806:18)
    at NotebookWindowedLayout.onChildRemoved (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:13723:14)
    at NotebookWindowedLayout.onChildRemoved (http://127.0.0.1:8889/static/lab/packages_notebook_lib_index_js.a0899e5b2c84c0887c94.js:9997:15)
    at NotebookWindowedLayout.processParentMessage (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:13522:22)
    at Notebook.notifyLayout (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:12938:26)
    at Notebook.processMessage (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:12918:22)
    at invokeHandler (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:9381:21)
    at Object.sendMessage (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:9135:13)
    at set parent [as parent] (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:12581:72)
exceptionHandler @ index.es6.js:377
```

followed by:

```ts
windowedlist.ts:1126 Uncaught Error: Inconsistent dataset index
    at Notebook._update (windowedlist.ts:1126:15)
    at windowedlist.ts:1005:16
```

## Reproduce

1. Set "Windowing mode" in Notebook settings to "ful"
2. Follow the screencast:
![windowed-notebook-breaks](https://github.com/jupyterlab/jupyterlab/assets/5832902/7a77aa6a-abcc-4b54-a945-d535ad4e1454)

## Expected behavior

Reverting does not break the windowed list.

## Context

- Browser and version: Chrome and Firefox
- JupyterLab version: 4.0.x and 4.1.0a3

**Comment by krassowski** [comment]
Stack trace:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/cd776178-89c1-403f-b251-9fc302d585e7)

**Comment by krassowski** [comment]
When revert happens the `cellsChanged` is emitted instructing to first remove all cells and then re-created them. Any `update()` call to windowing list widget while that set of operations is in progress can result in broken state, however update only happens after that. 

The problem is that not all cells get deleted and some linger with a negative index:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/8df87230-ebae-444e-96aa-b97272f8cdb0)

this is because of the special logic to handle active cell:

https://github.com/jupyterlab/jupyterlab/blob/9eea31bc38c7118cfe725e2f60a808f0a3e4c05e/packages/notebook/src/windowing.ts#L264

It looks it is missing `widget !== this._willBeRemoved`.

<details>

Huh, the notebook widget and model are both wired to `onCellsChanged` signal from shared model:

https://github.com/jupyterlab/jupyterlab/blob/9eea31bc38c7118cfe725e2f60a808f0a3e4c05e/packages/notebook/src/widget.ts#L579

https://github.com/jupyterlab/jupyterlab/blob/9eea31bc38c7118cfe725e2f60a808f0a3e4c05e/packages/notebook/src/model.ts#L128

This means that widget and model may have divergent state, and results will vary depending on which signal handler gets registered first.

</details>
