### ISSUE TITLE
have problem with --PyPIExtensionManager.base_url

### ISSUE THREAD

**Issue by tjc0726** [jupyterlab/jupyterlab#15480]
## Description
Hi all, not sure if it's a bug, I'm using --PyPIExtensionManager.base_url to change the default repository and it goes wrong,with console says following when I refresh the broswer to get the extension:
`
[E 2023-12-03 00:17:05.848 ServerApp] Uncaught exception GET /lab/api/extensions?query&page=1&per_page=30&refresh=0&1701533825681 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='www.aaa.xyz', method='GET', uri='/lab/api/extensions?query&page=1&per_page=30&refresh=0&1701533825681', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/ubuntu/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
        extensions, last_page = await self.manager.list_extensions(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/manager.py", line 368, in list_extensions
        await self.refresh(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/manager.py", line 402, in refresh
        await self._update_extensions_list(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/manager.py", line 575, in _update_extensions_list
        extensions, last_page = await self.list_packages(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/pypi.py", line 201, in list_packages
        matches = await self.__get_all_extensions()
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/pypi.py", line 255, in __get_all_extensions
        self.__all_packages_cache = await self.__throttleRequest(
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/pypi.py", line 156, in __throttleRequest
        data = await current_loop.run_in_executor(None, fn, *args)
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
        response = self.__transport.request(
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
        return self.single_request(host, handler, request_body, verbose)
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
        raise ProtocolError(
    xmlrpc.client.ProtocolError: <ProtocolError for mirrors.cloud.tencent.com/pypi/simple: 301 Moved Permanently>
[W 2023-12-03 00:17:05.850 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/ubuntu/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
        extensions, last_page = await self.manager.list_extensions(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/manager.py", line 368, in list_extensions
        await self.refresh(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/manager.py", line 402, in refresh
        await self._update_extensions_list(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/manager.py", line 575, in _update_extensions_list
        extensions, last_page = await self.list_packages(query, page, per_page)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/pypi.py", line 201, in list_packages
        matches = await self.__get_all_extensions()
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/pypi.py", line 255, in __get_all_extensions
        self.__all_packages_cache = await self.__throttleRequest(
      File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyterlab/extensions/pypi.py", line 156, in __throttleRequest
        data = await current_loop.run_in_executor(None, fn, *args)
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
        response = self.__transport.request(
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
        return self.single_request(host, handler, request_body, verbose)
      File "/usr/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
        raise ProtocolError(
    xmlrpc.client.ProtocolError: <ProtocolError for mirrors.cloud.tencent.com/pypi/simple: 301 Moved Permanently>
[E 2023-12-03 00:17:05.850 ServerApp] {
      "Host": "www.aaa.xyz",
      "Accept": "*/*",
      "Referer": "https://www.aaa.xyz/lab/tree/work",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
    }
`

## Reproduce
`jupyter lab --PyPIExtensionManager.base_url=https://mirrors.cloud.tencent.com/pypi/simple`

## Expected behavior
As the way I use the normal pypi,this url is basically same with the https://pypi.org/pypi，so I don't know what went wrong,thank for help!

## Context
- JupyterLab version:4.0.8

By the way,is there a way to put the base_url into the config file of jupyter lab so that I dont need to add argument after command,I'm still new to jupyter,thanks for the help

**Comment by tjc0726** [comment]
> Thanks @tjc0726. Can you try JupyterLab 4.0.9? There were some improvements to `PyPIExtensionManager` introduced in #15404 that landed in 4.0.9. There are further enhancements slotted for 4.1 if you are happy with trying out pre-releases.

Of course,but I tried 4.0.9 and 4.10a4 just a moment ago and it was the same issue

**Comment by JasonWeill** [comment]
I think the protocol error is because https://mirrors.cloud.tencent.com/pypi/simple redirects to the non-secure http://mirrors.cloud.tencent.com/pypi/simple . Can you try setting the base URL to http://mirrors.cloud.tencent.com/pypi/simple (with `http://` instead of `https://`)?

**Comment by JasonWeill** [comment]
@tjc0726 Unfortunately, this isn't something that Jupyter can support, because the problem occurs when contacting the Tencent-operated mirror. Please try using a different Pypi mirror, or, if you can, contact the operators of the Tencent mirror. The mirror needs to support the PyPI XMLRPC API. 

If there's anything else that we can do, please reopen this issue or open a new issue. Thanks for your contribution!
