### ISSUE TITLE
`usage2` started failing on CI with `RuntimeError: This event loop is already running`

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15570]
This appears to coincide with `jupyter_core` [5.6.0](https://github.com/jupyter/jupyter_core/releases/tag/v5.6.0) release yesterday.

```python
Traceback (most recent call last):
  File "/Users/runner/test_install/bin/jupyter-labhub", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/runner/test_install/lib/python3.11/site-packages/jupyterlab/labhubapp.py", line 41, in main
    return SingleUserLabApp.launch_instance(argv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/test_install/lib/python3.11/site-packages/jupyter_core/application.py", line 307, in launch_instance
    loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/runner/test_install/lib/python3.11/site-packages/jupyter_core/application.py", line 292, in _async_launch_instance
    app.initialize(argv)
  File "/Users/runner/test_install/lib/python3.11/site-packages/jupyterhub/singleuser/mixins.py", line 952, in initialize
    result = super().initialize(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/test_install/lib/python3.11/site-packages/jupyterhub/singleuser/mixins.py", line 607, in initialize
    super().initialize(argv)
  File "/Users/runner/test_install/lib/python3.11/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/test_install/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 2610, in initialize
    self.init_httpserver()
  File "/Users/runner/test_install/lib/python3.11/site-packages/jupyterhub/singleuser/mixins.py", line 632, in init_httpserver
    self.io_loop.run_sync(super().init_httpserver)
  File "/Users/runner/test_install/lib/python3.11/site-packages/tornado/ioloop.py", line 533, in run_sync
    self.start()
  File "/Users/runner/test_install/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 596, in run_forever
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 588, in _check_running
Error:     raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

**Comment by krassowski** [comment]
This appears related to https://github.com/jupyter/jupyter_core/pull/381 and there is a bug report in `jupyter_core` about this too: https://github.com/jupyter/jupyter_core/issues/383.

**Comment by krassowski** [comment]
@blink1073 is this something that should be addressed in JupyterLab's `labhubapp.py` or a bug in jupyter-core?

**Comment by blink1073** [comment]
Ah, okay, I now have a good thing to test for regressions.  I'll yank the core release.

**Comment by blink1073** [comment]
Yanked.

**Comment by krassowski** [comment]
Thank you!
