### ISSUE TITLE
Missing "jupyterlab/observables": "4.6.7" in npmjs 

### ISSUE THREAD

**Issue by brichet** [jupyterlab/jupyterlab#15677]
## Description

The release of [Jupyterlab 3.6.7](https://github.com/jupyterlab/jupyterlab/releases/tag/v3.6.7) should have pushed [`"jupyterlab/observables": "4.6.7"`](https://github.com/jupyterlab/jupyterlab/releases/tag/%40jupyterlab%2Fobservables%404.6.7), but the package does not appear in [npmjs](https://www.npmjs.com/package/@jupyterlab/observables?activeTab=versions).

## Expected behavior

The package to be on npmjs.

## Context

Some Jupyterlab test still using Jupyterlab 3 (don't know if this is expected or an oversight), and these test fails because it can fetch `"jupyterlab/observables": "4.6.7"`.
e.g. https://github.com/jupyterlab/jupyterlab/actions/runs/7586747899/job/20665619640?pr=15375#step:6:1342

**Comment by krassowski** [comment]
Thanks for opening this! From the release action logs (https://github.com/krassowski/jupyterlab-skip-traceback/actions/runs/7609388017/job/20720515088?pr=3), the upload of artifacts worked up to `jupyterlab-docprovider-3.6.7` but the traceback is not infromative at all: 

```
Handling dist file dist/jupyterlab-application-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-application-3.6.7.tgz
Handling dist file dist/jupyterlab-application-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-application-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-apputils-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-apputils-3.6.7.tgz
Handling dist file dist/jupyterlab-apputils-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-apputils-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-attachments-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-attachments-3.6.7.tgz
Handling dist file dist/jupyterlab-builder-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-builder-3.6.7.tgz
Handling dist file dist/jupyterlab-buildutils-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-buildutils-3.6.7.tgz
Handling dist file dist/jupyterlab-cell-toolbar-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-cell-toolbar-3.6.7.tgz
Handling dist file dist/jupyterlab-cell-toolbar-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-cell-toolbar-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-cells-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-cells-3.6.7.tgz
Handling dist file dist/jupyterlab-celltags-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-celltags-3.6.7.tgz
Handling dist file dist/jupyterlab-celltags-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-celltags-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-codeeditor-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-codeeditor-3.6.7.tgz
Handling dist file dist/jupyterlab-codemirror-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-codemirror-3.6.7.tgz
Handling dist file dist/jupyterlab-codemirror-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-codemirror-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-collaboration-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-collaboration-3.6.7.tgz
Handling dist file dist/jupyterlab-collaboration-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-collaboration-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-completer-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-completer-3.6.7.tgz
Handling dist file dist/jupyterlab-completer-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-completer-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-console-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-console-3.6.7.tgz
Handling dist file dist/jupyterlab-console-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-console-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-coreutils-5.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-coreutils-5.6.7.tgz
Handling dist file dist/jupyterlab-csvviewer-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-csvviewer-3.6.7.tgz
Handling dist file dist/jupyterlab-csvviewer-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-csvviewer-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-debugger-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-debugger-3.6.7.tgz
Handling dist file dist/jupyterlab-debugger-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-debugger-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-docmanager-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-docmanager-3.6.7.tgz
Handling dist file dist/jupyterlab-docmanager-extension-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-docmanager-extension-3.6.7.tgz
Handling dist file dist/jupyterlab-docprovider-3.6.7.tgz
COMMAND: npm publish --tag latest jupyterlab-docprovider-3.6.7.tgz
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.7/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/cli.py", line 122, in invoke
    super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/click/core.py", line 1[434](https://github.com/jupyterlab/jupyterlab/actions/runs/7585246424/job/20660661347#step:4:437), in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/cli.py", line 679, in publish_assets
    lib.publish_assets(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/lib.py", line 445, in publish_assets
    raise e
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/lib.py", line 440, in publish_assets
    util.run(f"{npm_cmd} {name}", cwd=dist_dir, quiet=True, quiet_error=True, echo=True)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'npm publish --tag latest jupyterlab-docprovider-3.6.7.tgz' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/actions/finalize_release.py", line 15, in <module>
    run_action("jupyter-releaser publish-assets")
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/actions/common.py", line 25, in run_action
    _run(target, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser publish-assets' returned non-zero exit status 1.
```

**Comment by krassowski** [comment]
It seems to me that there were no incidents on npm at the time according to https://status.npmjs.org/history and this version has not been previously published, so we were either rate limited or there was a transient networking error.

**Comment by krassowski** [comment]
Attempting to publish `jupyterlab-docprovider-3.6.7` manually fails too:

```
npm notice 
npm notice 📦  @jupyterlab/docprovider@3.6.7
npm notice === Tarball Contents === 
npm notice 681B  lib/awareness.d.ts  
npm notice 2.2kB lib/awareness.js    
npm notice 1.5kB lib/awareness.js.map
npm notice 164B  lib/index.d.ts      
npm notice 459B  lib/index.js        
npm notice 211B  lib/index.js.map    
npm notice 485B  lib/mock.d.ts       
npm notice 622B  lib/mock.js         
npm notice 432B  lib/mock.js.map     
npm notice 1.4kB lib/tokens.d.ts     
npm notice 338B  lib/tokens.js       
npm notice 235B  lib/tokens.js.map   
npm notice 1.8kB lib/yprovider.d.ts  
npm notice 4.6kB lib/yprovider.js    
npm notice 3.6kB lib/yprovider.js.map
npm notice 1.9kB package.json        
npm notice 396B  style/index.css     
npm notice 388B  style/index.js      
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/docprovider                 
npm notice version:       3.6.7                                   
npm notice filename:      jupyterlab-docprovider-3.6.7.tgz        
npm notice package size:  5.9 kB                                  
npm notice unpacked size: 21.4 kB                                 
npm notice shasum:        097851a397cc72abf107054d355b0017aa7b1d05
npm notice integrity:     sha512-WNXrT4Kmh4fIc[...]QIRviq30ITwoQ==
npm notice total files:   18                                      
npm notice 
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
Authenticate your account at:
[...]
Press ENTER to open in the browser...
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@jupyterlab%2fdocprovider - Not found
npm ERR! 404 
npm ERR! 404  '@jupyterlab/docprovider@3.6.7' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

The response from https://registry.npmjs.org/@jupyterlab%2fdocprovider includes:

`"ERROR: No README data found!"`

Does npm now reject packages without a README?

**Comment by fcollonval** [comment]
Done - @brichet I restarted the test failing you linked. Would you mind closing this if it is solved? Don't hesitate to ping me here otherwise?

**Comment by brichet** [comment]
Thanks @fcollonval, it should be solved now.

**Comment by jtpio** [comment]
Looks like `@jupyterlab/galata` version `4.5.7` is also missing on npm: https://www.npmjs.com/package/@jupyterlab/galata?activeTab=versions

**Comment by jtpio** [comment]
> Looks like `@jupyterlab/galata` version `4.5.7` is also missing on npm: https://www.npmjs.com/package/@jupyterlab/galata?activeTab=versions

Just published manually, using the tarball from the GitHub release: https://www.npmjs.com/package/@jupyterlab/galata/v/4.5.7

Also reset the `latest` to point to `5.1.2` afterwards, with: `npm dist-tag add @jupyterlab/galata@5.1.2 latest`
