### ISSUE TITLE
Ci failing across jobs on installation step

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15692]
Today between 13:16  and 14:18 GMT our CI started failing across branches, e.g.:
- https://github.com/jupyterlab/jupyterlab/pull/15691
- https://github.com/jupyterlab/jupyterlab/pull/15600
- https://github.com/jupyterlab/jupyterlab/pull/15271
- https://github.com/jupyterlab/jupyterlab/pull/15539

Most recent PR with passing (majority of) checks: https://github.com/jupyterlab/jupyterlab/pull/15659

The logs suggest this is coming from `hatchling`, with relevant bit:

```python
       File "/tmp/-/overlay/lib/python3.11/site-packages/hatchling/version/source/code.py", line 47, in get_version_data
          spec = importlib.util.spec_from_file_location(os.path.splitext(path)[0], path)  # type: ignore
                 ^^^^^^^^^^^^^^
      AttributeError: module 'importlib' has no attribute 'util'
```

Full log of the failing step:

<details>

```
+ set -o pipefail
+ export YARN_ENABLE_GLOBAL_CACHE=1
+ YARN_ENABLE_GLOBAL_CACHE=1
+ export YARN_ENABLE_INLINE_BUILDS=1
+ YARN_ENABLE_INLINE_BUILDS=1
+ '[' linux-gnu == linux-gnu ']'
++ which yarn
+ sudo rm -rf /usr/local/bin/yarn
+ yarn
./scripts/ci_install.sh: line 19: yarn: command not found
+ mkdir -p /home/runner/.jupyter
+ git config --global user.name foo
+ git config --global user.email foo@bar.com
+ pip install -q --upgrade pip --user
+ pip --version
pip 23.3.2 from /opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip (python 3.11)
+ pip install -e '.[dev,test]'
Obtaining file:///home/runner/work/jupyterlab/jupyterlab
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): still running...
  Preparing editable metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [311 lines of output]
      INFO:hatch_jupyter_builder.utils:Running jupyter-builder
      INFO:hatch_jupyter_builder.utils:Writing pre-commit hook
      INFO:hatch_jupyter_builder.utils:Building with buildapi.builder
      INFO:hatch_jupyter_builder.utils:With kwargs: {'build_cmd': 'build', 'source_dir': 'packages', 'build_dir': 'dev_mode/static', 'npm': ['node', 'jupyterlab/staging/yarn.js']}
      INFO:hatch_jupyter_builder.utils:Installing build dependencies with npm.  This may take a while...
      INFO:hatch_jupyter_builder.utils:> /opt/hostedtoolcache/node/18.19.0/x64/bin/node jupyterlab/staging/yarn.js install
      ➤ YN0000: ┌ Project validation
Project validation
      ➤ YN0000: └ Completed
      ➤ YN0000: ┌ Resolution step
Resolution step
      ➤ YN0000: └ Completed in 0s 515ms
      ➤ YN0000: ┌ Fetch step
Fetch step
      ➤ YN0000: └ Completed in 31s 673ms
      ➤ YN0000: ┌ Link step
Link step
      ➤ YN0000: └ Completed in 32s 446ms
      ➤ YN0000: Done with warnings in 1m 5s
      INFO:hatch_jupyter_builder.utils:> /opt/hostedtoolcache/node/18.19.0/x64/bin/node jupyterlab/staging/yarn.js run build
      
      > @jupyterlab/repo-top@0.0.1 build:dev
      > npm run integrity && npm run build:all && cd dev_mode && npm run build
      
      
      > @jupyterlab/repo-top@0.0.1 integrity
      > node scripts/ensure-buildutils.js && node buildutils/lib/ensure-repo.js
      
      Error: Command failed: hatchling version
      Traceback (most recent call last):
        File "/tmp/pip-build-env-fj9ca3sh/overlay/bin/hatchling", line 8, in <module>
          sys.exit(hatchling())
                   ^^^^^^^^^^^
        File "/tmp/pip-build-env-fj9ca3sh/overlay/lib/python3.11/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
          command(**kwargs)
        File "/tmp/pip-build-env-fj9ca3sh/overlay/lib/python3.11/site-packages/hatchling/cli/version/__init__.py", line 33, in version_impl
          version_data = source.get_version_data()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fj9ca3sh/overlay/lib/python3.11/site-packages/hatchling/version/source/code.py", line 47, in get_version_data
          spec = importlib.util.spec_from_file_location(os.path.splitext(path)[0], path)  # type: ignore
                 ^^^^^^^^^^^^^^
      AttributeError: module 'importlib' has no attribute 'util'
      
          at checkExecSyncError (node:child_process:890:11)
          at Object.execSync (node:child_process:962:15)
          at run (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:263:43)
          at Object.getPythonVersion (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:203:19)
          at ensureJupyterlab (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/ensure-repo.js:596:24)
          at ensureIntegrity (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/ensure-repo.js:789:19)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
        status: 1,
        signal: null,
        output: [
          null,
          <Buffer >,
          <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 74 6d 70 2f 70 69 ... 806 more bytes>
        ],
        pid: 2308,
        stdout: <Buffer >,
        stderr: <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 74 6d 70 2f 70 69 ... 806 more bytes>
      }
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
          hook = backend.prepare_metadata_for_build_editable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line [17](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:18)6, in prepare_metadata_for_build_editable
          whl_basename = build_hook(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fj9ca3sh/overlay/lib/python3.11/site-packages/hatchling/build.py", line 82, in build_editable
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fj9ca3sh/overlay/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
          build_hook.initialize(version, build_data)
        File "/tmp/pip-build-env-fj9ca3sh/normal/lib/python3.11/site-packages/hatch_jupyter_builder/plugin.py", line 87, in initialize
          raise e
        File "/tmp/pip-build-env-fj9ca3sh/normal/lib/python3.11/site-packages/hatch_jupyter_builder/plugin.py", line 82, in initialize
          build_func(self.target_name, version, **build_kwargs)
        File "/home/runner/work/jupyterlab/jupyterlab/buildapi.py", line 20, in builder
          npm_builder(target_name, version, *args, **kwargs)
        File "/tmp/pip-build-env-fj9ca3sh/normal/lib/python3.11/site-packages/hatch_jupyter_builder/utils.py", line 115, in npm_builder
          run([*npm_cmd, "run", build_cmd], cwd=str(abs_path))
        File "/tmp/pip-build-env-fj9ca3sh/normal/lib/python3.11/site-packages/hatch_jupyter_builder/utils.py", line 229, in run
          return subprocess.check_call(cmd, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/node/[18](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:19).[19](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:20).0/x64/bin/node', 'jupyterlab/staging/yarn.js', 'run', 'build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
+ pip install -v -e '.[dev,test]'
Using pip 23.3.2 from /opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip (python 3.11)
Obtaining file:///home/runner/work/jupyterlab/jupyterlab
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Collecting hatchling>=1.5.0
    Using cached hatchling-1.21.0-py3-none-any.whl.metadata (3.8 kB)
  Collecting editables>=0.3 (from hatchling>=1.5.0)
    Using cached editables-0.5-py3-none-any.whl.metadata (3.1 kB)
  Collecting packaging>=21.3 (from hatchling>=1.5.0)
    Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
  Collecting pathspec>=0.10.1 (from hatchling>=1.5.0)
    Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
  Collecting pluggy>=1.0.0 (from hatchling>=1.5.0)
    Using cached pluggy-1.4.0-py3-none-any.whl.metadata (4.3 kB)
  Collecting trove-classifiers (from hatchling>=1.5.0)
    Using cached trove_classifiers-[20](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:21)24.1.8-py3-none-any.whl.metadata (2.2 kB)
  Using cached hatchling-1.[21](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:22).0-py3-none-any.whl (76 kB)
  Using cached editables-0.5-py3-none-any.whl (5.1 kB)
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
  Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
  Using cached pluggy-1.4.0-py3-none-any.whl (20 kB)
  Using cached trove_classifiers-2024.1.8-py3-none-any.whl (13 kB)
  Installing collected packages: trove-classifiers, pluggy, pathspec, packaging, editables, hatchling
  Successfully installed editables-0.5 hatchling-1.21.0 packaging-23.2 pathspec-0.12.1 pluggy-1.4.0 trove-classifiers-2024.1.8
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Running command Getting requirements to build editable
  Getting requirements to build editable: finished with status 'done'
  Installing backend dependencies: started
  Running command pip subprocess to install backend dependencies
  Collecting hatch-jupyter-builder>=0.3.2
    Using cached hatch_jupyter_builder-0.8.3-py3-none-any.whl (17 kB)
  Collecting hatchling>=1.5 (from hatch-jupyter-builder>=0.3.2)
    Using cached hatchling-1.21.0-py3-none-any.whl.metadata (3.8 kB)
  Collecting editables>=0.3 (from hatchling>=1.5->hatch-jupyter-builder>=0.3.2)
    Using cached editables-0.5-py3-none-any.whl.metadata (3.1 kB)
  Collecting packaging>=21.3 (from hatchling>=1.5->hatch-jupyter-builder>=0.3.2)
    Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
  Collecting pathspec>=0.10.1 (from hatchling>=1.5->hatch-jupyter-builder>=0.3.2)
    Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
  Collecting pluggy>=1.0.0 (from hatchling>=1.5->hatch-jupyter-builder>=0.3.2)
    Using cached pluggy-1.4.0-py3-none-any.whl.metadata (4.3 kB)
  Collecting trove-classifiers (from hatchling>=1.5->hatch-jupyter-builder>=0.3.2)
    Using cached trove_classifiers-2024.1.8-py3-none-any.whl.metadata (2.2 kB)
  Using cached hatchling-1.21.0-py3-none-any.whl (76 kB)
  Using cached editables-0.5-py3-none-any.whl (5.1 kB)
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
  Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
  Using cached pluggy-1.4.0-py3-none-any.whl (20 kB)
  Using cached trove_classifiers-2024.1.8-py3-none-any.whl (13 kB)
  Installing collected packages: trove-classifiers, pluggy, pathspec, packaging, editables, hatchling, hatch-jupyter-builder
  Successfully installed editables-0.5 hatch-jupyter-builder-0.8.3 hatchling-1.21.0 packaging-23.2 pathspec-0.12.1 pluggy-1.4.0 trove-classifiers-2024.1.8
  Installing backend dependencies: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Running command Preparing editable metadata (pyproject.toml)
  INFO:hatch_jupyter_builder.utils:Running jupyter-builder
  WARNING:hatch_jupyter_builder.utils:Refusing to overwrite pre-commit hook
  INFO:hatch_jupyter_builder.utils:Building with buildapi.builder
  INFO:hatch_jupyter_builder.utils:With kwargs: {'build_cmd': 'build', 'source_dir': 'packages', 'build_dir': 'dev_mode/static', 'npm': ['node', 'jupyterlab/staging/yarn.js']}
  INFO:hatch_jupyter_builder.utils:Installing build dependencies with npm.  This may take a while...
  INFO:hatch_jupyter_builder.utils:> /opt/hostedtoolcache/node/18.19.0/x64/bin/node jupyterlab/staging/yarn.js install
  ➤ YN0000: ┌ Project validation
Project validation
  ➤ YN0000: └ Completed
  ➤ YN0000: ┌ Resolution step
Resolution step
  ➤ YN0000: └ Completed in 0s 649ms
  ➤ YN0000: ┌ Fetch step
Fetch step
  ➤ YN0000: └ Completed in 0s 525ms
  ➤ YN0000: ┌ Link step
Link step
  ➤ YN0000: └ Completed in 0s 853ms
  ➤ YN0000: Done with warnings in 2s 303ms
  INFO:hatch_jupyter_builder.utils:> /opt/hostedtoolcache/node/18.19.0/x64/bin/node jupyterlab/staging/yarn.js run build

  > @jupyterlab/repo-top@0.0.1 build:dev
  > npm run integrity && npm run build:all && cd dev_mode && npm run build


  > @jupyterlab/repo-top@0.0.1 integrity
  > node scripts/ensure-buildutils.js && node buildutils/lib/ensure-repo.js

  Error: Command failed: hatchling version
  Traceback (most recent call last):
    File "/tmp/pip-build-env-9gan39t1/overlay/bin/hatchling", line 8, in <module>
      sys.exit(hatchling())
               ^^^^^^^^^^^
    File "/tmp/pip-build-env-9gan39t1/overlay/lib/python3.11/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
      command(**kwargs)
    File "/tmp/pip-build-env-9gan39t1/overlay/lib/python3.11/site-packages/hatchling/cli/version/__init__.py", line 33, in version_impl
      version_data = source.get_version_data()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-9gan39t1/overlay/lib/python3.11/site-packages/hatchling/version/source/code.py", line 47, in get_version_data
      spec = importlib.util.spec_from_file_location(os.path.splitext(path)[0], path)  # type: ignore
             ^^^^^^^^^^^^^^
  AttributeError: module 'importlib' has no attribute 'util'

      at checkExecSyncError (node:child_process:890:11)
      at Object.execSync (node:child_process:962:15)
      at run (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:263:43)
      at Object.getPythonVersion (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/utils.js:203:19)
      at ensureJupyterlab (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/ensure-repo.js:596:24)
      at ensureIntegrity (/home/runner/work/jupyterlab/jupyterlab/buildutils/lib/ensure-repo.js:789:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    status: 1,
    signal: null,
    output: [
      null,
      <Buffer >,
      <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 [22](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:23) 2f 74 6d 70 2f 70 69 ... 806 more bytes>
    ],
    pid: [24](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:25)05,
    stdout: <Buffer >,
    stderr: <Buffer 54 72 61 63 65 62 61 63 6b 20 [28](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:29) 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 [29](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:30) 3a 0a 20 20 46 69 6c 65 20 22 2f 74 6d 70 2f 70 69 ... 806 more bytes>
  }
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
      hook = backend.prepare_metadata_for_build_editable
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line [33](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:34)5, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 176, in prepare_metadata_for_build_editable
      whl_basename = build_hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-9gan[39](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:40)t1/overlay/lib/python3.11/site-packages/hatchling/build.py", line 82, in build_editable
      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-9gan39t1/overlay/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
      build_hook.initialize(version, build_data)
    File "/tmp/pip-build-env-9gan39t1/normal/lib/python3.11/site-packages/hatch_jupyter_builder/plugin.py", line 87, in initialize
      raise e
    File "/tmp/pip-build-env-9gan39t1/normal/lib/python3.11/site-packages/hatch_jupyter_builder/plugin.py", line 82, in initialize
      build_func(self.target_name, version, **build_kwargs)
    File "/home/runner/work/jupyterlab/jupyterlab/buildapi.py", line 20, in builder
      npm_builder(target_name, version, *args, **kwargs)
    File "/tmp/pip-build-env-9gan39t1/normal/lib/python3.11/site-packages/hatch_jupyter_builder/utils.py", line 115, in npm_builder
      run([*npm_cmd, "run", build_cmd], cwd=str(abs_path))
    File "/tmp/pip-build-env-9gan39t1/normal/lib/python3.11/site-packages/hatch_jupyter_builder/utils.py", line 229, in run
      return subprocess.check_call(cmd, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/subprocess.py", line [41](https://github.com/jupyterlab/jupyterlab/actions/runs/7642145402/job/20821094705?pr=15271#step:4:42)3, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/node/18.19.0/x64/bin/node', 'jupyterlab/staging/yarn.js', 'run', 'build']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/hostedtoolcache/Python/3.11.7/x64/bin/python /opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmpvbu_5l3l
  cwd: /home/runner/work/jupyterlab/jupyterlab
  Preparing editable metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.
```

</details>

**Comment by krassowski** [comment]
Hatchling did not have a new release since December 18th: https://pypi.org/project/hatchling/#history so it might be unrelated. Both the passing and failing builds use Python 3.11 so not change there either.

Discussion on `importlib.util` working only if some third-party dependencies (like sphinx) make it work: https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641/4

**Comment by fcollonval** [comment]
Thanks a lot @krassowski for quickly working on a fix.

**Comment by krassowski** [comment]
Thanks! Hatchling [v1.21.1](https://github.com/pypa/hatch/releases/tag/hatchling-v1.21.1) was released 7 hours ago with https://github.com/pypa/hatch/pull/1222 which fixed the issue - closing as done :tada:

**Comment by fcollonval** [comment]
I restarted a failing job - and unfortunately it fails because the CI used the cached version of hatchling. I guess we should force the minimum version.

**Comment by krassowski** [comment]
Maybe the PyPI mirrors had not yet propagated when you restarted? I saw jobs pass on other PRs restarted with close/reopen approach.
