### ISSUE TITLE
CI started failing on `4.0.x` branch (after release of JupyterLab `4.1`?)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15764]
## Description

As seen in https://github.com/jupyterlab/jupyterlab/pull/15763 CI is failing on `4.0.x` branch. This first happened after merge of https://github.com/jupyterlab/jupyterlab/pull/15742 which happened a few hours after JupyterLab 4.1.0 release (and did not happen on the PR branch, also the PR content appears unrelated).

The following tests are failing:
- Linux Tests / Install from SDist and Test (pull_request)
- Linux Tests / Test Minimum Versions (pull_request) 
- Linux Tests / Linux (python, 3.11) (pull_request)
- Linux Tests / Linux (python, 3.8) (pull_request) 
- Windows Tests / Windows (python) (pull_request) 
- macOS Tests / macOS (python, 3.11) (pull_request)

```
=========================== short test summary info ===========================
FAILED jupyterlab/tests/test_jupyterlab.py::TestExtension::test_build_custom_minimal_core_config - RuntimeError: JupyterLab failed to build
======= 1 failed, 65 passed, 3 skipped, 4 warnings in 565.80s (0:09:25) =======
```

```
DEBUG    jupyterlab_test_logger:commands.py:1970 Node v18.19.0

DEBUG    jupyterlab_test_logger:commands.py:2013 Yarn configuration loaded.
DEBUG    jupyterlab_test_logger:commands.py:94 > /opt/hostedtoolcache/node/18.19.0/x64/bin/npm pack /tmp/tmpl7chp0ap/extension
DEBUG    jupyterlab_test_logger:commands.py:126 npm notice 
npm notice 📦  @jupyterlab/mock-extension@4.0.12
npm notice === Tarball Contents === 
npm notice 459B index.js       
npm notice 383B mock_package.py
npm notice 346B package.json   
npm notice 378B setup.py       
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/mock-extension              
npm notice version:       4.0.12                                  
npm notice filename:      jupyterlab-mock-extension-4.0.12.tgz    
npm notice package size:  817 B                                   
npm notice unpacked size: 1.6 kB                                  
npm notice shasum:        66ff430cfa181f404d98b50ffcc9055[602](https://github.com/jupyterlab/jupyterlab/actions/runs/7814380657/job/21320054724?pr=15763#step:6:609)91560f
npm notice integrity:     sha512-SSMpsCu1f6CP5[...]SVMIYCFggLyaA==
npm notice total files:   4                                       
npm notice 
jupyterlab-mock-extension-4.0.12.tgz

DEBUG    jupyterlab_test_logger:commands.py:1970 Node v18.19.0

INFO     jupyterlab_test_logger:commands.py:698 Building jupyterlab assets (production, minimized)
DEBUG    jupyterlab_test_logger:commands.py:94 > /opt/hostedtoolcache/node/18.19.0/x64/bin/npm pack /tmp/tmpl7chp0ap/extension
DEBUG    jupyterlab_test_logger:commands.py:126 npm notice 
npm notice 📦  @jupyterlab/mock-extension@4.0.12
npm notice === Tarball Contents === 
npm notice 459B index.js       
npm notice 383B mock_package.py
npm notice 346B package.json   
npm notice 378B setup.py       
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/mock-extension              
npm notice version:       4.0.12                                  
npm notice filename:      jupyterlab-mock-extension-4.0.12.tgz    
npm notice package size:  817 B                                   
npm notice unpacked size: 1.6 kB                                  
npm notice shasum:        66ff430cfa181f404d98b50ffcc905560291560f
npm notice integrity:     sha512-SSMpsCu1f6CP5[...]SVMIYCFggLyaA==
npm notice total files:   4                                       
npm notice 
jupyterlab-mock-extension-4.0.12.tgz

DEBUG    jupyterlab_test_logger:commands.py:94 > node /home/runner/work/jupyterlab/jupyterlab/jupyterlab/staging/yarn.js install
DEBUG    jupyterlab_test_logger:commands.py:126 ➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 2s 130ms
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0000: └ Completed in 1s 147ms
➤ YN0000: ┌ Link step
Link step
➤ YN0000: └ Completed in 5s 837ms
➤ YN0000: Done with warnings in 9s 206ms

DEBUG    jupyterlab_test_logger:commands.py:94 > node /home/runner/work/jupyterlab/jupyterlab/jupyterlab/staging/yarn.js dlx yarn-berry-deduplicate -s fewerHighest --fail
DEBUG    jupyterlab_test_logger:commands.py:126 ➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 0s 711ms
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
Link step
➤ YN0000: └ Completed in 0s 691ms
➤ YN0000: Done in 1s 457ms

Found duplicates, yarn.lock changed

Found duplicated entries. Run yarn-deduplicate to deduplicate them.

DEBUG    jupyterlab_test_logger:commands.py:94 > node /home/runner/work/jupyterlab/jupyterlab/jupyterlab/staging/yarn.js
DEBUG    jupyterlab_test_logger:commands.py:126 ➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 0s 227ms
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0000: └ Completed in 0s 217ms
➤ YN0000: ┌ Link step
Link step
➤ YN0000: └ Completed in 0s 275ms
➤ YN0000: Done with warnings in 0s 805ms

DEBUG    jupyterlab_test_logger:commands.py:94 > node /home/runner/work/jupyterlab/jupyterlab/jupyterlab/staging/yarn.js run build:prod:minimize
DEBUG    jupyterlab_test_logger:commands.py:126 [webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'util' in '/tmp/tmp_kgl0v0k/staging/node_modules/@rjsf/utils/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/Compilation.js:2016:28
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/tmp/tmp_kgl0v0k/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/tmp/tmp_kgl0v0k/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/NormalModuleFactory.js:[670](https://github.com/jupyterlab/jupyterlab/actions/runs/7814380657/job/21320054724?pr=15763#step:6:683):25
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /tmp/tmp_kgl0v0k/staging/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve 'util' in '/tmp/tmp_kgl0v0k/staging/node_modules/@rjsf/utils/lib'
  Parsed request is a module
  using description file: /tmp/tmp_kgl0v0k/staging/node_modules/@rjsf/utils/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /tmp/tmp_kgl0v0k/staging/node_modules/@rjsf/utils/lib/node_modules doesn't exist or is not a directory
      /tmp/tmp_kgl0v0k/staging/node_modules/@rjsf/utils/node_modules doesn't exist or is not a directory
      /tmp/tmp_kgl0v0k/staging/node_modules/@rjsf/node_modules doesn't exist or is not a directory
      /tmp/tmp_kgl0v0k/staging/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /tmp/tmp_kgl0v0k/staging/node_modules
        single file module
          using description file: /tmp/tmp_kgl0v0k/staging/package.json (relative path: ./node_modules/util)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/tmp_kgl0v0k/staging/node_modules/util doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/tmp_kgl0v0k/staging/node_modules/util.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/tmp_kgl0v0k/staging/node_modules/util.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/tmp_kgl0v0k/staging/node_modules/util.wasm doesn't exist
        /tmp/tmp_kgl0v0k/staging/node_modules/util doesn't exist
      /tmp/tmp_kgl0v0k/node_modules doesn't exist or is not a directory
      /tmp/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

DEBUG    jupyterlab_test_logger:commands.py:[722](https://github.com/jupyterlab/jupyterlab/actions/runs/7814380657/job/21320054724?pr=15763#step:6:738) JupyterLab failed to build
```

<details>

```
================================== FAILURES ===================================
_____________ TestExtension.test_build_custom_minimal_core_config _____________

self = <jupyterlab.tests.test_jupyterlab.TestExtension testMethod=test_build_custom_minimal_core_config>

    @pytest.mark.slow
    def test_build_custom_minimal_core_config(self):
        default_config = CoreConfig()
        core_config = CoreConfig()
        core_config.clear_packages()
        logger = logging.getLogger("jupyterlab_test_logger")
        logger.setLevel("DEBUG")
        app_dir = self.tempdir()
        options = AppOptions(
            app_dir=app_dir,
            core_config=core_config,
            logger=logger,
            use_sys_dir=False,
        )
    
        extensions = (
            "@jupyterlab/application-extension",
            "@jupyterlab/apputils-extension",
        )
        singletons = (
            "@jupyterlab/application",
            "@jupyterlab/apputils",
            "@jupyterlab/coreutils",
            "@jupyterlab/services",
        )
        for name in extensions:
            semver = default_config.extensions[name]
            core_config.add(name, semver, extension=True)
        for name in singletons:
            semver = default_config.singletons[name]
            core_config.add(name, semver)
    
        assert install_extension(self.mock_extension, app_options=options) is True
>       build(app_options=options)

jupyterlab\tests\test_jupyterlab.py:532: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
jupyterlab\commands.py:507: in build
    return handler.build(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <jupyterlab.commands._AppHandler object at 0x00000222BF52B250>
name = None, version = None, static_url = None, clean_staging = False
production = True, minimize = True

    def build(
        self,
        name=None,
        version=None,
        static_url=None,
        clean_staging=False,
        production=True,
        minimize=True,
    ):
        """Build the application."""
        if production is None:
            production = not (self.info["linked_packages"] or self.info["local_extensions"])
    
        if not production:
            minimize = False
    
        # If splicing, make sure the source packages are built
        if self._options.splice_source:
            ensure_node_modules(REPO_ROOT, logger=self.logger)
            self._run(["node", YARN_PATH, "build:packages"], cwd=REPO_ROOT)
    
        info = ["production" if production else "development"]
        if production:
            info.append("minimized" if minimize else "not minimized")
        self.logger.info(f'Building jupyterlab assets ({", ".join(info)})')
    
        # Set up the build directory.
        app_dir = self.app_dir
    
        self._populate_staging(
            name=name, version=version, static_url=static_url, clean=clean_staging
        )
    
        staging = pjoin(app_dir, "staging")
    
        # Make sure packages are installed.
        ret = self._run(["node", YARN_PATH, "install"], cwd=staging)
        if ret != 0:
            msg = "npm dependencies failed to install"
            self.logger.debug(msg)
            raise RuntimeError(msg)
    
        # Build the app.
        dedupe_yarn(staging, self.logger)
        command = f'build:{"prod" if production else "dev"}{":minimize" if minimize else ""}'
        ret = self._run(["node", YARN_PATH, "run", command], cwd=staging)
        if ret != 0:
            msg = "JupyterLab failed to build"
            self.logger.debug(msg)
>           raise RuntimeError(msg)
E           RuntimeError: JupyterLab failed to build

jupyterlab\commands.py:723: RuntimeError
```

</details>

**Comment by fcollonval** [comment]
The issue is coming from that line that deal with `@rsjf` being used in the browser (where `TextEncoder` is defined) or in NodeJS (where it is not):

https://github.com/rjsf-team/react-jsonschema-form/blob/0782878084602c4dd8e7a6e362bc0af003eef98a/packages/utils/src/base64.ts#L16

Using the fallback `util: false` should be fine. It seems that this is a recent change in rsjf: https://github.com/rjsf-team/react-jsonschema-form/commit/f31bef19c1420aec74384fc4f4152bed579f0902#diff-2cca430703c7938409b371c53a2504c5af43865587872598d6642451a5313be7. So it will likely affect main branch too.

This probably means we need to update the base webpack configuration: https://github.com/jupyterlab/jupyterlab/blob/a546463243b7bba228f616f946f731b5a153f0ec/builder/src/webpack.config.base.ts#L69

**Comment by fcollonval** [comment]
I added the fallback in https://github.com/jupyterlab/jupyterlab/pull/15763/commits/1dd784350a12b788b84ddc37a0f91b53ae58d813 to see if it fixes the issue.

**Comment by krassowski** [comment]
Thanks! Did it help? I do not see the build because it shows the commit as detached.

**Comment by fcollonval** [comment]
It unfortunately did not: https://github.com/jupyterlab/jupyterlab/actions/runs/7916084902/job/21609232809?pr=15763

But I'm not sure that test is using the dev version of the builder package.

**Comment by fcollonval** [comment]
Xref: https://github.com/rjsf-team/react-jsonschema-form/issues/4080

**Comment by krassowski** [comment]
Intrigued that this happens on 4.0.x but not on main. For some reason it must be resolving `@rjsf/utils` to a newer version.

**Comment by fcollonval** [comment]
My guess seems correct as changing the webpack config in staging is fixing the test: https://github.com/jupyterlab/jupyterlab/actions/runs/7931875811/job/21657069636

But I find it odd too that we are not hitting it on the main branch.

**Comment by fcollonval** [comment]
My guess is that on 4.0.x new packages are needed to fix the yarn.lock (as the dedupe step is reporting there are deduplication). That results in newer version of @rjsf/utils with the issue. On main, the same test does not alter that part of the yarn.lock - hence no issue.

One way to check that theory would be to bump @rjsf/utils on main and we should hit the same issue.

**Comment by fcollonval** [comment]
For example in https://github.com/jupyterlab/jupyterlab/actions/runs/7931363603/job/21655439711

The python job reports no duplicates:

> No duplicates found, yarn.lock identical

So this supports my guess

**Comment by fcollonval** [comment]
We could probably just wait a week. They are reverting the change in @rjsf/utils as it was only for testing.

**Comment by krassowski** [comment]
'Twas a short week: https://github.com/rjsf-team/react-jsonschema-form/releases/tag/v5.17.1 :tada: 

Thanks for the investigation and nudging upstream!
