### ISSUE TITLE
Inline completer nested config fails to be configured by `overrides.json`

### ISSUE THREAD

**Issue by bilcus** [jupyterlab/jupyterlab#15895]
## Description

Using `override.json` to configure the inline completer to use Jupyter AI fails and prevents JupyterLab from loading.

Using the following config `share/jupyter/lab/settings/overrides.json`:
```json
{
  "@jupyterlab/completer-extension:inline-completer": {
    "streamingAnimation": "uncover",
    "showWidget": "always",
    "providers": {
        "@jupyterlab/inline-completer:history": {
            "enabled": true,
            "timeout": 20000,
            "debouncerDelay": 1000,
            "maxSuggestions": 100
        },
        "@jupyterlab/jupyter-ai": {
            "enabled": true,
            "timeout": 20000,
            "debouncerDelay": 1000,
            "maxPrefix": 10000,
            "maxSuffix": 10000,
            "disabledLanguages": [
                "ipythongfm"
            ],
            "streaming": "manual"
        }
    }
  }
}
```

Lab frontend does not load, is stuck on a white screen, producing this error:

```
2024-03-01 10:47:21,823 - ServerApp - ERROR - Uncaught exception GET /lab/api/settings?1709318841795 (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/settings?1709318841795', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages/tornado/web.py", line 3301, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages/jupyterlab_server/settings_handler.py", line 57, in get
    result, warnings = get_settings(
                       ^^^^^^^^^^^^^
  File "/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages/jupyterlab_server/settings_utils.py", line 386, in get_settings
    settings_list, warnings = _list_settings(
                              ^^^^^^^^^^^^^^^
  File "/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages/jupyterlab_server/settings_utils.py", line 174, in _list_settings
    schema, version = _get_schema(schemas_dir, schema_name, overrides, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages/jupyterlab_server/settings_utils.py", line 65, in _get_schema
    schema = _override(schema_name, schema, overrides)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages/jupyterlab_server/settings_utils.py", line 238, in _override
    new_defaults = schema["properties"][key]["default"]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'default'
```

This is despite `~/.jupyter/lab/user-settings/@jupyterlab/completer-extension/inline-completer.jupyterlab-settings` being a valid config:
```json
{
    "showWidget": "always",
    "showShortcuts": true,
    "streamingAnimation": "uncover",
    "providers": {
        "@jupyterlab/inline-completer:history": {
            "enabled": true,
            "timeout": 20000,
            "debouncerDelay": 1000,
            "maxSuggestions": 100
        },
        "@jupyterlab/jupyter-ai": {
            "enabled": false,
            "timeout": 20000,
            "debouncerDelay": 1000,
            "maxPrefix": 10000,
            "maxSuffix": 10000,
            "disabledLanguages": [
                "ipythongfm"
            ],
            "streaming": "always"
        }
    }
}
```

## Reproduce

1. Start with a fresh venv and install jupyterlab and jupyter-ai.
2. Set the above override.json
3. Start JupyterLab

## Context

- Operating System and version: macOS-14.3.1-arm64-arm-64bit
- Browser and version: 
- JupyterLab version: 4.1.2

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/Users/ondrej/dev/venvs/jup/bin
	/Users/ondrej/.rd/bin
	/opt/homebrew/Caskroom/miniconda/base/bin
	/opt/homebrew/opt/llvm/bin
	/usr/local/opt/gnu-sed/libexec/gnubin
	/Users/ondrej/bin
	/usr/local/bin
	/Users/ondrej/go/bin
	/usr/local/opt/python/libexec/bin
	/Applications/Sublime Text.app/Contents/SharedSupport/bin
	/opt/homebrew/bin
	/opt/homebrew/sbin
	/usr/local/bin
	/System/Cryptexes/App/usr/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
	/usr/local/hatch/bin
	/Users/ondrej/.fig/bin
	/Users/ondrej/.local/bin
	/Users/ondrej/Library/Application Support/JetBrains/Toolbox/scripts
	/opt/homebrew/opt/fzf/bin
	/Users/ondrej/Library/Application Support/JetBrains/Toolbox/scripts
	/Users/ondrej/.local/bin
	/Users/ondrej/go/bin
	/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin
	/Users/ondrej/.fig/bin
	/Applications/Sublime Text.app/Contents/SharedSupport/bin

sys.path:
	/Users/ondrej/dev/venvs/jup/bin
	/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python311.zip
	/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11
	/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
	/Users/ondrej/dev/venvs/jup/lib/python3.11/site-packages

sys.executable:
	/Users/ondrej/dev/venvs/jup/bin/python

sys.version:
	3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]

platform.platform():
	macOS-14.3.1-arm64-arm-64bit

which -a jupyter:
	/Users/ondrej/dev/venvs/jup/bin/jupyter
	/opt/homebrew/bin/jupyter

pip list:
	Package                   Version
	------------------------- ---------------
	aiohttp                   3.9.3
	aiosignal                 1.3.1
	aiosqlite                 0.20.0
	annotated-types           0.6.0
	anyio                     4.3.0
	appnope                   0.1.4
	argon2-cffi               23.1.0
	argon2-cffi-bindings      21.2.0
	arrow                     1.3.0
	asttokens                 2.4.1
	async-lru                 2.0.4
	attrs                     23.2.0
	Babel                     2.14.0
	beautifulsoup4            4.12.3
	bleach                    6.1.0
	certifi                   2024.2.2
	cffi                      1.16.0
	charset-normalizer        3.3.2
	click                     8.1.7
	cloudpickle               3.0.0
	comm                      0.2.1
	dask                      2024.2.1
	dataclasses-json          0.6.4
	debugpy                   1.8.1
	decorator                 5.1.1
	deepmerge                 1.1.1
	defusedxml                0.7.1
	distributed               2024.2.1
	executing                 2.0.1
	faiss-cpu                 1.7.4
	fastjsonschema            2.19.1
	fqdn                      1.5.1
	frozenlist                1.4.1
	fsspec                    2024.2.0
	h11                       0.14.0
	h2o_notebook_theme        0.4.1
	httpcore                  1.0.4
	httpx                     0.27.0
	idna                      3.6
	importlib-metadata        7.0.1
	ipykernel                 6.29.3
	ipython                   8.22.1
	isoduration               20.11.0
	jedi                      0.19.1
	Jinja2                    3.1.3
	json5                     0.9.17
	jsonpatch                 1.33
	jsonpath-ng               1.6.1
	jsonpointer               2.4
	jsonschema                4.21.1
	jsonschema-specifications 2023.12.1
	jupyter_ai                2.10.0
	jupyter_ai_magics         2.10.0
	jupyter_client            8.6.0
	jupyter_core              5.7.1
	jupyter-events            0.9.0
	jupyter-lsp               2.2.3
	jupyter_server            2.12.5
	jupyter_server_terminals  0.5.2
	jupyterlab                4.1.2
	jupyterlab_pygments       0.3.0
	jupyterlab_server         2.25.3
	langchain                 0.1.9
	langchain-community       0.0.24
	langchain-core            0.1.28
	langsmith                 0.1.10
	locket                    1.0.0
	MarkupSafe                2.1.5
	marshmallow               3.21.0
	matplotlib-inline         0.1.6
	mistune                   3.0.2
	msgpack                   1.0.7
	multidict                 6.0.5
	mypy-extensions           1.0.0
	nbclient                  0.9.0
	nbconvert                 7.16.1
	nbformat                  5.9.2
	nest-asyncio              1.6.0
	notebook_shim             0.2.4
	numpy                     1.26.4
	orjson                    3.9.15
	overrides                 7.7.0
	packaging                 23.2
	pandocfilters             1.5.1
	parso                     0.8.3
	partd                     1.4.1
	pexpect                   4.9.0
	pip                       23.3.2
	platformdirs              4.2.0
	ply                       3.11
	prometheus_client         0.20.0
	prompt-toolkit            3.0.43
	psutil                    5.9.8
	ptyprocess                0.7.0
	pure-eval                 0.2.2
	pycparser                 2.21
	pydantic                  2.6.3
	pydantic_core             2.16.3
	Pygments                  2.17.2
	python-dateutil           2.8.2
	python-json-logger        2.0.7
	PyYAML                    6.0.1
	pyzmq                     25.1.2
	referencing               0.33.0
	regex                     2023.12.25
	requests                  2.31.0
	rfc3339-validator         0.1.4
	rfc3986-validator         0.1.1
	rpds-py                   0.18.0
	Send2Trash                1.8.2
	setuptools                69.0.3
	six                       1.16.0
	sniffio                   1.3.1
	sortedcontainers          2.4.0
	soupsieve                 2.5
	SQLAlchemy                2.0.27
	stack-data                0.6.3
	tblib                     3.0.0
	tenacity                  8.2.3
	terminado                 0.18.0
	tiktoken                  0.6.0
	tinycss2                  1.2.1
	toolz                     0.12.1
	tornado                   6.4
	traitlets                 5.14.1
	types-python-dateutil     2.8.19.20240106
	typing_extensions         4.10.0
	typing-inspect            0.9.0
	uri-template              1.3.0
	urllib3                   2.2.1
	wcwidth                   0.2.13
	webcolors                 1.13
	webencodings              0.5.1
	websocket-client          1.7.0
	wheel                     0.42.0
	yarl                      1.9.4
	zict                      3.0.0
	zipp                      3.17.0

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Thank you for reporting! It comes from these lines in [jupyterlab-server](https://github.com/jupyterlab/jupyterlab_server/blob/91a081672f05d6611b7d7a9f832695e863403c1d/jupyterlab_server/settings_utils.py#L236-L245). Apparently it assumes that an explicit default is always given; I think we can fix this for inline completer by adding an explicit empty default object in lines:

https://github.com/jupyterlab/jupyterlab/blob/ffca65da6af72ae4cbdf9d1ba8e1095f1ac54e3d/packages/completer-extension/schema/inline-completer.json#L30-L33
