### ISSUE TITLE
Publishing 4.2.0a2 failed: Package `@jupyterlab/workspaces` could not be found

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16055]
The new  `@jupyterlab/workspaces` was successfully published to npm: https://www.npmjs.com/package/@jupyterlab/workspaces

```
Handling dist file dist/jupyterlab-workspaces-4.2.0-alpha.2.tgz
COMMAND: npm publish --tag next jupyterlab-workspaces-4.2.0-alpha.2.tgz
Handling dist file dist/jupyterlab-workspaces-extension-4.2.0-alpha.2.tgz
COMMAND: npm publish --tag next jupyterlab-workspaces-extension-4.2.0-alpha.2.tgz
Handling dist file dist/metadata.json
Nothing to upload for metadata.json
Running hooks for after-publish-assets
> @jupyterlab/repo-top@0.0.1 after:publish:assets
> jlpm && npm run build:utils && node buildutils/lib/publish --skip-publish
```

but in the subsequent step of `after:publish:assets`, the CI failed with:

```
Uncaught exception PackageNotFoundError: Package `@jupyterlab/workspaces` could not be found
    at packageJson (/home/runner/work/jupyterlab/jupyterlab/.jupyter_releaser_checkout/node_modules/package-json/index.js:72:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handlePackage (/home/runner/work/jupyterlab/jupyterlab/.jupyter_releaser_checkout/buildutils/lib/update-dist-tag.js:58:21)
    at async Promise.all (index 120)
    at async Command.<anonymous> (/home/runner/work/jupyterlab/jupyterlab/.jupyter_releaser_checkout/buildutils/lib/publish.js:94:22)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.8/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 139, in invoke
    util.run(hook)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'npm run after:publish:assets' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/finalize_release.py", line 15, in <module>
    run_action("jupyter-releaser publish-assets")
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/common.py", line 25, in run_action
    _run(target, *args, **kwargs)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser publish-assets' returned non-zero exit status 1.
```

I wonder if this was just an issue of a delay between the `npm` upload and the artefact becoming available?

**Comment by krassowski** [comment]
It looks that all artifacts were uploaded (both npm and https://pypi.org/project/jupyterlab/4.2.0a2/) and release check is passing on CI (https://github.com/jupyterlab/jupyterlab/pull/16056) so I will go ahead an undraft the GitHub release.

There is a follow-up task of fixing the examples job thoguh: https://github.com/jupyterlab/jupyterlab/issues/16057

**Comment by jtpio** [comment]
> I wonder if this was just an issue of a delay between the `npm` upload and the artefact becoming available?

It could be yes (this happened with previous releases).

**Comment by krassowski** [comment]
This also happened with newly added https://www.npmjs.com/package/@jupyterlab/video-extension for 4.5.0a2 (https://github.com/jupyterlab/jupyterlab/actions/runs/16833404865/job/47686636430).

Since the PyPI project and npm packages were updated successfully I undrafted https://github.com/jupyterlab/jupyterlab/releases/tag/v4.5.0a2 manually.

**Comment by MMesch** [comment]
@krassowski how about giving this a more general name since it seems to be a recurring CI problem worth investigating / fixing?

**Comment by yohimik** [comment]
A newer partial-publication example has a different immediate cause. The [10 August release run](https://github.com/jupyterlab/jupyterlab/actions/runs/31419894584) uploaded JupyterLab 4.6.3, then failed in `after:publish:assets` on `npm dist-tag add @jupyterlab/services@7.6.2 latest` with E401. [PyPI 4.6.3](https://pypi.org/project/jupyterlab/4.6.3/) already had its wheel and sdist from that run.

This is an authorization failure after one destination completed, not the registry-visibility delay reported in the original incident. Recovery therefore had to preserve the completed PyPI receipt while finishing the remaining npm dist-tag and release-finalization work; retrying all publication steps would risk colliding with artifacts already present.
