### ISSUE TITLE
Usage tests are failing on CI: Mac 3.11 and Linux 3.12

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16086]
As seen in https://github.com/jupyterlab/jupyterlab/pull/16083:

```
+ python -m pip install copier jinja2-time 'pydantic<2'
Collecting copier
  Downloading copier-9.1.1-py3-none-any.whl.metadata (8.0 kB)
Collecting jinja2-time
  Downloading jinja2_time-0.2.0-py2.py3-none-any.whl.metadata (5.1 kB)
Collecting pydantic<2
  Downloading pydantic-1.10.14-cp311-cp311-macosx_10_9_x86_64.whl.metadata (150 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.2/150.2 kB 4.0 MB/s eta 0:00:00
Collecting colorama>=0.4.6 (from copier)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: decorator>=5.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from copier) (5.1.1)
Collecting dunamai>=1.7.0 (from copier)
  Downloading dunamai-1.19.2-py3-none-any.whl.metadata (10 kB)
Collecting funcy>=1.17 (from copier)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: jinja2>=3.1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from copier) (3.1.3)
Collecting jinja2-ansible-filters>=1.3.1 (from copier)
  Downloading jinja2_ansible_filters-1.3.2-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: packaging>=23.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from copier) (24.0)
Requirement already satisfied: pathspec>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from copier) (0.12.1)
Collecting plumbum>=1.6.9 (from copier)
  Downloading plumbum-1.8.2-py3-none-any.whl.metadata (10 kB)
INFO: pip is looking at multiple versions of copier to determine which version is compatible with other requirements. This could take a while.
Collecting copier
  Downloading copier-9.1.0-py3-none-any.whl.metadata (7.9 kB)
  Downloading copier-9.0.1-py3-none-any.whl.metadata (7.9 kB)
  Downloading copier-8.3.0-py3-none-any.whl.metadata (7.9 kB)
  Downloading copier-8.2.0-py3-none-any.whl.metadata (7.9 kB)
  Downloading copier-8.1.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: pygments>=2.7.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from copier) (2.17.2)
Requirement already satisfied: pyyaml>=5.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from copier) (6.0.1)
Collecting pyyaml-include>=1.2 (from copier)
  Downloading pyyaml_include-2.0-py3-none-any.whl.metadata (18 kB)
Collecting questionary>=1.8.1 (from copier)
  Downloading questionary-2.0.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: arrow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2-time) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic<2) (4.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2>=3.1.3->copier) (2.1.5)
Collecting fsspec>=2021.04.0 (from pyyaml-include>=1.2->copier)
  Downloading fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Collecting prompt_toolkit<=3.0.36,>=2.0 (from questionary>=1.8.1->copier)
  Downloading prompt_toolkit-3.0.36-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: python-dateutil>=2.7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from arrow->jinja2-time) (2.9.0.post0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from arrow->jinja2-time) (2.9.0.20240316)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from prompt_toolkit<=3.0.36,>=2.0->questionary>=1.8.1->copier) (0.2.13)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.7.0->arrow->jinja2-time) (1.16.0)
Downloading copier-8.1.0-py3-none-any.whl (38 kB)
Downloading jinja2_time-0.2.0-py2.py3-none-any.whl (6.4 kB)
Downloading pydantic-1.10.14-cp311-cp311-macosx_10_9_x86_64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 12.6 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading dunamai-1.19.2-py3-none-any.whl (25 kB)
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Downloading jinja2_ansible_filters-1.3.2-py3-none-any.whl (18 kB)
Downloading plumbum-1.8.2-py3-none-any.whl (127 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.0/127.0 kB 14.4 MB/s eta 0:00:00
Downloading pyyaml_include-2.0-py3-none-any.whl (28 kB)
Downloading questionary-2.0.1-py3-none-any.whl (34 kB)
Downloading fsspec-2024.3.1-py3-none-any.whl (171 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 15.3 MB/s eta 0:00:00
Downloading prompt_toolkit-3.0.36-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.4/386.4 kB 17.6 MB/s eta 0:00:00
Installing collected packages: funcy, pydantic, prompt_toolkit, plumbum, fsspec, dunamai, colorama, questionary, pyyaml-include, jinja2-ansible-filters, jinja2-time, copier
  Attempting uninstall: prompt_toolkit
    Found existing installation: prompt-toolkit 3.0.43
    Uninstalling prompt-toolkit-3.0.43:
      Successfully uninstalled prompt-toolkit-3.0.43
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 8.23.0 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.
Successfully installed colorama-0.4.6 copier-8.1.0 dunamai-1.19.2 fsspec-2024.3.1 funcy-2.0 jinja2-ansible-filters-1.3.2 jinja2-time-0.2.0 plumbum-1.8.2 prompt_toolkit-3.0.36 pydantic-1.10.14 pyyaml-include-2.0 questionary-2.0.1
+ python -m jupyterlab.upgrade_extension --no-input jupyterlab/tests/mock_packages/extension
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/runner/work/jupyterlab/jupyterlab/jupyterlab/upgrade_extension.py", line 27, in <module>
    raise RuntimeError(msg) from None
RuntimeError: Please install copier and jinja2-time
Error: Process completed with exit code 1.
```

**Comment by krassowski** [comment]
These were already failing shortly after 3pm GMT today after I merged https://github.com/jupyterlab/jupyterlab/pull/16077 but not before when the PR was made (at 1:17AM GMT).

**Comment by krassowski** [comment]
The diff between successful and failing job:

```
8c8
<      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.2/150.2 kB 3.6 MB/s eta 0:00:00
---
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.2/150.2 kB 10.0 MB/s eta 0:00:00
33c33
<   Downloading pyyaml_include-1.4.1-py3-none-any.whl.metadata (1.3 kB)
---
>   Downloading pyyaml_include-2.0-py3-none-any.whl.metadata (18 kB)
39a40,41
> Collecting fsspec>=2021.04.0 (from pyyaml-include>=1.2->copier)
>   Downloading fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
49c51
<    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.9/158.9 kB 18.9 MB/s eta 0:00:00
---
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.9/158.9 kB 42.8 MB/s eta 0:00:00
55,56c57,58
<    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.0/127.0 kB 27.9 MB/s eta 0:00:00
< Downloading pyyaml_include-1.4.1-py3-none-any.whl (19 kB)
---
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.0/127.0 kB 40.6 MB/s eta 0:00:00
> Downloading pyyaml_include-2.0-py3-none-any.whl (28 kB)
58a61,62
> Downloading fsspec-2024.3.1-py3-none-any.whl (171 kB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 46.0 MB/s eta 0:00:00
60,61c64,65
<    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.4/386.4 kB 17.3 MB/s eta 0:00:00
< Installing collected packages: funcy, typing-extensions, pyyaml-include, prompt_toolkit, plumbum, dunamai, colorama, questionary, pydantic, jinja2-ansible-filters, jinja2-time, copier
---
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.4/386.4 kB 73.6 MB/s eta 0:00:00
> Installing collected packages: funcy, typing-extensions, prompt_toolkit, plumbum, fsspec, dunamai, colorama, questionary, pyyaml-include, pydantic, jinja2-ansible-filters, jinja2-time, copier
67,68c71,72
< ipython 8.22.2 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.
< Successfully installed colorama-0.4.6 copier-8.1.0 dunamai-1.19.2 funcy-2.0 jinja2-ansible-filters-1.3.2 jinja2-time-0.2.0 plumbum-1.8.2 prompt_toolkit-3.0.36 pydantic-1.10.14 pyyaml-include-1.4.1 questionary-2.0.1 typing-extensions-4.10.0
---
> ipython 8.23.0 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.
> Successfully installed colorama-0.4.6 copier-8.1.0 dunamai-1.19.2 fsspec-2024.3.1 funcy-2.0 jinja2-ansible-filters-1.3.2 jinja2-time-0.2.0 plumbum-1.8.2 prompt_toolkit-3.0.36 pydantic-1.10.14 pyyaml-include-2.0 questionary-2.0.1 typing-extensions-4.10.0
```

Indeed https://pypi.org/project/pyyaml-include/2.0/ was released yesterday at the time it started failing.

**Comment by krassowski** [comment]
Our error message is misleading, because `copier` is installed. The thing is it cannot be imported due to the breaking change in `pyyaml-include`: https://github.com/copier-org/copier/issues/1568. New version of copier will drop the dependency on `pyyaml-include` but CI is installing from 8.x branch not 9.x because of some dependency conflicts.
