### ISSUE TITLE
Error Enabling jupyter_nbextensions_configurator with Jupyter Notebook

### ISSUE THREAD

**Issue by palparam** [jupyterlab/jupyterlab#16281]
I am using Python 3.12.3. 
I installed nbextension and configurator by the commands:
$pip install jupyter_contrib_nbextensions
$pip install jupyter_nbextensions_configurator

Then when I try to enable configurator, 
$jupyter contrib nbextension install --user

hitting error :
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Scripts\jupyter-contrib.EXE\__main__.py", line 7, in <module>
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\config\application.py", line 1073, in launch_instance
    app = cls.instance(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\config\configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_contrib_core\application.py", line 27, in __init__
    self._refresh_subcommands()
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_contrib_core\application.py", line 43, in _refresh_subcommands
    get_subcommands_dict = entrypoint.load()
                           ^^^^^^^^^^^^^^^^^
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 2482, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 2488, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_contrib_nbextensions\__init__.py", line 5, in <module>
    import jupyter_nbextensions_configurator
  File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_nbextensions_configurator\__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'

$jupyter --version
Selected Jupyter core packages...
IPython          : 8.24.0
ipykernel        : 6.29.4
ipywidgets       : not installed
jupyter_client   : 8.6.1
jupyter_core     : 5.7.2
jupyter_server   : 2.14.0
jupyterlab       : 4.1.8
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.1.3
qtconsole        : not installed
traitlets        : 5.14.3

I installed 'nbclassic' package also as mentioned in other thread as solution for jupyterlab but still seeing issue
Ref: https://github.com/jupyterlab/jupyterlab/issues/15053

**Comment by JasonWeill** [comment]
@palparam Thank you for opening this issue! It looks like this is not an issue specific to JupyterLab. Can you please open an issue here? https://github.com/jupyter/nbclassic/issues

Because nbclassic is in a different GitHub organization than jupyterlab is, I can't move it over myself. Thank you for your contributions!
