### ISSUE TITLE
ctrl/cmd+enter scrolls to top of cell instead of doing nothing

### ISSUE THREAD

**Issue by LunarLanding** [jupyterlab/jupyterlab#16433]
## Reproduce

0.1. Disable all keyboard utilities and mappers.
0.2. Install jupyter with micromamba in a clean env by using `micromamba env create -n jupyter_dev python==3.11 jupyterlab`
1. Start jupyter with `jupyter lab --core-mode`
2. Create new empty notebook with code cell that is taller than browser window.
3. Execute with ctrl+enter (cmd+enter on mac).
4. Observe that the view is scrolled to the beginning of the cell, hiding the line the cursor is at.

## Expected behavior

The cell should execute without scrolling and the cursor should stay put.

## Context

- Operating System and version: OSX Sonoma 14.5
- Browser and version: Firefox 126.0.1
- JupyterLab version: 4.2.1

It seems that the cell will not scroll if the cursor is roughly in the middle of the cell.

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	$CONDA_PREFIX/envs/jupyter_dev/bin
	$CONDA_PREFIX/condabin
	REDACTED

sys.path:
	$CONDA_PREFIX/envs/jupyter_dev/bin
	$CONDA_PREFIX/envs/jupyter_dev/lib/python311.zip
	$CONDA_PREFIX/envs/jupyter_dev/lib/python3.11
	$CONDA_PREFIX/envs/jupyter_dev/lib/python3.11/lib-dynload
	$CONDA_PREFIX/envs/jupyter_dev/lib/python3.11/site-packages

sys.executable:
	$CONDA_PREFIX/envs/jupyter_dev/bin/python

sys.version:
	3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:25:12) [Clang 14.0.6 ]

platform.platform():
	macOS-14.5-arm64-arm-64bit

which -a jupyter:
	$CONDA_PREFIX/envs/jupyter_dev/bin/jupyter

pip list:
	Package                   Version
	------------------------- --------------
	anyio                     4.3.0
	appnope                   0.1.4
	argon2-cffi               23.1.0
	argon2-cffi-bindings      21.2.0
	arrow                     1.3.0
	asttokens                 2.4.1
	async-lru                 2.0.4
	attrs                     23.2.0
	Babel                     2.14.0
	beautifulsoup4            4.12.3
	bleach                    6.1.0
	Brotli                    1.1.0
	cached-property           1.5.2
	certifi                   2024.2.2
	cffi                      1.16.0
	charset-normalizer        3.3.2
	comm                      0.2.2
	debugpy                   1.8.1
	decorator                 5.1.1
	defusedxml                0.7.1
	entrypoints               0.4
	exceptiongroup            1.2.0
	executing                 2.0.1
	fastjsonschema            2.19.1
	fqdn                      1.5.1
	h11                       0.14.0
	h2                        4.1.0
	hpack                     4.0.0
	httpcore                  1.0.5
	httpx                     0.27.0
	hyperframe                6.0.1
	idna                      3.7
	importlib_metadata        7.1.0
	importlib_resources       6.4.0
	ipykernel                 6.29.3
	ipython                   8.25.0
	isoduration               20.11.0
	jedi                      0.19.1
	Jinja2                    3.1.4
	json5                     0.9.25
	jsonpointer               2.4
	jsonschema                4.22.0
	jsonschema-specifications 2023.12.1
	jupyter_client            8.6.2
	jupyter_core              5.7.2
	jupyter-events            0.10.0
	jupyter-lsp               2.2.5
	jupyter_server            2.14.1
	jupyter_server_terminals  0.5.3
	jupyterlab                4.2.1
	jupyterlab_pygments       0.3.0
	jupyterlab_server         2.27.2
	MarkupSafe                2.1.5
	matplotlib-inline         0.1.7
	mistune                   3.0.2
	nbclient                  0.10.0
	nbconvert                 7.16.4
	nbformat                  5.10.4
	nest_asyncio              1.6.0
	notebook_shim             0.2.4
	overrides                 7.7.0
	packaging                 24.0
	pandocfilters             1.5.0
	parso                     0.8.4
	pexpect                   4.9.0
	pickleshare               0.7.5
	pip                       24.0
	pkgutil_resolve_name      1.3.10
	platformdirs              4.2.2
	prometheus_client         0.20.0
	prompt-toolkit            3.0.42
	psutil                    5.9.8
	ptyprocess                0.7.0
	pure-eval                 0.2.2
	pycparser                 2.22
	Pygments                  2.18.0
	pyobjc-core               10.2
	pyobjc-framework-Cocoa    10.2
	PySocks                   1.7.1
	python-dateutil           2.9.0
	python-json-logger        2.0.7
	pytz                      2024.1
	PyYAML                    6.0.1
	pyzmq                     26.0.3
	referencing               0.35.1
	requests                  2.32.3
	rfc3339-validator         0.1.4
	rfc3986-validator         0.1.1
	rpds-py                   0.18.1
	Send2Trash                1.8.3
	setuptools                70.0.0
	six                       1.16.0
	sniffio                   1.3.1
	soupsieve                 2.5
	stack-data                0.6.2
	terminado                 0.18.1
	tinycss2                  1.3.0
	tomli                     2.0.1
	tornado                   6.4
	traitlets                 5.14.3
	types-python-dateutil     2.9.0.20240316
	typing_extensions         4.12.1
	typing-utils              0.1.0
	uri-template              1.3.0
	urllib3                   2.2.1
	wcwidth                   0.2.13
	webcolors                 1.13
	webencodings              0.5.1
	websocket-client          1.8.0
	wheel                     0.43.0
	zipp                      3.17.0

conda list:
	# packages in environment at $CONDA_PREFIX/envs/jupyter_dev:
	#
	# Name                    Version                   Build  Channel
	anyio                     4.3.0              pyhd8ed1ab_0    conda-forge
	appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
	argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
	argon2-cffi-bindings      21.2.0          py311heffc1b2_4    conda-forge
	arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
	asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
	async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
	attrs                     23.2.0             pyh71513ae_0    conda-forge
	babel                     2.14.0             pyhd8ed1ab_0    conda-forge
	beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
	bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
	brotli-python             1.1.0           py311ha891d26_1    conda-forge
	bzip2                     1.0.8                h93a5062_5    conda-forge
	ca-certificates           2024.6.2             hf0a4a13_0    conda-forge
	cached-property           1.5.2                hd8ed1ab_1    conda-forge
	cached_property           1.5.2              pyha770c72_1    conda-forge
	certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
	cffi                      1.16.0          py311h4a08483_0    conda-forge
	charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
	comm                      0.2.2              pyhd8ed1ab_0    conda-forge
	debugpy                   1.8.1           py311h92babd0_0    conda-forge
	decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
	defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
	entrypoints               0.4                pyhd8ed1ab_0    conda-forge
	exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
	executing                 2.0.1              pyhd8ed1ab_0    conda-forge
	fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
	h11                       0.14.0             pyhd8ed1ab_0    conda-forge
	h2                        4.1.0              pyhd8ed1ab_0    conda-forge
	hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
	httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
	httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
	hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
	idna                      3.7                pyhd8ed1ab_0    conda-forge
	importlib-metadata        7.1.0              pyha770c72_0    conda-forge
	importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
	importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
	ipykernel                 6.29.3             pyh3cd1d5f_0    conda-forge
	ipython                   8.25.0             pyh707e725_0    conda-forge
	isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
	jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
	jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
	json5                     0.9.25             pyhd8ed1ab_0    conda-forge
	jsonpointer               2.4             py311h267d04e_3    conda-forge
	jsonschema                4.22.0             pyhd8ed1ab_0    conda-forge
	jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
	jsonschema-with-format-nongpl 4.22.0             pyhd8ed1ab_0    conda-forge
	jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
	jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
	jupyter_core              5.7.2           py311h267d04e_0    conda-forge
	jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
	jupyter_server            2.14.1             pyhd8ed1ab_0    conda-forge
	jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
	jupyterlab                4.2.1              pyhd8ed1ab_0    conda-forge
	jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
	jupyterlab_server         2.27.2             pyhd8ed1ab_0    conda-forge
	libcxx                    17.0.6               h5f092b4_0    conda-forge
	libffi                    3.4.2                h3422bc3_5    conda-forge
	libsodium                 1.0.18               h27ca646_1    conda-forge
	libsqlite                 3.45.3               h091b4b1_0    conda-forge
	libzlib                   1.3.1                hfb2fe0b_1    conda-forge
	markupsafe                2.1.5           py311h05b510d_0    conda-forge
	matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
	mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
	nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
	nbconvert-core            7.16.4             pyhd8ed1ab_0    conda-forge
	nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
	ncurses                   6.5                  hb89a1cb_0    conda-forge
	nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
	notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
	openssl                   1.1.1w               h53f4e23_0    conda-forge
	overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
	packaging                 24.0               pyhd8ed1ab_0    conda-forge
	pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
	parso                     0.8.4              pyhd8ed1ab_0    conda-forge
	pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
	pickleshare               0.7.5                   py_1003    conda-forge
	pip                       24.0               pyhd8ed1ab_0    conda-forge
	pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
	platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
	prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
	prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
	psutil                    5.9.8           py311h05b510d_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
	pycparser                 2.22               pyhd8ed1ab_0    conda-forge
	pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
	pyobjc-core               10.2            py311h665608e_0    conda-forge
	pyobjc-framework-cocoa    10.2            py311h665608e_0    conda-forge
	pysocks                   1.7.1              pyha2e5f31_6    conda-forge
	python                    3.11.0          hf452327_1_cpython    conda-forge
	python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
	python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
	python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
	python_abi                3.11                    4_cp311    conda-forge
	pytz                      2024.1             pyhd8ed1ab_0    conda-forge
	pyyaml                    6.0.1           py311heffc1b2_1    conda-forge
	pyzmq                     26.0.3          py311h9bed540_0    conda-forge
	readline                  8.2                  h92ec313_1    conda-forge
	referencing               0.35.1             pyhd8ed1ab_0    conda-forge
	requests                  2.32.3             pyhd8ed1ab_0    conda-forge
	rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
	rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
	rpds-py                   0.18.1          py311h98c6a39_0    conda-forge
	send2trash                1.8.3              pyh31c8845_0    conda-forge
	setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
	soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
	stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
	terminado                 0.18.1             pyh31c8845_0    conda-forge
	tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
	tk                        8.6.13               h5083fa2_1    conda-forge
	tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
	tornado                   6.4             py311h05b510d_0    conda-forge
	traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
	types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
	typing-extensions         4.12.1               hd8ed1ab_0    conda-forge
	typing_extensions         4.12.1             pyha770c72_0    conda-forge
	typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
	tzdata                    2024a                h0c530f3_0    conda-forge
	uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
	urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
	wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
	webcolors                 1.13               pyhd8ed1ab_0    conda-forge
	webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
	websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
	wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
	xz                        5.2.6                h57fd34a_0    conda-forge
	yaml                      0.2.5                h3422bc3_2    conda-forge
	zeromq                    4.3.5                hebf3989_1    conda-forge
	zipp                      3.17.0             pyhd8ed1ab_0    conda-forge

conda env:
	name: jupyter_dev
	channels:
	  - conda-forge
	dependencies:
	  - anyio=4.3.0=pyhd8ed1ab_0
	  - appnope=0.1.4=pyhd8ed1ab_0
	  - argon2-cffi=23.1.0=pyhd8ed1ab_0
	  - argon2-cffi-bindings=21.2.0=py311heffc1b2_4
	  - arrow=1.3.0=pyhd8ed1ab_0
	  - asttokens=2.4.1=pyhd8ed1ab_0
	  - async-lru=2.0.4=pyhd8ed1ab_0
	  - attrs=23.2.0=pyh71513ae_0
	  - babel=2.14.0=pyhd8ed1ab_0
	  - beautifulsoup4=4.12.3=pyha770c72_0
	  - bleach=6.1.0=pyhd8ed1ab_0
	  - brotli-python=1.1.0=py311ha891d26_1
	  - bzip2=1.0.8=h93a5062_5
	  - ca-certificates=2024.6.2=hf0a4a13_0
	  - cached-property=1.5.2=hd8ed1ab_1
	  - cached_property=1.5.2=pyha770c72_1
	  - certifi=2024.2.2=pyhd8ed1ab_0
	  - cffi=1.16.0=py311h4a08483_0
	  - charset-normalizer=3.3.2=pyhd8ed1ab_0
	  - comm=0.2.2=pyhd8ed1ab_0
	  - debugpy=1.8.1=py311h92babd0_0
	  - decorator=5.1.1=pyhd8ed1ab_0
	  - defusedxml=0.7.1=pyhd8ed1ab_0
	  - entrypoints=0.4=pyhd8ed1ab_0
	  - exceptiongroup=1.2.0=pyhd8ed1ab_2
	  - executing=2.0.1=pyhd8ed1ab_0
	  - fqdn=1.5.1=pyhd8ed1ab_0
	  - h11=0.14.0=pyhd8ed1ab_0
	  - h2=4.1.0=pyhd8ed1ab_0
	  - hpack=4.0.0=pyh9f0ad1d_0
	  - httpcore=1.0.5=pyhd8ed1ab_0
	  - httpx=0.27.0=pyhd8ed1ab_0
	  - hyperframe=6.0.1=pyhd8ed1ab_0
	  - idna=3.7=pyhd8ed1ab_0
	  - importlib-metadata=7.1.0=pyha770c72_0
	  - importlib_metadata=7.1.0=hd8ed1ab_0
	  - importlib_resources=6.4.0=pyhd8ed1ab_0
	  - ipykernel=6.29.3=pyh3cd1d5f_0
	  - ipython=8.25.0=pyh707e725_0
	  - isoduration=20.11.0=pyhd8ed1ab_0
	  - jedi=0.19.1=pyhd8ed1ab_0
	  - jinja2=3.1.4=pyhd8ed1ab_0
	  - json5=0.9.25=pyhd8ed1ab_0
	  - jsonpointer=2.4=py311h267d04e_3
	  - jsonschema=4.22.0=pyhd8ed1ab_0
	  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
	  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
	  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
	  - jupyter_client=8.6.2=pyhd8ed1ab_0
	  - jupyter_core=5.7.2=py311h267d04e_0
	  - jupyter_events=0.10.0=pyhd8ed1ab_0
	  - jupyter_server=2.14.1=pyhd8ed1ab_0
	  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
	  - jupyterlab=4.2.1=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
	  - jupyterlab_server=2.27.2=pyhd8ed1ab_0
	  - libcxx=17.0.6=h5f092b4_0
	  - libffi=3.4.2=h3422bc3_5
	  - libsodium=1.0.18=h27ca646_1
	  - libsqlite=3.45.3=h091b4b1_0
	  - libzlib=1.3.1=hfb2fe0b_1
	  - markupsafe=2.1.5=py311h05b510d_0
	  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
	  - mistune=3.0.2=pyhd8ed1ab_0
	  - nbclient=0.10.0=pyhd8ed1ab_0
	  - nbconvert-core=7.16.4=pyhd8ed1ab_0
	  - nbformat=5.10.4=pyhd8ed1ab_0
	  - ncurses=6.5=hb89a1cb_0
	  - nest-asyncio=1.6.0=pyhd8ed1ab_0
	  - notebook-shim=0.2.4=pyhd8ed1ab_0
	  - openssl=1.1.1w=h53f4e23_0
	  - overrides=7.7.0=pyhd8ed1ab_0
	  - packaging=24.0=pyhd8ed1ab_0
	  - pandocfilters=1.5.0=pyhd8ed1ab_0
	  - parso=0.8.4=pyhd8ed1ab_0
	  - pexpect=4.9.0=pyhd8ed1ab_0
	  - pickleshare=0.7.5=py_1003
	  - pip=24.0=pyhd8ed1ab_0
	  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
	  - platformdirs=4.2.2=pyhd8ed1ab_0
	  - prometheus_client=0.20.0=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.42=pyha770c72_0
	  - psutil=5.9.8=py311h05b510d_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pure_eval=0.2.2=pyhd8ed1ab_0
	  - pycparser=2.22=pyhd8ed1ab_0
	  - pygments=2.18.0=pyhd8ed1ab_0
	  - pyobjc-core=10.2=py311h665608e_0
	  - pyobjc-framework-cocoa=10.2=py311h665608e_0
	  - pysocks=1.7.1=pyha2e5f31_6
	  - python=3.11.0=hf452327_1_cpython
	  - python-dateutil=2.9.0=pyhd8ed1ab_0
	  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
	  - python-json-logger=2.0.7=pyhd8ed1ab_0
	  - python_abi=3.11=4_cp311
	  - pytz=2024.1=pyhd8ed1ab_0
	  - pyyaml=6.0.1=py311heffc1b2_1
	  - pyzmq=26.0.3=py311h9bed540_0
	  - readline=8.2=h92ec313_1
	  - referencing=0.35.1=pyhd8ed1ab_0
	  - requests=2.32.3=pyhd8ed1ab_0
	  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
	  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
	  - rpds-py=0.18.1=py311h98c6a39_0
	  - send2trash=1.8.3=pyh31c8845_0
	  - setuptools=70.0.0=pyhd8ed1ab_0
	  - six=1.16.0=pyh6c4a22f_0
	  - sniffio=1.3.1=pyhd8ed1ab_0
	  - soupsieve=2.5=pyhd8ed1ab_1
	  - stack_data=0.6.2=pyhd8ed1ab_0
	  - terminado=0.18.1=pyh31c8845_0
	  - tinycss2=1.3.0=pyhd8ed1ab_0
	  - tk=8.6.13=h5083fa2_1
	  - tomli=2.0.1=pyhd8ed1ab_0
	  - tornado=6.4=py311h05b510d_0
	  - traitlets=5.14.3=pyhd8ed1ab_0
	  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
	  - typing-extensions=4.12.1=hd8ed1ab_0
	  - typing_extensions=4.12.1=pyha770c72_0
	  - typing_utils=0.1.0=pyhd8ed1ab_0
	  - tzdata=2024a=h0c530f3_0
	  - uri-template=1.3.0=pyhd8ed1ab_0
	  - urllib3=2.2.1=pyhd8ed1ab_0
	  - wcwidth=0.2.13=pyhd8ed1ab_0
	  - webcolors=1.13=pyhd8ed1ab_0
	  - webencodings=0.5.1=pyhd8ed1ab_2
	  - websocket-client=1.8.0=pyhd8ed1ab_0
	  - wheel=0.43.0=pyhd8ed1ab_1
	  - xz=5.2.6=h57fd34a_0
	  - yaml=0.2.5=h3422bc3_2
	  - zeromq=4.3.5=hebf3989_1
	  - zipp=3.17.0=pyhd8ed1ab_0
	prefix: $CONDA_PREFIX/envs/jupyter_dev
</pre>
</details>

<details><summary>Command Line Output</summary>
See attached file, reached comment limit.
[log.txt](https://github.com/user-attachments/files/15551442/log.txt)
</details>

<details><summary>Browser Output</summary>

<pre>
14:32:13.771 Language pack 'en_US' not installed! jlab_core.b630ccd1707fda60edd5.js:1:1580003
14:32:13.791 Deprecated shortcut selectors: "[data-jp-kernel-user]:focus" was replaced with "[data-jp-kernel-user]:not(.jp-mod-readWrite) :focus:not(:read-write)" in JupyterLab 4.1 (present in "[data-jp-kernel-user]:focus")
".jp-Notebook:focus" was replaced with ".jp-Notebook.jp-mod-commandMode:not(.jp-mod-readWrite) :focus" in JupyterLab 4.1 (present in ".jp-Notebook:focus")
".jp-Notebook:focus.jp-mod-commandMode" was replaced with ".jp-Notebook.jp-mod-commandMode:not(.jp-mod-readWrite) :focus" in JupyterLab 4.1 (present in ".jp-Notebook:focus.jp-mod-commandMode")

The selectors will be substituted transparently this time, but need to be updated at source before next major release. jlab_core.b630ccd1707fda60edd5.js:1:1486316
14:32:13.791 Starting application in workspace: "default" jlab_core.b630ccd1707fda60edd5.js:1:8982
14:32:14.153 SyntaxError: JSON.parse: unexpected keyword at line 1 column 1 of the JSON data jlab_core.b630ccd1707fda60edd5.js:1:1401874
14:32:14.153 Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
14:32:15.137 Not a JSON response body. 
Response { type: "basic", url: "https://localhost:8888/lab/api/extensions?query&page=1&per_page=30&refresh=0&1717504335124", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(8), body: ReadableStream, bodyUsed: true }
jlab_core.b630ccd1707fda60edd5.js:1:711292
14:32:16.855 Starting WebSocket: wss://localhost:8888/api/kernels/191987bf-3e84-4cdf-a8f1-7bc79d8ff815 3 jlab_core.b630ccd1707fda60edd5.js:1:1357161
</pre>
</details>

**Comment by krassowski** [comment]
Cross-referencing https://github.com/jupyterlab/jupyterlab/issues/9283

**Comment by miraculixx** [comment]
I just noticed this - for what it's worth, here are my 5 cents:

This seems to be new behavior. I have used jupyter lab for years and never seen a cell being scrolled to the top upon ctrl/cmd+enter. The problem with this new behavior is that it hides the output, and one has to scroll down manually again.

**Comment by imyhxy** [comment]
It's annoyed when a cell is long, and the user have to scroll to the bottom again and again.
