### ISSUE TITLE
Comment on pull request workflow is failing (`benchmark-report.yml`)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16558]
```
Run actions/github-script@v7
  with:
    script: var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
     owner: context.repo.owner,
     repo: context.repo.repo,
     run_id: 9842740167,
  });
  var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
    return artifact.name == "benchmark-assets"
  })[0];
  var download = await github.rest.actions.downloadArtifact({
     owner: context.repo.owner,
     repo: context.repo.repo,
     artifact_id: matchArtifact.id,
     archive_format: 'zip',
  });
  var fs = require('fs');
  fs.writeFileSync('/home/runner/work/jupyterlab/jupyterlab/benchmark-assets.zip', Buffer.from(download.data));
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,40[3](https://github.com/jupyterlab/jupyterlab/actions/runs/9842741235/job/27172343788#step:2:3),404,422
TypeError: Cannot read properties of undefined (reading 'id')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:14:31)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'id')
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:20)
```

https://github.com/jupyterlab/jupyterlab/blob/16887de003e0f7d1f45713370731aafa7047aa99/.github/workflows/benchmark-report.yml

**Comment by krassowski** [comment]
I think we may need `github.event.workflow_run.conclusion == 'success'` back
