### ISSUE TITLE
Disabling / Enabling a single extension via `ServerApp.jpserver_extensions`  in `jupyter_server_config.json` causes "KeyError: 'jupyterhub-singleuser'"

### ISSUE THREAD

**Issue by frittentheke** [jupyterlab/jupyterlab#16596]
## Description

I wanted to disable the classic notebook extension, so I set it to false in `jupyter_server_config.json`:

```
{
  "ServerApp": {
    "jpserver_extensions": {
        "nbclassic": False"
     }
  }
}
```

I mounted this file to `/etc/jupyter/jupyter_server_config.json` and started the container, no errors were logged the the installed extensions worked as expected:

```
Entered start.sh with args: start-notebook.py
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: start-notebook.py
Executing: jupyter lab
[I 2024-07-17 12:51:16.969 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-07-17 12:51:16.971 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-07-17 12:51:16.971 ServerApp] jupyterfs.extension | extension was successfully linked.
[I 2024-07-17 12:51:16.973 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-07-17 12:51:16.975 ServerApp] notebook | extension was successfully linked.
[I 2024-07-17 12:51:16.976 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-07-17 12:51:17.222 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-07-17 12:51:17.246 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-07-17 12:51:17.248 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-07-17 12:51:17.248 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-07-17 12:51:17.248 ServerApp] Installing jupyter-fs resources handler on path /jupyterfs/resources
[I 2024-07-17 12:51:17.248 ServerApp] jupyterfs.extension | extension was successfully loaded.
[I 2024-07-17 12:51:17.251 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2024-07-17 12:51:17.251 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2024-07-17 12:51:17.251 LabApp] Extension Manager is 'pypi'.
[I 2024-07-17 12:51:17.259 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-07-17 12:51:17.262 ServerApp] notebook | extension was successfully loaded.
[I 2024-07-17 12:51:17.262 ServerApp] Serving contents
[I 2024-07-17 12:51:17.262 ServerApp] Jupyter Server 2.14.1 is running at:
[I 2024-07-17 12:51:17.262 ServerApp] http://c0f1de1a6836:8888/lab?token=406aa3f9217542edad2034b0955a063de305a0c77b9b1f7d
[I 2024-07-17 12:51:17.262 ServerApp]     http://127.0.0.1:8888/lab?token=406aa3f9217542edad2034b0955a063de305a0c77b9b1f7d
[I 2024-07-17 12:51:17.262 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-07-17 12:51:17.265 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-2-open.html
    Or copy and paste one of these URLs:
        http://c0f1de1a6836:8888/lab?token=406aa3f9217542edad2034b0955a063de305a0c77b9b1f7d
        http://127.0.0.1:8888/lab?token=406aa3f9217542edad2034b0955a063de305a0c77b9b1f7d

```

When moving this configuration to be launched via JupyterHub and starting the container as a singleuser instance of JupyterLab

```
Entered start.sh with args: start-notebook.py
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: start-notebook.py
WARNING: using start-singleuser.py instead of start-notebook.py to start a server associated with JupyterHub.
Executing: jupyterhub-singleuser --ip=0.0.0.0
[I 2024-07-17 11:24:43.100 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-07-17 11:24:43.100 ServerApp] jupyter_resource_usage | extension was successfully linked.
[I 2024-07-17 11:24:43.102 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-07-17 11:24:43.104 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-07-17 11:24:43.104 ServerApp] jupyterfs.extension | extension was successfully linked.
[I 2024-07-17 11:24:43.106 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-07-17 11:24:43.106 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-07-17 11:24:43.106 ServerApp] nbdime | extension was successfully linked.
[I 2024-07-17 11:24:43.108 ServerApp] notebook | extension was successfully linked.
[I 2024-07-17 11:24:43.110 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-07-17 11:24:43.360 ServerApp] notebook_shim | extension was successfully linked.
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 616, in launch_instance
    serverapp = cls.initialize_server(argv=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 586, in initialize_server
    serverapp.initialize(
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 2745, in initialize
    point = self.extension_manager.extension_points[starter_extension]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'jupyterhub-singleuser'
 ```

## Reproduce

see above

## Expected behavior
I expected to be able to disable / enable individual extensions with no distinction if the JupyterLab is launched standalone or via a JupyterHub.

## Context
- JupyterLab version: 4.2.3

**Comment by JasonWeill** [comment]
@frittentheke Thank you for your contribution! It looks like this may also represent an issue in JupyterHub. Please consider opening [an issue in JupyterHub](https://github.com/jupyterhub/jupyterhub/issues), and including a URL for this issue in the description, so that the two issues are related to each other. I appreciate your report!

**Comment by frittentheke** [comment]
> @frittentheke Thank you for your contribution! It looks like this may also represent an issue in JupyterHub. Please consider opening [an issue in JupyterHub](https://github.com/jupyterhub/jupyterhub/issues), and including a URL for this issue in the description, so that the two issues are related to each other. I appreciate your report!

Thanks for getting back to me @JasonWeill  ... I gladly raise another issue with Jupyterhub. 
But does this really help since I was already able to reproduce this with "just" a single JupyterLab instance? All JupyterHub does in this case is to (kube)spawn a JupyterLab Pod with all sorts of env vars, mounted ConfigMaps, ... and one of which is my statically configured file `jupyter_server_config.json`, just like with the standalone Lab. So the hub does nothing but to hand this piece of config as is into the Lab instance....

**Comment by krassowski** [comment]
Closing in favour of https://github.com/jupyterhub/jupyterhub/issues/4859.

On triage I misread the traceback, there is nothing to be done in jupyterlab here.
