### ISSUE TITLE
Uncaught error in cell toolbar tracker when loading JupyterLab

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16667]
## Description

When loading jupyterlab an error shows up in console:

```
celltoolbartracker.ts:552 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'enabled')
    at set enabled (celltoolbartracker.ts:552:26)
    at loadSetting (index.ts:46:24)
    at index.ts:68:11
```

## Reproduce

Build an launch from `main`

## Expected behavior

No error

## Context

- JupyterLab version: 4.3.0b0

**Comment by JasonWeill** [comment]
This is probably caused by #16637.   

The WIP PR #16602 includes some additional null checks to prevent errors. This might be a good place to fix this issue as well.

**Comment by JasonWeill** [comment]
In Firefox 129.0.1, I don't see the error @krassowski notes above, but I do see two other errors, which each produce an error on the same source code line:

## Message 1

<details>

```
Uncaught TypeError: activeCell.model is null
    _cellToolbarOverlapsContents celltoolbartracker.ts:321
    _updateCellForToolbarOverlap celltoolbartracker.ts:312
    requestIdleCallback handler*_updateCellForToolbarOverlap celltoolbartracker.ts:308
    _addToolbar celltoolbartracker.ts:242
    promise callback*_addToolbar celltoolbartracker.ts:221
    _onToolbarChanged celltoolbartracker.ts:280
    set enabled celltoolbartracker.ts:168
    set enabled celltoolbartracker.ts:552
    loadSetting index.ts:46
    activate index.ts:68
    promise callback*activate index.ts:65
    node_modules jlab_core.2dc73ca677e1929b265d.js:4444
    promise callback*activatePlugin index.es6.js:1851
    node_modules jlab_core.2dc73ca677e1929b265d.js:4608
    start index.es6.js:2014
    main index.out.js:723
    bootstrap bootstrap.js:96
    js bootstrap.js:97
    Webpack 3
        __webpack_require__
        <anonymous>
        <anonymous>
celltoolbartracker.ts:321:21
```

</details>

## Message 2

<details>

```
Uncaught TypeError: activeCell.model is null
    _cellToolbarOverlapsContents celltoolbartracker.ts:321
    _updateCellForToolbarOverlap celltoolbartracker.ts:312
    requestIdleCallback handler*_updateCellForToolbarOverlap celltoolbartracker.ts:308
    _resizeEventCallback celltoolbartracker.ts:299
    invokeSlot index.es6.js:555
    emit index.es6.js:513
    emit index.es6.js:112
    _resizeDebouncer widget.ts:767
    factory index.es6.js:442
    _execute index.es6.js:263
    execute index.es6.js:201
    setTimeout handler*schedule index.es6.js:204
    invoke index.es6.js:504
    onResize widget.ts:675
    processMessage index.es6.js:1202
    invokeHandler index.es6.js:412
    sendMessage index.es6.js:166
    onResize index.es6.js:1912
    processParentMessage index.es6.js:1836
    notifyLayout index.es6.js:1285
    processMessage index.es6.js:1201
    invokeHandler index.es6.js:412
    sendMessage index.es6.js:166
    update index.es6.js:2389
    _update index.es6.js:4842
    onUpdateRequest index.es6.js:4671
    processParentMessage index.es6.js:1839
    notifyLayout index.es6.js:1285
    processMessage index.es6.js:1205
    invokeHandler index.es6.js:412
    sendMessage index.es6.js:175
    runMessageLoop index.es6.js:463
    flush index.es6.js:328
    restoreLayout shell.ts:1274
    activate index.tsx:870
    promise callback*activate index.tsx:864
    node_modules jlab_core.2dc73ca677e1929b265d.js:4444
    promise callback*activatePlugin index.es6.js:1851
    resolveOptionalService index.es6.js:1971
    node_modules jlab_core.2dc73ca677e1929b265d.js:4441
    activatePlugin index.es6.js:1848
    node_modules jlab_core.2dc73ca677e1929b265d.js:4608
    start index.es6.js:2014
    main index.out.js:723
    bootstrap bootstrap.js:96
    js bootstrap.js:97
    Webpack 3
celltoolbartracker.ts:321:21
```

</details>
