### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by rongliangtang** [jupyterlab/jupyterlab#16685]
## Description

I compiled jupyterlab on docker and reported an error

## Reproduce

linux
python 3.12
node 22

## Expected behavior

success

## Context

root@886f618ece6a:/srv/jupyterhub/jupyterlab# pip install -v -e .
Using pip 24.2 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)
Obtaining file:///srv/jupyterhub/jupyterlab
  Running command pip subprocess to install build dependencies
  Using pip 24.2 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)
  Collecting hatchling>=1.21.1
    Obtaining dependency information for hatchling>=1.21.1 from https://files.pythonhosted.org/packages/0c/8b/90e80904fdc24ce33f6fc6f35ebd2232fe731a8528a22008458cf197bc4d/hatchling-1.25.0-py3-none-any.whl.metadata
    Using cached hatchling-1.25.0-py3-none-any.whl.metadata (3.8 kB)
  Collecting packaging>=23.2 (from hatchling>=1.21.1)
    Obtaining dependency information for packaging>=23.2 from https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl.metadata
    Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
  Collecting pathspec>=0.10.1 (from hatchling>=1.21.1)
    Obtaining dependency information for pathspec>=0.10.1 from https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl.metadata
    Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
  Collecting pluggy>=1.0.0 (from hatchling>=1.21.1)
    Obtaining dependency information for pluggy>=1.0.0 from https://files.pythonhosted.org/packages/88/5f/e351af9a41f866ac3f1fac4ca0613908d9a41741cfcf2228f4ad853b697d/pluggy-1.5.0-py3-none-any.whl.metadata
    Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
  Collecting trove-classifiers (from hatchling>=1.21.1)
    Obtaining dependency information for trove-classifiers from https://files.pythonhosted.org/packages/0f/b0/09794439a62a7dc18bffdbf145aaf50297fd994890b11da27a13e376b947/trove_classifiers-2024.7.2-py3-none-any.whl.metadata
    Using cached trove_classifiers-2024.7.2-py3-none-any.whl.metadata (2.2 kB)
  Using cached hatchling-1.25.0-py3-none-any.whl (84 kB)
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
  Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
  Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
  Using cached trove_classifiers-2024.7.2-py3-none-any.whl (13 kB)
  Installing collected packages: trove-classifiers, pluggy, pathspec, packaging, hatchling
    Creating /tmp/pip-build-env-lxgs3t31/overlay/bin
    changing mode of /tmp/pip-build-env-lxgs3t31/overlay/bin/hatchling to 755
  Successfully installed hatchling-1.25.0 packaging-24.1 pathspec-0.12.1 pluggy-1.5.0 trove-classifiers-2024.7.2
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  Getting requirements to build editable ... done
  Running command pip subprocess to install backend dependencies
  Using pip 24.2 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)
  Collecting hatch-jupyter-builder>=0.3.2
    Obtaining dependency information for hatch-jupyter-builder>=0.3.2 from https://files.pythonhosted.org/packages/9f/ce/be681f7af8141eabe61df05c7990db3bafe0ea9e2d7cec9329fad75a00e4/hatch_jupyter_builder-0.9.1-py3-none-any.whl.metadata
    Using cached hatch_jupyter_builder-0.9.1-py3-none-any.whl.metadata (5.4 kB)
  Collecting editables~=0.3
    Obtaining dependency information for editables~=0.3 from https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl.metadata
    Using cached editables-0.5-py3-none-any.whl.metadata (3.1 kB)
  Collecting hatchling>=1.17 (from hatch-jupyter-builder>=0.3.2)
    Obtaining dependency information for hatchling>=1.17 from https://files.pythonhosted.org/packages/0c/8b/90e80904fdc24ce33f6fc6f35ebd2232fe731a8528a22008458cf197bc4d/hatchling-1.25.0-py3-none-any.whl.metadata
    Using cached hatchling-1.25.0-py3-none-any.whl.metadata (3.8 kB)
  Collecting packaging>=23.2 (from hatchling>=1.17->hatch-jupyter-builder>=0.3.2)
    Obtaining dependency information for packaging>=23.2 from https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl.metadata
    Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
  Collecting pathspec>=0.10.1 (from hatchling>=1.17->hatch-jupyter-builder>=0.3.2)
    Obtaining dependency information for pathspec>=0.10.1 from https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl.metadata
    Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
  Collecting pluggy>=1.0.0 (from hatchling>=1.17->hatch-jupyter-builder>=0.3.2)
    Obtaining dependency information for pluggy>=1.0.0 from https://files.pythonhosted.org/packages/88/5f/e351af9a41f866ac3f1fac4ca0613908d9a41741cfcf2228f4ad853b697d/pluggy-1.5.0-py3-none-any.whl.metadata
    Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
  Collecting trove-classifiers (from hatchling>=1.17->hatch-jupyter-builder>=0.3.2)
    Obtaining dependency information for trove-classifiers from https://files.pythonhosted.org/packages/0f/b0/09794439a62a7dc18bffdbf145aaf50297fd994890b11da27a13e376b947/trove_classifiers-2024.7.2-py3-none-any.whl.metadata
    Using cached trove_classifiers-2024.7.2-py3-none-any.whl.metadata (2.2 kB)
  Using cached hatch_jupyter_builder-0.9.1-py3-none-any.whl (18 kB)
  Using cached editables-0.5-py3-none-any.whl (5.1 kB)
  Using cached hatchling-1.25.0-py3-none-any.whl (84 kB)
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
  Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
  Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
  Using cached trove_classifiers-2024.7.2-py3-none-any.whl (13 kB)
  Installing collected packages: trove-classifiers, pluggy, pathspec, packaging, editables, hatchling, hatch-jupyter-builder
    Creating /tmp/pip-build-env-lxgs3t31/normal/bin
    changing mode of /tmp/pip-build-env-lxgs3t31/normal/bin/hatchling to 755
    changing mode of /tmp/pip-build-env-lxgs3t31/normal/bin/hatch-jupyter-builder to 755
  Successfully installed editables-0.5 hatch-jupyter-builder-0.9.1 hatchling-1.25.0 packaging-24.1 pathspec-0.12.1 pluggy-1.5.0 trove-classifiers-2024.7.2
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
  Installing backend dependencies ... done
  Running command Preparing editable metadata (pyproject.toml)
  INFO:hatch_jupyter_builder.utils:Running jupyter-builder
  INFO:hatch_jupyter_builder.utils:Writing pre-commit hook
  INFO:hatch_jupyter_builder.utils:Building with buildapi.builder
  INFO:hatch_jupyter_builder.utils:With kwargs: {'build_cmd': 'build', 'source_dir': 'packages', 'build_dir': 'dev_mode/static', 'npm': ['node', 'jupyterlab/staging/yarn.js']}
  INFO:hatch_jupyter_builder.utils:Installing build dependencies with npm.  This may take a while...
  INFO:hatch_jupyter_builder.utils:> /root/.nvm/versions/node/v22.6.0/bin/node jupyterlab/staging/yarn.js install
  ➤ YN0000: ┌ Project validation
  ➤ YN0057: │ @jupyterlab/application-top: Resolutions field will be ignored
  ➤ YN0057: │ @jupyterlab/example-federated-core: Resolutions field will be ignored
  ➤ YN0000: └ Completed
  ➤ YN0000: ┌ Resolution step
  ➤ YN0002: │ @jupyterlab/cell-toolbar-extension@workspace:packages/cell-toolbar-extension doesn't provide react (p9b3fb), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/completer@workspace:packages/completer doesn't provide react (pb6629), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/console-extension@workspace:packages/console-extension doesn't provide react (p43f42), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/csvviewer-extension@workspace:packages/csvviewer-extension doesn't provide react (pc0654), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/debugger-extension@workspace:packages/debugger-extension doesn't provide react (p03594), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/documentsearch-extension@workspace:packages/documentsearch-extension doesn't provide react (p625eb), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/extensionmanager-extension@workspace:packages/extensionmanager-extension doesn't provide react (pf4c35), requested by @jupyterlab/settingregistry
  ➤ YN0060: │ @jupyterlab/extensionmanager@workspace:packages/extensionmanager provides react (pc6bfe) with version 18.2.0, which doesn't satisfy what react-paginate requests
  ➤ YN0002: │ @jupyterlab/filebrowser-extension@workspace:packages/filebrowser-extension doesn't provide react (p297ab), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/fileeditor-extension@workspace:packages/fileeditor-extension doesn't provide react (p034cc), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/galata-extension@workspace:galata/extension doesn't provide react (p94674), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/galata@workspace:galata doesn't provide react (pf71ca), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/htmlviewer-extension@workspace:packages/htmlviewer-extension doesn't provide react (p251e4), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/mainmenu-extension@workspace:packages/mainmenu-extension doesn't provide react (pe6ae9), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/markdownviewer-extension@workspace:packages/markdownviewer-extension doesn't provide react (p3482b), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/metadataform-extension@workspace:packages/metadataform-extension doesn't provide react (p7f08d), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/metadataform@workspace:packages/metadataform doesn't provide @rjsf/utils (p26354), requested by @rjsf/core
  ➤ YN0002: │ @jupyterlab/metadataform@workspace:packages/metadataform doesn't provide @rjsf/utils (p4b312), requested by @rjsf/validator-ajv8
  ➤ YN0002: │ @jupyterlab/metapackage@workspace:packages/metapackage doesn't provide react (pc1a66), requested by @jupyterlab/settingregistry
  ➤ YN0060: │ @jupyterlab/repo-top@workspace:. provides stylelint (pb09b9) with version 15.10.1, which doesn't satisfy what stylelint-config-prettier requests
  ➤ YN0002: │ @jupyterlab/repo-top@workspace:. doesn't provide typescript (p38c70), requested by typedoc
  ➤ YN0002: │ @jupyterlab/services@workspace:packages/services doesn't provide react (p3d5c2), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/settingeditor-extension@workspace:packages/settingeditor-extension doesn't provide react (p1bbc0), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/statusbar-extension@workspace:packages/statusbar-extension doesn't provide react (pba42f), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/terminal-extension@workspace:packages/terminal-extension doesn't provide react (p7805a), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/toc-extension@workspace:packages/toc-extension doesn't provide react (p336fb), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @jupyterlab/translation-extension@workspace:packages/translation-extension doesn't provide react (p854cf), requested by @jupyterlab/settingregistry
  ➤ YN0002: │ @nrwl/devkit@npm:16.5.2 doesn't provide nx (p83c1a), requested by @nx/devkit
  ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
  ➤ YN0000: └ Completed
  ➤ YN0000: ┌ Fetch step
  ➤ YN0066: │ typescript@patch:typescript@npm%3A5.1.6#~builtin<compat/typescript>::version=5.1.6&hash=85af82: Cannot apply hunk #1
  ➤ YN0000: └ Completed in 32s 65ms
  ➤ YN0000: ┌ Link step
  ➤ YN0009: │ @parcel/watcher@npm:2.0.4 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-af3c7c56/build.log)
  ➤ YN0000: └ Completed in 40s 95ms
  ➤ YN0000: Failed with errors in 1m 13s
  Traceback (most recent call last):
    File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
      hook = backend.prepare_metadata_for_build_editable
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 176, in prepare_metadata_for_build_editable
      whl_basename = build_hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-lxgs3t31/overlay/lib/python3.12/site-packages/hatchling/build.py", line 83, in build_editable
      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-lxgs3t31/overlay/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
      build_hook.initialize(version, build_data)
    File "/tmp/pip-build-env-lxgs3t31/normal/lib/python3.12/site-packages/hatch_jupyter_builder/plugin.py", line 94, in initialize
      raise e
    File "/tmp/pip-build-env-lxgs3t31/normal/lib/python3.12/site-packages/hatch_jupyter_builder/plugin.py", line 89, in initialize
      build_func(self.target_name, version, **build_kwargs)
    File "/srv/jupyterhub/jupyterlab/buildapi.py", line 20, in builder
      npm_builder(target_name, version, *args, **kwargs)
    File "/tmp/pip-build-env-lxgs3t31/normal/lib/python3.12/site-packages/hatch_jupyter_builder/utils.py", line 115, in npm_builder
      run([*npm_cmd, "install"], cwd=str(abs_path))
    File "/tmp/pip-build-env-lxgs3t31/normal/lib/python3.12/site-packages/hatch_jupyter_builder/utils.py", line 231, in run
      return subprocess.check_call(cmd, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/root/.nvm/versions/node/v22.6.0/bin/node', 'jupyterlab/staging/yarn.js', 'install']' returned non-zero exit status 1.
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/bin/python /usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmp_yglznku
  cwd: /srv/jupyterhub/jupyterlab
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
root@886f618ece6a:/srv/jupyterhub/jupyterlab# jupyter lab clean
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir] [--paths] [--json] [--debug] [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: dejavu events execute kernel kernelspec migrate nbconvert run server troubleshoot trust

Jupyter command `jupyter-lab` not found.
root@886f618ece6a:/srv/jupyterhub/jupyterlab#

**Comment by krassowski** [comment]
Building against Node 22 may be not supported yet. JupyterLab repository includes a `Dockerfile` which specifies node 20.1:

https://github.com/jupyterlab/jupyterlab/blob/3d925e3a6cb2c5a3c1c4267406cad785e6fa2542/docker/Dockerfile#L33-L35

And the contributor docs:

https://github.com/jupyterlab/jupyterlab/blob/3d925e3a6cb2c5a3c1c4267406cad785e6fa2542/docs/source/developer/contributing.rst?plain=1#L332

We should definitely make sure that compilation on Node 22 works as Node 20 is approaching end of "Current" lifecycle. The issue that you are seeing is related to yarn berry patch failing, likely due to different Node version.

That said, the Dockerfile in this repo may have some issues too: https://github.com/jupyterlab/jupyterlab/issues/16379

**Comment by JasonWeill** [comment]
This may be Docker-specific. On macOS Sonoma 14.6.1 (23G93), with Node v22.6.0 and Python 3.12.5 installed, I was able to compile and run JupyterLab from source using code at the tip of `main`.

**Comment by Rishab87** [comment]
@krassowski is this issue resolved because I was trying to reproduce it locally and docker file built without any errors even after changing nodejs version to 22.6.0 inside docker file.

```Dockerfile
RUN --mount=type=cache,target=/jupyterlab/conda-cache,uid=${NEW_MAMBA_USER_ID},gid=${NEW_MAMBA_USER_GID} \
    CONDA_PKGS_DIRS="/jupyterlab/conda-cache" micromamba install -c nodefaults -c conda-forge -yn base nodejs=22.6.0 yarn=3 git python=3
```

![Screenshot From 2025-01-12 11-23-25](https://github.com/user-attachments/assets/386c16d1-83fd-40c4-8eee-45028f2a5d65)

**Comment by krassowski** [comment]
Closing per multiple reports that this is now working, thanks.
