### ISSUE TITLE
Failing examples check on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#16772]
The `examples` check seems to be failing consistently on CI. For example:
- https://github.com/jupyterlab/jupyterlab/actions/runs/10801167759/job/29961047173?pr=16770
- https://github.com/jupyterlab/jupyterlab/actions/runs/10801370571/job/29961399584?pr=16771

```
Running 1 test using 1 worker
Navigating to page: file:///home/runner/.local/share/jupyter/runtime/jpserver-6198-open.html
[I 2024-09-10 22:11:25.705 ServerApp] Kernel started: fe8f9dba-02a0-45dc-b4b7-eb7570217e60
debug >> Starting WebSocket: ws://localhost:8888/foo/api/kernels/fe8f9dba-02a0-45dc-b4b7-eb7570217e60
[I 2024-09-10 22:11:26.194 ServerApp] Connecting to kernel fe8f9dba-02a0-45dc-b4b7-eb7570217e60.
debug >> Test complete!
[I 2024-09-10 22:11:26.306 ServerApp] Starting buffering for fe8f9dba-02a0-45dc-b4b7-eb7570217e60:58ca4dc7-03a1-4f9c-9ff3-e9f5e8c8455a
·
  1 passed (2.5s)
[I 2024-09-10 22:11:26.384 ServerApp] Test Complete
[I 2024-09-10 22:11:26.384 ServerApp] Exiting normally
[I 2024-09-10 22:11:26.384 ServerApp] Stopping server...
Traceback (most recent call last):
  File "/home/runner/work/jupyterlab/jupyterlab/examples/test_examples.py", line 71, in <module>
    main()
  File "/home/runner/work/jupyterlab/jupyterlab/examples/test_examples.py", line 65, in main
    raise AssertionError(msg)
AssertionError: The following examples failed:
-/home/runner/work/jupyterlab/jupyterlab/examples/app
-/home/runner/work/jupyterlab/jupyterlab/examples/federated
-/home/runner/work/jupyterlab/jupyterlab/examples/filebrowser
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
Error: Process completed with exit code 1.
```

![image](https://github.com/user-attachments/assets/7b94d187-abb6-4cb9-bf0e-337fa63c250c)

**Comment by jtpio** [comment]
> I think we will fix this with #16765 or #16751 (whichever we decide to go with).

Should we still wait for one of these two PRs? Or could it be worth fixing the tests now so other PRs can have their CI pass fully and be merged in the meantime?

**Comment by krassowski** [comment]
I think we can update the snapshots separately for now :)

**Comment by jtpio** [comment]
OK, just opened https://github.com/jupyterlab/jupyterlab/pull/16816 to (hopefully) fix it.
