### ISSUE TITLE
Improve Error Messaging for Proxy and SSL Configuration Issues in JupyterLab

### ISSUE THREAD

**Issue by felixmondelo** [jupyterlab/jupyterlab#16773]
## Description

Click on Extension Manager it gives me error "Error searching for extensions: Error: Unhandled error."

## Reproduce

1. Go to JupyterLab 
2. Click on 'Extensions Manager'
3. Search for any key on PyPi Manager

![image](https://github.com/user-attachments/assets/00fac1a5-24f2-4338-947e-cc23b6a4162a)

4. See error 'Error searching for extensions: Error: Unhandled error.'

The error in my command line was

```
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]: [E 2024-09-10 15:38:23.269 ServerApp] Uncaught exception GET /user/user/lab/api/extensions?query&page=1&per_page=30&refresh=0&1725978991214 (::ffff:XX.XX.XX.XX)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:     HTTPServerRequest(protocol='https', host='XX.XXX.X.XXX:7443', method='GET', uri='/user/user/lab/api/extensions?query&page=1&per_page=30&refresh=0&1725978991214', version='HT>
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:     Traceback (most recent call last):
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib64/python3.12/site-packages/tornado/web.py", line 1790, in _execute
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         result = await result
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                  ^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         extensions, last_page = await self.manager.list_extensions(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 474, in list_extensions
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         await self.refresh(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 508, in refresh
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         await self._update_extensions_list(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 681, in _update_extensions_list
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         extensions, last_page = await self.list_packages(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 261, in list_packages
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         matches = await self.__get_all_extensions()
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 315, in __get_all_extensions
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.__all_packages_cache = await self.__throttleRequest(
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 214, in __throttleRequest
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         data = await current_loop.run_in_executor(None, fn, *args)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 58, in run
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         result = self.fn(*self.args, **self.kwargs)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1122, in __call__
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         return self.__send(self.__name, args)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1461, in __request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         response = self.__transport.request(
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1166, in request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         return self.single_request(host, handler, request_body, verbose)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1178, in single_request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         http_conn = self.send_request(host, handler, request_body, verbose)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1291, in send_request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.send_content(connection, request_body)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1321, in send_content
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         connection.endheaders(request_body)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1331, in endheaders
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self._send_output(message_body, encode_chunked=encode_chunked)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1091, in _send_output
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.send(msg)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1035, in send
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.connect()
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1470, in connect
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         super().connect()
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1001, in connect
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.sock = self._create_connection(
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                     ^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/socket.py", line 852, in create_connection
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         raise exceptions[0]
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/socket.py", line 837, in create_connection
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         sock.connect(sa)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:     OSError: [Errno 101] Network is unreachable
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]: [W 2024-09-10 15:38:23.272 ServerApp] wrote error: 'Unhandled error'
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:     Traceback (most recent call last):
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib64/python3.12/site-packages/tornado/web.py", line 1790, in _execute
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         result = await result
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                  ^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         extensions, last_page = await self.manager.list_extensions(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 474, in list_extensions
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         await self.refresh(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 508, in refresh
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         await self._update_extensions_list(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 681, in _update_extensions_list
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         extensions, last_page = await self.list_packages(query, page, per_page)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 261, in list_packages
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         matches = await self.__get_all_extensions()
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 315, in __get_all_extensions
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.__all_packages_cache = await self.__throttleRequest(
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/local/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 214, in __throttleRequest
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         data = await current_loop.run_in_executor(None, fn, *args)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 58, in run
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         result = self.fn(*self.args, **self.kwargs)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1122, in __call__
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         return self.__send(self.__name, args)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1461, in __request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         response = self.__transport.request(
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1166, in request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         return self.single_request(host, handler, request_body, verbose)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1178, in single_request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         http_conn = self.send_request(host, handler, request_body, verbose)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1291, in send_request
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.send_content(connection, request_body)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/xmlrpc/client.py", line 1321, in send_content
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         connection.endheaders(request_body)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1331, in endheaders
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self._send_output(message_body, encode_chunked=encode_chunked)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1091, in _send_output
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.send(msg)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1035, in send
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.connect()
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1470, in connect
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1470, in connect
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         super().connect()
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/http/client.py", line 1001, in connect
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         self.sock = self._create_connection(
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:                     ^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/socket.py", line 852, in create_connection
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         raise exceptions[0]
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       File "/usr/lib64/python3.12/socket.py", line 837, in create_connection
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:         sock.connect(sa)
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:     OSError: [Errno 101] Network is unreachable
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]: [E 2024-09-10 15:38:23.273 ServerApp] {
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "X-Forwarded-Host": "XX.XXX.X.XXX:7443",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "X-Forwarded-Proto": "https",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "X-Forwarded-Port": "7443",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "X-Forwarded-For": "::ffff:XX.XX.XX.XX",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Cookie": "jupyterhub-user-**user**=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Accept-Language": "en-US,en;q=0.9",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Accept-Encoding": "gzip, deflate, br, zstd",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Referer": "https://XX.XXX.X.XXX:7443/user/user/lab/workspaces/auto-q?reset",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Sec-Fetch-Dest": "empty",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Sec-Fetch-Mode": "cors",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Sec-Fetch-Site": "same-origin",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Accept": "*/*",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Content-Type": "application/json",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Authorization": "token [secret]",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Sec-Ch-Ua-Mobile": "?0",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "X-Xsrftoken": "MnwxOjB8MTA6MTcyNTk3OTA4N3w1Ol94c3JmfDEzMjpaV0kxTmpRMlpURmhOelZrTkRSaFltRmtZMlV4Tm1JNU9UVTRaVEpsWmpJNk9EVTVNemxsWm1VMlkyWm1NVEUwWkRJMFlqUmlOekV6T0dGbVlXTm>
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Sec-Ch-Ua-Platform": "\"Windows\"",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Sec-Ch-Ua": "\"Not)A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"127\", \"Chromium\";v=\"127\"",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Connection": "close",
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:       "Host": "XX.XXX.X.XXX:7443"
Sep 10 15:38:23 Dev-calculations-machine jupyterhub[35812]:     }
```

## Expected behavior

See the available extensions.

## Context

- Operating System and version: Linux RHEL 8.10
- Browser and version: Chrome
- JupyterLab version: 

![image](https://github.com/user-attachments/assets/7d2b0cc2-d4d3-44c0-8da5-50603d0c5b96)

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
The relevant error is "OSError: [Errno 101] Network is unreachable". Could it be that you have the port used for the request blocked?

**Comment by krassowski** [comment]
Still, I think the error message should be better here.

**Comment by felixmondelo** [comment]
@krassowski do you now which is the port? the error seems that is in this line of code:

`extensions, last_page = await self.manager.list_extensions(query, page, per_page)`

but I don't know which IP or port is trying to reach.

**Comment by krassowski** [comment]
By default it is just:

https://github.com/jupyterlab/jupyterlab/blob/67f4ead4198df0484a45caaf6afe1e05e9989cc7/jupyterlab/extensions/pypi.py#L111

unless you have proxy configured (e.g. if you have proxy variables set in the environment):

https://github.com/jupyterlab/jupyterlab/blob/67f4ead4198df0484a45caaf6afe1e05e9989cc7/jupyterlab/extensions/pypi.py#L54-L73

**Comment by felixmondelo** [comment]
We're reaching with ping....

PING pypi.org (151.101.192.223) 56(84) bytes of data.
64 bytes from 151.101.192.223 (151.101.192.223): icmp_seq=1 ttl=45 time=25.3 ms
64 bytes from 151.101.192.223 (151.101.192.223): icmp_seq=2 ttl=45 time=25.6 ms

I don't know if there is another test that I can try....

**Comment by buti1021** [comment]
Can you elaborate on how you fixed the issue?

**Comment by felixmondelo** [comment]
Hi @buti1021, the problem was that Jupyterlab was not using the Proxy, so I forced to use it.

**Comment by buti1021** [comment]
Can you tell me how you did that?

**Comment by felixmondelo** [comment]
@buti1021 I resolved by modifying the file site-packages/jupyterlab/extensions/pypi.py to force manually the proxy, because I don't know how to set the proxy for Jupyter and how to validate SSL certificates, so in the code, I forced both.
