### ISSUE TITLE
HTML Sanitizer problem/crash

### ISSUE THREAD

**Issue by martenrichter** [jupyterlab/jupyterlab#16856]
It may be a problem with Plotly, and I should file an issue there.
However, I am observing a crash in the HTML sanitizer. It says `this.buffer.charCodeAt` is not a function.
The cause is relatively easy to find. Plotly generates HTML lines, which are an array of strings. The HTML sanitizer only allows strings (with the charCodeAt). This issue is probably relatively rare, as it only occurs when I have not installed Plotly in my development environment, and so the HTML code is usually not rendered.
You can reproduce it by creating a notebook with Plotly plots, saving it, and opening it in a clean environment without Plotly.

Nothing really important.

**Comment by martenrichter** [comment]
And the notebook was generated with jupyter lab and the error is seen in jupyter lite (but I did not check if it is also visible in jupyter lab).

**Comment by JasonWeill** [comment]
@martenrichter Thanks for opening this issue. I'm not seeing the code `this.buffer.charCodeAt` in JupyterLab's or Plotly's repos, although it's possible that this code is generated in JavaScript after compiling TypeScript. Are you able to see, using your browser's debugger, where this error originates? If it originates in Plotly, this is probably better to address in the Plotly repo.

**Comment by martenrichter** [comment]
The `this.buffer.charCodeAt` is in the HTML parser package, which is called by Jupyter Lab.
I am currently away from my dev environment, but it can be traced back to where the content with HTML mime types was put into the sanitizer. (I can look this up later and give you the precise line. I think it just must be checked for arrays, and the arrays should be merged into one string.)
The question is if it is legal for the notebooks to put in an array of strings for the HTML mime type. This is what Plotly does. The notebook crashes only if it is opened in an environment without Plotly since, with Plotly, the Plotly mime would be rendered.

**Comment by martenrichter** [comment]
Here is the call stack:
``` 
    at e.parse (Tokenizer.js:745:33)
    at e.write (Tokenizer.js:159:14)
    at e.write (Parser.js:459:28)
    at m (index.js:604:10)
    at oe.sanitize (sanitizer.js:931:16)
    at get headings (widget.js:972:102)
    at be.getHeadings (toc.js:176:83)
    at be.refresh (model.js:130:44)
    at i (factory.js:45:19)
    at d (index.es6.js:555:18)
    ```
I think it is this line
https://github.com/jupyterlab/jupyterlab/blob/c321c27b50431fc0414b20a3b61375af7ccb6c2e/packages/cells/src/widget.ts#L1311
There might be other similar invocations. The problem is that the assumption `string` is incorrect as it is an array of strings in this case.

**Comment by krassowski** [comment]
Thanks for the extra details. We had a couple of places where cast to `string` was incorrectly used but `string | string[]` was allowed. Can you think of a simple reproducer that we could use in tests which does not involve third-party package (plotly)?

**Comment by martenrichter** [comment]
One can generate a jupyter notebook with Plotly and load this; this should be enough.
Give me some time, and I can create a notebook by editing the json directly; that should trigger it.
(P.S. I am currently running it in Jupiter lite, but it should not make a difference, as the packages are the same.)

**Comment by martenrichter** [comment]
Here is a specially prepared file to trigger the problem. (I only see it in jupyter lite through, but it is a jupyterlab component).
[minimalexample.zip](https://github.com/user-attachments/files/17429325/minimalexample.zip)
