### ISSUE TITLE
Publishing JupyterLab 4.4.0a0 failed

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16976]
https://github.com/jupyterlab/jupyterlab/actions/runs/11880972498

```
Environment release url was https://github.com/jupyterlab/jupyterlab/releases/tag/untagged-4e7828540a5be0667df6
Extracting metadata for release: https://github.com/jupyterlab/jupyterlab/releases/tag/untagged-4e7828540a5be0667df6
Fetching data for metadata.json...


--------------------------------------------------


extract-release




--------------------------------------------------
Using env value for auth: '***'
Using default value for dist_dir: 'dist'
Using env value for dry_run: 'false'
Using env value for release_url: 'https://github.com/jupyterlab/jupyterlab/releases/tag/untagged-4e7828540a5be0667df6'
Using default value for help: 'False'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Git checkout already exists
Already on 'main'
Your branch is up to date with 'origin/main'.
refs/heads/main
krassowski@users.noreply.github.com
Fetching asset_shas.json...
Fetching jupyterlab-4.4.0a0-py3-none-any.whl...
Fetching jupyterlab-4.4.0a0.tar.gz...
Fetching jupyterlab-application-4.4.0-alpha.0.tgz...
Fetching jupyterlab-application-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-apputils-4.5.0-alpha.0.tgz...
Fetching jupyterlab-apputils-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-attachments-4.4.0-alpha.0.tgz...
Fetching jupyterlab-builder-4.4.0-alpha.0.tgz...
Fetching jupyterlab-buildutils-4.4.0-alpha.0.tgz...
Fetching jupyterlab-cell-toolbar-4.4.0-alpha.0.tgz...
Fetching jupyterlab-cell-toolbar-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-cells-4.4.0-alpha.0.tgz...
Fetching jupyterlab-celltags-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-codeeditor-4.4.0-alpha.0.tgz...
Fetching jupyterlab-codemirror-4.4.0-alpha.0.tgz...
Fetching jupyterlab-codemirror-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-completer-4.4.0-alpha.0.tgz...
Fetching jupyterlab-completer-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-console-4.4.0-alpha.0.tgz...
Fetching jupyterlab-console-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-coreutils-6.4.0-alpha.0.tgz...
Fetching jupyterlab-csvviewer-4.4.0-alpha.0.tgz...
Fetching jupyterlab-csvviewer-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-debugger-4.4.0-alpha.0.tgz...
Fetching jupyterlab-debugger-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-docmanager-4.4.0-alpha.0.tgz...
Fetching jupyterlab-docmanager-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-docregistry-4.4.0-alpha.0.tgz...
Fetching jupyterlab-documentsearch-4.4.0-alpha.0.tgz...
Fetching jupyterlab-documentsearch-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-extensionmanager-4.4.0-alpha.0.tgz...
Fetching jupyterlab-extensionmanager-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-filebrowser-4.4.0-alpha.0.tgz...
Fetching jupyterlab-filebrowser-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-fileeditor-4.4.0-alpha.0.tgz...
Fetching jupyterlab-fileeditor-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-galata-5.4.0-alpha.0.tgz...
Fetching jupyterlab-help-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-htmlviewer-4.4.0-alpha.0.tgz...
Fetching jupyterlab-htmlviewer-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-hub-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-imageviewer-4.4.0-alpha.0.tgz...
Fetching jupyterlab-imageviewer-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-inspector-4.4.0-alpha.0.tgz...
Fetching jupyterlab-inspector-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-javascript-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-json-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-launcher-4.4.0-alpha.0.tgz...
Fetching jupyterlab-launcher-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-logconsole-4.4.0-alpha.0.tgz...
Fetching jupyterlab-logconsole-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-lsp-4.4.0-alpha.0.tgz...
Fetching jupyterlab-lsp-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-mainmenu-4.4.0-alpha.0.tgz...
Fetching jupyterlab-mainmenu-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-markdownviewer-4.4.0-alpha.0.tgz...
Fetching jupyterlab-markdownviewer-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-markedparser-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-mathjax-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-mermaid-4.4.0-alpha.0.tgz...
Fetching jupyterlab-mermaid-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-metadataform-4.4.0-alpha.0.tgz...
Fetching jupyterlab-metadataform-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-metapackage-4.4.0-alpha.0.tgz...
Fetching jupyterlab-nbconvert-css-4.4.0-alpha.0.tgz...
Fetching jupyterlab-nbformat-4.4.0-alpha.0.tgz...
Fetching jupyterlab-notebook-4.4.0-alpha.0.tgz...
Fetching jupyterlab-notebook-extension-4.4.0-alpha.0.tgz...
Fetching jupyterlab-observables-5.4.0-alpha.0.tgz...
Fetching jupyterlab-outputarea-4.4.0-alpha.0.tgz...
Fetching jupyterlab-pdf-extension-4.4.0-alpha.0.tgz...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 121, in invoke
    super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/click/core.py", line 16[88](https://github.com/jupyterlab/jupyterlab/actions/runs/11880972498/job/33104759916#step:5:91), in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 624, in extract_release
    lib.extract_release(
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/lib.py", line 340, in extract_release
    util.fetch_release_asset(dist_dir, asset, auth)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 497, in fetch_release_asset
    r.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. for url: https://objects.githubusercontent.com/github-production-release-asset-XXXXXXXXXXXX?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241117%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241117T180334Z&X-Amz-Expires=300&X-Amz-Signature=XXXXXXXXX&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Djupyterlab-pdf-extension-4.4.0-alpha.0.tgz&response-content-type=application%2Foctet-stream
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/finalize_release.py", line 13, in <module>
    run_action("jupyter-releaser extract-release")
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/common.py", line 25, in run_action
    _run(target, *args, **kwargs)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line [94](https://github.com/jupyterlab/jupyterlab/actions/runs/11880972498/job/33104759916#step:5:97), in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser extract-release' returned non-zero exit status 1.
```

**Comment by krassowski** [comment]
Proceeding with manual upload of packages to fix the CI.

**Comment by krassowski** [comment]
Actually, re-running "Step 2: Publish Release" with "Comma separated list of steps to skip:" `populate-release` is a better approach.

**Comment by krassowski** [comment]
Except that:

- I already uploaded `@jupyterlab/pdf-extension` so this one will be the only one not signed (not a big issue as it is alpha 0)
- after uploading assets releaser failed on `after-publish-assets` with:
```
Running hooks for after-publish-assets
> @jupyterlab/repo-top@0.0.1 after:publish:assets
> jlpm && npm run build:utils && node buildutils/lib/publish --skip-publish
sh: 1: jlpm: not found
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 139, in invoke
    util.run(hook)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'npm run after:publish:assets' returned non-zero exit status 127.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/finalize_release.py", line 15, in <module>
    run_action("jupyter-releaser publish-assets")
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/common.py", line 25, in run_action
    _run(target, *args, **kwargs)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser publish-assets' returned non-zero exit status 1.
```

I suspect it assumes that `jlpm` should be installed in `populate-release` step?

**Comment by jtpio** [comment]
> Actually, re-running "Step 2: Publish Release" with "Comma separated list of steps to skip:" `populate-release` is a better approach.

Yes: https://jupyter-releaser.readthedocs.io/en/latest/faq/index.html#how-to-resume-a-failed-release

> I suspect it assumes that `jlpm` should be installed in `populate-release` step?

Ah that's odd, I thought we have previously been able to resume failed releases like this (it's not the first time `npm` causes us some trouble)

**Comment by andrii-i** [comment]
TODO: reference to this issue should be added to https://github.com/jupyterlab/jupyterlab/blob/main/RELEASE.md#postmortems
