### ISSUE TITLE
Discovery in extension manager doesn't work with proxy

### ISSUE THREAD

**Issue by AmberArr** [jupyterlab/jupyterlab#17054]
## Description

Discovery in extension manager just shows "Error searching for extensions: Error: Unhandled error".
<details><summary>Console output</summary>
<pre>
[E 2024-12-08 01:15:15.159 ServerApp] Uncaught exception GET /lab/api/extensions?query&page=1&per_page=30&refresh=0&1733591713685 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/lab/api/extensions?query&page=1&per_page=30&refresh=0&1733591713685', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/tmp/h28/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 37, in get
        extensions, last_page = await self.manager.list_extensions(query, page, per_page)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 474, in list_extensions
        await self.refresh(query, page, per_page)
      File "/tmp/h28/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 508, in refresh
        await self._update_extensions_list(query, page, per_page)
      File "/tmp/h28/lib/python3.12/site-packages/jupyterlab/extensions/manager.py", line 681, in _update_extensions_list
        extensions, last_page = await self.list_packages(query, page, per_page)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 274, in list_packages
        data = await self._fetch_package_metadata(name, latest_version, self.base_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/async_lru/__init__.py", line 227, in __call__
        return await asyncio.shield(fut)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 82, in _fetch_package_metadata
        response = await client.get(
                   ^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/httpx/_client.py", line 1768, in get
        return await self.request(
               ^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/httpx/_client.py", line 1540, in request
        return await self.send(request, auth=auth, follow_redirects=follow_redirects)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/httpx/_client.py", line 1629, in send
        response = await self._send_handling_auth(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
        response = await self._send_handling_redirects(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
        response = await self._send_single_request(request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/h28/lib/python3.12/site-packages/httpx/_client.py", line 1730, in _send_single_request
        response = await transport.handle_async_request(request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'HTTPTransport' object has no attribute 'handle_async_request'. Did you mean: 'handle_request'?
</pre>
</details>

## Reproduce

1. Open the extension manager tab
2. See the error in Discover

## Context
https://github.com/jupyterlab/jupyterlab/blob/bb596b37d44cacb7aaec2c09aa5d6c8b43a3a2a8/jupyterlab/extensions/pypi.py#L73-L74
Replacing the `HTTPTransport` with `AsyncHTTPTransport` fixes the problem.

- jupyterlab version 4.3.2

**Comment by krassowski** [comment]
Would you like to open a PR? Any idea how to add a test for the proxy functionality which can run on CI?
