### ISSUE TITLE
Install: phosphor/keyboard missing

### ISSUE THREAD

**Issue by marberi** [jupyterlab/jupyterlab#1936]
When installing on Mac I get the message included in the bottom
of the email and an npm log is also attached. From reading the
messages, it looks like it either cannot find the repository for
'phosphor/keyboard' or I have insufficient permissions.

=====
Error message 1:
(tried first without root permissions)
```
ekorn:jupyterlab marberi$ sudo python setup.py develop
Password:
/Users/marberi/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py:331: UserWarning: Normalizing '0.18.0-0' to '0.18.0.post0'
running develop
running egg_info
writing requirements to jupyterlab.egg-info/requires.txt
writing jupyterlab.egg-info/PKG-INFO
writing top-level names to jupyterlab.egg-info/top_level.txt
writing dependency_links to jupyterlab.egg-info/dependency_links.txt
writing entry points to jupyterlab.egg-info/entry_points.txt
reading manifest file 'jupyterlab.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'jupyterlab/build'
no previously-included directories found matching 'jupyterlab/tests'
writing manifest file 'jupyterlab.egg-info/SOURCES.txt'
running build_ext
running jsdeps
> npm --version
1.4.13
Installing build dependencies with npm. This may take a while...
> npm install
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'phosphor/keyboard' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'jupyterlab'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 16.4.0
[npm-debug.log.txt](https://github.com/jupyterlab/jupyterlab/files/848404/npm-debug.log.txt)

npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/marberi/source/jupyterlab
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.4.13
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/marberi/source/jupyterlab/npm-debug.log
npm ERR! not ok code 0
rebuilding js and css failed
missing files: ['/Users/marberi/source/jupyterlab/jupyterlab/build/main.css', '/Users/marberi/source/jupyterlab/jupyterlab/build/main.bundle.js']
Traceback (most recent call last):
  File "setup.py", line 147, in <module>
    setup(**setup_args)
  File "/Users/marberi/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/marberi/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/marberi/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/marberi/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 34, in run
  File "/Users/marberi/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 119, in install_for_development
  File "/Users/marberi/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/marberi/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/marberi/source/jupyterlab/setupbase.py", line 89, in run
    raise e
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
```

```
ekorn:jupyterlab marberi$ sudo npm install phosphor/keyboard
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
\re you sure you want to continue connecting (yes/no)? 
npm ERR! git clone git@github.com:phosphor/keyboard Cloning into bare repository '/var/root/.npm/_git-remotes/git-github-com-phosphor-keyboard-8f89f246'...
npm ERR! git clone git@github.com:phosphor/keyboard Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
npm ERR! git clone git@github.com:phosphor/keyboard Permission denied (publickey).
npm ERR! git clone git@github.com:phosphor/keyboard fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:phosphor/keyboard 
npm ERR! git clone git@github.com:phosphor/keyboard Please make sure you have the correct access rights
npm ERR! git clone git@github.com:phosphor/keyboard and the repository exists.
npm ERR! addLocal Could not install phosphor/keyboard
npm ERR! Error: ENOENT, stat 'phosphor/keyboard'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 16.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "phosphor/keyboard"
npm ERR! cwd /Users/marberi/source/jupyterlab
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.4.13
npm ERR! path phosphor/keyboard
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/marberi/source/jupyterlab/npm-debug.log
npm ERR! not ok code 0
```

**Comment by AbdealiJK** [comment]
There's something weird going on because it should be trying to install `@phosphor/keyboard` and not `phosphor/keyboard`

This works:
```
 $ npm install @phosphor/keyboard
/private/tmp
└── @phosphor/keyboard@0.1.1 
```

Which version of jupyterlab or which commit are you at in the master ?

**Comment by marberi** [comment]
Updated to 8b3f4c3d8edb519d02758264bf03f2eff5ff9145 and still getting the 
same error message. Some more info:

ekorn:jupyterlab marberi$ uname -a
Darwin ekorn.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

and many of the packages are installed using MacPorts. Please let me know if there
are additional log files which will help with debugging.

**Comment by blink1073** [comment]
Hi @marberi, what is the output of:

```
$ npm -v && node -v
3.10.10
v6.9.3
```

**Comment by blink1073** [comment]
Nevermind, I see it in the original error message.  Those are very old versions, are you able to upgrade?

**Comment by marberi** [comment]
Thanks. I upgraded to npm4 and it eventually worked after deleting
some npm cache. It fails on startup, but it looks like an unrelated
question and I will open another issue.

**Comment by blink1073** [comment]
Progress!  Closing this one.
