### ISSUE TITLE
jupyterlab breaks nbconvert by settings cell metadata "slideshow"

### ISSUE THREAD

**Issue by Happyholic1203** [jupyterlab/jupyterlab#2436]
Error message:
```
[NbConvertApp] Converting notebook numpy.ipynb to slides
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 305, in start
    self.convert_notebooks()
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 473, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 444, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 373, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 171, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 189, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/exporters/slides.py", line 111, in from_notebook_node
    nb = prepare(nb)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/exporters/slides.py", line 19, in prepare
    cell.metadata.slide_type = cell.metadata.get('slideshow', {}).get('slide_type', '-')
AttributeError: 'unicode' object has no attribute 'get'
```

To reproduce this AttributeError:
1. Run jupyterlab: `jupyter lab`
2. Create an ipynb
3. Edit a cell and choose **Cell Tools** from the leftmost panel
4. Set the cell to **slide** type

Now, the metadata looks like this:
```json
{
  "collapsed": true,
  "slideshow": "slide"
}
```

This causes nbconvert to raise an `AttributeError` exception:
```python
    # nbconvert/exporters/slides.py:19
    for cell in nb.cells:
         # Make sure every cell has a slide_type
         cell.metadata.slide_type = cell.metadata.get('slideshow', {}).get('slide_type', '-')
```

The above code expects 'slideshow' to be a dict, but jupyterlab sets it to a str.

Just for reference, jupyter notebook sets the cell to:
```json
{
  "collapsed": true,
  "slideshow": {
    "slide_type": "slide"
  }
}
```

Please refer to this [pull request](https://github.com/jupyter/nbconvert/pull/604) in nbconvert as well.

**Comment by blink1073** [comment]
Thanks for the heads up!
