### ISSUE TITLE
jupyterlab install nbwidgets dont work

### ISSUE THREAD

**Issue by Mblp4ur** [jupyterlab/jupyterlab#2485]
```jupyter labextension install @jupyterlab/nbwidgets``` 
output:```
> npm pack @jupyterlab/nbwidgets
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/commands.py", line 110, in install_extension
    errors = _validate_compatibility(extension, deps, core_data)
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/commands.py", line 489, in _validate_compatibility
    overlap = _test_overlap(core_deps[key], value)
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/commands.py", line 510, in _test_overlap
    r1 = Range(spec1, True)
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/semver.py", line 669, in __init__
    xs = [self.parse_range(r.strip()) for r in re.split(r"\s*\|\|\s*", range_)]
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/semver.py", line 723, in parse_range
    set_ = [make_comparator(comp, loose) for comp in set_]
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/semver.py", line 593, in comparator
    return Comparator(comp, loose)
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/semver.py", line 605, in __init__
    self.parse(comp)
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/semver.py", line 628, in parse
    self.semver = semver(m.group(2), self.loose)
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/semver.py", line 315, in semver
    raise ValueError("Invalid Version: {}".format(version))
ValueError: Invalid Version: 0.7.0-0```

```
git clone https://github.com/jupyter-widgets/ipywidgets.git
cd ipywidgets/jupyterlab_widgets
npm install
npm run build
jupyter labextension link .
```
also

**Comment by jasongrout** [comment]
This should be fixed in #2486

**Comment by blink1073** [comment]
Fixed by #2486, thanks!

**Comment by himbeles** [comment]
On a fresh Jupyter install (v0.25.2, using pip), 
`jupyter labextension install @jupyterlab/nbwidgets
`

yields the error message attached below.
Do I interpret correctly, that the version of @jupyterlab/application delivered with the pip package is only 0.7.0 ?

> npm pack @jupyterlab/nbwidgets
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "/usr/local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 57, in <listcomp>
    for arg in self.extra_args]
  File "/usr/local/lib/python3.6/site-packages/jupyterlab/commands.py", line 116, in install_extension
    raise ValueError(msg)
ValueError:
"@jupyterlab/nbwidgets@0.21.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required	Actual	Package
**^0.8.2  	^0.7.0	@jupyterlab/application
^0.8.2  	^0.7.0	@jupyterlab/notebook
^0.8.1  	^0.7.0	@jupyterlab/rendermime**

**Comment by jasongrout** [comment]
Use `jupyter labextension install @jupyter-widgets/jupyterlab-manager`. The name of the npm package has changed.

**Comment by himbeles** [comment]
Great, thanks, I missed that.
