### ISSUE TITLE
Unhandled error in API request

### ISSUE THREAD

**Issue by rodolfo-viana** [jupyterlab/jupyterlab#2516]
I have installed Anaconda and created an env. Jupyter Notebook keeps crashing and returning this error:

```
$ jupyter notebook
[I 01:34:51.802 NotebookApp] Serving notebooks from local directory: C:\Users\ro                                                                                                                dolfoviana\Documents\code\serenata-de-amor
[I 01:34:51.803 NotebookApp] 0 active kernels
[I 01:34:51.803 NotebookApp] The Jupyter Notebook is running at: http://localhos                                                                                                                t:8888/?token=9c6c2fc188537877498d35350be2e52920ece171972b876f
[I 01:34:51.803 NotebookApp] Use Control-C to stop this server and shut down all                                                                                                                 kernels (twice to skip confirmation).
[C 01:34:51.804 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=9c6c2fc188537877498d35350be2e52920ece171972                                                                                                                b876f
[I 01:34:52.999 NotebookApp] Accepting one-time-token-authenticated connection f                                                                                                                rom ::1
[E 01:35:03.820 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\base\handlers.py                                                                                                                ", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 289                                                                                                                7, in wrapper
        return method(self, *args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\                                                                                                                handlers.py", line 20, in get
        self.finish(json.dumps(self.config_manager.get(section_name)))
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\                                                                                                                manager.py", line 25, in get
        recursive_update(config, cm.get(section_name))
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\manager.                                                                                                                py", line 63, in get
        return json.load(f)
      File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw                                                                                                                )
      File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_deco                                                                                                                de
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[E 01:35:03.839 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.3                                                                                                                6 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/develop/2017-06-20-rodolfovian                                                                                                                a-expenses-on-car-rental.ipynb",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Accept-Language": "pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4",
      "Cookie": "_xsrf=2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744; u                                                                                                                sername-localhost-8888=\"2|1:0|10:1498106093|23:username-localhost-8888|44:MDcyN                                                                                                                zRkNDZiZTc3NGYzNDk5NzIyOGE2ZjQxYTFlNzU=|e67b378dda3a3b63c4799e35543e6dd80d175d96                                                                                                                5c17cf98c296bf2bf8c2b52c\""
```
Then I ran kernelspec list debug and got this:

```
$ jupyter kernelspec list --debug
[ListKernelSpecs] Searching ['C:\\Users\\rodolfoviana\\Documents\\code\\serenata                                                                                                                -de-amor', 'C:\\Users\\rodolfoviana\\.jupyter', 'C:\\ProgramData\\Anaconda3\\etc                                                                                                                \\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[ListKernelSpecs] Looking for jupyter_config in C:\ProgramData\jupyter
[ListKernelSpecs] Looking for jupyter_config in C:\ProgramData\Anaconda3\etc\jup                                                                                                                yter
[ListKernelSpecs] Looking for jupyter_config in C:\Users\rodolfoviana\.jupyter
[ListKernelSpecs] Looking for jupyter_config in C:\Users\rodolfoviana\Documents\                                                                                                                code\serenata-de-amor
[ListKernelSpecs] Found kernel python3 in C:\ProgramData\Anaconda3\share\jupyter                                                                                                                \kernels
[ListKernelSpecs] Found kernel python3 in C:\ProgramData\Anaconda3\share\jupyter                                                                                                                \kernels
Available kernels:
  python3    C:\ProgramData\Anaconda3\share\jupyter\kernels\python3
```
Finally, ran notebook debug:

```
$ jupyter notebook --debug
[D 01:37:42.348 NotebookApp] Searching ['C:\\Users\\rodolfoviana\\Documents\\cod                                                                                                                e\\serenata-de-amor', 'C:\\Users\\rodolfoviana\\.jupyter', 'C:\\ProgramData\\Ana                                                                                                                conda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 01:37:42.349 NotebookApp] Looking for jupyter_config in C:\ProgramData\jupyte                                                                                                                r
[D 01:37:42.349 NotebookApp] Looking for jupyter_config in C:\ProgramData\Anacon                                                                                                                da3\etc\jupyter
[D 01:37:42.349 NotebookApp] Looking for jupyter_config in C:\Users\rodolfoviana                                                                                                                \.jupyter
[D 01:37:42.350 NotebookApp] Looking for jupyter_config in C:\Users\rodolfoviana                                                                                                                \Documents\code\serenata-de-amor
[D 01:37:42.351 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramDa                                                                                                                ta\jupyter
[D 01:37:42.351 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramDa                                                                                                                ta\Anaconda3\etc\jupyter
[D 01:37:42.352 NotebookApp] Looking for jupyter_notebook_config in C:\Users\rod                                                                                                                olfoviana\.jupyter
[D 01:37:42.352 NotebookApp] Loaded config file: C:\Users\rodolfoviana\.jupyter\                                                                                                                jupyter_notebook_config.py
[D 01:37:42.353 NotebookApp] Looking for jupyter_notebook_config in C:\Users\rod                                                                                                                olfoviana\Documents\code\serenata-de-amor
[D 01:37:44.144 NotebookApp] Terminals not available (error was No module named                                                                                                                 'terminado')
[I 01:37:44.256 NotebookApp] Serving notebooks from local directory: C:\Users\ro                                                                                                                dolfoviana\Documents\code\serenata-de-amor
[I 01:37:44.256 NotebookApp] 0 active kernels
[I 01:37:44.256 NotebookApp] The Jupyter Notebook is running at: http://localhos                                                                                                                t:8888/?token=50c47e8f76e3a193ca5b229550ce98c69fb7c6933a4c4b85
[I 01:37:44.256 NotebookApp] Use Control-C to stop this server and shut down all                                                                                                                 kernels (twice to skip confirmation).
[C 01:37:44.258 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=50c47e8f76e3a193ca5b229550ce98c69fb7c6933a4                                                                                                                c4b85
[I 01:37:45.060 NotebookApp] Accepting one-time-token-authenticated connection f                                                                                                                rom ::1
[D 01:43:34.267 NotebookApp] 200 GET /api/sessions?_=1498106265406 (::1) 2.00ms
[D 01:43:34.299 NotebookApp] 200 GET /api/contents?type=directory&_=1498106265407 (::1) 24.06ms                                                                                                 [D 01:43:42.095 NotebookApp] Using contents: services/contentsavicon.ico
[D 01:43:42.097 NotebookApp] 200 GET /tree/develop (::1) 4.01msmoothness/jquery-                                                                                                                [D 01:43:42.124 NotebookApp] 304 GET /custom/custom.css (::1) 2.01mstebook\stati                                                                                                                [D 01:43:42.527 NotebookApp] 200 GET /api/config/tree?_=1498106622341 (::1) 4.01ms
[D 01:43:42.530 NotebookApp] 200 GET /api/config/common?_=1498106622342 (::1) 2.01ms                                                                                                            [D 01:43:42.541 NotebookApp] Found kernel python3 in C:\ProgramData\Anaconda3\share\jupyter\kernels                                                                                             [D 01:43:42.541 NotebookApp] Found kernel python3 in C:\ProgramData\Anaconda3\share\jupyter\kernels
[D 01:43:42.544 NotebookApp] 304 GET /api/kernelspecs (::1) 5.01msC:\ProgramData                                                                                                                [D 01:43:42.546 NotebookApp] 200 GET /api/sessions?_=1498106622343 (::1) 2.01ms
[D 01:43:42.671 NotebookApp] 200 GET /api/contents/develop?type=directory&_=1498106622344 (::1) 92.25ms                                                                                         [D 01:43:42.674 NotebookApp] 304 GET /custom/custom.js?v=20170622013742 (::1) 2.01ms                                                                                                            [D 01:43:48.893 NotebookApp] Using contents: services/contents
[D 01:43:48.959 NotebookApp] Path components/bootstrap-tour/build/css/bootstrap-tour.min.css served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\bootstrap-tour\build\css\bootstrap-tour.min.csskages\notebook\static\components\preact\index.js
[D 01:43:48.960 NotebookApp] Path components/codemirror/lib/codemirror.css served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\codemirror\lib\codemirror.css      [D 01:43:48.961 NotebookApp] Path notebook/css/override.css served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\notebook\css\override.css                                    [D 01:43:48.962 NotebookApp] Path components/text-encoding/lib/encoding.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\text-encoding\lib\encoding.js
[D 01:43:48.963 NotebookApp] Path notebook/js/main.min.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\notebook\js\main.min.js                                        [D 01:43:48.969 NotebookApp] 200 GET /notebooks/develop/2017-06-20-rodolfoviana-expenses-on-car-rental.ipynb (::1) 76.20ms                                                                      [D 01:43:48.985 NotebookApp] Path components\MathJax\MathJax.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\MathJax\MathJax.js
[D 01:43:48.986 NotebookApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&delayStartupUntil=configured (::1) 2.00ms                                     [D 01:43:48.994 NotebookApp] 304 GET /custom/custom.css (::1) 1.00msrequirejs\re                                                                                                                [D 01:43:49.125 NotebookApp] Path components\MathJax\config\TeX-AMS-MML_HTMLorMML-full.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\MathJax\config\TeX-AMS-MML_HTMLorMML-full.jsApp] Path base/images/logo.png served from C:\ProgramDat                                                                                                                [D 01:43:49.126 NotebookApp] 304 GET /static/components/MathJax/config/TeX-AMS-MML_HTMLorMML-full.js?rev=2.6.0 (::1) 1.00ms
[D 01:43:49.273 NotebookApp] Path components\MathJax\config\Safe.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\MathJax\config\Safe.js                    [D 01:43:49.274 NotebookApp] 304 GET /static/components/MathJax/config/Safe.js?rev=2.6.0 (::1) 1.00ms
[E 01:43:49.414 NotebookApp] Unhandled error in API request9f67965842cc9091ca634                                                                                                                    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper                                                                                                 result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 2897, in wrapper
        return method(self, *args, **kwargs)ontents.js served from C:\ProgramDat                                                                                                                      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\handlers.py", line 20, in get
        self.finish(json.dumps(self.config_manager.get(section_name)))1706220137                                                                                                                      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\manager.py", line 25, in get
        recursive_update(config, cm.get(section_name))_=1498106265400 (::1) 4.01                                                                                                                      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\manager.py", line 63, in get
        return json.load(f)] 200 GET /api/config/common?_=1498106265401 (::1) 4.                                                                                                                      File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)                                                                                                                     File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s) python3 in C:\ProgramData\Anaconda3\sh                                                                                                                      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())1) 18.05ms
      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None10626540                                                                                                                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[E 01:43:49.420 NotebookApp] {ath custom.js served from C:\ProgramData\Anaconda3                                                                                                                      "Host": "localhost:8888",tic\custom\custom.js
      "Connection": "keep-alive",GET /custom/custom.js?v=20170622013742 (::1) 3.                                                                                                                      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",essions?_=1498106265404 (::1) 1.00ms
      "X-Xsrftoken": "2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744",40                                                                                                                      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/develop/2017-06-20-rodolfoviana-expenses-on-car-rental.ipynb",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Accept-Language": "pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4",
      "Cookie": "_xsrf=2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744; username-localhost-8888=\"2|1:0|10:1498106265|23:username-localhost-8888|44:MGM1YzIwYmRjYTcyNDBkM2E5OGY0NzlmNzZhMzk2NGM=|8fb72047e90e623567d8b398d94588beb9456861fa1d566dfe77f097e7d0592d\""
    }
[E 01:43:49.421 NotebookApp] 500 GET /api/config/notebook?_=1498106629304 (::1) 9.02ms referer=http://localhost:8888/notebooks/develop/2017-06-20-rodolfoviana-expenses-on-car-rental.ipynb
[D 01:43:49.424 NotebookApp] 200 GET /api/config/common?_=1498106629305 (::1) 3.01ms
[D 01:43:49.481 NotebookApp] Path components\MathJax\extensions\MathML\content-mathml.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\MathJax\extensions\MathML\content-mathml.js
[D 01:43:49.482 NotebookApp] 304 GET /static/components/MathJax/extensions/MathML/content-mathml.js?rev=2.6.0 (::1) 1.00ms
[D 01:43:49.524 NotebookApp] Found kernel python3 in C:\ProgramData\Anaconda3\share\jupyter\kernels
[D 01:43:49.525 NotebookApp] Found kernel python3 in C:\ProgramData\Anaconda3\share\jupyter\kernels
[D 01:43:49.527 NotebookApp] 304 GET /api/kernelspecs (::1) 4.01ms
[D 01:43:50.171 NotebookApp] 200 GET /api/contents/develop/2017-06-20-rodolfoviana-expenses-on-car-rental.ipynb?type=notebook&_=1498106629306 (::1) 600.60ms
[D 01:43:50.195 NotebookApp] Path components\MathJax\jax\output\HTML-CSS\fonts\STIX-Web\fontdata.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\MathJax\jax\output\HTML-CSS\fonts\STIX-Web\fontdata.js
[D 01:43:50.196 NotebookApp] 304 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js?rev=2.6.0 (::1) 2.01ms
[D 01:43:50.198 NotebookApp] Path components\MathJax\extensions\Safe.js served from C:\ProgramData\Anaconda3\lib\site-packages\notebook\static\components\MathJax\extensions\Safe.js
[D 01:43:50.200 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.js?rev=2.6.0 (::1) 3.01ms
[D 01:43:50.203 NotebookApp] 304 GET /custom/custom.js?v=20170622013742 (::1) 2.01ms
[D 01:43:56.204 NotebookApp] Found kernel python3 in C:\ProgramData\Anaconda3\share\jupyter\kernels
[D 01:43:56.206 NotebookApp] Starting kernel: ['C:\\ProgramData\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\rodolfoviana\\AppData\\Roaming\\jupyter\\runtime\\kernel-86388b63-cb76-4fb2-b5a4-8befe3243e14.json']
[D 01:43:56.217 NotebookApp] Connecting to: tcp://127.0.0.1:50799
[D 01:43:56.243 NotebookApp] Connecting to: tcp://127.0.0.1:50797
[I 01:43:56.250 NotebookApp] Kernel started: 86388b63-cb76-4fb2-b5a4-8befe3243e14
[D 01:43:56.250 NotebookApp] Kernel args: {'kernel_name': 'python3', 'cwd': 'C:\\Users\\rodolfoviana\\Documents\\code\\serenata-de-amor\\develop'}
[D 01:43:56.251 NotebookApp] 201 POST /api/sessions (::1) 167.45ms
[D 01:43:56.254 NotebookApp] 200 GET /api/contents/develop/2017-06-20-rodolfoviana-expenses-on-car-rental.ipynb/checkpoints?_=1498106629307 (::1) 2.00ms
[D 01:43:56.517 NotebookApp] 200 GET /api/sessions?_=1498106622345 (::1) 1.00ms
[D 01:43:59.030 NotebookApp] Initializing websocket connection /api/kernels/86388b63-cb76-4fb2-b5a4-8befe3243e14/channels
[D 01:43:59.033 NotebookApp] Requesting kernel info from 86388b63-cb76-4fb2-b5a4-8befe3243e14
[D 01:43:59.034 NotebookApp] Connecting to: tcp://127.0.0.1:50796
[D 01:43:59.175 NotebookApp] 200 GET /api/contents/develop?type=directory&_=1498106622346 (::1) 120.32ms
[D 01:44:00.335 NotebookApp] activity on 86388b63-cb76-4fb2-b5a4-8befe3243e14: status
[D 01:44:00.338 NotebookApp] activity on 86388b63-cb76-4fb2-b5a4-8befe3243e14: status
[D 01:44:00.339 NotebookApp] activity on 86388b63-cb76-4fb2-b5a4-8befe3243e14: status
[D 01:44:00.340 NotebookApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.1', 'implementation': 'ipython', 'implementation_version': '5.3.0', 'language_info': {'name': 'python', 'version': '3.6.1', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': 'Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]\nType "copyright", "credits" or "license" for more information.\n\nIPython 5.3.0 -- An enhanced Interactive Python.\n?         -> Introduction and overview of IPython\'s features.\n%quickref -> Quick reference.\nhelp      -> Python\'s own help system.\nobject?   -> Details about \'object\', use \'object??\' for extra details.\n', 'help_links': [{'text': 'Python', 'url': 'http://docs.python.org/3.6'}, {'text': 'IPython', 'url': 'http://ipython.org/documentation.html'}, {'text': 'NumPy', 'url': 'http://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy', 'url': 'http://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib', 'url': 'http://matplotlib.org/contents.html'}, {'text': 'SymPy', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas', 'url': 'http://pandas.pydata.org/pandas-docs/stable/'}]}
[D 01:44:00.342 NotebookApp] 101 GET /api/kernels/86388b63-cb76-4fb2-b5a4-8befe3243e14/channels?session_id=F8B9251B8EF4499C8DFD671EAF4A0F33 (::1) 1310.48ms
[D 01:44:00.342 NotebookApp] Opening websocket /api/kernels/86388b63-cb76-4fb2-b5a4-8befe3243e14/channels
[D 01:44:00.342 NotebookApp] Connecting to: tcp://127.0.0.1:50796
[D 01:44:00.349 NotebookApp] Connecting to: tcp://127.0.0.1:50797
[D 01:44:00.355 NotebookApp] Connecting to: tcp://127.0.0.1:50798
```
Do you guys know how to fix this, please?

**Comment by blink1073** [comment]
Hi @rodolfo-viana, it looks like it might be an issue with the notebook file itself not being valid JSON.  You can try from a python prompt in your `develop` directory as:

```python
import json
with open('2017-06-20-rodolfoviana-expenses-on-car-rental.ipynb') as fid:
    json.load(fid)
```

**Comment by rodolfo-viana** [comment]
I did that. It didn't work.
I tried 1) to open another existing notebook and 2) to create a new one. Got the same error.

```
$ jupyter notebook
[I 12:32:24.662 NotebookApp] Serving notebooks from local directory: C:\Users\ro                                                                                                                dolfoviana\Documents\code\serenata-de-amor
[I 12:32:24.662 NotebookApp] 0 active kernels
[I 12:32:24.662 NotebookApp] The Jupyter Notebook is running at: http://localhos                                                                                                                t:8888/?token=a996b5e939a077e57e21cdef9ded91182eeafe0b8bf3e5fe
[I 12:32:24.662 NotebookApp] Use Control-C to stop this server and shut down all                                                                                                                 kernels (twice to skip confirmation).
[C 12:32:24.662 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=a996b5e939a077e57e21cdef9ded91182eeafe0b8bf                                                                                                                3e5fe
[I 12:32:24.896 NotebookApp] Accepting one-time-token-authenticated connection f                                                                                                                rom ::1
[E 12:32:47.018 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\base\handlers.py                                                                                                                ", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 289                                                                                                                7, in wrapper
        return method(self, *args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\                                                                                                                handlers.py", line 20, in get
        self.finish(json.dumps(self.config_manager.get(section_name)))
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\                                                                                                                manager.py", line 25, in get
        recursive_update(config, cm.get(section_name))
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\manager.                                                                                                                py", line 63, in get
        return json.load(f)
      File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw                                                                                                                )
      File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_deco                                                                                                                de
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[E 12:32:47.022 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.3                                                                                                                6 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/develop/2017-05-19-jtemporal-c                                                                                                                ities-transparency-portal.ipynb",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Accept-Language": "pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4",
      "Cookie": "_xsrf=2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744; u                                                                                                                sername-localhost-8888=\"2|1:0|10:1498145544|23:username-localhost-8888|44:OTljZ                                                                                                                DdhMDA1MWU0NDJkN2I0ZmE5ZDdmN2UyM2IzODA=|74f21d62514d1e1fddef58e300272b258a90f500                                                                                                                190dca4fa6ab38d1ab226fdd\""
    }
[E 12:32:47.022 NotebookApp] 500 GET /api/config/notebook?_=1498145566902 (::1)                                                                                                                 8.01ms referer=http://localhost:8888/notebooks/develop/2017-05-19-jtemporal-citi                                                                                                                es-transparency-portal.ipynb
[W 12:32:47.210 NotebookApp] Notebook develop/2017-05-19-jtemporal-cities-transp                                                                                                                arency-portal.ipynb is not trusted
[I 12:32:48.476 NotebookApp] Kernel started: fff34ad9-6e97-4b41-995b-85920f33343                                                                                                                3
[I 12:34:06.553 NotebookApp] Creating new notebook in /develop
[NbConvertApp] Converting notebook Untitled.ipynb to script
[NbConvertApp] Writing 0 bytes to Untitled.txt
[NbConvertApp] Converting notebook Untitled.ipynb to html
[NbConvertApp] Writing 248809 bytes to Untitled.html
[E 12:34:17.627 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\base\handlers.py                                                                                                                ", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 289                                                                                                                7, in wrapper
        return method(self, *args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\                                                                                                                handlers.py", line 20, in get
        self.finish(json.dumps(self.config_manager.get(section_name)))
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\config\                                                                                                                manager.py", line 25, in get
        recursive_update(config, cm.get(section_name))
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\manager.                                                                                                                py", line 63, in get
        return json.load(f)
      File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw                                                                                                                )
      File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_deco                                                                                                                de
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[E 12:34:17.627 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.3                                                                                                                6 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/develop/Untitled.ipynb?kernel_                                                                                                                name=python3",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Accept-Language": "pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4",
      "Cookie": "_xsrf=2|b4f33e18|39b67e3dd664ba24e19afc439b7427d8|1498100744; u                                                                                                                sername-localhost-8888=\"2|1:0|10:1498145544|23:username-localhost-8888|44:OTljZ                                                                                                                DdhMDA1MWU0NDJkN2I0ZmE5ZDdmN2UyM2IzODA=|74f21d62514d1e1fddef58e300272b258a90f500                                                                                                                190dca4fa6ab38d1ab226fdd\""
    }
[E 12:34:17.627 NotebookApp] 500 GET /api/config/notebook?_=1498145657502 (::1)                                                                                                                 4.01ms referer=http://localhost:8888/notebooks/develop/Untitled.ipynb?kernel_nam                                                                                                                e=python3
[I 12:34:18.012 NotebookApp] Kernel started: cb893dfd-64da-40b9-ad8e-b8da7ce820f                                                                                                                8

```

**Comment by blink1073** [comment]
I could be that there is a bad config file in one of the config locations listed by `jupyter --paths`.

For example, `~/.jupyter/nbconfig/notebook.json`.

**Comment by rodolfo-viana** [comment]
Yes, I guess that's it. I just don't know how to fix it. Ideas? :)

**Comment by blink1073** [comment]
You can either blow away the offending `nbconfig` director(ies), or try and debug the existing files to see where the invalid JSON is coming from.

**Comment by rodolfo-viana** [comment]
I reinstalled everything and now it works. Thanks for your help, @blink1073.
