### ISSUE TITLE
ipywidgets in 0.25.0

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#2650]
Hi, 
Im on release 0.25.0 
Tried to install ipywidgets as below.

`pip install ipywidgets --pre`
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

Get the following error for labextension install:

>npm pack @jupyter-widgets/jupyterlab-manager
Traceback (most recent call last):
  File "/../bin/jupyter-labextension", line 11, in <module>
    load_entry_point('jupyterlab', 'console_scripts', 'jupyter-labextension')()
  File "/../lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/../lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/../jlab_0.25/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/../lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/../jlab_0.25/jupyterlab/labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "/../jlab_0.25/jupyterlab/labextensions.py", line 57, in <listcomp>
    for arg in self.extra_args]
  File "/../jlab_0.25/jupyterlab/commands.py", line 116, in install_extension
    raise ValueError(msg)
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.23.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required	Actual	Package
^0.8.0  	^0.7.0	@jupyterlab/application
^0.8.0  	^0.7.0	@jupyterlab/notebook
^0.8.0  	^0.7.0	@jupyterlab/rendermime

Tried with 0.23.4 as well. Same conflicts. Is there some other way to run ipywidgets in v0.25.0?

**Comment by jasongrout** [comment]
> Is there some other way to run ipywidgets in v0.25.0?

We'll update to 0.25 shortly. Current ipywidgets alpha runs on 0.24.1.

**Comment by rsinha25** [comment]
Sure, Thanks :)
