### ISSUE TITLE
Unable to install extensions with 0.25

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#2660]
When I try to install the jupyterlab extension for either `ipywidgets` or `jupyterlab-hub` I get a conflicting dependency issue - e.g.
```python-traceback
C:\>jupyter labextension install @jupyter-widgets/jupyterlab-manager
> npm pack @jupyter-widgets/jupyterlab-manager
Traceback (most recent call last):
  File "C:\Miniconda3\envs\quantdev\Scripts\jupyter-labextension-script.py", line 5, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "C:\Miniconda3\envs\quantdev\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Miniconda3\envs\quantdev\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Miniconda3\envs\quantdev\lib\site-packages\jupyterlab\labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "C:\Miniconda3\envs\quantdev\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "C:\Miniconda3\envs\quantdev\lib\site-packages\jupyterlab\labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "C:\Miniconda3\envs\quantdev\lib\site-packages\jupyterlab\labextensions.py", line 57, in <listcomp>
    for arg in self.extra_args]
  File "C:\Miniconda3\envs\quantdev\lib\site-packages\jupyterlab\commands.py", line 116, in install_extension
    raise ValueError(msg)
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.23.4" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required        Actual  Package
^0.8.2          ^0.7.0  @jupyterlab/application
^0.8.2          ^0.7.0  @jupyterlab/notebook
^0.8.1          ^0.7.0  @jupyterlab/rendermime
```
```
C:\>conda list jupyterlab
# packages in environment at C:\Miniconda3\envs\quantdev:
#
jupyterlab                0.25.2                   py36_0    conda-forge
jupyterlab_launcher       0.3.0                    py36_0    conda-forge
```
The `package.app.json` from the installed `jupyterlab` does seem to specify `"^0.8.2"` though so I'm not sure where `"^0.7.0"` is being picked up from.

**`pacakge.app.json`:**
```json
{
  "name": "@jupyterlab/application-top",
  "version": "0.8.3",
  "scripts": {
    "build": "webpack",
    "publish": "node make-release.js"
  },
  "dependencies": {
    "@jupyterlab/application": "^0.8.2",
    "@jupyterlab/application-extension": "^0.8.2",
<snip>
```

Any idea how to begin to debug this?

**Comment by sccolbert** [comment]
ipywidgets are not yet updated for `0.25`. In semver `0.x` treats `x` as a major version, so `^0.7` is not compatible with `^0.8`.

**Comment by dhirschfeld** [comment]
Yep, only just realised that. Sorry for the noise!
