### ISSUE TITLE
Keystrokes not being sent correctly to a remote instance of jupyter lab

### ISSUE THREAD

**Issue by joonro** [jupyterlab/jupyterlab#2736]
Hi,

I have been using ssh to log-into a cluster (`ssh -L 9000:127.0.0.1:8888 cluster`), run `jupyter lab`, and then open `http://localhost:9000/lab` in my browser to access it. 

It has been working great so far, but I just upgraded to `0.26.3` (from `0.25.x`), and I just found that keystrokes are not being sent correctly to a remote instance of jupyter lab. 

For example,

- Pressing `ctrl-s` invokes browser's save as function
- Pressing `enter` works in a notebook, but `shift-enter` does not do anything
- In a console, even `enter` does not do anything.

I do not have this issue with a juptyer lab instance on my local machine.

**Comment by blink1073** [comment]
Hi @joonro, if you select `File > Settings`, do so see these setting items?

<image src="https://user-images.githubusercontent.com/2096628/28542892-8c0dceba-7083-11e7-8abd-19d1cf23300b.png" width=400>

**Comment by joonro** [comment]
No - they are empty.

**Comment by blink1073** [comment]
Is this a source checkout?  If so, it looks like you need to run `npm install && npm run build` from the repo root.

**Comment by joonro** [comment]
No I installed (upgraded) it with `conda install -c conda-forge jupyterlab`.

**Comment by joonro** [comment]
It is strange that in my local machine I do see those settings. The only difference is the remote machine uses GNU/Linux and my local machine has Windows 10. I used `conda` to install and upgrade jupyter lab in both machines.

**Comment by blink1073** [comment]
Hmm, I just tried on Ubuntu with a clean conda install and it is working fine.  Are you able to introspect what is installed on the cluster?  Specifically, there should be a populated `schemas` directory where `jupyterlab` is installed.

**Comment by joonro** [comment]
Thanks for the quick replies. I just checked and here are the stuff in the schemas directory:

```
[/home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab/schemas]
$ l
total 36
drwxr-sr-x 2 jro jro  4096 Jul 24 15:55 .
drwxr-sr-x 5 jro jro  4096 Jul 24 15:55 ..
-rw-rw-r-- 2 jro jro 18750 Jul 22 07:45 jupyter.extensions.shortcuts.json
-rw-rw-r-- 2 jro jro   399 Jul 22 07:45 jupyter.services.codemirror-commands.json
-rw-rw-r-- 2 jro jro   623 Jul 22 07:45 jupyter.services.editor-tracker.json
```

Please let me know if this does not look right.

**Comment by blink1073** [comment]
That looks right.  Do you have access to the log output of the server?

**Comment by joonro** [comment]
The following is what I got:

```
$ jupyter lab
[W 10:51:04.148 LabApp] Unrecognized JSON config file version, assuming version 1
[I 10:51:05.186 LabApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 10:51:05.186 LabApp] JupyterLab alpha preview extension loaded from /home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab
JupyterLab v0.26.3
Known labextensions:
[I 10:51:05.189 LabApp] Running the core application with no additional extensions or settings
[E 10:51:05.191 LabApp] shemas_dir: /home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab/schemas
[I 10:51:05.196 LabApp] Serving notebooks from local directory: /home/jro
[I 10:51:05.196 LabApp] 0 active kernels
[I 10:51:05.196 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=7c5b7389bb7bddf3f7f2ac472d24a7a75b32592d87a646d1
[I 10:51:05.196 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:51:05.198 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=7c5b7389bb7bddf3f7f2ac472d24a7a75b32592d87a646d1
[I 10:51:05.232 LabApp] Accepting one-time-token-authenticated connection from 127.0.0.1
```

Nothing looks out of ordinary, I just installed `jupyter_nbextensions_configurator` after seeing jupyter lab complaining about it via `conda install -c conda-forge jupyter_nbextensions_configurator`, but it did not change anything in terms of the browser behavior.

**Comment by blink1073** [comment]
That part looks good, can we see some output after you load the page over ssh?

**Comment by joonro** [comment]
Sure. Currently I'm running something and the following is the output:

```python
I 10:54:28.521 LabApp] 302 GET / (127.0.0.1) 0.35ms                                                                                   [------] [I 10:54:29.004 LabApp] 302 GET / (127.0.0.1) 0.30ms
[W 10:54:30.844 LabApp] 404 GET /lab/api/settings/jupyter.extensions.shortcuts?1500998070980 (127.0.0.1) 34.12ms referer=http://localhost:9000/lab?
[W 10:54:30.848 LabApp] 404 GET /lab/api/settings/jupyter.services.editor-tracker?1500998070989 (127.0.0.1) 3.54ms referer=http://localhost:9000/lab?
[W 10:54:30.871 LabApp] 404 GET /lab/api/settings/jupyter.services.codemirror-commands?1500998070997 (127.0.0.1) 4.15ms referer=http://localhost:9000/lab?
[I 10:54:35.953 LabApp] Kernel started: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:54:37.375 LabApp] Adapting to protocol v5.1 for kernel 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:01.903 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:02.050 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:02.184 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:02.344 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:02.470 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:02.672 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:02.798 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:02.952 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:03.099 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:03.248 LabApp] Kernel interrupted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:06.009 LabApp] Kernel restarted: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[I 10:56:40.547 LabApp] Saving file at /Sync/devel.ipynb
[W 11:07:05.245 LabApp] Notebook Sync/Inspect_Results.ipynb is not trusted
[I 11:07:07.463 LabApp] Kernel started: 70066e00-97f9-4f93-8e9e-bb9d4b17df48
[I 11:07:09.768 LabApp] Adapting to protocol v5.1 for kernel 70066e00-97f9-4f93-8e9e-bb9d4b17df48
[I 11:07:17.720 LabApp] Adapting to protocol v5.1 for kernel 70066e00-97f9-4f93-8e9e-bb9d4b17df48
```

**Comment by blink1073** [comment]
Hmm, it looks like the settings handler is getting added but not invoked.   For some reason `/lab/api/settings/jupyter.extensions.shortcuts?1500998070980` is not matching `r"/lab/api/settings/(?P<section_name>[\w.-]+)"`  What version of python is this?

**Comment by joonro** [comment]
It is

```python
$ python
Python 3.5.3 | packaged by conda-forge | (default, May 12 2017, 15:07:14)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
```

**Comment by blink1073** [comment]
Can you try adding this line to the end of `jupyterlab/extension.py` to verify which url is getting added?

```python
    web_app.add_handlers(".*$", [settings_handler])  # existing line
    nbapp.log.warn('settings_url', settings_url)
```

**Comment by joonro** [comment]
Here it is!

```python
W 11:46:32.674 LabApp] 404 GET /api/kernels/70066e00-97f9-4f93-8e9e-bb9d4b17df48/channels?session_id=a7c09950552930d9ad8434061a2d2882&token=0ddc74bf5dcec3fe37d3d1ebe432ae704b11ad8ae2dbfe9a (127.0.0.1): Kernel does not exist: 70066e00-97f9-4f93-8e9e-bb9d4b17df48
[W 11:46:32.707 LabApp] 404 GET /api/kernels/70066e00-97f9-4f93-8e9e-bb9d4b17df48/channels?session_id=a7c09950552930d9ad8434061a2d2882&token=0ddc74bf5dcec3fe37d3d1ebe432ae704b11ad8ae2dbfe9a (127.0.0.1) 39.33ms referer=None
[W 11:46:33.000 LabApp] 404 GET /api/kernels/81bbe12e-bc84-4782-a1dc-eb9fe466df8a/channels?session_id=5764def4cfc829f5a35dd9d5c4dbe839&token=0ddc74bf5dcec3fe37d3d1ebe432ae704b11ad8ae2dbfe9a (127.0.0.1): Kernel does not exist: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a
[W 11:46:33.003 LabApp] 404 GET /api/kernels/81bbe12e-bc84-4782-a1dc-eb9fe466df8a/channels?session_id=5764def4cfc829f5a35dd9d5c4dbe839&token=0ddc74bf5dcec3fe37d3d1ebe432ae704b11ad8ae2dbfe9a (127.0.0.1) 7.13ms referer=None
[W 11:46:33.305 LabApp] 404 GET /api/kernels/70066e00-97f9-4f93-8e9e-bb9d4b17df48/channels?session_id=97108c75229de283c62787eead25a02b&token=0ddc74bf5dcec3fe37d3d1ebe432ae704b11ad8ae2dbfe9a (127.0.0.1): Kernel does not exist: 70066e00-97f9-4f93-8e9e-bb9d4b17df48
[W 11:46:33.308 LabApp] 404 GET /api/kernels/70066e00-97f9-4f93-8e9e-bb9d4b17df48/channels?session_id=97108c75229de283c62787eead25a02b&token=0ddc74bf5dcec3fe37d3d1ebe432ae704b11ad8ae2dbfe9a (127.0.0.1) 7.05ms referer=None
[W 11:46:41.068 LabApp] Replacing stale connection: 70066e00-97f9-4f93-8e9e-bb9d4b17df48:a7c09950552930d9ad8434061a2d2882
[W 11:46:41.798 LabApp] Replacing stale connection: 81bbe12e-bc84-4782-a1dc-eb9fe466df8a:5764def4cfc829f5a35dd9d5c4dbe839
[W 11:48:06.946 LabApp] 404 GET /lab/api/settings/jupyter.extensions.shortcuts?1501001287298 (127.0.0.1) 3.57ms referer=http://localhost:9000/lab?
[W 11:48:06.954 LabApp] 404 GET /lab/api/settings/jupyter.services.editor-tracker?1501001287308 (127.0.0.1) 3.20ms referer=http://localhost:9000/lab?
[W 11:48:06.976 LabApp] 404 GET /lab/api/settings/jupyter.services.codemirror-commands?1501001287319 (127.0.0.1) 3.61ms referer=http://localhost:9000/lab?
[W 11:48:07.434 LabApp] Notebook Sync/Inspect_Results.ipynb is not trusted
[W 11:48:13.963 LabApp] Notebook Sync/Inspect_Results.ipynb is not trusted
[I 11:48:15.991 LabApp] Kernel started: 5c7c96d0-81dc-4a97-bba0-b9f54460d199
[I 11:48:16.679 LabApp] Kernel started: 87733958-6361-416a-9bbc-d49a5e214c71
[I 11:48:17.448 LabApp] Adapting to protocol v5.1 for kernel 5c7c96d0-81dc-4a97-bba0-b9f54460d199
[I 11:48:18.045 LabApp] Adapting to protocol v5.1 for kernel 87733958-6361-416a-9bbc-d49a5e214c71
```

**Comment by blink1073** [comment]
The relevant part would be before the `copy/paste this URL` part of the output.

**Comment by joonro** [comment]
Sorry, did not realize that the screen was refreshed. 

```python
$ jupyter lab >> jupyter_lab.log
[W 12:17:34.485 LabApp] Unrecognized JSON config file version, assuming version 1
[I 12:17:36.629 LabApp] The port 8888 is already in use, trying another port.
[I 12:17:36.722 LabApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 12:17:36.723 LabApp] JupyterLab alpha preview extension loaded from /home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab
JupyterLab v0.26.3
Known labextensions:
[I 12:17:36.730 LabApp] Running the core application with no additional extensions or settings
[E 12:17:36.733 LabApp] shemas_dir: /home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab/schemas
[W 12:17:36.733 LabApp] Bad message (TypeError('not all arguments converted during string formatting',)): {'created': 1501003056.7339084, 'exc_text': None, 'thread': 46912518825120, 'filename': 'extension.py', 'relativeCreated': 3534.1479778289795, 'name': 'LabApp', 'funcName': 'load_jupyter_server_extension', 'process': 44491, 'msecs': 733.9084148406982, 'module': 'extension', 'msg': 'settings_url', 'args': ('/lab/api/settings/(?P<section_name>[\\w.-]+)',), 'exc_info': None, 'levelno': 30, 'threadName': 'MainThread', 'stack_info': None, 'processName': 'MainProcess', 'pathname': '/home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab/extension.py', 'levelname': 'WARNING', 'lineno': 112}
[I 12:17:36.747 LabApp] Serving notebooks from local directory: /home/jro
[I 12:17:36.747 LabApp] 0 active kernels
[I 12:17:36.748 LabApp] The Jupyter Notebook is running at: http://localhost:8889/?token=25c418436a74cb3c741b302a0009ec24d714583c42e6f035
[I 12:17:36.748 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:17:36.757 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=25c418436a74cb3c741b302a0009ec24d714583c42e6f035
```

**Comment by blink1073** [comment]
Ugh, apologies, the code I gave you was wrong.  It should be `nbapp.log.warn('settings_url %s' % settings_url)`

**Comment by joonro** [comment]
No worries. Here is the output:

```python
$ jupyter lab >> jupyter_lab.log
[W 12:40:36.079 LabApp] Unrecognized JSON config file version, assuming version 1
[I 12:40:38.766 LabApp] The port 8888 is already in use, trying another port.
[I 12:40:38.876 LabApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 12:40:38.877 LabApp] JupyterLab alpha preview extension loaded from /home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab
JupyterLab v0.26.3
Known labextensions:
[I 12:40:38.885 LabApp] Running the core application with no additional extensions or settings
[E 12:40:38.888 LabApp] shemas_dir: /home/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab/schemas
[W 12:40:38.889 LabApp] settings_url /lab/api/settings/(?P<section_name>[\w.-]+)
[I 12:40:38.904 LabApp] Serving notebooks from local directory: /lustre/project/jro/.conda/envs/jro/lib/python3.5/site-packages/jupyterlab
[I 12:40:38.904 LabApp] 0 active kernels
[I 12:40:38.905 LabApp] The Jupyter Notebook is running at: http://localhost:8889/?token=e51429aab3f09d3aeaa34bc92c2705f54bf15263e6ac9c97
[I 12:40:38.905 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:40:38.909 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=e51429aab3f09d3aeaa34bc92c2705f54bf15263e6ac9c97
```

**Comment by blink1073** [comment]
@minrk, do you see a reason why `r'/lab/api/settings/(?P<section_name>[\w.-]+)'` would not work as a url pattern?

**Comment by blink1073** [comment]
Here's something we can try @joonro:

In your browser JavaScript console, run the following:

```javascript
var xhttp = new XMLHttpRequest();
xhttp.open("GET", "http://localhost:9000/lab/api/settings/foo", true);
xhttp.send();
```

You should see the following output on the output log on the cluster:

```
[W 09:50:19.603 LabApp] Schema not found: 'foo'
[W 09:50:19.603 LabApp] 404 GET /lab/api/settings/foo (::1) 1.04ms referer=http://localhost:8888/lab
```

**Comment by joonro** [comment]
Here is the screenshot of my Console:

![image](https://user-images.githubusercontent.com/1063143/28633365-6b24097e-71e8-11e7-9653-50d03c88e309.png)

**Comment by blink1073** [comment]
And the output from the cluster?  That's the part that should have the `Schema not found: 'foo'` output.

**Comment by joonro** [comment]
I see - I'm sorry. The only output I got is:

```
[W 16:02:39.231 LabApp] 404 GET /lab/api/settings/foo (127.0.0.1) 26.70ms referer=http://localhost:9000/lab?
[W 16:03:20.643 LabApp] 404 GET /lab/api/settings/foo (127.0.0.1) 25.49ms referer=http://localhost:9000/lab?
``` 

(I tried it twice).

**Comment by blink1073** [comment]
Okay, so it isn't related to having a `.` character in the url.  I am at a loss.

**Comment by joonro** [comment]
I created another conda environment and installed jupyter lab there, and it went back to normal. Thank you so much for your effort - I will keep the previous environment alive so please let me know if you need any other information regarding this issue.

**Comment by blink1073** [comment]
Let's chalk it up to a bad config, glad you got sorted!

**Comment by joonro** [comment]
Thank you so much for your effort again. I really appreciate it.

**Comment by minrk** [comment]
> do you see a reason why r'/lab/api/settings/(?P<section_name>[\w.-]+)' would not work as a url pattern?

Not off the top of my head, but I typically use `([^/]+)` for a url segment, since it'll catch anything before the slash.

**Comment by tobsecret** [comment]
@joonro I have a question about your cluster setup. Did you just install jupyterlab or also jupyterhub? I am asking because I cannot get it to work. I installed jupyterlab 0.31.12 on our cluster via conda. I have an ssh tunnel open to the cluster and tried to open jupyter lab.

I first got an error like mentioned in https://github.com/jupyter/notebook/issues/1318
```
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/schrat01/.conda/envs/bio/bin/jupyter-lab", line 6, in <module>
    sys.exit(jupyterlab.labapp.main())
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/notebook/notebookapp.py", line 1505, in initialize
    self.init_configurables()
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/notebook/notebookapp.py", line 1209, in init_configurables
    connection_dir=self.runtime_dir,
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/schrat01/.conda/envs/bio/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/user/2974754'
```

In response to that I ran the command as suggested:
`unset XDG_RUNTIME_DIR`

That then worked, i.e. jupyterlab started up and told me to open the following URL:

```  Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=01ad4ec845f2d92297edf84e260ec344d01ae21aed9ddc2b
START /usr/bin/firefox "http://localhost:8888/lab?token=7484e2444ddac86cba97b19a141dd0a4bb0723df5e5adc25"
Error: cannot open display: localhost:21.0
xdg-open: no method available for opening 'http://localhost:8888/lab?token=7484e2444ddac86cba97b19a141dd0a4bb0723df5e5adc25'
```
Pasting that into the browser gave me no connection though.
