### ISSUE TITLE
Installing Labextensions - Dependency Checking Bug

### ISSUE THREAD

**Issue by patrickjdwyer** [jupyterlab/jupyterlab#2811]
While trying to install the jupyterlab-hub extension, I think a may have found a couple bugs related to dependency checking.

Command: `jupyter labextension install jupyterlab-hub`

Output:

```
> npm pack jupyterlab-hub
Traceback (most recent call last):
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 57, in <listcomp>
    for arg in self.extra_args]
  File "/Users/pdwyer200/.virtualenvs/Jupyter3/lib/python3.6/site-packages/jupyterlab/commands.py", line 127, in install_extension
    raise ValueError(msg)
ValueError:
"jupyterlab-hub@0.4.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required	Actual	Package
^0.9.0  	^0.7.0	@jupyterlab/application
^0.9.0  	^0.7.0	@jupyterlab/apputils
^0.9.0  	^0.7.0	@jupyterlab/coreutils
```

I'm running the following versions:

```
jupyter lab --version
0.26.5
jupyter --version
4.3.0
```

I think there are two issues here:

1. The package version ^0.7.0 is specified as a dependency by jupyterlab-hub (I checked this by running `npm pack jupyterlab-hub`, unpacking the tarball, and looking at the package.json) and version ^0.9.0 is the one I'm actually running.  So I think the error message is printing those in the wrong order.
2. Since version 0.9.0 is greater than 0.7.0, I'd assume that jupyterlab-hub should successfully install.  So there may be an issue in the code that's checking dependencies for compatibility.

**Comment by blink1073** [comment]
Hi @patrickjdwyer, the `jupyterlab-hub` is in need of a new release.  Npm version specifiers mean that `^0.7.0` is compatible with `0.7.0 - 0.7.x`.

**Comment by patrickjdwyer** [comment]
Ah did not realize that, thanks for the info!  Still though, are the "Required" / "Actual" labels in the error message actually backwards though?  It stills seems a bit misleading to me

**Comment by blink1073** [comment]
Perhaps if those were "JupyterLab / Extension"?

**Comment by patrickjdwyer** [comment]
That makes it somewhat more clear.  Intuitively, I would think that "Required" is what the extension requires and "Actual" is what I actually have installed, but right now that's not the case and they're actually the opposite.  So even just flipping them might be something to consider, unless I'm totally misinterpreting.

**Comment by blink1073** [comment]
They're both requirements, the first column right now are those of JupyterLab and the second are those of the extension.  We are flagging the requirements that don't overlap (can't be deduplicated).
