### ISSUE TITLE
Launch failure on Windows 10 + Conda + Jupyter 4.3.0

### ISSUE THREAD

**Issue by mindbound** [jupyterlab/jupyterlab#2933]
Running `jupyter lab` fails with the following error:
```
[I 10:35:36.891 LabApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[W 10:35:36.892 LabApp] JupyterLab server extension not enabled, manually loading...
[I 10:35:36.892 LabApp] JupyterLab alpha preview extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
JupyterLab v0.27.0
Known labextensions:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-lab-script.py", line 5, in <module>
    sys.exit(jupyterlab.labapp.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1074, in initialize
    self.init_server_extensions()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 169, in init_server_extensions
    load_jupyter_server_extension(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 78, in load_jupyter_server_extension
    web_app.settings['page_config_data']['token'] = nbapp.token
AttributeError: 'LabApp' object has no attribute 'token'
```

All Conda packages have been updated to their latest versions.

**Comment by blink1073** [comment]
Hi @mindbound, what is the output of `jupyter notebook --version`?

**Comment by mindbound** [comment]
It was 4.2.3. For some reason, Anaconda didn't have it updated to the latest version. Updating it via `pip` solved it.
