### ISSUE TITLE
conflicting dependencies with jupyter_widgets

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jupyterlab/jupyterlab#3121]
I have:
python 3.6; jupyterlab 0.28.3; jupyter-nbextensions-configurator 0.2.8; ipython 6.2.1; ipywidgets                7.0.1

I launch `jupyter labextension install @jupyter-widgets/jupyterlab-manager`

I get:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
> npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-0.27.1.tgz
Traceback (most recent call last):
  File "/Users/e/anaconda3/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 168, in start
    super(LabExtensionApp, self).start()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 58, in start
    for arg in self.extra_args]
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 58, in <listcomp>
    for arg in self.extra_args]
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 126, in install_extension
    return IOLoop.instance().run_sync(func)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/e/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 188, in install_extension_async
    raise ValueError(msg)
ValueError: 
"@jupyter-widgets/jupyterlab-manager@0.27.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.11.1-0 <0.12.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/application
>=0.11.1-0 <0.12.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/notebook
>=0.11.1-0 <0.12.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/rendermime
```

**Comment by blink1073** [comment]
Hi @smartinsightsfromdata, a compatible version is coming soon: https://github.com/jupyter-widgets/ipywidgets/pull/1761.

**Comment by smartinsightsfromdata** [comment]
Thanks @blink1073

**Comment by blink1073** [comment]
I just confirmed that `jupyter labextension install @jupyter-widgets/jupyterlab-manager` now works with 0.28.  Cheers!
