### ISSUE TITLE
module 'site' has no attribute 'getuserbase'

### ISSUE THREAD

**Issue by eliorc** [jupyterlab/jupyterlab#3125]
Really simple flow, first i 

`virtualenv jupyterlab -p python3`

Then, as documentation says:

`pip install jupyterlab`
`jupyter serverextension enable --py jupyterlab --sys-prefix`

Then I tried launching using `jupyter lab` and I get the following:
`[W 21:56:35.947 LabApp] JupyterLab server extension not enabled, manually loading...
[I 21:56:35.947 LabApp] JupyterLab alpha preview extension loaded from /home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/jupyterlab
Traceback (most recent call last):
  File "/home/elior/VirtualEnvs/jupyterlab/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/notebook/notebookapp.py", line 1371, in initialize
    self.init_server_extensions()
  File "/home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/jupyterlab/labapp.py", line 176, in init_server_extensions
    load_jupyter_server_extension(self)
  File "/home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/jupyterlab/extension.py", line 48, in load_jupyter_server_extension
    app_dir = get_app_dir()
  File "/home/elior/VirtualEnvs/jupyterlab/lib/python3.6/site-packages/jupyterlab/commands.py", line 54, in get_app_dir
    if here.startswith(site.getuserbase()):
AttributeError: module 'site' has no attribute 'getuserbase'
`

I'm on Fedora 26, Python 3.6

**Comment by blink1073** [comment]
That's odd, it should be part of the standard lib: https://docs.python.org/3/library/site.html#site.getuserbase.   I'll add a guard around it.

**Comment by lampts** [comment]
I got the same on python 2.7.
[W 09:42:13.149 LabApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "python2.7/site-packages/notebook/notebookapp.py", line 1346, in init_server_extensions
        func(self)
      File "/python2.7/site-packages/jupyterlab/extension.py", line 48, in load_jupyter_server_extension
        app_dir = get_app_dir()
      File "/python2.7/site-packages/jupyterlab/commands.py", line 54, in get_app_dir
        if here.startswith(site.getuserbase()):
    AttributeError: 'module' object has no attribute 'getuserbase'

**Comment by kiendang** [comment]
Ran into this today. This is a known issue in `virtualenv` pypa/virtualenv#355.

**Comment by nicolasfguillaume** [comment]
Hi,

I ran into the same issue (Python 2.7.12 on macOS). Then I edited the file `lib/python2.7/site-packages/jupyterlab/commands.py` and in function `get_app_dir` (line 43), i replaced 

```
if here.startswith(site.getuserbase()):
         app_dir = pjoin(site.getuserbase(), 'share', 'jupyter', 'lab')
```

by

```
if here.startswith(site.USER_BASE):
        app_dir = pjoin(site.USER_BASE, 'share', 'jupyter', 'lab')
```
And I was able to start Jupyter Lab !

**Comment by blink1073** [comment]
v0.28.5, and this worked for me on macOS 10.13:

```bash
virtualenv jupyterlab -p /usr/bin/python
cd jupyterlab
source bin/activate
pip install jupyterlab
jupyter lab
```
