### ISSUE TITLE
cannot install nbwidgets 

### ISSUE THREAD

**Issue by AugustoYao** [jupyterlab/jupyterlab#3274]
I installed jupyterlab with conda. Now, installation of nbwidgets failed. Details are shown below. Could someone help me on this ?

`[jhyao@sdd002023 ~]$ jupyter labextension install @jupyterlab/nbwidgets
> node node-version-check.js
> npm pack @jupyterlab/nbwidgets
jupyterlab-nbwidgets-0.21.0.tgz
Traceback (most recent call last):
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/bin/jupyter-labextension", line 6, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 174, in start
    super(LabExtensionApp, self).start()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 64, in start
    for arg in self.extra_args]
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 64, in <listcomp>
    for arg in self.extra_args]
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/commands.py", line 137, in install_extension
    return IOLoop.instance().run_sync(func)
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/commands.py", line 208, in install_extension_async
    raise ValueError(msg)
ValueError:
"@jupyterlab/nbwidgets@0.21.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.12.0-0 <0.13.0-0    >=0.7.0-0 <0.8.0-0   @jupyterlab/application
>=0.12.0-0 <0.13.0-0    >=0.7.0-0 <0.8.0-0   @jupyterlab/notebook
>=0.12.0-0 <0.13.0-0    >=0.7.0-0 <0.8.0-0   @jupyterlab/rendermime

[jhyao@sdd002023 ~]$ jupyter labextension list
`JupyterLab v0.29.2
Known labextensions:
   app dir: /disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.30.1  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.6.0  enabled  OK
jupyterlab_bokeh
        jupyterlab_bokeh v0.1.0  enabled  OK
`

**Comment by blink1073** [comment]
Hi @AugustoYao, the name of the package has changed:  `jupyter labextension install @jupyter-widgets/jupyterlab-manager`.  

cf https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager#jupyter-widgets-jupyterlab-extension

**Comment by AugustoYao** [comment]
@blink1073  Thank you very much.
