### ISSUE TITLE
Extension link failure

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#3279]
I am getting an error on master when running `jupyter labextension link .`:
```bash
> /home/ian/anaconda3/envs/jupyter/bin/jlpm pack .
yarn pack v1.3.2
error Couldn't find a package.json file in "/tmp/tmp96ed_isl"
info Visit https://yarnpkg.com/en/docs/cli/pack for documentation about this command.
Traceback (most recent call last):
  File "/home/ian/anaconda3/envs/jupyter/bin/jupyter-labextension", line 11, in <module>
    load_entry_point('jupyterlab', 'console_scripts', 'jupyter-labextension')()
  File "/home/ian/anaconda3/envs/jupyter/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/ian/anaconda3/envs/jupyter/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ian/jupyter/jupyterlab/jupyterlab/labextensions.py", line 179, in start
    super(LabExtensionApp, self).start()
  File "/home/ian/anaconda3/envs/jupyter/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/ian/jupyter/jupyterlab/jupyterlab/labextensions.py", line 94, in start
    for arg in self.extra_args]
  File "/home/ian/jupyter/jupyterlab/jupyterlab/labextensions.py", line 94, in <listcomp>
    for arg in self.extra_args]
  File "/home/ian/jupyter/jupyterlab/jupyterlab/commands.py", line 204, in link_package
    handler.link_package(path)
  File "/home/ian/jupyter/jupyterlab/jupyterlab/commands.py", line 469, in link_package
    info = self._extract_package(path, tempdir)
  File "/home/ian/jupyter/jupyterlab/jupyterlab/commands.py", line 953, in _extract_package
    raise ValueError('Extension failed to pack')
ValueError: Extension failed to pack
```

**Comment by ian-r-rose** [comment]
Probably related to https://github.com/jupyterlab/jupyterlab/issues/3212#issuecomment-346862846

**Comment by gnestor** [comment]
I'm seeing this too on master.

I am also not able to get lab to work outside of dev-mode. When I open lab in the browser in regular mode, I see:

```
Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
    at <anonymous>:21:35
main.bundle.js:144445 Loading shortcut settings failed. errors.forEach is not a function
(anonymous) @ main.bundle.js:144445
main.bundle.js:141380 errors.forEach is not a function
(anonymous) @ main.bundle.js:141380
main.bundle.js:139562 errors.forEach is not a function
(anonymous) @ main.bundle.js:139562
main.bundle.js:158727 Uncaught (in promise) TypeError: errors.forEach is not a function
    at main.bundle.js:158727
    at <anonymous>
```

I also notice that when I refresh the browser tab, it triggers a rebuild on the server:

```
[W 09:19:20.076 LabApp] Build recommended
[W 09:19:20.077 LabApp] @jupyterlab/geojson-extension content changed
[W 09:19:20.077 LabApp] @jupyterlab/plotly-extension content changed
[W 09:19:20.077 LabApp] @jupyterlab/katex-extension content changed
[W 09:19:20.077 LabApp] @jupyterlab/fasta-extension content changed
```

I tried uninstalling and unlinking all extensions and I'm still seeing this.

**Comment by blink1073** [comment]
@gnestor, I suspect #3270 will fix that.

**Comment by gnestor** [comment]
That's what I figured 👍

**Comment by blink1073** [comment]
@gnestor, Darian and I figured out what the problem is.  Until we release 0.30, dev mode and core mode require different versions of JuptyerLab launcher because of the backwards incompatible changes to settings.  Mind opening that as a separate issue tagged for 0.30 (which I'm about to make)?
