### ISSUE TITLE
Error using terminal on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3286]
I thought I'd try out the brand new terminal support on Windows but ran into an exception:
```
[I 16:31:17.153 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda3\lib\site-packages\winpty\ptyprocess.py", line 315, in _read_in_thread
    data = pty.read(4096)
  File "C:\Miniconda3\lib\site-packages\winpty\winpty_wrapper.py", line 67, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000

[I 16:31:17.182 LabApp] EOF on FD 1084; stopping reading
[I 16:31:17.383 LabApp] Terminal 1 closed
[E 16:31:17.384 LabApp] Uncaught exception in /terminals/websocket/1
    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\tornado\websocket.py", line 494, in _run_callback
        result = callback(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\terminado\websocket.py", line 84, in on_message
        self.terminal.resize_to_smallest()
      File "C:\Miniconda3\lib\site-packages\terminado\management.py", line 63, in resize_to_smallest
        self.ptyproc.setwinsize(minrows, mincols)
      File "C:\Miniconda3\lib\site-packages\winpty\ptyprocess.py", line 305, in setwinsize
        self.pty.set_size(cols, rows)
    AttributeError: 'NoneType' object has no attribute 'set_size'
Websocket closed
```
![image](https://user-images.githubusercontent.com/881019/33305496-0343ec28-d45a-11e7-9d87-256858e5198b.png)

packages:
```
jupyterlab                0.29.2                   py36_0    conda-forge
terminado                 0.8                      py36_0    conda-forge
pywinpty                  0.4.1                    py36_0    conda-forge
notebook                  5.2.1            py36h4fb2ca6_0    https://repo.continuum.io/pkgs/main
```

**Comment by dhirschfeld** [comment]
Right, obviously needs at least jupyter/notebook#3087. I jumped the gun as I saw Steve post some screenshots so wanted to try it out myself!

Will wait for everything to be released before testing further...
