### ISSUE TITLE
Lab failing outside of dev-mode

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#3297]
I am not able to get lab to work outside of dev-mode. When I open lab in the browser in regular mode, I see:

```
Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
    at <anonymous>:21:35
main.bundle.js:144445 Loading shortcut settings failed. errors.forEach is not a function
(anonymous) @ main.bundle.js:144445
main.bundle.js:141380 errors.forEach is not a function
(anonymous) @ main.bundle.js:141380
main.bundle.js:139562 errors.forEach is not a function
(anonymous) @ main.bundle.js:139562
main.bundle.js:158727 Uncaught (in promise) TypeError: errors.forEach is not a function
    at main.bundle.js:158727
    at <anonymous>
```

I also notice that when I refresh the browser tab, it triggers a rebuild on the server:

```
[W 09:19:20.076 LabApp] Build recommended
[W 09:19:20.077 LabApp] @jupyterlab/geojson-extension content changed
[W 09:19:20.077 LabApp] @jupyterlab/plotly-extension content changed
[W 09:19:20.077 LabApp] @jupyterlab/katex-extension content changed
[W 09:19:20.077 LabApp] @jupyterlab/fasta-extension content changed
```

I tried uninstalling and unlinking all extensions and I'm still seeing this. 

Additionally, I am getting errors when trying to link extensions: 

```
$ jupyter labextension link packages/geojson-extension/
> /usr/local/bin/npm pack packages/geojson-extension/
npm ERR! code ENOLOCAL
npm ERR! Could not install from "packages/geojson-extension" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/grant/.npm/_logs/2017-12-01T03_40_03_330Z-debug.log
Traceback (most recent call last):
  File "/Users/grant/anaconda/bin/jupyter-labextension", line 11, in <module>
    load_entry_point('jupyterlab', 'console_scripts', 'jupyter-labextension')()
  File "/Users/grant/anaconda/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/grant/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 179, in start
    super(LabExtensionApp, self).start()
  File "/Users/grant/anaconda/lib/python3.5/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 94, in start
    for arg in self.extra_args]
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 94, in <listcomp>
    for arg in self.extra_args]
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/commands.py", line 204, in link_package
    handler.link_package(path)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/commands.py", line 469, in link_package
    info = self._extract_package(path, tempdir)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/commands.py", line 953, in _extract_package
    raise ValueError('Extension failed to pack')
ValueError: Extension failed to pack
```

**Comment by blink1073** [comment]
Both are fixed in master.
