### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3353]
On my newly built container with jupyterlab 0.30.5, when I start jupyterlab it brings up the build dialog however the build fails and the dialog comes up again.

There are two suspicious entries in the output:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab%2fapplication:
self signed certificate in certificate chain".
```
and
```
$ webpack --define process.env.NODE_ENV="'production'"
'webpack' is not recognized as an internal or external command,
```

I haven't specifically installed `webpack` - just `nodejs` from conda-forge.

Any ideas how to resolve this?

```
[W 20:40:25.833 LabApp] Build recommended
[W 20:40:25.833 LabApp] jupyter-matplotlib needs to be included
[W 20:40:25.833 LabApp] @jupyter-widgets/jupyterlab-manager needs to be included
[W 20:40:25.833 LabApp] @jupyterlab/hub-extension needs to be included
[W 20:40:25.834 LabApp] @jupyterlab/geojson-extension needs to be included
[W 20:40:25.834 LabApp] @jupyterlab/plotly-extension needs to be included
[W 20:40:25.834 LabApp] @jupyterlab/vega3-extension needs to be included
[W 20:40:25.834 LabApp] jupyterlab_bokeh needs to be included
[I 20:40:43.293 LabApp] > node C:\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab%2fapplication: self signed certificate in certificate chain".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Miniconda3\\share\\jupyter\\lab\\staging\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[I 20:40:45.308 LabApp] > node C:\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --define process.env.NODE_ENV="'production'"
'webpack' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**`yarn-error.log`:**
```
Arguments:
  C:\Miniconda3\node.exe C:\Miniconda3\share\jupyter\lab\staging\yarn.js install

PATH:
  C:\Miniconda3;C:\Miniconda3\Library\mingw-w64\bin;C:\Miniconda3\Library\usr\bin;C:\Miniconda3\Library\bin;C:\Miniconda3\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\oracle\instantclient_11_2;

Yarn version:
  1.3.2

Node version:
  6.12.0

Platform:
  win32 x64

npm manifest:
  {
      "name": "@jupyterlab/application-top",
      "version": "0.13.0",
      "private": true,
      "scripts": {
          "build": "webpack",
          "build:prod": "webpack --define process.env.NODE_ENV=\"'production'\"",
          "clean": "rimraf build",
          "prepublishOnly": "npm run build",
          "watch": "webpack --watch"
      },
      "dependencies": {
          "@jupyterlab/application": "^0.13.1",
          "@jupyterlab/application-extension": "^0.13.0",
          "@jupyterlab/apputils": "^0.13.1",
          "@jupyterlab/apputils-extension": "^0.13.0",
          "@jupyterlab/cells": "^0.13.0",
          "@jupyterlab/codeeditor": "^0.13.0",
          "@jupyterlab/codemirror": "^0.13.0",
          "@jupyterlab/codemirror-extension": "^0.13.0",
          "@jupyterlab/completer": "^0.13.0",
          "@jupyterlab/completer-extension": "^0.13.0",
          "@jupyterlab/console": "^0.13.0",
          "@jupyterlab/console-extension": "^0.13.0",
          "@jupyterlab/coreutils": "^0.13.0",
          "@jupyterlab/csvviewer": "^0.13.0",
          "@jupyterlab/csvviewer-extension": "^0.13.0",
          "@jupyterlab/docmanager": "^0.13.0",
          "@jupyterlab/docmanager-extension": "^0.13.0",
          "@jupyterlab/docregistry": "^0.13.0",
          "@jupyterlab/faq-extension": "^0.13.0",
          "@jupyterlab/filebrowser": "^0.13.2",
          "@jupyterlab/filebrowser-extension": "^0.13.0",
          "@jupyterlab/fileeditor": "^0.13.0",
          "@jupyterlab/fileeditor-extension": "^0.13.0",
          "@jupyterlab/help-extension": "^0.13.0",
          "@jupyterlab/imageviewer": "^0.13.0",
          "@jupyterlab/imageviewer-extension": "^0.13.0",
          "@jupyterlab/inspector": "^0.13.0",
          "@jupyterlab/inspector-extension": "^0.13.0",
          "@jupyterlab/json-extension": "^0.13.0",
          "@jupyterlab/launcher": "^0.13.2",
          "@jupyterlab/launcher-extension": "^0.13.0",
          "@jupyterlab/mainmenu": "^0.2.0",
          "@jupyterlab/mainmenu-extension": "^0.2.0",
          "@jupyterlab/markdownviewer-extension": "^0.13.0",
          "@jupyterlab/notebook": "^0.13.0",
          "@jupyterlab/notebook-extension": "^0.13.0",
          "@jupyterlab/observables": "^0.2.0",
          "@jupyterlab/outputarea": "^0.13.1",
          "@jupyterlab/pdf-extension": "^0.5.0",
          "@jupyterlab/rendermime": "^0.13.0",
          "@jupyterlab/rendermime-interfaces": "^0.4.3",
          "@jupyterlab/running": "^0.13.0",
          "@jupyterlab/running-extension": "^0.13.0",
          "@jupyterlab/services": "^0.52.0",
          "@jupyterlab/settingeditor": "^0.2.0",
          "@jupyterlab/settingeditor-extension": "^0.8.0",
          "@jupyterlab/shortcuts-extension": "^0.13.0",
          "@jupyterlab/tabmanager-extension": "^0.13.0",
          "@jupyterlab/terminal": "^0.13.0",
          "@jupyterlab/terminal-extension": "^0.13.0",
          "@jupyterlab/theme-dark-extension": "^0.13.0",
          "@jupyterlab/theme-light-extension": "^0.13.0",
          "@jupyterlab/tooltip": "^0.13.0",
          "@jupyterlab/tooltip-extension": "^0.13.0",
          "@jupyterlab/vdom-extension": "^0.13.0",
          "@jupyterlab/vega2-extension": "^0.13.0",
          "@phosphor/coreutils": "^1.3.0",
          "@phosphor/widgets": "^1.5.0",
          "jupyter-matplotlib": "file:../extensions/jupyter-matplotlib-0.3.0.tgz",
          "@jupyter-widgets/jupyterlab-manager": "file:../extensions/jupyter-widgets-jupyterlab-manager-0.31.3.tgz",
          "@jupyterlab/geojson-extension": "file:../extensions/jupyterlab-geojson-extension-0.13.0.tgz",
          "@jupyterlab/hub-extension": "file:../extensions/jupyterlab-hub-extension-0.7.0.tgz",
          "@jupyterlab/plotly-extension": "file:../extensions/jupyterlab-plotly-extension-0.13.0.tgz",
          "@jupyterlab/vega3-extension": "file:../extensions/jupyterlab-vega3-extension-0.13.0.tgz",
          "jupyterlab_bokeh": "file:../extensions/jupyterlab_bokeh-0.1.0.tgz"
      },
      "devDependencies": {
          "@jupyterlab/buildutils": "^0.4.0",
          "css-loader": "~0.28.7",
          "file-loader": "~0.10.1",
          "fs-extra": "~4.0.2",
          "glob": "~7.1.2",
          "handlebars": "~4.0.11",
          "json-loader": "~0.5.7",
          "raw-loader": "~0.5.1",
          "rimraf": "~2.6.2",
          "sort-package-json": "~1.7.1",
          "source-map-loader": "~0.2.1",
          "style-loader": "~0.13.2",
          "url-loader": "~0.5.9",
          "webpack": "~2.7.0"
      },
      "jupyterlab": {
          "extensions": {
              "@jupyterlab/application-extension": "",
              "@jupyterlab/apputils-extension": "",
              "@jupyterlab/codemirror-extension": "",
              "@jupyterlab/completer-extension": "",
              "@jupyterlab/console-extension": "",
              "@jupyterlab/csvviewer-extension": "",
              "@jupyterlab/docmanager-extension": "",
              "@jupyterlab/faq-extension": "",
              "@jupyterlab/filebrowser-extension": "",
              "@jupyterlab/fileeditor-extension": "",
              "@jupyterlab/help-extension": "",
              "@jupyterlab/imageviewer-extension": "",
              "@jupyterlab/inspector-extension": "",
              "@jupyterlab/launcher-extension": "",
              "@jupyterlab/mainmenu-extension": "",
              "@jupyterlab/markdownviewer-extension": "",
              "@jupyterlab/notebook-extension": "",
              "@jupyterlab/running-extension": "",
              "@jupyterlab/settingeditor-extension": "",
              "@jupyterlab/shortcuts-extension": "",
              "@jupyterlab/tabmanager-extension": "",
              "@jupyterlab/terminal-extension": "",
              "@jupyterlab/theme-dark-extension": "",
              "@jupyterlab/theme-light-extension": "",
              "@jupyterlab/tooltip-extension": "",
              "jupyter-matplotlib": "src/lab_extension",
              "@jupyter-widgets/jupyterlab-manager": "",
              "@jupyterlab/hub-extension": ""
          },
          "mimeExtensions": {
              "@jupyterlab/json-extension": "",
              "@jupyterlab/pdf-extension": "",
              "@jupyterlab/vdom-extension": "",
              "@jupyterlab/vega2-extension": "",
              "@jupyterlab/geojson-extension": "",
              "@jupyterlab/plotly-extension": "",
              "@jupyterlab/vega3-extension": "",
              "jupyterlab_bokeh": ""
          },
          "name": "JupyterLab",
          "outputDir": "..",
          "singletonPackages": [
              "@jupyterlab/application",
              "@jupyterlab/apputils",
              "@jupyterlab/console",
              "@jupyterlab/coreutils",
              "@jupyterlab/docmanager",
              "@jupyterlab/filebrowser",
              "@jupyterlab/fileeditor",
              "@jupyterlab/imageviewer",
              "@jupyterlab/launcher",
              "@jupyterlab/notebook",
              "@jupyterlab/rendermime",
              "@jupyterlab/rendermime-interfaces",
              "@jupyterlab/services",
              "@jupyterlab/terminal",
              "@jupyterlab/tooltip",
              "@phosphor/coreutils",
              "@phosphor/widgets"
          ],
          "version": "0.30.5",
          "linkedPackages": {},
          "staticDir": "../static"
      }
  }

yarn manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: self signed certificate in certificate chain
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:610:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

**Comment by dhirschfeld** [comment]
...I also don't have yarn installed - is that a requirement now for building jupyterlab?

**Comment by blink1073** [comment]
You don't need `yarn`, only node 4+.  The issue there is the lack of a `yarn.lock` file to start.  I see where the bug is and will put out a patch release.

**Comment by blink1073** [comment]
Thanks for catching all our build system :bug: :bug:, @dhirschfeld!
