### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3364]
...so, I'm still having problems building. I'm pretty sure this is just my needing to  configure our proxy correctly so this is mostly for my own reference. 

It looks yarn/npm doesn't respect `HTTPS_PROXY` env var? Also concerned about the `'webpack' is not recognized` error though.
```
Step 12/21 : RUN Start-Process jupyter -ArgumentList 'lab','build' -NoNewWindow -Wait;
 ---> Running in 95262de52606
> node C:\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyter-widgets%2fbase: read ECONNRESET".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Miniconda3\\share\\jupyter\\lab\\staging\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:568:26)
Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:568:26)
Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:568:26)
> node C:\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --define process.env.NODE_ENV="'production'"
'webpack' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Removing intermediate container 95262de52606
```

**Comment by blink1073** [comment]
Looks like this was fixed recently in yarn master but is not yet released: https://github.com/yarnpkg/yarn/pull/4903.

**Comment by blink1073** [comment]
IIUC the workaround is to create a `~/.yarnrc` with the config values: https://github.com/yarnpkg/yarn/issues/4546#issuecomment-332835946

**Comment by dhirschfeld** [comment]
One thing I don't understand is that I haven't got yarn installed. Is it just downloaded on the fly as part of the build?

I'll try the `.yarnrc` route and report back...

**Comment by blink1073** [comment]
We provide a local copy of yarn now, which once we get these bugs ironed out will be a good thing for consistency and reproducibility.

**Comment by dhirschfeld** [comment]
Documentation on the exact format seems a bit  sparse/contradictory. What worked for me was:

**`.yarnrc`**
```
https-proxy "http://username:password@proxy.address.com:port"
strict-ssl false
```
Note no `=` sign in there and quotes around the address.

Obviously that may be different on non-Windows platforms

**Comment by dhirschfeld** [comment]
I'm not sure if this worked or not?! Checking the image now...
```
Step 13/22 : RUN Start-Process jupyter -ArgumentList 'lab','build' -NoNewWindow -Wait;
 ---> Running in 1760aee0fd3b
> node C:\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-supported@1.2.0: This package has been moved to @mapbox/mapbox-gl-supported
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vt-pbf > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
warning @jupyterlab/plotly-extension > plotly.js > color-rgba > color-space > husl@5.0.3: Project renamed to HSLuv
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "C:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: C:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas\nOutput:\nC:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Miniconda3\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.12.0 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Python executable \"C:\\Miniconda3\\python.EXE\" is v3.6.3, which is not supported by gyp.\ngyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.\ngyp ERR! stack     at failPythonVersion (C:\\Miniconda3\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:454:14)\ngyp ERR! stack     at C:\\Miniconda3\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:443:9\ngyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at maybeClose (internal/child_process.js:920:16)\ngyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:351:11)\ngyp ERR! stack     at emitOne (events.js:96:13)\ngyp ERR! stack     at Socket.emit (events.js:188:7)\ngyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)\ngyp ERR! System Windows_NT 10.0.16299\ngyp ERR! command \"C:\\\\Miniconda3\\\\node.exe\" \"C:\\\\Miniconda3\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"\ngyp ERR! cwd C:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas\ngyp ERR! node -v v6.12.0\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "C:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\vega-wordcloud\\node_modules\\canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: C:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\vega-wordcloud\\node_modules\\canvas\nOutput:\nC:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\vega-wordcloud\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Miniconda3\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.12.0 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Python executable \"C:\\Miniconda3\\python.EXE\" is v3.6.3, which is not supported by gyp.\ngyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.\ngyp ERR! stack     at failPythonVersion (C:\\Miniconda3\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:454:14)\ngyp ERR! stack     at C:\\Miniconda3\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:443:9\ngyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at maybeClose (internal/child_process.js:920:16)\ngyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:351:11)\ngyp ERR! stack     at emitOne (events.js:96:13)\ngyp ERR! stack     at Socket.emit (events.js:188:7)\ngyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)\ngyp ERR! System Windows_NT 10.0.16299\ngyp ERR! command \"C:\\\\Miniconda3\\\\node.exe\" \"C:\\\\Miniconda3\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"\ngyp ERR! cwd C:\\Miniconda3\\share\\jupyter\\lab\\staging\\node_modules\\vega-wordcloud\\node_modules\\canvas\ngyp ERR! node -v v6.12.0\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
Done in 297.62s.
> node C:\Miniconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --define process.env.NODE_ENV="'production'"
Hash: f93e6b3dbdf61fd6dd3c
Version: webpack 2.7.0
Time: 23163ms
                                 Asset       Size  Chunks                    Chunk Names
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
  a6137456ed160d7606981aa57c559898.png  696 bytes          [emitted]
  2273e3d8ad9264b7daa5bdbf8e6b47f8.png    1.47 kB          [emitted]
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
  4f0283c6ce28e888000e978e537a6a56.png    1.26 kB          [emitted]
                           0.bundle.js     260 kB       0  [emitted]  [big]  @jupyter-widgets/controls
                           1.bundle.js     890 kB       1  [emitted]  [big]
                        main.bundle.js    15.4 MB       2  [emitted]  [big]  main
                       0.bundle.js.map     307 kB       0  [emitted]         @jupyter-widgets/controls
                       1.bundle.js.map    1.08 MB       1  [emitted]
                    main.bundle.js.map    17.4 MB       2  [emitted]         main
  [40] ./~/@jupyterlab/application/lib/index.js 5.64 kB {2} [built]
 [935] ./~/@jupyter-widgets/jupyterlab-manager/lib/index.js 252 bytes {2} [optional] [built]
 [956] ./~/@jupyterlab/pdf-extension/lib/index.js 4.96 kB {2} [optional] [built]
 [962] ./~/@jupyterlab/terminal-extension/lib/index.js 7.41 kB {2} [optional] [built]
 [963] ./~/@jupyterlab/theme-dark-extension/lib/index.js 969 bytes {2} [optional] [built]
 [964] ./~/@jupyterlab/theme-light-extension/lib/index.js 940 bytes {2} [optional] [built]
 [965] ./~/@jupyterlab/tooltip-extension/lib/index.js 5.57 kB {2} [optional] [built]
 [966] ./~/@jupyterlab/vdom-extension/lib/index.js 2.95 kB {2} [optional] [built]
 [967] ./~/@jupyterlab/vega2-extension/lib/index.js 6.17 kB {2} [optional] [built]
 [968] ./~/@jupyterlab/vega3-extension/lib/index.js 3.94 kB {2} [optional] [built]
 [969] ./~/es6-promise/auto.js 179 bytes {2} [built]
 [970] ./~/jupyter-matplotlib/src/lab_extension.js 434 bytes {2} [optional] [built]
 [971] ./~/jupyterlab_bokeh/lib/index.js 3.91 kB {2} [optional] [built]
 [972] ./~/font-awesome/css/font-awesome.min.css 892 bytes {2} [built]
[1897] ./build/index.out.js 45.8 kB {2} [built]
    + 2469 hidden modules
Done in 25.96s.
Removing intermediate container 1760aee0fd3b
```

**Comment by dhirschfeld** [comment]
Seems the errors weren't important as everything seems to be working!

Thanks for you help sorting it out @blink1073!

**Comment by blink1073** [comment]
Yep, once https://github.com/yarnpkg/yarn/issues/4876 is fixed we can use `--ignore-optional` and avoid those nasty looking errors that aren't really errors.   Glad you got sorted!

**Comment by blink1073** [comment]
I'm going to leave this open until we have a final solution for this.

**Comment by cmprince** [comment]
Just wanted to add that I just used this to cure my install on a cntlm-enabled proxy, setting my `.yarnrc` to:

`https-proxy "http://localhost:3128"`
`strict-ssl false`

**Comment by jasongrout** [comment]
> Yep, once [yarnpkg/yarn#4876](https://github.com/yarnpkg/yarn/issues/4876) is fixed we can use `--ignore-optional` and avoid those nasty looking errors that aren't really errors. Glad you got sorted!

Looks like that issue is fixed now.
