### ISSUE TITLE
Error with pip install -e .

### ISSUE THREAD

**Issue by davidrthorn** [jupyterlab/jupyterlab#3566]
I get the following error when trying to install with pip install -e .

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/david/Github/jupyterlab/setup.py", line 163, in <module>
        setup(**setup_args)
      File "/home/david/.miniconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/david/.miniconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/david/.miniconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/david/.miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/david/Github/jupyterlab/setup.py", line 92, in run
        run(npm, cwd=HERE)
      File "/home/david/Github/jupyterlab/setupbase.py", line 216, in run
        return subprocess.check_call(cmd, **kwargs)
      File "/home/david/.miniconda3/lib/python3.6/subprocess.py", line 286, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/home/david/.miniconda3/lib/python3.6/subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/home/david/.miniconda3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/david/.miniconda3/lib/python3.6/subprocess.py", line 1258, in _execute_child
        executable = os.fsencode(executable)
      File "/home/david/.miniconda3/lib/python3.6/os.py", line 800, in fsencode
        filename = fspath(filename)  # Does type-checking of `filename`.
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
And then...

`Command "/home/david/.miniconda3/bin/python -c "import setuptools, tokenize;__file__='/home/david/Github/jupyterlab/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/david/Github/jupyterlab/`

I'm running Xubuntu 16.04 and pip 9.0.1.
I've tried:

- installing with pip3 instead of pip
- installing as root
- re-cloning the repository 
- reinstallling miniconda
- updating setuptools with pip install --update setuptools

**Comment by blink1073** [comment]
Hi @davidrthorn, I suspect you don't have `npm` installed.  We should catch that fact in `setup.py`.

**Comment by blink1073** [comment]
You can install it as `conda install nodejs`

**Comment by davidrthorn** [comment]
I swore I'd tried that, but obviously not. Working now, thanks!
