### ISSUE TITLE
[W 12:34:26.947 LabApp] WebSocket ping timeout after 133941 ms.

### ISSUE THREAD

**Issue by dbl001** [jupyterlab/jupyterlab#3598]
I'm running Jupyter Lab alpha release version: 0.30.6
on OS X 10.11.6.
Python 3.6
Tensorflow 1.4.0

```
[W 12:34:26.947 LabApp] WebSocket ping timeout after 133941 ms.
E 12:34:27.165 LabApp] Uncaught exception GET /api/kernels/ada6afb4-5400-420a-868f-23a806f9862a/channels?session_id=4404100fae889c718b9bff1bb42d5c85&token=2687f21698eda71dfe2f9e93f423543f5054f1935b6a7648 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/ada6afb4-5400-420a-868f-23a806f9862a/channels?session_id=4404100fae889c718b9bff1bb42d5c85&token=2687f21698eda71dfe2f9e93f423543f5054f1935b6a7648', version='HTTP/1.1', remote_ip='::1', headers={'Cookie': '_xsrf=2|44f7e5e5|e8cc739d1fadd41732a2b166fbb5e873|1515610400; username-localhost-8888="2|1:0|10:1515610481|23:username-localhost-8888|44:OGU2OGYyYTI3YTg4NGU4YWI1OWM4OTQwY2RjYTk3Zjc=|350699e501993dbbc11a337a42abc292cbb45e56fe2e80f813de6eab0a7c2ddf"', 'Sec-Websocket-Key': 'TtAgczA/Lfw/dLIBEMuJjg==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7', 'Host': 'localhost:8888', 'Origin': 'http://localhost:8888', 'Pragma': 'no-cache', 'Upgrade': 'websocket', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'Connection': 'Upgrade', 'Sec-Websocket-Version': '13', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 373, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/websocket.py", line 213, in write_message
        raise WebSocketClosedError()
    WebSocketClosedError
[W 12:34:27.335 LabApp] zmq message arrived on closed channel
[I 12:34:28.343 LabApp] Adapting to protocol v5.1 for kernel ada6afb4-5400-420a-868f-23a806f9862a
```

I WebSocket ping timeout on Jupyter notebook as well.

These have been reported in Jupyter:

https://github.com/jupyter/notebook/issues/1164

https://github.com/jupyter/notebook/issues/1474

https://github.com/jupyterhub/jupyterhub/issues/248

**Comment by blink1073** [comment]
Thanks @dbl001, let's leave this open as a reference to https://github.com/jupyter/notebook/issues/1164.

**Comment by jamartinh** [comment]
Same Issue here :(

**Comment by dbl001** [comment]
I discovered that if you simply refresh the page, it doesn’t disturb the kernel, and that JupyterLab can reconnect to the kernel.

**Comment by jamartinh** [comment]
Ok, thanks I will try.
Jose

**Comment by H3yfinn** [comment]
Would using Tmux or nohup work in this case? 
Or is the problem the loss of connection between Jupyter notebook and the server connecting to Notebook (in which case putting the app in background [nohup functionality] will not stop Jupyter from complaining about losing connection to the server)?
Willing to try it out if someone with domain knowledge confirms it could work.

**Comment by dbl001** [comment]
How does the Jupyter process monitor the connection state of the kernel (in this instance Python 3.6)?
Is it a socket?
Does the web socket timeout indicate there was a KEEP ALIVE timeout exception?

Keras and/or Tensorflow are running in these kernels, at high CPU/GPU usage levels.
Perhaps the kernel is ignoring Jupyter’s probes.

**Comment by blink1073** [comment]
@minrk, thoughts on the above?

**Comment by minrk** [comment]
This is the websocket ping between the notebook server and the browser, the Kernel isn't involved except in consuming general computer resources. I have a hard time seeing how the kernel could delay a websocket message between two other processes for *two minutes*.

Are you running any proxy in fromt of Jupyter (e.g. JupyterHub and/or nginx)?

**Comment by dbl001** [comment]
No, I’m not running any proxy.  
After the web socket timeout, output from the kernel process is not longer displayed in JupyterLab and no further commands work.
If I refresh the web page in the browser, JupyterLab reconnects to the kernel, I can access all the variables in the kernel process and further commands work.

**Comment by dbl001** [comment]
https://github.com/jupyter/notebook/issues/1474

**Comment by andybrnr** [comment]
I'm encountering a similar issue running Jupyter Lab on an AWS EC2 instance. Because it's running on a private subnet in a VPC, need to access via a proxy with NGINX. Set the NGINX timeout to 30mins, but on queries against Redshift that take longer than 3 mins to complete, it'll hang. If instead I run in the "Classic" notebook, no hang and completes without issue. Not sure if there's a way to get better logging to understand this?

**Comment by blink1073** [comment]
Does running `Reconnect to Kernel` in the command palette resolve the issue?

**Comment by dbl001** [comment]
Reconnect to Kernel in the command palette does not appear to help.
…


[I 10:26:53.995 LabApp] Saving file at /examples/Untitled9.ipynb
[W 10:35:46.074 LabApp] WebSocket ping timeout after 136281 ms.
[W 10:35:46.407 LabApp] WebSocket ping timeout after 136592 ms.
[W 10:35:46.419 LabApp] WebSocket ping timeout after 136892 ms.
[W 10:35:46.421 LabApp] WebSocket ping timeout after 136895 ms.
[W 10:36:32.279 LabApp] Replacing stale connection: b21539e4-c622-49d0-b38b-5de33c575d63:f48abbc0aa9a367af4ddbf5c4d7ec2ac
[W 10:36:32.285 LabApp] Replacing stale connection: b21539e4-c622-49d0-b38b-5de33c575d63:e8deb84d969af8dd8ffd68bec98764d6
[W 10:36:32.301 LabApp] Replacing stale connection: 056290f3-ec31-4a20-8b0a-61422a6ab81e:4ae00bec138c7b41d8cff5be5d27eecb
[W 10:36:32.324 LabApp] Replacing stale connection: 056290f3-ec31-4a20-8b0a-61422a6ab81e:86c5d19dec77c16d77fbb6e414c03db3
[E 10:36:33.245 LabApp] Exception in callback <bound method ZMQChannelsHandler.send_ping of ZMQChannelsHandler(056290f3-ec31-4a20-8b0a-61422a6ab81e)>
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/notebook/base/zmqhandlers.py", line 197, in send_ping
        self.ping(b'')
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/websocket.py", line 314, in ping
        raise WebSocketClosedError()
    WebSocketClosedError
[E 10:36:33.329 LabApp] Exception in callback <bound method ZMQChannelsHandler.send_ping of ZMQChannelsHandler(056290f3-ec31-4a20-8b0a-61422a6ab81e)>
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/notebook/base/zmqhandlers.py", line 197, in send_ping
        self.ping(b'')
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/websocket.py", line 314, in ping
        raise WebSocketClosedError()
    WebSocketClosedError
[I 10:36:56.315 LabApp] Adapting to protocol v5.1 for kernel b21539e4-c622-49d0-b38b-5de33c575d63
[I 10:36:56.321 LabApp] Adapting to protocol v5.1 for kernel b21539e4-c622-49d0-b38b-5de33c575d63

**Comment by dbl001** [comment]
Please ignore the issue with the plot.  It’s working.

**Comment by blink1073** [comment]
@minrk, the difference that could account for the above is that we use a new `session_id` on a page refresh.

**Comment by cupdike** [comment]
I'm on 0.31.8 and I also see WebSocketClosedError running Pytorch.  It happens when I run a cells that does significant training and a progress meter gets displayed.  Eventually the notebook stops updating, the browser pops up notification that the page is taking a long time will a wait or exit option, and then the web socket error eventually occurs.  It happens across every combination of systems and browsers that I've tried: Mac (Chrome, Safari, Firefox) and Windows (Chrome).  When it happens, I can kill the page and reload to pick up where things left off.   When I run the same notebook using plain Jupyter, I don't see this problem.

**Comment by blink1073** [comment]
Thanks, @ian-r-rose was able to narrow it down to this code as a reproducible example, we are looking into how to address the problem:

```python
from time import sleep
import sys

for i in range(501):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-100s] %d%%" % ('='*int(i/5), i/5))
    sys.stdout.flush()
    sleep(0.002)
```

**Comment by blink1073** [comment]
Ignore my previous comment, wrong issue.

**Comment by CyruSun** [comment]
@dbl001 Thanks.
It happened for me while running Jupyter. I ran a cell that did a long massive execution, refreshing the page and "rerun" the cells involved made appear the output, but I had to shutdown and restart the notebook in   to bring back the normal functioning.

**Comment by dbl001** [comment]
Still happening ...

```
W 14:38:07.019 LabApp] zmq message arrived on closed channel
[W 14:41:27.179 LabApp] 404 GET /apple-touch-icon-precomposed.png (166.171.250.155) 9.14ms referer=None
[E 14:41:29.126 LabApp] Uncaught exception GET /lab/api/build?1563201689496 (166.171.250.155)
    HTTPServerRequest(protocol='https', host='52.8.16.250:8888', method='GET', uri='/lab/api/build?1563201689496', version='HTTP/1.1', remote_ip='166.171.250.155', headers={'Accept': '*/*', 'Accept-Langua
ge': 'en-us', 'Referer': 'https://52.8.16.250:8888/lab?', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15', 'Accept-E
ncoding': 'gzip, deflate', 'Content-Type': 'application/json', 'Pragma': 'no-cache', 'X-Xsrftoken': '2|d93ae4fa|7f0f781886b7c21b7643e1bb13cd53b1|1562610575', 'Cookie': '_xsrf=2|d93ae4fa|7f0f781886b7c21b76
43e1bb13cd53b1|1562610575; username-52-8-16-250-8888="2|1:0|10:1562000018|25:username-52-8-16-250-8888|44:NzYzYjU3YWE2ZmY5NDYxMjk0YTk5YjE4MTYxYzVhNDU=|66e0278ffd18f8197ec9eb4c891bda223555075dd6e303bdeb961
e6d941de9d0"; username-52-8-16-250-8889="2|1:0|10:1562781717|25:username-52-8-16-250-8889|44:NjEwYzAzZmY3YTY0NDQyYzlhMzZkZGZjMzJjNGIxNzk=|d5e4aef6fc11fb960f08285e7e2138acea83cf9e5257abf426d1cd391a736c68";
 username-52-8-16-250-8890="2|1:0|10:1562784619|25:username-52-8-16-250-8890|44:NGI2NmJkMDY0ZDRjNGNmYWJhZDBjMmExZTE1ZWI3YTI=|5c1003bab0d34311b6b4d132596393e698a9bca0a80a079655d8a5202d8a71a2"', 'Connection
': 'keep-alive', 'Host': '52.8.16.250:8888', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/jupyterlab/build_handler.py", line 111, in get
        data = yield self.builder.get_status()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/jupyterlab/build_handler.py", line 37, in get_status
        messages = yield self._run_build_check(self.app_dir, self.log)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
        return self.__get_result()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/jupyterlab/build_handler.py", line 88, in _run_build_check
        return build_check(app_dir=app_dir, logger=logger)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/jupyterlab/commands.py", line 318, in build_check
        _node_check()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/jupyterlab/commands.py", line 1466, in _node_check
        proc = Process(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/jupyterlab_launcher/process.py", line 109, in __init__
        kwargs['stdout'] = subprocess.DEVNULL
    AttributeError: 'module' object has no attribute 'DEVNULL'
[E 14:41:29.134 LabApp] {
      "Accept": "*/*",
      "Accept-Language": "en-us",
      "Referer": "https://52.8.16.250:8888/lab?",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Pragma": "no-cache",
      "X-Xsrftoken": "2|d93ae4fa|7f0f781886b7c21b7643e1bb13cd53b1|1562610575",
      "Cookie": "_xsrf=2|d93ae4fa|7f0f781886b7c21b7643e1bb13cd53b1|1562610575; username-52-8-16-250-8888=\"2|1:0|10:1562000018|25:username-52-8-16-250-8888|44:NzYzYjU3YWE2ZmY5NDYxMjk0YTk5YjE4MTYxYzVhNDU=|66e0278ffd18f8197ec9eb4c891bda223555075dd6e303bdeb961e6d941de9d0\"; username-52-8-16-250-8889=\"2|1:0|10:1562781717|25:username-52-8-16-250-8889|44:NjEwYzAzZmY3YTY0NDQyYzlhMzZkZGZjMzJjNGIxNzk=|d5e4aef6fc11fb960f08285e7e2138acea83cf9e5257abf426d1cd391a736c68\"; username-52-8-16-250-8890=\"2|1:0|10:1562784619|25:username-52-8-16-250-8890|44:NGI2NmJkMDY0ZDRjNGNmYWJhZDBjMmExZTE1ZWI3YTI=|5c1003bab0d34311b6b4d132596393e698a9bca0a80a079655d8a5202d8a71a2\"",
      "Connection": "keep-alive",
      "Host": "52.8.16.250:8888",
      "Cache-Control": "no-cache"
    }
[E 14:41:29.137 LabApp] 500 GET /lab/api/build?1563201689496 (166.171.250.155) 39.33ms referer=https://52.8.16.250:8888/lab?

```

**Comment by vidartf** [comment]
@dbl001 Your error seem like a different error. It seems caused by you running lab from python 2.7, while only Python 3 is supported.

**Comment by dbl001** [comment]
Understood.  I just restarted 'jupyter lab' from my Anaconda virtual environment (python 3.6).  Let's see what happens.

**Comment by dbl001** [comment]
Running from Anaconda 3.6 virtual environment:

```
[I 17:23:01.020 LabApp] Adapting to protocol v5.1 for kernel 5d9dd1fd-b329-4c2e-9c40-bd0f2d27307d
[I 17:23:18.717 LabApp] Adapting to protocol v5.1 for kernel dfb39ffa-d2fd-4185-bc6f-a0bf91b0dbe3
[W 17:24:19.913 LabApp] WebSocket ping timeout after 94622 ms.
[W 17:24:21.439 LabApp] WebSocket ping timeout after 96188 ms.
[I 17:24:22.649 LabApp] Adapting to protocol v5.1 for kernel 86013a67-73f1-4e0e-935c-ce91722677c3
[I 17:24:25.035 LabApp] Adapting to protocol v5.1 for kernel c2643919-0eb3-47f3-8ba4-162a4c47ff16
[W 17:24:58.204 LabApp] WebSocket ping timeout after 108518 ms.
[I 17:25:08.443 LabApp] Adapting to protocol v5.1 for kernel 3d23a23f-9dea-4f01-9463-0e3160c4b298
[W 17:28:49.495 LabApp] WebSocket ping timeout after 119935 ms.
[I 17:28:59.711 LabApp] Adapting to protocol v5.1 for kernel c2643919-0eb3-47f3-8ba4-162a4c47ff16
[W 17:57:09.746 LabApp] WebSocket ping timeout after 119909 ms.
[W 17:57:27.547 LabApp] WebSocket ping timeout after 119932 ms.
[W 17:57:29.713 LabApp] WebSocket ping timeout after 119950 ms.
[I 17:57:30.656 LabApp] Adapting to protocol v5.1 for kernel 5d9dd1fd-b329-4c2e-9c40-bd0f2d27307d
[I 17:57:31.817 LabApp] Adapting to protocol v5.1 for kernel c2643919-0eb3-47f3-8ba4-162a4c47ff16
[I 17:57:36.445 LabApp] Adapting to protocol v5.1 for kernel ce02f8b5-7f3c-414a-8280-f79f8b3519e5
[W 18:02:03.744 LabApp] WebSocket ping timeout after 119929 ms.
[I 18:02:03.947 LabApp] Starting buffering for 4192273c-2950-482d-82c5-7751a73a7b08:c9cec7e745c1849ef6a75e21141330a7
[I 18:02:13.954 LabApp] Adapting to protocol v5.1 for kernel 4192273c-2950-482d-82c5-7751a73a7b08
[I 18:02:13.955 LabApp] Restoring connection for 4192273c-2950-482d-82c5-7751a73a7b08:c9cec7e745c1849ef6a75e21141330a7
[W 18:05:18.721 LabApp] WebSocket ping timeout after 115068 ms.
[W 18:05:21.037 LabApp] WebSocket ping timeout after 115168 ms.
[W 18:05:21.246 LabApp] WebSocket ping timeout after 104440 ms.
[W 18:05:21.714 LabApp] WebSocket ping timeout after 108496 ms.
[W 18:05:21.783 LabApp] WebSocket ping timeout after 105856 ms.
[W 18:05:22.652 LabApp] WebSocket ping timeout after 99718 ms.
[W 18:05:23.776 LabApp] WebSocket ping timeout after 117845 ms.
[W 18:05:25.038 LabApp] WebSocket ping timeout after 104728 ms.
[W 18:05:27.405 LabApp] WebSocket ping timeout after 110213 ms.
[W 18:05:27.934 LabApp] WebSocket ping timeout after 114957 ms.
[I 18:05:28.778 LabApp] Starting buffering for 86013a67-73f1-4e0e-935c-ce91722677c3:ca16f600faaf16c870c37683333111d9
[W 18:05:29.201 LabApp] WebSocket ping timeout after 109167 ms.
[W 18:05:29.950 LabApp] WebSocket ping timeout after 116996 ms.
[W 18:05:30.659 LabApp] WebSocket ping timeout after 117301 ms.
[W 18:05:31.025 LabApp] WebSocket ping timeout after 117470 ms.
[W 18:05:31.233 LabApp] WebSocket ping timeout after 119704 ms.
[W 18:05:31.510 LabApp] WebSocket ping timeout after 114253 ms.
[W 18:05:31.636 LabApp] WebSocket ping timeout after 117571 ms.
[W 18:05:31.820 LabApp] WebSocket ping timeout after 118283 ms.
[I 18:05:32.407 LabApp] Starting buffering for dfb39ffa-d2fd-4185-bc6f-a0bf91b0dbe3:0960c1ce7d8deeb96c44a47bb027d5d5
[W 18:05:32.790 LabApp] WebSocket ping timeout after 119594 ms.
[W 18:05:33.067 LabApp] WebSocket ping timeout after 117627 ms.
[W 18:05:34.234 LabApp] WebSocket ping timeout after 116635 ms.
[I 18:05:34.953 LabApp] Starting buffering for 1a42841a-78a3-4189-b323-556085c81099:f1d9584395899dad9515414829802daa
[W 18:05:35.195 LabApp] WebSocket ping timeout after 118390 ms.
[I 18:05:36.028 LabApp] Starting buffering for 5d9dd1fd-b329-4c2e-9c40-bd0f2d27307d:82244e88f51402b07e7cce7d05023b5f
[W 18:05:36.449 LabApp] WebSocket ping timeout after 119560 ms.
[I 18:05:36.639 LabApp] Starting buffering for 4e0367dc-f2e1-4778-a016-d6724da78153:569f7519d56e2c47a5f89e032116c857
[I 18:05:36.822 LabApp] Starting buffering for c2643919-0eb3-47f3-8ba4-162a4c47ff16:063d57d8da51ed5f69e25836e5804745
[I 18:05:38.069 LabApp] Starting buffering for 2bd2d0b6-735b-4e97-b692-a93a2aeea5d3:fdd5f55f4d3a8273473bb8e8ef21cdbc
[W 18:05:38.447 LabApp] WebSocket ping timeout after 119932 ms.
[I 18:05:39.237 LabApp] Starting buffering for a53ebedd-40f5-477e-8477-523925df6ba2:66144617a89ef4325bcec42092816a0b
[W 18:05:39.516 LabApp] WebSocket ping timeout after 119924 ms.
[I 18:05:41.452 LabApp] Starting buffering for ce02f8b5-7f3c-414a-8280-f79f8b3519e5:322812886c12068eb43ec930ff4c9b96
[I 18:05:43.450 LabApp] Starting buffering for 3d23a23f-9dea-4f01-9463-0e3160c4b298:8ecc4b2b59c1d8834eaf287d96c43c0a
[W 18:05:43.956 LabApp] WebSocket ping timeout after 119951 ms.
[W 18:05:44.091 LabApp] WebSocket ping timeout after 119913 ms.
[I 18:05:44.518 LabApp] Starting buffering for f58921a4-a5f7-416d-8e8a-ee9591528d9f:0b586a97a398ca14b14d8291ee9e4acc
[I 18:05:48.959 LabApp] Starting buffering for 4192273c-2950-482d-82c5-7751a73a7b08:c9cec7e745c1849ef6a75e21141330a7
[I 18:05:49.093 LabApp] Starting buffering for a82b6fc4-d9a3-4f82-aad1-69da9d14a54f:7e3c02bb27d3a857b2e8c22394c7ebb4

```
The jupyter kernel is connected, but the output from training the model isn’t displayed.
Should it reconnect and display the model’s output?

**Comment by hemangjoshi37a** [comment]
Is this already solved?? please help.

**Comment by jtlz2** [comment]
Any update? :\
