### ISSUE TITLE
`warning error` building jupyter lab 0.31.1

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jupyterlab/jupyterlab#3638]
I have `python 3.6.4` `node@9.4.0`  on `OSX 10.13.2`
`jupyterlab  0.31.1`     `jupyterlab-launcher  0.10.2`
`jupyter-widgets-jupyterlab-manager-0.33.0`

I've update jupyterlab & I get a `warning error` (? - an error or a warning??)

```
e$ jupyter lab clean
e$ jupyter lab build
[LabBuildApp] > node /Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[-/3] ⠐ waiting...
[2/3] ⠐ canvas: using node@9.4.0 | darwin | x64
[3/3] ⠐ fsevents: info using node@9.4.0 | darwin | x64
[-/3] ⠐ waiting...
warning Error running install script for optional dependency: "/Users/e/anaconda3/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /Users/e/anaconda3/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@9.4.0 | darwin | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Python executable \"/Users/e/anaconda3/bin/python\" is v3.6.4, which is not supported by gyp.\ngyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.\ngyp ERR! stack     at PythonFinder.failPythonVersion (/Users/e/.config/yarn/global/node_modules/node-gyp/lib/configure.js:492:19)\ngyp ERR! stack     at PythonFinder.<anonymous> (/Users/e/.config/yarn/global/node_modules/node-gyp/lib/configure.js:474:14)\ngyp ERR! stack     at ChildProcess.exithandler (child_process.js:264:7)\ngyp ERR! stack     at ChildProcess.emit (events.js:160:13)\ngyp ERR! stack     at maybeClose (internal/child_process.js:943:16)\ngyp ERR! stack     at Sockesuccess Saved lockfile.
✨  Done in 14.08s.
[LabBuildApp] > node /Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
Hash: 2e00ef4975f477d41588
Version: webpack 2.7.0
Time: 56316ms
                                 Asset       Size  Chunks                    Chunk Names
             2.2fdf50f4cb288ddada35.js     418 kB       2  [emitted]  [big]  
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]  
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]         
  4f0283c6ce28e888000e978e537a6a56.png    1.26 kB          [emitted]         
  a6137456ed160d7606981aa57c559898.png  696 bytes          [emitted]         
  2273e3d8ad9264b7daa5bdbf8e6b47f8.png    1.47 kB          [emitted]         
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]         
             0.564884708191041a4bbe.js     131 kB       0  [emitted]         @jupyter-widgets/controls
             1.8e0d1da5c4502dd42977.js     578 kB       1  [emitted]  [big]  vega2
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]         
        vendor.c615d5bc3e0c4398b45f.js    1.46 MB       3  [emitted]  [big]  vendor
          main.455026ae0437d24d2aa0.js    1.56 MB       4  [emitted]  [big]  main
      manifest.0befd7a85fdc7db3f064.js     1.6 kB       5  [emitted]         manifest
         0.564884708191041a4bbe.js.map     439 kB       0  [emitted]         @jupyter-widgets/controls
         1.8e0d1da5c4502dd42977.js.map    2.19 MB       1  [emitted]         vega2
         2.2fdf50f4cb288ddada35.js.map     1.3 MB       2  [emitted]         
    vendor.c615d5bc3e0c4398b45f.js.map     5.5 MB       3  [emitted]         vendor
      main.455026ae0437d24d2aa0.js.map    5.39 MB       4  [emitted]         main
  manifest.0befd7a85fdc7db3f064.js.map    8.13 kB       5  [emitted]         manifest
                            index.html    1.72 kB          [emitted]         
[+HaM] ./~/@phosphor/messaging/lib/index.js 18.5 kB {3} [built]
[/sZe] ./~/@phosphor/commands/lib/index.js 33.2 kB {3} [built]
[PJh5] ./~/moment/moment.js 123 kB {3} [built]
[Vszx] ./~/@phosphor/domutils/lib/index.js 636 bytes {3} [built]
[b/Hx] ./~/ansi_up/ansi_up.js 11 kB {3} [built]
[cYMN] ./~/@phosphor/virtualdom/lib/index.js 21 kB {3} [built]
[l9te] ./~/@phosphor/application/lib/index.js 18.1 kB {3} [built]
[lMhA] ./~/@phosphor/dragdrop/lib/index.js 33.7 kB {3} [built]
[nh00] ./~/@phosphor/disposable/lib/index.js 4.24 kB {3} [built]
[q1RZ] ./~/@phosphor/datagrid/lib/index.js 793 bytes {3} [built]
   [5] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/datagrid @phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/properties @phosphor/signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json es6-promise marked moment path-posix react react-dom sanitize-html url-parse xterm 328 bytes {3} [built]
   [6] multi whatwg-fetch ./build/index.out.js 40 bytes {4} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {3} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {3} [built]
[y7VK] ./~/@phosphor/algorithm/lib/index.js 1.03 kB {3} [built]
    + 1327 hidden modules
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 420 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.6 kB {0} [built]
✨  Done in 58.77s.
e$ 
```

At the moment I didn't notice anything *sinister*.  Can you please confirm is not an issue?

By the way, I deleted all of my jupyter-widgets-jupyterlab extensions, because of the perennial release conflict.  

With all the moving pieces required by jubyter lab, per-se a great product, & all the components releases conflicts, you risk to make it unmanageable form a user perspective.  Is there a plan to make things simpler in the future?

**Comment by blink1073** [comment]
I can confirm this is not an issue. I've opened #3665 to track the upstream issue causing this.  Cheers!
