### ISSUE TITLE
`jupyterlab` doesn't recognize `nodejs` and `npm` installations

### ISSUE THREAD

**Issue by IamGianluca** [jupyterlab/jupyterlab#3640]
Hi,

I'm having troubles installing the `jupyterlab_bokeh` extension. 

```
$ jupyter labextension install jupyterlab_bokeh

Errored, use --debug for full output:
ValueError: Please install nodejs and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```

I'm using a virtual environment (`pyenv` plus `pyenv-virtualenvwrapper`). I've tried to install the two packages first on my local OS (Ubuntu 16.04) and reinstalled `jupyterlab` but that didn't help. I've also tried to install both `nodejs` and `npm` via `pip` on the virtual enviroment, after having uninstalled the packages on my OS just to make sure they were not conflicting. Unfortunately, neither of the tentative succeeded.

The weird thing is that if I type the `nodejs` command on my terminal, I can access a `nodejs` REPL.

```
bokeh==0.12.13
jupyter-client==5.2.1
jupyter-core==4.4.0
jupyterlab==0.31.1
jupyterlab-launcher==0.10.2
```

**Comment by IamGianluca** [comment]
The problem is not limited to the extension `jupyterlab_bokeh`. I can replicate the same error with the extension `jupyterlab-manager`.

I've actually noticed that if I run `jupyter labextension list` I can see both extensions as correctly installed:

```
$ jupyter labextension list
JupyterLab v0.31.1
Known labextensions:
   app dir: /home/gianluca/.virtualenvs/rethinking/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.0  enabled  OK
jupyterlab_bokeh
        jupyterlab_bokeh v0.2.0  enabled  OK

Build recommended, please run `jupyter lab build`:
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    jupyterlab_bokeh needs to be included in build
```

However, as you can read in the above snipped, a built is recommended. If I try to run the build, this is the error message I see:

```
$ jupyter lab build
[LabBuildApp] > node /home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
Traceback (most recent call last):
  File "/home/gianluca/.virtualenvs/rethinking/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/notebook/notebookapp.py", line 1431, in start
    super(NotebookApp, self).start()
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/labapp.py", line 64, in start
    command=command, logger=self.log)
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/commands.py", line 238, in build
    command=command, clean_staging=clean_staging)
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/commands.py", line 376, in build
    self._run(['node', YARN_PATH, 'install'], cwd=staging)
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/commands.py", line 1158, in _run
    proc = Process(cmd, **kwargs)
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/process.py", line 72, in __init__
    self.proc = self._create_process(cwd=cwd, env=env)
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/process.py", line 130, in _create_process
    cmd[0] = which(cmd[0], kwargs.get('env'))
  File "/home/gianluca/.virtualenvs/rethinking/lib/python3.6/site-packages/jupyterlab/jlpmapp.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```

Again, both `nodejs` and `npm` are installed in the operating system.

**Comment by blink1073** [comment]
Hi @IamGianluca, it looks like `shutil.which` is not able to find `node`.   What are the outputs of the following?:

```
which node
python -c "from shutil import which; print(which('node'))"
```

**Comment by IamGianluca** [comment]
Hi @blink1073, 

The issue was with the `nodejs` version I have installed. Following [this answer](https://askubuntu.com/questions/786272/why-does-installing-node-6-x-on-ubuntu-16-04-actually-install-node-4-2-6#786279) I was able to install `nodejs` v6.12.3. That sorted all my issues :-)

**Comment by blink1073** [comment]
Glad you got sorted, cheers!

**Comment by bubthegreat** [comment]
This is a problem for default installations on mac OSX as well.  Same solution solved it, but it would be pretty nice if the installation either did this for me, or warned me that I might need to fix it.

**Comment by blink1073** [comment]
Hi @MaxSchambach, what is the full stack trace when you run `jupyter lab build`?

**Comment by MaxSchambach** [comment]
Hi, I get the following (I replaced my home directory with ``~``):

```
$ ~/.conda/envs/jupyterlab/bin/jupyter lab build --debug

[LabBuildApp] Searching ['~/.conda/envs/jupyterlab', '~/.jupyter', '~/.conda/envs/jupyterlab/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in ~/.conda/envs/jupyterlab/etc/jupyter
[LabBuildApp] Looking for jupyter_config in ~/.jupyter
[LabBuildApp] Looking for jupyter_config in ~/.conda/envs/jupyterlab
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in ~/.conda/envs/jupyterlab/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in ~/.jupyter
[LabBuildApp] Looking for JupyterLab_config in ~/.conda/envs/jupyterlab
Traceback (most recent call last):
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/commands.py", line 1179, in _node_check
    proc = Process(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/process.py", line 73, in __init__
    self.proc = self._create_process(cwd=cwd, env=env)
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/process.py", line 136, in _create_process
    proc = subprocess.Popen(cmd, **kwargs)
  File "~/.conda/envs/jupyterlab/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "~/.conda/envs/jupyterlab/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './bin/node': './bin/node'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/jupyter-lab", line 11, in <module>
    load_entry_point('jupyterlab==0.32.0.dev0', 'console_scripts', 'jupyter-lab')()
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/notebook/notebookapp.py", line 1571, in start
    super(NotebookApp, self).start()
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/labapp.py", line 64, in start
    command=command, logger=self.log)
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/commands.py", line 247, in build
    _node_check()
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/commands.py", line 1183, in _node_check
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing. nodejs may be installed using conda or directly from the nodejs website.
```

**Comment by blink1073** [comment]
Ah, I see the problem there.  We should be using `which node`:

```
  File "~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/commands.py", line 1179, in _node_check
    proc = Process(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
```

**Comment by blink1073** [comment]
No, we are doing that in the `Process` class.  What does the following print:

```
./python -c "from jupyterlab.jlpmapp import which; print(which('node'))"
```

**Comment by MaxSchambach** [comment]
I get
```
$ ./bin/python -c "from jupyterlab.jlpmapp import which; print(which('node'))"

/usr/bin/node
```

I replaced `` 'node' `` with `` '/usr/bin/node'`` in the ``commands.py`` file in lines 1179,  389 and 392, then the build runs without an error. Still, I think it should be using the ``node`` in the environments ``bin/node`` which is there and executable

**Comment by blink1073** [comment]
If you make the following change does it find the right location?

```diff
diff --git a/jupyterlab/jlpmapp.py b/jupyterlab/jlpmapp.py
index 39bd6a7..931daee 100644
--- a/jupyterlab/jlpmapp.py
+++ b/jupyterlab/jlpmapp.py
@@ -59,6 +59,14 @@ def which(command, env=None):
         command = 'nodejs'
         command_with_path = _which('nodejs', path=path)

+    if command_with_path and not os.path.isabs(command_with_path):
+        for p in path:
+            test = os.path.relpath(p, command_with_path)
+            test = os.path.abspath(test)
+            if os.path.exists(test):
+                command_with_path = test
+                break
+
     if not command_with_path:
         if command in ['nodejs', 'node', 'npm']:
             msg = 'Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.'
```

**Comment by blink1073** [comment]
Note I edited the above.

**Comment by MaxSchambach** [comment]
Yes, mostly!
It does start building, but looks for a global ``node``later. On a machine with globally installed ``node``the build finishes, on a machine where ``node``is only installed in the env, I get the following from ``jupyter lab build``:

```
[LabBuildApp] Searching ['~/.conda/envs/jupyterlab', '~/.jupyter', '~/.conda/envs/jupyterlab/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in ~/.conda/envs/jupyterlab/etc/jupyter
[LabBuildApp] Looking for jupyter_config in ~/.jupyter
[LabBuildApp] Looking for jupyter_config in ~/.conda/envs/jupyterlab
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in ~/.conda/envs/jupyterlab/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in ~/.jupyter
[LabBuildApp] Looking for JupyterLab_config in ~/.conda/envs/jupyterlab
[LabBuildApp] > node ~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] 📃  Building fresh packages...
[1/3] ⠂ spawn-sync
[2/3] ⠂ canvas
[3/3] ⠂ fsevents
[-/3] ⠂ waiting...
warning Error running install script for optional dependency: "~/.conda/envs/jupyterlab/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 127\nCommand: node-gyp rebuild\nArguments: \nDirectory: ~/.conda/envs/jupyterlab/share/jupyter/lab/staging/node_modules/canvas\nOutput:\n~/.conda/envs/jupyterlab/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "~/.conda/envs/jupyterlab/share/jupyter/lab/staging/node_modules/fsevents: Command failed.\nExit code: 127\nCommand: node install\nArguments: \nDirectory: ~/.conda/envs/jupyterlab/share/jupyter/lab/staging/node_modules/fsevents\nOutput:\n/bin/sh: node: command not found"
info This module is OPTIONAL, you can safely ignore this error
error ~/.conda/envs/jupyterlab/share/jupyter/lab/staging/node_modules/spawn-sync: Command failed.
Exit code: 127
Command: node postinstall
Arguments: 




[LabBuildApp] > node ~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
env: node: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by blink1073** [comment]
Does `node ~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install` work when run directly from the environment with no errors?

**Comment by MaxSchambach** [comment]
Yes, it does.

**Comment by blink1073** [comment]
Can you please make this change and see what it prints?

```diff
diff --git a/jupyterlab/process.py b/jupyterlab/process.py
index a75359a..db3d959 100644
--- a/jupyterlab/process.py
+++ b/jupyterlab/process.py
@@ -129,6 +129,7 @@ class Process(object):
         kwargs.setdefault('stderr', subprocess.STDOUT)

         cmd[0] = which(cmd[0], kwargs.get('env'))
+        print('Running command', cmd[0])

         if os.name == 'nt':
             kwargs['shell'] = True
```

**Comment by MaxSchambach** [comment]
It prints
  
    Running command /home/schambach/.conda/envs/jupyterlab/bin/node

**Comment by blink1073** [comment]
According to the docs for [subprocess](https://docs.python.org/3/library/subprocess.html#popen-constructor), the new process should inherit the parent process' environment, but the child process isn't finding `node`.  Perhaps try this?

```diff
diff --git a/jupyterlab/process.py b/jupyterlab/process.py
index a75359a..6307140 100644
--- a/jupyterlab/process.py
+++ b/jupyterlab/process.py
@@ -133,6 +133,8 @@ class Process(object):
         if os.name == 'nt':
             kwargs['shell'] = True

+        kwargs['env'] = os.environ
+
         proc = subprocess.Popen(cmd, **kwargs)
         return proc
```

**Comment by MaxSchambach** [comment]
It didn't help:
```
[...]
[LabBuildApp] > node ~/.conda/envs/jupyterlab/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
/usr/bin/env: ‘node’: No such file or directory
error Command failed with exit code 127.
```

But on Linux I do get the additional ``/usr/bin/env: ‘node’: No such file or directory``, so the Javascript script is definitely trying to find ``node`` in one of the places of ``PATH``.

**Comment by blink1073** [comment]
Ah, so the directory where the environment's `node` lives is not on the `PATH` variable?

**Comment by MaxSchambach** [comment]
No, at least if it is not temporarily added somewhere along the process.

**Comment by blink1073** [comment]
Yes, I think that is the key.  Adding that to `PATH` should make it work without any patches to JupyterLab.

**Comment by MaxSchambach** [comment]
Yes, adding it to the PATH will make it work.

But is that something the user should have to do in order for the build to succeed? I mean, if there happens to be a ``node`` in the ``PATH`` already, to environment's ``node`` will not be used which does not seem to be the expected behaviour.
Also, if you install JupyterLab to a fresh environment with node and all dependencies installed in that envorinment, you would expect the build to succeed.

Or it should be mentioned that the environment needs to be activated (which will add the environment's ``bin`` PATH to the beginning of the ``PATH`` variable) in order for the build to succeed. The activation does not work in all shells though.

As I don't have any experiences with this, I don't know how other packages solve this, but that would be interesting to know.

**Comment by blink1073** [comment]
I don't think there is any way around pre-pending the `PATH` variable, because we are calling sub-processes.  If it can't be done by activation, it has to be done manually.

**Comment by MaxSchambach** [comment]
Yes, I think you're right.
It might be worth mentioning the needed activation somewhere in the docs though.
Anyways, thanks for the help and quick responses!

**Comment by iamtodor** [comment]
I have the similar issue
```
(env) ilyat@todorpc:~/projects/topic_modeling$ jupyter labextension install jupyterlab_bokeh
Node v8.10.0


Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```

Here is the output of `jupyter lab build`
```
(env) ilyat@todorpc:~/projects/topic_modeling$ jupyter lab build
[LabBuildApp] JupyterLab 0.35.4
[LabBuildApp] Cleaning /home/ilyat/projects/topic_modeling/env/share/jupyter/lab
Cleaning /home/ilyat/projects/topic_modeling/env/share/jupyter/lab...
Success!
[LabBuildApp] Building in /home/ilyat/projects/topic_modeling/env/share/jupyter/lab
[LabBuildApp] Node v8.10.0

[LabBuildApp] > node /home/ilyat/projects/topic_modeling/env/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
warning "@jupyterlab/vega4-extension > vega-embed > vega-themes@2.3.0" has unmet peer dependency "vega@*".
[5/5] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.15.2", while you're on "1.9.4".
Done in 112.17s.
[LabBuildApp] > node /home/ilyat/projects/topic_modeling/env/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
yarn run v1.9.4
$ webpack
Hash: 92ade64dd844bd36890f
Version: webpack 4.12.2
Time: 7219ms
Built at: 03/26/2019 4:54:44 PM
                                   Asset       Size        Chunks             Chunk Names
    vendors~vega.2ea76bfc25e70d59a551.js   2.95 MiB  vendors~vega  [emitted]  vendors~vega
    674f50d287a8c48dc19ba404d20fe713.eot    162 KiB                [emitted]  
    912ec66d7572ff821749319396470bde.svg    434 KiB                [emitted]  
   fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB                [emitted]  
    b06871f281fee6b241d60582ae9369b9.ttf    162 KiB                [emitted]  
            main.cdc43895974962930368.js   52.4 KiB          main  [emitted]  main
               0.cc98107762fcc28532b3.js    4.5 KiB             0  [emitted]  
            vega.91b98e783d16fd1b9e23.js  519 bytes          vega  [emitted]  vega
    vendors~main.415b32f70b93872cf70c.js   8.06 MiB  vendors~main  [emitted]  vendors~main
  af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB                [emitted]  
               1.055322dcf6c2bb19185f.js    888 KiB             1  [emitted]  
        main.cdc43895974962930368.js.map   60.9 KiB          main  [emitted]  main
           0.cc98107762fcc28532b3.js.map   5.73 KiB             0  [emitted]  
        vega.91b98e783d16fd1b9e23.js.map  251 bytes          vega  [emitted]  vega
vendors~main.415b32f70b93872cf70c.js.map   9.27 MiB  vendors~main  [emitted]  vendors~main
vendors~vega.2ea76bfc25e70d59a551.js.map    2.3 MiB  vendors~vega  [emitted]  vendors~vega
           1.055322dcf6c2bb19185f.js.map   1.04 MiB             1  [emitted]  
                              index.html   1.54 KiB                [emitted]  
Entrypoint main = vendors~main.415b32f70b93872cf70c.js vendors~main.415b32f70b93872cf70c.js.map main.cdc43895974962930368.js main.cdc43895974962930368.js.map
 [0] multi whatwg-fetch ./build/index.out.js 40 bytes {main} [built]
 [1] vertx (ignored) 15 bytes {main} [optional] [built]
 [4] buffer (ignored) 15 bytes {main} [optional] [built]
 [5] crypto (ignored) 15 bytes {main} [optional] [built]
 [6] readable-stream (ignored) 15 bytes {main} [built]
 [7] supports-color (ignored) 15 bytes {main} [built]
 [8] chalk (ignored) 15 bytes {main} [built]
 [9] fs (ignored) 15 bytes {main} [built]
[10] node-fetch (ignored) 15 bytes {vega} [built]
[11] fs (ignored) 15 bytes {vega} [built]
 [ANye] ./build/index.out.js 34.1 KiB {main} [built]
 [RnhZ] ./node_modules/moment/locale sync ^\.\/.*$ 2.88 KiB {main} [optional] [built]
 [YuTi] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
 [eTbV] ./node_modules/codemirror/mode sync ^\.\/.*\.js$ 2.78 KiB {0} [built]
 [yLpj] (webpack)/buildin/global.js 489 bytes {vendors~main} [built]
    + 2425 hidden modules

WARNING in d3-array
  Multiple versions of d3-array found:
    1.2.4 ./~/d3-scale/~/d3-array from ./~/d3-scale/~/d3-array/src/index.js
    2.0.3 ./~/d3-array from ./~/d3-array/src/index.js


WARNING in vega-lite
  Multiple versions of vega-lite found:
    2.5.1 ./~/vega-lite/build/src from ./~/vega-lite/build/src/compile/selection/selection.js
    2.6.0 ./~/vega-lite/build from ./~/vega-lite/build/src/index.js

Check how you can resolve duplicate packages: 
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [KTNU] ./node_modules/html-loader!./templates/partial.html 567 bytes {0} [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.22 KiB {0} [built]
    [yLpj] (webpack)/buildin/global.js 489 bytes {0} [built]
        + 1 hidden module
Done in 8.40s.
```

Any my nodejs version 
```
ilyat@todorpc:~$ node --version
v8.10.0
```

**Comment by yumaloop** [comment]
if you use Ubuntu, exexute `sudo apt install -y nodejs npm`.

**Comment by bilow-factual** [comment]
Thanks, @yumaloop, that was my issue.
