### ISSUE TITLE
Can't install using MiniConda on Windows 10

### ISSUE THREAD

**Issue by pdeffebach** [jupyterlab/jupyterlab#3671]
I am eager to try out jupyterlab, so I installed MiniConda, First I updated my conda installation using `conda update conda`. Then I ran the code 
```
conda install -c conda-forge jupyterlab
```
I get the following error

```
>conda install -c conda-forge jupyterlab
Traceback (most recent call last):
  File "C:\Users\PeterDeffebach\Miniconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\cli\main.py", line 125, in main
    from ..exceptions import conda_exception_handler
  File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\exceptions.py", line 17, in <module>
    from .common.io import timeout
  File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\common\io.py", line 28, in <module>
    from .._vendor.tqdm import tqdm
  File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\_vendor\tqdm\__init__.py", line 6, in <module>
    from ._tqdm import tqdm
  File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\_vendor\tqdm\_tqdm.py", line 14, in <module>
    from ._utils import _supports_unicode, _environ_cols_wrapper, _range, _unich, \
  File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\_vendor\tqdm\_utils.py", line 31, in <module>
    colorama.init()
AttributeError: module 'colorama' has no attribute 'init'
```

Is there anything I should be doing? I am confused at how to proceed.

**Comment by blink1073** [comment]
Hi @pdeffebach, it sounds like the conda environment is corrupted.  Had you installed any other libraries before `jupyterlab`?

**Comment by pdeffebach** [comment]
Yes that may have been the problem above. I uninstalled MiniConda and made sure that everything related, including the anaconda command prompt, was deleted. 

Then I reinstalled and tried again. This was certainly in the correct direction, but still no success. 

I run the command `conda install -c conda-forge jupyterlab`, it downloads a number of dependencies, then I get here: 

```
The following packages will be SUPERSEDED by a higher-priority channel:

    conda:               4.3.31-py36_0                 --> 4.3.31-py36_0 conda-forge
    conda-env:           2.6.0-h36134e3_1              --> 2.6.0-0       conda-forge
    openssl:             1.0.2n-h74b6da3_0             --> 1.0.2n-vc14_0 conda-forge [vc14]
    yaml:                0.1.7-hc54c509_2              --> 0.1.7-vc14_0  conda-forge [vc14]

Proceed ([y]/n)?
```

I type `y` and hit enter. It downloads more dependencies, until I get this error. 

```
ERROR conda.core.link:_execute_actions(339): An error occurred while installing package 'conda-forge::jupyter_core-4.4.0-py_0'.
CondaError: Cannot link a source that does not exist. C:\Users\PeterDeffebach\Miniconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
```

So I run  `conda clean --packages` . It removes a bunch of packages and gives me a new prompt. I enter `conda install -c conda-forge jupyterlab` again. It again gives me the 

 ```
The following packages will be SUPERSEDED by a higher-priority channel:
``` 

Prompt, to which I hit `y`. Then I get the following error 

```
CondaError: PermissionError(13, 'Access is denied')
CondaError: PermissionError(13, 'Access is denied')
CondaError: PermissionError(13, 'Access is denied')
```

**Comment by pdeffebach** [comment]
Here are the results of `conda list` 

```
# packages in environment at C:\Users\PeterDeffebach\Miniconda3:
#
asn1crypto                0.23.0           py36h546eea3_0
ca-certificates           2017.08.26           h94faf87_0
certifi                   2017.11.5        py36hb8ac631_0
cffi                      1.11.2           py36h829d1a5_0
chardet                   3.0.4            py36h420ce6e_1
conda                     4.3.31                   py36_0
conda-env                 2.6.0                h36134e3_1
console_shortcut          0.1.1                h6bb2dd7_3
cryptography              2.1.4            py36he1d7878_0
idna                      2.6              py36h148d497_1
menuinst                  1.4.10           py36h42196fb_0
openssl                   1.0.2n               h74b6da3_0
pip                       9.0.1            py36h226ae91_4
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.18             py36hd053e01_1
pyopenssl                 17.5.0           py36h5b7d817_0
pysocks                   1.6.7            py36h698d350_1
python                    3.6.3                h3b118a2_4
pywin32                   221              py36h9c10281_0
requests                  2.18.4           py36h4371aae_1
ruamel_yaml               0.11.14          py36h9b16331_2
setuptools                36.5.0           py36h65f9e6e_0
six                       1.11.0           py36h4db2310_1
urllib3                   1.22             py36h276f60a_0
vc                        14                   h2379b0c_2
vs2015_runtime            14.0.25123           hd4c4e62_2
wheel                     0.30.0           py36h6c3ec14_1
win_inet_pton             1.0.1            py36he67d7fd_1
wincertstore              0.2              py36h7fe50ca_0
yaml                      0.1.7                hc54c509_2
```

**Comment by blink1073** [comment]
It looks like JupyterLab 0.31.1 is available in the [default channel](https://anaconda.org/anaconda/jupyterlab).  It could be a bad local interaction with those overridden conda-forge packages.  Does it work with a fresh miniconda and a `conda install jupyterlab` (no channel specified).

**Comment by pdeffebach** [comment]
Thanks for the replies. 

I have uninstalled miniconda and deleted all relevant files. However it still isn't working. 

`conda install jupyterlab` works initially, installing a number of dependencies, but ultimately ends in an error. I am adding a ton of output here, because when it initially failed it told me to repeat the command with `-v` at the end, and I'm not sure what is important. 

```
>conda install jupyterlab -v
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\PeterDeffebach\Miniconda3:

The following NEW packages will be INSTALLED:

    bleach:              2.1.2-py36_0
    colorama:            0.3.9-py36h029ae33_0
    decorator:           4.1.2-py36he63a57b_0
    entrypoints:         0.2.3-py36hfd66bb0_2
    html5lib:            1.0.1-py36h047fa9f_0
    ipykernel:           4.7.0-py36h2f9c1c0_0
    ipython:             6.2.1-py36h9cf0123_1
    ipython_genutils:    0.2.0-py36h3c5d0ee_0
    jedi:                0.11.1-py36_0
    jinja2:              2.10-py36h292fed1_0
    jsonschema:          2.6.0-py36h7636477_0
    jupyter_client:      5.2.1-py36_0
    jupyter_core:        4.4.0-py36h56e9d50_0
    jupyterlab:          0.31.1-py36_0
    jupyterlab_launcher: 0.10.2-py36_0
    markupsafe:          1.0-py36h0e26971_1
    mistune:             0.8.3-py36_0
    nbconvert:           5.3.1-py36h8dc0fde_0
    nbformat:            4.4.0-py36h3a5bc1b_0
    notebook:            5.2.2-py36hc48260a_0
    pandoc:              1.19.2.1-hb2460c7_1
    pandocfilters:       1.4.2-py36h3ef6317_1
    parso:               0.1.1-py36hae3edee_0
    pickleshare:         0.7.4-py36h9de030f_0
    prompt_toolkit:      1.0.15-py36h60b8f86_0
    pygments:            2.2.0-py36hb010967_0
    python-dateutil:     2.6.1-py36h509ddcb_1
    pyzmq:               16.0.3-py36he714bf5_0
    simplegeneric:       0.8.1-py36heab741f_0
    testpath:            0.3.1-py36h2698cfe_0
    tornado:             4.5.3-py36_0
    traitlets:           4.3.2-py36h096827d_0
    wcwidth:             0.1.7-py36h3d5aa90_0
    webencodings:        0.5.1-py36h67c50ae_1

The following packages will be UPDATED:

    conda:               4.3.31-py36_0         --> 4.4.7-py36_0

Proceed ([y]/n)? y

()

===> UNLINKING PACKAGE: defaults::conda-4.3.31-py36_0 <===
  prefix=C:\Users\PeterDeffebach\Miniconda3


===> LINKING PACKAGE: defaults::pandoc-1.19.2.1-hb2460c7_1 <===
  prefix=C:\Users\PeterDeffebach\Miniconda3
  source=C:\Users\PeterDeffebach\Miniconda3\pkgs\pandoc-1.19.2.1-hb2460c7_1


===> LINKING PACKAGE: defaults::colorama-0.3.9-py36h029ae33_0 <===
  prefix=C:\Users\PeterDeffebach\Miniconda3
  source=C:\Users\PeterDeffebach\Miniconda3\pkgs\colorama-0.3.9-py36h029ae33_0


file exists, but clobbering for directory: 'C:\\Users\\PeterDeffebach\\Miniconda3\\Lib\\site-packages\\colorama\\__pycache__'

Failed to remove C:\Users\PeterDeffebach\Miniconda3\Lib\site-packages\colorama\__pycache__.

rm_rf failed for C:\Users\PeterDeffebach\Miniconda3\Lib\site-packages\colorama\__pycache__

An error occurred while installing package 'defaults::colorama-0.3.9-py36h029ae33_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.


===> REVERSING PACKAGE LINK: defaults::colorama-0.3.9-py36h029ae33_0 <===
  prefix=C:\Users\PeterDeffebach\Miniconda3


===> REVERSING PACKAGE LINK: defaults::pandoc-1.19.2.1-hb2460c7_1 <===
  prefix=C:\Users\PeterDeffebach\Miniconda3


===> REVERSING PACKAGE UNLINK: defaults::conda-4.3.31-py36_0 <===
  prefix=C:\Users\PeterDeffebach\Miniconda3


An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\PeterDeffebach\Miniconda3  (writable)
    default environment : C:\Users\PeterDeffebach\Miniconda3
       envs directories : C:\Users\PeterDeffebach\Miniconda3\envs
                          C:\Users\PeterDeffebach\AppData\Local\conda\conda\envs
                          C:\Users\PeterDeffebach\.conda\envs
          package cache : C:\Users\PeterDeffebach\Miniconda3\pkgs
                          C:\Users\PeterDeffebach\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False

`$ C:\Users\PeterDeffebach\Miniconda3\Scripts\conda install jupyterlab -v`




    Traceback (most recent call last):
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\core\link.py", line 328, in _execute_actions
        action.execute()
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\core\path_actions.py", line 245, in execute
        force=context.force)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\gateways\disk\create.py", line 237, in create_link
        mkdir_p(dst)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\gateways\disk\create.py", line 158, in mkdir_p
        makedirs(path)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\os.py", line 220, in makedirs
        mkdir(name, mode)
    PermissionError: [WinError 5] Access is denied: 'C:\\Users\\PeterDeffebach\\Miniconda3\\Lib\\site-packages\\colorama\\__pycache__'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\core\link.py", line 283, in execute
        pkg_data, actions)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\core\link.py", line 346, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: [WinError 5] Access is denied: 'C:\\Users\\PeterDeffebach\\Miniconda3\\Lib\\site-packages\\colorama\\__pycache__'


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\common\io.py", line 174, in decorated
        return f(*args, **kwds)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\plan.py", line 832, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\Users\PeterDeffebach\Miniconda3\lib\site-packages\conda\core\link.py", line 299, in execute
        rollback_excs,
    conda.CondaMultiError: [WinError 5] Access is denied: 'C:\\Users\\PeterDeffebach\\Miniconda3\\Lib\\site-packages\\colorama\\__pycache__'
```

**Comment by pdeffebach** [comment]
Additionally, in the process I have somewhow arrived at my original error, which ends with `colorama has no attribute \`init\` `

**Comment by arinbasu** [comment]
Hi Peter,

Can you install JupyterLab with pip or virtualenv on your machine? 

Best,
Arin

**Comment by blink1073** [comment]
It also looks like it could be related to file permission settings in the `Miniconda3` folder.

**Comment by pdeffebach** [comment]
@arinbasu I reinstalled Miniconda to my user folder, and it failed

@blink1073 I then uninstalled Miniconda and reinstalled it in Documents, which might have more lenient permissions given I am on a work computer. It failed in the same way as above. I then tried to use `pip` to install again and received this error, which was the same one I got the first time I tried to use `pip`. 

One issue of note, is that there cold be some sort of anti-virus software preventing certain .bat scripts from downloading. I am using Miniconda because Anaconda would not let me download `activate.bat`, and consequently could not start a terminal session. 

```
>pip install jupyterlab
Collecting jupyterlab
  Using cached jupyterlab-0.31.1-py2.py3-none-any.whl
Collecting notebook>=4.3.1 (from jupyterlab)
  Using cached notebook-5.3.1-py2.py3-none-any.whl
Collecting jupyterlab-launcher<0.11.0,>=0.10.0 (from jupyterlab)
  Using cached jupyterlab_launcher-0.10.2-py2.py3-none-any.whl
Collecting ipython-genutils (from jupyterlab)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: jupyter-core>=4.4.0 in c:\users\peterdeffebach\documents\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab)
Exception:
Traceback (most recent call last):
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "C:\Users\PeterDeffebach\Documents\Miniconda3\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'
```

**Comment by blink1073** [comment]
Given that it is such a locked-down environment, I'd suggest using the full Anaconda distribution, the latest of which comes with a slightly older version of JupyterLab, but given that it has all of the dependencies, you should be able to upgrade to the latest.

**Comment by pdeffebach** [comment]
I tried to download Anaconda, but there seems to be a standing issue with the activation script `activate.bat` among others, get caught in virus protection software.

I don't fully understand, why should the installation of a python environment require more permissions that a Julia environment or an R environment.

**Comment by vidartf** [comment]
I've had strange issues with AV and conda before as well, so that might be a suspect. E.g. Avast tends to put python.exe into quarantine, leading to very obscure errors. If possible, check your AV logs to see if you are able to gain some hints. Many AV's also have the option to temporarily disable the running checks, so you could consider that.

**Comment by aattaran** [comment]
I have the same issue with miniconda:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\Miniconda3\lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: %1 is not a valid Win32 application.
Traceback (most recent call last):
  File "C:\Users\User\Miniconda3\lib\site-packages\conda\cli\main.py", line 170, in main
    import conda.cli.activate as activate
  File "C:\Users\User\Miniconda3\lib\site-packages\conda\cli\activate.py", line 10, in <module>
    from ..exceptions import (ArgumentError, CondaEnvironmentError, CondaSystemExit, CondaValueError,
  File "C:\Users\User\Miniconda3\lib\site-packages\conda\exceptions.py", line 16, in <module>
    from .common.url import maybe_unquote
  File "C:\Users\User\Miniconda3\lib\site-packages\conda\common\url.py", line 8, in <module>
    import socket
  File "C:\Users\User\Miniconda3\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Miniconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\User\Miniconda3\lib\site-packages\conda\cli\main.py", line 177, in main
    from ..exceptions import handle_exception
  File "C:\Users\User\Miniconda3\lib\site-packages\conda\exceptions.py", line 16, in <module>
    from .common.url import maybe_unquote
  File "C:\Users\User\Miniconda3\lib\site-packages\conda\common\url.py", line 8, in <module>
    import socket
  File "C:\Users\User\Miniconda3\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

C:\Users\User>

**Comment by murtuzamdahod** [comment]
@pdeffebach Same error occurred to me too. what I did was I **closed all the python scripts and notebooks** and then tried installing pip and fortunately, IT WORKED!

**Comment by TSH-Simon** [comment]
Okay, so I found the issue fix (at least for me - comment if it works for you).

How to fix it:
1. [Download Colorama](https://github.com/tartley/colorama)
2. Copy the "Colorama" from the download then replace the folder named "colorama" in C:\Program Files\Anaconda3\Lib\site-packages

I suspect this issue occurs because of ([issue 8842](https://github.com/conda/conda/issues/8842))

**Comment by Raul818** [comment]
deleting colorama(folder and files) from site-packages solved the issue for me.
