### ISSUE TITLE
Unable to install jupyterlab with anaconda-navigator

### ISSUE THREAD

**Issue by scubamut** [jupyterlab/jupyterlab#3711]
Miniconda3-latest-Windows-x86_64 installed.
Activated root.
conda install anaconda-navigator.
Anaconda-navigator started sucessfully.
Clicked jupyterlab "install" -

Conda process error
The following errors occurred:
NotWritableError: The current user does not have write permissions to a required path.
path: C:\Users\scuba\C:\Users\scuba\.conda\environments.txt

> Traceback (most recent call last):
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 1064, in check_outdated_channels
    self.add_default_channels(conda_data)
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 1055, in add_default_channels
    worker.communicate()
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 279, in communicate
    result[0], result[-1], **self._extra_kwargs
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1112, in <lambda>
    callback=lambda o, e: o.get('warnings', [])
AttributeError: 'bytes' object has no attribute 'get'
2018-01-24 11:23:23,833 - ERROR main_window._conda_output_ready:1593
NotWritableError: The current user does not have write permissions to a required path./n  path: C:/Users/scuba/C:/Users/scuba/.conda/environments.txt/n

**Comment by blink1073** [comment]
Hi @scubamut, I'm not sure what is causing the path to be repeated, can you please raise the issue on https://github.com/ContinuumIO/anaconda-issues/issues/new?

**Comment by scubamut** [comment]
thks @blink1073. I have already....
