### ISSUE TITLE
Lack of Node.js Causes 404

### ISSUE THREAD

**Issue by TariqAHassan** [jupyterlab/jupyterlab#3820]
This is probably obvious to the dev. team, but Node.js is required for Jupyter Lab to spin up. Without it, invoking `jupyter lab` simply yields a 404. 

Now that Jupyter Lab is in beta, it might be a good idea to mention this dependency in the README and/or docs.

Cheers.

FYI, here is the error message:

```bash
Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyterlab/commands.py", line 321, in __init__
        self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyterlab/commands.py", line 1165, in _run
        proc = Process(cmd, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyterlab/process.py", line 73, in __init__
        self.proc = self._create_process(cwd=cwd, env=env)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyterlab/process.py", line 131, in _create_process
        cmd[0] = which(cmd[0], kwargs.get('env'))
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyterlab/jlpmapp.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```

(Indeed, installing node.js from the website solved the problem).

**Comment by blink1073** [comment]
Thanks for reporting, @TariqAHassan!  Did this prevent JupyterLab from working or was it a logged error that it recovered from?

**Comment by TariqAHassan** [comment]
Sadly, it did not recover from it. Rather, in the browser window that opened I simply saw a 404 Page Not Found error and nothing else.

**Comment by blink1073** [comment]
Thanks again, I have removed `node.js` locally to confirm this, and will put out a patch release with a fix shortly.
