### ISSUE TITLE
Failing to connect to kernel

### ISSUE THREAD

**Issue by kmisiunas** [jupyterlab/jupyterlab#3842]
Odd problem on the latest release. jupyterlab seems to loose connection to the kernel and fail to reconnect. Error below. My system: ubuntu, jupyterlab 0.31.4, jupyter 1.0.0, 

```
[E 20:55:41.672 LabApp] Uncaught exception POST /api/sessions?1518123342669 (127.0.0.1)                                                  HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1518123342669', version='HTTP/1.1', r
emote_ip='127.0.0.1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Content-Length': '101', 'Authorization': 'token
 e5ec01c1cd1e346f5a8f3c71959d99049c3e021c32f2f1cf', 'Origin': 'http://localhost:8888', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel M
ac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36', 'Content-Type': 'application/json', 'Acc
ept': '*/*', 'Dnt': '1', 'Referer': 'http://localhost:8888/lab', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en
;q=0.9,lt;q=0.8', 'Cookie': '_xsrf=2|4703811b|fca67f3c361efc4672fb2fb2cc741c77|1511793319; username-localhost-8800="2|1:0|10:15180912
96|23:username-localhost-8800|44:ZjhmNDQ1MzRmNTQ2NGU2YjkxZmIyYzcyNTEzYmE0ZGQ=|627bffc713d12ea80a5e4629635fbf3f4034e37fa431af9caf5393c
900403af0"; username-localhost-8888="2|1:0|10:1518123337|23:username-localhost-8888|44:ZTI3MTJkMzA4MmM5NDM1OWI3NzZkYjVjZTMxZjE3ZTE=|c
49313d9e5c6b7ccdb5e230669c22a3358546d143c4259a58e094a0c951c5622"'})
    Traceback (most recent call last):
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_s
ession
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
              raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_ke
rnel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel 
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 239, in start_kernel
        self.write_connection_file()
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
        kernel_name=self.kernel_name
      File "/home/kmisiunas/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
        with open(fname, 'w') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1002/jupyter/kernel-20771f7d-ca9c-493c-ba76-1ed39afc5b4a.json'
```

**Comment by blink1073** [comment]
Hi @kmisiunas, do you see the same error when running the classic notebook `jupyter notebook`?

**Comment by kmisiunas** [comment]
no, with classic notebook i did not observe this. Also, I have not observed
the problem since upgrading to 0.31.5

**Comment by blink1073** [comment]
Okay, I'm going to close this then as a transient local issue.  Feel free to reopen, cheers!
