### ISSUE TITLE
Cannot start jupyterlab (connect for the first time)

### ISSUE THREAD

**Issue by paddington0814** [jupyterlab/jupyterlab#4002]
I install Jupyter Lab and get it running and I am running into some errors:

I have installed it via pip.  But I cannot start the Jupyterlab with the command "jupyter lab".
The browser shows: "404 : Not Found You are requesting a page that does not exist!"
The URL is "http://localhost:8888/lab"

And the error massage is as below:

==
[I 00:43:55.304 LabApp] JupyterLab beta preview extension loaded from C:\Users\David\Anaconda3\lib\site-packages\jupyterlab
[I 00:43:55.304 LabApp] JupyterLab application directory is C:\Users\David\Anaconda3\share\jupyter\lab
[W 00:43:55.313 LabApp] Error loading server extension jupyterlab
Traceback (most recent call last):
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
proc = Process(cmd, **kwargs)
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
self.proc = self._create_process(cwd=cwd, env=env)
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
cmd[0] = which(cmd[0], kwargs.get('env'))
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\David\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1454, in init_server_extensions
func(self)
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
info = get_app_info(app_dir)
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
handler = _AppHandler(app_dir, logger)
File "C:\Users\David\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[I 00:43:55.439 LabApp] Serving notebooks from local directory: C:\Users\David
[I 00:43:55.439 LabApp] 0 active kernels
[I 00:43:55.439 LabApp] The Jupyter Notebook is running at:
[I 00:43:55.439 LabApp] http://localhost:8888/?token=e786b99e4912938a956c6a68c2a4795e37739889d54eb1d6
[I 00:43:55.439 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:43:55.441 LabApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=e786b99e4912938a956c6a68c2a4795e37739889d54eb1d6
[I 00:43:55.646 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 00:43:55.684 LabApp] 404 GET /lab?token=4a624d203bccec66ab69078326a2c3858aa79b11bc20372e (::1) 63.24ms referer=None
==

Could anyone kindly help me?

**Comment by paddington0814** [comment]
I have solved the problem by updating the jupyter lab version to 0.31.8
