### ISSUE TITLE
Invalid response: 500 Internal Server Error

### ISSUE THREAD

**Issue by klonuo** [jupyterlab/jupyterlab#4016]
Hi,

I installed jupyterlab with `pip install jupyterlab`, and while starting I get this error:

```
> jupyter lab
[I 13:49:23.158 LabApp] JupyterLab beta preview extension loaded from c:\python36\lib\site-packages\jupyterlab
[I 13:49:23.159 LabApp] JupyterLab application directory is c:\python36\share\jupyter\lab
[W 13:49:23.163 LabApp] JupyterLab server extension not enabled, manually loading...
[I 13:49:23.163 LabApp] JupyterLab beta preview extension loaded from c:\python36\lib\site-packages\jupyterlab
[I 13:49:23.163 LabApp] JupyterLab application directory is c:\python36\share\jupyter\lab
[I 13:49:23.940 LabApp] Serving contents
[I 13:49:23.940 LabApp] 0 active kernels
[I 13:49:23.940 LabApp] The Jupyter Notebook is running at:
[I 13:49:23.940 LabApp] http://localhost:8888/
[I 13:49:23.940 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 13:49:44.807 LabApp] 302 GET / (::1) 2.01ms
[E 13:49:45.427 LabApp] Uncaught exception GET /api/contents/?content=1&1519649385423 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1519649385423', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'X-Xsrftoken': '2|d3e93043|f3ea2adab858044e405adab64827ba72|1519569392', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Content-Type': 'application/json', 'Accept': '*/*', 'Referer': 'http://localhost:8888/lab?', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9,mk;q=0.8,hr;q=0.7,bs;q=0.6,sr;q=0.5', 'Cookie': 'username-localhost-8888="2|1:0|10:1519476462|23:username-localhost-8888|44:ODdmYTRhNmRlZmMwNGI3MmFmYjU1ZTVlOTRjNGFjYWI=|368a7e909ec7077a6fa90eb304963de2ba2ef4636d83415dfefd591a90d13a16"; _xsrf=2|d3e93043|f3ea2adab858044e405adab64827ba72|1519569392'})
    Traceback (most recent call last):
      File "c:\python36\lib\site-packages\tornado\web.py", line 1512, in _execute
        result = yield result
      File "c:\python36\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "c:\python36\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "c:\python36\lib\site-packages\tornado\gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "c:\python36\lib\site-packages\notebook\services\contents\handlers.py", line 114, in get
        validate_model(model, expect_content=content)
      File "c:\python36\lib\site-packages\notebook\services\contents\handlers.py", line 39, in validate_model
        missing = required_keys - set(model.keys())
    AttributeError: 'list' object has no attribute 'keys'
[W 13:49:45.437 LabApp] Unhandled error
[E 13:49:45.438 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "X-Xsrftoken": "2|d3e93043|f3ea2adab858044e405adab64827ba72|1519569392",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab?",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,mk;q=0.8,hr;q=0.7,bs;q=0.6,sr;q=0.5",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1519476462|23:username-localhost-8888|44:ODdmYTRhNmRlZmMwNGI3MmFmYjU1ZTVlOTRjNGFjYWI=|368a7e909ec7077a6fa90eb304963de2ba2ef4636d83415dfefd591a90d13a16\"; _xsrf=2|d3e93043|f3ea2adab858044e405adab64827ba72|1519569392"
    }
[E 13:49:45.439 LabApp] 500 GET /api/contents/?content=1&1519649385423 (::1) 11.03ms referer=http://localhost:8888/lab?
[I 13:49:46.458 LabApp] Build is up to date
```
![image](https://user-images.githubusercontent.com/361447/36671873-a0164db8-1afd-11e8-83f3-6316f059cec2.png)

**Comment by saulshanabrook** [comment]
Which version of Jupyter Notebook do you have installed?

**Comment by klonuo** [comment]
It's 5.4.0

**Comment by saulshanabrook** [comment]
Do you have anything in your `jupyter_notebook_config.py` file?

**Comment by klonuo** [comment]
If I remove `jupyter_notebook_config.py` is just the same.

Additionally, if I try to run some kernel I get: 
```
Launcher Error
Cannot read property 'path' of undefined
```

**Comment by klonuo** [comment]
The problem was in `jupyter_notebook_config.json` file.

I removed jupyter drive extension setting:

```json
  "NotebookApp": {
    "tornado_settings": {
      "contents_js_source": "nbextensions/gdrive/mixed-contents"
    },
    "contents_manager_class": "jupyterdrive.mixednbmanager.MixedContentsManager"
  }
```

and everything is fine now :)

**Comment by saulshanabrook** [comment]
Great!

**Comment by klonuo** [comment]
So problem seem to be with gdrive extension perhaps

**Comment by saulshanabrook** [comment]
I am closing this then, since the problem doesn't seem to be in core. Feel free to re-open if you feel otherwise.

**Comment by woodknight** [comment]
I encountered this problem today and found that there was an invalid symbolic link in the folder that I started jupyterlab from. After removing the invalid link, everything goes fine.

**Comment by jaamarks** [comment]
Similar resolution for me @woodknight — Thanks!

**Comment by jasongrout** [comment]
Thanks for following up!
