### ISSUE TITLE
OSError on macOS

### ISSUE THREAD

**Issue by fonnesbeck** [jupyterlab/jupyterlab#4017]
Running JupyterLab for any length of time on macOS results in a litany of OSErrors like this:

```
[E 08:58:44.878 LabApp] Exception in callback (<socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 8888, 0, 0)>, <function wrap.<locals>.null_wrapper at 0x10ee8e048>)
    Traceback (most recent call last):
      File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
      File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
      File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.6/site-packages/tornado/netutil.py", line 264, in accept_handler
      File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.6/socket.py", line 205, in accept
    OSError: [Errno 24] Too many open files
```

and a server connection error in the browser:

![](https://d.pr/i/p06i5I+)

Running jupyterlab 0.31.8 on Python3.6, installed via conda.

**Comment by saulshanabrook** [comment]
This won't resolve the underlying issue, but [the default file limits are lower on mac and you can raise them with](https://github.com/ipython/ipython/issues/4882/#issuecomment-33434826):

```bash
ulimit -n 1024
```

**Comment by blink1073** [comment]
Hi @fonnesbeck, I've not seen this before on my Mac.  Can you describe what kind of items you had open and about how many of them?

**Comment by fonnesbeck** [comment]
@blink1073 This is a single notebook that was open and includes a long-running process. It runs fine on the notebook, but not in jupyterlab.

**Comment by blink1073** [comment]
Thanks, I'll try that notebook locally.

**Comment by blink1073** [comment]
I was able to run the notebook fully with no 500 error.  I am not sure what would cause this error.

**Comment by dayuhuang** [comment]
I have encountered the same error when trying to run on linux today: 
jupyterlab version: 0.31.12
Linux: CentOS7
Python: Python 3.6

```
Traceback (most recent call last):
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/jupyter_client/manager.py", line 239, in start_kernel
    self.write_connection_file()
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/site-packages/jupyter_client/connect.py", line 98, in write_connection_file
    sock = socket.socket()
  File "/no_backup_ssd/anaconda3/envs/p36env/lib/python3.6/socket.py", line 144, in __init__
OSError: [Errno 24] Too many open files
```

**Comment by jasongrout** [comment]
Can you see how many open files are open in the jlab process using something like lsof? Does this happen with the classic notebook?

(The classic notebook and jlab use the same server-side component to access the filesystem, so it would be helpful to see if this happens with the classic notebook).

**Comment by maartenbreddels** [comment]
Same here on MacOS 10.13.3 jupyter lab  0.31.12
It happens after a long time, so probably after having opened the 100th notebook orso.

**Comment by flying-sheep** [comment]
Might be a pyzmq bug: jupyter/notebook#3748

**Comment by krassowski** [comment]
Happened to me today on Ubuntu 19.04 but I do not remember seeing pyzmq in backtrace. I might have had too many kernels open indeed. Would making JupyterLab display a nice message that closing some kernels may help a good fix?

**Comment by flying-sheep** [comment]
No that’s a fix for “Bad error reporting when you have many kernels open”. My problem however is “after updating jupyter it started showing an error after 30 minutes of working with a single kernel”

**Comment by BoPeng** [comment]
I noticed this problem after I upgraded to JLab 1.0.0, so it does not look like a kernel problem. I can reset my ulimit to a smaller number (I changed from 256 to 4096 after I noticed the problem) and see if I can reproduce it reliably.

**Comment by jtmatamalas** [comment]
I'm working under Jupyterhub, and I noticed the same problem since I upgraded to JLab 1.0.0.

I have an intuition about what is generating such behavior. It seems that the new status bar is sending update queries at a fixed rate to check the status of the environment. Each of these queries opens a socket that REMAINS open until the session ends. When the number of open sockets reaches the ulimit... boom! Errno 24.

Does anybody know if there is a way to deactivate the status bar update queries?

**Comment by kemathur** [comment]
same issue 4 kernels open for 10 minutes

**Comment by jasongrout** [comment]
There is quite a bit of discussion around this error over at #6727.
