### ISSUE TITLE
Error 500 on "delete file" from JL GUI - exception from send2trash

### ISSUE THREAD

**Issue by mj-harvey** [jupyterlab/jupyterlab#4057]
Hi,

Attempting to delete a file from the JupyterLab GUI gives a 500 server error, and the exception below.
Seems a thing called "send2trash" is trying to make a .Trash directory in the root of an NFS mount. Can this be disabled, and the file simply deleted? There's no need for Freedesktop integration on this system.

```
   Traceback (most recent call last):
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 235, in delete
        yield gen.maybe_future(cm.delete(path))
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 278, in delete
        self.delete_file(path)
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 499, in delete_file
        send2trash(os_path)
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/send2trash/plat_other.py", line 185, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/send2trash/plat_other.py", line 145, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/send2trash/plat_other.py", line 139, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/site-packages/send2trash/plat_other.py", line 84, in check_create
        os.makedirs(dir, 0o700)
      File "/apps/jupyterhub/2018-02-19/anaconda/lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/export131/.Trash-97933'
[W 2018-02-27 22:40:57.312 SingleUserNotebookApp handlers:525] Unhandled error
```

looks similar to  #3793

**Comment by mj-harvey** [comment]
I see this is fixed in a PR. Until that hits conda-forge, I'm just commenting out the call to send2trash() all together.

**Comment by blink1073** [comment]
There is also a config option: https://github.com/jupyter/notebook/pull/1968#issuecomment-329739088
