### ISSUE TITLE
Installation of plotly-extension error

### ISSUE THREAD

**Issue by JeroenSchmidt** [jupyterlab/jupyterlab#4093]
I am unable to install the plotly-extension.

I had a look through this [issue](https://github.com/jupyterlab/jupyterlab/issues/3082) hoping a solution would arise but nothing has yet.

The following versions I've tried installing it in:
1) Attempt 1 
* Conda 4.4.11
* python 3.5.2
* nmp 3,4 and 5
2) Attempt 2
* Conda 4.4.11
* python 3.5.4
* nmp 3,4, and 5

When I trying to install plotly-extension; i get the following error:

```
>>> jupyter labextension install @jupyterlab/plotly-extension
> /conda/bin/npm pack @jupyterlab/plotly-extension
jupyterlab-plotly-extension-0.14.4.tgz
> node /conda/lib/python3.5/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-supported@1.2.0: This package has been moved to @mapbox/mapbox-gl-supported
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vt-pbf > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
warning @jupyterlab/plotly-extension > plotly.js > color-rgba > color-space > husl@5.0.3: Project renamed to HSLuv
warning @jupyterlab/plotly-extension > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0:
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
error Couldn't find match for "83b1a3e5837d785af582efd5ed1a212f2df6a4ae" in "_c" for "https://github.com/mapbox/mapbox-gl-style-spec.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node /conda/lib/python3.5/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
module.js:457
    throw err;
    ^

Error: Cannot find module '@jupyterlab/plotly-extension/package.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.resolve (internal/module.js:27:19)
    at /conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:22:43
    at Array.forEach (native)
    at Object.ensureAssets (/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:21:22)
    at Object.<anonymous> (/conda/share/jupyter/lab/staging/webpack.config.js:19:7)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/conda/share/jupyter/lab/staging/webpack.prod.config.js:5:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by blink1073** [comment]
Hi @JeroenSchmidt, can you please try a `yarn cache clean` and then try again?

**Comment by blink1073** [comment]
(or `jlpm cache clean` if you don't have yarn installed separately).

**Comment by JeroenSchmidt** [comment]
`yarn cache clean` didnt run.
`jlpm cache clean` ran. 

I ran `jupyter labextension install @jupyterlab/plotly-extension` again. 
Now it is haginig on `functional-red-black-tree@^1.0.0` and then produced the following error:
```
> node /conda/lib/python3.5/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-supported@1.2.0: This package has been moved to @mapbox/mapbox-gl-supported
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vt-pbf > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vt-pbf > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
warning @jupyterlab/plotly-extension > plotly.js > color-rgba > color-space > husl@5.0.3: Project renamed to HSLuv
warning @jupyterlab/plotly-extension > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0:
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
error Couldn't find match for "83b1a3e5837d785af582efd5ed1a212f2df6a4ae" in "_c" for "https://github.com/mapbox/mapbox-gl-style-spec.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node /conda/lib/python3.5/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
module.js:538
    throw err;
    ^

Error: Cannot find module '@jupyterlab/plotly-extension/package.json'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at /conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:22:43
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:21:22)
    at Object.<anonymous> (/conda/share/jupyter/lab/staging/webpack.config.js:19:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/conda/share/jupyter/lab/staging/webpack.prod.config.js:5:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JeroenSchmidt** [comment]
Hi @blink1073 
I just figured out what the problem was.

My jupyterlab runs behind corporate firewalls. 

Before I was telling npm my proxy settings using the guide in this [stackoverflow post](https://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy) and it seemed to work as I was able to pull from the NPM repos - so assumed it was working as expected.

Because of the above fact I didnt think that my proxy settings were causing the errors I was encountering. However on a whim I decided to also source my proxy settings on the machine... and vuala the errors disapeared and I was able to install the jupyterlab extension.

**Comment by jasongrout** [comment]
Great, thanks for following up here.
