### ISSUE TITLE
Unable to open Notebooks

### ISSUE THREAD

**Issue by akshay-raj-dhamija** [jupyterlab/jupyterlab#4097]
Hello,

I am unable to open any jupyter notebook after I recently updated my jupyter lab installation.
`jupyter-lab --version 0.31.5`
I have tried opening the notebook with both jupyter lab and the classic jupyter notebooks.

In both cases, the initial page opens and I am able to navigate to the notebook of interest but when I try to open the notebook the page doesn't load.
With the classic jupyter notebooks, I see the following error in the browser console.

`
main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:41579 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:41579
main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:19269 load_extensions Arguments(1)
main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:42481 Loaded moment locale en
main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:19271 Failed to load extensions: (2) ["custom/custom", "nbextensions/jupyter-js-widgets/extension"] Error: Load timeout for modules: custom/custom,nbextensions/jupyter-js-widgets/extension
http://requirejs.org/docs/errors.html#timeout
    at makeError (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165)
    at checkLoaded (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:693)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:714
(anonymous) @ main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:19271
Promise.catch (async)
load_extensions @ main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:19270
(anonymous) @ main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:19298
Promise.then (async)
load_extensions_from_config @ main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:19295
(anonymous) @ main.min.js?v=e668f0463f94c07b6ae316d94271c38d:sourcemap:45187
execCb @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690
check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865
(anonymous) @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140
(anonymous) @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131
(anonymous) @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190
each @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56
emit @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189
check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940
enable @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177
init @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:783
callGetModule @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1204
completeLoad @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1583
onScriptLoad @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1711
`

I don't see any errors in the browser console when using jupyterlab and the last message in the terminal window is:
`[I 23:38:11.573 LabApp] Build is up to date`

I either case after this point I am unable to shutdown the server too.
Trying to kill the process results in a zombie process and the only option left is reboot.

Any pointers on the solution would be very much appreciated.

Thanks!

**Comment by blink1073** [comment]
Hi @akshay-raj-dhamija, are you able to execute the notebook from the command line using `nbconvert`?  e.g. `jupyter nbconvert --to notebook --execute mynotebook.ipynb`

You might also try a fresh conda or pip environment.

**Comment by akshay-raj-dhamija** [comment]
Hi @blink1073,

Thanks for the pointers, they were really helpful and my issue is now resolved.
I had tried a fresh conda environment, but with no success.
When trying nbconvert I get the following error message
```
adhamija@r2-d8:~$ jupyter nbconvert --to notebook --execute Airlines.ipynb 

[NbConvertApp] Converting notebook Airlines.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python2

Traceback (most recent call last):
  File "/home/adhamija/anaconda2/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 493, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 464, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 257, in preprocess
    cwd=path)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 241, in start_new_kernel
    kc.wait_for_ready(timeout=startup_timeout)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/jupyter_client/blocking/client.py", line 124, in wait_for_ready
    raise RuntimeError("Kernel didn't respond in %d seconds" % timeout)
RuntimeError: Kernel didn't respond in 60 seconds
```

On further search, I found the [link](https://github.com/takluyver/bash_kernel/issues/53) where according to the discussion uninstalling pexpect from conda and installing it using pip worked for me.

Thanks!

**Comment by blink1073** [comment]
Cheers!
