### ISSUE TITLE
Updating to latest version of Tornado breaks the Jupyter lab on anaconda

### ISSUE THREAD

**Issue by bidhya** [jupyterlab/jupyterlab#4133]
I get the following error message when using conda update --all. I noticed upon downgrading the Tornado 5.0 to 4.5.3, both Jupyterlab and notebook works properly.

Following is the error message:
(gis) C:\Users\bny>jupyter lab
Traceback (most recent call last):
  File "C:\Users\bny\Anaconda2\envs\gis\Scripts\jupyter-lab-script.py", line 6, in <module>
    from jupyterlab.labapp import main
  File "C:\Users\bny\Anaconda2\envs\gis\lib\site-packages\jupyterlab\labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "C:\Users\bny\Anaconda2\envs\gis\lib\site-packages\notebook\notebookapp.py", line 45, in <module>
    ioloop.install()
  File "C:\Users\bny\Anaconda2\envs\gis\lib\site-packages\zmq\eventloop\ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

**Comment by blink1073** [comment]
Hi @bidhya, this is being tracked in https://github.com/ContinuumIO/anaconda-issues/issues/8789, thanks!

**Comment by rddaz2013** [comment]
See...
https://github.com/tornadoweb/tornado/commit/426b3812b9dd21ae0bac19d4146c6952816c7bfe#diff-1d4144f0ef561b7c18c7fe438816e1f5
