### ISSUE TITLE
pysqlite2 error after installing in Python 3.6 pipenv

### ISSUE THREAD

**Issue by palewire** [jupyterlab/jupyterlab#4181]
Here's what I run. And here's the error I get.

```
$ pipenv install pandas jupyter jupyterlab pypyodbc
...
$ pipenv shell
...
$ jupyter lab
Traceback (most recent call last):
  File "/home/palewire/.local/share/virtualenvs/helicopter-accident-analysis-OQ5AjB6w/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/home/palewire/.local/share/virtualenvs/helicopter-accident-analysis-OQ5AjB6w/lib/python3.6/site-packages/jupyterlab/labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "/home/palewire/.local/share/virtualenvs/helicopter-accident-analysis-OQ5AjB6w/lib/python3.6/site-packages/notebook/notebookapp.py", line 83, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/home/palewire/.local/share/virtualenvs/helicopter-accident-analysis-OQ5AjB6w/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'
$ pipenv install pysqlite
Installing pysqlite…
Collecting pysqlite
  Using cached pysqlite-2.8.3.tar.gz
    Complete output from command python setup.py egg_info:
    pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
```

**Comment by palewire** [comment]
My understanding is the pysqlite2 is not used in Python 3. Shouldn't JupyterLab be avoiding its use somehow?

**Comment by palewire** [comment]
Turns out this is a pyenv build problem I solved by doing [this](https://github.com/pyenv/pyenv/wiki/Common-build-problems). I will close the ticket but I recommend anyone with this problem in Jupyter follow that fix.

**Comment by smile-on** [comment]
Ben, could you elaborate on what exactly was the fix. I can't find any pysqlite2 mentioning in the post pointed by you.

    $ sudo apt install libsqlite3-dev
definetly can't fix missed python package. The pip can't find any pysqlite2 available to python 3.6.5.

**Comment by palewire** [comment]
I had to remove my pyenv install of Python 3, compile the dependency, and then reinstall Python 3 with pyenv.

**Comment by smile-on** [comment]
you mean:

    ./configure --enable-loadable-sqlite-extensions=yes

**Comment by palewire** [comment]
No. But that might do the same thing. I used pyenv to uninstall and reinstall python. And apt to install sqlite in between.
