### ISSUE TITLE
Large CSV file failing with 500 error

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#4240]
I understand that large csv files would not work because of browser constraints ... But when I try to open a very large CSV file like a 2.5GB file, it just gives a 500 internal server error.

I guess this is more probably a notebook error rather than a lab error - but just mentioning it here.

Here's the error:
```
[E 15:38:01.186 LabApp] Uncaught exception GET /api/contents/Downloads/data/allstate_claim_prediction/train_set.csv?format=text&type=file&content=1&1521972481180 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/Downloads/data/allstate_claim_prediction/train_set.csv?format=text&type=file&content=1&1521972481180', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/abdealijk/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/Users/abdealijk/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/Users/abdealijk/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
        yielded = next(result)
      File "/Users/abdealijk/anaconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/abdealijk/anaconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 423, in get
        model = self._file_model(path, content=content, format=format)
      File "/Users/abdealijk/anaconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 352, in _file_model
        content, format = self._read_file(os_path, format)
      File "/Users/abdealijk/anaconda3/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 309, in _read_file
        bcontent = f.read()
    OSError: [Errno 22] Invalid argument
[W 15:38:01.200 LabApp] Unhandled error
[E 15:38:01.200 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
      "Authorization": "token 52ee380a15588d7ea918fdf362ff5936d215139923985778",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|87fa03da|78bcce7e7440543dac84d4343d3264df|1521969832; username-localhost-8888=\"2|1:0|10:1521972478|23:username-localhost-8888|44:MTEyODdlMjE5MzgyNDcyOTg3NjI4NmZlOTIyYTljZGE=|fbef53534e753f5a078eecd9ea92565b73c1c8dcfa8d85f5cea446836d273b04\""
    }
[E 15:38:01.201 LabApp] 500 GET /api/contents/Downloads/data/allstate_claim_prediction/train_set.csv?format=text&type=file&content=1&1521972481180 (::1) 15.71ms referer=http://localhost:8888/lab
```

**Comment by saulshanabrook** [comment]
#5918 covers at least surfacing this error the user, which is the easiest thing to do if the notebook server gives an error without explicitly working around it.
