### ISSUE TITLE
Import error; unable to start Jupyter Lab

### ISSUE THREAD

**Issue by mdmadhu** [jupyterlab/jupyterlab#4281]
I was running Jupyter Lab 0.31.12 on an Anaconda installation of Python 3.6.4 on macOS High Sierra 10.13.3. After updating to Python 3.6.5 (and High Sierra 10.3.4), I have been getting an import error when I try to start Jupyter Lab. Any ideas of how I could fix this? Thanks

`Traceback (most recent call last):
  File "/Users/mdmadhusudan/anaconda3/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/Users/mdmadhusudan/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "/Users/mdmadhusudan/anaconda3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/mdmadhusudan/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 28, in <module>
    from ipython_genutils.py3compat import string_types, cast_unicode_py2
  File "/Users/mdmadhusudan/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 145, in <module>
    import platform
  File "/Users/mdmadhusudan/anaconda3/lib/python3.6/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/Users/mdmadhusudan/anaconda3/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: dlopen(/Users/mdmadhusudan/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
  Referenced from: /Users/mdmadhusudan/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/mdmadhusudan/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so`

**Comment by mdmadhu** [comment]
Managed to get it sorted out by running:
`conda install -c conda-forge jupyterlab`

**Comment by jasongrout** [comment]
Great, thanks for following up with your solution. Enjoy!
