### ISSUE TITLE
just released .32 windows package FileNotFoundError jupyterlab staging package.json

### ISSUE THREAD

**Issue by afonit** [jupyterlab/jupyterlab#4418]
_(Windows 7 64bit, python 3.6)_

Installing the latest windows builds from:
https://anaconda.org/conda-forge/jupyterlab
with:
```
conda install -c conda-forge jupyterlab
```

After install and launching one gets this error:
```
$ jupyter lab
Traceback (most recent call last):
  File "C:\Users\some_user_name\AppData\Local\Continuum\anaconda3\envs\data_analysis\Scripts\jupyter-lab-script.py", line 3, in <module>
    import jupyterlab.labapp
  File "C:\Users\some_user_name\AppData\Local\Continuum\anaconda3\envs\data_analysis\lib\site-packages\jupyterlab\labapp.py", line 32, in <module>
    app_version = get_app_version()
  File "C:\Users\some_user_name\AppData\Local\Continuum\anaconda3\envs\data_analysis\lib\site-packages\jupyterlab\commands.py", line 323, in get_app_version
    handler = _AppHandler(app_dir)
  File "C:\Users\some_user_name\AppData\Local\Continuum\anaconda3\envs\data_analysis\lib\site-packages\jupyterlab\commands.py", line 338, in __init__
    self.info = self._get_app_info()
  File "C:\Users\some_user_name\AppData\Local\Continuum\anaconda3\envs\data_analysis\lib\site-packages\jupyterlab\commands.py", line 697, in _get_app_info
    info['core_data'] = core_data = _get_core_data()
  File "C:\Users\some_user_name\AppData\Local\Continuum\anaconda3\envs\data_analysis\lib\site-packages\jupyterlab\commands.py", line 1389, in _get_core_data
    with open(pjoin(HERE, 'staging', 'package.json')) as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\some_user_name\\AppData\\Local\\Continuum\\anaconda3\\envs\\data_analysis\\lib\\site-packages\\jupyterlab\\staging\\package.json'
(data_analysis)
```

`Note`: I did also do this in a brand new conda environment with the same error as noted above.

**Comment by jasongrout** [comment]
Confirmed:

```
conda create -n jlab32 -c conda-forge jupyterlab
activate jlab32
jupyter lab
```
gives
```
Traceback (most recent call last):
  File "C:\Users\[snip]\Miniconda3\envs\jlab32\Scripts\jupyter-lab-script.py", line 3, in <module>
    import jupyterlab.labapp
  File "C:\Users\[snip]\Miniconda3\envs\jlab32\lib\site-packages\jupyterlab\labapp.py", line 32, in <module>
    app_version = get_app_version()
  File "C:\Users\[snip]\Miniconda3\envs\jlab32\lib\site-packages\jupyterlab\commands.py", line 323, in get_app_version
    handler = _AppHandler(app_dir)
  File "C:\Users\[snip]\Miniconda3\envs\jlab32\lib\site-packages\jupyterlab\commands.py", line 338, in __init__
    self.info = self._get_app_info()
  File "C:\Users\[snip]\Miniconda3\envs\jlab32\lib\site-packages\jupyterlab\commands.py", line 697, in _get_app_info
    info['core_data'] = core_data = _get_core_data()
  File "C:\Users\[snip]\Miniconda3\envs\jlab32\lib\site-packages\jupyterlab\commands.py", line 1389, in _get_core_data
    with open(pjoin(HERE, 'staging', 'package.json')) as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\[snip]\\Miniconda3\\envs\\jlab32\\lib\\site-packages\\jupyterlab\\staging\\package.json'
```

**Comment by jasongrout** [comment]
Very odd - here are the files in the win64 python 3.6 jlab 0.32.0 package:

```
.
./info
./info/recipe
./info/recipe/post-link.sh
./info/recipe/post-link.bat
./info/recipe/pre-unlink.sh
./info/recipe/pre-unlink.bat
./info/recipe/meta.yaml
./info/recipe/meta.yaml.template
./info/paths.json
./info/files
./info/about.json
./info/LICENSE.txt
./info/has_prefix
./info/index.json
./Scripts
./Scripts/.jupyterlab-pre-unlink.bat
./Scripts/.jupyterlab-post-link.bat
./Scripts/jupyter-lab-script.py
./Scripts/jupyter-labextension.exe
./Scripts/jupyter-labextension-script.py
./Scripts/jupyter-labhub-script.py
./Scripts/jupyter-lab.exe
./Scripts/jupyter-labhub.exe
./Scripts/jlpm-script.py
./Scripts/jlpm.exe
./Lib
./Lib/site-packages
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info/PKG-INFO
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info/installed-files.txt
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info/SOURCES.txt
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info/entry_points.txt
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info/requires.txt
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info/top_level.txt
./Lib/site-packages/jupyterlab-0.32.0-py3.6.egg-info/dependency_links.txt
./Lib/site-packages/jupyterlab
./Lib/site-packages/jupyterlab/update.py
./Lib/site-packages/jupyterlab/process_app.py
./Lib/site-packages/jupyterlab/semver.py
./Lib/site-packages/jupyterlab/_version.py
./Lib/site-packages/jupyterlab/selenium_check.py
./Lib/site-packages/jupyterlab/tests
./Lib/site-packages/jupyterlab/tests/test_jupyterlab.py
./Lib/site-packages/jupyterlab/tests/__init__.py
./Lib/site-packages/jupyterlab/tests/__pycache__
./Lib/site-packages/jupyterlab/tests/__pycache__/test_jupyterlab.cpython-36.pyc
./Lib/site-packages/jupyterlab/tests/__pycache__/test_settings_api.cpython-36.pyc
./Lib/site-packages/jupyterlab/tests/__pycache__/echo_kernel.cpython-36.pyc
./Lib/site-packages/jupyterlab/tests/__pycache__/utils.cpython-36.pyc
./Lib/site-packages/jupyterlab/tests/__pycache__/test_build_api.cpython-36.pyc
./Lib/site-packages/jupyterlab/tests/__pycache__/test_app.cpython-36.pyc
./Lib/site-packages/jupyterlab/tests/__pycache__/__init__.cpython-36.pyc
./Lib/site-packages/jupyterlab/tests/utils.py
./Lib/site-packages/jupyterlab/tests/echo_kernel.py
./Lib/site-packages/jupyterlab/tests/test_build_api.py
./Lib/site-packages/jupyterlab/tests/test_app.py
./Lib/site-packages/jupyterlab/tests/test_settings_api.py
./Lib/site-packages/jupyterlab/build_handler.py
./Lib/site-packages/jupyterlab/jlpmapp.py
./Lib/site-packages/jupyterlab/__init__.py
./Lib/site-packages/jupyterlab/__pycache__
./Lib/site-packages/jupyterlab/__pycache__/commands.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/update.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/labapp.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/_version.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/selenium_check.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/labextensions.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/build_handler.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/__main__.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/process_app.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/jlpmapp.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/process.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/__init__.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/extension.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/labhubapp.cpython-36.pyc
./Lib/site-packages/jupyterlab/__pycache__/semver.cpython-36.pyc
./Lib/site-packages/jupyterlab/extension.py
./Lib/site-packages/jupyterlab/labapp.py
./Lib/site-packages/jupyterlab/process.py
./Lib/site-packages/jupyterlab/labhubapp.py
./Lib/site-packages/jupyterlab/labextensions.py
./Lib/site-packages/jupyterlab/commands.py
./Lib/site-packages/jupyterlab/__main__.py
```
No static. No /share

**Comment by jasongrout** [comment]
Here is the build log: https://ci.appveyor.com/project/conda-forge/jupyterlab-feedstock/build/job/gvxqbb5w12kpmrpp

It looks like there is an error about node: https://ci.appveyor.com/project/conda-forge/jupyterlab-feedstock/build/job/gvxqbb5w12kpmrpp#L989

```
error punycode@2.1.0: The engine "node" is incompatible with this module. Expected version ">=6".
  error An unexpected error occurred: "Found incompatible module".
  info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-dle8ucrt-build\\jupyterlab\\staging\\yarn-error.log".
```

**Comment by bollwyvl** [comment]
Yeah, consistent across the board for win:
https://anaconda.org/conda-forge/jupyterlab/files?version=0.32.0

Here's an appveyor error which didn't stop the build:
https://ci.appveyor.com/project/conda-forge/jupyterlab-feedstock/branch/master/job/gvxqbb5w12kpmrpp#L983

And the telling file count:
https://ci.appveyor.com/project/conda-forge/jupyterlab-feedstock/branch/master/job/gvxqbb5w12kpmrpp#L1045

**Comment by bollwyvl** [comment]
haha

**Comment by jasongrout** [comment]
It's a bit odd to me that node would be invoked. Here is the corresponding travis build: https://travis-ci.org/conda-forge/jupyterlab-feedstock/jobs/367374118

**Comment by bollwyvl** [comment]
Eek, local build did not trigger `jsdeps`...

**Comment by bollwyvl** [comment]
So happens that it _did_ trigger it, but it failed silently.

Started https://github.com/conda-forge/jupyterlab-feedstock/pull/108 which adds a bit more rigor to the recipe, and things are looking pretty good...

**Comment by bollwyvl** [comment]
Builds (with tests) are all looking good over on https://github.com/conda-forge/jupyterlab-feedstock/pull/108

Thanks again, @afonit and @jasongrout!

**Comment by jasongrout** [comment]
I guess we could have also seen the problem from the windows builds being about 150K, compared to 9M for other builds, and 12M for past windows builds.

Thanks @bollwyvl for doing a lot of work to get the recipe in *much* better shape, including tests that will help us catch things like this in the future!

**Comment by jasongrout** [comment]
I just tested the new win64 py36 package up on conda-forge, and it works great. Thanks again for flagging this and posting an issue, and thanks @bollwyvl for fixing everything!!

**Comment by zwn** [comment]
I am seeing this issue again, please see https://github.com/conda-forge/jupyterlab-feedstock/issues/151.
