### ISSUE TITLE
Theme building issue

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4459]
Many people have had trouble building the recent versions of jupyterlab. @jzf2101 [posted on gitter](https://gitter.im/jupyterlab/jupyterlab?at=5ae0806a27c509a7744d012d):

```bash
$ lerna run build:webpack --scope "@jupyterlab/theme-*-extension"
lerna info version 2.9.0
lerna info versioning independent
lerna info scope @jupyterlab/theme-*-extension
lerna ERR! build:webpack Errored while running script in '@jupyterlab/theme-dark-extension'
lerna ERR! execute callback with error
lerna ERR! Error: spawn yarn ENOENT
lerna ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
lerna ERR!     at onErrorNT (internal/child_process.js:379:16)
lerna ERR!     at process._tickCallback (internal/process/next_tick.js:178:19)
lerna ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
lerna ERR!     at startup (internal/bootstrap/node.js:201:19)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
lerna ERR! build:webpack Errored while running script in '@jupyterlab/theme-light-extension'
{ Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'run', 'build:webpack' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'yarn run build:webpack',
  timedOut: false,
  exitCode: 1 }
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c lerna run build:webpack --scope \"@jupyterlab/theme-*-extension\"
Directory: /Users/forde/Documents/jupyter_docs/jupyterlab
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/forde/Documents/jupyter_docs/jupyterlab/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c jlpm run integrity && jlpm run build:packages && jlpm run build:themes && cd dev_mode && jlpm run build
Directory: /Users/forde/Documents/jupyter_docs/jupyterlab
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/forde/Documents/jupyter_docs/jupyterlab/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c jlpm run build:dev
Directory: /Users/forde/Documents/jupyter_docs/jupyterlab
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/forde/Documents/jupyter_docs/jupyterlab/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Fordes-MacBook:jupyterlab forde$ conda install -c conda forge pip
Solving environment: failed
```

**Comment by saulshanabrook** [comment]
This was introduced somehow when I added theme building in https://github.com/jupyterlab/jupyterlab/pull/3914, but it doesn't happen for me locally. I will try to recreate it in a Docker container.

**Comment by saulshanabrook** [comment]
Also when just building themes:

```Dockerfile
FROM continuumio/miniconda3:4.4.10

RUN conda install -y --quiet \
    -c conda-forge nodejs notebook

COPY . .
RUN pip install -e .
RUN jlpm install
RUN jlpm run build:themes
```

**Comment by saulshanabrook** [comment]
But works if we just build *one* them

```
FROM continuumio/miniconda3:4.4.10

RUN conda install -y --quiet \
    -c conda-forge nodejs notebook

COPY . .
RUN pip install -e .
RUN jlpm install
WORKDIR packages/theme-dark-extension
RUN jlpm run build:webpack
```

**Comment by saulshanabrook** [comment]
Oh it works if we set `--npm-client jlpm` in the lerna command:  

```bash
lerna run build:webpack --npm-client jlpm --scope "@jupyterlab/theme-*-extension"
```

**Comment by jasongrout** [comment]
I also have issues running `jlpm run build:examples`, etc. - other commands where we use lerna to execute things in subpackages.

**Comment by saulshanabrook** [comment]
@jasongrout Yep, installing yarn as a dev dependency fixes it in my docker build, this works:

```Dockerfile
FROM continuumio/miniconda3:4.4.10

RUN conda install -y --quiet \
    -c conda-forge nodejs notebook

RUN git clone https://github.com/jupyterlab/jupyterlab.git
WORKDIR jupyterlab
RUN pip install -e .
RUN jlpm install
RUN jlpm add --ignore-workspace-root-check --dev yarn
RUN jlpm run build:themes  # Build the dev mode assets (optional)
```

**Comment by jzf2101** [comment]
I had thought that #4474 would fix my issue but I don't think it's fixed https://github.com/jupyterlab/jupyterlab/pull/4474#issuecomment-385445074

**Comment by saulshanabrook** [comment]
@jzf2101  this might be a different issue. I haven't seen that one.  Not sure if that's related to theme building.

**Comment by jasongrout** [comment]
@jzf2101 - it does seem like a different issue, not related to the 'yarn not found' issue here and fixed in the PR. Can you open a new issue with details on how to reproduce it?

**Comment by jzf2101** [comment]
Ah ok np.
