### ISSUE TITLE
Jupyterlab 0.32.0 Cannot Open

### ISSUE THREAD

**Issue by nathanzhang3** [jupyterlab/jupyterlab#4493]
Traceback (most recent call last):
File "/Users/nzhang/anaconda3/bin/jupyter-lab", line 7, in 
from jupyterlab.labapp import main
File "/Users/nzhang/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 7, in 
from notebook.notebookapp import NotebookApp, aliases, flags
File "/Users/nzhang/anaconda3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in 
from .nbextensions import install_nbextension
File "/Users/nzhang/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 28, in 
from ipython_genutils.py3compat import string_types, cast_unicode_py2
File "/Users/nzhang/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 145, in 
import platform
File "/Users/nzhang/anaconda3/lib/python3.6/platform.py", line 116, in 
import sys, os, re, subprocess
File "/Users/nzhang/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/Users/nzhang/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /Users/nzhang/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /Users/nzhang/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

**Comment by jasongrout** [comment]
It seems like something is seriously wrong with your python installation. Does the classic notebook work? `jupyter notebook`

**Comment by cpoulos** [comment]
I'm running into the same issue actually.  Jupyter notebook runs fine, but I can't launch jupyter lab

**Comment by jasongrout** [comment]
Is it this issue? https://github.com/ContinuumIO/anaconda-issues/issues/9046

**Comment by alejandrodgb** [comment]
Yes it does. I had the same issue and tested this resolution - it worked.

**Comment by jasongrout** [comment]
Great, thanks for following up here!
