### ISSUE TITLE
FileNotFoundError: The command was not found or was not executable: /bin/fish.

### ISSUE THREAD

**Issue by domoritz** [jupyterlab/jupyterlab#4501]
I am running jupyterlab on a server with fish. 

```bash
jupyter lab --no-browser --ip='*'
```

When I try to open the terminal in jupyterlab, I get an error "Launcher callbacks must resolve with a widget" and the following error on the server.

```
[E 16:33:51.960 LabApp] Uncaught exception POST /api/terminals?1525131231944 (128.208.3.19)
    HTTPServerRequest(protocol='http', host='128.208.2.91:8888', method='POST', uri='/api/terminals?1525131231944', version='HTTP/1.1', remote_ip='128.208.3.19', headers={'Host': '128.208.2.91:8888', 'Connection': 'keep-alive', 'Content-Length': '0', 'Origin': 'http://128.208.2.91:8888', 'X-Xsrftoken': '2|d5123503|a969671f7814f7aa7b32fcf25a82e429|1525129581', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.18 Safari/537.36', 'Dnt': '1', 'Content-Type': 'application/json', 'Accept': '*/*', 'Referer': 'http://128.208.2.91:8888/lab?', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7', 'Cookie': '_xsrf=2|d5123503|a969671f7814f7aa7b32fcf25a82e429|1525129581; username-128-208-2-91-8888="2|1:0|10:1525129585|26:username-128-208-2-91-8888|44:ZjA1MzQwOGZjYzY3NDFkZDkyZjJkNmNhMDU2NjE4Yzg=|607eea8d35a1d6ff2fc1b7838e12c864a0c3eee10578862c30e339b15f53a2ab"'})
    Traceback (most recent call last):
      File "/homes/gws/domoritz/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/homes/gws/domoritz/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 2898, in wrapper
        return method(self, *args, **kwargs)
      File "/homes/gws/domoritz/anaconda3/lib/python3.6/site-packages/notebook/terminal/api_handlers.py", line 16, in post
        name, _ = self.terminal_manager.new_named_terminal()
      File "/homes/gws/domoritz/anaconda3/lib/python3.6/site-packages/terminado/management.py", line 319, in new_named_terminal
        term = self.new_terminal()
      File "/homes/gws/domoritz/anaconda3/lib/python3.6/site-packages/terminado/management.py", line 171, in new_terminal
        pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
      File "/homes/gws/domoritz/anaconda3/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 208, in spawn
        'executable: %s.' % command)
    FileNotFoundError: The command was not found or was not executable: /bin/fish.
[W 16:33:51.968 LabApp] Unhandled error
[E 16:33:51.969 LabApp] {
      "Host": "128.208.2.91:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Origin": "http://128.208.2.91:8888",
      "X-Xsrftoken": "2|d5123503|a969671f7814f7aa7b32fcf25a82e429|1525129581",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.18 Safari/537.36",
      "Dnt": "1",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://128.208.2.91:8888/lab?",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7",
      "Cookie": "_xsrf=2|d5123503|a969671f7814f7aa7b32fcf25a82e429|1525129581; username-128-208-2-91-8888=\"2|1:0|10:1525129585|26:username-128-208-2-91-8888|44:ZjA1MzQwOGZjYzY3NDFkZDkyZjJkNmNhMDU2NjE4Yzg=|607eea8d35a1d6ff2fc1b7838e12c864a0c3eee10578862c30e339b15f53a2ab\""
    }
[E 16:33:51.969 LabApp] 500 POST /api/terminals?1525131231944 (128.208.3.19) 10.28ms referer=http://128.208.2.91:8888/lab?
```

**Comment by domoritz** [comment]
I don't have this problem when I launch jupyterlab with bash as my shell.

**Comment by saulshanabrook** [comment]
I have fish shell and the console works for me. Does opening a terminal with jupyter notebook work on your server? You should be able to open one at `/terminals/1`.

**Comment by domoritz** [comment]
Could the problem be that my fish binary is not at /bin/fish but somewhere else in my path?

**Comment by saulshanabrook** [comment]
Likely yes, I just wonder where it is getting that path from then.

**Comment by domoritz** [comment]
I reinstalled fish, conda, jupyterlab and now everything works as expected. I will reopen this issue if I see the problem appearing again.
