### ISSUE TITLE
Can't Build Off Master

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4505]
I had previous experienced issues with my dev install off master.  Thanks to @saulshanabrook and @jasongrout  for noticing that my new error is unrelated.  I have pulled as of the time of this posting and get the follow error when I try to build after calling `pip install -e .; jlpm install`:

```
$ jlpm run build
yarn run v1.6.0
$ jlpm run build:dev
$ jlpm run integrity && jlpm run build:packages && jlpm run build:themes && cd dev_mode && jlpm run build
$ node buildutils/lib/ensure-repo.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/Users/forde/Documents/jupyter_docs/jupyterlab/buildutils/lib/ensure-repo.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jasongrout** [comment]
Can you double check if that ensure-repo.js file it's not finding is actually there in the directory it is looking for it?

**Comment by ian-r-rose** [comment]
Closing as stale, since there have been several releases since then. @jzf2101 feel free to reopen if this is still an issue.

**Comment by jzf2101** [comment]
yeah sorry this is stale yeah

**Comment by Notmeor** [comment]
@jzf2101 Same issue here, have you resolved it?
