### ISSUE TITLE
Jupyter Lab build hangs after installing extensions

### ISSUE THREAD

**Issue by neighthan** [jupyterlab/jupyterlab#4555]
I recently tried to install a couple of extensions like

```bash
jupyter labextension install @jupyterlab/latex
```

but the build part never finished. Here's the result of `jupyter labextension list`:
```
JupyterLab v0.32.1
Known labextensions:
   app dir: /home/nhunt/anaconda3/share/jupyter/lab
@jupyterlab/latex
        @jupyterlab/latex v0.3.1  enabled  OK
jupyterlab-toc
        jupyterlab-toc v0.2.0  enabled  OK

Build recommended, please run `jupyter lab build`:
    @jupyterlab/latex needs to be included in build
    jupyterlab-toc needs to be included in build
```

When I run `jupyter lab build` I get

```
[LabBuildApp] > node /home/nhunt/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "linux" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 53.68s.
[LabBuildApp] > node /home/nhunt/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.5.1
$ webpack --config webpack.prod.config.js
```

but the `webpack` command never returns (I've waited for it for at least 10 minutes - I don't think it should take longer than that?). When I interrupt it, this is the traceback:

```
^CTraceback (most recent call last):
  File "/home/nhunt/anaconda3/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1571, in start
    super(NotebookApp, self).start()
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 64, in start
    command=command, logger=self.log)
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 259, in build
    command=command, clean_staging=clean_staging)
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 403, in build
    self._run(['node', YARN_PATH, 'run', command], cwd=staging)
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1278, in _run
    return proc.wait()
  File "/home/nhunt/anaconda3/lib/python3.6/site-packages/jupyterlab/process.py", line 108, in wait
    time.sleep(1.)
KeyboardInterrupt
```

Any idea why this doesn't finish / how I can debug this?

Here's a bit about my versions:
```
$ jupyter lab --version
0.32.1
$ jupyter notebook --version
5.4.1
$ node --version
v8.11.1
```

This is all on the Windows Subsystem for Linux; I don't know if that might cause any weird things.

**Comment by neighthan** [comment]
Closing as this seems like a duplicate of #4276; I should have searched for the line in question earlier.
