### ISSUE TITLE
LabApp tries to modify global config file during importing

### ISSUE THREAD

**Issue by gdlmx** [jupyterlab/jupyterlab#4719]
During startup, JupyterLab scans for all locally installed or linked extensions and tries to modify the global config file `/share/lab/settings/build_config.json` if any local extension is missing. It will crash in multi-user environment because that file is (and should be) read-only. According to the following traceback, the modify attempt is triggered when `LabApp` is imported.

    **Note: Removing dead /opt/jlab-theme "@jupyterlab/theme-aixvipmap-extension"
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/jLab/bin/jupyter-labhub", line 7, in <module>
        from jupyterlab.labhubapp import main
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/labhubapp.py", line 2, in <module>
        from .labapp import LabApp
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/labapp.py", line 32, in <module>
        app_version = get_app_version()
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/commands.py", line 323, in get_app_version
        handler = _AppHandler(app_dir)
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/commands.py", line 338, in __init__
        self.info = self._get_app_info()
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/commands.py", line 701, in _get_app_info
        info['local_extensions'] = self._get_local_extensions()
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/commands.py", line 973, in _get_local_extensions
        return self._get_local_data('local_extensions')
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/commands.py", line 1107, in _get_local_data
        self._write_build_config(config)
      File "/opt/anaconda3/envs/jLab/lib/python3.6/site-packages/jupyterlab/commands.py", line 1068, in _write_build_config
        with open(target, 'w') as fid:
    PermissionError: [Errno 13] Permission denied: '/opt/anaconda3/envs/jLab/share/jupyter/lab/settings/build_config.json'

One would expect the Lab server to generate a warning message about the missing lab extensions instead of trying to change the config file that belongs to the administrator. More importantly, neither `import LabApp` nor `get_app_version` should modify any file on the system.

The following code lines are responsible for the error.

https://github.com/jupyterlab/jupyterlab/blob/296b92d5b72c2dd61c344da3b4ffa64296beba4b/jupyterlab/commands.py#L1107

**Comment by doutriaux1** [comment]
I'm running into the same error trying to load a docker image via shifter.

**Comment by danielballan** [comment]
Reproduced on JupyterLab 1.1.4

**Comment by mohammedi-haroune** [comment]
I'm running into the same error, I've changed the access to the config file as a work around, is there any solution ?

**Comment by doutriaux1** [comment]
@mohammedi-haroune i found that publishing my extension to npm and then installing from npm seems to work. Please try and confirm.
