### ISSUE TITLE
Error: Adapting to protocol v5.1 

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#4777]
When I start JupyterLab in my container I've just started seeing `Adapting to protocol v5.1 ` messages cropping up in the server logs with corresponding websocket connection lost errors in the front-end:

```
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://204de7712a62:8888/?token=56da9ee4440a1503a020f58b6d8e9a5ff083d855ae1ce3c5&token=56da9ee4440a1503a020f58b6d8e9a5ff083d855ae1ce3c5
[I 14:39:11.033 LabApp] 302 GET /lab (10.200.18.81) 2.00ms
[I 14:39:20.994 LabApp] 302 POST /login?next=%2Flab (10.200.18.81) 2.00ms
[W 14:39:24.600 LabApp] 404 GET /iframes (10.200.18.81) 11.99ms referer=http://dc1thwn01:8888/lab
[I 14:39:26.324 LabApp] Build is up to date
[I 14:40:27.131 LabApp] Writing notebook-signing key to C:\Users\ContainerAdministrator\AppData\Roaming\jupyter\notebook_secret
[W 14:40:27.143 LabApp] Notebook jupyter/Pricing/ProfilePricing.ipynb is not trusted
[I 14:40:28.583 LabApp] Kernel started: 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:40:29.923 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:40:29.955 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:40:34.515 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:40:44.517 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:40:49.894 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:40:49.917 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:40:54.524 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:03.120 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:04.542 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:14.515 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:17.111 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:17.140 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:17.170 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:17.197 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:24.510 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:24.531 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:34.482 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:34.545 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:37.076 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:37.110 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:37.142 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:37.172 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:37.200 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:44.467 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:44.514 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:44.547 LabApp] Adapting to protocol v5.1 for kernel 4cf7c0bd-8a50-447a-9a86-51996812bb27
[I 14:41:47.178 LabApp] Interrupted...
[I 14:41:47.179 LabApp] Shutting down 1 kernel
[I 14:41:47.985 LabApp] Kernel shutdown: 4cf7c0bd-8a50-447a-9a86-51996812bb27
```
![image](https://user-images.githubusercontent.com/881019/41889671-24b3e99a-794f-11e8-8cb4-631cdf0dbf14.png)

After a while I see a `Server Connection Error` and JupyterLab becomes entirely unresponsive:

![image](https://user-images.githubusercontent.com/881019/41889851-1811fb2c-7950-11e8-8eeb-000b29100c12.png)

I suspect some networking problem on my end however I'm at a loss as to how to debug it so am soliciting any and all advice!

The problem is the same in incongnito mode or not in either FireFox (Quantum) or Chrome.

**Comment by dhirschfeld** [comment]
```
# packages in environment at C:\Miniconda3:
#
# Name                    Version                   Build  Channel
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterhub                0.9.0                    py36_0    conda-forge
jupyterlab                0.32.1                   py36_0
jupyterlab-github         0.6.0                     <pip>
jupyterlab-latex          0.3.1                     <pip>
jupyterlab_launcher       0.10.5                   py36_0
notebook                  5.5.0                    py36_0
```

**Comment by dhirschfeld** [comment]
Further testing has thrown up the below error:
```
[I 12:59:49.693 NotebookApp] Adapting to protocol v5.1 for kernel 7eff08b2-43fd-4b96-8723-d7355c948f0d
[I 12:59:49.710 NotebookApp] Adapting to protocol v5.1 for kernel 7eff08b2-43fd-4b96-8723-d7355c948f0d
Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\tornado\websocket.py", line 808, in wrapper
    yield fut
  File "C:\Miniconda3\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Miniconda3\lib\site-packages\tornado\websocket.py", line 810, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
[W 12:59:50.286 NotebookApp] Got events for closed stream None
[I 12:59:51.274 NotebookApp] Adapting to protocol v5.1 for kernel 7eff08b2-43fd-4b96-8723-d7355c948f0d
[I 12:59:51.330 NotebookApp] Adapting to protocol v5.1 for kernel 7eff08b2-43fd-4b96-8723-d7355c948f0d
```

**Comment by blink1073** [comment]
Hi @dhirschfeld, which kernel and version is this?  I'm assuming Windows 10?

**Comment by dhirschfeld** [comment]
It's a `windowsservercore:1803` image.

It's actually working now. IT insisted that there wasn't anything interfering with network traffic but it turns out there was :unamused:

Given that, I'm not sure there's anything to do here so I'm inclined to close. 

The only thing which might have helped is if there were some better error reporting around disconnections - is that something feasible?

**Comment by blink1073** [comment]
Yeah, it would.  We are switching  jupyter_server soon, mind raising an issue there? https://github.com/jupyter/jupyter_server

**Comment by dhirschfeld** [comment]
Done!
