### ISSUE TITLE
jupyter uninstall failing (hub-extension)

### ISSUE THREAD

**Issue by bikashdube** [jupyterlab/jupyterlab#4783]
yarn v1.5.1
node v8.11.3
npm 5.6.0
JupyterLab v0.32.1

Error is same if I want to install as well. I tried in place upgrade to yarn 1.7.0 but the error is same.

```
[4/4] Building fresh packages...
success Saved lockfile.
Done in 49.84s.
> node /etc/.pyenv/versions/3.6.4/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.5.1
$ webpack --config webpack.prod.config.js
module.js:549
    throw err;
    ^

Error: Cannot find module './lib/_stream_readable.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/etc/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/readable-stream/readable.js:12:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/etc/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/duplexify/index.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack --config webpack.prod.config.js
Directory: /etc/.pyenv/versions/3.6.4/share/jupyter/lab/staging
Output:
".
```

**Comment by jasongrout** [comment]
Is this still an issue?
