### ISSUE TITLE
not working with python3?

### ISSUE THREAD

**Issue by isalirezag** [jupyterlab/jupyterlab#4823]
I have python 3
![image](https://user-images.githubusercontent.com/12434910/42128558-53cd8aee-7c7c-11e8-9b40-fd31ff1e682f.png)

and i am trying to use jupytherlab with python 23 but it always show me this error everytime when i choose python3:
```
Traceback (most recent call last):
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/home/alireza/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/alireza/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alireza/anaconda2/envs/Py3/bin/python3': '/home/alireza/anaconda2/envs/Py3/bin/python3'

```

![image](https://user-images.githubusercontent.com/12434910/42128569-8d6c790e-7c7c-11e8-939d-79c75525c42d.png)

it works fine with pthon 2.
Funny fact is that when i select python 2 and check the python version inside the cell isee python 3:

![image](https://user-images.githubusercontent.com/12434910/42128582-c92d19c6-7c7c-11e8-9e19-4c5a47d0e971.png)

**Comment by jasongrout** [comment]
It looks to me like the kernel configuration is not set up right in Jupyter, not a JupyterLab frontend issue.

Do you see the same sort of issues with the classic notebook?

**Comment by isalirezag** [comment]
yes, the same story with jupyter notebook.
Any suggestion how to fix that? and how to fix that kernel thing?

**Comment by jasongrout** [comment]
To fix a kernel issue, I think the first thing to do is to do `jupyter kernelspec list` and see where the kernels are.
