### ISSUE TITLE
selenium_check broken on most recent release

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4873]
In https://github.com/jupyterlab/jupyterlab/pull/4735, I switched JupyterLab to run it's e2e tests using pupeteer instead of selenium. This requires the `chrome-test.js` file, which runs the tests. For some reason, this is not included on the version we published on PyPi:

```bash
(base) root@a446fde2f117:/# python -m jupyterlab.selenium_check --allow-root
[I 13:30:26.188 SeleniumApp] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 13:30:26.188 SeleniumApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[W 13:30:26.191 SeleniumApp] JupyterLab server extension not enabled, manually loading...
[I 13:30:26.192 SeleniumApp] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 13:30:26.192 SeleniumApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 13:30:26.197 SeleniumApp] Serving notebooks from local directory: /
[I 13:30:26.197 SeleniumApp] The Jupyter Notebook is running at:
[I 13:30:26.197 SeleniumApp] http://127.0.0.1:8888/foo/?token=02dde823670d5f6c7c85f0d7fece1c840d324c2637af6c7b
[I 13:30:26.198 SeleniumApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:30:26.199 SeleniumApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://127.0.0.1:8888/foo/?token=02dde823670d5f6c7c85f0d7fece1c840d324c2637af6c7b
module.js:549
    throw err;
    ^

Error: Cannot find module '/opt/conda/lib/python3.6/site-packages/jupyterlab/chrome-test.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
[I 13:30:26.536 SeleniumApp] Shutting down 0 kernels
```

**Comment by blink1073** [comment]
Needs to be added to the [manifest](https://github.com/jupyterlab/jupyterlab/blob/2f1c3d0335367d48527941a0154e0e7bc0365636/MANIFEST.in).

**Comment by saulshanabrook** [comment]
@blink1073  Do you think https://github.com/jupyterlab/jupyterlab/pull/4874 will fix it?

**Comment by blink1073** [comment]
Ah, yep, forgot about that little guy.
