### ISSUE TITLE
Build Failed under 0.33.1

### ISSUE THREAD

**Issue by horsto** [jupyterlab/jupyterlab#4992]
Just tried a rebuild after updating to 0.33.1 and ran into the following error. Jupyter lab was installed via conda. Any ideas?

```W 15:57:29.497 LabApp] Build recommended
[W 15:57:29.497 LabApp] jupyter-matplotlib needs to be included in build
[W 15:57:32.687 LabApp] Build failed, running a clean and rebuild
[W 15:57:32.687 LabApp] 500 POST /lab/api/build?1532786251668 (::1): [WinError 3] The system cannot find the path specified: 'C:\\Users\\horsto\\AppData\\Local\\conda\\conda\\envs\\analysis\\share\\jupyter\\lab\\staging\\node_modules\\jupyter-matplotlib\\node_modules\\.cache\\uglifyjs-webpack-plugin\\content-v2\\sha512\\1b\\7f\\707b368483003ea3ed7d06267d3b1a046d0475617913b477c2852ba74d40e951e6eaf980d95d93160914c59bc9e3e8732d04f0339fbe7ea9348b943f2fc6'
[W 15:57:32.687 LabApp] [WinError 3] The system cannot find the path specified: 'C:\\Users\\horsto\\AppData\\Local\\conda\\conda\\envs\\analysis\\share\\jupyter\\lab\\staging\\node_modules\\jupyter-matplotlib\\node_modules\\.cache\\uglifyjs-webpack-plugin\\content-v2\\sha512\\1b\\7f\\707b368483003ea3ed7d06267d3b1a046d0475617913b477c2852ba74d40e951e6eaf980d95d93160914c59bc9e3e8732d04f0339fbe7ea9348b943f2fc6'

**Comment by horsto** [comment]
Thanks, just tried `jupyter lab clean` but get the following output: 
```jupyter lab clean
Traceback (most recent call last):
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\Scripts\jupyter-lab-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\notebook\notebookapp.py", line 1671, in start
    super(NotebookApp, self).start()
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\jupyterlab\labapp.py", line 85, in start
    clean(self.app_dir)
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\jupyterlab\commands.py", line 267, in clean
    shutil.rmtree(target)
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 5 more times]
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\horsto\\AppData\\Local\\conda\\conda\\envs\\analysis\\share\\jupyter\\lab\\staging\\node_modules\\jupyter-matplotlib\\node_modules\\.cache\\uglifyjs-webpack-plugin\\content-v2\\sha512\\1b\\7f\\707b368483003ea3ed7d06267d3b1a046d0475617913b477c2852ba74d40e951e6eaf980d95d93160914c59bc9e3e8732d04f0339fbe7ea9348b943f2fc6'

**Comment by jasongrout** [comment]
Can you try removing that file manually? Is there something wrong with that file?

You can delete the whole node_modules directory: `C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\share\jupyter\lab\staging\node_modules\
`

**Comment by horsto** [comment]
Ok, so I tried to delete the `node_modules` folder and that reveiled I think where the problem was. The filename apparently was too long for windows: 

![too_long](https://user-images.githubusercontent.com/7548928/43358244-ab2952fa-928e-11e8-80a8-b9102ea3e0b6.PNG)

There were several of these under: 
_C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\share\jupyter\lab\staging\node_modules\jupyter-matplotlib\node_modules\.cache\uglifyjs-webpack-plugin\content-v2\sha512_

I succeeded to delete them manually and was able to call `jupyter lab clean` and then `jupyter lab build`. 

However: 
Although I see a message displayed `Build successfully completed, reload page?` and reload - the message `Build Recommended` re-appears. I see the following message in the console:
``` [W 17:53:00.503 LabApp] Build recommended
[W 17:53:00.503 LabApp] jupyter-matplotlib needs to be included in build
[W 17:53:05.010 LabApp]
    "@jupyter-widgets/jupyterlab-manager@0.35.0" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension        Package
    >=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
    >=2.0.2 <3.0.0          >=1.1.0 <2.0.0   @jupyterlab/coreutils
    >=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
    >=0.17.3 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/rendermime
    >=3.0.3 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services


[I 17:53:05.010 LabApp] > node C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[I 17:53:34.197 LabApp] > node C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
'webpack' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.``

**Comment by blink1073** [comment]
I've followed these instructions successfully before: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by apoorvalal** [comment]
I'm getting a similar error on ubuntu 16.04 LTS. 
Running `jupyter lab clean` followed by `jupyter lab build` throws a timout:

```
An unexpected error occurred "https://registry.yarnpkg.com/@jupyterlab%2fapplication: ETIMEDOUT"
```

The full bug report is:
[yarn-error.log](https://github.com/jupyterlab/jupyterlab/files/2238112/yarn-error.log)

**Comment by horsto** [comment]
Things work now - and I don't quite know why (I restarted most of what I had open). Building finished successfully and I don't see any (obvious) errors / warning anymore. 

Thanks @blink1073 - will give that a try.

**Comment by blink1073** [comment]
@apoorvalal, I tried `jupyter lab clean && jupyter lab build` on MacOS 10.13.5 with the latest release and it works fine.  Perhaps it was a temporary issue with `yarnpkg.org`, do you mind trying again?

**Comment by apoorvalal** [comment]
It still gives me the same error. The error is slightly different when on ethernet vs wifi: it fails quietly on ethernet, while it says `there appears to be trouble with your network connection` while on wifi. really bizarre. 
I think it might be a problem on the node/yarn end of things, so I updated both, but i keep getting the same error.

**Comment by jasongrout** [comment]
Be careful to not use node 10. Right now jlab's yarn only works with node < 10.
