### ISSUE TITLE
Error: Cannot find module './lib/_stream_readable.js'

### ISSUE THREAD

**Issue by bikashdube** [jupyterlab/jupyterlab#5022]
node -v
v8.11.3

npm -v
5.6.0

jupyterlab-hub-extension-0.10.0
jupyterlab-0.33.4 
jupyterlab-launcher-0.11.2

Getting this while trying to install hub-extension
```
warning Your current version of Yarn is out of date. The latest version is "1.9.2", while you're on "1.6.0".
Done in 57.64s.
> node /.pyenv/versions/3.6.4/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:244
          throw err;
          ^

Error: Cannot find module './lib/_stream_readable.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/readable-stream/readable.js:12:30)
    at Module._compile (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/duplexify/index.js:1:76)
    at Module._compile (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/pumpify/index.js:3:17)
    at Module._compile (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/mississippi/index.js:3:27)
    at Module._compile (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by blink1073** [comment]
Hi @bikashdube, I've not see that one.  What OS are you on?

**Comment by bikashdube** [comment]
cat /proc/version
```
Linux version 2.6.32-696.18.7.el6.x86_64 (mockbuild@x86-042.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Thu Dec 28 20:15:47 EST 2017```

 cat /etc/redhat-release
```
Red Hat Enterprise Linux Server release 6.9 (Santiago)```

**Comment by bikashdube** [comment]
The problem I think has been because we are not using a system wide Python for this, but .pyenv
I was hoping with the updated JupyterLab release and its Yarn dependency everything would get solved, but this error is not going away even after the upgrade.

**Comment by blink1073** [comment]
Can you please try `jupyter lab clean && jupyter labextension install @jupyterlab/hub-extension`?

**Comment by bikashdube** [comment]
Thanks just tried it and it fails with the same error

**Comment by blink1073** [comment]
How did you install `node`, through `yum`?

**Comment by bikashdube** [comment]
Yes and it was run by the system administrator.

```
curl -sL https://rpm.nodesource.com/setup_8.x | bash -
yum install -y nodejs
```

**Comment by blink1073** [comment]
Hmm, I had no trouble on Ubuntu 18.04 this morning, will have to try with Red Hat.

**Comment by bikashdube** [comment]
[CentOS 6.9](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS6.9) might be a better choice if suspect this is something OS related. CentOS6.9 is based on RHEL Santiago.

**Comment by blink1073** [comment]
Thanks for the heads up

**Comment by blink1073** [comment]
I tried on CentOS 6.9 with the following:

```
$ node -v
v8.111.v

$ npm -v
5.6.0

$ python -V
Python 3.5.1
```

I used the `scl` version of Python 3.5 and `pip install --user jupyterlab cookiecutter` and then followed the instructions in the JupyterLab notebook example.  I was not able to replicate the issue.

**Comment by bikashdube** [comment]
Fixed with this combination in our environment. Not sure which package update did the trick but we will take it. Please close this if you are able to identify the root cause or any other pertinent info.

```
node -v
v8.11.3
```
```
npm -v
5.6.0
```
```
python -V
Python 3.6.4
```
```
jupyterlab-hub-extension-0.11.0
jupyterlab-v0.34.12
jupyterlab-launcher-0.13.1
```
```
pip install --upgrade pip
pip install --upgrade jupyter
pip install --upgrade jupyterhub
pip install --upgrade jupyterlab
pip install --upgrade notebook
jupyter labextension update --all
```

**Comment by jasongrout** [comment]
Thanks for posting your upgrade, glad it's working!
