### ISSUE TITLE
TypeError(s): "n.indexOf is not a function" (phosphor/signalling - jupyterlab/services) + "n.default is undefined"

### ISSUE THREAD

**Issue by mprogram** [jupyterlab/jupyterlab#5070]
I'm putting the raw output(s) (sorry for not providing a better way to report it) from the Firefox's Web Console upon starting the latest jupyterlab, if someone needs more information:
```
webpack:///node_modules/@phosphor/signalling/lib/index.js:220

TypeError: "n.indexOf is not a function"

  onLintMessage http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:632:713668
  v             http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:856:27859
  u             http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:856:27537
  emit          http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:856:25619
  onmessage     http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:878:11617

qUp9/</</t.exceptionHandler     webpack:///node_modules/@phosphor/signalling/lib/index.js:220
v                               webpack:///node_modules/@phosphor/signalling/lib/index.js:478
u                               webpack:///node_modules/@phosphor/signalling/lib/index.js:433
qUp9/</i</e.prototype.emit      webpack:///node_modules/@phosphor/signalling/lib/index.js:106
_initializeSocket/</t.onmessage webpack:///node_modules/@jupyterlab/services/lib/terminal/default.js:178
```
```
webpack:///build/index.out.js:1995

TypeError: "n.default is undefined"

  sjUu http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:871:213876
  h    http://localhost:8888/lab/static/main.5f72ce1802d038bf5221.js:1:897
  Dcwf http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:306:365056
  h    http://localhost:8888/lab/static/main.5f72ce1802d038bf5221.js:1:897
  a    http://localhost:8888/lab/static/main.5f72ce1802d038bf5221.js:1:33353

a webpack:///build/index.out.js:1995
```

**Comment by blink1073** [comment]
Hi @mprogram, what is the output of `jupyter labextension list`, and what OS/browser are you using?

**Comment by mprogram** [comment]
Presently it is (for a comprehensive info: `git`, `celltags`, `threejs` – do not work for now, `volume` could not be found and `webrtc` errors on absent `labplugin` <don't know why, both are installed/enabled>, `geojson` was changed to use `mapboxgl` by default, `sidecar` gives in the build log mixed/outdated messages, `sos` <…>, and `vdom` is just for fun; on `vpython` I opened the issue – but disabling _all those_ doesn't change the picture):

`# jupyter labextension list`
```
JupyterLab v0.33.6
Known labextensions:
   app dir: ~/.jupyter/lab
@enki-portal/gitlab
        @enki-portal/gitlab v0.2.2  enabled  OK
@ijmbarr/jupyterlab_spellchecker
        @ijmbarr/jupyterlab_spellchecker v0.1.1  enabled  OK
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.36.0  enabled  OK
@jupyter-widgets/jupyterlab-sidecar
        @jupyter-widgets/jupyterlab-sidecar v0.1.0  enabled  OK
@jupyterlab/celltags
        @jupyterlab/celltags v0.1.0  enabled  OK
@jupyterlab/fasta-extension
        @jupyterlab/fasta-extension v0.17.1  enabled  OK
@jupyterlab/geojson-extension
        @jupyterlab/geojson-extension v0.17.0  enabled  OK
@jupyterlab/git
        @jupyterlab/git v0.1.3  enabled  OK
@jupyterlab/github
        @jupyterlab/github v0.8.0  enabled  OK
@jupyterlab/google-drive
        @jupyterlab/google-drive v0.13.0  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.9.2  enabled  OK
@jupyterlab/katex-extension
        @jupyterlab/katex-extension v0.17.0  enabled  OK
@jupyterlab/mathjax3-extension
        @jupyterlab/mathjax3-extension v0.1.0  enabled  OK
@jupyterlab/plotly-extension
        @jupyterlab/plotly-extension v0.17.0  enabled  OK
@jupyterlab/shortcutui
        @jupyterlab/shortcutui v0.1.0  enabled  OK
@jupyterlab/statusbar
        @jupyterlab/statusbar v0.1.1  enabled  OK
@jupyterlab/toc
        @jupyterlab/toc v0.3.1  enabled  OK
@jupyterlab/vdom-experimental-extension
        @jupyterlab/vdom-experimental-extension v0.15.7  enabled  OK
@jupyterlab/vega2-extension
        @jupyterlab/vega2-extension v0.17.0  enabled  OK
@jupyterlab/vega3-extension
        @jupyterlab/vega3-extension v0.17.0  enabled  OK
@pyviz/jupyterlab_pyviz
        @pyviz/jupyterlab_pyviz v0.6.0  enabled  OK
bqplot
        bqplot v0.4.0  enabled  OK
ipyevents
        ipyevents v1.4.0-0  enabled  OK
ipysheet
        ipysheet v0.2.0  enabled  OK
jupyter-leaflet
        jupyter-leaflet v0.9.0  enabled  OK
jupyter-matplotlib
        jupyter-matplotlib v0.4.0  enabled  OK
jupyter-threejs
        jupyter-threejs v1.1.0  enabled  OK
jupyter-webrtc
        jupyter-webrtc v0.3.0  enabled  OK
jupyterlab-chart-editor
        jupyterlab-chart-editor v0.2.0  enabled  OK
jupyterlab-datawidgets
        jupyterlab-datawidgets v5.0.1  enabled  OK
jupyterlab-flake8
        jupyterlab-flake8 v0.2.2  enabled  OK
jupyterlab-kernelspy
        jupyterlab-kernelspy v0.2.0  enabled  OK
jupyterlab-scales
        jupyterlab-scales v0.2.1  enabled  OK
jupyterlab-sos
        jupyterlab-sos v0.2.1  enabled  OK
jupyterlab-volume
        jupyterlab-volume v0.4.0  enabled  OK
jupyterlab_vpython_test
        jupyterlab_vpython_test v0.1.0  enabled  OK
plotlywidget
        plotlywidget v0.2.0  enabled  OK
```
`# uname -a`
`Linux work 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mprogram** [comment]
_UPDATE: I've updated to `ipywidgets 7.4.0` and disabled the following extensions to reduce the log noise_
``` json
{
    "disabledExtensions": [
        "@jupyterlab/celltags",
        "@jupyter-widgets/jupyterlab-sidecar",
        "@jupyterlab/git",
        "@jupyterlab/vdom-experimental-extension",
        "jupyterlab_vpython_test",
        "jupyterlab-sos",
        "jupyterlab-volume",
        "jupyter-webrtc"
    ]
}
```
Now I see only the first error:
```
webpack:///node_modules/@phosphor/signalling/lib/index.js:220

TypeError: "n.indexOf is not a function"

  onLintMessage http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:632:713668
  v             http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:856:27859
  u             http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:856:27537
  emit          http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:856:25619
  onmessage     http://localhost:8888/lab/static/vendors~main.4e858f08547f7556fe16.js:878:11617

qUp9/</</t.exceptionHandler     webpack:///node_modules/@phosphor/signalling/lib/index.js:220
v                               webpack:///node_modules/@phosphor/signalling/lib/index.js:478
u                               webpack:///node_modules/@phosphor/signalling/lib/index.js:433
qUp9/</i</e.prototype.emit      webpack:///node_modules/@phosphor/signalling/lib/index.js:106
_initializeSocket/</t.onmessage webpack:///node_modules/@jupyterlab/services/lib/terminal/default.js:178
```

**Comment by blink1073** [comment]
Can you please post some lines surrounding 632 in your vendors bundle?

**Comment by mprogram** [comment]
Shurely, 
line 632 (truncated with …) is the one containinglang `LocaleCode:"es-NI"`
```
…
/*!
 * numbro.js language configuration
 * language : Slovene
 * locale: Slovenia
 * author : Tim McIntosh (StayinFront NZ)
 */
(function(){"use strict";var t={langLocaleCode:"sl",cultureCode:"sl",delimiters:{thousands:".",decimal:","}…
/*!
 * numbro.js language configuration
 * language : Spanish
 * locale: Nicaragua
 * author : Gwyn Judd : https://github.com/gwynjudd
 */
(function(){"use strict";var t={langLocaleCode:"es-NI",cultureCode:"es-NI",delimiters:{thousands:",",decimal:"."}…
/** @license React v16.2.0
 * react.production.min.js
 *
 * Copyright (c) 2013-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var n=r("MgzW"),i=r("t33a"),a=r("ohE5"),o="function"===typeof Symbol&&Symbol["for"],s=o?Symbol["for"]("react.element")…
…
//# sourceMappingURL=vendors~main.98e4175f02de56df98f8.js.map
```

**Comment by blink1073** [comment]
Hmm, that doesn't shed any light unfortunately.  That's a heck of a long list of extensions that might be contributing to the problem.  I think it is happening [here](https://github.com/jupyterlab/jupyterlab/blob/79ec988ccdde8de7889398d3ae58fd58721614d4/packages/services/src/terminal/default.ts#L208), either in the emit or the creation of the emit.  

Does this only happen when you open a terminal?

**Comment by jasongrout** [comment]
Can you do a `jupyter lab build --dev-mode`, and then post the lines with the error? It's hard to tell where the error is with the production build.

**Comment by mprogram** [comment]
Just did it. I'm not getting that error if the lab was built in the `--dev` mode. `"Download the React DevTools for a better development experience: https://fb.me/react-devtools"` shows up in the Chrome console instead. 
```
vendors~main.32f2fb9c79a1b2f01f13.js:854527 Download the React DevTools for a better development experience: https://fb.me/react-devtools
vendors~main.32f2fb9c79a1b2f01f13.js:591190 Download the React DevTools for a better development experience: https://fb.me/react-devtools
vendors~main.32f2fb9c79a1b2f01f13.js:1177176 Download the React DevTools for a better development experience: https://fb.me/react-devtools
vendors~main.32f2fb9c79a1b2f01f13.js:227782 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error    at checkDeprecatedMixinEvents (http://localhost:8888/lab/static/vendors~main.32f2fb9c79a1b2f01f13.js:227784:47)
    at Function.push.4R65.Class.extend (http://localhost:8888/lab/static/vendors~main.32f2fb9c79a1b2f01f13.js:227712:3)
    at Object.OTXi (http://localhost:8888/lab/static/vendors~main.32f2fb9c79a1b2f01f13.js:676342:32)
    at __webpack_require__ (http://localhost:8888/lab/static/main.e66393912e88cafe886f.js:84:30)
    at Object.O3wJ (http://localhost:8888/lab/static/vendors~main.32f2fb9c79a1b2f01f13.js:671332:1)
    at __webpack_require__ (http://localhost:8888/lab/static/main.e66393912e88cafe886f.js:84:30)
    at Object.xtrE (http://localhost:8888/lab/static/vendors~main.32f2fb9c79a1b2f01f13.js:1214167:18)
    at __webpack_require__ (http://localhost:8888/lab/static/main.e66393912e88cafe886f.js:84:30)
    at Object.12aA (http://localhost:8888/lab/static/vendors~main.32f2fb9c79a1b2f01f13.js:27923:23)
    at __webpack_require__ (http://localhost:8888/lab/static/main.e66393912e88cafe886f.js:84:30)
checkDeprecatedMixinEvents @ vendors~main.32f2fb9c79a1b2f01f13.js:227782
vendors~main.32f2fb9c79a1b2f01f13.js:885103 Download the React DevTools for a better development experience: https://fb.me/react-devtools
vendors~main.32f2fb9c79a1b2f01f13.js:1158104 jupyterlab-hub: No configuration found.
vendors~main.32f2fb9c79a1b2f01f13.js:935527 Starting application in workspace: [default: /lab]
vendors~main.32f2fb9c79a1b2f01f13.js:656216 Attempting to load spellchecker
vendors~main.32f2fb9c79a1b2f01f13.js:656218 Spellchecker Loaded  SpellChecker
vendors~main.32f2fb9c79a1b2f01f13.js:892394 User name = 
(anonymous) @ vendors~main.32f2fb9c79a1b2f01f13.js:892394 
vendors~main.32f2fb9c79a1b2f01f13.js:892397 User code = 
(anonymous) @ vendors~main.32f2fb9c79a1b2f01f13.js:892397 
vendors~main.32f2fb9c79a1b2f01f13.js:892400 Group name = 
(anonymous) @ vendors~main.32f2fb9c79a1b2f01f13.js:892400
vendors~main.32f2fb9c79a1b2f01f13.js:593435 Warning: Google Realtime has been deprecated. No new realtime applications may be registered, and existing ones will cease to work in December 2018
settingRegistry.load.then.settings @ vendors~main.32f2fb9c79a1b2f01f13.js:593435
vendors~main.32f2fb9c79a1b2f01f13.js:656208 Dictionary Loaded  en_Us
default.js:61 Starting WebSocket: ws://localhost:8888/api/kernels/1ce96011-d2c0-45d1-b92b-980c3b26d898
default.js:61 Starting WebSocket: ws://localhost:8888/api/kernels/1ce96011-d2c0-45d1-b92b-980c3b26d898
default.js:61 Starting WebSocket: ws://localhost:8888/api/kernels/1ce96011-d2c0-45d1-b92b-980c3b26d898
default.js:1432 Kernel: connected (1ce96011-d2c0-45d1-b92b-980c3b26d898)
default.js:1432 Kernel: connected (1ce96011-d2c0-45d1-b92b-980c3b26d898)
default.js:1432 Kernel: connected (1ce96011-d2c0-45d1-b92b-980c3b26d898)
default.js:928 Exception opening new comm
(anonymous) @ default.js:928 
rejected @ default.js:7
Promise.then (async)
step @ default.js:8
(anonymous) @ default.js:9
push.YC29.__awaiter @ default.js:5
_handleCommOpen @ default.js:913
(anonymous) @ default.js:1020
(anonymous) @ default.js:9
push.YC29.__awaiter @ default.js:5
_handleMessage @ default.js:977
_msgChain._msgChain.then @ default.js:124
Promise.then (async)
DefaultKernel._onWSMessage @ default.js:121
default.js:129 Error: Object 'jupyter.widget' not found in registry
    at Promise (default.js:1476) 
    at new Promise (<anonymous>)
    at Object.loadObject (default.js:1455)
    at DefaultKernel.<anonymous> (default.js:921)
    at Generator.next (<anonymous>)
    at default.js:9
    at new Promise (<anonymous>)
    at push.YC29.__awaiter (default.js:5)
    at new Promise (<anonymous>)
    at push.YC29.__awaiter (default.js:5)
    at DefaultKernel._handleMessage (default.js:977)
    at _msgChain._msgChain.then (default.js:124)
_msgChain._msgChain.then.catch.error @ default.js:129
Promise.catch (async)
DefaultKernel._onWSMessage @ default.js:126
```
_Note: `Exception opening new comm` and `Error: Object 'jupyter.widget' not found in registry` show up on the first opening the Animation example from pythreejs. On the second opening and run it fails on input 7 with `Error: Could not create a model`, but this is a subject matter of the issue on `pythreejs`_

I'll rebuild it back in the production mode to compare it with the above output (I did it before posting the issue) at my first opportunity.

**Comment by mprogram** [comment]
I cannot replicate the issue neither in the production, nor in the `dev` mode. It might have been connected to the disabled extensions (especially `jupyterlab-sidecar` needs to catch up with the development), pre-7.4.0 ipywidgets, or something else. Feel free to close this issue. 

However, `pythreejs` now gives a more meaningful error, which I'm going to post there.

**Comment by mprogram** [comment]
No longer the issue after various upgrades, closing. For future reference, I would recommend a "zero warnings" policy and also asking/posting JLab's build logs, paying special attention to the emitted warnings, which are not at all harmless.
