### ISSUE TITLE
Launching 0.34 on Chrome

### ISSUE THREAD

**Issue by willingc** [jupyterlab/jupyterlab#5159]
@blink1073 and folks,

I just installed 0.34. I'm having some 500 errors and I had to specify Python3 kernel as default. 

I'm not sure why I am getting symbolic link errors. 

It's a new miniconda installation as well.

```
$ jupyter lab
[I 04:26:42.477 LabApp] JupyterLab extension loaded from /Users/willingc/miniconda3/lib/python3.6/site-packages/jupyterlab
[I 04:26:42.477 LabApp] JupyterLab application directory is /Users/willingc/miniconda3/share/jupyter/lab
[W 04:26:42.481 LabApp] JupyterLab server extension not enabled, manually loading...
[I 04:26:42.481 LabApp] JupyterLab extension loaded from /Users/willingc/miniconda3/lib/python3.6/site-packages/jupyterlab
[I 04:26:42.482 LabApp] JupyterLab application directory is /Users/willingc/miniconda3/share/jupyter/lab
[I 04:26:42.484 LabApp] Serving notebooks from local directory: /Users/willingc
[I 04:26:42.484 LabApp] The Jupyter Notebook is running at:
[I 04:26:42.484 LabApp] http://localhost:8888/?token=443e13c3492083e371e7b139b154524065010d56607e0a9f
[I 04:26:42.484 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:26:42.485 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=443e13c3492083e371e7b139b154524065010d56607e0a9f
[I 04:26:42.685 LabApp] Accepting one-time-token-authenticated connection from ::1
[E 04:26:43.644 LabApp] Uncaught exception GET /api/contents/?content=1&1534678003620 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678003620', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:26:43.650 LabApp] Unhandled error
[E 04:26:43.651 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 443e13c3492083e371e7b139b154524065010d56607e0a9f",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|c4ae6ff6|a69efc7e302732f55778505a46eb1b48|1534677822; username-localhost-8888=\"2|1:0|10:1534678003|23:username-localhost-8888|44:ZmI0NjJiZjVjYTM0NGZlMWE4NDYxNmVmYTc1MzFjNzk=|77631fcf2c4f3653786fef7babebe7149220cfed0552e9c66c031e073daa0767\""
    }
[E 04:26:43.651 LabApp] 500 GET /api/contents/?content=1&1534678003620 (::1) 26.64ms referer=http://localhost:8888/lab
[E 04:26:43.972 LabApp] Uncaught exception GET /api/contents/?content=1&1534678003963 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678003963', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:26:43.973 LabApp] Unhandled error
[E 04:26:43.973 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 443e13c3492083e371e7b139b154524065010d56607e0a9f",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|c4ae6ff6|a69efc7e302732f55778505a46eb1b48|1534677822; username-localhost-8888=\"2|1:0|10:1534678003|23:username-localhost-8888|44:ZTkyZTMzMDg5NTJmNDkzMTljZjFkN2RhOTVmMDc1NTU=|fc81ccb3e24825cab915032722b597a3fde0b418456ce4a6c388a1cc3b200261\""
    }
[E 04:26:43.973 LabApp] 500 GET /api/contents/?content=1&1534678003963 (::1) 5.97ms referer=http://localhost:8888/lab
[I 04:26:44.640 LabApp] Build is up to date
[I 04:26:58.570 LabApp] Kernel started: 01d3aa07-bc5b-42d5-b66e-380c19d16780
[I 04:26:59.053 LabApp] Adapting to protocol v5.1 for kernel 01d3aa07-bc5b-42d5-b66e-380c19d16780
[I 04:26:59.054 LabApp] Adapting to protocol v5.1 for kernel 01d3aa07-bc5b-42d5-b66e-380c19d16780
[E 04:27:22.345 LabApp] Uncaught exception GET /api/contents/?content=1&1534678042334 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678042334', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:27:22.346 LabApp] Unhandled error
[E 04:27:22.347 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 443e13c3492083e371e7b139b154524065010d56607e0a9f",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|c4ae6ff6|a69efc7e302732f55778505a46eb1b48|1534677822; username-localhost-8888=\"2|1:0|10:1534678037|23:username-localhost-8888|44:MTc0NjQ4YjQxYzRlNDU0NGI3ODE2NTA4ZmQxYzM2NTM=|8b004c03a77324a9615d6300793a4e79509f1abde3dc64589a10e5ec810542c0\""
    }
[E 04:27:22.347 LabApp] 500 GET /api/contents/?content=1&1534678042334 (::1) 9.07ms referer=http://localhost:8888/lab
[E 04:27:45.115 LabApp] Uncaught exception GET /api/contents/?content=1&1534678065105 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678065105', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:27:45.115 LabApp] Unhandled error
[E 04:27:45.116 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 443e13c3492083e371e7b139b154524065010d56607e0a9f",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|c4ae6ff6|a69efc7e302732f55778505a46eb1b48|1534677822; username-localhost-8888=\"2|1:0|10:1534678064|23:username-localhost-8888|44:MTJkMWZlOWM1MGQ5NGM2ZTllMGZlMTkyN2M5NzBlZGM=|179d7426eddf5b5c03f74ab93472b9f1d96c3dc63cfee86d0ed1b0de49251d6a\""
    }
[E 04:27:45.116 LabApp] 500 GET /api/contents/?content=1&1534678065105 (::1) 6.86ms referer=http://localhost:8888/lab
[E 04:27:56.422 LabApp] Uncaught exception GET /api/contents/?content=1&1534678076413 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678076413', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:27:56.423 LabApp] Unhandled error
[E 04:27:56.424 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 443e13c3492083e371e7b139b154524065010d56607e0a9f",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|c4ae6ff6|a69efc7e302732f55778505a46eb1b48|1534677822; username-localhost-8888=\"2|1:0|10:1534678073|23:username-localhost-8888|44:ZGFlZWI2Y2NjYTY1NGU2NjgxNGQ0YTE5ZmFkYWM2YmI=|1d3f9dd9302a67b7e59b93ab18c8d5a9f5925201cde86898862bf60be54b6af8\""
    }
[E 04:27:56.424 LabApp] 500 GET /api/contents/?content=1&1534678076413 (::1) 6.57ms referer=http://localhost:8888/lab
[I 04:28:44.039 LabApp] Saving file at /Untitled1.ipynb
[E 04:28:44.072 LabApp] Uncaught exception GET /api/contents/?content=1&1534678124054 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678124054', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:28:44.073 LabApp] Unhandled error
[E 04:28:44.074 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 443e13c3492083e371e7b139b154524065010d56607e0a9f",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|c4ae6ff6|a69efc7e302732f55778505a46eb1b48|1534677822; username-localhost-8888=\"2|1:0|10:1534678124|23:username-localhost-8888|44:NjBjN2VjM2Y5NmFmNDdiN2E0NzE5MjQ1ZWFjMmQ3NDA=|0f979ad9ebc13a1038ccd6ece8629e392377b81a24108a6bf2fcfb988b9d8503\""
    }
[E 04:28:44.074 LabApp] 500 GET /api/contents/?content=1&1534678124054 (::1) 11.15ms referer=http://localhost:8888/lab
```

**Comment by blink1073** [comment]
Thanks, @willingc!  I'm about to be afk but I'll check it out later today.

**Comment by willingc** [comment]
Thanks @blink1073. Similar behavior within a conda environment:

```
$ jupyter lab --version
0.34.0
(myenv)
[04:39:27] willingc at Carols-MacBook-Pro in ~
$ jupyter lab
[I 04:39:35.168 LabApp] JupyterLab extension loaded from /Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/jupyterlab
[I 04:39:35.168 LabApp] JupyterLab application directory is /Users/willingc/miniconda3/envs/myenv/share/jupyter/lab
[W 04:39:35.178 LabApp] JupyterLab server extension not enabled, manually loading...
[I 04:39:35.179 LabApp] JupyterLab extension loaded from /Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/jupyterlab
[I 04:39:35.179 LabApp] JupyterLab application directory is /Users/willingc/miniconda3/envs/myenv/share/jupyter/lab
[I 04:39:35.183 LabApp] Serving notebooks from local directory: /Users/willingc
[I 04:39:35.183 LabApp] The Jupyter Notebook is running at:
[I 04:39:35.183 LabApp] http://localhost:8888/?token=48d32840cb9acfd2f4c6c8a857c0b3b7ba8c530701393768
[I 04:39:35.183 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:39:35.186 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=48d32840cb9acfd2f4c6c8a857c0b3b7ba8c530701393768
[I 04:39:35.388 LabApp] Accepting one-time-token-authenticated connection from ::1
[E 04:39:36.316 LabApp] Uncaught exception GET /api/contents/?content=1&1534678776293 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678776293', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:39:36.319 LabApp] Unhandled error
[E 04:39:36.320 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 48d32840cb9acfd2f4c6c8a857c0b3b7ba8c530701393768",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|d9a1be50|0e63d08de2aa5c427048fb1adbfcde55|1534678775; username-localhost-8888=\"2|1:0|10:1534678776|23:username-localhost-8888|44:OWI1YWY5MTg4MmE2NDJhMjk3OTNiOTkzZDgzZmVlNDI=|2d148d363586d204f0924b38bec0760e4abedb8bff6804b4957ad1cd3b971a5d\""
    }
[E 04:39:36.320 LabApp] 500 GET /api/contents/?content=1&1534678776293 (::1) 17.43ms referer=http://localhost:8888/lab
[E 04:39:36.696 LabApp] Uncaught exception GET /api/contents/?content=1&1534678776688 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678776688', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:39:36.697 LabApp] Unhandled error
[E 04:39:36.697 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 48d32840cb9acfd2f4c6c8a857c0b3b7ba8c530701393768",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|d9a1be50|0e63d08de2aa5c427048fb1adbfcde55|1534678775; username-localhost-8888=\"2|1:0|10:1534678776|23:username-localhost-8888|44:NWJhMzMzMGJhZWVkNGZjOTg1OGNlMTA5MzEyM2U4YmU=|36d13f836ab539bde40b1e9af0da59dceb5c281434ffedef59e6a7f032435466\""
    }
[E 04:39:36.697 LabApp] 500 GET /api/contents/?content=1&1534678776688 (::1) 6.31ms referer=http://localhost:8888/lab
[I 04:39:36.988 LabApp] Kernel started: 5f31f8d9-5d46-4aa1-9619-5362569334a3
[I 04:39:37.310 LabApp] Build is up to date
[I 04:39:37.714 LabApp] Adapting to protocol v5.1 for kernel 5f31f8d9-5d46-4aa1-9619-5362569334a3
[I 04:39:37.715 LabApp] Adapting to protocol v5.1 for kernel 5f31f8d9-5d46-4aa1-9619-5362569334a3
[E 04:40:06.948 LabApp] Uncaught exception GET /api/contents/?content=1&1534678806935 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678806935', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:40:06.949 LabApp] Unhandled error
[E 04:40:06.950 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 48d32840cb9acfd2f4c6c8a857c0b3b7ba8c530701393768",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|d9a1be50|0e63d08de2aa5c427048fb1adbfcde55|1534678775; username-localhost-8888=\"2|1:0|10:1534678805|23:username-localhost-8888|44:Y2ZhZTc3ODRiYTk0NGE5YmE5ZmI2YTQzYjlmNzIyODM=|b8f8071218b557f13d8c60723ed21a658a5d4ebd162d230f2ed117ce49c1d716\""
    }
[E 04:40:06.950 LabApp] 500 GET /api/contents/?content=1&1534678806935 (::1) 10.75ms referer=http://localhost:8888/lab
[E 04:40:17.383 LabApp] Uncaught exception GET /api/contents/?content=1&1534678817374 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1534678817374', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/Users/willingc/miniconda3/envs/myenv/lib/python3.6/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/willingc/MacBook'
[W 04:40:17.384 LabApp] Unhandled error
[E 04:40:17.385 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
      "Authorization": "token 48d32840cb9acfd2f4c6c8a857c0b3b7ba8c530701393768",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|d9a1be50|0e63d08de2aa5c427048fb1adbfcde55|1534678775; username-localhost-8888=\"2|1:0|10:1534678815|23:username-localhost-8888|44:YWM1ZGQ1N2ZlMjg5NDhlYmI3ZmFiMjVmNDk0ZjljM2E=|e1439fe663373aa6c0a741bb7f2ef7acaf445adf8845c23e1c1bee64b1002c2e\""
    }
[E 04:40:17.385 LabApp] 500 GET /api/contents/?content=1&1534678817374 (::1) 7.67ms referer=http://localhost:8888/lab
```

**Comment by willingc** [comment]
@blink1073 I think there was symlink cruft from conda. I wiped all and installed a new miniconda. All seems happier now. I'm going to close.

**Comment by blink1073** [comment]
Ye olde hard restart.  :wink:
