### ISSUE TITLE
Documentation for installing extensions seem to be incorrect

### ISSUE THREAD

**Issue by alex4200** [jupyterlab/jupyterlab#5160]
I have tried to install an extension for jupyterlab (Version 0.33.12) on Ubuntu 16.04.5, following the documentation given [here](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html). 

I followed the instructions to install `nodejs` (after I have installed `conda` following the instructions from [here](https://conda.io/docs/user-guide/install/linux.html) (miniconda to be more precise)) and then I found the following extension on the link on guthub:

`https://github.com/jupyter-widgets/ipywidgets`

So I used the following command 

`jupyter  labextension install ipywidgets --debug`

which resulted in the following output:

```
Searching [u'/home/adietz/Work/20_BSP/JupyterLab', '/home/adietz/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /usr/etc/jupyter
Looking for jupyter_config in /home/adietz/.jupyter
Looking for jupyter_config in /home/adietz/Work/20_BSP/JupyterLab
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/labextensions.py", line 79, in start
    ans = self.run_task()
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/labextensions.py", line 108, in run_task
    for arg in self.extra_args
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/commands.py", line 227, in install_extension
    _node_check()
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/commands.py", line 1470, in _node_check
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing. nodejs may be installed using conda or directly from the nodejs website.
```

So maybe the instructions for installing `conda` and/or `nodejs` is incomplete or outdated...

**Comment by blink1073** [comment]
Hi @alex4200, what does `node -v` show?

**Comment by alex4200** [comment]
`node -v` shows:

`v10.4.1`

**Comment by blink1073** [comment]
Ah, node 10 was not compatible with JupyterLab 0.33, can you please try with JupyterLab 0.34 (`pip install -U jupyterlab)`?

**Comment by alex4200** [comment]
This installed just `jupyterlab-0.33.12` ...

**Comment by blink1073** [comment]
Wow, that's odd, I published 0.34 on Saturday.  Does `pip install jupyterlab==0.34` give you an error saying it can't find the version?

**Comment by alex4200** [comment]
Yes, it says 

```
Collecting jupyterlab==0.34
  Could not find a version that satisfies the requirement jupyterlab==0.34 (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.13, 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.16.2, 0.17.0, 0.17.1, 0.17.2, 0.17.4, 0.17.5, 0.18.0.dev1, 0.18.0, 0.18.1, 0.19.0, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.0rc1, 0.21.0rc2, 0.21.0rc3, 0.21.0rc4, 0.21.0rc5, 0.21.0, 0.22.0rc0, 0.22.0, 0.22.1, 0.23.0rc0, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.0rc0, 0.24.0rc1, 0.24.0rc2, 0.24.0, 0.24.1, 0.25.0rc0, 0.25.0rc1, 0.25.0, 0.25.1, 0.25.2rc0, 0.25.2, 0.26.0rc0, 0.26.0rc1, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.26.5, 0.27.0rc0, 0.27.0rc1, 0.27.0rc2, 0.27.0rc3, 0.27.0rc4, 0.27.0rc5, 0.27.0, 0.27.1, 0.27.2, 0.28.0rc0, 0.28.0rc1, 0.28.0rc2, 0.28.0rc3, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.28.5, 0.28.6, 0.28.7, 0.28.8, 0.28.10, 0.28.11, 0.28.12, 0.28.13, 0.28.14, 0.28.15, 0.29.0rc0, 0.29.0, 0.29.1, 0.29.2, 0.30.0rc0, 0.30.0rc1, 0.30.0, 0.30.1, 0.30.2, 0.30.3, 0.30.4, 0.30.5, 0.30.6, 0.31.0rc0, 0.31.0rc1, 0.31.0rc2, 0.31.0, 0.31.1, 0.31.2, 0.31.3, 0.31.4, 0.31.5, 0.31.6, 0.31.7, 0.31.8, 0.31.9, 0.31.10, 0.31.11, 0.31.12, 0.32.0rc0, 0.32.0rc1, 0.32.0, 0.32.1, 0.33.0rc0, 0.33.0rc1, 0.33.0, 0.33.1, 0.33.2, 0.33.3, 0.33.4, 0.33.5, 0.33.6, 0.33.7, 0.33.8, 0.33.9, 0.33.10, 0.33.11, 0.33.12)
No matching distribution found for jupyterlab==0.34
```

**Comment by vidartf** [comment]
Newest lab does not support python 2, which is probably why `pip` does not list it.

**Comment by blink1073** [comment]
Ohhh, good catch @vidartf, thanks!

**Comment by blink1073** [comment]
cf #2096

**Comment by alex4200** [comment]
I just tried to uninstall jupyter lab with the following commands:

pip uninstall jupyterlab
pip3 uninstall jupyterlab
sudo pip uninstall jupyterlab
sudo pip3 uninstall jupyterlab

then reinstalled it by using the following command

```
pip install jupyterlab==0.34
```

just to see that something is not right:

```
jupyter lab --version
0.33.12
```

In fact, the old version was not removed. How to remove the old jupyter lab instance..?

**Comment by blink1073** [comment]
What does `which jupyter-lab` show?

**Comment by alex4200** [comment]
/usr/local/bin/jupyter-lab

**Comment by blink1073** [comment]
My recommendation would be to remove that final using `sudo`, then run `python3 -m pip install --user jupyterlab`

**Comment by alex4200** [comment]
@blink1073 Yes, now I have installed jupyter lab 0.34, but when I try to install an extension I get a different error message now...

```
$ jupyter labextension install ipywidgets --debug
Searching ['/home/adietz/Work/20_BSP/JupyterLab', '/home/adietz/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /usr/etc/jupyter
Looking for jupyter_config in /home/adietz/.jupyter
Looking for jupyter_config in /home/adietz/Work/20_BSP/JupyterLab
> /home/adietz/miniconda2/bin/npm pack ipywidgets
/home/adietz/miniconda2/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
Traceback (most recent call last):

  File "/home/adietz/.local/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 77, in start
    ans = self.run_task()

  File "/home/adietz/.local/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 106, in run_task
    for arg in self.extra_args

  File "/home/adietz/.local/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 106, in <listcomp>
    for arg in self.extra_args

  File "/home/adietz/.local/lib/python3.5/site-packages/jupyterlab/commands.py", line 221, in install_extension
    return handler.install_extension(extension)

  File "/home/adietz/.local/lib/python3.5/site-packages/jupyterlab/commands.py", line 413, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/adietz/.local/lib/python3.5/site-packages/jupyterlab/commands.py", line 1243, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "/home/adietz/.local/lib/python3.5/site-packages/jupyterlab/commands.py", line 1314, in _extract_package
    raise ValueError(msg % source)

ValueError: "ipywidgets" is not a valid npm package


Errored, use --debug for full output:
ValueError: "ipywidgets" is not a valid npm package
```

**Comment by blink1073** [comment]
The npm package name is different: `jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug`.  I opened an issue on [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/issues/2179).

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. @alex4200  - we haven't heard from you for a while, so I assume you were you able to resolve this issue on your own after Steve's last suggestion. Let us know if that's not the case.

Thanks everyone and happy hacking! :bowtie:
