### ISSUE TITLE
More extensions build issues

### ISSUE THREAD

**Issue by fkfertigprof** [jupyterlab/jupyterlab#5177]
Hi all

I'm also getting recurring extension build messages.

I've trawled through similar issues here, but nothing has resolved it for me.

**Here is the list of extensions.**  
(I had the same problem when only threejs datawidgets, and scales was listed.)  

```
(base) C:\>jupyter labextension list
JupyterLab v0.33.11
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
@jupyterlab/plotly-extension
        @jupyterlab/plotly-extension v0.17.1 enabled  ok
jupyter-threejs
        jupyter-threejs v1.1.0 enabled  ok
jupyterlab-datawidgets
        jupyterlab-datawidgets v5.0.1 enabled  ok
jupyterlab-scales
        jupyterlab-scales v0.2.1 enabled  ok
jupyterlab_bokeh
        jupyterlab_bokeh v0.6.1 enabled  ok

Build recommended, please run `jupyter lab build`:
    jupyter-threejs needs to be included in build
    jupyterlab-datawidgets needs to be included in build
    jupyterlab-scales needs to be included in build
    jupyterlab_bokeh needs to be included in build
    @jupyterlab/plotly-extension needs to be included in build
```

**When trying to build, I get the following output:**  

```
(base) C:\>jupyter lab build
[LabBuildApp] > node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > @mapbox/gl-matrix@0.0.1: This
warning @jupyterlab/plotly-extension > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0:
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 117.29s.
[LabBuildApp] > node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab/csvviewer' in 'C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer-extension\lib'
    at factory.create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\Compilation.js:535:10)
    at factory (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\neo-async\async.js:2817:7
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\neo-async\async.js:6783:13
    at normalResolver.resolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn41 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:381:1)
    at resolver.doResolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at args (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\forEachBail.js:30:14)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn42 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:393:1)
    at hook.callAsync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
resolve '@jupyterlab/csvviewer' in 'C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer-extension\lib'
  Parsed request is a module
  using description file: C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer-extension\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer-extension\lib\node_modules doesn't exist or is not a directory
      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer-extension\node_modules doesn't exist or is not a directory
      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\node_modules doesn't exist or is not a directory
      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\node_modules doesn't exist or is not a directory
      C:\ProgramData\Anaconda3\share\jupyter\lab\node_modules doesn't exist or is not a directory
      C:\ProgramData\Anaconda3\share\jupyter\node_modules doesn't exist or is not a directory
      C:\ProgramData\Anaconda3\share\node_modules doesn't exist or is not a directory
      C:\ProgramData\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules
        using description file: C:\ProgramData\Anaconda3\share\jupyter\lab\staging\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\ProgramData\Anaconda3\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\ProgramData\Anaconda3\share\jupyter\lab\staging\package.json (relative path: ./node_modules/@jupyterlab/csvviewer)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer is not a file
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
          C:\ProgramData\Anaconda3\node_modules\@jupyterlab\csvviewer doesn't exist
        .wasm
          Field 'browser' doesn't contain a valid alias configuration
              C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
          C:\ProgramData\Anaconda3\node_modules\@jupyterlab\csvviewer.wasm doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer.json doesn't exist
          C:\ProgramData\Anaconda3\node_modules\@jupyterlab\csvviewer.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          C:\ProgramData\Anaconda3\node_modules\@jupyterlab\csvviewer.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          C:\ProgramData\Anaconda3\node_modules\@jupyterlab\csvviewer.json doesn't exist
        as directory
          C:\ProgramData\Anaconda3\node_modules\@jupyterlab\csvviewer doesn't exist
            as directory
              existing directory
                using path: C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer\index
                  using description file: C:\ProgramData\Anaconda3\share\jupyter\lab\staging\package.json (relative path: ./node_modules/@jupyterlab/csvviewer/index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer\index doesn't exist
                    .wasm
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer\index.wasm doesn't exist
                    .mjs
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer\index.mjs doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer\index.js doesn't exist
                    .json
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer\index.json doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'd appreciate any pointers on how to fix this.

Kind regards,
Franz

**Comment by blink1073** [comment]
Hi @fkfertigprof, is there a `C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\csvviewer` folder?  Can you please paste the contents of `C:\ProgramData\Anaconda3\share\jupyter\lab\staging\package.json`?

**Comment by fkfertigprof** [comment]
Hi @blink1073,  
The folder seems to be in order:
![image](https://user-images.githubusercontent.com/37416633/44442946-59eb2580-a5d5-11e8-8fea-d83c7efdd910.png)
The content of package.json is:
```
{
    "name": "@jupyterlab/application-top",
    "version": "0.17.2",
    "private": true,
    "scripts": {
        "build": "webpack",
        "build:prod": "webpack --config webpack.prod.config.js",
        "build:prod:stats": "webpack --profile --config webpack.prod.config.js --json > stats.json",
        "build:stats": "webpack --profile --json > stats.json",
        "clean": "rimraf build",
        "prepublishOnly": "npm run build",
        "watch": "webpack --watch"
    },
    "dependencies": {
        "@jupyterlab/application": "^0.17.2",
        "@jupyterlab/application-extension": "^0.17.4",
        "@jupyterlab/apputils": "^0.17.2",
        "@jupyterlab/apputils-extension": "^0.17.2",
        "@jupyterlab/attachments": "^0.17.2",
        "@jupyterlab/cells": "^0.17.2",
        "@jupyterlab/codeeditor": "^0.17.2",
        "@jupyterlab/codemirror": "^0.17.3",
        "@jupyterlab/codemirror-extension": "^0.17.2",
        "@jupyterlab/completer": "^0.17.2",
        "@jupyterlab/completer-extension": "^0.17.2",
        "@jupyterlab/console": "^0.17.2",
        "@jupyterlab/console-extension": "^0.17.2",
        "@jupyterlab/coreutils": "^2.0.3",
        "@jupyterlab/csvviewer": "^0.17.2",
        "@jupyterlab/csvviewer-extension": "^0.17.2",
        "@jupyterlab/docmanager": "^0.17.2",
        "@jupyterlab/docmanager-extension": "^0.17.4",
        "@jupyterlab/docregistry": "^0.17.2",
        "@jupyterlab/extensionmanager": "^0.17.2",
        "@jupyterlab/extensionmanager-extension": "^0.17.2",
        "@jupyterlab/faq-extension": "^0.17.2",
        "@jupyterlab/filebrowser": "^0.17.3",
        "@jupyterlab/filebrowser-extension": "^0.17.4",
        "@jupyterlab/fileeditor": "^0.17.2",
        "@jupyterlab/fileeditor-extension": "^0.17.2",
        "@jupyterlab/help-extension": "^0.17.2",
        "@jupyterlab/imageviewer": "^0.17.2",
        "@jupyterlab/imageviewer-extension": "^0.17.2",
        "@jupyterlab/inspector": "^0.17.2",
        "@jupyterlab/inspector-extension": "^0.17.2",
        "@jupyterlab/javascript-extension": "^0.17.2",
        "@jupyterlab/json-extension": "^0.16.2",
        "@jupyterlab/launcher": "^0.17.2",
        "@jupyterlab/launcher-extension": "^0.17.2",
        "@jupyterlab/mainmenu": "^0.6.2",
        "@jupyterlab/mainmenu-extension": "^0.6.2",
        "@jupyterlab/markdownviewer-extension": "^0.17.2",
        "@jupyterlab/mathjax2-extension": "^0.5.2",
        "@jupyterlab/notebook": "^0.17.2",
        "@jupyterlab/notebook-extension": "^0.17.2",
        "@jupyterlab/observables": "^2.0.2",
        "@jupyterlab/outputarea": "^0.17.3",
        "@jupyterlab/pdf-extension": "^0.8.2",
        "@jupyterlab/rendermime": "^0.17.3",
        "@jupyterlab/rendermime-extension": "^0.11.2",
        "@jupyterlab/rendermime-interfaces": "^1.1.2",
        "@jupyterlab/running": "^0.17.3",
        "@jupyterlab/running-extension": "^0.17.2",
        "@jupyterlab/services": "^3.0.3",
        "@jupyterlab/settingeditor": "^0.6.2",
        "@jupyterlab/settingeditor-extension": "^0.12.2",
        "@jupyterlab/shortcuts-extension": "^0.17.3",
        "@jupyterlab/tabmanager-extension": "^0.17.2",
        "@jupyterlab/terminal": "^0.17.2",
        "@jupyterlab/terminal-extension": "^0.17.2",
        "@jupyterlab/theme-dark-extension": "^0.17.5",
        "@jupyterlab/theme-light-extension": "^0.17.3",
        "@jupyterlab/tooltip": "^0.17.2",
        "@jupyterlab/tooltip-extension": "^0.17.2",
        "@jupyterlab/vdom-extension": "^0.16.2",
        "@jupyterlab/vega4-extension": "^0.16.2",
        "@phosphor/algorithm": "^1.1.2",
        "@phosphor/application": "^1.6.0",
        "@phosphor/commands": "^1.5.0",
        "@phosphor/coreutils": "^1.3.0",
        "@phosphor/datagrid": "^0.1.6",
        "@phosphor/disposable": "^1.1.2",
        "@phosphor/domutils": "^1.1.2",
        "@phosphor/dragdrop": "^1.3.0",
        "@phosphor/messaging": "^1.2.2",
        "@phosphor/properties": "^1.1.2",
        "@phosphor/signaling": "^1.2.2",
        "@phosphor/virtualdom": "^1.1.2",
        "@phosphor/widgets": "^1.6.0",
        "ajv": "~5.1.6",
        "ansi_up": "^3.0.0",
        "codemirror": "~5.39.0",
        "comment-json": "^1.1.3",
        "es6-promise": "~4.1.1",
        "marked": "~0.4.0",
        "moment": "~2.21.0",
        "path-posix": "~1.0.0",
        "react": "~16.4.0",
        "react-dom": "~16.4.0",
        "react-paginate": "^5.2.3",
        "sanitize-html": "~1.14.3",
        "semver": "^5.5.0",
        "url-parse": "~1.4.3",
        "xterm": "~3.3.0",
        "jupyter-threejs": "file:../extensions/jupyter-threejs-1.1.0.tgz",
        "jupyterlab-datawidgets": "file:../extensions/jupyterlab-datawidgets-5.0.1.tgz",
        "@jupyterlab/plotly-extension": "file:../extensions/jupyterlab-plotly-extension-0.17.1.tgz",
        "jupyterlab-scales": "file:../extensions/jupyterlab-scales-0.2.1.tgz",
        "jupyterlab_bokeh": "file:../extensions/jupyterlab_bokeh-0.6.1.tgz"
    },
    "devDependencies": {
        "@jupyterlab/buildutils": "^0.8.2",
        "css-loader": "~0.28.7",
        "duplicate-package-checker-webpack-plugin": "^3.0.0",
        "file-loader": "~1.1.11",
        "fs-extra": "~4.0.2",
        "glob": "~7.1.2",
        "handlebars": "~4.0.11",
        "html-loader": "^0.5.1",
        "html-webpack-plugin": "~3.2.0",
        "raw-loader": "~0.5.1",
        "rimraf": "~2.6.2",
        "sort-package-json": "~1.7.1",
        "source-map-loader": "~0.2.1",
        "style-loader": "~0.21.0",
        "uglifyjs-webpack-plugin": "~1.2.5",
        "url-loader": "~1.0.1",
        "webpack": "~4.12.0",
        "webpack-cli": "^3.0.3",
        "webpack-merge": "^4.1.1"
    },
    "jupyterlab": {
        "extensions": {
            "@jupyterlab/application-extension": "",
            "@jupyterlab/apputils-extension": "",
            "@jupyterlab/codemirror-extension": "",
            "@jupyterlab/completer-extension": "",
            "@jupyterlab/console-extension": "",
            "@jupyterlab/csvviewer-extension": "",
            "@jupyterlab/docmanager-extension": "",
            "@jupyterlab/extensionmanager-extension": "",
            "@jupyterlab/faq-extension": "",
            "@jupyterlab/filebrowser-extension": "",
            "@jupyterlab/fileeditor-extension": "",
            "@jupyterlab/help-extension": "",
            "@jupyterlab/imageviewer-extension": "",
            "@jupyterlab/inspector-extension": "",
            "@jupyterlab/launcher-extension": "",
            "@jupyterlab/mainmenu-extension": "",
            "@jupyterlab/mathjax2-extension": "",
            "@jupyterlab/notebook-extension": "",
            "@jupyterlab/rendermime-extension": "",
            "@jupyterlab/running-extension": "",
            "@jupyterlab/settingeditor-extension": "",
            "@jupyterlab/shortcuts-extension": "",
            "@jupyterlab/tabmanager-extension": "",
            "@jupyterlab/terminal-extension": "",
            "@jupyterlab/theme-dark-extension": "",
            "@jupyterlab/theme-light-extension": "",
            "@jupyterlab/tooltip-extension": "",
            "jupyter-threejs": "src/jupyterlab-plugin",
            "jupyterlab-datawidgets": "",
            "jupyterlab-scales": "",
            "jupyterlab_bokeh": ""
        },
        "mimeExtensions": {
            "@jupyterlab/javascript-extension": "",
            "@jupyterlab/json-extension": "",
            "@jupyterlab/markdownviewer-extension": "",
            "@jupyterlab/pdf-extension": "",
            "@jupyterlab/vdom-extension": "",
            "@jupyterlab/vega4-extension": "",
            "@jupyterlab/plotly-extension": ""
        },
        "name": "JupyterLab",
        "buildDir": "./build",
        "outputDir": "..",
        "singletonPackages": [
            "@jupyterlab/application",
            "@jupyterlab/apputils",
            "@jupyterlab/console",
            "@jupyterlab/coreutils",
            "@jupyterlab/docmanager",
            "@jupyterlab/extensionmanager",
            "@jupyterlab/filebrowser",
            "@jupyterlab/fileeditor",
            "@jupyterlab/imageviewer",
            "@jupyterlab/launcher",
            "@jupyterlab/notebook",
            "@jupyterlab/rendermime",
            "@jupyterlab/rendermime-interfaces",
            "@jupyterlab/services",
            "@jupyterlab/terminal",
            "@jupyterlab/tooltip",
            "@phosphor/coreutils",
            "@phosphor/widgets"
        ],
        "vendor": [
            "@phosphor/algorithm",
            "@phosphor/application",
            "@phosphor/commands",
            "@phosphor/coreutils",
            "@phosphor/datagrid",
            "@phosphor/disposable",
            "@phosphor/domutils",
            "@phosphor/dragdrop",
            "@phosphor/messaging",
            "@phosphor/properties",
            "@phosphor/signaling",
            "@phosphor/virtualdom",
            "@phosphor/widgets",
            "ajv",
            "ansi_up",
            "codemirror",
            "comment-json",
            "es6-promise",
            "marked",
            "moment",
            "path-posix",
            "react",
            "react-dom",
            "react-paginate",
            "sanitize-html",
            "semver",
            "url-parse",
            "xterm"
        ],
        "version": "0.33.11",
        "linkedPackages": {},
        "staticDir": "../static"
    }
}
```

**Comment by blink1073** [comment]
@fkfertigprof, can you please try `jupyter lab clean && jupyter lab build` from a neutral (perhaps home) directory?

**Comment by saulshanabrook** [comment]
Please feel free to reopen if you have tried it on a new release and have more info.
