### ISSUE TITLE
Upgrading JupyterLab to 0.34.1 causes crash on startup

### ISSUE THREAD

**Issue by vilim** [jupyterlab/jupyterlab#5187]
I tried to update the version of Jupyter Lab with conda, and after installing 0.34.1. the application does not start anymore, with the following error message appearing after any jupyter lab command:

```
>>> jupyter lab
Traceback (most recent call last):
  File "/Users/vilimstich/anaconda3/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/Users/vilimstich/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 32, in <module>
    app_version = get_app_version()
  File "/Users/vilimstich/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 343, in get_app_version
    handler = _AppHandler(app_dir)
  File "/Users/vilimstich/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 381, in __init__
    self.info = self._get_app_info()
  File "/Users/vilimstich/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 804, in _get_app_info
    info['extensions'] = extensions = self._get_extensions(core_data)
  File "/Users/vilimstich/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1068, in _get_extensions
    extensions = self._get_extensions_in_dir(self.sys_dir, core_data)
  File "/Users/vilimstich/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1094, in _get_extensions_in_dir
    url = data['repository'].get('url', '')
AttributeError: 'str' object has no attribute 'get'
```

Reverting to 0.33.8 fixes the problem.
I am running OS X.

**Comment by vidartf** [comment]
@bollwyvl That code was recently merged, and not extensively tested. I guess all uses of `name` should use `key` instead? Ref #5174

**Comment by vidartf** [comment]
@vilim The error occurs because the code assumes that the "[repository](https://docs.npmjs.com/files/package.json#repository)" field is an object/dict. Is there an extension where this is not the case? I guess the code could be hardened to not fail completely if one extension is (partially) invalid though.

**Comment by bollwyvl** [comment]
Package.json is one of those formats that just... is... Here's a notional
schema, but there are definitely installable, production-deployed packages
that don't conform:

http://json.schemastore.org/package

I guess we plan on _at least_ that level of crazy, but we basically can't
trust anything.

When it actually hits the big registry in the sky, it is normalized, but
let's _please_ not add any _more_ reliance on live servers for end users.

We have ajv and Jsonschema just hanging around. If we're talking just
labextensions, we could adopt/ship the above schema and add our own jupyter
fields, and not install anything that doesn't conform such that you
couldn't even _develop_ a non-conforming package, even if you could still
ship it.

As to key/name... Traveling, haven't been able to look into it!

**Comment by vidartf** [comment]
Added a commit to #5196 to check if field is a dict.
