### ISSUE TITLE
KeyError exception after installing JupyterLab 0.34.1

### ISSUE THREAD

**Issue by lebedov** [jupyterlab/jupyterlab#5191]
After installing JupyterLab 0.34.1 from conda-forge and starting it as usual via `jupyter lab`, I observed the following exception on the console:

```
Uncaught exception GET /lab/api/build?1534955760416 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/lab/api/build?1534955760416', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/jupyterlab/build_handler.py", line 111, in get
        data = yield self.builder.get_status()
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/jupyterlab/build_handler.py", line 37, in get_status
        messages = yield self._run_build_check(self.app_dir, self.log)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/lebedov/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/jupyterlab/build_handler.py", line 88, in _run_build_check
        return build_check(app_dir=app_dir, logger=logger)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 312, in build_check
        return handler.build_check()
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 540, in build_check
        new_package = self._get_package_template(silent=fast)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 978, in _get_package_template
        name = value['name']
    KeyError: 'name'
```

This problem did not occur with JupyterLab 0.34.0.

**Comment by micdonato** [comment]
It happens to me too. I cannot install extensions anymore, and the bokeh one is now broken.

**Comment by brasie** [comment]
I see the same error.

For me, it seems to be triggered by the presence of `nbdime`.  If I don't have `nbdime` installed, then I get no such exception.  Furthermore, with `nbdime` present, I cannot install lab extensions via `jupyter labextension install` or do `jupyter lab build` without getting the same error.

**Comment by ian-r-rose** [comment]
Reproducible steps:
```bash
pip install jupyterlab==0.33
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.36
pip install jupyterlab==0.34
jupyter lab build
```

**Comment by vilim** [comment]
Thank you for the quick responses! Uninstalling all extensions before upgrading jupyterlab (in my case jupyterlab manager, jupyter-matplotlib and julia-web-io) fixes the issue.

**Comment by lebedov** [comment]
After updating to JupyterLab 0.34.3, the problem appears to have been resolved.
