### ISSUE TITLE
labapp.py # AttributeError: 'LabApp' object has no attribute 'quit_button'

### ISSUE THREAD

**Issue by rddaz2013** [jupyterlab/jupyterlab#5246]
update jupyterlab with pip - after that i get this error.
After removing the line 206 - the app runs normaly

```
Traceback (most recent call last):
  File "/home/rened/anaconda3/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/home/rened/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/home/rened/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 206, in init_webapp
    *settings['page_config_data']['quit_button'] = self.quit_button*
AttributeError: 'LabApp' object has no attribute 'quit_button'
```

**Comment by harpone** [comment]
Having the exact same issue and same solution works.

**Comment by blink1073** [comment]
Ah, it looks like this property was renamed in Notebook 5.6.  I'll update our minimum compatible version.
