### ISSUE TITLE
Can't install any extension: AttributeError: full_url

### ISSUE THREAD

**Issue by rickystream94** [jupyterlab/jupyterlab#5283]
I'm trying to install extensions and whatever attempt fails with the following error message:
```
Errored, use --debug for full output:
AttributeError: full_url
```
A full stack trace for example when trying to install jupyterlab_bokeh:
```
user@hal:~$ jupyter labextension install jupyterlab_bokeh --debug
Searching [u'/home/user', '/home/user/.jupyter', '/home/user/anaconda2/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /home/user/anaconda2/etc/jupyter
Looking for jupyter_config in /home/user/.jupyter
Looking for jupyter_config in /home/user
> /home/user/anaconda2/bin/npm pack jupyterlab_bokeh
npm notice
npm notice 📦  jupyterlab_bokeh@0.6.2
npm notice === Tarball Contents ===
npm notice 1.2kB package.json
npm notice 1.5kB LICENSE.txt
npm notice 1.1kB README.md
npm notice 64B   lib/index.d.ts
npm notice 151B  lib/index.js
npm notice 540B  lib/manager.d.ts
npm notice 974B  lib/manager.js
npm notice 577B  lib/plugin.d.ts
npm notice 1.6kB lib/plugin.js
npm notice 1.4kB lib/renderer.d.ts
npm notice 4.9kB lib/renderer.js
npm notice === Tarball Details ===
npm notice name:          jupyterlab_bokeh
npm notice version:       0.6.2
npm notice filename:      jupyterlab_bokeh-0.6.2.tgz
npm notice package size:  4.6 kB
npm notice unpacked size: 14.0 kB
npm notice shasum:        080668537cc2dabb16ba7f7fc3ed68c7123599a8
npm notice integrity:     sha512-9qDpssWSFrT8o[...]cy9dA4UKWuklA==
npm notice total files:   11
npm notice
jupyterlab_bokeh-0.6.2.tgz
Traceback (most recent call last):

  File "/home/user/anaconda2/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 71, in start
    ans = self.run_task()

  File "/home/user/anaconda2/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "/home/user/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 227, in install_extension
    return handler.install_extension(extension)

  File "/home/user/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 366, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/user/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 1138, in _install_extension
    version = self._latest_compatible_package_version(name)

  File "/home/user/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 1202, in _latest_compatible_package_version
    metadata = _fetch_package_metadata(self.registry, name, self.logger)

  File "/home/user/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 1585, in _fetch_package_metadata
    logger.debug('Fetching URL: %s' % (req.full_url))

  File "/home/user/anaconda2/lib/python2.7/urllib2.py", line 254, in __getattr__
    raise AttributeError, attr

AttributeError: full_url


Errored, use --debug for full output:
AttributeError: full_url
```
I have JupyterLab v0.32.1 installed as part of Anaconda distribution with Python 2.7.

**Comment by rickystream94** [comment]
@blink1073 Sounds good, I switched to Python 3.6 and the installation seems to be fine 😃
