### ISSUE TITLE
Jupyter lab build fails, can't find file with 270 character path

### ISSUE THREAD

**Issue by aquirdTurtle** [jupyterlab/jupyterlab#5325]
Hello, 

`jupyter lab build` is currently failing for me, with the final error message 

`FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\npm\\node_modules\\libcipm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.js'`

After some digging, the file in question is exactly where this path indicates, but I noticed that the path is 270 characters long, which might be the issue considering the default 260 character path limit in windows (using windows 10). I'm pasting the full error message below. I'm on Jupyter lab version 0.34.9, Jupyter version 4.4.0. Also, probably related, `jupyter labextension update --all` currently fails silently for me.  See the following chain of commands:

```
PS C:\WINDOWS\system32> jupyter labextension list
JupyterLab v0.34.9
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
        jupyterlab-toc v0.2.1 enabled   X

   The following extension are outdated:
        jupyterlab-toc

   Consider running "jupyter labextension update --all" to check for updates.

PS C:\WINDOWS\system32> jupyter labextension update --all
PS C:\WINDOWS\system32> jupyter labextension list
JupyterLab v0.34.9
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
        jupyterlab-toc v0.2.1 enabled   X

   The following extension are outdated:
        jupyterlab-toc

   Consider running "jupyter labextension update --all" to check for updates.

PS C:\WINDOWS\system32>
```
And the full error for the build:
```
PS C:\WINDOWS\system32> jupyter lab build
[LabBuildApp] JupyterLab 0.34.9
[LabBuildApp] Building in C:\ProgramData\Anaconda3\share\jupyter\lab
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-lab-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1571, in start
    super(NotebookApp, self).start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 67, in start
    command=command, logger=self.log)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 270, in build
    command=command, clean_staging=clean_staging)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 441, in build
    clean=clean_staging
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 859, in _populate_staging
    shutil.rmtree(staging)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 13 more times]
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\npm\\node_modules\\libcipm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.js'
```

**Comment by aquirdTurtle** [comment]
Okay, changing the registry allowed a build to work, and after that build it looks like the node packages have flattened themselves out, such that I can even change the registry value back. On further inspection, looks like it was an old issue with node: https://stackoverflow.com/questions/26155135/node-npm-windows-file-paths-are-too-long-to-install-packages. Not sure how my node installation got into this funny state, but seems resolved. Thanks!

**Comment by blink1073** [comment]
Reopening so we can document the issue and the workaround.  Glad you got sorted though!
