### ISSUE TITLE
Jupyterlab 0.34.12 cannot start

### ISSUE THREAD

**Issue by thongnnguyen** [jupyterlab/jupyterlab#5385]
The last time I updated Jupyterlab was around June 2018. It works perfectly fine until a few days ago, I installed pygame, which forces my conda updated. And I arrived at Jupyterlab 0.34.12

I was having a jupyterlab running when I did the update (in fact, I was using the terminal from jupyterlab), after the update, it looks nicer, but everytime I reload the browser, it doesn't show all the notebooks, files, etc. I opened before reloading the page anymore. Instead, it shows me a blank workspace.

So I decided to stop the jupyterlab I had been running, and launch it again. Now i'm stuck with this error and cannot launch jupyterlab anymore.

This is the error I get by trying to run `jupyter lab`
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.5/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/opt/anaconda3/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/opt/anaconda3/lib/python3.5/site-packages/jupyterlab/labapp.py", line 202, in init_webapp
    super().init_webapp(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/opt/anaconda3/lib/python3.5/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/anaconda3/lib/python3.5/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/opt/anaconda3/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Any suggestion where it might go wrong?

I want to downgrade my jupyterlab. I tried re-install version 0.32.1 but still got the same error. It was so stupid of me not installing that package (pygame) to a different environment. I'm so regret now. Please help.

I'm using Ubuntu 16.04, conda 4.5.11, `jupyter notebook --version` shows `5.7.0`. This is from `conda list | grep jupyter`:

```
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py35_1    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                    py35_0    conda-forge
jupyter_latex_envs        1.4.4                    py35_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py35_0    conda-forge
jupyterhub                0.9.4                    py35_0    conda-forge
jupyterlab                0.32.1                   py35_0    conda-forge
jupyterlab_launcher       0.10.5                   py35_0    conda-forge
```

**Comment by blink1073** [comment]
Hi @thongnnguyen, I've never seen that happen with traitlets before.  Can you please try `conda install traitlets` and see if that picks up a newer version and sorts out the problem?

**Comment by thongnnguyen** [comment]
@blink1073 , thanks for your reply. I tried the command, but it seems everything is up to date.

I got

```

# All requested packages already installed.

```

**Comment by blink1073** [comment]
Can you please try in a new conda enviroment, (e.g. `conda create -n test jupyterlab`)?

**Comment by thongnnguyen** [comment]
Hi, I just remembered I still keep the old conda installer, so I remove the current one, re-install the old one. Now I can launch jupyterlab (phew).

Just for the record, I just `rm` the `anaconda3` folder, then run the `.sh` file to reinstall anaconda exactly to the same place. I didn't touch everything else (such as config files, path etc.). It just works.

I'm now still having problems with opening a jupyterlab workspace on jupyterhub, but I think it's the hub problem, will open issues on their page.

Thanks much for your help.

**Comment by thongnnguyen** [comment]
Finally, it works. I don't know how and why. I just do the following:

1. `rm` the `anaconda3` directory
2. run `.sh` file to reinstall anaconda to exactly same place
3. launch jupyter lab
4. from jupyter lab terminal: `conda install jupyterhub` and `conda install sudospawner`

Then everything just works again. Now I can have the hub serve multiple users with their own jupyterlab workspace.

Thank you very much

**Comment by jasongrout** [comment]
I'm glad it's working! Thanks for following up here letting us know what you did.
