### ISSUE TITLE
JupyterLab clean fails

### ISSUE THREAD

**Issue by vilim** [jupyterlab/jupyterlab#5397]
On installing a new release of jupyter lab, the clean command fails:
```
>>> jupyter lab clean
```

<details><summary>Command Line Output</summary>
<pre>
Traceback (most recent call last):
  File "C:\Users\vilim\anaconda3\Scripts\jupyter-lab-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\vilim\anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\vilim\anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\vilim\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1605, in start
    super(NotebookApp, self).start()
  File "C:\Users\vilim\anaconda3\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\Users\vilim\anaconda3\lib\site-packages\jupyterlab\labapp.py", line 88, in start
    clean(self.app_dir)
  File "C:\Users\vilim\anaconda3\lib\site-packages\jupyterlab\commands.py", line 259, in clean
    shutil.rmtree(target)
  File "C:\Users\vilim\anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\vilim\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\vilim\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\vilim\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 5 more times]
  File "C:\Users\vilim\anaconda3\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\vilim\anaconda3\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\vilim\\anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\jupyter-matplotlib\\node_modules\\.cache\\uglifyjs-webpack-plugin\\content-v2\\sha512\\1b\\7f\\707b368483003ea3ed7d06267d3b1a046d0475617913b477c2852ba74d40e951e6eaf980d95d93160914c59bc9e3e8732d04f0339fbe7ea9348b943f2fc6'
</pre>
</details>

I am running Windows 10, and I have the newest release of JupyterLab, 0.34.12 installed.

**Comment by blink1073** [comment]
Thanks for the report, @vilim!  We'll get this fixed for the upcoming release.   Dev note: we just need to wrap `rmtree` in a try/except because it tends to throw spurious errors.
