### ISSUE TITLE
Jupyterlab front-end crash when using keras progress bar during training 

### ISSUE THREAD

**Issue by ReDeiPirati** [jupyterlab/jupyterlab#5399]
**Describe the bug**
The Jupyterlab front-end crash when using `keras` progress bar during training (which is the default behavior). This seems a [long-standing issue from Jupyter](https://github.com/jupyter/notebook/issues/1474). 

**To Reproduce**

1. Get the latest stable release of `jupyterlab`
2. Run a simple MNIST training (make sure that the training will take more than 15 minutes)

or you can reproduce the freeze with the code below (which is similar to the Keras logging utility) - thanks to @houqp.

```python
from time import sleep
while True:
    for i in range(10000):
        print(f'b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\r10624/60000 [====>.........................] - ETA: 12s - loss: 12.7657 - acc: 0.2077"', end="")
        sleep(0.001)  # you will experience the same issue with 0.01 and 0.1 as well
    print("")
```
Coult it be related to `\b` handling...?

3. After this, the Browser window will become unresponsive and the Task Manager will report a CPU utilization > 100%.

**Expected behavior**
Not freezing/crashing the front-end.

**Desktop:**

- OS: tested on Windows 10, MacOS 10.13.6
- Browser: tested on Chrome 69.0, Firefox 62.0.
- JupyterLab: tested on 0.34.2, 0.33.8, 0.31.12. 

**Additional context**

Running the same code as a script from the Workspace Terminal doesn't produce any issue.

From the Logs:

```bash
Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/Users/pirate/Developer/labs-test/lib/python3.6/site-packages/tornado/websocket.py", line 874, in wrapper
    yield fut
  File "/Users/pirate/Developer/labs-test/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pirate/Developer/labs-test/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/pirate/Developer/labs-test/lib/python3.6/site-packages/tornado/websocket.py", line 876, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/Users/pirate/Developer/labs-test/lib/python3.6/site-packages/tornado/websocket.py", line 874, in wrapper
    yield fut
  File "/Users/pirate/Developer/labs-test/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed
```

**Comment by blink1073** [comment]
Hi @ReDeiPirati, I suspect this will not be solved until we move to server-side rendering of the document, cf #5382.

**Comment by NickCastello** [comment]
Having this problem too

**Comment by MMesch** [comment]
The triaging agent has identified this issue as resolved. I just tried running the reproducer on JupyterLab 4.5.0 posted above and it seems indeed fixed—no freezing/crashing after more than 15 minutes. The agent also identified related issues that were fixed and that may be helpful to give more context here.

- #4202
- #6304
- #6496
- #6497 
- #6505
- #6513

Please reopen/comment in case you think it's still relevant.
