### ISSUE TITLE
socket.gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by bingws** [jupyterlab/jupyterlab#5410]
when I run the command "jupyter lab" or "jupyter notebook" on ubuntu16.04, it  report the following error, I can't find solutions.

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by bingws** [comment]
the error happens after I modify the jupyter_notebook_config.py , I add the following 
configuration information：
c.NotebookApp.ip='*'
c.NotebookApp.password = u'sha1:ce......'
c.NotebookApp.open_browser = False
c.NotebookApp.port =8888

**Comment by blink1073** [comment]
Hi @bingws, what is the output of `jupyter notebook --version`?

**Comment by Pazitos10** [comment]
I had a similar error message when using `jupyter-lab --ip='*' --port='8888'` to run jupyter-lab `5.7.0`: `socket.gaierror: [Errno -2] Name or service not known`. 
So I tried using `--ip='0.0.0.0'` instead of `--ip='*'` and it worked fine. I didn't have this problem when I run the same command using jupyter-lab `5.4.0`.  
I know it's not the same exact error message, but I noticed that your config file has `c.NotebookApp.ip='*'`. 
Could you try changing that to `c.NotebookApp.ip='0.0.0.0'` ?

**Comment by ivanov** [comment]
@bingws it looks like you're trying to do this in Python 2, but as of August, JupyterLab requires Python3.5  or greater (see #5111) . The README does not currently reflect that, I opened #5422 to address that.

**Comment by bingws** [comment]
I had solved the problem after I  create a new file named "jupyter_config.py", and then add the configuration information . thanks @blink1073 @ivanov @Pazitos10
