### ISSUE TITLE
Starting Kernel Error

### ISSUE THREAD

**Issue by gboeing** [jupyterlab/jupyterlab#5424]
I just did a fresh miniconda install with py3.7 on win64, then created a virtual env with conda, then installed jupyter lab. Upon launching jupyter lab, I try to open a new notebook and get the following "Starting Kernel Error" window with message text:

```
Traceback (most recent call last):
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda\envs\ppua7237\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda\envs\ppua7237\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

If I run `jupyter notebook` instead and launch a notebook file, I see the same thing... the error window says "failed to start kernel" with message:

```
Traceback (most recent call last):
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda\envs\ppua7237\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda\envs\ppua7237\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda\envs\ppua7237\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

The same behavior happens with opening new notebooks or old existing ones. I have tried uninstalling miniconda and reinstalling, but the same behavior repeats.

Here's my conda info:

```
     active environment : ppua7237
    active env location : C:\Anaconda\envs\ppua7237
            shell level : 1
       user config file : C:\Users\Geoff\.condarc
 populated config files : C:\Users\Geoff\.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\Anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda\pkgs
                          C:\Users\Geoff\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda\envs
                          C:\Users\Geoff\AppData\Local\conda\conda\envs
                          C:\Users\Geoff\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

And conda list:

```
# packages in environment at C:\Anaconda\envs\ppua7237:
#
# Name                    Version                   Build  Channel
altair                    2.2.2                    py36_1    conda-forge
asn1crypto                0.24.0                   py36_3    conda-forge
backcall                  0.1.0                      py_0    conda-forge
basemap                   1.1.0            py36h5987640_7    conda-forge
blas                      1.0                         mkl  
bleach                    2.1.4                      py_1    conda-forge
boost                     1.66.0              py36_vc14_1  [vc14]  conda-forge
boost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge
branca                    0.3.0                      py_0    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24             py36_1001    conda-forge
cffi                      1.11.5           py36hfa6e2cd_1    conda-forge
chardet                   3.0.4                    py36_3    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
colorama                  0.3.9                      py_1    conda-forge
cryptography              2.3.1            py36h74b6da3_0    conda-forge
cryptography-vectors      2.3.1                    py36_0    conda-forge
curl                      7.60.0                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
entrypoints               0.2.3                    py36_2    conda-forge
expat                     2.2.5                    vc14_0  [vc14]  conda-forge
fiona                     1.7.13           py36h01e27f7_3    conda-forge
folium                    0.6.0                      py_0    conda-forge
freetype                  2.9.1             he8b6a0d_1004    conda-forge
freexl                    1.0.2                    vc14_2  [vc14]  conda-forge
gdal                      2.2.4            py36h2fc6367_1    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geopy                     1.17.0                     py_0    conda-forge
geos                      3.6.2                he025d50_3    conda-forge
geotiff                   1.4.2                    vc14_1  [vc14]  conda-forge
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icc_rt                    2017.0.4             h97af966_0  
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.7                      py36_2    conda-forge
intel-openmp              2019.0                      118  
ipykernel                 5.0.0              pyh24bf2e0_1    conda-forge
ipython                   7.0.1            py36h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                2.6.0                    py36_2    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.34.12                  py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
kealib                    1.4.7                    vc14_4  [vc14]  conda-forge
kiwisolver                1.0.1            py36he980bc4_2    conda-forge
krb5                      1.14.6                   vc14_0  [vc14]  conda-forge
libgdal                   2.2.4                    vc14_5  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libnetcdf                 4.6.1                    vc14_2  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libpq                     9.6.3                    vc14_0  [vc14]  conda-forge
libsodium                 1.0.16                   vc14_0  [vc14]  conda-forge
libspatialindex           1.8.5                    vc14_1  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_19  [vc14]  conda-forge
libssh2                   1.8.0                hc4dcbb0_2    conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markupsafe                1.0              py36hfa6e2cd_1    conda-forge
matplotlib                3.0.0            py36h7b168c4_1    conda-forge
mistune                   0.8.3            py36hfa6e2cd_2    conda-forge
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
msys2-conda-epoch         20160418                      1  
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.2                        py_1    conda-forge
notebook                  5.7.0                    py36_0    conda-forge
numpy                     1.15.2           py36ha559c80_0  
numpy-base                1.15.2           py36h8128ebf_0  
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0                    vc14_2  [vc14]  conda-forge
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
osmnx                     0.8.2                      py_0    conda-forge
pandas                    0.23.4           py36h830ac7b_0    conda-forge
pandoc                    2.3.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pickleshare               0.7.5                    py36_0    conda-forge
pillow                    5.3.0            py36h9a613e6_0    conda-forge
pip                       18.0                     py36_1    conda-forge
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
prometheus_client         0.3.1                      py_1    conda-forge
prompt_toolkit            2.0.5                      py_0    conda-forge
psycopg2                  2.7.5            py36h74b6da3_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.2                      py_0    conda-forge
pyproj                    1.9.5.1          py36haf3c679_5    conda-forge
pyqt                      5.6.0            py36h764d66f_7    conda-forge
pysal                     1.14.4.post2             py36_0    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                    py36_2    conda-forge
python                    3.6.6                he025d50_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywinpty                  0.5.4                    py36_2    conda-forge
pyzmq                     17.1.2           py36hf576995_0    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
requests                  2.19.1                   py36_1    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
scikit-learn              0.20.0           py36heebcf9a_1  
scipy                     1.1.0            py36h4f6bf74_1  
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.4.0                py36_1000    conda-forge
shapely                   1.6.4            py36hc90234e_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1           py36h6538335_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlalchemy                1.2.12           py36hfa6e2cd_0    conda-forge
sqlite                    3.20.1                   vc14_2  [vc14]  conda-forge
terminado                 0.8.1                    py36_1    conda-forge
testpath                  0.3.1                    py36_1    conda-forge
tk                        8.6.8                    vc14_0  [vc14]  conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py36hfa6e2cd_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.23                     py36_1    conda-forge
vc                        14                            0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.32.0                py36_1000    conda-forge
win_inet_pton             1.0.1                    py36_2    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zeromq                    4.2.5                    vc14_2  [vc14]  conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
```

**Comment by blink1073** [comment]
Hi @gboeing, does it work if you use a dash instead of a space (e.g. `jupyter-lab` or `jupyter-notebook`)?

**Comment by gboeing** [comment]
@blink1073 no, same error occurs.

**Comment by guillaumedavidphd** [comment]
I'm also affected by this bug on the same platform with a fresh anaconda install.

**Comment by blink1073** [comment]
Ah, looking closer it can't find the executable called out by the kernel spec.  

Can you please post the contents for the `kernel.json` file found in the folder(s) given by `jupyter kernelspec list`?

**Comment by guillaumedavidphd** [comment]
I get:
`Available kernels:
  python3    <user_folder>\AppData\Local\Continuum\anaconda3\envs\<env_name>\share\jupyter\kernels\python3`

**Comment by gboeing** [comment]
@blink1073 it returns one folder. Here's the contents of its kernel.json:

```
{
 "argv": [
  "C:/Anaconda/envs/ppua7237/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

**Comment by gboeing** [comment]
False alarm. That did not fix it.

**Comment by blink1073** [comment]
@gboeing, are you able to directly run `C:/Anaconda/envs/ppua7237/bin/python -m ipykernel_launcher -h`?

**Comment by blink1073** [comment]
If you remove that folder and run `python -m ipykernel install --user`, does it pick up the right path?

**Comment by gboeing** [comment]
Yes this resolves it.

**Comment by gboeing** [comment]
Any idea why I have to go through this hacky workflow to get it functioning after a clean install (this has never been an issue before, or on my other computer)?

**Comment by jasongrout** [comment]
Possibly Anaconda or your environment was storing (stale) information about what kernels were where, and that was stored outside of the actual installation, so even after a fresh install, that information was available and used by the new installation.

**Comment by jasongrout** [comment]
Closed as resolved. I'm glad it's working for you now!

**Comment by gboeing** [comment]
@jasongrout @blink1073 this issue has been recurring on every one of my windows machines over the past couple of weeks, including a brand-new windows machine when I installed anaconda + jupyter for the first time. Every time I have to resolve it manually per the steps detailed above. This issue has not shown up on my linux machines.

**Comment by gboeing** [comment]
Specifically, the fix is that I have to run `python -m ipykernel install --user` manually after every package update or fresh anaconda installation (even on a brand new computer).

**Comment by djproc** [comment]
I would like to report that i had the exact same issue and this also fixed it. This occurred when I created a new environment to install tensorflow. This only happened on one of my PCs though.

**Comment by mahercapo123** [comment]
python -m ipykernel install --user this is  the fix of that error
