### ISSUE TITLE
Installing JupyterLab via conda prohibits use of base conda environment

### ISSUE THREAD

**Issue by karosc** [jupyterlab/jupyterlab#5471]
I recently tried to upgrade JupyterLab to v0.35 and experienced an issue. When I try to use my base conda env to open a notebook, I get an "Error Starting Kernel" message and the traceback below. I thought the error might be something wrong with my existing base env, so a created an empty conda env, installed only jupyterlab via ```conda install jupyterlab```, but still get the same traceback. It should be noted that I do not get any error when using one of my other conda envs....this only happens when using the base env. I suspect this is a dependency issue?

```
Traceback (most recent call last):
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by jasongrout** [comment]
Looks to me like the kernel spec is maybe corrupted? Perhaps if you do `jupyter kernelspec list` in that base environment, then check those kernel files?

Does the classic notebook work too? My guess is that it has the same error?

**Comment by karosc** [comment]
you are correct!  ```jupyter kernelspec list``` listed all my conda envs and at the bottom was python3

```python3     C:\CKAROS_PROJECTS\Utils\miniconda3\envs\python37\share\jupyter\kernels\python3```

I opened up the python3 kernel spec to find this path:
"C:/CKAROS_PROJECTS/Utils/miniconda3/envs/python37/bin/python"

There is no python executable in python37/bin because python37/bin does not exist!.....so this might be a conda issue? I wonder why the error occurred when installing in the base env. This will take some more investigation after backing up again. 

Does jupyter edit the kernel spec in "miniconda3/share/jupyter/kernels" upon install?

**Comment by jasongrout** [comment]
I don't know who modified that kernel spec. Certainly not JupyterLab, though.

**Comment by karosc** [comment]
resolved
