### ISSUE TITLE
Node error while installing any extension although node is present

### ISSUE THREAD

**Issue by byouness** [jupyterlab/jupyterlab#5663]
I cannot install any jupyterlab extensions, for example when I try:
```
>jupyter-labextension install @jupyter-widgets/jupyterlab-manager --debug
```
I get the following :
```
Searching ['C:\\Windows\\system32', 'C:\\Users\\ybouisouden\\.jupyter', 'd:\\anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
Looking for jupyter_config in C:\ProgramData\jupyter
Looking for jupyter_config in d:\anaconda3\etc\jupyter
Looking for jupyter_config in C:\Users\ybouisouden\.jupyter
Looking for jupyter_config in C:\Windows\system32
Traceback (most recent call last):

  File "d:\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 77, in start
    ans = self.run_task()

  File "d:\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 106, in run_task
    for arg in self.extra_args

  File "d:\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 106, in <listcomp>
    for arg in self.extra_args

  File "d:\anaconda3\lib\site-packages\jupyterlab\commands.py", line 217, in install_extension
    _node_check(logger)

  File "d:\anaconda3\lib\site-packages\jupyterlab\commands.py", line 1481, in _node_check
    node = which('node')

  File "d:\anaconda3\lib\site-packages\jupyterlab_server\process.py", line 59, in which
    raise ValueError(msg)

ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```
I am using windows 10 version 1709 (OS build 16299.726)
Jupyterlab is working fine (but widgets are not displaying, hence the need for extension installation).
```
>jupyter-labextension list
JupyterLab v0.35.4
No installed extensions
>node --version
v8.9.3
>npm --version
6.4.1
```
Could you help with this?

**Comment by byouness** [comment]
Reinstalling nodejs via conda somehow fixed it for me.
