### ISSUE TITLE
Launcher crashes when kernel is removed

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#5676]
**Describe the bug**

When using `nb_conda_kernels`, removing an existing environment and opening the launcher results in an empty blank launcher.

**To Reproduce**

1. Install `nb_conda_kernels` (available on conda-forge)
2. Be sure to have multiple conda environment  
   Dummy environment can be created through `conda create -n dummy ipykernel`
3. Launch JupyterLab
4. Open a notebook
5. Remove one of the conda environment (`conda env remove -n dummy`)
6. Open the launcher

**Expected behavior**
The launcher should appears with all environments minus the deleted one.

**Desktop:**

- OS: Windows 7 64bits
- Browser chrome 61.0
- JupyterLab 0.35.3

**Additional context**

<details><summary>Browser Output</summary>
<pre>
index.js:380 TypeError: Cannot read property 'display_name' of undefined
    at label (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:285100:73)
    at CommandRegistry.push.5TpB.CommandRegistry.label (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:29210:32)
    at Object.sortCmp (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:33054:33)
    at categories.(anonymous function).categories.(anonymous function).sort (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:32926:32)
    at Array.sort (native)
    at Launcher.render (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:32925:47)
    at Launcher.onUpdateRequest (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:295544:26)
    at Launcher.push.FmDU.Widget.processMessage (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:248745:22)
    at invokeHandler (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:393572:21)
    at sendMessage (http://localhost:8888/lab/static/vendors~main.9eb87bab456c37d46462.js:393308:13)
</pre>
</details>

**Associated bug**
Creating new environments does not lead in additional cards in the launcher.

**Possible fix**
`Session.specsChanged` signal could use to listen for kernel changes.

**Comment by jasongrout** [comment]
Next step is to determine if this is nb_conda_kernel's fault, or JLab's fault.
