### ISSUE TITLE
Jest tests failing when importing ES modules

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#5751]
It looks like our current jest config doesn't support ES modules (because it's running in a node.js environment). The blueprint packages provide ES modules by default. We can import the commonjs modules if need be (e.g. `import { Button } from '@blueprintjs/core/lib/cjs/components/button/buttons'`) but it seems like we will run into this issue more as ES modules becomes the standard module type.

Output from [Travis build](https://travis-ci.org/jupyterlab/jupyterlab/jobs/466235657):

```
@jupyterlab/test-application: $ python run.py --coverage
@jupyterlab/test-application: [I 22:32:48.911 JestApp] Writing notebook server cookie secret to /tmp/tmpeywu3yvy/jupyter_runtime/notebook_cookie_secret
@jupyterlab/test-application: [I 22:32:48.938 JestApp] Serving notebooks from local directory: /tmp/mock_contentsp7r4iwwc
@jupyterlab/test-application: [I 22:32:48.938 JestApp] The Jupyter Notebook is running at:
@jupyterlab/test-application: [I 22:32:48.938 JestApp] http://localhost:8888/?token=d05099444bb13d70c8fce4c8c799ca90d83774cba2ffc0d8
@jupyterlab/test-application: [I 22:32:48.938 JestApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
@jupyterlab/test-application: [C 22:32:48.938 JestApp] 
@jupyterlab/test-application:     
@jupyterlab/test-application:     Copy/paste this URL into your browser when you connect for the first time,
@jupyterlab/test-application:     to login with a token:
@jupyterlab/test-application:         http://localhost:8888/?token=d05099444bb13d70c8fce4c8c799ca90d83774cba2ffc0d8
@jupyterlab/test-application: [I 22:32:48.941 JestApp] > node /home/travis/build/jupyterlab/jupyterlab/node_modules/jest/bin/jest.js --coverage --runInBand
@jupyterlab/test-application: jest-haste-map: @providesModule naming collision:
@jupyterlab/test-application:   Duplicate module name: @jupyterlab/application-top
@jupyterlab/test-application:   Paths: /home/travis/build/jupyterlab/jupyterlab/dev_mode/package.json collides with /home/travis/build/jupyterlab/jupyterlab/jupyterlab/staging/package.json
@jupyterlab/test-application: This warning is caused by a @providesModule declaration with the same name across two different files.
@jupyterlab/test-application:  FAIL  src/shell.spec.ts
@jupyterlab/test-application:   ● Test suite failed to run
@jupyterlab/test-application:     Jest encountered an unexpected token
@jupyterlab/test-application:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-application:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-application:     Here's what you can do:
@jupyterlab/test-application:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-application:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-application:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-application:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-application:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-application:     Details:
@jupyterlab/test-application:     /home/travis/build/jupyterlab/jupyterlab/node_modules/@blueprintjs/core/lib/esm/components/button/buttons.js:6
@jupyterlab/test-application:     import * as tslib_1 from "tslib";
@jupyterlab/test-application:     ^^^^^^
@jupyterlab/test-application:     SyntaxError: Unexpected token import
@jupyterlab/test-application:       11 | Object.defineProperty(exports, "__esModule", { value: true });
@jupyterlab/test-application:       12 | const React = __importStar(require("react"));
@jupyterlab/test-application:     > 13 | const buttons_1 = require("@blueprintjs/core/lib/esm/components/button/buttons");
@jupyterlab/test-application:          |                   ^
@jupyterlab/test-application:       14 | const icon_1 = require("@blueprintjs/core/lib/esm/components/icon/icon");
@jupyterlab/test-application:       15 | const collapse_1 = require("@blueprintjs/core/lib/esm/components/collapse/collapse");
@jupyterlab/test-application:       16 | const inputGroup_1 = require("@blueprintjs/core/lib/esm/components/forms/inputGroup");
@jupyterlab/test-application:       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
@jupyterlab/test-application:       at Object.<anonymous> (packages/ui-components/lib/index.js:13:19)
@jupyterlab/test-application:       at Object.<anonymous> (packages/apputils/lib/toolbar.js:13:25)
```

**Comment by bollwyvl** [comment]
Found this earlier when trying to get `async import` working:
https://github.com/jupyterlab/jupyterlab/issues/5500#issuecomment-432909712

There was this fix, but I haven't had the fortitude to investigate further:
kulshekhar/ts-jest#258

**Comment by gnestor** [comment]
Related: https://github.com/facebook/jest/issues/2081
