### ISSUE TITLE
How to edit webpack configuration used for `jupyter lab --watch`

### ISSUE THREAD

**Issue by reem** [jupyterlab/jupyterlab#5815]
I would like to edit the webpack configuration used for `jupyter lab --watch`, in this case to change the polling options for `--watch` in order to be able to run the build in a docker container with the source files mounted in. Can't seem to find where I can do this or if it is even possible.

Asked on gitter, was told to tag @saulshanabrook and @afshin

**Comment by reem** [comment]
Anyone know of a workaround here? This is making the development process when using docker rather unfortunate.

**Comment by jasongrout** [comment]
Are you running from the git repo, or an installed jlab?

**Comment by saulshanabrook** [comment]
If you look in the `staging` directory of the `jupyterlab` python package you should see some webpack files. I believe you can edit those and re-run `jupyter lab build` to copy those files over.

To find the JupyterLab python directory run `python -c 'import os; import jupyterlab; print(os.path.dirname(jupyterlab.__file__))'`

If you run `jupyter lab path` you will see the app directory. This also contains a `staging` directory you can edit files in. Whenever you run `jupyter lab build` this directory is replaced by the one in the Python package.

Does that give you enough to edit this manually?

**Comment by nanchenchen** [comment]
Thank you again for the reply!

I have seen @scriptedforms' example but he said that the example is no
longer working. I can't find any other resources so I am trying to figure
it out...

And thank you for the explanations! Could you please point me to the files
that contain these steps (i.e., where to look for `jupyter labextension
install`)? I was looking for them but did not succeed.

Thank you so much again! Really appreciate your help on answering my
questions. :)

Nan-Chen

---

**Comment by saulshanabrook** [comment]
@nanchenchen Sorry for the late notice, but we are actually having a little meeting in a couple minutes about making the builds run faster in JupyterLab by  prebuilding.  Feel free to join, if you are free! https://hackmd.io/@_4xc7QhhSHKODRQn1uiulw/BkRmApfHS/edit

**Comment by nanchenchen** [comment]
Oh wow! Sorry I totally missed that. Would love to be part of this. Will
take a look at the notes and send out comments if I have any! :)


---

**Comment by ParseDark** [comment]
I have some problems. I want to run a react widget on jupyter lab. But I have a question for the build system. Why they need to run two times ```webpack```  I don't know why need to run a webpack on ```/usr/local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js```  the auto-generated didn't container our babel transform. so when i run ```jupyter labextension install ./js```  

In my extension on js dir. I have own webpack.config.js. And i can run webpack build no error. But when i run ```jupyter labextension install ./js``` i will get the error. 


this is the error log.

```
Node v10.16.3

Yarn configuration loaded.
> /usr/local/bin/npm pack /Users/xxxxxxxxxxx/Project/zzzz/js

> qgrid2@1.1.3 prepare /Users/xxxxxxxxxxx/Project/zzzz/js
> webpack

Hash: add25e765eb91dba92f476fa61242f49a1888d3f508aab8d903c05d34467
Version: webpack 4.44.1
Child
    Hash: add25e765eb91dba92f4
    Time: 486ms
    Built at: 09/12/2020 6:18:28 PM
           Asset      Size  Chunks             Chunk Names
    extension.js  1.07 KiB       0  [emitted]  main
    Entrypoint main = extension.js
    [0] ./src/extension.js 510 bytes {0} [built]
Child
    Hash: 76fa61242f49a1888d3f
    Time: 1391ms
    Built at: 09/12/2020 6:18:29 PM
           Asset     Size  Chunks                   Chunk Names
        index.js  128 KiB       0  [emitted]        main
    index.js.map  305 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
     [3] ./src/index.js 254 bytes {0} [built]
     [4] ./src/otherGrid/index.js 4.64 KiB {0} [built]
     [5] external "@jupyter-widgets/base" 42 bytes {0} [built]
    [10] ./package.json 1.46 KiB {0} [built]
    [11] ./src/otherGrid/frontend/index.js + 1 modules 543 bytes {0} [built]
         | ./src/otherGrid/frontend/index.js 239 bytes [built]
         | ./src/otherGrid/frontend/component/index.js 294 bytes [built]
        + 7 hidden modules
Child
    Hash: 508aab8d903c05d34467
    Time: 1387ms
    Built at: 09/12/2020 6:18:29 PM
           Asset     Size  Chunks                   Chunk Names
        index.js  128 KiB       0  [emitted]        main
    index.js.map  305 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
     [3] ./src/embed.js 452 bytes {0} [built]
     [4] ./src/otherGrid/index.js 4.64 KiB {0} [built]
     [5] external "@jupyter-widgets/base" 42 bytes {0} [built]
    [10] ./package.json 1.46 KiB {0} [built]
    [11] ./src/otherGrid/frontend/index.js + 1 modules 543 bytes {0} [built]
         | ./src/otherGrid/frontend/index.js 239 bytes [built]
         | ./src/otherGrid/frontend/component/index.js 294 bytes [built]
        + 7 hidden modules
npm notice 
npm notice 📦  qgrid2@1.1.3
npm notice === Tarball Contents === 
npm notice 14.5kB  src/qgrid.css                            
npm notice 454B    src/embed.js                             
npm notice 510B    src/extension.js                         
npm notice 130.6kB dist/index.js                            
npm notice 255B    src/index.js                             
npm notice 203B    src/otherGrid/frontend/component/index.js
npm notice 188B    src/otherGrid/frontend/index.js          
npm notice 1.0kB   src/otherGrid/index.js                   
npm notice 386B    src/jupyterlab-plugin.js                 
npm notice 2.8kB   src/qgrid.booleanfilter.js               
npm notice 4.9kB   src/qgrid.datefilter.js                  
npm notice 2.7kB   src/qgrid.editors.js                     
npm notice 5.8kB   src/qgrid.filterbase.js                  
npm notice 4.0kB   src/qgrid.sliderfilter.js                
npm notice 11.2kB  src/qgrid.textfilter.js                  
npm notice 25.3kB  src/qgrid.widget.js                      
npm notice 1.5kB   package.json                             
npm notice 312.5kB dist/index.js.map                        
npm notice === Tarball Details === 
npm notice name:          qgrid2                                  
npm notice version:       1.1.3                                   
npm notice filename:      qgrid2-1.1.3.tgz                        
npm notice package size:  155.5 kB                                
npm notice unpacked size: 518.9 kB                                
npm notice shasum:        9b6e9c4787cc3381ccbe16b3186040e06146a5ae
npm notice integrity:     sha512-Mz7L1zHbYyGIo[...]6W3KN7sbDuwSA==
npm notice total files:   18                                      
npm notice 
qgrid2-1.1.3.tgz

Node v10.16.3

Yarn configuration loaded.
Building jupyterlab assets (build:dev:minimize)
> /usr/local/bin/npm pack /Users/xxxxxxxxxxx/Project/zzzz/js

> qgrid2@1.1.3 prepare /Users/xxxxxxxxxxx/Project/zzzz/js
> webpack

Hash: add25e765eb91dba92f476fa61242f49a1888d3f508aab8d903c05d34467
Version: webpack 4.44.1
Child
    Hash: add25e765eb91dba92f4
    Time: 414ms
    Built at: 09/12/2020 6:18:31 PM
           Asset      Size  Chunks             Chunk Names
    extension.js  1.07 KiB       0  [emitted]  main
    Entrypoint main = extension.js
    [0] ./src/extension.js 510 bytes {0} [built]
Child
    Hash: 76fa61242f49a1888d3f
    Time: 1456ms
    Built at: 09/12/2020 6:18:32 PM
           Asset     Size  Chunks                   Chunk Names
        index.js  128 KiB       0  [emitted]        main
    index.js.map  305 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
     [3] ./src/index.js 254 bytes {0} [built]
     [4] ./src/otherGrid/index.js 4.64 KiB {0} [built]
     [5] external "@jupyter-widgets/base" 42 bytes {0} [built]
    [10] ./package.json 1.46 KiB {0} [built]
    [11] ./src/otherGrid/frontend/index.js + 1 modules 543 bytes {0} [built]
         | ./src/otherGrid/frontend/index.js 239 bytes [built]
         | ./src/otherGrid/frontend/component/index.js 294 bytes [built]
        + 7 hidden modules
Child
    Hash: 508aab8d903c05d34467
    Time: 1449ms
    Built at: 09/12/2020 6:18:32 PM
           Asset     Size  Chunks                   Chunk Names
        index.js  128 KiB       0  [emitted]        main
    index.js.map  305 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
     [3] ./src/embed.js 452 bytes {0} [built]
     [4] ./src/otherGrid/index.js 4.64 KiB {0} [built]
     [5] external "@jupyter-widgets/base" 42 bytes {0} [built]
    [10] ./package.json 1.46 KiB {0} [built]
    [11] ./src/otherGrid/frontend/index.js + 1 modules 543 bytes {0} [built]
         | ./src/otherGrid/frontend/index.js 239 bytes [built]
         | ./src/otherGrid/frontend/component/index.js 294 bytes [built]
        + 7 hidden modules
npm notice 
npm notice 📦  qgrid2@1.1.3
npm notice === Tarball Contents === 
npm notice 14.5kB  src/qgrid.css                            
npm notice 454B    src/embed.js                             
npm notice 510B    src/extension.js                         
npm notice 130.6kB dist/index.js                            
npm notice 255B    src/index.js                             
npm notice 203B    src/otherGrid/frontend/component/index.js
npm notice 188B    src/otherGrid/frontend/index.js          
npm notice 1.0kB   src/otherGrid/index.js                   
npm notice 386B    src/jupyterlab-plugin.js                 
npm notice 2.8kB   src/qgrid.booleanfilter.js               
npm notice 4.9kB   src/qgrid.datefilter.js                  
npm notice 2.7kB   src/qgrid.editors.js                     
npm notice 5.8kB   src/qgrid.filterbase.js                  
npm notice 4.0kB   src/qgrid.sliderfilter.js                
npm notice 11.2kB  src/qgrid.textfilter.js                  
npm notice 25.3kB  src/qgrid.widget.js                      
npm notice 1.5kB   package.json                             
npm notice 312.5kB dist/index.js.map                        
npm notice === Tarball Details === 
npm notice name:          qgrid2                                  
npm notice version:       1.1.3                                   
npm notice filename:      qgrid2-1.1.3.tgz                        
npm notice package size:  155.5 kB                                
npm notice unpacked size: 518.9 kB                                
npm notice shasum:        9b6e9c4787cc3381ccbe16b3186040e06146a5ae
npm notice integrity:     sha512-Mz7L1zHbYyGIo[...]6W3KN7sbDuwSA==
npm notice total files:   18                                      
npm notice 
qgrid2-1.1.3.tgz

> node /usr/local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning qgrid2 > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 19.87s.

> node /usr/local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /usr/local/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.42s.

> node /usr/local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:dev:minimize
yarn run v1.21.1
$ jlpm run build:dev
$ jlpm run build
$ webpack
Hash: 7df08b64894a25517c931fd5f40b84accc53cea9641cd761e568b9b8c866
Version: webpack 4.44.1
Child
    Hash: 7df08b64894a25517c93
    Time: 9302ms
    Built at: 09/12/2020 6:19:07 PM
                                     Asset      Size        Chunks                         Chunk Names
                 0.75388be739456275d51d.js  8.01 MiB             0  [emitted] [immutable]  
      03ba7cb710104df27f1c9c46d64bee4e.svg   893 KiB                [emitted]              
     05b53beb21e3ef13d28244545977152d.woff  16.4 KiB                [emitted]              
      085b1dd8427dbeff10bd55410915a3f6.ttf   131 KiB                [emitted]              
      0fabb6606be4c45acfeedd115d0caca4.eot   131 KiB                [emitted]              
                 1.1c5e8434152a43d1e5d5.js   2.3 MiB             1  [emitted] [immutable]  
                10.45b5e5fbf7ad122e19e4.js  8.44 KiB            10  [emitted] [immutable]  
                11.0d55b6626845f3ae5de1.js  6.52 KiB            11  [emitted] [immutable]  
                12.29b5a95defbb65147965.js  8.06 KiB            12  [emitted] [immutable]  
                13.c078f9e31546cbdfbb19.js  7.39 KiB            13  [emitted] [immutable]  
                14.57806be29d44aa40dabe.js  7.41 KiB            14  [emitted] [immutable]  
                15.a76f900d40c2205b873a.js  10.1 KiB            15  [emitted] [immutable]  
                16.44c9b48e4f77943f87fa.js  8.23 KiB            16  [emitted] [immutable]  
                17.baac762d9d49122b694f.js  9.48 KiB            17  [emitted] [immutable]  
                18.5aa5d54847234c8f76d7.js  9.75 KiB            18  [emitted] [immutable]  
                19.95166eb4f63b1c0aae81.js  6.11 KiB            19  [emitted] [immutable]  
      1a78af4105d4d56e6c34f76dc70bf1bc.ttf  33.3 KiB                [emitted]              
                 2.cb70b3d50f12f8b5691a.js   8.1 KiB             2  [emitted] [immutable]  
                20.f0ed85aac2bc741c24cb.js  4.93 KiB            20  [emitted] [immutable]  
                21.7bb66e701c6b0410d69a.js  8.95 KiB            21  [emitted] [immutable]  
                22.8419c8f2b15882e09425.js  7.54 KiB            22  [emitted] [immutable]  
                23.f40b9c4ca7c6fe7f3fad.js  6.69 KiB            23  [emitted] [immutable]  
                24.5978864f911ba07cd78a.js  9.46 KiB            24  [emitted] [immutable]  
                25.2b60a3b3e260a6a3693b.js  7.36 KiB            25  [emitted] [immutable]  
                26.1a053a1e905fa0fe3e50.js   6.6 KiB            26  [emitted] [immutable]  
                27.b03c5472f00beeae8392.js  9.93 KiB            27  [emitted] [immutable]  
                28.8ed76c9f9dcc12e904ec.js  13.7 KiB            28  [emitted] [immutable]  
                29.0a9ea77a2bb19faa2371.js  7.93 KiB            29  [emitted] [immutable]  
                 3.0ed0fe389dd246b98445.js  8.32 KiB             3  [emitted] [immutable]  
                30.a73bb3fbdbfdb9214164.js  10.1 KiB            30  [emitted] [immutable]  
                31.f8357644d8d8f1de6b87.js  9.98 KiB            31  [emitted] [immutable]  
                32.00ea4836f4b4587128cc.js  10.4 KiB            32  [emitted] [immutable]  
                33.df0c9041483176bd1bcb.js  9.41 KiB            33  [emitted] [immutable]  
                34.07080700df38814e06ea.js  8.39 KiB            34  [emitted] [immutable]  
                35.78a0275be671bfb3d596.js  15.6 KiB            35  [emitted] [immutable]  
                36.2a6124190d58ac28205a.js  7.79 KiB            36  [emitted] [immutable]  
                37.5928cceddb4c693c83e7.js   8.7 KiB            37  [emitted] [immutable]  
                38.c002cfe5edd0667eecaf.js  9.47 KiB            38  [emitted] [immutable]  
                39.a6827c69506f9963d692.js  4.68 KiB            39  [emitted] [immutable]  
    3a3398a6ef60fc64eacf45665958342e.woff2  13.3 KiB                [emitted]              
                 4.6ce30bcf6e192f550650.js  8.13 KiB             4  [emitted] [immutable]  
                40.d5514df1316eb0fa9099.js  5.42 KiB            40  [emitted] [immutable]  
                41.fc95255a5278ff66883f.js  7.43 KiB            41  [emitted] [immutable]  
                42.153846a5ea7a9e1ea6f8.js  8.47 KiB            42  [emitted] [immutable]  
                43.8d6d2833519c9d912d55.js   8.8 KiB            43  [emitted] [immutable]  
                44.b0237c9dc4db52fc16c1.js  7.98 KiB            44  [emitted] [immutable]  
                45.129ce170116f110da0d3.js  8.34 KiB            45  [emitted] [immutable]  
                46.4f9a6140425b11d83699.js  8.35 KiB            46  [emitted] [immutable]  
                47.aa79d35d04ea0c0ada48.js  9.48 KiB            47  [emitted] [immutable]  
                48.a16dc31de59a5e4e77d1.js   6.8 KiB            48  [emitted] [immutable]  
                49.84f13d1a63c8720489cf.js  7.58 KiB            49  [emitted] [immutable]  
                 5.aca068feccd4dd729d74.js  3.17 KiB             5  [emitted] [immutable]  
                50.ab5747bfa2f04f52b7d2.js  8.18 KiB            50  [emitted] [immutable]  
                51.8c97cf941c626a89a523.js  9.44 KiB            51  [emitted] [immutable]  
                52.e17292f883542f8f0e4f.js  17.7 KiB            52  [emitted] [immutable]  
                53.a9bdfadfdaa8a3ce92b6.js  4.84 KiB            53  [emitted] [immutable]  
                54.5665a93fa7ffc9df99de.js  8.04 KiB            54  [emitted] [immutable]  
                55.07c0452d9ec42be85b6a.js  7.67 KiB            55  [emitted] [immutable]  
                56.9f76cbb0c4d74427d477.js  9.28 KiB            56  [emitted] [immutable]  
                57.e5baa4ec36f7b226a1f1.js  9.64 KiB            57  [emitted] [immutable]  
                58.2ca624e56e84d570844d.js  8.62 KiB            58  [emitted] [immutable]  
                59.bd83de7fc9e21275033e.js  8.57 KiB            59  [emitted] [immutable]  
                 6.8460bd0ff4b22e0d11ed.js  64.5 KiB             6  [emitted] [immutable]  
                60.6bd84cbbdf482c8a8bc2.js  10.6 KiB            60  [emitted] [immutable]  
                61.2afff57ed3525f28f4b4.js   8.6 KiB            61  [emitted] [immutable]  
                62.90a3f02619b8d746dec5.js  7.86 KiB            62  [emitted] [immutable]  
                63.2c2710f529e3dcb160d6.js  11.1 KiB            63  [emitted] [immutable]  
                64.618f94d0569d4fa38dea.js  8.21 KiB            64  [emitted] [immutable]  
                65.b77358e806ab3a5b68b7.js   548 KiB            65  [emitted] [immutable]  
                66.18c85d62c70ea590e398.js  12.1 KiB            66  [emitted] [immutable]  
                 7.2d3b4a9b610455dd7252.js  8.88 KiB             7  [emitted] [immutable]  
      781e85bb50c8e8301c30de56b31b1f04.ttf   199 KiB                [emitted]              
                 8.e0b60fbb88502f3872d8.js   9.2 KiB             8  [emitted] [immutable]  
      89bd2e38475e441a5cd70f663f921d61.eot   199 KiB                [emitted]              
                 9.948501da6b30e81c458d.js  8.41 KiB             9  [emitted] [immutable]  
      ad3a7c0d77e09602f4ab73db3660ffd8.eot  33.5 KiB                [emitted]              
    c500da19d776384ba69573ae6fe274e7.woff2  78.3 KiB                [emitted]              
    cac68c831145804808381a7032fdc7c2.woff2  75.6 KiB                [emitted]              
      ccfdb9dc442be0c629d331e94497428b.svg   713 KiB                [emitted]              
     dc0bd022735ed218df547742a1b2f172.woff  88.5 KiB                [emitted]              
      e75dfd904d366a2560c63c23cfc98ef8.svg   141 KiB                [emitted]              
     ee09ad7553b8ad3d81150d609d5341a0.woff   102 KiB                [emitted]              
                                index.html  1.74 KiB                [emitted]              
              main.925c2f155d12019ae8e5.js   155 KiB          main  [emitted] [immutable]  main
      vendors~main.cf043eebbe9eb08f3e11.js    29 MiB  vendors~main  [emitted] [immutable]  vendors~main
    Entrypoint main = vendors~main.cf043eebbe9eb08f3e11.js main.925c2f155d12019ae8e5.js
    [0] multi whatwg-fetch ./build/index.out.js 40 bytes {main} [built]
    [1] crypto (ignored) 15 bytes {main} [built]
    [2] readable-stream (ignored) 15 bytes {main} [built]
    [3] supports-color (ignored) 15 bytes {main} [built]
    [4] chalk (ignored) 15 bytes {main} [built]
    [4vsW] external "node-fetch" 42 bytes {main} [built]
    [9fgM] ./build/imports.css 463 bytes {main} [built]
    [ANye] ./build/index.out.js 28.2 KiB {main} [built]
    [AvjM] ./node_modules/codemirror/mode sync ^\.\/.*\/.*\.js$ 2.78 KiB {66} [built]
    [RnhZ] ./node_modules/moment/locale sync ^\.\/.*$ 3.16 KiB {main} [optional] [built]
    [SDqH] ./node_modules/codemirror/theme lazy ^\.\/.*\.css$ namespace object 160 bytes {main} [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
    [kEOu] external "ws" 42 bytes {main} [built]
    [mcb3] ./node_modules/css-loader/dist/cjs.js!./build/imports.css 4.34 KiB {main} [built]
    [yLpj] (webpack)/buildin/global.js 472 bytes {vendors~main} [built]
        + 3213 hidden modules
    
    WARNING in d3-array
      Multiple versions of d3-array found:
        1.2.4 ./~/d3-geo/~/d3-array from ./~/d3-geo/~/d3-array/src/index.js
        2.6.0 ./~/d3-array from ./~/d3-array/src/index.js
    
    
    WARNING in entities
      Multiple versions of entities found:
        1.1.2 ./~/entities from ./~/htmlparser2/lib/Tokenizer.js
        2.0.3 ./~/dom-serializer/~/entities from ./~/dom-serializer/~/entities/lib/index.js
    
    
    WARNING in semver
      Multiple versions of semver found:
        6.3.0 ./~/semver from ./~/@jupyterlab/extensionmanager/lib/model.js
        7.3.2 ./~/vega-embed/~/semver from ./~/vega-embed/~/semver/index.js
    
    
    WARNING in tslib
      Multiple versions of tslib found:
        1.13.0 ./~/tslib from ./~/@blueprintjs/core/lib/cjs/components/forms/inputGroup.js
        2.0.1 ./~/vega-lite/~/tslib from ./~/vega-lite/build/src/config.js
    
    
    WARNING in vega-util
      Multiple versions of vega-util found:
        1.14.1 ./~/vega-lite/~/vega-util from ./~/vega-lite/~/vega-util/index.js
        1.15.0 ./~/vega-util from ./~/vega-util/index.js
    
    Check how you can resolve duplicate packages: 
    https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle
    
    
    ERROR in ./node_modules/qgrid2/src/otherGrid/frontend/index.js 7:4
    Module parse failed: Unexpected token (7:4)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    | 
    | const render = (el) => ReactDOM.render(
    >     <App />,
    |  el 
    | );
     @ ./node_modules/qgrid2/src/otherGrid/index.js 2:13-40
     @ ./node_modules/qgrid2/src/index.js
     @ ./node_modules/qgrid2/src/jupyterlab-plugin.js
     @ ./build/index.out.js
     @ multi whatwg-fetch ./build/index.out.js
    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [KTNU] ./node_modules/html-loader!./templates/partial.html 703 bytes {0} [built]
        [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
        [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.27 KiB {0} [built]
        [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
            + 1 hidden module
Child
    Hash: 1fd5f40b84accc53cea9
    Time: 970ms
    Built at: 09/12/2020 6:18:59 PM
        Asset       Size  Chunks             Chunk Names
    index.css   15.7 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       3 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-dark-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           3 modules
Child
    Hash: 641cd761e568b9b8c866
    Time: 993ms
    Built at: 09/12/2020 6:18:59 PM
        Asset       Size  Chunks             Chunk Names
    index.css   14.7 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       3 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-light-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           3 modules
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "/usr/local/lib/python3.8/site-packages/jupyterlab/commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/usr/local/lib/python3.8/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```


I can't understand why need to build three times. Build local qgrid package two times. And in staging dir build one time.

**Comment by ParseDark** [comment]
> @nanchenchen I know that @scriptedforms has had some luck bundling an angular application in a JupyterLab extension, without having to using an iframe: https://github.com/SimonBiggs/scriptedforms/blob/master/scriptedforms/docs/create-your-own-angular-jupyterlab-extension.md
> 
> > What I am missing right now is probably the "Those outputs you distribute with your extension and those outputs are what the jupyterlab webpack loads." part -- I am not sure what the exact steps/configures required for this step.
> 
> When you run `jupyter labextension install xxx` it will first install the npm package `xxx` and it will add a require/import statement to import that extension to a JS file. Then that file is run through webpack. When webpack sees the `require('xxx')` statement, it will go and look if it can load this package: https://webpack.js.org/concepts/module-resolution/#module-paths. So it will see if there is a `main` field in the `package.json` and use that to find the file to load. That file should export a JupyterLab extension.
> 
> So if you look at the example I mentioned (https://github.com/saulshanabrook/jupyterlab-webpack), it [outputs a compiled JS file to `./dist/index.js`](https://github.com/saulshanabrook/jupyterlab-webpack/blob/55a7eaba83fdedfdb5b7e093ff008cb8669fa35f/webpack.config.js#L8) and then we [say, in the `package.json` that that file is the one we want to load](https://github.com/saulshanabrook/jupyterlab-webpack/blob/55a7eaba83fdedfdb5b7e093ff008cb8669fa35f/package.json#L5).

I think you didn't get the @nanchenchen point. We can successfully build our widget, but when we run ```jupyter labextension install .``` jupyter build system ignores ourself webpack.config.js. So jupyter build will error.  Can't install widget on jupyter.


look forward to your help. @saulshanabrook .

**Comment by arunkumaralagesan** [comment]
I tried manually updating `webpack.config.js` inside the `staging` directory. But on `jupyter lab build`, the file contents are overwritten with the template file and hence my webpack changes are discarded. Any thoughts on this?
Thanks much in advance
