### ISSUE TITLE
Jupyterlab running inside a docker can't render interactive plots

### ISSUE THREAD

**Issue by whoisshaunakde** [jupyterlab/jupyterlab#5933]
**Describe the bug**
After installing nodejs, npm, ipympl and all the dependencies, when I try to use `%matplotlib widget` I get a `FigureCanvasNbAgg()` text print instead of the figure. I tried looking at similar issues (#2948, #1548, #4787) but wasn't able to solve my issue. 
My notebook (lab?) is running on an EC2 inside a docker. I bind the docker's port 8888 to the EC2 so I can access it via the browser. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45184859/52137114-aadc5c80-25fe-11e9-9827-74f487841d59.png)

**Desktop (please complete the following information):**

- OS: CentOS 7 server and Mac OS 10.14.2 Client
- Browser Chrome 71.x
- JupyterLab 33.12

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
[root@sde101 notebooks]# jupyter troubleshoot
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$PATH:
        /usr/local/bin
        /usr/local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /root/bin

sys.path:
        /usr/local/bin
        /opt/caffe/python
        /usr/local/lib/python27.zip
        /usr/local/lib/python2.7
        /usr/local/lib/python2.7/plat-linux2
        /usr/local/lib/python2.7/lib-tk
        /usr/local/lib/python2.7/lib-old
        /usr/local/lib/python2.7/lib-dynload
        /usr/local/lib/python2.7/site-packages
        /usr/local/lib/python2.7/site-packages/GDAL-1.10.1-py2.7-linux-x86_64.egg
        /usr/local/lib/python2.7/site-packages/newrelic-2.78.0.57

sys.executable:
        /usr/local/bin/python2.7

sys.version:
        2.7.12 (default, Dec  5 2018, 19:25:19)
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

platform.platform():
        Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        Package                            Version
        ---------------------------------- -----------
        absl-py                            0.6.1
        affine                             2.2.1
        apipkg                             1.4
        apispec                            0.39.0
        appdirs                            1.4.3
        argcomplete                        1.9.3
        asn1crypto                         0.24.0
        attrs                              18.2.0
        aws-xray-sdk                       0.95
        awscli                             1.15.47
        backports-abc                      0.5
        backports.shutil-get-terminal-size 1.0.0
        backports.ssl-match-hostname       3.5.0.1
        backports.tempfile                 1.0
        backports.weakref                  1.0.post1
        basemap                            1.0.7
        beautifulsoup4                     4.6.3
        bleach                             1.5.0
        boto                               2.48.0
        boto3                              1.7.47
        botocore                           1.10.83
        bravado                            10.1.0
        bravado-core                       5.10.0
        bumpversion                        0.5.3
        cachetools                         3.0.0
        Cerberus                           1.1
        certifi                            2017.4.17
        cffi                               1.11.2
        chardet                            3.0.4
        chardet2                           2.0.1
        Cheetah                            2.4.4
        click                              6.7
        click-plugins                      1.0.4
        cligj                              0.5.0
        cloudpickle                        0.6.1
        colorama                           0.3.3
        colorlover                         0.2.1
        configparser                       3.5.0
        contextlib2                        0.5.5
        cookies                            2.2.1
        cottoncandy                        0.1.0
        coverage                           4.4.2
        crcmod                             1.7
        cryptography                       2.1.4
        cufflinks                          0.8.2
        cx-Oracle                          7.0.0
        cycler                             0.10.0
        Cython                             0.25.2
        dap                                2.2.6.7
        dask                               1.0.0
        decorator                          4.3.0
        deepdish                           0.3.6
        docker                             3.6.0
        docker-pycreds                     0.4.0
        docutils                           0.13.1
        EasyProcess                        0.2.3
        ecdsa                              0.13
        elasticsearch                      5.3.0
        entrypoints                        0.2.3
        enum34                             1.1.6
        ephem                              3.7.6.0
        execnet                            1.4.1
        Fabric                             1.13.1
        fastparquet                        0.1.5
        faulthandler                       2.6
        flake8                             3.3.0
        Flask                              0.10.1
        Flask-Admin                        1.1.0
        Flask-Login                        0.2.11
        Flask-Session                      0.3.1
        Flask-SQLAlchemy                   2.0
        Flask-WTF                          0.11
        FormEncode                         1.2.6
        funcsigs                           1.0.2
        functools32                        3.2.3.post2
        future                             0.16.0
        futures                            3.2.0
        gbdx-auth                          0.4.0
        gbdxtools                          0.16.0
        gcs-oauth2-boto-plugin             1.14
        GDAL                               1.10.1
        GeoAlchemy2                        0.2.4
        geojson                            2.4.1
        geomet                             0.2.0.post2
        gevent                             1.1.2
        google-api-python-client           1.7.6
        google-apitools                    0.5.16
        google-auth                        1.6.1
        google-auth-httplib2               0.0.3
        googlemaps                         3.0.2
        gpudb                              6.2.0.10
        greenlet                           0.4.12
        gsutil                             4.28
        gyp                                0.1
        h5py                               2.7.1
        html2text                          2018.1.9
        html5lib                           0.9999999
        httplib2                           0.10.3
        idna                               2.6
        inflection                         0.3.1
        ipaddress                          1.0.19
        ipdb                               0.10.2
        ipykernel                          4.8.2
        ipympl                             0.2.1
        ipython                            5.7.0
        ipython-genutils                   0.2.0
        ipywidgets                         7.2.1
        itsdangerous                       0.24
        Jinja2                             2.10
        jmespath                           0.9.2
        joblib                             0.11
        jsondiff                           1.1.1
        jsonpath-ng                        1.4.3
        jsonpickle                         0.9.4
        jsonref                            0.2
        jsonschema                         2.6.0
        JsonWeb                            0.8.2
        jupyter                            1.0.0
        jupyter-client                     5.2.3
        jupyter-console                    5.2.0
        jupyter-core                       4.4.0
        jupyterlab                         0.33.12
        jupyterlab-launcher                0.11.2
        Keras                              2.1.3
        keyring                            10.4.0
        leveldb                            0.194
        llvmlite                           0.26.0
        lmdb                               0.87
        lockfile                           0.12.2
        lxml                               3.7.3
        Markdown                           3.0.1
        MarkupSafe                         1.0
        marshmallow                        3.0.0b12
        marshmallow-enum                   1.4.1
        marshmallow-jsonapi                0.20.1
        matplotlib                         2.0.0
        mccabe                             0.6.1
        meld3                              1.0.2
        mercantile                         1.0.4
        mistune                            0.8.3
        mmh3                               2.5.1
        mock                               2.0.0
        monotonic                          1.5
        moto                               1.3.5
        msgpack-python                     0.5.6
        multiprocessing                    2.6.2.1
        nass                               0.1.1
        nbconvert                          5.3.1
        nbformat                           4.4.0
        networkx                           1.11
        newrelic                           2.78.0.57
        nodejs                             0.1.1
        nose                               1.3.7
        notebook                           5.5.0
        numba                              0.41.0
        numexpr                            2.6.8
        numpy                              1.14.2
        oauth2client                       2.2.0
        oauthlib                           2.1.0
        openapi-spec-validator             0.2.3
        optional-django                    0.1.0
        packaging                          16.8
        pandas                             0.22.0
        pandocfilters                      1.4.2
        paramiko                           2.1.2
        Paste                              1.7.5.1
        PasteDeploy                        1.5.2
        PasteScript                        1.7.5
        pathlib2                           2.3.2
        patsy                              0.4.1
        pbr                                4.0.4
        pep8                               1.6.2
        pexpect                            4.6.0
        pickleshare                        0.7.4
        Pillow                             2.9.0
        pip                                18.1
        pkginfo                            1.4.2
        plotly                             2.0.8
        pluggy                             0.6.0
        ply                                3.11
        prettytable                        0.7.2
        prompt-toolkit                     1.0.15
        protobuf                           3.6.1
        psycopg2                           2.7
        ptyprocess                         0.5.2
        py                                 1.5.2
        py4j                               0.10.7
        pyaml                              18.11.0
        pyarrow                            0.9.0
        pyasn1                             0.4.2
        pyasn1-modules                     0.2.1
        PyAthena                           1.2.2
        pycodestyle                        2.3.1
        pycparser                          2.18
        pycrypto                           2.6.1
        pycryptodome                       3.7.2
        pycurl                             7.43.0.2
        pydns                              2.3.6
        PyDrive                            1.3.1
        pyflakes                           1.5.0
        pygeohash                          1.2.0
        Pygments                           2.2.0
        PyJWT                              1.7.1
        pykml                              0.1.0
        pyminizip                          0.2.3
        pyodbc                             4.0.25
        pyOpenSSL                          17.5.0
        pyparsing                          2.1.10
        pyproj                             1.9.5.1
        Pyro4                              4.39
        pysftp                             0.2.8
        Pysolar                            0.6
        pyspark                            2.3.1
        pystache                           0.5.4
        pytest                             3.3.1
        pytest-cov                         2.5.1
        pytest-forked                      0.2
        pytest-ordering                    0.5
        pytest-runner                      4.2
        pytest-testmon                     0.9.6
        pytest-timeout                     1.2.0
        pytest-xdist                       1.21.0
        python-cjson                       1.2.1
        python-daemon                      2.1.2
        python-dateutil                    2.7.5
        python-gflags                      3.1.2
        python-jose                        2.0.2
        python-ldap                        2.4.19
        python-openid                      2.2.5
        pytz                               2017.3
        PyVirtualDisplay                   0.2.1
        PyYAML                             3.12
        pyzmq                              17.0.0
        qds-sdk                            1.9.8
        qtconsole                          4.3.1
        rasterio                           1.0.9
        redis                              3.0.1
        requests                           2.21.0
        requests-aws4auth                  0.9
        requests-futures                   0.9.9
        requests-oauthlib                  1.0.0
        requests-toolbelt                  0.8.0
        responses                          0.9.0
        retry                              0.9.2
        retry-decorator                    1.1.0
        retrying                           1.3.3
        rmate                              1.0.3
        rpy2                               2.7.5
        rq                                 0.13.0
        rq-scheduler                       0.5.1
        rsa                                3.4.2
        Rtree                              0.8.2
        s3fs                               0.2.0
        s3transfer                         0.1.13
        scandir                            1.7
        scgi                               1.13
        scikit-image                       0.11.3
        scikit-learn                       0.16.1
        scipy                              0.19.0
        seaborn                            0.8.1
        SecretStorage                      2.3.1
        selenium                           3.4.1
        Send2Trash                         1.5.0
        sentinelsat                        0.12.1
        serpent                            1.19
        setuptools                         39.2.0
        Shapely                            1.5.13
        simplegeneric                      0.8.1
        simplejson                         3.16.0
        simpleldap                         0.8
        singledispatch                     3.4.0.3
        six                                1.11.0
        snuggs                             1.4.2
        SocksiPy-branch                    1.1
        SQLAlchemy                         1.0.5
        sqlparse                           0.2.4
        ssh-import-id                      3.21
        statsmodels                        0.8.0
        subprocess32                       3.5.3
        supervisor                         3.3.4
        swagger-spec-validator             2.4.1
        TA-Lib                             0.4.17
        tables                             3.4.4
        Tempita                            0.5.2
        tenacity                           5.0.2
        tensorflow                         1.5.0
        tensorflow-tensorboard             1.5.1
        terminado                          0.8.1
        testfixtures                       4.13.1
        testpath                           0.3.1
        Theano                             1.0.1
        thrift                             0.11.0
        tifffile                           0.11.1
        timezonefinder                     2.0.1
        toolz                              0.9.0
        tornado                            5.0.2
        tqdm                               4.28.1
        traitlets                          4.3.2
        twine                              1.9.1
        typing                             3.6.6
        ua-parser                          0.6.1
        ujson                              1.35
        uritemplate                        3.0.0
        urllib3                            1.24.1
        uWSGI                              2.0.10
        vcrpy                              2.0.1
        wcwidth                            0.1.7
        webencodings                       0.5.1
        websocket-client                   0.54.0
        Werkzeug                           0.12.1
        wheel                              0.32.3
        widgetsnbextension                 3.2.1
        wrapt                              1.10.11
        WTForms                            2.1
        xlrd                               0.9.4
        XlsxWriter                         0.7.6
        xmltodict                          0.11.0
        xmlutils                           1.3
[root@sde101 notebooks]#
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
default.js:924 Exception opening new comm
(anonymous) @ default.js:924
s @ default.js:7
Promise.then (async)
l @ default.js:8
(anonymous) @ default.js:9
YC29.n @ default.js:5
_handleCommOpen @ default.js:909
(anonymous) @ default.js:1016
o @ default.js:6
Promise.then (async)
l @ default.js:8
(anonymous) @ default.js:9
YC29.n @ default.js:5
_handleMessage @ default.js:973
_msgChain._msgChain.then @ default.js:127
Promise.then (async)
_onWSMessage.e @ default.js:124
default.js:132 Error: Object 'jupyter.widget' not found in registry
    at C.Promise (default.js:1472)
    at new Promise (<anonymous>)
    at Object.C [as loadObject] (default.js:1451)
    at _.<anonymous> (default.js:917)
    at Generator.next (<anonymous>)
    at default.js:9
    at new Promise (<anonymous>)
    at YC29.n (default.js:5)
    at _handleCommOpen (default.js:909)
    at _.<anonymous> (default.js:1016)
_msgChain._msgChain.then.catch.e @ default.js:132
Promise.catch (async)
_onWSMessage.e @ default.js:129
default.js:924 Exception opening new comm
(anonymous) @ default.js:924
s @ default.js:7
Promise.then (async)
l @ default.js:8
(anonymous) @ default.js:9
YC29.n @ default.js:5
_handleCommOpen @ default.js:909
(anonymous) @ default.js:1016
o @ default.js:6
Promise.then (async)
l @ default.js:8
(anonymous) @ default.js:9
YC29.n @ default.js:5
_handleMessage @ default.js:973
_msgChain._msgChain.then @ default.js:127
Promise.then (async)
_onWSMessage.e @ default.js:124
default.js:132 Error: Object 'jupyter.widget' not found in registry
    at C.Promise (default.js:1472)
    at new Promise (<anonymous>)
    at Object.C [as loadObject] (default.js:1451)
    at _.<anonymous> (default.js:917)
    at Generator.next (<anonymous>)
    at default.js:9
    at new Promise (<anonymous>)
    at YC29.n (default.js:5)
    at _handleCommOpen (default.js:909)
    at _.<anonymous> (default.js:1016)
</pre>
</details>

**Comment by agoose77** [comment]
You can't change the matplotlib backend once you've set it (or at least, once it's been used). I'm not a developer, but try re-running the notebook with the backend set at the start, and report back! 

Try to provide a minimal-reproducible example notebook, too.

**Comment by tobiasjj** [comment]
I have got the same issue. In a previous jupyterlab version (0.35.4) I could get interactive plots by issuing:
```
import matplotlib
matplotlib.use('module://ipympl.backend_nbagg')
from matplotlib import pyplot as plt
fig, ax = plt.subplots()
ax.plot([1,2,3], [3,2,1])
fig.show()
```
However, now I only get the Text `FigureCanvasNbAgg()`, as described by @whoisshaunakde:

### Desktop/Server:
Debian Buster
Firefox 65.0
Jupyterlab 1.0.0a0
matplotlib 3.0.2
ipympl 0.2.1

**Comment by jasongrout** [comment]
It won't work until we've released an update to ipywidgets supporting JLab 1

**Comment by jasongrout** [comment]
There is an update to Jupyter widgets supporting the 1.0a1 jlab release now: `jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.39`.

**Comment by whoisshaunakde** [comment]
Are there any other dependencies to update? 

I got the following error:
```
[root@sde101 notebooks]# jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.39 --debug
Searching [u'/efs/home/shaunak/notebooks', '/root/.jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /root/.jupyter
Looking for jupyter_config in /efs/home/shaunak/notebooks
> /usr/local/bin/npm pack @jupyter-widgets/jupyterlab-manager@0.39
npm notice
npm notice 📦  @jupyter-widgets/jupyterlab-manager@0.39.0
npm notice === Tarball Contents ===
npm notice 2.1kB package.json
npm notice 1.5kB LICENSE
npm notice 2.0kB README.md
npm notice 131B  lib/index.d.ts
npm notice 410B  lib/index.js
npm notice 2.5kB lib/manager.d.ts
npm notice 6.3kB lib/manager.js
npm notice 1.9kB lib/output.d.ts
npm notice 6.0kB lib/output.js
npm notice 1.1kB lib/plugin.d.ts
npm notice 3.6kB lib/plugin.js
npm notice 829B  lib/renderer.d.ts
npm notice 3.0kB lib/renderer.js
npm notice 216B  lib/semvercache.d.ts
npm notice 972B  lib/semvercache.js
npm notice === Tarball Details ===
npm notice name:          @jupyter-widgets/jupyterlab-manager
npm notice version:       0.39.0
npm notice filename:      jupyter-widgets-jupyterlab-manager-0.39.0.tgz
npm notice package size:  8.6 kB
npm notice unpacked size: 32.4 kB
npm notice shasum:        0a60389a66bb8c54842ef2e97e82e4d6ea899bd8
npm notice integrity:     sha512-FpS/AeDgfesmd[...]g6Yqi8TvFj7KA==
npm notice total files:   15
npm notice
jupyter-widgets-jupyterlab-manager-0.39.0.tgz
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 79, in start
    ans = self.run_task()

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 108, in run_task
    for arg in self.extra_args

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 229, in install_extension
    return handler.install_extension(extension)

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 421, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 1278, in _install_extension
    raise ValueError(msg)

ValueError:
"@jupyter-widgets/jupyterlab-manager@0.39.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/application
>=0.17.3 <0.18.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/rendermime
>=0.17.2 <0.18.0        >=1.0.0-alpha.4 <2.0.0@jupyterlab/notebook



Errored, use --debug for full output:
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.39.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/application
>=0.17.3 <0.18.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/rendermime
>=0.17.2 <0.18.0        >=1.0.0-alpha.4 <2.0.0@jupyterlab/notebook
[root@sde101 notebooks]#
```

**Comment by jasongrout** [comment]
It looks like you haven't upgraded to the 1.0 prerelease. The 0.39 version is only for the JLab 1.0 prerelease.
