### ISSUE TITLE
jupyter lab build fails with shutil.SameFileError

### ISSUE THREAD

**Issue by cinghiopinghio** [jupyterlab/jupyterlab#6162]
Hi,
I've troubles running `jupyter lab build`.
As suggested by `jupyter labextension list` which gives me:
```
JupyterLab v0.35.4
Known labextensions:
   app dir: /usr/lib/python3.7/site-packages/jupyterlab
        jupyterlab-drawio v0.5.0  enabled  OK
        jupyterlab_vim v0.10.1  enabled  OK

Build recommended, please run `jupyter lab build`:
    jupyterlab_vim needs to be included in build
    jupyterlab-drawio needs to be included in build
```

I run `jupyter lab clean && jupyter lab build`.
It seams that it's trying to overwrite an already present file:

```
[LabBuildApp] JupyterLab 0.35.4
[LabBuildApp] Cleaning /usr/lib/python3.7/site-packages/jupyterlab
Cleaning /usr/lib/python3.7/site-packages/jupyterlab...
Success!
[LabBuildApp] Building in /usr/lib/python3.7/site-packages/jupyterlab
[LabBuildApp] Node v11.13.0

Traceback (most recent call last):
  File "/usr/bin/jupyter-lab", line 11, in <module>
    load_entry_point('jupyterlab==0.35.4', 'console_scripts', 'jupyter-lab')()
  File "/usr/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.7/site-packages/notebook/notebookapp.py", line 1760, in start
    super(NotebookApp, self).start()
  File "/usr/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/lib/python3.7/site-packages/jupyterlab/labapp.py", line 78, in start
    command=command, logger=self.log)
  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 274, in build
    command=command, clean_staging=clean_staging)
  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 446, in build
    clean=clean_staging
  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 871, in _populate_staging
    shutil.copy(pjoin(HERE, 'staging', fname), target)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/usr/lib/python3.7/site-packages/jupyterlab/staging/index.js' and '/usr/lib/python3.7/site-packages/jupyterlab/staging/index.js' are the same file
```

**Comment by vidartf** [comment]
@cinghiopinghio Hi and thanks for the feedback! Would you mind trying this in the pre-release of lab 1.0? `pip install --pre jupyterlab`. That will help eliminate some candidates from the troubleshooting.

**Comment by cinghiopinghio** [comment]
Sorry for the delay,

I'm not able t have something working with the extensions.
Both `pip` and the package manager (`pacman`) install the version 1.0a3.
Some extensions require version 1.0a6.

```
Conflicting Dependencies:
JupyterLab              Extension              Package
>=1.0.0-alpha.6 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/application
>=1.0.0-alpha.6 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/rendermime
```

For those working, I receive:

```
Error communicating with server extension. Consult the documentation for how to ensure that it is enabled.
Reason given:
Error: 500 (Internal Server Error)
```
