### ISSUE TITLE
Unable to create/open notebook when disk is full. Misleading error.

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterlab/jupyterlab#6248]
When running out of disk space Jupyter Lab starts giving error messages which seem unrelated.

![image](https://user-images.githubusercontent.com/1610850/56749374-82857980-6779-11e9-846c-7ebfe193fa8b.png)

When checking the logs you can see disk space related errors

```
[I 2019-04-25 15:40:51.771 SingleUserLabApp handlers:153] Creating new notebook in /work/revolver
[E 2019-04-25 15:40:51.772 SingleUserLabApp filemanager:485] Error while saving file: work/revolver/Untitled.ipynb database or disk is full
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 470, in save
        self.check_and_sign(nb, path)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 487, in check_and_sign
        self.notary.sign(nb)
      File "/opt/conda/lib/python3.6/site-packages/nbformat/sign.py", line 449, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/opt/conda/lib/python3.6/site-packages/nbformat/sign.py", line 207, in store_signature
        if not self.check_signature(digest, algorithm):
      File "/opt/conda/lib/python3.6/site-packages/nbformat/sign.py", line 239, in check_signature
        (datetime.utcnow(), algorithm, digest),
    sqlite3.OperationalError: database or disk is full
```

Steps to reproduce:
- Run Jupyter Lab on a machine with a size limited disk 
- Fill the disk (`dd if=/dev/zero of=/path/to/some/file` until full)
- Try to create or open a notebook

**Comment by jasongrout** [comment]
Can you open this issue on the https://github.com/jupyter/notebook repo? That is where the server code is, and where the error message is coming from.
