### ISSUE TITLE
jupyter-widgets-jupyterlab - SSl / self signed certificate in certificate chain

### ISSUE THREAD

**Issue by yyakaule** [jupyterlab/jupyterlab#6293]
jupyterlab 0.28.3; 

Error:

```
(node:40692) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usab
ility issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() method
s instead.
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab%2fapplicatio
n: self signed certificate in certificate chain".
info If you think this is a bug, please open a bug report with the information provided in
 "C:\\Anaconda3\\share\\jupyter\\lab\\staging\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[LabBuildApp] > node C:\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:p
rod
yarn run v1.5.1

```

Log: 
```

Arguments: 
  C:\Anaconda3\envs\myenv\node.exe C:\Anaconda3\share\jupyter\lab\staging\yarn.js run build:prod

PATH: 
  C:\Anaconda3\Library\bin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Anaconda3\envs\myenv;C:\Anaconda3\envs\myenv\Library\mingw-w64\bin;C:\Anaconda3\envs\myenv\Library\usr\bin;C:\Anaconda3\envs\myenv\Library\bin;C:\Anaconda3\envs\myenv\Scripts;C:\Anaconda3\envs\myenv\bin;C:\Anaconda3\condabin;C:\Anaconda3\condabin\..;C:\Anaconda3\condabin\..\Library\mingw-w64\bin;C:\Anaconda3\condabin\..\Library\usr\bin;C:\Anaconda3\condabin\..\Library\bin;C:\Anaconda3\condabin\..\Scripts;C:\Anaconda3\condabin\..\bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Sybase\DBISQL\bin;C:\Sybase\DataAccess\ADONET\dll;C:\Sybase\DataAccess\ODBC\dll;C:\Sybase\DataAccess\OLEDB\dll;C:\Sybase\OCS-15_0\lib3p;C:\Sybase\OCS-15_0\dll;C:\Sybase\OCS-15_0\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;2_5\bin;C:\Program Files (x86)\Sybase\oledb;C:\Program Files (x86)\TIBCO\TIBRV\BIN;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\GitExtensions\;C:\Program Files\dotnet\;C:\Program Files\1010data Inc\Tendo;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\blp\DAPI;C:\blp\DAPI\DDE;C:\Users\yyakaule\AppData\Local\Continuum\Anaconda;C:\Program Files (x86)\Gradle\bin;C:\Users\yyakaule\AppData\Local\Continuum\Anaconda\Scripts;C:\Program Files\wkhtmltopdf\bin;C:\Program Files\R\R-3.2.2\library\tm\ghostscript;C:\Anaconda3\Scripts;F:\My Doc\Python\Bloomberg_api\blpapi_cpp_3.8.18.1-windows\blpapi_cpp_3.8.18.1\lib;C:\Users\yyakaule\AppData\Roaming\Microsoft\AddIns\1010data Inc\1010data Excel Add-in

Yarn version: 
  1.5.1

Node version: 
  10.13.0

Platform: 
  win32 x64

npm manifest: 
  {
      "name": "@jupyterlab/application-top",
      "version": "0.16.3",
      "private": true,
      "scripts": {
          "build": "webpack",
          "build:prod": "webpack --config webpack.prod.config.js",
          "clean": "rimraf build",
          "prepublishOnly": "npm run build",
          "watch": "webpack --watch"
      },
      "dependencies": {
          "@jupyterlab/application": "^0.16.3",
          "@jupyterlab/application-extension": "^0.16.3",
          "@jupyterlab/apputils": "^0.16.4",
          "@jupyterlab/apputils-extension": "^0.16.3",
          "@jupyterlab/cells": "^0.16.3",
          "@jupyterlab/codeeditor": "^0.16.2",
          "@jupyterlab/codemirror": "^0.16.3",
          "@jupyterlab/codemirror-extension": "^0.16.3",
          "@jupyterlab/completer": "^0.16.3",
          "@jupyterlab/completer-extension": "^0.16.3",
          "@jupyterlab/console": "^0.16.3",
          "@jupyterlab/console-extension": "^0.16.3",
          "@jupyterlab/coreutils": "^1.1.3",
          "@jupyterlab/csvviewer": "^0.16.3",
          "@jupyterlab/csvviewer-extension": "^0.16.3",
          "@jupyterlab/docmanager": "^0.16.3",
          "@jupyterlab/docmanager-extension": "^0.16.3",
          "@jupyterlab/docregistry": "^0.16.3",
          "@jupyterlab/faq-extension": "^0.16.3",
          "@jupyterlab/filebrowser": "^0.16.3",
          "@jupyterlab/filebrowser-extension": "^0.16.3",
          "@jupyterlab/fileeditor": "^0.16.3",
          "@jupyterlab/fileeditor-extension": "^0.16.3",
          "@jupyterlab/help-extension": "^0.16.3",
          "@jupyterlab/imageviewer": "^0.16.3",
          "@jupyterlab/imageviewer-extension": "^0.16.3",
          "@jupyterlab/inspector": "^0.16.3",
          "@jupyterlab/inspector-extension": "^0.16.3",
          "@jupyterlab/json-extension": "^0.15.8",
          "@jupyterlab/launcher": "^0.16.3",
          "@jupyterlab/launcher-extension": "^0.16.3",
          "@jupyterlab/mainmenu": "^0.5.3",
          "@jupyterlab/mainmenu-extension": "^0.5.3",
          "@jupyterlab/markdownviewer-extension": "^0.16.3",
          "@jupyterlab/mathjax2-extension": "^0.4.3",
          "@jupyterlab/notebook": "^0.16.3",
          "@jupyterlab/notebook-extension": "^0.16.3",
          "@jupyterlab/observables": "^1.0.10",
          "@jupyterlab/outputarea": "^0.16.3",
          "@jupyterlab/pdf-extension": "^0.7.8",
          "@jupyterlab/rendermime": "^0.16.3",
          "@jupyterlab/rendermime-extension": "^0.10.3",
          "@jupyterlab/rendermime-interfaces": "^1.0.10",
          "@jupyterlab/running": "^0.16.3",
          "@jupyterlab/running-extension": "^0.16.3",
          "@jupyterlab/services": "^2.0.3",
          "@jupyterlab/settingeditor": "^0.5.3",
          "@jupyterlab/settingeditor-extension": "^0.11.3",
          "@jupyterlab/shortcuts-extension": "^0.16.3",
          "@jupyterlab/tabmanager-extension": "^0.16.3",
          "@jupyterlab/terminal": "^0.16.3",
          "@jupyterlab/terminal-extension": "^0.16.3",
          "@jupyterlab/theme-dark-extension": "^0.16.3",
          "@jupyterlab/theme-light-extension": "^0.16.3",
          "@jupyterlab/tooltip": "^0.16.3",
          "@jupyterlab/tooltip-extension": "^0.16.3",
          "@jupyterlab/vdom-extension": "^0.15.8",
          "@jupyterlab/vega3-extension": "^0.15.3",
          "@phosphor/algorithm": "^1.1.2",
          "@phosphor/application": "^1.5.0",
          "@phosphor/commands": "^1.4.0",
          "@phosphor/coreutils": "^1.3.0",
          "@phosphor/datagrid": "^0.1.5",
          "@phosphor/disposable": "^1.1.2",
          "@phosphor/domutils": "^1.1.2",
          "@phosphor/dragdrop": "^1.3.0",
          "@phosphor/messaging": "^1.2.2",
          "@phosphor/properties": "^1.1.2",
          "@phosphor/signaling": "^1.2.2",
          "@phosphor/virtualdom": "^1.1.2",
          "@phosphor/widgets": "^1.5.0",
          "ajv": "~5.1.6",
          "ansi_up": "^3.0.0",
          "codemirror": "~5.35.0",
          "comment-json": "^1.1.3",
          "es6-promise": "~4.1.1",
          "marked": "~0.3.9",
          "moment": "~2.21.0",
          "path-posix": "~1.0.0",
          "react": "~16.2.0",
          "react-dom": "~16.2.0",
          "sanitize-html": "~1.14.3",
          "url-parse": "~1.1.9",
          "xterm": "~2.8.1",
          "@jupyter-widgets/jupyterlab-manager": "file:../extensions/jupyter-widgets-jupyterlab-manager-0.35.0.tgz"
      },
      "devDependencies": {
          "@jupyterlab/buildutils": "^0.7.3",
          "css-loader": "~0.28.7",
          "file-loader": "~0.10.1",
          "fs-extra": "~4.0.2",
          "glob": "~7.1.2",
          "handlebars": "~4.0.11",
          "html-loader": "^0.5.1",
          "html-webpack-plugin": "~2.30.1",
          "json-loader": "~0.5.7",
          "raw-loader": "~0.5.1",
          "rimraf": "~2.6.2",
          "sort-package-json": "~1.7.1",
          "source-map-loader": "~0.2.1",
          "style-loader": "~0.13.2",
          "uglifyjs-webpack-plugin": "~1.1.5",
          "url-loader": "~0.5.9",
          "webpack": "~2.7.0",
          "webpack-merge": "^4.1.1"
      },
      "jupyterlab": {
          "extensions": {
              "@jupyterlab/application-extension": "",
              "@jupyterlab/apputils-extension": "",
              "@jupyterlab/codemirror-extension": "",
              "@jupyterlab/completer-extension": "",
              "@jupyterlab/console-extension": "",
              "@jupyterlab/csvviewer-extension": "",
              "@jupyterlab/docmanager-extension": "",
              "@jupyterlab/faq-extension": "",
              "@jupyterlab/filebrowser-extension": "",
              "@jupyterlab/fileeditor-extension": "",
              "@jupyterlab/help-extension": "",
              "@jupyterlab/imageviewer-extension": "",
              "@jupyterlab/inspector-extension": "",
              "@jupyterlab/launcher-extension": "",
              "@jupyterlab/mainmenu-extension": "",
              "@jupyterlab/markdownviewer-extension": "",
              "@jupyterlab/mathjax2-extension": "",
              "@jupyterlab/notebook-extension": "",
              "@jupyterlab/rendermime-extension": "",
              "@jupyterlab/running-extension": "",
              "@jupyterlab/settingeditor-extension": "",
              "@jupyterlab/shortcuts-extension": "",
              "@jupyterlab/tabmanager-extension": "",
              "@jupyterlab/terminal-extension": "",
              "@jupyterlab/theme-dark-extension": "",
              "@jupyterlab/theme-light-extension": "",
              "@jupyterlab/tooltip-extension": "",
              "@jupyter-widgets/jupyterlab-manager": ""
          },
          "mimeExtensions": {
              "@jupyterlab/json-extension": "",
              "@jupyterlab/pdf-extension": "",
              "@jupyterlab/vdom-extension": "",
              "@jupyterlab/vega3-extension": ""
          },
          "name": "JupyterLab",
          "buildDir": "./build",
          "outputDir": "..",
          "singletonPackages": [
              "@jupyterlab/application",
              "@jupyterlab/apputils",
              "@jupyterlab/console",
              "@jupyterlab/coreutils",
              "@jupyterlab/docmanager",
              "@jupyterlab/filebrowser",
              "@jupyterlab/fileeditor",
              "@jupyterlab/imageviewer",
              "@jupyterlab/launcher",
              "@jupyterlab/notebook",
              "@jupyterlab/rendermime",
              "@jupyterlab/rendermime-interfaces",
              "@jupyterlab/services",
              "@jupyterlab/terminal",
              "@jupyterlab/tooltip",
              "@phosphor/coreutils",
              "@phosphor/widgets"
          ],
          "vendor": [
              "@phosphor/algorithm",
              "@phosphor/application",
              "@phosphor/commands",
              "@phosphor/coreutils",
              "@phosphor/datagrid",
              "@phosphor/disposable",
              "@phosphor/domutils",
              "@phosphor/dragdrop",
              "@phosphor/messaging",
              "@phosphor/properties",
              "@phosphor/signaling",
              "@phosphor/virtualdom",
              "@phosphor/widgets",
              "ajv",
              "ansi_up",
              "codemirror",
              "comment-json",
              "es6-promise",
              "marked",
              "moment",
              "path-posix",
              "react",
              "react-dom",
              "sanitize-html",
              "url-parse",
              "xterm"
          ],
          "version": "0.32.1",
          "linkedPackages": {},
          "staticDir": "../static"
      }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: Command failed.
  Exit code: 1
  Command: C:\WINDOWS\system32\cmd.exe
  Arguments: /d /s /c webpack --config webpack.prod.config.js
  Directory: ****\\share\jupyter\lab\staging
  Output:
  
      at ProcessTermError.MessageError (****\\share\jupyter\lab\staging\yarn.js:186:110)
      at new ProcessTermError (****\\share\jupyter\lab\staging\yarn.js:226:113)
      at ChildProcess.<anonymous> (****\share\jupyter\lab\staging\yarn.js:30281:17)
      at ChildProcess.emit (events.js:182:13)
      at maybeClose (internal/child_process.js:962:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

```

**Comment by yyakaule** [comment]
Looks like was able to overcome the error: 

Modify yarnrc
**\Lib\site-packages\jupyterlab\staging\.yarnrc

add line: 
strict-ssl false

when you run :+1: 
node C:\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\staging\yarn.js install

go to dir:

C:\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\staging\

**Comment by jasongrout** [comment]
Disabling ssl is one way to work around it. Probably even better is to find out why there was an ssl error (corporate proxy?) and fix that issue.

Closing as resolved, though, given the above comment. This is a network setup issue, not a JLab issue.
