### ISSUE TITLE
ModuleNotFoundError: No module named 'jupyterlab.labapp'`

### ISSUE THREAD

**Issue by DevinRouth** [jupyterlab/jupyterlab#6474]
Hi there,

I run a MacOS 10.14.4 machine using pip to manage my packages. I previously had a development version of Jupyter Lab on my machine that wasn't working, and tried to fix it by upgrading to the latest version of Jupyter Lab using "pip3 install -U jupyterlab". The command ran to completion, but upon trying to start Jupyter Lab I receive the following errors and decided to report them this time for assistance.

`Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 11, in <module>
    load_entry_point('jupyterlab==0.29.0.dev0', 'console_scripts', 'jupyter-lab')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'jupyterlab.labapp'`

How should I proceed?

Cheers,
Devin

**Comment by blink1073** [comment]
It looks like the dev version is tripping up `pip`.  Can you please run `pip3 uninstall jupyterlab` until it tells you that it is no longer installed and then run `pip3 install jupyterlab`?

**Comment by DevinRouth** [comment]
Hi again,

Sure thing. I ran `pip3 uninstall jupyterlab` and received the following output:

```
Uninstalling jupyterlab-0.35.6:
 Would remove:
    /usr/local/lib/python3.6/site-packages/jupyterlab-0.35.6.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled jupyterlab-0.35.6
```

I then ran `pip3 install jupyterlab` and received:

```
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.6/site-packages (0.29.0.dev0)
Requirement already satisfied: notebook>=4.3.1 in /usr/local/lib/python3.6/site-packages (from jupyterlab) (5.5.0)
Requirement already satisfied: jupyterlab_launcher<0.6.0,>=0.5.2 in /usr/local/lib/python3.6/site-packages (from jupyterlab) (0.5.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (2.9.4)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (4.3.2)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (0.2.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (17.0.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (5.1.1)
Requirement already satisfied: tornado>=4 in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (4.4.2)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (4.5.2)
Requirement already satisfied: jupyter-core>=4.4.0 in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (4.4.0)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (1.5.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (4.2.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (0.8.1)
Requirement already satisfied: jupyter-client>=5.2.0 in /usr/local/lib/python3.6/site-packages (from notebook>=4.3.1->jupyterlab) (5.2.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from jinja2->notebook>=4.3.1->jupyterlab) (0.23)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (4.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (1.11.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (1.5.0)
Requirement already satisfied: mistune!=0.6 in /usr/local/lib/python3.6/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.7.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (1.4.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (2.2.0)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.3)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.6/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.2.2)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.6/site-packages (from ipykernel->notebook>=4.3.1->jupyterlab) (6.2.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.6/site-packages (from nbformat->notebook>=4.3.1->jupyterlab) (2.6.0)
Requirement already satisfied: ptyprocess; os_name != "nt" in /usr/local/lib/python3.6/site-packages (from terminado>=0.8.1->notebook>=4.3.1->jupyterlab) (0.5.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/site-packages (from jupyter-client>=5.2.0->notebook>=4.3.1->jupyterlab) (2.5.0)
Requirement already satisfied: html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 in /usr/local/lib/python3.6/site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab) (0.9999999)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (39.0.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (4.3.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (1.0.15)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.7.4)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.8.1)
Requirement already satisfied: appnope; sys_platform == "darwin" in /usr/local/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.1.0)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.11.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.1.7)
Requirement already satisfied: parso==0.1.0 in /usr/local/lib/python3.6/site-packages (from jedi>=0.10->ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.1.0)
```

So it looks like the uninstall didn't work given the requirements are still satisfied after the attempted uninstall.

What would you next suggest?

Thanks!

**Comment by DevinRouth** [comment]
P.S. a `pip3 list` call after the `pip3 uninstall jupyterlab` shows that I still have `jupyterlab-launcher 0.5.4` and `jupyterlab-server 0.2.0`, indicating (I think) that I wasn't able to successfully uninstall the Jupyter Lab dev version fully. Should I delete these particular jupyterlab submodules more specifically, and if so could you recommend the cleanest way?

**Comment by DevinRouth** [comment]
Ahhh, I managed to fix it following some of the other debugging guidance. After trying another `pip3 install jupyterlab` I appended `/Library/Python/3.6/bin` to my `$PATH`, and it seems to be working smoothly. Thanks again for the help!

**Comment by blink1073** [comment]
Glad you got sorted!  Yeah, installation feels like whack a mole sometimes. 😀
