### ISSUE TITLE
cannot run container in read only mode

### ISSUE THREAD

**Issue by doutriaux1** [jupyterlab/jupyterlab#6535]
the follwoing works fine:

```
docker run  -p 8081:8081  -p 8888:8888 -v $HOME:/home/jovyan -it  cdoutrix/vcdat:latest  jupyter-lab
```

But when running in read only:

```
docker run --read-only -p 8081:8081  -p 8888:8888 -v $HOME:/home/jovyan -it  cdoutrix/vcdat:latest  jupyter-lab
```

I get:

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 37, in <module>
    app_version = get_app_version()
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 348, in get_app_version
    handler = _AppHandler(app_dir)
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 386, in __init__
    self.info = self._get_app_info()
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 812, in _get_app_info
    info['local_extensions'] = self._get_local_extensions()
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1108, in _get_local_extensions
    return self._get_local_data('local_extensions')
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1243, in _get_local_data
    self._write_build_config(config)
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1204, in _write_build_config
    with open(target, 'w') as fid:
OSError: [Errno 30] Read-only file system: '/opt/conda/share/jupyter/lab/settings/build_config.json'
```

**Comment by doutriaux1** [comment]
if I build the extension in the container from the npm repo rather than from the github sources:
```
jupyter-labextension install jupyter-vcdat
```
The the container can be executed read-only

**Comment by jtpio** [comment]
@doutriaux1 thanks for the report.

Do you have a link to the Dockerfile used to build this image?

**Comment by doutriaux1** [comment]
dockeR: `cdoutrix/vcdat:2.0.0` is the one that was built with `jupyter-labenxtion install .` and cannot be mounted read-only

`cdoutrix/vcdat:latest` was built with `jupyter-labexntsion install jupyter-vcdat` (i.e from npm) and can read only.

**Comment by jasongrout** [comment]
Is this still an issue?

**Comment by doutriaux1** [comment]
@jasongrout I'm no longer involved with the projectt, but @downie4 is now leading it, he will know.

**Comment by jasongrout** [comment]
Thanks for responding. I see we're practically neighbors. It would be great to connect sometime (post-COVID, I guess).

**Comment by downiec** [comment]
I believe we worked around this issue successfully a while ago. As things are now, I don't believe this is a concern and I can create a new issue with updated details if needed.
