### ISSUE TITLE
Installing jupyterlab-manager fails with TypeError: "_extract_package()" got an unexpected argument 'quiet'"

### ISSUE THREAD

**Issue by tobiasjj** [jupyterlab/jupyterlab#6634]
**Describe the bug**
Dear all,
I'm running the latest jupyterlab instance from git. A recent upgrade attempt failed when trying to install the jupyterlab-manager labextension:
```
# jupyter labextension install @jupyter-widgets/jupyterlab-manager
An error occured.
TypeError: _extract_package() got an unexpected keyword argument 'quiet'
See the log file for details:  /tmp/jupyterlab-debug-h51mtpyp.log
```
The log file contained the following:
```
Node v10.15.2

> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
jupyter-widgets-jupyterlab-manager-0.41.0.tgz

Fetching URL: https://registry.npmjs.org/@jupyter-widgets%2Fjupyterlab-manager
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 82, in start
    ans = self.run_task()

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 1396, in _install_extension
    version = self._latest_compatible_package_version(name)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 1485, in _latest_compatible_package_version
    '%s@%s' % (name, version), tempdir, quiet=True)

TypeError: _extract_package() got an unexpected keyword argument 'quiet'

Exiting application: jupyter
```

The issue seems to be the parameter "quiet" in line 1485 in the file `/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py`:

```
...
                      '%s@%s' % (name, version), tempdir, quiet=True)
...
```

A simple fix seems to be deleting the parameter and jupyterlab installs fine. Is this probably a left over from commit (https://github.com/jupyterlab/jupyterlab/pull/6567/commits/64ba3c82f9203efc5f9102369acc2e402c700ea0)?

**To Reproduce**
```
# pip3 install --force-reinstall --upgrade git+git://github.com/jupyterlab/jupyterlab
# jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Desktop (please complete the following information):**

- OS: [Debian 10]
- JupyterLab [a1b9bdd17c36d2a8fa0e8d7613556253d9aaad49]

**Comment by echarles** [comment]
I also face this. For now I simply remove `, quiet=True` from the `commands.py` (line 1485) and it works fine.  I haven't nailed down the installation step where it was occuring in my installation script.

We can fix it this way removing `, quiet=True` but we would not know the source of the issue...

**Comment by vidartf** [comment]
Seems like a left over from the silencing PR, as you spotted. A PR simply removing the keyword would be very much appreciated! 👍
