### ISSUE TITLE
File Load Error: Unhandled error

### ISSUE THREAD

**Issue by claraabello** [jupyterlab/jupyterlab#6640]
Hi all!

New here so my apologises if this doesn't go here.

I was using jupyterlab in Google Chrome and it suddenly started failing, not being able to save or open any file.

Logs when it started failing:
`[I 17:25:07.392 LabApp] Adapting to protocol v5.1 for kernel b0009b68-ade6-4db3-9b66-cbb73cc99b89
[E 17:25:07.618 LabApp] Uncaught exception PUT /lab/api/workspaces/lab?1560957907606 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='PUT', uri='/lab/api/workspaces/lab?1560957907606', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/base/handlers.py", line 723, in wrapper
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyterlab_server/workspaces_handler.py", line 179, in put
    OSError: [Errno 24] Too many open files: '/Users/clara/.jupyter/lab/workspaces/lab-a511.jupyterlab-workspace'
[W 17:25:07.634 LabApp] Unhandled error
[E 17:25:07.636 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "1516",
      "Authorization": "token 6569e579e1ca437e04751a4d62d80d3ce0bb8f50f6ed92c2",
      "Origin": "http://localhost:8888",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "_xsrf=2|ae19b999|9db23d2e9b64456a79b521f7c4b5c05d|1559149307; username-localhost-8888=\"2|1:0|10:1560957907|23:username-localhost-8888|44:NGY3ZTY5NjRhOGM4NDBhOTg0ZmEzZDVkNmJlMzE4OTM=|0913d9146c314a8afe8a66cc5e551b4248c2010f13ac360ca9f215155a8979c8\""
    }
[E 17:25:07.636 LabApp] 500 PUT /lab/api/workspaces/lab?1560957907606 (::1) 24.70ms referer=http://localhost:8888/lab
`

Reading about other issues on loading files I tried re-starting jupyterlab, updating it and updating notebook and nbformat and clearing my browser cache. None of it worked, and I wasn't able to find the same issue except for issue [#11649](https://github.com/ipython/ipython/issues/11649) which has no useful answer and it's closed.

The error I get now every time I try to open a file: 
`[E 18:05:06.481 LabApp] Uncaught exception GET /api/contents/Documents/Chicfy/embajadoras2.0.ipynb?type=notebook&content=1&1560960306473 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8838', method='GET', uri='/api/contents/Documents/Chicfy/embajadoras2.0.ipynb?type=notebook&content=1&1560960306473', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 433, in get
        model = self._notebook_model(path, content=content)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 392, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 503, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbformat/sign.py", line 439, in check_signature
        return self.store.check_signature(signature, self.algorithm)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbformat/sign.py", line 239, in check_signature
        (datetime.utcnow(), algorithm, digest),
    sqlite3.OperationalError: database is locked
[W 18:05:06.481 LabApp] Unhandled error
[E 18:05:06.482 LabApp] {
      "Host": "localhost:8838",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36",
      "Authorization": "token 3f85c59c72cd40f5c62cb50bb048b5a8ebfb929712a3eb90",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8838/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "_xsrf=2|ca840b3b|700cbe1fda223452f9af972dcbb55885|1560959338; username-localhost-8838=\"2|1:0|10:1560960302|23:username-localhost-8838|44:ZjYxZTU0Yjk5NDZkNDhkNThhYWU2ZmE2NDg0MTExN2Y=|40697dadf76d8bac9ae2a340421aa64a084f7a6af41c9bee59d357b376fc0d39\""
    }
[E 18:05:06.482 LabApp] 500 GET /api/contents/Documents/Chicfy/embajadoras2.0.ipynb?type=notebook&content=1&1560960306473 (::1) 7.18ms referer=http://localhost:8838/lab`

Thanks in advance for any advice you could give!

**Comment by claraabello** [comment]
The issue fixed itself today, not sure why.

**Comment by claraabello** [comment]
fake news it stills failing, now it says: database is locked

**Comment by claraabello** [comment]
I guess not as it is 1.5 years old. Not even sure if I ever fixed it or re-installed all again
