### ISSUE TITLE
too many problems and warnings when installing JupyterLab / Data Voyager

### ISSUE THREAD

**Issue by richdevboston** [jupyterlab/jupyterlab#6732]
If you are having issues with installation or configuration, we encourage you to post in the [Jupyter Discourse forum](https://discourse.jupyter.org/c/jupyterlab) or file an issue here.

I am going round in circles with JavaScript trying to resolve warnings and error when getting JupyterLab notebook extensions installed.  I've already hosed one installation of Anaconda, and had to call in IT to help me resolve problems.  I thought Python had too many dependencies, but at least with conda and pip, there aren't so many different Javascript package managers (yarn, npm, jlpms, etc.), trying to manage the same packages and not doing a good job of staying out of each other's way.  

What do people suggest to resolve this?   I don't have admin rights on this laptop but at least the Anaconda distro is installed in a single user account.  I was able to install and upgrade npm and yarn tonight, which got rid of many warnings.  However, the suggestion on how to resolve the duplicate packages messages was very incomplete for a non-JavaScript programmer to understand how to make configuration changes.  I just want to get the various JupyterLab extensions installed and working.  

I get the following warnings and error messages after doing `jupyter clean` and `jupyter build` commands.  

(quantecon) C:\Anaconda3\envs\quantecon>jupyter lab clean
[LabCleanApp] Cleaning C:\Anaconda3\envs\quantecon\share\jupyter\lab...
[LabCleanApp] Success!

(quantecon) C:\Anaconda3\envs\quantecon>jupyter lab build
[LabBuildApp] JupyterLab 0.35.4
[LabBuildApp] Cleaning C:\Anaconda3\envs\quantecon\share\jupyter\lab
Cleaning C:\Anaconda3\envs\quantecon\share\jupyter\lab...
Success!
[LabBuildApp] Building in C:\Anaconda3\envs\quantecon\share\jupyter\lab
[LabBuildApp] Node v11.14.0

[LabBuildApp] > node C:\Anaconda3\envs\quantecon\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @jupyterlab/application > @jupyterlab/apputils > react > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning @jupyterlab/application > @jupyterlab/coreutils > comment-json > json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
warning jupyterlab_voyager > datavoyager > react-file-download@0.3.5: WARNING: This project has been renamed to js-file-download. Use js-file-download instead.
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > request > hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk > sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk > cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk > cryptiles > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk > sntp > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning jupyterlab_voyager > datavoyager > vega > canvas-prebuilt > node-pre-gyp > hawk > boom > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning css-loader > cssnano > postcss-merge-rules > postcss-selector-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[3/5] Fetching packages...
[--------------------------------------------------------------------------------------------------------------------------------------------------------] 0/1222(node:22040) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
warning "@jupyterlab/vega4-extension > vega-embed > vega-themes@2.3.0" has unmet peer dependency "vega@*".
warning "@jupyterlab/vega4-extension > vega-embed > vega-lite@2.7.0" has unmet peer dependency "vega@^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
[-/7] ⠠ waiting...
[6/7] ⠐ node-sass
[3/7] ⠐ canvas
[4/7] ⠐ canvas-prebuilt
warning Error running install script for optional dependency: "C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas
Output:
(quantecon) C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Anaconda3\\envs\\quantecon\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.14.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\\Anaconda3\\envs\\quantecon\\python.EXE -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack   File \"<string>\", line 1
gyp ERR! stack     import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command \"C:\\\\Anaconda3\\\\envs\\\\quantecon\\\\node.exe\" \"C:\\\\Anaconda3\\\\envs\\\\quantecon\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas
[-/7] ⢀ waiting...
[6/7] ⠠ node-sass
[-/7] ⠠ waiting...
[4/7] ⠠ canvas-prebuilt
warning Error running install script for optional dependency: "C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\datavoyager\\node_modules\\vega-tooltip\\node_modules\\canvas-prebuilt: Command failed.
Exit code: 1
Command: node_modules\\.bin\\node-pre-gyp install
Arguments:
Directory: C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\datavoyager\\node_modules\\vega-tooltip\\node_modules\\canvas-prebuilt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@11.14.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\datavoyager\\node_modules\\vega-tooltip\\node_modules\\canvas-prebuilt\\canvas\\build\\Release\\canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-win32-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\datavoyager\\node_modules\\node-pre-gyp\\lib\\install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:198:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\request\\request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:193:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:23)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:447:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:193:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:276:11)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command \"C:\\\\Anaconda3\\\\envs\\\\quantecon\\\\node.exe\" \"C:\\\\Anaconda3\\\\envs\\\\quantecon\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\datavoyager\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\datavoyager\\node_modules\\vega-tooltip\\node_modules\\canvas-prebuilt
node-pre-gyp ERR! node -v v11.14.0
[-/7] ⠈ waiting...
[6/7] ⠁ node-sass
[-/7] ⠁ waiting...
[4/7] ⠁ canvas-prebuilt
warning Error running install script for optional dependency: "C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt: Command failed.
Exit code: 1
Command: node_modules\\.bin\\node-pre-gyp install
Arguments:
Directory: C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@11.14.0 | win32 | x64
node-pre-gyp info check checked for \"C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt\\canvas\\build\\Release\\canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.5-prerelease.1/canvas-prebuilt-v1.6.5-prerelease.1-node-v67-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.5-prerelease.1/canvas-prebuilt-v1.6.5-prerelease.1-node-v67-win32-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.5-prerelease.1/canvas-prebuilt-v1.6.5-prerelease.1-node-v67-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt\\node_modules\\node-pre-gyp\\lib\\install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:198:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt\\node_modules\\request\\request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:193:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:23)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:447:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:193:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:276:11)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command \"C:\\\\Anaconda3\\\\envs\\\\quantecon\\\\node.exe\" \"C:\\\\Anaconda3\\\\envs\\\\quantecon\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\canvas-prebuilt\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd C:\\Anaconda3\\envs\\quantecon\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt
node-pre-gyp ERR! node -v v11.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
success Saved lockfile.
Done in 98.11s.
[LabBuildApp] > node C:\Anaconda3\envs\quantecon\lib\site-packages\jupyterlab\staging\yarn.js run build
yarn run v1.9.4
$ webpack
Hash: 696e81ad91a4cf644b9d
Version: webpack 4.12.2
Time: 22205ms
Built at: 06/29/2019 2:14:31 AM
                                   Asset      Size        Chunks             Chunk Names
    674f50d287a8c48dc19ba404d20fe713.eot   162 KiB                [emitted]
  af7ae505a9eed503f8b8e6982036873e.woff2  75.4 KiB                [emitted]
    042585f85647282a772c7f9b7e35fe2a.png  1.33 KiB                [emitted]
    13059a40029bff639fbea99f998fd72d.png  21.3 KiB                [emitted]
    912ec66d7572ff821749319396470bde.svg   434 KiB                [emitted]
   fee66e712a8a08eef5805a46892932ad.woff  95.7 KiB                [emitted]
    79b3ad7a8ae5402898cd21342a89f645.png  8.87 KiB                [emitted]
    b06871f281fee6b241d60582ae9369b9.ttf   162 KiB                [emitted]
            main.538685eff9e310e82277.js  61.5 KiB          main  [emitted]  main
               0.cc98107762fcc28532b3.js   4.5 KiB             0  [emitted]
    vendors~main.de5ff97158c9759be29f.js  16.4 MiB  vendors~main  [emitted]  vendors~main
    vendors~vega.b36f5a9a31bc4a7d5de4.js  1.62 MiB  vendors~vega  [emitted]  vendors~vega
               1.055322dcf6c2bb19185f.js   888 KiB             1  [emitted]
        main.538685eff9e310e82277.js.map  72.8 KiB          main  [emitted]  main
           0.cc98107762fcc28532b3.js.map  5.73 KiB             0  [emitted]
vendors~main.de5ff97158c9759be29f.js.map  17.5 MiB  vendors~main  [emitted]  vendors~main
vendors~vega.b36f5a9a31bc4a7d5de4.js.map  1.49 MiB  vendors~vega  [emitted]  vendors~vega
           1.055322dcf6c2bb19185f.js.map  1.04 MiB             1  [emitted]
                              index.html  1.54 KiB                [emitted]
Entrypoint main = vendors~main.de5ff97158c9759be29f.js vendors~main.de5ff97158c9759be29f.js.map main.538685eff9e310e82277.js main.538685eff9e310e82277.js.map
 [0] multi whatwg-fetch ./build/index.out.js 40 bytes {main} [built]
 [3UD+] (webpack)/buildin/harmony-module.js 573 bytes {vendors~main} [built]
 [ANye] ./build/index.out.js 36.7 KiB {main} [built]
 [yLpj] (webpack)/buildin/global.js 489 bytes {vendors~main} [built]
 [1] vertx (ignored) 15 bytes {main} [optional] [built]
 [HDxf] ./node_modules/datavoyager/node_modules/moment/locale sync ^\.\/.*$ 3 KiB {main} [optional] [built]
 [RnhZ] ./node_modules/moment/locale sync ^\.\/.*$ 2.88 KiB {main} [optional] [built]
 [YuTi] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
 [eTbV] ./node_modules/codemirror/mode sync ^\.\/.*\.js$ 2.78 KiB {0} [built]
 [4] buffer (ignored) 15 bytes {main} [optional] [built]
 [5] crypto (ignored) 15 bytes {main} [optional] [built]
 [6] readable-stream (ignored) 15 bytes {main} [built]
[10] node-fetch (ignored) 15 bytes {main} [built]
[11] fs (ignored) 15 bytes {main} [built]
[12] node-fetch (ignored) 15 bytes {main} [built]
    + 3746 hidden modules

WARNING in css-loader
  Multiple versions of css-loader found:
    0.28.11 ./~/css-loader from ./~/@jupyterlab\json-extension\style\index.css
    3.0.0 ./~/font-awesome-sass-loader/~/css-loader from ./~/font-awesome-sass-loader\font-awesome-sass.config.js

WARNING in d3-array
  Multiple versions of d3-array found:
    1.2.4 ./~/d3-scale/~/d3-array from ./~/d3-scale/~/d3-array\src\index.js
    2.2.0 ./~/d3-array from ./~/d3-array\src\index.js

WARNING in hoist-non-react-statics
  Multiple versions of hoist-non-react-statics found:
    2.5.5 ./~/hoist-non-react-statics from ./~/datavoyager/~/react-dnd\lib\DragLayer.js
    3.3.0 ./~/datavoyager/~/react-redux/~/hoist-non-react-statics from ./~/datavoyager/~/react-redux\es\components\connectAdvanced.js

WARNING in moment
  Multiple versions of moment found:
    2.21.0 ./~/moment
    2.24.0 ./~/datavoyager/~/moment

WARNING in react
  Multiple versions of react found:
    15.6.2 ./~/datavoyager/~/react from ./~/datavoyager/~/react\lib\React.js
    16.4.2 ./~/react from ./~/react\index.js

WARNING in react-dom
  Multiple versions of react-dom found:
    15.6.2 ./~/datavoyager/~/react-dom from ./~/datavoyager/~/react-dom\lib\ReactDefaultInjection.js
    16.4.2 ./~/react-dom from ./~/react-dom\index.js

WARNING in style-loader
  Multiple versions of style-loader found:
    0.21.0 ./~/style-loader from ./~/style-loader\lib\addStyles.js
    0.23.1 ./~/font-awesome-sass-loader/~/style-loader from ./~/font-awesome-sass-loader\font-awesome-sass.config.js

WARNING in vega-lib
  Multiple versions of vega-lib found:
    4.0.0 ./~/datavoyager/~/vega-lib from ./~/datavoyager/~/vega-lib\index.js
    4.4.0 ./~/vega-lib from ./~/vega-lib\index.js

WARNING in vega-lite
  Multiple versions of vega-lite found:
    2.4.0 ./~/datavoyager/~/vega-lite\build\src from ./~/datavoyager/~/vega-lite\build\src\compile\data\assemble.js
    2.7.0 ./~/datavoyager/~/vega-tooltip/~/vega-lite\build from ./~/datavoyager/~/vega-tooltip/~/vega-lite\build\src\compile\data\assemble.js

WARNING in vega-tooltip
  Multiple versions of vega-tooltip found:
    0.12.0 ./~/vega-tooltip from ./~/vega-tooltip\build\Handler.js
    0.4.4 ./~/datavoyager/~/vega-tooltip from ./~/datavoyager/~/vega-tooltip\build\src\index.js

Check how you can resolve duplicate packages:
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [KTNU] ./node_modules/html-loader!./templates/partial.html 567 bytes {0} [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.22 KiB {0} [built]
    [yLpj] (webpack)/buildin/global.js 489 bytes {0} [built]
        + 1 hidden module
Done in 25.60s.

**Comment by vidartf** [comment]
Hi @richdevboston! A lot of information during extension install was shown before 1.0.0 (released yesterday). Now it has been made quiet by default, and all of these expected warnings are hidden. So please try out 1.0 and see if that works better for you (although probably not all the extensions you want are available for 1.0 yet).

**Comment by vidartf** [comment]
Closing as answered since the underlying issue has been resolved in 1.0, and there has been no further replies.
