### ISSUE TITLE
Unit tests are not working

### ISSUE THREAD

**Issue by ieglonew01f** [jupyterlab/jupyterlab#6781]
Here is what I get when I try to run `npm test` under test-application

```
> npm test

> @jupyterlab/test-application@1.0.0 test /Users/XXXXXX/Work/jupyterlab/tests/test-application
> python run.py

[I 14:17:47.905 JestApp] Writing notebook server cookie secret to /var/folders/67/5kx_0t217_x84fls1w68h494rwpbn8/T/tmps59gg6vh/jupyter_runtime/notebook_cookie_secret
[I 14:17:47.932 JestApp] The port 8888 is already in use, trying another port.
[I 14:17:47.945 JestApp] Serving notebooks from local directory: /var/folders/67/5kx_0t217_x84fls1w68h494rwpbn8/T/mock_contentsg5snhfb7
[I 14:17:47.945 JestApp] The Jupyter Notebook is running at:
[I 14:17:47.945 JestApp] http://localhost:8889/?token=fb027382ccd2ed0fe44c65c613155c7c4bb95446cfda3946
[I 14:17:47.945 JestApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:17:47.948 JestApp]

    To access the notebook, open this file in a browser:
        file:///var/folders/67/5kx_0t217_x84fls1w68h494rwpbn8/T/tmps59gg6vh/jupyter_runtime/nbserver-34463-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=fb027382ccd2ed0fe44c65c613155c7c4bb95446cfda3946
[I 14:17:47.950 JestApp] > node /Users/XXXXXX/Work/jupyterlab/tests/test-application/node_modules/jest/bin/jest.js --runInBand
● Validation Error:

  Module @jupyterlab/testutils/lib/jest-script.js in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/XXXXXX/Work/jupyterlab

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

npm ERR! Test failed.  See above for more details.
```

**Comment by jtpio** [comment]
@ieglonew01f does this happen after going through the [dev install](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#installing-jupyterlab) and [building the tests](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#build-and-run-the-tests)?

**Comment by ieglonew01f** [comment]
Looks like that was a different issue, now I'm getting the following errors while running tests after build

```
@jupyterlab/test-application: Ran all test suites.
@jupyterlab/test-apputils: $ python run.py
@jupyterlab/test-apputils: [I 16:29:03.402 JestApp] Writing notebook server cookie secret to /var/folders/67/5kx_0t217_x84fls1w68h494rwpbn8/T/tmpm9izli35/jupyter_runtime/notebook_cookie_secret
@jupyterlab/test-apputils: [I 16:29:03.426 JestApp] The port 8888 is already in use, trying another port.
@jupyterlab/test-apputils: [I 16:29:03.433 JestApp] Serving notebooks from local directory: /var/folders/67/5kx_0t217_x84fls1w68h494rwpbn8/T/mock_contents5dr8qhph
@jupyterlab/test-apputils: [I 16:29:03.433 JestApp] The Jupyter Notebook is running at:
@jupyterlab/test-apputils: [I 16:29:03.433 JestApp] http://localhost:8889/?token=26faf0e4f1ddb98e5f1b64289d45fdcca736b6064bb51685
@jupyterlab/test-apputils: [I 16:29:03.433 JestApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
@jupyterlab/test-apputils: [C 16:29:03.436 JestApp]
@jupyterlab/test-apputils:
@jupyterlab/test-apputils:     To access the notebook, open this file in a browser:
@jupyterlab/test-apputils:         file:///var/folders/67/5kx_0t217_x84fls1w68h494rwpbn8/T/tmpm9izli35/jupyter_runtime/nbserver-17068-open.html
@jupyterlab/test-apputils:     Or copy and paste one of these URLs:
@jupyterlab/test-apputils:         http://localhost:8889/?token=26faf0e4f1ddb98e5f1b64289d45fdcca736b6064bb51685
@jupyterlab/test-apputils: [I 16:29:03.437 JestApp] > node /Users/mukundag/Work/jupyterlab/node_modules/jest/bin/jest.js --runInBand
@jupyterlab/test-apputils: jest-haste-map: Haste module naming collision: @jupyterlab/application-top
@jupyterlab/test-apputils:   The following files share their name; please adjust your hasteImpl:
@jupyterlab/test-apputils:     * <rootDir>/dev_mode/package.json
@jupyterlab/test-apputils:     * <rootDir>/jupyterlab/staging/package.json
@jupyterlab/test-apputils: FAIL src/toolbar.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       4 | import { expect } from 'chai';
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:     > 6 | import {
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       7 |   ClientSession,
@jupyterlab/test-apputils:       8 |   Toolbar,
@jupyterlab/test-apputils:       9 |   ToolbarButton,
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/toolbar.spec.ts:6:1)
@jupyterlab/test-apputils: FAIL src/clientsession.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:        6 | import { SessionManager } from '@jupyterlab/services';
@jupyterlab/test-apputils:        7 |
@jupyterlab/test-apputils:     >  8 | import { ClientSession, Dialog, IClientSession } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:          | ^
@jupyterlab/test-apputils:        9 |
@jupyterlab/test-apputils:       10 | import { UUID } from '@phosphor/coreutils';
@jupyterlab/test-apputils:       11 |
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/clientsession.spec.ts:8:1)
@jupyterlab/test-apputils: FAIL src/dialog.spec.tsx
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       4 | // import { expect } from 'chai';
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:     > 6 | import { Dialog, showDialog } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       7 |
@jupyterlab/test-apputils:       8 | import { each } from '@phosphor/algorithm';
@jupyterlab/test-apputils:       9 |
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/dialog.spec.tsx:6:1)
@jupyterlab/test-apputils: FAIL src/widgettracker.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       4 | import { expect } from 'chai';
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:     > 6 | import { WidgetTracker } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       7 |
@jupyterlab/test-apputils:       8 | import { signalToPromise, testEmission } from '@jupyterlab/testutils';
@jupyterlab/test-apputils:       9 |
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/widgettracker.spec.ts:6:1)
@jupyterlab/test-apputils: FAIL src/inputdialog.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       2 | // Distributed under the terms of the Modified BSD License.
@jupyterlab/test-apputils:       3 |
@jupyterlab/test-apputils:     > 4 | import { InputDialog } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:       6 | import {
@jupyterlab/test-apputils:       7 |   acceptDialog,
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/inputdialog.spec.ts:4:1)
@jupyterlab/test-apputils: FAIL src/sanitizer.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       4 | import { expect } from 'chai';
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:     > 6 | import { defaultSanitizer } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       7 |
@jupyterlab/test-apputils:       8 | describe('defaultSanitizer', () => {
@jupyterlab/test-apputils:       9 |   describe('#sanitize()', () => {
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/sanitizer.spec.ts:6:1)
@jupyterlab/test-apputils: FAIL src/commandlinker.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       10 | import { simulate } from 'simulate-event';
@jupyterlab/test-apputils:       11 |
@jupyterlab/test-apputils:     > 12 | import { CommandLinker } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:          | ^
@jupyterlab/test-apputils:       13 |
@jupyterlab/test-apputils:       14 | describe('@jupyterlab/apputils', () => {
@jupyterlab/test-apputils:       15 |   describe('CommandLinker', () => {
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/commandlinker.spec.ts:12:1)
@jupyterlab/test-apputils: FAIL src/vdom.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       4 | import { expect } from 'chai';
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:     > 6 | import { VDomModel, VDomRenderer } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       7 |
@jupyterlab/test-apputils:       8 | import { framePromise } from '@jupyterlab/testutils';
@jupyterlab/test-apputils:       9 |
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/vdom.spec.ts:6:1)
@jupyterlab/test-apputils: FAIL src/mainareawidget.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       4 | import { expect } from 'chai';
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:     > 6 | import { MainAreaWidget, Toolbar } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       7 |
@jupyterlab/test-apputils:       8 | import { MessageLoop } from '@phosphor/messaging';
@jupyterlab/test-apputils:       9 |
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/mainareawidget.spec.ts:6:1)
@jupyterlab/test-apputils: FAIL src/iframe.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:       4 | import { expect } from 'chai';
@jupyterlab/test-apputils:       5 |
@jupyterlab/test-apputils:     > 6 | import { IFrame } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:         | ^
@jupyterlab/test-apputils:       7 |
@jupyterlab/test-apputils:       8 | describe('@jupyterlab/apputils', () => {
@jupyterlab/test-apputils:       9 |   describe('IFrame', () => {
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/iframe.spec.ts:6:1)
@jupyterlab/test-apputils: FAIL src/styling.spec.ts
@jupyterlab/test-apputils:   ● Test suite failed to run
@jupyterlab/test-apputils:     Jest encountered an unexpected token
@jupyterlab/test-apputils:     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
@jupyterlab/test-apputils:     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
@jupyterlab/test-apputils:     Here's what you can do:
@jupyterlab/test-apputils:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
@jupyterlab/test-apputils:      • If you need a custom transformation specify a "transform" option in your config.
@jupyterlab/test-apputils:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
@jupyterlab/test-apputils:     You'll find more details and examples of these config options in the docs:
@jupyterlab/test-apputils:     https://jestjs.io/docs/en/configuration.html
@jupyterlab/test-apputils:     Details:
@jupyterlab/test-apputils:     /Users/mukundag/Work/jupyterlab/tests/node_modules/@jupyterlab/apputils/lib/index.js:3
@jupyterlab/test-apputils:     export * from './clientsession';
@jupyterlab/test-apputils:     ^^^^^^
@jupyterlab/test-apputils:     SyntaxError: Unexpected token export
@jupyterlab/test-apputils:        8 | import { simulate } from 'simulate-event';
@jupyterlab/test-apputils:        9 |
@jupyterlab/test-apputils:     > 10 | import { Styling } from '@jupyterlab/apputils';
@jupyterlab/test-apputils:          | ^
@jupyterlab/test-apputils:       11 |
@jupyterlab/test-apputils:       12 | describe('@jupyterlab/apputils', () => {
@jupyterlab/test-apputils:       13 |   describe('Styling', () => {
@jupyterlab/test-apputils:       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
@jupyterlab/test-apputils:       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
@jupyterlab/test-apputils:       at Object.<anonymous> (tests/test-apputils/src/styling.spec.ts:10:1)
@jupyterlab/test-apputils: Test Suites: 11 failed, 11 total
@jupyterlab/test-apputils: Tests:       0 total
@jupyterlab/test-apputils: Snapshots:   0 total
@jupyterlab/test-apputils: Time:        4.974s
@jupyterlab/test-apputils: Ran all test suites.
@jupyterlab/test-apputils: error Command failed with exit code 1.
@jupyterlab/test-apputils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in '@jupyterlab/test-apputils'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ieglonew01f** [comment]
Also, tests work fine if I run it from an individual test folder.

**Comment by ieglonew01f** [comment]
Never mind looks like it was an issue with my env
