### ISSUE TITLE
Can't install any extensions anymore. ValueError: "@oriolmirosa/jupyterlab_materialdarker" is not a valid npm package

### ISSUE THREAD

**Issue by theChosenUndead28** [jupyterlab/jupyterlab#6845]
Recently, I updated Jupyterlab to the latest version 1.0.2. With that update, the cursor wasn't visible whenever the material darker theme extension was applied ([https://github.com/oriolmirosa/jupyterlab_materialdarker](url)). After many tries to get the cursor back, I decided to reinstall anaconda and see if that works. Sadly, after reinstalling I started to get the  "System can not find the path specified" message on top of the anaconda prompt(even after editing the PATH environment variable). After installing node and npm(the latest stable version) and trying to install the extension, I started getting "ValueError: "@oriolmirosa/jupyterlab_materialdarker" is not a valid npm package" error.

Here is the error log after appending "--debug" in the command line(I tried with Node v8 to see if an earlier version worked):
Input:
`jupyter labextension install @oriolmirosa/jupyterlab_materialdarker --debug`
Output:
```
Searching ['C:\\Users\\K. ABHIROOP TEJOMAY\\Desktop\\jupyterlab_materialdarker', 'C:\\Users\\K. ABHIROOP TEJOMAY\\.jupyter', 'c:\\users\\k. abhiroop tejomay\\anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
Looking for jupyter_config in C:\ProgramData\jupyter
Looking for jupyter_config in c:\users\k. abhiroop tejomay\anaconda3\etc\jupyter
Looking for jupyter_config in C:\Users\K. ABHIROOP TEJOMAY\.jupyter
Looking for jupyter_config in C:\Users\K. ABHIROOP TEJOMAY\Desktop\jupyterlab_materialdarker
Node v8.16.0
 "C:\Program Files (x86)\nodejs\npm.CMD" pack @oriolmirosa/jupyterlab_materialdarker
\The system cannot find the path specified.
The system cannot find the path specified.
npm notice
npm notice package: @oriolmirosa/jupyterlab_materialdarker@0.4.0
npm notice === Tarball Contents ===
npm notice 387B    style/embed.css
npm notice 591B    style/fonts.css
npm notice 855B    style/index.css
npm notice 5.8kB   style/urls.css
npm notice 12.8kB  style/variables.css
npm notice 660B    lib/index.js
npm notice 1.4kB   package.json
npm notice 546B    README.md
npm notice 210B    style/images/caretdown.png
npm notice 210B    style/images/caretleft.png
npm notice 217B    style/images/caretright.png
npm notice 214B    style/images/caretup.png
npm notice 282B    style/icons/md/baseline-web-24px.svg
npm notice 538B    style/icons/md/bug.svg
npm notice 517B    style/icons/md/caretdown.svg
npm notice 554B    style/icons/md/caretleft.svg
npm notice 522B    style/icons/md/caretright.svg
npm notice 522B    style/icons/md/caretup.svg
npm notice 538B    style/icons/md/checkmark-disabled.svg
npm notice 539B    style/icons/md/checkmark.svg
npm notice 506B    style/icons/md/circle-inverse.svg
npm notice 257B    style/icons/md/circle.svg
npm notice 653B    style/icons/md/close-circle-inverse.svg
npm notice 597B    style/icons/md/close-circle.svg
npm notice 590B    style/icons/md/close-inverse.svg
npm notice 266B    style/icons/md/close.svg
npm notice 462B    style/icons/jupyter/console_selected.svg
npm notice 4.2kB   style/icons/jupyter/console.svg
npm notice 447B    style/icons/md/copy.svg
npm notice 4.0kB   style/icons/jupyter/csv_selected.svg
npm notice 4.1kB   style/icons/jupyter/csv.svg
npm notice 717B    style/icons/md/cut.svg
npm notice 298B    style/icons/md/down_caret.svg
npm notice 559B    style/icons/md/download.svg
npm notice 644B    style/icons/md/edit.svg
npm notice 320B    style/icons/md/ellipses.svg
npm notice 4.2kB   style/icons/jupyter/file_selected.svg
npm notice 4.2kB   style/icons/jupyter/file.svg
npm notice 151B    style/icons/md/ic_add_24px.svg
npm notice 284B    style/icons/md/ic_build_24px.svg
npm notice 250B    style/icons/md/ic_create_new_folder_24px.svg
npm notice 408B    style/icons/md/ic_extension_24px.svg
npm notice 153B    style/icons/md/ic_file_upload_24px.svg
npm notice 162B    style/icons/md/ic_filter_list_24px.svg
npm notice 207B    style/icons/md/ic_folder_24px_selected.svg
npm notice 207B    style/icons/md/ic_folder_24px.svg
npm notice 192B    style/icons/md/ic_format_align_left_24px_selected.svg
npm notice 192B    style/icons/md/ic_format_align_left_24px.svg
npm notice 151B    style/icons/md/ic_home_24px.svg
npm notice 356B    style/icons/md/ic_keyboard_24px_selected.svg
npm notice 356B    style/icons/md/ic_keyboard_24px.svg
npm notice 246B    style/icons/md/ic_launch_24px_selected.svg
npm notice 246B    style/icons/md/ic_launch_24px.svg
npm notice 309B    style/icons/md/ic_memory_24px_selected.svg
npm notice 309B    style/icons/md/ic_memory_24px.svg
npm notice 568B    style/icons/md/ic_palette_24px.svg
npm notice 323B    style/icons/md/ic_refresh_18px.svg
npm notice 788B    style/icons/md/ic_settings_24px_selected.svg
npm notice 788B    style/icons/md/ic_settings_24px.svg
npm notice 212B    style/icons/md/ic_tab_24px.svg
npm notice 4.1kB   style/icons/jupyter/image_selected.svg
npm notice 4.2kB   style/icons/jupyter/image.svg
npm notice 4.7kB   style/icons/jupyter/json_selected.svg
npm notice 4.9kB   style/icons/jupyter/json.svg
npm notice 2.4kB   style/images/jupyter-favicon.svg
npm notice 4.1kB   style/images/jupyter-white-moons.svg
npm notice 4.1kB   style/icons/jupyter/jupyter.svg
npm notice 4.1kB   style/images/jupyter.svg
npm notice 5.8kB   style/images/jupyterlab-wordmark-inverse.svg
npm notice 5.4kB   style/images/jupyterlab-wordmark.svg
npm notice 16.9kB  style/images/jupyterlab.svg
npm notice 375B    style/icons/md/link.svg
npm notice 4.2kB   style/icons/jupyter/markdown_selected.svg
npm notice 4.2kB   style/icons/jupyter/markdown.svg
npm notice 342B    style/icons/md/more-horiz.svg
npm notice 4.3kB   style/icons/jupyter/notebook_selected.svg
npm notice 4.3kB   style/icons/jupyter/notebook.svg
npm notice 289B    style/icons/md/panorama_fish_eye.svg
npm notice 365B    style/icons/md/paste.svg
npm notice 4.7kB   style/icons/jupyter/python_selected.svg
npm notice 4.7kB   style/icons/jupyter/python.svg
npm notice 4.2kB   style/icons/jupyter/r_selected.svg
npm notice 4.2kB   style/icons/jupyter/r.svg
npm notice 178B    style/icons/md/run.svg
npm notice 307B    style/icons/md/save.svg
npm notice 550B    style/icons/jupyter/search_arrow_down.svg
npm notice 547B    style/icons/jupyter/search_arrow_up.svg
npm notice 1.4kB   style/icons/jupyter/search_case_sensitive.svg
npm notice 846B    style/icons/jupyter/search_regex.svg
npm notice 503B    style/icons/md/search.svg
npm notice 440B    style/icons/md/stop-circle.svg
npm notice 178B    style/icons/md/stop.svg
npm notice 809B    style/icons/jupyter/terminal.svg
npm notice 4.6kB   style/icons/jupyter/texteditor.svg
npm notice 614B    style/icons/md/undo.svg
npm notice 4.6kB   style/icons/jupyter/vega_selected.svg
npm notice 4.6kB   style/icons/jupyter/vega.svg
npm notice 4.1kB   style/icons/jupyter/yml_selected.svg
npm notice 4.1kB   style/icons/jupyter/yml.svg
npm notice 203B    lib/index.d.ts
npm notice 120.5kB style/fonts/SourceCodePro-Bold.ttf
npm notice 120.5kB style/fonts/SourceCodePro-Regular.ttf
npm notice === Tarball Details ===
npm notice name:          @oriolmirosa/jupyterlab_materialdarker
npm notice version:       0.4.0
npm notice filename:      oriolmirosa-jupyterlab_materialdarker-0.4.0.tgz
npm notice package size:  146.0 kB
npm notice unpacked size: 428.2 kB
npm notice shasum:        83265165d27d9e68c7497be6899acd8f647effa1
npm notice integrity:     sha512-tbMZ9lGNn5t39[...]2ewe/1JrnUjOA==
npm notice total files:   102
npm notice
oriolmirosa-jupyterlab_materialdarker-0.4.0.tgz

Traceback (most recent call last):

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\commands.py", line 1373, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "c:\users\k. abhiroop tejomay\anaconda3\lib\site-packages\jupyterlab\commands.py", line 1444, in _extract_package
    raise ValueError(msg % source)

ValueError: "@oriolmirosa/jupyterlab_materialdarker" is not a valid npm package

An error occured.
ValueError: "@oriolmirosa/jupyterlab_materialdarker" is not a valid npm package
See the log file for details:  C:\Users\KC214~1.ABH\AppData\Local\Temp\jupyterlab-debug-qc2nw2ks.log
Exiting application: jupyter
```

This applies to every other extension that I tried to install.  After reinstalling Anaconda, I cannot install any extensions.  I have tried all the solutions to other similar issues on github but to no avail.

Similar issues:
@https://github.com/jupyter-widgets/ipywidgets/issues/1982
@https://github.com/jupyterlab/jupyterlab-git/issues/306

**Comment by monash89** [comment]
Same issue running these:

```
jupyter labextension install @jupyterlab/inspector
jupyter labextension install @lckr/jupyterlab_variableinspector
jupyter labextension install @jupyterlab_variableinspector
```

**Comment by monash89** [comment]
Found the solution:
GO to the registry entry below:
`HKCU\Software\Microsoft\Command Processor\AutoRun`
Edit the entry to "anaconda3":
"C:\Users\Monash\**Anaconda3**\condabin\conda_hook.bat"
Make sure that you have already added these addresses to the system path:
```
C:\Users\Monash\Anaconda3\Scripts
C:\Users\Monash\Anaconda3
C:\Program Files (x86)\nodejs
C:\Users\Monash\Anaconda3\Library\bin
```

**Comment by komjum6** [comment]
Thank you, namakshenas, I've struggled with this for a long time. Your answer was highly appreciated!

**Comment by jasongrout** [comment]
Thanks for sharing your solution!
