### ISSUE TITLE
jlpm add:sibling with third-party dependencies

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#6911]
Running the `add:sibling` command with an extension that depends on packages that are not available from the existing dependency graph seems to be giving some errors.

Testing with [jupyterlab-kernelspy](https://github.com/vidartf/jupyterlab-kernelspy) which depends on `react-inspector`:

```
(node:10120) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-inspector/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.resolve (internal/modules/cjs/helpers.js:19:19)
    at requirePackage (/home/jtp/dev/jupyterlab/buildutils/lib/utils.js:264:33)
    at Object.keys.forEach.depName (/home/jtp/dev/jupyterlab/buildutils/lib/utils.js:237:31)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach.name (/home/jtp/dev/jupyterlab/buildutils/lib/utils.js:228:27)
    at Array.forEach (<anonymous>)
    at Object.getPackageGraph (/home/jtp/dev/jupyterlab/buildutils/lib/utils.js:224:25)
    at ensureIntegrity (/home/jtp/dev/jupyterlab/buildutils/lib/ensure-repo.js:226:25)
    at Object.<anonymous> (/home/jtp/dev/jupyterlab/buildutils/lib/ensure-repo.js:341:10)
(node:10120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It looks like these packages should be fetched from npm to be able to parse their `package.json`.

**Comment by jtpio** [comment]
Command: `jlpm run add:sibling https://github.com/vidartf/jupyterlab-kernelspy.git`
