### ISSUE TITLE
`jupyter lab build` fails with "EINVAL: invalid argument, copyfile..." (v1.0.4)

### ISSUE THREAD

**Issue by st-bender** [jupyterlab/jupyterlab#6969]
Hi!

**Describe the bug**
`jupyter lab build` fails with:

    RuntimeError: npm dependencies failed to install

which is presumably caused by an earlier error by `yarn`:

    [3/5] Fetching packages...
    error An unexpected error occurred: "EINVAL: invalid argument, copyfile '/cluster/home/user/.cache/yarn/v4/.tmp/81cdb36f698f9dd1628f8acac1df1f7c/.yarn-metadata.json' -> '/cluster/home/user/.cache/yarn/v4/npm-jupyterlab-vim-0.11.0-e9339dde205c631a168b2291856257d7ed7dd54b/node_modules/jupyterlab_vim/.yarn-metadata.json'".
    info If you think this is a bug, please open a bug report with the information provided in "/cluster/home/stefaben/nobackup/miniconda3/envs/stats37/share/jupyter/lab/staging/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

`ls` or shows that the file exists, but the directory to which it should be copied does not. It happens with other extensions too.

**To Reproduce**

1. update jupyter with `conda update -c conda-forge --all`
2. update jupyterlab extensions by `jupyter labextension update --all`
3. follow the recommendation to run `jupyter lab build`

**Expected behavior**
jupyterlab builds without errors.

**Desktop (please complete the following information):**

- OS: Linux
- JupyterLab v1.0.4

**Additional context**
Maybe related to the nfs issues?

Cheers.

**Comment by st-bender** [comment]
PS: It even fails without extensions, then the `yarn` error is:

    [4/5] Linking dependencies...
    error An unexpected error occurred: "EINVAL: invalid argument, copyfile '/cluster/home/user/.cache/yarn/v4/npm-@blueprintjs-icons-3.9.1-064d43314313f0feb4b1dd7e0904ddc17c8652d1/node_modules/@blueprintjs/icons/package.json' -> '/cluster/home/user/nobackup/miniconda3/envs/stats37/share/jupyter/lab/staging/node_modules/@blueprintjs/icons/package.json'".
    info If you think this is a bug, please open a bug report with the information provided in "/cluster/home/user/nobackup/miniconda3/envs/stats37/share/jupyter/lab/staging/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by st-bender** [comment]
No one seems to care?
I had no problems with jupyterlab < 1.0.0, any pointers would be appreciated.

**Comment by vidartf** [comment]
> Maybe related to the nfs issues?

Which NFS issues? Cross references are always a good thing.

> Still failing with 1.0.9, no one seems to care?

It is very hard to troubleshoot an issue if only one person are able to reproduce it. Do you have the opportunity to try this on another system? The `'/cluster/...` paths seems to indicate to me that you have a somewhat non-traditional setup going on 😃  Have you tried with a fresh conda install / env? Your npm/node versions might be worth sharing as well.

**Comment by st-bender** [comment]
> > Maybe related to the nfs issues?
> 
> Which NFS issues? Cross references are always a good thing.

Thanks for taking on, I was thinking about #4738 and maybe yarnpkg/yarn#1961 or yarnpkg/yarn#4188.

> > Still failing with 1.0.9, no one seems to care?
> 
> It is very hard to troubleshoot an issue if only one person are able to reproduce it. Do you have the opportunity to try this on another system? The `'/cluster/...` paths seems to indicate to me that you have a somewhat non-traditional setup going on  Have you tried with a fresh conda install / env? Your npm/node versions might be worth sharing as well.

Which is quite disturbing that I am the only one.
I don't know what you mean with "non-traditional", just for testing I used a fresh `conda` environment set up with the commands from #4738 and `jupyter lab build` still fails:

    [LabBuildApp] Building in /usit/abel/u1/user/nobackup/miniconda3/envs/jlab/share/jupyter/lab
    [LabBuildApp] Node v12.8.1

    [LabBuildApp] Building jupyterlab assets
    [LabBuildApp] > node /usit/abel/u1/user/nobackup/miniconda3/envs/jlab/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
    /[LabBuildApp] yarn install v1.15.2
    [1/5] Validating package.json...
    [2/5] Resolving packages...
    [3/5] Fetching packages...
    info fsevents@1.2.9: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
    [4/5] Linking dependencies...
    error An unexpected error occurred: "EINVAL: invalid argument, copyfile '/usit/abel/u1/user/.cache/yarn/v4/npm-@blueprintjs-core-3.18.0-8835ead10460e6535076465865d2ad7600ae1a07/node_modules/@blueprintjs/core/LICENSE' -> '/cluster/home/user/nobackup/miniconda3/envs/jlab/share/jupyter/lab/staging/node_modules/@blueprintjs/core/LICENSE'".
    info If you think this is a bug, please open a bug report with the information provided in "/cluster/home/user/nobackup/miniconda3/envs/jlab/share/jupyter/lab/staging/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    [LabBuildApp] npm dependencies failed to install
    [LabBuildApp] Traceback (most recent call last):

    [LabBuildApp]   File "/usit/abel/u1/user/nobackup/miniconda3/envs/jlab/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

    [LabBuildApp]   File "/usit/abel/u1/user/nobackup/miniconda3/envs/jlab/lib/python3.7/site-packages/jupyterlab/labapp.py", line 80, in start
    command=command, logger=self.log)

    [LabBuildApp]   File "/usit/abel/u1/user/nobackup/miniconda3/envs/jlab/lib/python3.7/site-packages/jupyterlab/commands.py", line 373, in build
    command=command, clean_staging=clean_staging)

    [LabBuildApp]   File "/usit/abel/u1/user/nobackup/miniconda3/envs/jlab/lib/python3.7/site-packages/jupyterlab/commands.py", line 557, in build
    raise RuntimeError(msg)

    [LabBuildApp] RuntimeError: npm dependencies failed to install

    [LabBuildApp] Exiting application: JupyterLab

Note that when running `jupyter lab build` a second time, it fails when copying `README.md` instead of `LICENSE`, occasionally it fails on a file from a different package. This erratic behaviour may give hopefully some clue.

As you may have guessed it is on a cluster, SLURM to be precise, and the `/home` directories seem to be on beegfs. Not much I can do about that, but jupyterlab < 1.0 had no problems and downgrading makes it work again.

The versions you asked for:
node: v12.8.1
npm: 6.10.2

**Comment by vidartf** [comment]
> As you may have guessed it is on a cluster, SLURM to be precise, and the /home directories seem to be on beegfs. 

I'm going to bet that this is an import factor here. Some things to try:
- Try to find someone with experience with the cluster setups and ask if there is anything that could trigger these errors.
- Try with some other yarn installations. If this is an issue between yarn and the file system setup, this issue should probably be taken upstream (yarn or FS communities).
- If Jupyterlab is the only yarn project for which this happens, a good starting point would be to determine exactly what Jupyterlab does that other projects does not do. We can probably help a little bit here, but since none of us have access to a system like yours (I think), it would be hard for us to troubleshoot this.

**Comment by st-bender** [comment]
Thanks again for your support.

> > As you may have guessed it is on a cluster, SLURM to be precise, and the /home directories seem to be on beegfs.
> 
> I'm going to bet that this is an import factor here. Some things to try:

Maybe, but IMO file system operations such as `copyfile` should be left to the system and not be done by anything else.

> * Try to find someone with experience with the cluster setups and ask if there is anything that could trigger these errors.

That's why I submitted this report, in the hope that someone else with more experience has an idea. ;)

> * Try with some other yarn installations. If this is an issue between yarn and the file system setup, this issue should probably be taken upstream (yarn or FS communities).

I would like to try, how would I do that? As I understood, jupyterlab bundles its own version of yarn. Btw. I copied the `yarn.js` v1.9.4 from jupyterlab version 0.34.12 to the staging directory of 1.0.9 and `jupyter lab build` runs through. How can I test other `yarn` versions to find the first bad one?

> * If Jupyterlab is the only yarn project for which this happens, a good starting point would be to determine exactly what Jupyterlab does that other projects does not do. We can probably help a little bit here, but since none of us have access to a system like yours (I think), it would be hard for us to troubleshoot this.

If we could figure out which version of yarn, or jupyter's yarn, broke it, that would be a good start.

**Comment by vidartf** [comment]
> If we could figure out which version of yarn, or jupyter's yarn, broke it, that would be a good start.

I agree, but unfortunately, it will have to be you who does this legwork, as we do not have access to a system to try this on. 🤷‍♂

**Comment by st-bender** [comment]
> > If we could figure out which version of yarn, or jupyter's yarn, broke it, that would be a good start.
> 
> I agree, but unfortunately, it will have to be you who does this legwork, as we do not have access to a system to try this on.

I can try, where do I start, and how can I test other yarn versions?

**Comment by neighthan** [comment]
I'm having a similar issue. I tried to install an extension using `jupyter labextension install @jupyter-widgets/jupyterlab-manager` (I also tried the pyviz extension), and I get the same `EINVAL: invalid argument, copyfile` message in the error log. This was with JupyterLab version 1.1.1 on Ubuntu 16.04 on an NFS-formatted drive. Downgrading to yarn version 1.9.4 does seem to be a valid workaround for me (I haven't tried other version to determine if this is the most recent one that works on my system). I did this by running:

```bash
yarn_dir=$HOME/anaconda/lib/python3.7/site-packages/jupyterlab/staging
wget -O yarn.js https://github.com/yarnpkg/yarn/releases/download/v1.9.4/yarn-1.9.4.js
mv $yarn_dir/yarn.js $yarn_dir/yarn.js.bk # save this in case you want to revert
mv yarn.js $yarn_dir
```

The install now finishes without errors, and I see the extensions when I run `jupyter labextension list` (though I've yet to test in a notebook).

**Comment by st-bender** [comment]
@neighthan I found the same. Another solution is to edit `yarn.js` as follows (see the yarn issues linked above and yarnpkg/yarn#6302):
Look for a line that sets `ficloneFlag` to some value and change that to

    const ficloneFlag = 0;

Unfortunately neither the jupyterlab nor the yarn people seem to be particularly interested in fixing that "supposedly minor" bug.

**Comment by jasongrout** [comment]
The issue around using COPYFILE_FICLONE (see the yarn issue) may actually be a bug in Node? From a small dive into the issues you've linked (thanks!), it's supposed to fall back to a non-clone copy if a cloning copy doesn't work. That constant value is coming from node.

There are other reasons why we've upgraded yarn past 1.9. Good news is that yarn 2.0 (https://github.com/yarnpkg/berry) doesn't seem to reference the flag, which hopefully will be out soon and we'll upgrade.

**Comment by jasongrout** [comment]
I wouldn't be opposed to patching the yarn binary in the meantime. The fix seems very localized.

I'm curious if upgrading node to the latest version fixes the issue, since it appears to be a node bug.

**Comment by jasongrout** [comment]
> I'm curious if upgrading node to the latest version fixes the issue, since it appears to be a node bug.

And node apparently gets the constant from libuv: https://github.com/nodejs/node/blob/master/src/node_constants.cc#L1252-L1257

So I wonder if upgrading libuv (if it is dynamically linked) fixes the issue?

**Comment by st-bender** [comment]
Hi @jasongrout,
Thanks for taking it on! :)

I figured that it would have to do something with platform/filesystem support and `yarn` resp. `libuv` and their communication of supported features.
I found the following lines in `libuv/src/fs.c`:
https://github.com/libuv/libuv/blob/master/src/unix/fs.c#L1055-L1078
They were introduced in libuv/libuv#1491 and updated in libuv/libuv#1863.
The problem is that in my case `ioctl()` fails with `EINVAL` which is not caught and returned to the caller. Adding `EINVAL` to the "good" errors in
https://github.com/libuv/libuv/blob/master/src/unix/fs.c#L1062 fixes libuv for me (i.e. libuv's `make check` passes that test).
I'll try to check if that helps with yarn and file a report to libuv.

Cheers.

**Comment by jasongrout** [comment]
Wow, thanks for diving that deep! Perhaps a patch to libuv is forthcoming.

**Comment by st-bender** [comment]
> Wow, thanks for diving that deep! Perhaps a patch to libuv is forthcoming.

It took a while, but the libuv issue should be fixed with the latest release (v1.33.0). This issue can probably be closed now, but I'd like to double check when the update lands in the conda repository.

**Comment by jasongrout** [comment]
Great, thanks for following up here.

**Comment by st-bender** [comment]
Hi,
Finally the new version of `libuv` made it into conda-forge, and the update to v1.33.1 solved the issue for me. So I think this issue can be closed now.

**Comment by vidartf** [comment]
Yes, thanks for hunting this, and thanks for reporting back 👍
