### ISSUE TITLE
Failure to build OPTIONAL package causes jupypyterlab build fails?

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#6974]
Hi all,
I am using v1.0.4 to build `nglview` extension for jupyterlab. This is the first time I saw the failure (below log). Any idea why and how to avoid that? thanks

 ```
gyp ERR! cwd /Users/haichit/miniconda3/share/jupyter/lab/staging/node_modules/canvas
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
Done in 5.29s.

> node /Users/haichit/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build

JupyterLab failed to build
Traceback (most recent call last):

  File "/Users/haichit/miniconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/haichit/miniconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 86, in start
    logger=self.log, command=command)

  File "/Users/haichit/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 373, in build
    command=command, clean_staging=clean_staging)

  File "/Users/haichit/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 566, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

The full log is here: 
[lab_error.log](https://github.com/jupyterlab/jupyterlab/files/3484879/lab_error.log)

**Comment by vidartf** [comment]
It might also be that this is what is causing the failure? Node-gyp has always been confusing to me 😕 

```
> node /Users/haichit/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.15.2
$ /Users/haichit/miniconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
```

**Comment by vidartf** [comment]
Hmm... Looking at the `yard-deduplicate` code, I think it was a mistake to add the `--fail` flag. That flag basically causes the command to fail if it corrected a duplication (not, as I thought, if there were duplicates left)...
