### ISSUE TITLE
Cannot install any JupyterLab ExtensionRuntimeError: JupyterLab failed to build

### ISSUE THREAD

**Issue by tgllsy** [jupyterlab/jupyterlab#7003]
I try to install a JupyterLab extension, but every my trial fails

```bash

$ jupyter lab build    
[LabBuildApp] JupyterLab 1.0.2
[LabBuildApp] Building in /opt/anaconda3/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-eofhuz8s.log
```

```bash
$ cat /tmp/jupyterlab-debug-eofhuz8s.log
[LabBuildApp] Building in /opt/anaconda3/share/jupyter/lab
[LabBuildApp] Node v10.13.0

[LabBuildApp] Building jupyterlab assets
[LabBuildApp] > /opt/anaconda3/bin/npm pack /root/jupyterlab-go-to-definition
[LabBuildApp] npm WARN lifecycle @krassowski/jupyterlab_go_to_definition@0.6.1~prepare: cannot run in wd @krassowski/jupyterlab_go_to_definition@0.6.1 npm run clean && npm run build (wd=/root/jupyterlab-go-to-definition)
npm notice 
npm notice 📦  @krassowski/jupyterlab_go_to_definition@0.6.1
npm notice === Tarball Contents === 
npm notice 1.9kB  package.json                              
npm notice 1.5kB  LICENSE                                   
npm notice 4.0kB  README.md                                 
npm notice 731B   lib/editors/codemirror/extension.d.ts     
npm notice 6.4kB  lib/editors/codemirror/extension.js       
npm notice 11B    lib/editors/codemirror/extension.spec.d.ts
npm notice 2.3kB  lib/editors/codemirror/extension.spec.js  
npm notice 104B   lib/editors/codemirror/index.d.ts         
npm notice 288B   lib/editors/codemirror/index.js           
npm notice 409B   lib/editors/codemirror/tokens.d.ts        
npm notice 446B   lib/editors/codemirror/tokens.js          
npm notice 478B   lib/editors/editor.d.ts                   
npm notice 77B    lib/editors/editor.js                     
npm notice 385B   lib/history.d.ts                          
npm notice 725B   lib/history.js                            
npm notice 228B   lib/index.d.ts                            
npm notice 7.8kB  lib/index.js                              
npm notice 709B   lib/jump.d.ts                             
npm notice 77B    lib/jump.js                               
npm notice 958B   lib/jumpers/fileeditor.d.ts               
npm notice 2.8kB  lib/jumpers/fileeditor.js                 
npm notice 2.1kB  lib/jumpers/jumper.d.ts                   
npm notice 10.7kB lib/jumpers/jumper.js                     
npm notice 1.1kB  lib/jumpers/notebook.d.ts                 
npm notice 5.4kB  lib/jumpers/notebook.js                   
npm notice 3.0kB  lib/languages/analyzer.d.ts               
npm notice 7.7kB  lib/languages/analyzer.js                 
npm notice 11B    lib/languages/analyzer.spec.d.ts          
npm notice 1.6kB  lib/languages/analyzer.spec.js            
npm notice 299B   lib/languages/chooser.d.ts                
npm notice 672B   lib/languages/chooser.js                  
npm notice 1.2kB  lib/languages/python.d.ts                 
npm notice 10.7kB lib/languages/python.js                   
npm notice 11B    lib/languages/python.spec.d.ts            
npm notice 13.5kB lib/languages/python.spec.js              
npm notice 584B   lib/languages/r.d.ts                      
npm notice 2.8kB  lib/languages/r.js                        
npm notice 11B    lib/languages/r.spec.d.ts                 
npm notice 3.9kB  lib/languages/r.spec.js                   
npm notice 551B   lib/notebook_private.d.ts                 
npm notice 2.1kB  lib/notebook_private.js                   
npm notice 764B   lib/testutils.d.ts                        
npm notice 1.2kB  lib/testutils.js                          
npm notice 291B   schema/plugin.json                        
npm notice 0      style/index.css                           
npm notice === Tarball Details === 
npm notice name:          @krassowski/jupyterlab_go_to_definition         
npm notice version:       0.6.1                                           
npm notice filename:      krassowski-jupyterlab_go_to_definition-0.6.1.tgz
npm notice package size:  24.6 kB                                         
npm notice unpacked size: 102.5 kB                                        
npm notice shasum:        b7f325d7a72e05362aaabf2d948c959643d82eb3        
npm notice integrity:     sha512-8wkwLaosVGei/[...]f/MGRvb9Ja1Hw==        
npm notice total files:   45                                              
npm notice 
krassowski-jupyterlab_go_to_definition-0.6.1.tgz

[LabBuildApp] > node /opt/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
warning Error running install script for optional dependency: "/opt/anaconda3/share/jupyter/lab/staging/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /opt/anaconda3/share/jupyter/lab/staging/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/anaconda3/bin/python -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack   File \"<string>\", line 1
gyp ERR! stack     import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command \"/opt/anaconda3/bin/node\" \"/opt/anaconda3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /opt/anaconda3/share/jupyter/lab/staging/node_modules/canvas
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
Done in 11.80s.

[LabBuildApp] > node /opt/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.15.2
$ /opt/anaconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 1.25s.

[LabBuildApp] > node /opt/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build
[LabBuildApp] yarn run v1.15.2
$ webpack
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 80, in start
    command=command, logger=self.log)

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 373, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 566, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```
Some hints about my environment:

Ubuntu 18.04.2

Python 3.7.3

 node 10.13.0

npm   6.4.1

**Comment by blink1073** [comment]
@jasongrout, do we need to add `ignore-optional` to this [file](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/.yarnrc) perhaps?

**Comment by blink1073** [comment]
We had it at one point: https://github.com/jupyterlab/jupyterlab/blob/b513457b01bb4f0330915e3e508454e44ea04a7b/.yarnrc

**Comment by blink1073** [comment]
cf #6974 

cf https://github.com/jupyterlab/jupyterlab/issues/3665 and the fix in https://github.com/yarnpkg/yarn/pull/5059

**Comment by vidartf** [comment]
It is not clear to me that the gyp warnings are relevant to this failure (the build continues after that step, and fails later). I see this warning often myself with no issues.

```
$ webpack
Killed
```
@tgllsy It says "killed" here, so I just thought I would double check: Are you killing the process manually? Or does it crash on its own?

**Comment by vidartf** [comment]
(note, it might still be nice to make the gyp warnings go away)

**Comment by blink1073** [comment]
It looks like a memory issue with Uglify:  https://stackoverflow.com/questions/30747314/webpack-uglify-plugin-returns-killed-on-ubuntu

**Comment by vidartf** [comment]
I think we switched from Uglify to terser before 1.0, and 1.0.2 defaults to a dev build. It might be a similar issue though (OOM).

**Comment by blink1073** [comment]
Right, different cause, same symptom.

Sent from Phone

________________________________

**Comment by tgllsy** [comment]
> 我不清楚gyp警告是否与此失败相关（构建在该步骤之后继续，并且稍后失败）。我经常看到这个警告，没有任何问题。
> 
> ```
> $ webpack
> Killed
> ```
> 
> @tgllsy它在这里说“杀死”，所以我只是想我会仔细检查：你是否手动杀死了这个过程？或者它自己崩溃了吗？



> 看起来像Uglify的内存问题：[https](https://stackoverflow.com/questions/30747314/webpack-uglify-plugin-returns-killed-on-ubuntu)：//stackoverflow.com/questions/30747314/webpack-uglify-plugin-returns-killed-on-ubuntu [](https://stackoverflow.com/questions/30747314/webpack-uglify-plugin-returns-killed-on-ubuntu)

Thanks for your comment, my memory space is 512 M, deployed on vultr, see the prompt you gave, I guess the memory is insufficient, I tried to increase the swap size, the result was successful.

```bash
# dd if=/dev/zero of=/swap bs=1024 count=1M 
# mkswap /swap 
# swapon /swap 
# echo "/swap swap swap sw 0 0" >> /etc/fstab
```

**Comment by vidartf** [comment]
@tgllsy Thanks for reporting back the details of resolving the issue. Closing as resolved then. If there is still something I missed, please comment and I will reopen the issue.
