### ISSUE TITLE
Install Jupyter Widgets JupyterLab Extension (@0.36 version) in a node without internet.

### ISSUE THREAD

**Issue by juandasgandaras** [jupyterlab/jupyterlab#7069]
## Problems to install Jupyter Widgets JupyterLab Extension in a node without internet.
Hi, I am trying to install a jupyterlab-manager package acording to the instructions from the link: 

- [packages jupyterlab-manager](https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager)

My problem is that I don´t have internet conection in this node. So I download the version that I need for  JupyterLab version that I have (JupyterLab 0.33.x).

Acording to the instructions in the link,

@jupyter-widgets/jupyterlab-manager@0.36

So I am trying to download the packages that need with git and after to do a npm install for this version fails:

```
git clone https://github.com/jupyter-widgets/ipywidgets.git (@0.36 version)
cd ipywidgets/packages/jupyterlab-manager
**npm install**

```
After I wanted to upload the node_modules folder to the node without internet conection and to do the command

```
npm rebuild
jupyter labextension link .

```
But the comand:

```
npm install

```
is failing.

The version of node.js that I have is:

node -v 
12.9.0   

The npm-degug.log that I have obtained is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/jdiazg/node-v4.2.6-linux-x64/bin/node',
1 verbose cli   '/home/jdiazg/node-v4.2.6-linux-x64/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose readDependencies loading dependencies from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/package.json
5 verbose install where, deps [ '/home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager',
5 verbose install   [ '@jupyter-widgets/base',
5 verbose install     '@jupyter-widgets/controls',
5 verbose install     '@jupyter-widgets/output',
5 verbose install     '@jupyterlab/application',
5 verbose install     '@jupyterlab/coreutils',
5 verbose install     '@jupyterlab/docregistry',
5 verbose install     '@jupyterlab/notebook',
5 verbose install     '@jupyterlab/outputarea',
5 verbose install     '@jupyterlab/rendermime',
5 verbose install     '@jupyterlab/rendermime-interfaces',
5 verbose install     '@jupyterlab/services',
5 verbose install     '@phosphor/disposable',
5 verbose install     '@phosphor/messaging',
5 verbose install     '@phosphor/widgets',
5 verbose install     '@types/backbone',
5 verbose install     'jquery',
5 verbose install     'semver',
5 verbose install     '@types/semver',
5 verbose install     'rimraf',
5 verbose install     'tslint',
5 verbose install     'typedoc',
5 verbose install     'typescript' ] ]
6 verbose install where, peers [ '/home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager',
6 verbose install   [] ]
7 verbose installManyTop reading for lifecycle /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/package.json
8 info preinstall @jupyter-widgets/jupyterlab-manager@0.36.0-0
9 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/jquery/package.json
10 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/rimraf/package.json
11 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/semver/package.json
12 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/tslint/package.json
13 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/typedoc/package.json
14 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/typescript/package.json
15 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyter-widgets/base/package.json
16 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyter-widgets/controls/package.json
17 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyter-widgets/output/package.json
18 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@types/backbone/package.json
19 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@types/semver/package.json
20 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@phosphor/disposable/package.json
21 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@phosphor/messaging/package.json
22 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@phosphor/widgets/package.json
23 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/application/package.json
24 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/coreutils/package.json
25 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/docregistry/package.json
26 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/notebook/package.json
27 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/outputarea/package.json
28 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/rendermime/package.json
29 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/rendermime-interfaces/package.json
30 verbose installManyTop reading scoped package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/services/package.json
31 verbose readDependencies loading dependencies from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/package.json
32 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/jquery/package.json
33 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/rimraf/package.json
34 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/semver/package.json
35 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/tslint/package.json
36 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/typedoc/package.json
37 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/typescript/package.json
38 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/application/package.json
39 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/coreutils/package.json
40 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/docregistry/package.json
41 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/notebook/package.json
42 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/outputarea/package.json
43 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/rendermime/package.json
44 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/rendermime-interfaces/package.json
45 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyterlab/services/package.json
46 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@phosphor/disposable/package.json
47 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@phosphor/messaging/package.json
48 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@phosphor/widgets/package.json
49 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyter-widgets/base/package.json
50 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyter-widgets/controls/package.json
51 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@jupyter-widgets/output/package.json
52 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/.bin/rimraf/package.json
53 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/.bin/semver/package.json
54 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/.bin/tsc/package.json
55 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/.bin/tslint/package.json
56 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/.bin/tsserver/package.json
57 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/.bin/typedoc/package.json
58 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@types/backbone/package.json
59 verbose targetResolver reading package data from /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager/node_modules/@types/semver/package.json
60 verbose already installed skipping @phosphor/messaging@^1.2.1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
61 verbose already installed skipping @phosphor/widgets@^1.3.0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
62 verbose already installed skipping @types/backbone@^1.3.33 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
63 verbose already installed skipping jquery@^3.1.1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
64 verbose already installed skipping semver@^5.1.0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
65 verbose already installed skipping @types/semver@^5.4.0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
66 verbose already installed skipping rimraf@^2.6.1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
67 verbose already installed skipping tslint@^5.8.0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
68 verbose already installed skipping typedoc@^0.6.0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
69 verbose already installed skipping typescript@~2.9.2 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
70 verbose already installed skipping @jupyter-widgets/base@^1.2.0-0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
71 verbose already installed skipping @jupyter-widgets/controls@^1.3.0-0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
72 verbose already installed skipping @jupyter-widgets/output@^1.1.0-0 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
73 verbose already installed skipping @jupyterlab/application@^0.17.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
74 verbose already installed skipping @jupyterlab/coreutils@^2.0.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
75 verbose already installed skipping @jupyterlab/docregistry@^0.17.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
76 verbose already installed skipping @jupyterlab/notebook@^0.17.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
77 verbose already installed skipping @jupyterlab/outputarea@^0.17.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
78 verbose already installed skipping @jupyterlab/rendermime@^0.17.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
79 verbose already installed skipping @jupyterlab/rendermime-interfaces@^1.1.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
80 verbose already installed skipping @jupyterlab/services@^3.0.0-1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
81 verbose already installed skipping @phosphor/disposable@^1.1.1 /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
82 silly install resolved []
83 info build /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
84 info linkStuff @jupyter-widgets/jupyterlab-manager@0.36.0-0
85 silly linkStuff @jupyter-widgets/jupyterlab-manager@0.36.0-0 has /home/jdiazg/git_test/proba_hoxe/ipywidgets as its parent node_modules
86 verbose linkBins @jupyter-widgets/jupyterlab-manager@0.36.0-0
87 verbose linkMans @jupyter-widgets/jupyterlab-manager@0.36.0-0
88 verbose rebuildBundles @jupyter-widgets/jupyterlab-manager@0.36.0-0
89 verbose rebuildBundles [ '.bin',
89 verbose rebuildBundles   '@jupyter-widgets',
89 verbose rebuildBundles   '@jupyterlab',
89 verbose rebuildBundles   '@phosphor',
89 verbose rebuildBundles   '@types',
89 verbose rebuildBundles   'jquery',
89 verbose rebuildBundles   'rimraf',
89 verbose rebuildBundles   'semver',
89 verbose rebuildBundles   'tslint',
89 verbose rebuildBundles   'typedoc',
89 verbose rebuildBundles   'typescript' ]
90 info install @jupyter-widgets/jupyterlab-manager@0.36.0-0
91 info postinstall @jupyter-widgets/jupyterlab-manager@0.36.0-0
92 info prepublish @jupyter-widgets/jupyterlab-manager@0.36.0-0
93 verbose unsafe-perm in lifecycle true
94 info @jupyter-widgets/jupyterlab-manager@0.36.0-0 Failed to exec prepublish script
95 verbose stack Error: @jupyter-widgets/jupyterlab-manager@0.36.0-0 prepublish: `npm run clean && npm run build`
95 verbose stack Exit status 1
95 verbose stack     at EventEmitter.<anonymous> (/home/jdiazg/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
95 verbose stack     at emitTwo (events.js:87:13)
95 verbose stack     at EventEmitter.emit (events.js:172:7)
95 verbose stack     at ChildProcess.<anonymous> (/home/jdiazg/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
95 verbose stack     at emitTwo (events.js:87:13)
95 verbose stack     at ChildProcess.emit (events.js:172:7)
95 verbose stack     at maybeClose (internal/child_process.js:821:16)
95 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
96 verbose pkgid @jupyter-widgets/jupyterlab-manager@0.36.0-0
97 verbose cwd /home/jdiazg/git_test/proba_hoxe/ipywidgets/packages/jupyterlab-manager
98 error Linux 2.6.32-220.23.1.el6.x86_64
99 error argv "/home/jdiazg/node-v4.2.6-linux-x64/bin/node" "/home/jdiazg/node-v4.2.6-linux-x64/bin/npm" "install"
100 error node v4.2.6
101 error npm  v2.14.12
102 error code ELIFECYCLE
103 error @jupyter-widgets/jupyterlab-manager@0.36.0-0 prepublish: `npm run clean && npm run build`
103 error Exit status 1
104 error Failed at the @jupyter-widgets/jupyterlab-manager@0.36.0-0 prepublish script 'npm run clean && npm run build'.
104 error This is most likely a problem with the @jupyter-widgets/jupyterlab-manager package,
104 error not with npm itself.
104 error Tell the author that this fails on your system:
104 error     npm run clean && npm run build
104 error You can get their info via:
104 error     npm owner ls @jupyter-widgets/jupyterlab-manager
104 error There is likely additional logging output above.
105 verbose exit [ 1, true ]

```

Could please somebody how to install  @jupyter-widgets/jupyterlab-manager@0.36 in a node without internet or how to compile it?

Thanks

**Comment by jasongrout** [comment]
Unfortunately, it is not very straightforward to do this now because it will pull in a number of dependencies when it builds. One thing you can do is build on a computer with internet, then copy the appropriate staging directory to the computer without internet. Or you can install an npm proxy on a computer with internet, install and build to pull in the appropriate npm packages, then copy those packages to the computer without internet to install there (you'd probably have to use something like verdaccio there to provide a local npm package). Another way I suppose you could do it is copying a yarn cache with the appropriate packages to the computer without internet.
