### ISSUE TITLE
ValueError: "jupyter-widgets/jupyterlab-manager" is not a valid npm package

### ISSUE THREAD

**Issue by rejscotia** [jupyterlab/jupyterlab#7076]
Not obvious to me what's wrong. Installed the most recent Anaconda3, installed jupyterlab, node js...  attached is the debug log.

Conda version:
conda 4.7.11

Jupyter version info:
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : 4.5.1
ipython          : 7.7.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : 1.0.6
nbconvert        : 5.6.0
ipywidgets       : 7.5.0
nbformat         : 4.4.0
traitlets        : 4.3.2

**Console:**

(base) C:\Users\S7791242>jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug
Searching ['C:\\Users\\S7791242', 'C:\\Users\\S7791242\\.jupyter', 'C:\\Users\\S7791242\\AppData\\Local\\Continuum\\anaconda3\\etc\\jupyter'
, 'C:\\ProgramData\\jupyter'] for config files
Looking for jupyter_config in C:\ProgramData\jupyter
Looking for jupyter_config in C:\Users\S7791242\AppData\Local\Continuum\anaconda3\etc\jupyter
Looking for jupyter_config in C:\Users\S7791242\.jupyter
Looking for jupyter_config in C:\Users\S7791242
Node v12.8.1

> C:\Users\S7791242\AppData\Local\Continuum\anaconda3\npm.CMD pack @jupyter-widgets/jupyterlab-manager
The system cannot find the path specified.
The system cannot find the path specified.
npm notice
npm notice package: @jupyter-widgets/jupyterlab-manager@1.0.2
npm notice === Tarball Contents ===
npm notice 2.3kB  package.json
npm notice 1.5kB  LICENSE
npm notice 1.9kB  README.md
npm notice 277B   lib/index.d.ts
npm notice 380B   lib/index.js
npm notice 5.3kB  lib/manager.d.ts
npm notice 12.0kB lib/manager.js
npm notice 1.9kB  lib/output.d.ts
npm notice 5.2kB  lib/output.js
npm notice 830B   lib/plugin.d.ts
npm notice 6.7kB  lib/plugin.js
npm notice 956B   lib/renderer.d.ts
npm notice 3.3kB  lib/renderer.js
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js
npm notice 375B   schema/plugin.json
npm notice === Tarball Details ===
npm notice name:          @jupyter-widgets/jupyterlab-manager
npm notice version:       1.0.2
npm notice filename:      jupyter-widgets-jupyterlab-manager-1.0.2.tgz
npm notice package size:  11.3 kB
npm notice unpacked size: 44.0 kB
npm notice shasum:        8913784a181f7fb05d79943080549893ccb45ca1
npm notice integrity:     sha512-7c5jADfFFc16g[...]728vBtwbByyIw==
npm notice total files:   16
npm notice
jupyter-widgets-jupyterlab-manager-1.0.2.tgz

Traceback (most recent call last):

  File "C:\Users\S7791242
[jupyterlab-debug-18ky8qq2.log](https://github.com/jupyterlab/jupyterlab/files/3530547/jupyterlab-debug-18ky8qq2.log)
\AppData\Roaming\Python\Python37\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\S7791242\AppData\Roaming\Python\Python37\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "C:\Users\S7791242\AppData\Roaming\Python\Python37\site-packages\jupyterlab\labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "C:\Users\S7791242\AppData\Roaming\Python\Python37\site-packages\jupyterlab\labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "C:\Users\S7791242\AppData\Roaming\Python\Python37\site-packages\jupyterlab\commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "C:\Users\S7791242\AppData\Roaming\Python\Python37\site-packages\jupyterlab\commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "C:\Users\S7791242\AppData\Roaming\Python\Python37\site-packages\jupyterlab\commands.py", line 1373, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "C:\Users\S7791242\AppData\Roaming\Python\Python37\site-packages\jupyterlab\commands.py", line 1444, in _extract_package
    raise ValueError(msg % source)

ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid npm package

Exiting application: jupyter

**npm config list:**

(base) C:\Users\S7791242>npm config list
The system cannot find the path specified.
; cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.10.2 node/v12.8.1 win32 x64"

; userconfig C:\Users\S7791242\.npmrc
http-proxy = "http://proxy.corporate.com:8080"
https-proxy = "http://proxy.corporate.com:8080/"
proxy = "http://proxy..com:8080/"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; node bin location = C:\Users\S7791242\AppData\Local\Continuum\anaconda3\node.exe
; cwd = C:\Users\S7791242
; HOME = C:\Users\S7791242
; "npm config ls -l" to show all defaults.

I've tried doing the solution of:
https://github.com/jupyterlab/jupyterlab/issues/6845

but to no avail

**PATH:** C:\Users\S7791242\AppData\Local\Google\Chrome\Application;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Lenovo\Touch Fingerprint Software\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Users\S7791242\AppData\Local\Programs\Git\cmd;%IntelliJ IDEA%;C:\Users\S7791242\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\Users\S7791242\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\xelatex;C:\Users\S7791242\AppData\Roaming\npm;C:\Users\S7791242\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\S7791242\AppData\Local\Continuum\anaconda3;C:\Users\S7791242\AppData\Local\Continuum\anaconda3\Library\bin;

**Comment by rejscotia** [comment]
I believe this can be marked as closed. A complete clean install seems to have worked. I never figured out the root cause of the issue on my original setup though.

In case someone is in a similar scenario, here are the cleaning steps I did:

1. I reset all my NPM configs
2. I used conda's anaconda-clean package to clean up my anaconda configs
3. Uninstalled anaconda3 
4. After reinstall, I did conda init cmd.exe
5. Proceed with installation as normal
