### ISSUE TITLE
"Fatal process OOM in insufficient memory to create an Isolate" trying to build Jupyterlab on Win10 / 32 bit mode

### ISSUE THREAD

**Issue by stonebig** [jupyterlab/jupyterlab#7118]
I have a strange message, since around Jupyterlab-1.0.x:

`Fatal process OOM in insufficient memory to create an Isolate` 

any idea/suggestion ?

````
[LabBuildApp] Building in C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\share\jupyter\lab
[LabBuildApp] Node v10.16.3

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "jupyter-leaflet > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
warning "@jupyterlab/vega3-extension > vega-embed > vega-themes@2.3.2" has unmet peer dependency "vega@*".
warning "@jupyterlab/vega3-extension > vega-embed > vega-lite@2.7.0" has unmet peer dependency "vega@^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 192.13s.

[LabBuildApp] > node C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 2.52s.

[LabBuildApp] > node C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js

#
# Fatal process OOM in insufficient memory to create an Isolate
#
````

**Comment by stonebig** [comment]
current list of complement shall be:
````
        @jupyter-widgets/jupyterlab-manager v1.0.2 enabled  ok
        @jupyterlab/vega3-extension v1.0.0 enabled  ok
        @pyviz/jupyterlab_pyviz v0.8.0 enabled  ok
        bqplot v0.4.7 enabled  ok
        jupyter-leaflet v0.11.1 enabled  ok
        jupyter-matplotlib v0.4.2 enabled  ok
        jupyter-threejs v2.1.1 enabled  ok
        jupyterlab-datawidgets v6.2.0 enabled  ok
        jupyterlab_bokeh v1.0.0 enabled  ok
````

What shall I do to recover this ? 
- reduce list of plugins ?
- upgrade in yarn/nom version ?
- is it the result of a bug ?

**Comment by stonebig** [comment]
I read "It's a common issue when using TypeScript 2.1+ and webpack." https://www.npmjs.com/package/increase-memory-limit

**Comment by stonebig** [comment]
no  more success:
````

[LabBuildApp] > node C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js

#
# Fatal process OOM in insufficient memory to create an Isolate
#


<--- Last few GCs --->


<--- JS stacktrace --->

error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\commands.py", line 583, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
````

**Comment by stonebig** [comment]
is this "--max_old_space_size=4096" a problem on 32 bit ? seeing https://github.com/Microsoft/vscode/issues/43223#issuecomment-364164972

**Comment by stonebig** [comment]
so trying back to Jupyterlab-1.0.1 , before that 4096

**Comment by jasongrout** [comment]
Also, does it help to use jlab 1.1.0 with the new `jupyter lab build --minimize=False`?

**Comment by jasongrout** [comment]
Also, you may be right that setting the memory to 4GB is too much for 32-bit? You can try setting it lower and see if it helps.

**Comment by stonebig** [comment]
hi @jasongrout , I will try now your suggestion "--minimize=False".

 and how to play with the memory parameter ?

**Comment by jasongrout** [comment]
Use `jupyter lab path` to find your application directory, and inside that directory, inside the staging directory, you'll find the package.json jlab uses to build, and there you should find these lines:

https://github.com/jupyterlab/jupyterlab/blob/e7d5441f745bc96741a168c187cd1b5508489a69/jupyterlab/staging/package.json#L9-L11

You can try adjusting it there

**Comment by stonebig** [comment]
--minimize=false was not a success:
````
[LabBuildApp] Building in C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\share\jupyter\lab
[LabBuildApp] Node v10.16.3

[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "jupyter-leaflet > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
warning "@jupyterlab/vega3-extension > vega-embed > vega-themes@2.4.0" has unmet peer dependency "vega@*".
warning "@jupyterlab/vega3-extension > vega-embed > vega-lite@2.7.0" has unmet peer dependency "vega@^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 195.11s.

[LabBuildApp] > node C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 2.54s.

[LabBuildApp] > node C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
[LabBuildApp] yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.config.js

#
# Fatal process OOM in insufficient memory to create an Isolate
#


<--- Last few GCs --->


<--- JS stacktrace --->

error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy32-3741b2\python-3.7.4\lib\site-packages\jupyterlab\commands.py", line 583, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

````

**Comment by stonebig** [comment]
trying "jupyter lab build" with "NODE_OPTIONS=--max_old_space_size=3000"

**Comment by stonebig** [comment]
now retrying with voila and max_old_space_size=3000 for 32 and 64 bit

**Comment by vidartf** [comment]
Potentially also `--dev-build=True` can help.

**Comment by dhirschfeld** [comment]
I have a vague recollection that this may just be an out-of -memory error on your PC i.e. independent from node.

If you're running 32bit on Windows you may simply be out of luck.

One thing to try is that by default 32bit Windows can only address 2GB of memory. You can however increase that to 3GB with the following hack:
https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-enable-a-3GB-switch-on-Windows-Vista-Windows-7-or-Windows-XP-s.html

https://techcommunity.microsoft.com/t5/Ask-The-Performance-Team/Memory-Management-Demystifying-3GB/ba-p/372333

I think the application may have to opt-in to this so YMMV.

**Comment by stonebig** [comment]
so, with voila it fails again.:
- I'll remove voila from my 32bit build,
- I'll suppose that soon Jupyter will become too big for 32 bit Windows.

After Python-2, maybe an E.O.L for 32 bit Windows shall be decided.

**Comment by jasongrout** [comment]
So it sounds like this investigation is resolved now?

**Comment by stonebig** [comment]
root cause is known, a slow desease with no long term remedies, except maybe a modular Jupyterlab-2

**Comment by jasongrout** [comment]
Thanks! Closing as answered, then. Sorry you have to still support 32-bit windows.

**Comment by stonebig** [comment]
I will just use plain Jupyterlab in 32bit mode, no attempt to rebuild it with extensions.

**Comment by vidartf** [comment]
You could pack your own distro on a 64-bit machine and install that on the 32 bit systems, if needed.

**Comment by stonebig** [comment]
I use a 64 bit PC and a 32 bit tool chain.

If it doesn't build "naturally" that way, it won't "re-build" on the end-user 32bit PC, making the solution not self-maintainable.

**Comment by stonebig** [comment]
now retrying with voila and max_old_space_size=2000 for 32 bit, and situation seems better
