### ISSUE TITLE
`jupyter lab build` says it requires python 2.7

### ISSUE THREAD

**Issue by Rabeez** [jupyterlab/jupyterlab#7195]
I'm setting up jupyterlab with a couple of extensions on my work laptop. When I run the build command I get `RuntimeError: JupyterLab failed to build` along with a generated log file which says that some node command was looking for python 2.7 (which I don't have installed obviously)

I'm using Windows 10 and jupyterlab 1.0.2 on python 3.7.3 and this is the only version of python I have which is in the base environment of anaconda distribution. 

The contents of the log file are:
```
[LabBuildApp] Building in C:\ProgramData\Anaconda3\share\jupyter\lab
[LabBuildApp] Node v12.10.0

[LabBuildApp] Building jupyterlab assets
[LabBuildApp] > node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyterlab-chart-editor > react-chart-editor > plotly.js > mapbox-gl > @mapbox/gl-matrix@0.0.1: This
warning jupyterlab-chart-editor > react-chart-editor > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning jupyterlab-chart-editor > react-chart-editor > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0: 
warning jupyterlab-chart-editor > react-chart-editor > plotly.js > regl-line2d > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-utils@1.4.0" has unmet peer dependency "immutable@3.x.x".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-import-html@1.4.1" has unmet peer dependency "immutable@3.x.x".
warning "jupyterlab-chart-editor > react-chart-editor > @plotly/draft-js-export-html@1.2.0" has unmet peer dependency "immutable@3.x.x".
warning "jupyterlab-chart-editor > react-chart-editor > react-rangeslider@2.2.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-import-html > draft-js-import-element@1.4.0" has unmet peer dependency "immutable@3.x.x".
[5/5] Building fresh packages...
warning Error running install script for optional dependency: "C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas
Output:
C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.10.0 | win32 | x64
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if \"python\" can be used
gyp ERR! find Python - executable path is \"C:\\ProgramData\\Anaconda3\\python.exe\"
gyp ERR! find Python - version is \"3.7.3\"
gyp ERR! find Python - version is 3.7.3 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if \"python2\" can be used
gyp ERR! find Python - \"python2\" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - \"py.exe\" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\\Python27\\python.exe
gyp ERR! find Python - \"C:\\Python27\\python.exe\" could not be run
gyp ERR! find Python checking if Python is C:\\Python37\\python.exe
gyp ERR! find Python - \"C:\\Python37\\python.exe\" could not be run
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python 2.7.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python=\"C:\\Path\\To\\python.exe\"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python \"C:\\Path\\To\\python.exe\"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:303:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:132:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:221:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:267:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt: Command failed.
Exit code: 1
Command: node_modules\\.bin\\node-pre-gyp install
Arguments: 
Directory: C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@12.10.0 | win32 | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp info check checked for \"C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt\\canvas\\build\\Release\\canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp http 301 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\node-pre-gyp\\lib\\install.js:137:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:214:15)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\needle\\lib\\needle.js:482:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:299:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:209:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:456:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:209:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:305:12)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\ProgramData\\\\Anaconda3\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt
node-pre-gyp ERR! node -v v12.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
Done in 428.66s.

[LabBuildApp] > node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.15.2
$ C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] > node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "jupyterlab-chart-editor > react-chart-editor > @plotly/draft-js-export-html@1.2.0" has unmet peer dependency "immutable@3.x.x".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-import-html@1.4.1" has unmet peer dependency "immutable@3.x.x".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-utils@1.4.0" has unmet peer dependency "immutable@3.x.x".
warning "jupyterlab-chart-editor > react-chart-editor > react-rangeslider@2.2.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-import-html > draft-js-import-element@1.4.0" has unmet peer dependency "immutable@3.x.x".
[5/5] Building fresh packages...
warning Error running install script for optional dependency: "C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas
Output:
C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.10.0 | win32 | x64
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if \"python\" can be used
gyp ERR! find Python - executable path is \"C:\\ProgramData\\Anaconda3\\python.exe\"
gyp ERR! find Python - version is \"3.7.3\"
gyp ERR! find Python - version is 3.7.3 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if \"python2\" can be used
gyp ERR! find Python - \"python2\" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - \"py.exe\" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\\Python27\\python.exe
gyp ERR! find Python - \"C:\\Python27\\python.exe\" could not be run
gyp ERR! find Python checking if Python is C:\\Python37\\python.exe
gyp ERR! find Python - \"C:\\Python37\\python.exe\" could not be run
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python 2.7.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python=\"C:\\Path\\To\\python.exe\"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python \"C:\\Path\\To\\python.exe\"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:303:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:132:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:221:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\\Users\\RABEEZ~1\\AppData\\Roaming\\nvm\\v12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:267:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt: Command failed.
Exit code: 1
Command: node_modules\\.bin\\node-pre-gyp install
Arguments: 
Directory: C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@12.10.0 | win32 | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp info check checked for \"C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt\\canvas\\build\\Release\\canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp http 301 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\node-pre-gyp\\lib\\install.js:137:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:214:15)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\needle\\lib\\needle.js:482:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:299:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:209:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:456:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:209:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:305:12)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\ProgramData\\\\Anaconda3\\\\share\\\\jupyter\\\\lab\\\\staging\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd C:\\ProgramData\\Anaconda3\\share\\jupyter\\lab\\staging\\node_modules\\canvas-prebuilt
node-pre-gyp ERR! node -v v12.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-win32-x64.tar.gz"
info This module is OPTIONAL, you can safely ignore this error
Done in 18.49s.

[LabBuildApp] > node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build
[LabBuildApp] yarn run v1.15.2
$ webpack
C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:93
				throw err;
				^

Error: EPERM: operation not permitted, unlink '..\schemas\@jupyterlab\application-extension\main.json'
    at Object.unlinkSync (fs.js:1046:3)
    at fixWinEPERMSync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\fs-extra\lib\remove\rimraf.js:169:13)
    at rimrafSync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\fs-extra\lib\remove\rimraf.js:260:26)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\fs-extra\lib\remove\rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at fixWinEPERMSync (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\fs-extra\lib\remove\rimraf.js:167:5)
    at Object.rimrafSync [as removeSync] (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\fs-extra\lib\remove\rimraf.js:260:26)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:67:28
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:38:22)
    at Object.<anonymous> (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\webpack.config.js:32:25)
    at Module._compile (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:116:13)
    at requireConfig (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:118:6)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:123:15)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\yargs\yargs.js:567:18)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10) {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: '..\\schemas\\@jupyterlab\\application-extension\\main.json'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 80, in start
    command=command, logger=self.log)

[LabBuildApp]   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 373, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 566, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

```

**Comment by jasongrout** [comment]
Did upgrading npm work for you?

**Comment by Rabeez** [comment]
@jasongrout I'm on a work laptop and don't have write permissions for most directories so upgrading npm also gives an error. I have a feeling the EPERM issue is also because of this. I haven't had time to contact IT and confirm this yet.

**Comment by Rabeez** [comment]
I had IT give me admin access temporarily and running `jupyter lab build` on the elevated prompt worked okay. 
Is a better error message possible for this problem?

**Comment by jasongrout** [comment]
The error message here is from webpack, not JupyterLab code. It did say "Error: EPERM: operation not permitted, unlink '..\schemas\@jupyterlab\application-extension\main.json'" which (at least to some) is pretty clear. Of course it could always be clearer, if you want to file an issue with webpack.

Closing as resolved. Thanks for following up here and letting us know you got it working.

**Comment by oujlassi** [comment]
Hi
I have similar error.
the app from github repository use **webpack**. 
```
C:\Users\ZETA\Documents\Labs\LaboReact>git clone https://github.com/alexnm/react-ssr
Cloning into 'react-ssr'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (24/24), done.

Receiving objects: 100% (157/157), 188.72 KiB | 248.00 KiB/s, done.
Resolving deltas: 100% (66/66), done.

C:\Users\ZETA\Documents\Labs\LaboReact>cd react-ssr

C:\Users\ZETA\Documents\Labs\LaboReact\react-ssr>npm install
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!

> iltorb@1.3.10 install C:\Users\ZETA\Documents\Labs\LaboReact\react-ssr\node_modules\iltorb
> detect-libc prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\iltorb-v1.3.10-node-v64-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\ZETA\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MayhemYDG-iltorb-releases-download-v1.3.10-iltorb-v1.3.10-node-v64-win32-x64.tar.gz
prebuild-install http request GET https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v64-win32-x64.tar.gz
prebuild-install http 404 https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v64-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=win32)

C:\Users\ZETA\Documents\Labs\LaboReact\react-ssr\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ZETA\Documents\Labs\LaboReact\react-ssr\node_modules\iltorb
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN react-ssr@1.0.0 No repository field.
npm WARN react-ssr@1.0.0 scripts['server'] should probably be scripts['start'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.3.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ZETA\AppData\Roaming\npm-cache\_logs\2019-10-03T18_26_32_333Z-debug.log
```

**Comment by vidartf** [comment]
@oujlassi Your error has nothing to do with jupyterlab. You should probably report your error to the package maintainers of `react-ssr`.
