### ISSUE TITLE
No kernel while creating new nb

### ISSUE THREAD

**Issue by StevenLi-DS** [jupyterlab/jupyterlab#7255]
I can run the existing notebooks but can't have new nb. I tried to update the Jupyter lab and iPython, but the problem still exists.
![image](https://user-images.githubusercontent.com/33796896/65392405-9e01aa00-dd42-11e9-89df-9e8728e331e2.png)

```
[I 13:53:18.536 LabApp] Build is up to date
[W 13:53:19.117 LabApp] Notebook Desktop/PLSR_on_sensory_and_fluorescence_data.ipynb is not trusted
[I 13:53:19.635 LabApp] Kernel started: db49135b-5a41-40d4-a0d4-a0b3af63a2fd
[I 13:53:19.657 LabApp] Kernel started: 3666e009-ed2e-421d-9349-12574e1354dc
[I 13:53:19.683 LabApp] Kernel started: 39cbaba9-4d77-4eaf-b49d-7ee2975d9051
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
Traceback (most recent call last):
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "__main__", mod_spec)
    "Missing required dependencies {0}".format(missing_dependencies))
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
ImportError: Missing required dependencies ['numpy']
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
[I 13:53:20.717 LabApp] Adapting to protocol v5.1 for kernel db49135b-5a41-40d4-a0d4-a0b3af63a2fd
[I 13:53:20.718 LabApp] Adapting to protocol v5.1 for kernel db49135b-5a41-40d4-a0d4-a0b3af63a2fd
[I 13:53:22.647 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
[I 13:53:22.672 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
[I 13:53:25.643 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
[I 13:53:25.686 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
[I 13:53:28.654 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
[I 13:53:28.698 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
[I 13:53:31.669 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
[I 13:53:31.716 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
Traceback (most recent call last):
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liqia\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in <module>
    from .core.application import Application
  File "C:\Users\liqia\Anaconda3\lib\site-packages\IPython\core\application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 19, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 12, in <module>
    from .loader import Config, LazyConfigValue, _is_section_key
  File "C:\Users\liqia\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "C:\Users\liqia\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 13, in <module>
    import random
  File "C:\Users\liqia\Desktop\random.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\liqia\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
[W 13:53:34.677 LabApp] KernelRestarter: restart failed
[W 13:53:34.677 LabApp] Kernel 3666e009-ed2e-421d-9349-12574e1354dc died, removing from map.
[W 13:53:34.727 LabApp] KernelRestarter: restart failed
[W 13:53:34.727 LabApp] Kernel 39cbaba9-4d77-4eaf-b49d-7ee2975d9051 died, removing from map.
[I 13:53:48.876 LabApp] Starting buffering for db49135b-5a41-40d4-a0d4-a0b3af63a2fd:5350cb27-e306-4b28-9165-06beecf4988c
[W 13:54:20.752 LabApp] Timeout waiting for kernel_info reply from 3666e009-ed2e-421d-9349-12574e1354dc
[W 13:54:33.743 LabApp] Timeout waiting for kernel_info reply from 3666e009-ed2e-421d-9349-12574e1354dc
[E 13:54:33.748 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 3666e009-ed2e-421d-9349-12574e1354dc)
[E 13:54:33.749 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 3666e009-ed2e-421d-9349-12574e1354dc)
```

**Comment by StevenLi-DS** [comment]
It turns out I have a `random.py` on my desktop... I renamed the file and problem solved. sorry about that.
