### ISSUE TITLE
Jupyter lab 1.1.4 conda install on Windows missing pywin32 dependency

### ISSUE THREAD

**Issue by owen-synergy** [jupyterlab/jupyterlab#7259]
## Description

I found jupyter lab was throwing an error when attempting to select a kernel and the error mentioned a missing win32api import (sorry forgot to take a screenshot before I fixed the issue).

## Reproduce

1. Updated to jupyterlab 1.1.4 on windows in an environment that didn't contain the pywin32 package.
2. Performed a jupyter lab build
3. Attempt to open a notebook - was prompted to select a kernel - I selected the default Python3 kernel.
4. Jupyter lab showed a bad import error - for a "import win32api" line. 

After I manually conda installed pywin32 everything worked fine.

## Expected behavior

I expect the jupyterlab conda recipe to automatically install pywin32 if that is a dependency and there to be no issue launching the kernel.

## Context

- Operating System and version: Windows 10 Enterprise 10.0.17763
- Browser and version: Chrome version 73.0.3683.75
- JupyterLab version: 1.1.4

**Comment by jasongrout** [comment]
Googling for "pywin32 conda", it appears that this is a more fundamental issue than JupyterLab, possibly an issue with the conda python package. JupyterLab doesn't itself depend on pywin32, as far as I know.

Can you give a environment create command that illustrates the issue, or at least the listing of packages in your environment where the issue occurs?

**Comment by owen-synergy** [comment]
Alright, I created a new environment and reproduced the issue. Command to create environment is:

conda create -n testlab python=3.7 jupyterlab

Installed packages are:

Name | Version | Build | Channel
--- | --- | --- | --- 
attrs | 19.1.0 | py_0 | conda-forge
backcall | 0.1.0 | py_0 | conda-forge
bleach | 3.1.0 | py_0 | conda-forge
ca-certificates | 2019.9.11 | hecc5488_0 | conda-forge
certifi | 2019.6.16 | py37_1 | conda-forge
colorama | 0.4.1 | py_0 | conda-forge
decorator | 4.4.0 | py_0 | conda-forge
defusedxml | 0.5.0 | py_1 | conda-forge
entrypoints | 0.3 | py37_1000 | conda-forge
ipykernel | 5.1.2 | py37h5ca1d4c_0 | conda-forge
ipython | 7.8.0 | py37h5ca1d4c_0 | conda-forge
ipython_genutils | 0.2.0 | py_1 | conda-forge
jedi | 0.15.1 | py37_0 | conda-forge
jinja2 | 2.10.1 | py_0 | conda-forge
json5 | 0.8.5 | py_0 | conda-forge
jsonschema | 3.0.2 | py37_0 | conda-forge
jupyter_client | 5.3.3 | py_0 | conda-forge
jupyter_core | 4.4.0 | py_0 | conda-forge
jupyterlab | 1.1.4 | py_0 | conda-forge
jupyterlab_server | 1.0.6 | py_0 | conda-forge
libsodium | 1.0.17 | h2fa13f4_0 | conda-forge
m2w64-gcc-libgfortran | 5.3.0 | 6
m2w64-gcc-libs | 5.3.0 | 7
m2w64-gcc-libs-core | 5.3.0 | 7
m2w64-gmp | 6.1.0 | 2
m2w64-libwinpthread-git | 5.0.0.4634.697f757 | 2
markupsafe | 1.1.1 | py37hfa6e2cd_0 | conda-forge
mistune | 0.8.4 | py37hfa6e2cd_1000 | conda-forge
msys2-conda-epoch | 20160418 | 1
nbconvert | 5.6.0 | py37_1 | conda-forge
nbformat | 4.4.0 | py_1 | conda-forge
notebook | 6.0.1 | py37_0 | conda-forge
openssl | 1.1.1c | hfa6e2cd_0 | conda-forge
pandoc | 2.7.3 | 0 | conda-forge
pandocfilters | 1.4.2 | py_1 | conda-forge
parso | 0.5.1 | py_0 | conda-forge
pickleshare | 0.7.5 | py37_1000 | conda-forge
pip | 19.2.3 | py37_0 | conda-forge
prometheus_client | 0.7.1 | py_0 | conda-forge
prompt_toolkit | 2.0.9 | py_0 | conda-forge
pygments | 2.4.2 | py_0 | conda-forge
pyrsistent | 0.15.4 | py37hfa6e2cd_0 | conda-forge
python | 3.7.3 | h510b542_1 | conda-forge
python-dateutil | 2.8.0 | py_0 | conda-forge
pywinpty | 0.5.5 | py37_1000 | conda-forge
pyzmq | 18.1.0 | py37h16f9016_0 | conda-forge
send2trash | 1.5.0 | py_0 | conda-forge
setuptools | 41.2.0 | py37_0 | conda-forge
six | 1.12.0 | py37_1000 | conda-forge
sqlite | 3.29.0 | hfa6e2cd_1 | conda-forge
terminado | 0.8.2 | py37_0 | conda-forge
testpath | 0.4.2 | py_1001 | conda-forge
tornado | 6.0.3 | py37hfa6e2cd_0 | conda-forge
traitlets | 4.3.2 | py37_1000 | conda-forge
vc | 14.1 | h0510ff6_4
vs2015_runtime | 14.16.27012 | hf0eaf9b_0
wcwidth | 0.1.7 | py_1 | conda-forge
webencodings | 0.5.1 | py_1 | conda-forge
wheel | 0.33.6 | py37_0 | conda-forge
wincertstore | 0.2 | py37_1002 | conda-forge
winpty | 0.4.3 | 4 | conda-forge
zeromq | 4.3.2 | h6538335_2 | conda-forge

The exception trace is:

`Traceback (most recent call last):
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\307357\AppData\Local\Continuum\miniconda3\envs\testlab\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
    import win32api
ModuleNotFoundError: No module named 'win32api'`

**Comment by owen-synergy** [comment]
![kernel_error](https://user-images.githubusercontent.com/50761413/65488943-b7d6f480-dedc-11e9-8312-c7a4c2441153.png)

This is what I see in the browser after selecting the Python3 kernel

**Comment by vidartf** [comment]
This is due to a recent change in jupyter client. Xref: https://github.com/jupyter/jupyter_client/pull/469

**Comment by jasongrout** [comment]
This is now tracked at https://github.com/conda-forge/jupyter_client-feedstock/issues/29.

Thanks for bringing this to our attention!

**Comment by owen-synergy** [comment]
You're welcome. Thanks for following up on it so quickly.

**Comment by vidartf** [comment]
The issue has been resolved upstream, but might take some time (up to a day?) to propagate out.

**Comment by jasongrout** [comment]
It's out now.

**Comment by PremekPaska** [comment]
BTW there's another variant of this issue. I've installed Jupyter Lab using pip and got a very similar error. The trace ended like this:

```
File "c:\users\pp\appdata\local\continuum\anaconda3\envs\atb\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
```

I tried downgrading jupyter lab to 1.1.2 and 1.0.10, but I didn't get rid of the error. What actually helped:
```
pip uninstall pywin32
conda install pywin32
```

It's probably just a hack that put there a different version. Didn't look into it.

**Comment by jasongrout** [comment]
Upgrading or downgrading jupyter lab probably won't do anything since it is an issue with the jupyter_client package, not the juptyerlab package.

I think installing the most recent jupyter_client conda-forge package will automatically pull in pywin32 now.
