### ISSUE TITLE
failed to render properly after update white

### ISSUE THREAD

**Issue by AbhimanyuAryan** [jupyterlab/jupyterlab#7296]
This is happening after conda update --all

<img width="913" alt="Screenshot 2019-10-05 at 4 49 34 AM" src="https://user-images.githubusercontent.com/8083613/66245458-8f949480-e72b-11e9-9ae7-06c906c51362.png">

```
jupyter lab
[I 04:42:14.527 LabApp] The port 8888 is already in use, trying another port.
[W 04:42:14.531 LabApp] Error loading server extension jupyter_http_over_ws
    Traceback (most recent call last):
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1615, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_http_over_ws'
[I 04:42:14.545 LabApp] JupyterLab extension loaded from /Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/jupyterlab
[I 04:42:14.545 LabApp] JupyterLab application directory is /Users/abhimanyuaryan/anaconda/share/jupyter/lab
[I 04:42:14.736 LabApp] Serving notebooks from local directory: /Users/abhimanyuaryan
[I 04:42:14.736 LabApp] The Jupyter Notebook is running at:
[I 04:42:14.736 LabApp] http://localhost:8889/?token=af9ab0a6c71908409a775da6c3b7460a7d4db6db6aaa80df
[I 04:42:14.736 LabApp]  or http://127.0.0.1:8889/?token=af9ab0a6c71908409a775da6c3b7460a7d4db6db6aaa80df
[I 04:42:14.736 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:42:14.743 LabApp]

    To access the notebook, open this file in a browser:
        file:///Users/abhimanyuaryan/Library/Jupyter/runtime/nbserver-45279-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=af9ab0a6c71908409a775da6c3b7460a7d4db6db6aaa80df
     or http://127.0.0.1:8889/?token=af9ab0a6c71908409a775da6c3b7460a7d4db6db6aaa80df
[W 04:42:18.898 LabApp] 500 GET /lab/api/settings/?1570230738854 (::1): Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.3.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/coreutils']:
        '^1.3.0'
[W 04:42:18.898 LabApp] Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.3.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/coreutils']:
        '^1.3.0'
[E 04:42:18.898 LabApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Sec-Fetch-Mode": "cors",
      "Dnt": "1",
      "Authorization": "token af9ab0a6c71908409a775da6c3b7460a7d4db6db6aaa80df",
      "X-Xsrftoken": "2|61fbceca|7f6f02a9441c248b9447ca7b4d4e9363|1570032367",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://localhost:8889/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "_xsrf=2|61fbceca|7f6f02a9441c248b9447ca7b4d4e9363|1570032367; username-localhost-8888=\"2|1:0|10:1570125997|23:username-localhost-8888|44:YjM1YjAxNGE1NTZlNDIwYWJjMWI0NDlkYzIxMGI1Mjk=|422b9358728daecad0d5de50980ea4fc1dd8c9b2230280135adba49f53d8f5a9\"; username-localhost-8889=\"2|1:0|10:1570230737|23:username-localhost-8889|44:ZTMxYzgxZmFjMDA1NDliM2I1NDkxYjYzMjY3ZjdmOWQ=|413434f2a9f60c5723bb761a3911fba301c03ace5dac6cf46ccaa058cfa51643\""
    }
[E 04:42:18.899 LabApp] 500 GET /lab/api/settings/?1570230738854 (::1) 27.59ms referer=http://localhost:8889/lab
[W 04:42:19.416 LabApp] The extension "@deathbeds/jupyterlab-font-dejavu-sans-mono" is outdated.

[W 04:42:19.418 LabApp] The extension "@deathbeds/jupyterlab-fonts" is outdated.

[W 04:42:19.419 LabApp] The extension "@oriolmirosa/jupyterlab_materialdarker" is outdated.

[W 04:42:19.419 LabApp] The extension "@deathbeds/jupyterlab-font-anonymous-pro" is outdated.

[W 04:42:19.420 LabApp] The extension "@deathbeds/jupyterlab-font-fira-code" is outdated.

[I 04:42:19.420 LabApp] Build is up to date
^C[I 04:43:18.787 LabApp] interrupted
Serving notebooks from local directory: /Users/abhimanyuaryan
0 active kernels
The Jupyter Notebook is running at:
http://localhost:8889/?token=af9ab0a6c71908409a775da6c3b7460a7d4db6db6aaa80df
 or http://127.0.0.1:8889/?token=af9ab0a6c71908409a775da6c3b7460a7d4db6db6aaa80df
Shutdown this notebook server (y/[n])? y
[C 04:43:20.370 LabApp] Shutdown confirmed
[I 04:43:20.371 LabApp] Shutting down 0 kernels

~
❯ jupyter labextension install \
  @deathbeds/jupyterlab-fonts \
  @deathbeds/jupyterlab-font-anonymous-pro \
  @deathbeds/jupyterlab-font-dejavu-sans-mono \
  @deathbeds/jupyterlab-font-fira-code

An error occured.
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.1.3 <1.2.0          >=0.19.2 <0.20.0@jupyterlab/notebook
See the log file for details:  /var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/jupyterlab-debug-t1xshbbv.log

~
❯ jupyter labextension install @deathbeds/jupyterlab-fonts @deathbeds/jupyterlab-font-anonymous-pro @deathbeds/jupyterlab-font-dejavu-sans-mono @deathbeds/jupyterlab-font-fira-code

An error occured.
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.1.3 <1.2.0          >=0.19.2 <0.20.0@jupyterlab/notebook
See the log file for details:  /var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/jupyterlab-debug-zf_zyend.log

~
❯ jupyter lab
[I 04:44:03.105 LabApp] The port 8888 is already in use, trying another port.
[W 04:44:03.109 LabApp] Error loading server extension jupyter_http_over_ws
    Traceback (most recent call last):
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1615, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_http_over_ws'
[I 04:44:03.124 LabApp] JupyterLab extension loaded from /Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/jupyterlab
[I 04:44:03.124 LabApp] JupyterLab application directory is /Users/abhimanyuaryan/anaconda/share/jupyter/lab
[I 04:44:03.311 LabApp] Serving notebooks from local directory: /Users/abhimanyuaryan
[I 04:44:03.311 LabApp] The Jupyter Notebook is running at:
[I 04:44:03.311 LabApp] http://localhost:8889/?token=0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546
[I 04:44:03.311 LabApp]  or http://127.0.0.1:8889/?token=0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546
[I 04:44:03.311 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:44:03.320 LabApp]

    To access the notebook, open this file in a browser:
        file:///Users/abhimanyuaryan/Library/Jupyter/runtime/nbserver-45414-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546
     or http://127.0.0.1:8889/?token=0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546
[W 04:44:05.732 LabApp] 500 GET /lab/api/settings/?1570230845702 (::1): Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.5.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[W 04:44:05.732 LabApp] Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.5.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[E 04:44:05.733 LabApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Sec-Fetch-Mode": "cors",
      "Dnt": "1",
      "Authorization": "token 0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546",
      "X-Xsrftoken": "2|61fbceca|7f6f02a9441c248b9447ca7b4d4e9363|1570032367",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://localhost:8889/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "_xsrf=2|61fbceca|7f6f02a9441c248b9447ca7b4d4e9363|1570032367; username-localhost-8888=\"2|1:0|10:1570125997|23:username-localhost-8888|44:YjM1YjAxNGE1NTZlNDIwYWJjMWI0NDlkYzIxMGI1Mjk=|422b9358728daecad0d5de50980ea4fc1dd8c9b2230280135adba49f53d8f5a9\"; username-localhost-8889=\"2|1:0|10:1570230845|23:username-localhost-8889|44:ZDMxOTI0ODM4Yzk1NDAxMWFiMTgzMmU4N2FkMDg2NmY=|e860cf194456df7b1754fb1d1a6842fe954001848a2ae4afbd875c22b0c9dcd2\""
    }
[E 04:44:05.736 LabApp] 500 GET /lab/api/settings/?1570230845702 (::1) 21.07ms referer=http://localhost:8889/lab
[I 04:44:05.894 LabApp] 301 GET /lab/workspaces/auto-U/?clone (::1) 0.88ms
[W 04:44:06.325 LabApp] 500 GET /lab/api/settings/?1570230846298 (::1): Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.5.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[W 04:44:06.325 LabApp] Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.5.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[E 04:44:06.325 LabApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Sec-Fetch-Mode": "cors",
      "Dnt": "1",
      "Authorization": "token 0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546",
      "X-Xsrftoken": "2|61fbceca|7f6f02a9441c248b9447ca7b4d4e9363|1570032367",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://localhost:8889/lab/workspaces/auto-U?clone",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "_xsrf=2|61fbceca|7f6f02a9441c248b9447ca7b4d4e9363|1570032367; username-localhost-8888=\"2|1:0|10:1570125997|23:username-localhost-8888|44:YjM1YjAxNGE1NTZlNDIwYWJjMWI0NDlkYzIxMGI1Mjk=|422b9358728daecad0d5de50980ea4fc1dd8c9b2230280135adba49f53d8f5a9\"; username-localhost-8889=\"2|1:0|10:1570230846|23:username-localhost-8889|44:NDJiNDVjNzBjNmFmNGNkNDk4NWQ5YzI0OGQ4MGFkYmM=|c9c3e170c5663c1b4994bfb292ba950d31121ffe0414729abd9efacd852d1495\""
    }
[E 04:44:06.326 LabApp] 500 GET /lab/api/settings/?1570230846298 (::1) 19.06ms referer=http://localhost:8889/lab/workspaces/auto-U?clone
[W 04:44:06.776 LabApp] The extension "@deathbeds/jupyterlab-font-dejavu-sans-mono" is outdated.

[W 04:44:06.777 LabApp] The extension "@deathbeds/jupyterlab-fonts" is outdated.

[W 04:44:06.778 LabApp] The extension "@oriolmirosa/jupyterlab_materialdarker" is outdated.

[W 04:44:06.778 LabApp] The extension "@deathbeds/jupyterlab-font-anonymous-pro" is outdated.

[W 04:44:06.779 LabApp] The extension "@deathbeds/jupyterlab-font-fira-code" is outdated.

[I 04:44:06.779 LabApp] Build is up to date
[I 04:44:42.279 LabApp] 302 GET /?token=0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546 (::1) 0.97ms
[W 04:44:43.294 LabApp] 500 GET /lab/api/settings/?1570230883277 (::1): Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.5.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[W 04:44:43.295 LabApp] Failed validating schema (@deathbeds/jupyterlab-fonts:package): '^1.5.0' is not valid under any of the given schemas

    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}

    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[E 04:44:43.295 LabApp] {
      "Host": "localhost:8889",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8889/lab",
      "Authorization": "token 0975342506ae25d578447afb3b1aed4fb4eaef03d2f39546",
      "X-Xsrftoken": "2|46c05251|504a7bca5cef2e0d9d07a25164bb2840|1570230882",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8889=\"2|1:0|10:1570230883|23:username-localhost-8889|44:Njg5ZjNkN2JlMzAwNGZiOGE0MzM1MzMwMmFjNGFmOTk=|6f9d42f9ab01cf045d90710e7e374bbe3f4aad46094c72ada604bbf4f90a3e93\"; _xsrf=2|46c05251|504a7bca5cef2e0d9d07a25164bb2840|1570230882",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 04:44:43.295 LabApp] 500 GET /lab/api/settings/?1570230883277 (::1) 13.68ms referer=http://localhost:8889/lab
```

**Comment by AbhimanyuAryan** [comment]
had to reinstall things to fix

**Comment by oikonang** [comment]
@AbhimanyuAryan Have exactly the same issue. What did you reinstall?

**Comment by telamonian** [comment]
@oikonang Instead of a reinstall you could just try doing a clean and rebuild:

```
jupyter lab clean && jupyter lab build
```

That fixes many things. From the log he posted, it also looks like @AbhimanyuAryan was having some problems with some out of date extensions. If the clean and rebuild doesn't work, if you have any extensions installed I'd recommend first listing them:

```bash
jupyter labextension list
```

then uninstalling all of them (the `--no-build` flag is to help save time):

```bash
jupyter labextension uninstall --all --no-build
```

then reinstalling the extensions one-by-one:

```bash
jupyter labextension install <extension-name> --no-build
```

Then, after all of your extensions have been uninstalled and reinstalled, do a build of Jupyterlab itself:

```
jupyter lab build
```

If that still doesn't work, try following the steps in the ["Diagnosing an Issue" guide](https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html#diagnosing-an-issue). If you follow all of the steps and your Jupyterlab install is still broken, please then open a new issue with all of the details.
