### ISSUE TITLE
Fail to run jupyter lab build

### ISSUE THREAD

**Issue by jmercier-lbi** [jupyterlab/jupyterlab#7298]
## Description

Dear, I try to install jupyter lab thus I create this script

```bash
python3 -m venv jupyterlab_venv
source jupyterlab_venv/bin/activate
pip install --upgrade pip
pip install wheel jupyterlab 

# extra dependencies
# bokeh:      https://github.com/bokeh/bokeh
# ipywidgets: https://github.com/jupyter-widgets/ipywidgets
# ipyvuetify: https://github.com/mariobuikhuizen/ipyvuetify
# bqplot:     https://github.com/bloomberg/bqplot
# ipyvolume:  https://github.com/maartenbreddels/ipyvolume
# ipyleaflet: https://github.com/jupyter-widgets/ipyleaflet
# voila:      https://github.com/voila-dashboards/voila
# jupytext :  https://github.com/mwouts/jupytext
pip install bokeh ipywidgets ipyvuetify bqplot ipyvolume ipyleaflet voila ipywidgets jupytext 

pushd jupyterlab_venv
  npm config set prefix "${PWD}/lib"
  npm install --prefix lib cross-env
  pushd bin
      ln -s ../lib/node_modules/cross-env/src/bin/cross-env.js cross-env
      ln -s ../lib/node_modules/cross-env/src/bin/cross-env-shell.js cross-env-shell
  popd
popd
jupyter lab build    # Build the app dir assets (optional)

deactivate
virtualenv --relocatable jupyterlab_venv
```

but the command `jupyter lab build` fail with this error:

```
[LabBuildApp] Building in /opt/jupyterlab-2.0.0a1/jupyterlab_venv/share/jupyter/lab
[LabBuildApp] Node v12.11.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 23.48s.

[LabBuildApp] > node /opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
error Command "yarn-deduplicate" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] > node /opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/staging/yarn.js
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.08s.

[LabBuildApp] > node /opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [ '--config', 'webpack.prod.minimize.config.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "/opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/jupyterlab-2.0.0a1/jupyterlab_venv/lib/python3.7/site-packages/jupyterlab/commands.py", line 583, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

I have no idea why that fails 
I see that it try to use this file `webpack.prod.minimize.config.js` but I see any remote location to download this file.

thanks for your help

best regards

**Comment by haraldschilly** [comment]
I also see this `error Command "yarn-deduplicate" not found` ...

```
> node --version           
v10.17.0                                                                 
> npm --version            
6.12.0                                                                   
> python --version         
Python 2.7.15+                                                           
> python3 --version        
Python 3.6.8                                                             
> jupyter lab --version    
1.1.4

**Comment by vidartf** [comment]
@haraldschilly Are you also virtualenv ? I'm curious if this issue is an issue of lab vs virtualenv or if this is something else.

**Comment by haraldschilly** [comment]
No, this is Ubuntu 18.04 and I'm running this is as root (installing from PyPI, etc.)

What's probably the same is that both of our environments do not meet some requirements (package missing, pkg is installed but at the wrong version, etc.). I've no idea, though. I would have hoped that build step (which runs in a temp dir) does setup everything properly. Some detail must be off …

**Comment by heayoungsuh** [comment]
Out of curiosity, Have you found a fix for your problem? I am having the same problem when building in a docker container.

**Comment by haraldschilly** [comment]
@heayoungsuh no, I gave up on this. IMHO something is fundamentally off with the build step (at the level of which "webpack" or "yarn" version is used, or whatever)

**Comment by jasongrout** [comment]
Indeed it should be installed for when it is needed (as of #5775, which was pre-1.0). We require it as a dependency [here](https://github.com/jupyterlab/jupyterlab/blob/3cb64ca6885358e7f9623f518518bb3f9de017bc/dev_mode/package.json#L85) and [here](https://github.com/jupyterlab/jupyterlab/blob/3cb64ca6885358e7f9623f518518bb3f9de017bc/jupyterlab/staging/package.json#L85).

**Comment by jasongrout** [comment]
Hmmm, perhaps we need to use npx run or something like that, to make sure we have the right paths? Can we try again with JupyterLab 2.0, coming out very soon?

**Comment by heayoungsuh** [comment]
Hello!

Sorry bout that I found out my problem. It seems that I forgot to add the
--deploy tag when building the image. It qas my first time so I ddnt know
how to do it. Thanks for looking into it! Have a nice day!

Kind regards,
Heayoung

**Comment by heayoungsuh** [comment]
Hi

Uhh discard my last message I got this confused with something else.

Kind regards
Heayoung

**Comment by vivekpayasi** [comment]
Hey @jasongrout ,
Could we got to the root of this? I'm still getting error in `JupyterLab 2.1.2` while building even with fixes suggested?

```
(base) -bash-4.2$ jupyter lab build --minimize=False --debug
[LabBuildApp] Searching ['/home_dir/some_dir/Vivek/miniconda/bin', '/home_dir/some_dir/.jupyter', '/home_dir/some_dir/Vivek/miniconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /home_dir/some_dir/Vivek/miniconda/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /home_dir/some_dir/.jupyter
[LabBuildApp] Looking for jupyter_config in /home_dir/some_dir/Vivek/miniconda/bin
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /home_dir/some_dir/Vivek/miniconda/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /home_dir/some_dir/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /home_dir/some_dir/Vivek/miniconda/bin
[LabBuildApp] JupyterLab 2.1.2
[LabBuildApp] Building in /home_dir/some_dir/Vivek/miniconda/share/jupyter/lab
[LabBuildApp] Node v13.13.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node /home_dir/some_dir/Vivek/miniconda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
\[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/vega-lite/-/vega-lite-4.11.0.tgz: unexpected end of file".
info If you think this is a bug, please open a bug report with the information provided in "/home_dir/some_dir/Vivek/miniconda/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...

[LabBuildApp] npm dependencies failed to install
Build failed.

--------
------ Troubleshooting info
--------
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home_dir/some_dir/Vivek/miniconda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home_dir/some_dir/Vivek/miniconda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/home_dir/some_dir/Vivek/miniconda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/home_dir/some_dir/Vivek/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/home_dir/some_dir/Vivek/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-sdpjdws4.log
[LabBuildApp] Exiting application: JupyterLab
```

Versions:
```
JupyterLab 2.1.2
Node v13.13.0
npm 6.14.4
```

**Comment by jasongrout** [comment]
Is this still an issue?

**Comment by jasongrout** [comment]
Hmm, that seems like a different error then above.

We removed that `ensure-max-old-space` script in JLab 3: https://github.com/jupyterlab/jupyterlab/pull/9282

FYI, I just checked building a fresh install of jlab 2.2.9 on macOS and node 12.19.0 with `jupyter lab build --dev-build=False`, and it seems to work okay.

**Comment by jasongrout** [comment]
Can you reproduce it in a fresh install of jlab 2.2.9 in a clean new environment?

**Comment by haraldschilly** [comment]
@jasongrout ok, I had some time to test this. node is `v12.21.0`, and essentially did

```
pip3 uninstall jupyterlab       
rm -rf /usr/local/share/jupyter/lab 
pip3 install 'jupyterlab<3'         
[...]
Successfully installed jupyterlab-2.2.9
jupyter lab build --dev-build=False 
```

which ends with an error. the log says:

```
[LabBuildApp] > node /usr/local/lib/python3.8/dist-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1                                                                                
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js                                       
/bin/sh: 1: ensure-max-old-space: not found                                                                   
error Command failed with exit code 127.                                                                      
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                          
```
---

We (here at CoCalc) should look into updating to version 3, maybe this fixes this. ... but last time I tried to run version 3, it failed. I think some of the command-line options must have changed or maybe some detail is different now. Hence I had no luck to let it show up...

**Comment by timenet2300** [comment]
check this: conda install -c conda-forge nodejs. work for me
