### ISSUE TITLE
Error Starting Kernel

### ISSUE THREAD

**Issue by ma-blaetke** [jupyterlab/jupyterlab#7472]
## Description

Using conda I have created a new enviroment called topeca with python3.7 and some standard packages including jupyter-lab, pandas, scipy, numpy etc. When starting jupyter labs it seems not possible to connect to the python kernel.

I get the following error in the terminal:

```
[E 11:25:33.341 LabApp] Uncaught exception POST /api/sessions?1572863133330 (192.168.35.223)
    HTTPServerRequest(protocol='https', host='nam-99.ipk-gatersleben.de:8888', method='POST', uri='/api/sessions?1572863133330', version='HTTP/1.1', remote_ip='192.168.35.223')
    Traceback (most recent call last):
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
        type=mtype))
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/jupyter_client/manager.py", line 240, in start_kernel
        self.write_connection_file()
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/jupyter_client/connect.py", line 547, in write_connection_file
        kernel_name=self.kernel_name
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/jupyter_client/connect.py", line 212, in write_connection_file
        with secure_write(fname) as f:
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "/home/blaetke/anaconda3/envs/topeca/lib/python3.7/site-packages/jupyter_client/connect.py", line 105, in secure_write
        assert '0600' == oct(stat.S_IMODE(os.stat(fname).st_mode)).replace('0o', '0')
    AssertionError
[W 11:25:33.343 LabApp] Unhandled error
[E 11:25:33.343 LabApp] {
      "Host": "nam-99.ipk-gatersleben.de:8888",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:69.0) Gecko/20100101 Firefox/69.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://nam-99.ipk-gatersleben.de:8888/lab?",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|5e27b8ed|90069f896a8ff526bec3a329bfbef3d5|1572863097",
      "Origin": "https://nam-99.ipk-gatersleben.de:8888",
      "Content-Length": "197",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|5e27b8ed|90069f896a8ff526bec3a329bfbef3d5|1572863097; username-nam-99-ipk-gatersleben-de-8888=\"2|1:0|10:1572863099|39:username-nam-99-ipk-gatersleben-de-8888|44:ZmQ2Y2RmZjNjYjY3NGM0MWJlMmVlZTYwODhhZjhmNzI=|8e8b821fba04b53c7e1c754916f67b0064a114ea4446300333bab6065c1eb9f1\"",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 11:25:33.344 LabApp] 500 POST /api/sessions?1572863133330 (192.168.35.223) 13.25ms referer=https://nam-99.ipk-gatersleben.de:8888/lab?
```

I have already done some research, but nothing really helped. E.g. I checked the kernelspec and kernel.json and it seems to be fine.

```
jupyter kernelspec list

Available kernels:

python3             /home/blaetke/.local/share/jupyter/kernels/python3
```

```
cd /home/blaetke/.local/share/jupyter/kernels/python3

nano kernel.json

{

"argv": [

"/home/blaetke/anaconda3/envs/topeca/bin/python",

"-m",

"ipykernel_launcher",

"-f",

"{connection_file}"

],

"display_name": "Python 3",

"language": "python"

}
```
I checked if the path above exists and it does.
```
which python

~/anaconda3/envs/topeca/bin/python
```

Any idea?!?

**Comment by jasongrout** [comment]
This looks like a kernel issue, not a JupyterLab issue. I think the appropriate repo for the issue is the [juptyer_client](https://github.com/jupyter/jupyter_client/) repo (where the traceback is showing the error is occuring).

This looks like it is a permission error:

```
        assert '0600' == oct(stat.S_IMODE(os.stat(fname).st_mode)).replace('0o', '0')
    AssertionError
```
I think it's making sure the kernel connection file is not writable.

**Comment by ma-blaetke** [comment]
Thanks for that hint. I found a solution here:

https://stackoverflow.com/questions/58214911/kernel-error-jupyter-client-connect-py-assertionerror

The latest `jupyter_client=5.3.3` is not compatible with jupyter running on the linux server. I had to downgrade it to `jupyter_client=5.3.1`

**Comment by jasongrout** [comment]
Great, thanks!
