### ISSUE TITLE
Jupyterlab starting error

### ISSUE THREAD

**Issue by zapsdus** [jupyterlab/jupyterlab#7530]
### Description:
---------
Note: this is a local server on my personal computer as I was trying to start a JupyterLab notebook.
For reference the full message on the UI:

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 40, in <module>
    app_version = get_app_version()
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 541, in get_app_version
    app_options, app_dir=app_dir, core_config=core_config))
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 580, in __init__
    self.info = self._get_app_info()
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1042, in _get_app_info
    info['local_extensions'] = self._get_local_extensions()
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1354, in _get_local_extensions
    return self._get_local_data('local_extensions')
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1479, in _get_local_data
    config = self._read_build_config()
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1448, in _read_build_config
    return json.load(fid)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Reproduce:
---
Launch JupyterLab in a terminal with the command `jupyter lab`

### Context:
---
- Operating System and version: MAC OSX 10.4.6
- Browser and version: Chrome
- JupyterLab version: 1.2.3
- Jupyter Notebook can work properly

Originally, Jupyter Lab worked well. Until I tried to install the `metadata-extension` and a `Error: 500 (Internal Server Error)` came out.
I cleaned up the `.jupyter` folder hoping to solve the problem, and I think I accidentally removed a .json file that is required to start Jupyter Lab.

**Comment by zapsdus** [comment]
Originally, Jupyter Lab worked well. Until I tried to install the `metadata-extension` and a `Error: 500 (Internal Server Error)` came out.
I cleaned up the `.jupyter` folder hoping to solve the problem, and I think I accidentally removed a .json file that is required to start Jupyter Lab.

**Comment by zapsdus** [comment]
Problem fixed by manually removing everything in the directory `/usr/local/share/jupyter/lab`
