### ISSUE TITLE
Jupyter Build Failed on Rpi

### ISSUE THREAD

**Issue by xilunaJumma** [jupyterlab/jupyterlab#7606]
Hi,Friends!
When I run jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1
there is a error as blow:

`Yarn configuration loaded.
Node v8.9.0

> /usr/local/bin/npm pack @jupyter-widgets/jupyterlab-manager@1.1
jupyter-widgets-jupyterlab-manager-1.1.0.tgz

Yarn configuration loaded.
Node v8.9.0

Building jupyterlab assets (build:prod:minimize)
> node /home/corvin/.local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 2.28s.

> node /home/corvin/.local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
yarn run v1.15.2
$ /home/corvin/.local/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 1.23s.

> node /home/corvin/.local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:624
    throw err;
    ^

Error: Command failed: /home/corvin/.local/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (/home/corvin/.local/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/home/corvin/.local/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/corvin/.local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/home/corvin/.local/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "/home/corvin/.local/lib/python3.7/site-packages/jupyterlab/commands.py", line 669, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
`

**Comment by xilunaJumma** [comment]
jupyter lab --version
1.2.3
node -v 
v8.9.0
npm -v
5.5.1

**Comment by hexagonrecursion** [comment]
Had the same issue with node from my distro
```
$ jupyter lab --version
1.2.6
$ node -v
v10.16.3
$ npm -v
6.9.0
```
Installed node from conda-forge
```
$ conda install -c conda-forge nodejs
$ jupyter lab --version
1.2.6
$ node -v
v13.7.0
$ npm -v
6.13.6
```
Now 
```
 jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
runs fine
