### ISSUE TITLE
Problen on extensions

### ISSUE THREAD

**Issue by Tvix22** [jupyterlab/jupyterlab#7608]
Hello community:

When i try to install some extension, i have this problem. I cant install extensions never. nothings.
¿Any Solve?

Thanks for your time!
```
(quant) ubuntu@QuanTArmY:/etc/systemd/system$ jupyter labextension install jupyterlab-cpustatus --debug
No files in /home/ubuntu/.ipython/nbextensions
Searching ['/etc/systemd/system', '/home/ubuntu/.jupyter', '/home/ubuntu/miniconda3/envs/quant/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /home/ubuntu/miniconda3/envs/quant/etc/jupyter
Looking for jupyter_config in /home/ubuntu/.jupyter
Looking for jupyter_config in /etc/systemd/system
Yarn configuration loaded.
Node v10.13.0

> /home/ubuntu/miniconda3/envs/quant/bin/npm pack jupyterlab-cpustatus
/npm notice
npm notice 📦  jupyterlab-cpustatus@1.1.0
npm notice === Tarball Contents ===
npm notice 0     style/index.css
npm notice 6.6kB lib/index.js
npm notice 1.1kB package.json
npm notice 454B  README.md
npm notice 354B  lib/index.d.ts
npm notice === Tarball Details ===
npm notice name:          jupyterlab-cpustatus
npm notice version:       1.1.0
npm notice filename:      jupyterlab-cpustatus-1.1.0.tgz
npm notice package size:  2.7 kB
npm notice unpacked size: 8.5 kB
npm notice shasum:        64de1d252cc504d948a900e1446a3b56a985db4b
npm notice integrity:     sha512-1uRm9dXltQQQ7[...]f/q+B+agCd2RA==
npm notice total files:   5
npm notice
jupyterlab-cpustatus-1.1.0.tgz

Yarn configuration loaded.
Node v10.13.0

Building jupyterlab assets (build:prod:minimize)
> node /home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
|yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.02s.

> node /home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
|yarn run v1.15.2
$ /home/ubuntu/miniconda3/envs/quant/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 1.00s.

> node /home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
\yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:632
    throw err;
    ^

Error: Command failed: /home/ubuntu/miniconda3/envs/quant/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Object.<anonymous> (/home/ubuntu/miniconda3/envs/quant/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "/home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/commands.py", line 669, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-q2bky208.log
Exiting application: jupyter

```

```
Yarn configuration loaded.
Node v10.13.0

> /home/ubuntu/miniconda3/envs/quant/bin/npm pack jupyterlab-cpustatus
npm notice
npm notice 📦  jupyterlab-cpustatus@1.1.0
npm notice === Tarball Contents ===
npm notice 0     style/index.css
npm notice 6.6kB lib/index.js
npm notice 1.1kB package.json
npm notice 454B  README.md
npm notice 354B  lib/index.d.ts
npm notice === Tarball Details ===
npm notice name:          jupyterlab-cpustatus
npm notice version:       1.1.0
npm notice filename:      jupyterlab-cpustatus-1.1.0.tgz
npm notice package size:  2.7 kB
npm notice unpacked size: 8.5 kB
npm notice shasum:        64de1d252cc504d948a900e1446a3b56a985db4b
npm notice integrity:     sha512-1uRm9dXltQQQ7[...]f/q+B+agCd2RA==
npm notice total files:   5
npm notice
jupyterlab-cpustatus-1.1.0.tgz

Yarn configuration loaded.
Node v10.13.0

Building jupyterlab assets (build:prod:minimize)
> node /home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.91s.

> node /home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
yarn run v1.15.2
$ /home/ubuntu/miniconda3/envs/quant/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 0.98s.

> node /home/ubuntu/miniconda3/envs/quant/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:632
    throw err;
    ^

Error: Command failed: /home/ubuntu/miniconda3/envs/quant/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
```

**Comment by frankyan** [comment]
The same problem.
