### ISSUE TITLE
jupyter-lab build isn't working on Windows

### ISSUE THREAD

**Issue by peter-ch** [jupyterlab/jupyterlab#7631]
On Windows 10 x64, I HAVE nodejs 10 installed (I reinstalled it TWICE) and I keep getting this:

 jupyter-lab build
[LabBuildApp] JupyterLab 1.2.4
[LabBuildApp] Building in c:\python36\share\jupyter\lab
An error occured.
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  C:\Users\spook\AppData\Local\Temp\jupyterlab-debug-xsao0fp5.log

I DON'T WANT CONDA.

**Comment by jasongrout** [comment]
Apparently it's not finding the node you installed. Is node accessible from the command prompt where you are building jupyterlab?

**Comment by jasongrout** [comment]
what happens when you type `node` at the command prompt where you are building jupyterlab?

**Comment by peter-ch** [comment]
The paths are correct, "node" works. "npm" also works.

**Comment by jasongrout** [comment]
What does it say in that log file it references for details? Any clues there?

**Comment by peter-ch** [comment]
Here are the contents of the log file:

[LabBuildApp] Building in c:\python36\share\jupyter\lab
[LabBuildApp] NodeJS was not found. Yarn user configuration is ignored.
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "c:\python36\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "c:\python36\lib\site-packages\jupyterlab\labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "c:\python36\lib\site-packages\jupyterlab\commands.py", line 456, in build
    _node_check(app_options.logger)

[LabBuildApp]   File "c:\python36\lib\site-packages\jupyterlab\commands.py", line 1748, in _node_check
    node = which('node')

[LabBuildApp]   File "c:\python36\lib\site-packages\jupyterlab_server\process.py", line 59, in which
    raise ValueError(msg)

[LabBuildApp] ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

[LabBuildApp] Exiting application: JupyterLab

**Comment by jasongrout** [comment]
Does `python -c "from jupyterlab_server.process import which; print(which('node'))"` point to the path you expect it to point to?

**Comment by peter-ch** [comment]
This is the output I got after executing it:

 python -c "from jupyterlab_server.process import which; print(which('node'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\site-packages\jupyterlab_server\process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

**Comment by jasongrout** [comment]
How about the stock python version of which?

`python -c "import shutil; print(shutil.which('node'))"`

**Comment by peter-ch** [comment]
$ python -c "import shutil; print(shutil.which('node'))"
None

**Comment by jasongrout** [comment]
Yeah, python isn't seeing your node binary. Are you sure it is in the PATH?

**Comment by peter-ch** [comment]
Well, at the same command prompt "node" works, I can confirm it's in the PATH variable (at least the Windows way, I'm not sure how to attach a screenshot but I can tell you it's totally there ( C:\Program Files\nodejs\ is the last entry).

**Comment by peter-ch** [comment]
$ echo $PATH
/c/Users/spook/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/spook/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/cmd:/c/Boost/lib:/c/MinGW/x86_64-w64-mingw32/bin:/c/MinGW/x86_64-w64-mingw32/lib:/c/Python36/DLLs:/c/Python36:/c/MinGW/bin:/mingw64/bin:/mingw64/lib:/usr/bin:/c/Program Files/nodejs:/c/Python36/Scripts:/c/Python36:/c/Boost/lib:/c/MinGW/x86_64-w64-mingw32/bin:/c/Users/spook/AppData/Roaming/npm:/usr/bin/vendor_perl:/usr/bin/core_perl

**Comment by jasongrout** [comment]
oh, it looks like you are using cygwin or something? Does it work at the windows shell? I think python does some tricks there with windows and looking for nodejs.exe, etc.

**Comment by peter-ch** [comment]
I have MinGW installed and I compile things with it, and things work overall. I haven't tried the Windows shell though, I use Git Bash as it provides handy Unix shell commands for work. Could this be the issue? But it worked previously there. I don't know what happened, it suddenly stopped working. Plus, this command no longer works: "jupyter lab". I have to do "jupyter-lab" now instead.

**Comment by jasongrout** [comment]
Great questions, and out of my experience now. I know I've had issues with trying to run things from the git bash shell, and I try to run build steps from the windows shell now.

**Comment by peter-ch** [comment]
FYI the same thing happened in the Windows command prompt as well, I just tried.

**Comment by jasongrout** [comment]
And `echo %PATH%` shows the directory with nodejs.exe in it? Running node from that windows prompt works fine?

**Comment by peter-ch** [comment]
It doesn't ruin all work though, I mean I can still access jupyterlab via "jupyter-lab" and things generally work, I just can't run the build anymore, and with that all extensions I'd like to add.

**Comment by peter-ch** [comment]
Yes, echo %PATH% shows this:

C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Boost\lib;C:\MinGW\x86_64-w64-mingw32\bin;C:\MinGW\x86_64-w64-mingw32\lib;C:\Python36\DLLs;C:\Python36;C:\MinGW\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\mingw64\lib;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Python36\Scripts\;C:\Python36\;C:\Boost\lib;C:\MinGW\x86_64-w64-mingw32\bin;C:\Users\spook\AppData\Roaming\npm

**Comment by jasongrout** [comment]
> Running node from that windows prompt works fine?

And this works too? `node` at the windows prompt?

**Comment by peter-ch** [comment]
Yes. I do nothing else, I just enter "cmd" in the start menu, I'm in the shell, I enter "node" and I get this:
> 
so I'm in, right? I assume it means it works.

**Comment by peter-ch** [comment]
Sorry, this must have been formatted out, it's the "greater than" character.

**Comment by jasongrout** [comment]
> so I'm in, right? I assume it means it works.

I think so. 

I think at this point someone more experienced with Windows is going to have to chime in. If you figure it out from google or stackexchange or something, please post back here so we can all learn.

**Comment by peter-ch** [comment]
I'm afraid I'm coming here after already doing Google searches on it and found nothing helpful. I only submit bug reports when I exhaust the other options.

**Comment by jasongrout** [comment]
> I'm afraid I'm coming here after already doing Google searches on it and found nothing helpful. I only submit bug reports when I exhaust the other options.

Thanks, we appreciate that! Hopefully someone more experienced with Windows node installations can chime in.

**Comment by peter-ch** [comment]
I found something that might help. When I append ".exe" to "node" in the command you gave me, it worked. But only with .exe appended. Can I do this in jupyterlab's code and where?

`Peter@Laptop MINGW64 ~
$ python -c "import shutil; print(shutil.which('node'))"
None

Peter@Laptop MINGW64 ~
$ python -c "import shutil; print(shutil.which('node.exe'))"
C:\Program Files\nodejs\node.exe`

**Comment by peter-ch** [comment]
This hack helped me (the first line I inserted in jupyterlab_server.process.which):

`def which(command, env=None):
    """Get the full path to a command.

    Parameters
    ----------
    command: str
        The command name or path.
    env: dict, optional
        The environment variables, defaults to `os.environ`.
    """
    if command[-4:] != '.exe': command += '.exe'
`

**Comment by jasongrout** [comment]
According to https://docs.python.org/3/library/shutil.html#shutil.which:

> On Windows, the current directory is always prepended to the path whether or not you use the default or provide your own, which is the behavior the command shell uses when finding executables. Additionally, when finding the cmd in the path, the PATHEXT environment variable is checked. For example, if you call shutil.which("python"), which() will search PATHEXT to know that it should look for python.exe within the path directories. For example, on Windows:

So it is odd it did not search for `.exe` automatically. What is your PATHEXT variable?

**Comment by peter-ch** [comment]
`$ echo $PATHEXT
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.DLL;
`
Maybe it's case sensitive?

**Comment by peter-ch** [comment]
By the way, it did work with my hack alright, but now jupyter-labextension says:

`An error occured.
ValueError: The command was not found or was not executable: npm.exe.
`
But the whole point was so I can install extensions so I didn't accomplish anything. npm.exe doesn't exist, the file has .cmd extension.. and another file with the same name has no extension at all.

**Comment by peter-ch** [comment]
Ok, so this is my solution. First, add ".;" to PATHEXT. Then, in jupyterlab_server.process.which insert this code on top:

`if 'npm' in command:
        pass
 else:
        if command[-4:] != '.exe': command += '.exe'`

And it all works.
