### ISSUE TITLE
Cannot install dev build on windows

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7678]
## Description

In a clean conda environment on windows, installing the dev build errors out looking for `jlpm` in the `pip install` step

## Reproduce

On windows, in a fresh checkout of the jupyterlab git repo:

1.` conda create -n devjlab notebook nodejs`
2. `conda activate devjlab`
3. `pip install -ve .`

I get this error in the pip install step:

```
Installing collected packages: py, atomicwrites, pyparsing, packaging, pluggy, pytest, html5lib, docutils, pytest-check-links, idna, urllib3, chardet, requests, jupyterlab
  Running setup.py develop for jupyterlab
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\[snip]\Miniconda3\envs\devjlab\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\[snip]\\projects\\jupyterlab\\setup.py'"'"'; __file__='"'"'C:\\Users\\[snip]\\projects\\jupyterlab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\[snip]\projects\jupyterlab\
    Complete output (74 lines):
    running develop
    > node C:\Users\[snip]\projects\jupyterlab\jupyterlab\staging\yarn.js
    yarn install v1.15.2
    [1/4] Resolving packages...
    success Already up-to-date.
    $ node scripts/ensure-buildutils.js
    npm WARN npm npm does not support Node.js v13.0.0
    npm WARN npm You should probably upgrade to a newer version of node as we
    npm WARN npm can't make any promises that npm will work with this version.
    npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
    npm WARN npm You can find the latest version at https://nodejs.org/
    npm WARN npm npm does not support Node.js v13.0.0
    npm WARN npm You should probably upgrade to a newer version of node as we
    npm WARN npm can't make any promises that npm will work with this version.
    npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
    npm WARN npm You can find the latest version at https://nodejs.org/

    > @ build C:\Users\[snip]\projects\jupyterlab
    > jlpm run build:dev

    'jlpm' is not recognized as an internal or external command,
    operable program or batch file.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @ build: `jlpm run build:dev`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @ build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\[snip]\projects\jlabremix\jlabapp\npm-cache\_logs\2019-12-21T13_17_59_833Z-debug.log
    child_process.js:642
        throw err;
        ^

    Error: Command failed: npm run build
        at checkExecSyncError (child_process.js:603:11)
        at Object.execSync (child_process.js:639:15)
        at Object.<anonymous> (C:\Users\[snip]\projects\jupyterlab\scripts\ensure-buildutils.js:56:16)
        at Module._compile (internal/modules/cjs/loader.js:958:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
        at Module.load (internal/modules/cjs/loader.js:813:32)
        at Function.Module._load (internal/modules/cjs/loader.js:725:14)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
        at internal/main/run_main_module.js:17:11 {
      status: 1,
      signal: null,
      output: [ null, null, null ],
      pid: 9468,
      stdout: null,
      stderr: null
    }
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\[snip]\projects\jupyterlab\setup.py", line 177, in <module>
        setup(**setup_args)
      File "C:\Users\[snip]\Miniconda3\envs\devjlab\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\[snip]\Miniconda3\envs\devjlab\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\[snip]\Miniconda3\envs\devjlab\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\[snip]\Miniconda3\envs\devjlab\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\[snip]\projects\jupyterlab\setup.py", line 102, in run
        run(npm, cwd=HERE)
      File "C:\Users\[snip]\projects\jupyterlab\setupbase.py", line 221, in run
        return subprocess.check_call(cmd, **kwargs)
      File "C:\Users\[snip]\Miniconda3\envs\devjlab\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\[snip]\\Miniconda3\\envs\\devjlab\\node.EXE', 'C:\\Users\\[snip]\\projects\\jupyterlab\\jupyterlab\\staging\\yarn.js']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\[snip]\Miniconda3\envs\devjlab\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\[snip]\\projects\\jupyterlab\\setup.py'"'"'; __file__='"'"'C:\\Users\\[snip]\\projects\\jupyterlab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
## Expected behavior

jupyterlab to install

## Context

- Operating System and version: Windows 10
- Browser and version: N/A
- JupyterLab version: current master

**Comment by jasongrout** [comment]
Weird, this seems to work now. Closing, and I'll reopen if I see it again.
