### ISSUE TITLE
multi-key shortcuts with different modifiers in each don't work

### ISSUE THREAD

**Issue by amosbird** [jupyterlab/jupyterlab#7702]
## Description

```
commands.addKeyBinding({
    selector: '.jp-Notebook.jp-mod-editMode',
    keys: ['Ctrl C', 'Shift P'], // <<--- doesn't work
    command: 'paste-above-cell-and-edit'
});

commands.addKeyBinding({
    selector: '.jp-Notebook.jp-mod-editMode',
    keys: ['Ctrl C', 'Ctrl P'], // <<--- works
    command: 'paste-above-cell-and-edit'
});


{
    "shortcuts": [
                {
            "command": "notebook:extend-marked-cells-above",
            "keys": [
                "Ctrl Shift D", "Ctrl Shift F"  // works too
            ],
            "selector": ".jp-Notebook:focus"
        },
    ]
}
```
@telamonian mentioned in gitter that "It looks like we don't support multi-key shortcuts in which you have to change modifier keys."

**Comment by jasongrout** [comment]
Did you happen to try with the latest 2.0 beta? There has been some work recently with the keyboard shortcut processing.

**Comment by amosbird** [comment]
Not yet, can I grab 2.0 beta via pip install?

**Comment by jasongrout** [comment]
Yes, `pip install --pre jupyterlab`.

**Comment by amosbird** [comment]
Hmm, is this expected error?

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'vega-embed' in '/home/amos/.local/share/jupyter/lab/staging/node_modules/@jupyterlab/vega5-extension/lib'
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /home/amos/.local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
```

**Comment by jasongrout** [comment]
yes, please don't try to build, that is a known problem with the beta. But you should be able to set keyboard shortcuts in the settings to test things.

**Comment by amosbird** [comment]
It still doesn't work in 2.0 beta

**Comment by markellekelly** [comment]
The problem seems to be with lumino, which doesn't currently support releasing a modifier mid-shortcut, regardless of whether you use two different modifiers. (e.g., ```['Ctrl C', 'Ctrl P']``` doesn't work if you press Ctrl+C, release, then press Ctrl+P.)
Currently, whenever all keys are released, ```keystroke``` is empty, causing the pending state to be cleared:
https://github.com/jupyterlab/lumino/blob/3b93496b80e1e681af112e6184ef5791c5ad06fc/packages/commands/src/index.ts#L454-L462
This means lumino stops keeping track of the keys already pressed, so a match with the existing shortcut never happens. To fix this, I think we'd also have to allow releasing all keys in the middle of other shortcuts (e.g. ```['Ctrl C', 'Ctrl P']```). Is this desired behavior?

**Comment by amosbird** [comment]
>  To fix this, I think we'd also have to allow releasing all keys in the middle of other shortcuts

I think so. And it would help make  `['Ctrl C', 'Shift P']` work

**Comment by jasongrout** [comment]
I think a fix in Lumino to this would be to check right after this if the key is a modifier key, and if it is, return immeditately

https://github.com/jupyterlab/lumino/blob/8c253bea28fb9584adc65e0d5af4e6bec2d25659/packages/commands/src/index.ts#L449-L452

**Comment by jasongrout** [comment]
Looking at the code, does Lumino also have a problem with this shortcut? `['Ctrl C', 'Ctrl Shift P']`, even if control is held down? I think pressing the shift for the second key would trigger the emptying the pending state?

**Comment by amosbird** [comment]
> does Lumino also have a problem with this shortcut? 

I don't know how to verify that.

**Comment by jasongrout** [comment]
For Lumino changes, I think it would be enough to:

1. Extend keyboard layouts to include a separate section for modifier key keycodes (or maybe we just call them ignored keycodes? the idea is that we ignore them in the processing)
2. Extend the IKeyboardLayout with functions to test if a key is ignored, perhaps `isIgnoredKey` to mirror `isValidKey`?
3. Use this function to shortcut return at https://github.com/jupyterlab/lumino/blob/8c253bea28fb9584adc65e0d5af4e6bec2d25659/packages/commands/src/index.ts#L449-L452

**Comment by jasongrout** [comment]
> Currently, whenever all keys are released, `keystroke` is empty, causing the pending state to be cleared:

If I'm reading the code correctly, it's not that the key was released, it's that a key not in the keyboard layout was pressed (in your example, this would be the modifier shift key in the second chord of the shortcut).

**Comment by amosbird** [comment]
I'm afraid patching Lumino is beyond my abilities. I would love to help testing.
