### ISSUE TITLE
Install with Previous Jupyter Notebook

### ISSUE THREAD

**Issue by bakakouhai** [jupyterlab/jupyterlab#7716]
Hello.

I installed Jupyter Notebook via ubuntu repository (I am on Pop_OS 18.04) and want to enable jupyter lab. I can install Jupyterlab via pip3, but I want to install it this way to avoid dual package manager.

Typing 
`jupyter serverextension enable --py jupyterlab --sys-prefix`
on terminal returned:
```
Traceback (most recent call last):
  File "/usr/bin/jupyter-serverextension", line 11, in <module>
    load_entry_point('notebook==5.2.2', 'console_scripts', 'jupyter-serverextension')()
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/notebook/serverextensions.py", line 293, in start
    super(ServerExtensionApp, self).start()
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/lib/python3/dist-packages/notebook/serverextensions.py", line 210, in start
    self.toggle_server_extension_python(arg)
  File "/usr/lib/python3/dist-packages/notebook/serverextensions.py", line 199, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/usr/lib/python3/dist-packages/notebook/serverextensions.py", line 327, in _get_server_extension_metadata
    m = import_item(module)
  File "/usr/lib/python3/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'jupyterlab'
```
Any thought please?

Kind regards,
Iwan

**Comment by bakakouhai** [comment]
Moved to [discourse](https://discourse.jupyter.org/t/install-jupyterlab-with-previous-jupyter-noteboook/2978).

Kind regards,
Iwan
