### ISSUE TITLE
JupyterLab not recognizing nodejs and npm installations on Mac

### ISSUE THREAD

**Issue by lwerner101** [jupyterlab/jupyterlab#7741]
Hi,

I am a bit green and have minimal experience so apologies if this issue is simple. I am having trouble opening `JupyterLab` (1.0.2) after installing `nodejs` (13.5.0) and `npm` on Mac (10.15.2). When attempting to open, I get this error:

Traceback (most recent call last):
File "/Applications/anaconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
value = obj._trait_values[self.name]
KeyError: 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Applications/anaconda3/bin/jupyter-lab", line 6, in
from jupyterlab.labapp import main
File "/Applications/anaconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 40, in
app_version = get_app_version()
File "/Applications/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 541, in get_app_version
app_options, app_dir=app_dir, core_config=core_config))
File "/Applications/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 582, in init
self.registry = options.registry
File "/Applications/anaconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in get
return self.get(obj, cls)
File "/Applications/anaconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
value = self._validate(obj, dynamic_default())
File "/Applications/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 343, in _default_registry
config = _yarn_config(self.logger)["yarn config"]
File "/Applications/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1765, in _yarn_config
node = which('node')
File "/Applications/anaconda3/lib/python3.7/site-packages/jupyterlab_server/process.py", line 59, in which
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

I downloaded the latest version of nodejs from their website, so I am unsure how to fix this issue. Again, I apologize for my lack of knowledge.

**Comment by Juan-132** [comment]
Could you try installing NodeJS with Conda instead? `conda install nodejs`

**Comment by lwerner101** [comment]
That worked, thanks!!
