### ISSUE TITLE
500 after uninstalling via Extension Manager

### ISSUE THREAD

**Issue by HashRocketSyntax** [jupyterlab/jupyterlab#7802]
After **uninstalling** the plotly extension using the **Extension Manager** UI my build failed. Thankfully, this was in a docker env.

Now I am having a similar issue on my machine after having uninstalled the tensorboard extension using the UI (screenshot and error message below).

It's like Jupyter is looking for the extension even though it was uninstalled - as if the uninstallation did not remove it from some registry. 

What's weird is if I now try to manually uninstall the extension, it says it doesn't exist.

---

**Error message when starting Jupyter from command line:**
```
$ 

[E 02:08:50.436 NotebookApp] Uncaught exception GET /lab/api/build?1579572529830 (::1)

    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/lab/api/build?1579572529830', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/jupyterlab/handlers/build_handler.py", line 121, in get
        data = yield self.builder.get_status()
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/jupyterlab/handlers/build_handler.py", line 43, in get_status
        self.app_dir, self.log, self.core_config)
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/Users/layne/.pyenv/versions/3.7.3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/jupyterlab/handlers/build_handler.py", line 96, in _run_build_check
        app_dir=app_dir, logger=logger, core_config=core_config))
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/jupyterlab/commands.py", line 507, in build_check
        return handler.build_check()
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/jupyterlab/commands.py", line 760, in build_check
        new_package = self._get_package_template(silent=fast)
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/jupyterlab/commands.py", line 1241, in _get_package_template
        data['jupyterlab']['mimeExtensions'].pop(item)
    KeyError: 'jupyterlab_tensorboard'


[W 02:08:50.437 NotebookApp] Unhandled error


[E 02:08:50.438 NotebookApp] 

{
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Authorization": "token 7da93c1fcddb5dd07459bd4fde0a430d1437eefdae4c0144",
      "X-Xsrftoken": "2|4e95d663|4b5c59216ce2e3c50b3f0f7fc785cfe4|1578256910",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8889/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "csrftoken=c9gQNC4zugwBa2Luk5WBr3YYLNgf6W5t90m7H4LV0HXkt7Koi5l3mPf16Q7zc1Wj; _xsrf=2|4e95d663|4b5c59216ce2e3c50b3f0f7fc785cfe4|1578256910; username-localhost-8890=\"2|1:0|10:1578261163|23:username-localhost-8890|44:MTRhN2VlNzMzNGVhNDQ5ZjllNDg5MTMzMmEwNDY4ZDc=|a6037a3589b7783d605601e3cf2792e112d54c8072d2f1d6813726f9b6a7633a\"; username-localhost-8891=\"2|1:0|10:1578261380|23:username-localhost-8891|44:NjIzOGNmNzZmYTNlNGE2Mjg4OTMyMGFkMTcyNmE2OWU=|52f88509bafab5b93ffc9b9a515ff5e968b380c0809617663f529e434f67e11a\"; username-localhost-8892=\"2|1:0|10:1578261474|23:username-localhost-8892|44:NjZkNTQ3ZmI0OTIzNDZiMmE2NmI5N2M4ZmZiMDY2ODU=|55c3eee7644ac1b7895011835606db14c73e135a324dc1b8469e2706d33b53de\"; username-localhost-8872=\"2|1:0|10:1578261644|23:username-localhost-8872|44:MGViZTU0NzE2NzllNGRiNDg3YzQzMDQwNjMxNWU1NDU=|1fcbc477e2351ee2f8ea2c07f02a743c1fec7b9a0e94414a07d2b04b6b43451e\"; username-localhost-8841=\"2|1:0|10:1578269735|23:username-localhost-8841|44:ZGQ5YjBiYzlkY2FjNGFmMDhiM2Q1ZjQ4ZjhiNzBlNzM=|f9d23f28bd199824f92c980f7f9269633ec8cdd474df28314935c7e8adee0fe2\"; username-localhost-8823=\"2|1:0|10:1578884338|23:username-localhost-8823|44:YmZkNTg5MGJkOGRjNDgyYmI2OGU4N2I4M2YwZTg2OTc=|bb641ce5c1152b18345cacdee4a5d2a1589092949a7efc38ad55362b76b6b3a5\"; username-localhost-8951=\"2|1:0|10:1578884723|23:username-localhost-8951|44:OWZhYThhNTVjM2M3NGU0ZTg4NzY1NGZmYTQ3ZTg4Mzc=|099675a9287d8b54731ac27f9b2421c661c3c7db5ea03ab42e92b179bf98ffe1\"; username-localhost-8903=\"2|1:0|10:1578884942|23:username-localhost-8903|44:NjM1MDlhOGEwZDU2NGY3ODgyOWRhNDFkMTY1MDlhOGY=|f40750a6cd946ef118d353d0a1e977c8264745a348e766f841b37c2c376c8e30\"; username-localhost-8888=\"2|1:0|10:1579571743|23:username-localhost-8888|44:MTJiNTE2MDM0MDc4NDY4NjkxMjU0ZjEwOTMyYWRhMzk=|db4825ac08c8bdf35ebc5e1a1c917c29c36bf846b71b8b119d694bb1d38dc0e1\"; username-localhost-8889=\"2|1:0|10:1579572529|23:username-localhost-8889|44:NTU4ZDk0ZTE2ZGNkNGNlMWI2ZDllNjFjYTBhODUyMDA=|022a160dd4de86ecbf410d8c96a50b6ff69e07007e9d1e28c2b67e45e8422bf9\""
    }
```

**nbextension manager**
```
$ jupyter nbextension uninstall jupyterlab_tensorboard

No installed extension 'jupyterlab_tensorboard' found.
```

**Package Versions**
```
$ pip list
jupyter                           1.0.0
jupyter-client                    5.3.4
jupyter-console                   6.1.0
jupyter-contrib-core              0.3.3
jupyter-core                      4.6.1
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        1.2.4
jupyterlab-server                 1.0.6
```

**JS Output**
![image](https://user-images.githubusercontent.com/16389820/72806505-540ecf00-3c23-11ea-9317-68245210015e.png)

**System**
```
Chrome = Version 79.0.3945.117 (Official Build) (64-bit)
MacOS = Catalina 10.15.2 (19C57)
```

---

If we can get extensions right... jupyter will take over the webapp/ browser world =)

**Comment by blink1073** [comment]
Hi @HashRocketSyntax, are you able to upgrade to JupyterLab 1.2.5 (`pip install -U jupyterlab`)?  It has a fix for this error.

**Comment by HashRocketSyntax** [comment]
@blink1073 Wahoo! Thank you. Progress. 

Now the Extension Manager works again, but I am still getting a soft error.

![image](https://user-images.githubusercontent.com/16389820/72857226-03cb5780-3c8b-11ea-96ef-f26448638b2f.png)

```
[W 01:15:30.843 NotebookApp] Error loading server extension jupyter_tensorboard
    Traceback (most recent call last):
      File "/Users/layne/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/notebook/notebookapp.py", line 1655, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/layne/.pyenv/versions/3.7.3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_tensorboard'
```
I'll take a look what is in those files.

I tried using the UI to reinstall/ uninstall to see if it would overwrite the missing extension, but had no luck.

**Comment by HashRocketSyntax** [comment]
![image](https://user-images.githubusercontent.com/16389820/72858062-8fde7e80-3c8d-11ea-9590-5058e345db2b.png)

I think I found it. Although there are files in that `packages/.../notebook` directory, they are calling a config file in `~/.jupyter`
