### ISSUE TITLE
Building jupyterlab assets: npm dependencies failed to install

### ISSUE THREAD

**Issue by Felihong** [jupyterlab/jupyterlab#7847]
## Description
Hi there, 

I met this error every time when I try to install some Jupyterlab extensions, for instance when installing this theme extension:
```
jupyter labextension install @telamonian/theme-darcula

Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-3t888fua.log
```
Snippet of the log file:
```
cat /tmp/jupyterlab-debug-3t888fua.log

Building jupyterlab assets (build:prod:minimize)
> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.9.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/opt/conda/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: jupyter
```

## Context
- Operating System and version: `Ubuntu bionic 18.04.3`
- Browser and version: `Firefox`
- JupyterLab version: `1.2.5`
- Node version: `v12.14.1`
- npm version: `6.13.4`
- Python version: `3.7.6`

Please note that my Jupyterlab container runs in a `Kubeflow` pod hosted in `GKE`.

Thanks for your help!

**Comment by Felihong** [comment]
Hi again, 

I increased the timeout setting with
```
yarn install --network-timeout 100000
```
in the `staging` directory of the output of `jupyter lab path | grep application`, and the issue seems to be resolved.

**Comment by thirdday** [comment]
I had trouble with this particular package (others were fine) behind my company firewall/proxy.  Increasing the timeout didn't help.  At home with no proxy it worked fine though.
