### ISSUE TITLE
It seems the Jupter Lab can only be started in the Anaconda base environment?

### ISSUE THREAD

**Issue by songyuc** [jupyterlab/jupyterlab#7894]
Hi guys!
Today I tried using a Anaconda environment (not base), to start Jupter Lab,
but it shows,

> (conda-general) songyuc@Eric-Song:~/professional/语义分割/项目/deeplabv3+/deeplabv3+_model/experiment$ jupyter lab
Traceback (most recent call last):
  File "/home/songyuc/software/python/anaconda/anaconda3/envs/conda-general/bin/jupyter", line 11, in <module>
    sys.exit(main())
  File "/home/songyuc/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.7/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/home/songyuc/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.7/site-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-lab` not found.

and I am wondering whether Jupter Lab can only be started in the Anaconda base environment?

Any answer or idea will be appreciated!

**Comment by vidartf** [comment]
Did you install JupyterLab in the new environment? It seems unreliable to start lab in a sub-env if it was only installed in the base env. Generally, it is a good idea to keep the base environment "untouched" if you plan to use other environments, as you can get hard-to-debug cases like this.

Hope this helps!

**Comment by hkennyv** [comment]
hey, i'm having the same issue using [pyenv](https://github.com/pyenv/pyenv). 

```
khuynh@kmba:~ $ which python
/Users/khuynh/.pyenv/shims/python
khuynh@kmba:~ $ which pip
/Users/khuynh/.pyenv/shims/pip
khuynh@kmba:~ $ pip install jupyterlab
Requirement already satisfied: jupyterlab in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (3.0.7)
Requirement already satisfied: packaging in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (20.9)
Requirement already satisfied: jupyterlab-server~=2.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (2.1.4)
Requirement already satisfied: jinja2>=2.10 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (2.11.3)
Requirement already satisfied: tornado>=6.1.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (6.1)
Requirement already satisfied: nbclassic~=0.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (0.2.6)
Requirement already satisfied: jupyter-core in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (4.7.1)
Requirement already satisfied: ipython in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (7.20.0)
Requirement already satisfied: jupyter-server~=1.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab) (1.2.2)
Requirement already satisfied: pyparsing>=2.0.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from packaging->jupyterlab) (2.4.7)
Requirement already satisfied: babel in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab-server~=2.0->jupyterlab) (2.9.0)
Requirement already satisfied: json5 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab-server~=2.0->jupyterlab) (0.9.5)
Requirement already satisfied: jsonschema>=3.0.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab-server~=2.0->jupyterlab) (3.2.0)
Requirement already satisfied: requests in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyterlab-server~=2.0->jupyterlab) (2.25.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jinja2>=2.10->jupyterlab) (1.1.1)
Requirement already satisfied: notebook<7 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbclassic~=0.2->jupyterlab) (6.2.0)
Requirement already satisfied: traitlets in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-core->jupyterlab) (5.0.5)
Requirement already satisfied: jedi>=0.16 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (0.18.0)
Requirement already satisfied: pygments in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (2.7.4)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (4.8.0)
Requirement already satisfied: decorator in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (4.4.2)
Requirement already satisfied: pickleshare in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (3.0.14)
Requirement already satisfied: setuptools>=18.5 in ./.pyenv/versions/3.9.1/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython->jupyterlab) (49.2.1)
Requirement already satisfied: backcall in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (0.2.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from ipython->jupyterlab) (0.1.2)
Requirement already satisfied: nbconvert in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (6.0.7)
Requirement already satisfied: jupyter-client>=6.1.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (6.1.11)
Requirement already satisfied: anyio>=2.0.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (2.0.2)
Requirement already satisfied: terminado>=0.8.3 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (0.9.2)
Requirement already satisfied: Send2Trash in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (1.5.0)
Requirement already satisfied: nbformat in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (5.1.2)
Requirement already satisfied: pyzmq>=17 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (22.0.2)
Requirement already satisfied: ipython-genutils in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (0.2.0)
Requirement already satisfied: prometheus-client in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-server~=1.2->jupyterlab) (0.9.0)
Requirement already satisfied: pytz>=2015.7 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from babel->jupyterlab-server~=2.0->jupyterlab) (2021.1)
Requirement already satisfied: six>=1.11.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.0->jupyterlab) (1.15.0)
Requirement already satisfied: attrs>=17.4.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.0->jupyterlab) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.0->jupyterlab) (0.17.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests->jupyterlab-server~=2.0->jupyterlab) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests->jupyterlab-server~=2.0->jupyterlab) (1.26.3)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests->jupyterlab-server~=2.0->jupyterlab) (4.0.0)
Requirement already satisfied: ipykernel in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from notebook<7->nbclassic~=0.2->jupyterlab) (5.4.3)
Requirement already satisfied: argon2-cffi in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from notebook<7->nbclassic~=0.2->jupyterlab) (20.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jedi>=0.16->ipython->jupyterlab) (0.8.1)
Requirement already satisfied: ptyprocess>=0.5 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython->jupyterlab) (0.7.0)
Requirement already satisfied: wcwidth in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyterlab) (0.2.5)
Requirement already satisfied: bleach in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (3.3.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (0.5.1)
Requirement already satisfied: entrypoints>=0.2.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (0.3)
Requirement already satisfied: jupyterlab-pygments in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (0.1.2)
Requirement already satisfied: pandocfilters>=1.4.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (1.4.3)
Requirement already satisfied: defusedxml in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (0.6.0)
Requirement already satisfied: mistune<2,>=0.8.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (0.8.4)
Requirement already satisfied: testpath in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab) (0.4.4)
Requirement already satisfied: python-dateutil>=2.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jupyter-client>=6.1.1->jupyter-server~=1.2->jupyterlab) (2.8.1)
Requirement already satisfied: sniffio>=1.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from anyio>=2.0.2->jupyter-server~=1.2->jupyterlab) (1.2.0)
Requirement already satisfied: cffi>=1.0.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from argon2-cffi->notebook<7->nbclassic~=0.2->jupyterlab) (1.14.4)
Requirement already satisfied: webencodings in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from bleach->nbconvert->jupyter-server~=1.2->jupyterlab) (0.5.1)
Requirement already satisfied: nest-asyncio in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.2->jupyterlab) (1.5.1)
Requirement already satisfied: async-generator in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.2->jupyterlab) (1.10)
Requirement already satisfied: pycparser in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook<7->nbclassic~=0.2->jupyterlab) (2.20)
Installing collected packages: idna
  Attempting uninstall: idna
    Found existing installation: idna 3.1
    Uninstalling idna-3.1:
      Successfully uninstalled idna-3.1
Successfully installed idna-2.10
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/khuynh/.pyenv/versions/3.9.1/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
khuynh@kmba:~ $ python -m jupyter lab
Traceback (most recent call last):
  File "/Users/khuynh/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/khuynh/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/khuynh/.pyenv/versions/3.9.1/lib/python3.9/site-packages/jupyter.py", line 4, in <module>
    main()
  File "/Users/khuynh/.pyenv/versions/3.9.1/lib/python3.9/site-packages/jupyter_core/command.py", line 285, in main
    command = _jupyter_abspath(subcommand)
  File "/Users/khuynh/.pyenv/versions/3.9.1/lib/python3.9/site-packages/jupyter_core/command.py", line 124, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-lab` not found.
khuynh@kmba:~ $
```

**Comment by hkennyv** [comment]
I was able to fix this issue on my machine by uninstalling and re-installing all of the `jupyter-xxx` packages. It _seems_ like pyenv was not registering their shims until i installed them again for some reason.

**Comment by joehalliwell** [comment]
You can use [pipx](https://pypa.github.io/pipx/) to install Jupyter in its own isolated environment. This will add the Jupyter binaries to your path without modifying your base/default Python environment.

**Comment by songyuc** [comment]
你好，您的邮件我已经收到，谢谢您！~O(∩_∩)O~                                                    宋玉成
