### ISSUE TITLE
Build failing because of ensure-max-old-space

### ISSUE THREAD

**Issue by santiagobasulto** [jupyterlab/jupyterlab#7907]
(I'm using Jupyter Lab 1.2.6)

I was just trying to install [nglview](https://github.com/arose/nglview) with their instructions: 

```bash
$ pip install nglview==2.6.9
$ jupyter-labextension install @jupyter-widgets/jupyterlab-manager --no-build
$ jupyter-labextension install  nglview-js-widgets@2.6.9 --no-build
$ jupyter nbextension enable --py nglview
$ jupyter nbextension enable --py widgetsnbextension

$ jupyter lab build
```

but it fails given the ensure-max-old-space check (see the full log at the bottom of this issue).

I saw a few issues posted, and also the PR #7201  that was merged that seemed to resolve the issue by allowing the user to pass NODE_OPTIONS. But neither option is working for me (I have 32GB of RAM, should be enough right?): `NODE_OPTIONS="--max_old_space_size=4096" jupyter lab build --dev-build=False --minimize=True`

If I disable the minimization (`jupyter lab build --minimize=False`) it works.

```
[LabBuildApp] Building in /usr/local/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v13.9.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /usr/local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.75s.

[LabBuildApp] > node /usr/local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ /usr/local/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 0.57s.

[LabBuildApp] > node /usr/local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:632
    throw err;
    ^

Error: Command failed: /usr/local/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: null,
  signal: 'SIGKILL',
  output: [ null, null, null ],
  pid: 2018,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/usr/local/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/usr/local/lib/python3.8/site-packages/jupyterlab/labapp.py", line 97, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/usr/local/lib/python3.8/site-packages/jupyterlab/commands.py", line 458, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/usr/local/lib/python3.8/site-packages/jupyterlab/commands.py", line 669, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by jasongrout** [comment]
Can you upgrade node? IIRC, the newest version of node automatically uses the space it needs.

**Comment by santiagobasulto** [comment]
Ah! I will give it a try right away, thanks.

**Comment by santiagobasulto** [comment]
Node version is 13.9, latest. Still failing 😔.

**Comment by santiagobasulto** [comment]
I've solved this by just not-minimizing the build, which I assume results in large js files (I haven't tested it yet). Is there anyway to either a) fix this issue? or b) minimize AFTER the build (maybe with some other external tool?)

**Comment by santiagobasulto** [comment]
I just made a quick test and minified `vendors~main.<hash>.js` "manually" (using uglify-js) and it worked, it reduced 30% of the total size. The vendors file is ES6, so I had to try the now unsupported [uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony), but I could try transpiling with babel and then applying UglifyJS3. Can you please tell me if the following logic makes sense:

```
1. build JupyterLab without minifying (jupyter lab build --dev-build=False --minimize=False)
2. assume /usr/local/share/jupyter/lab/static is the only place statics are kept
3. babel `vendors~main.<hash>.js` -> `vendors~main.<hash>.es5.js` 
4. uglifyjs `vendors~main.<hash>.es5.js` -o `vendors~main.<hash>.min.js`
```

Does this make sense?

**Comment by marimeireles** [comment]
I was having the same issue with my [repo](https://github.com/QuantStack/pyls-memestra) and turning off the `--minimize=False` fixed for me.

**Comment by brockcraft** [comment]
This also worked on my Jupyter Hub install. Was trying to set up nodejs and the lab extensions for plotly and the labextensions build kept failing. Setting the lab extension build option to `--minimize=False` worked.
