### ISSUE TITLE
installation of @jupyterlab/celltags@2.0.0 failed with error:  ValueError: "@jupyterlab/celltags" is not a valid extension: : No `jupyterlab` key

### ISSUE THREAD

**Issue by tarrade** [jupyterlab/jupyterlab#7969]
## Description

jupyter labextension install @jupyterlab/celltags --no-build --debug

is crashing with the following message:
```

  File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 1514, in _install_extension
     raise ValueError(msg % (extension, '\n'.join(messages)))

 ValueError: "@jupyterlab/celltags" is not a valid extension:
 No `jupyterlab` key

```

## Reproduce

I am buidling a docker images in which Anaconda is installed and I am installing some jupyter lab extensions. Only celltag cannot be installed properly (over 10  jupyter lab extensions). The code is here:
https://github.com/tarrade/proj_custom_ai_platform_notebook/blob/master/docker/derived-pytorch-cpu/Dockerfile

## Expected behavior
I am expecting to have the following working:
`jupyter labextension install @jupyterlab/celltags --no-build --debug`

## Context

- Operating System and version: Ubuntu 18.04.4 LTS 
- JupyterLab version: jupyterlab=1.2.6 with python 3.7.6

full python dependency can be found here:
https://github.com/tarrade/proj_custom_ai_platform_notebook/blob/master/env/base.yml

Logfile:

```
Step #7 - "Build the Docker image":  ---> Running in a7e925f190ce
Step #7 - "Build the Docker image": [LabCleanApp] Cleaning /opt/conda/envs/jupyter-notebook/share/jupyter/lab...
Step #7 - "Build the Docker image": [LabCleanApp] Success!
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": Removing intermediate container a7e925f190ce
Step #7 - "Build the Docker image":  ---> 116eaa9c9365
Step #7 - "Build the Docker image": Step 44/89 : RUN jupyter labextension update --all
Step #7 - "Build the Docker image":  ---> Running in afc92529e189
Step #7 - "Build the Docker image": Extension '@jupyterlab/git' already up to date
Step #7 - "Build the Docker image": Extension 'nbdime-jupyterlab' already up to date
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": -\|/-\|/-\|/-\|/--\|/-\|/-\|
Step #7 - "Build the Docker image": Removing intermediate container afc92529e189
Step #7 - "Build the Docker image":  ---> ae478e1e2898
Step #7 - "Build the Docker image": Step 45/89 : RUN jupyter labextension install @jupyterlab/celltags --no-build --debug
Step #7 - "Build the Docker image":  ---> Running in 9ba6fdac2720
Step #7 - "Build the Docker image": ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['/bin/bash', '-c', 'jupyter labextension install @jupyterlab/celltags --no-build --debug']' command failed.  (See above for error)
Step #7 - "Build the Docker image": Searching ['/', '/root/.jupyter', '/opt/conda/envs/jupyter-notebook/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Step #7 - "Build the Docker image": Looking for jupyter_config in /etc/jupyter
Step #7 - "Build the Docker image": Looking for jupyter_config in /usr/local/etc/jupyter
Step #7 - "Build the Docker image": Looking for jupyter_config in /opt/conda/envs/jupyter-notebook/etc/jupyter
Step #7 - "Build the Docker image": Looking for jupyter_config in /root/.jupyter
Step #7 - "Build the Docker image": Looking for jupyter_config in /
Step #7 - "Build the Docker image": Yarn configuration loaded.
Step #7 - "Build the Docker image": Node v13.9.0
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": > /opt/conda/envs/jupyter-notebook/bin/npm pack @jupyterlab/celltags
Step #7 - "Build the Docker image": npm notice 
Step #7 - "Build the Docker image": npm notice 📦  @jupyterlab/celltags@2.0.0
Step #7 - "Build the Docker image": npm notice === Tarball Contents === 
Step #7 - "Build the Docker image": npm notice 1.7kB LICENSE           
Step #7 - "Build the Docker image": npm notice 1.4kB style/base.css    
Step #7 - "Build the Docker image": npm notice 640B  style/index.css   
Step #7 - "Build the Docker image": npm notice 4.4kB lib/addwidget.js  
Step #7 - "Build the Docker image": npm notice 79B   lib/index.js      
Step #7 - "Build the Docker image": npm notice 7.3kB lib/tool.js       
Step #7 - "Build the Docker image": npm notice 3.9kB lib/widget.js     
Step #7 - "Build the Docker image": npm notice 1.4kB package.json      
Step #7 - "Build the Docker image": npm notice 146B  README.md         
Step #7 - "Build the Docker image": npm notice 1.5kB lib/addwidget.d.ts
Step #7 - "Build the Docker image": npm notice 79B   lib/index.d.ts    
Step #7 - "Build the Docker image": npm notice 2.3kB lib/tool.d.ts     
Step #7 - "Build the Docker image": npm notice 1.5kB lib/widget.d.ts   
Step #7 - "Build the Docker image": npm notice === Tarball Details === 
Step #7 - "Build the Docker image": npm notice name:          @jupyterlab/celltags                    
Step #7 - "Build the Docker image": npm notice version:       2.0.0                                   
Step #7 - "Build the Docker image": npm notice filename:      jupyterlab-celltags-2.0.0.tgz           
Step #7 - "Build the Docker image": npm notice package size:  6.1 kB                                  
Step #7 - "Build the Docker image": npm notice unpacked size: 26.2 kB                                 
Step #7 - "Build the Docker image": npm notice shasum:        1b73e15fa4eb5f44db07581be4df0df508ae5373
Step #7 - "Build the Docker image": npm notice integrity:     sha512-qwD+Yfw/4Busr[...]IzfH0k93Nr5YQ==
Step #7 - "Build the Docker image": npm notice total files:   13                                      
Step #7 - "Build the Docker image": npm notice 
Step #7 - "Build the Docker image": jupyterlab-celltags-2.0.0.tgz
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": Traceback (most recent call last):
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
Step #7 - "Build the Docker image":     yield
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
Step #7 - "Build the Docker image":     ans = self.run_task()
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in run_task
Step #7 - "Build the Docker image":     for i, arg in enumerate(self.extra_args)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
Step #7 - "Build the Docker image":     for i, arg in enumerate(self.extra_args)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 398, in install_extension
Step #7 - "Build the Docker image":     return handler.install_extension(extension, pin=pin)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 611, in install_extension
Step #7 - "Build the Docker image":     info = self._install_extension(extension, tempdir, pin=pin)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 1514, in _install_extension
Step #7 - "Build the Docker image":     raise ValueError(msg % (extension, '\n'.join(messages)))
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": ValueError: "@jupyterlab/celltags" is not a valid extension:
Step #7 - "Build the Docker image": No `jupyterlab` key
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": Exiting application: jupyter
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": -\|/-\|/-\|An error occured.
Step #7 - "Build the Docker image": ValueError: "@jupyterlab/celltags" is not a valid extension:
Step #7 - "Build the Docker image": No `jupyterlab` key
Step #7 - "Build the Docker image": See the log file for details:  /tmp/jupyterlab-debug-yrsijgg0.log
```

**Comment by tarrade** [comment]
Just to add that the previous stable tag 0.2.0 is working in the same setup:
`jupyter labextension install @jupyterlab/celltags@0.2.0 --no-build --debug`

**Comment by jtpio** [comment]
Would it be possible to upgrade to JupyterLab 2.0? (which includes the `@jupyterlab/celltags` extension)

**Comment by tarrade** [comment]
Hi @jtpio, I updated  Jupyterlab to 2.0.0 and I have the same exact issue to install:
jupyter labextension install @jupyterlab/celltags --no-build --debug
 (plus all other extension crashing).

What you are saying is that this extension should be installed by default, right ? I don't see it installed by default:

```
jupyter labextension list
app dir: /opt/conda/envs/jupyter-notebook/share/jupyter/lab
        @jupyterlab/git v0.9.0  enabled   X
         nbdime-jupyterlab v1.0.0  enabled   X

    The following extension are outdated:
         @jupyterlab/git
         nbdime-jupyterlab
```

**Comment by jtpio** [comment]
Yes it's part of JupyterLab 2.0 core, so no need to install it manually.

But the core extensions don't show up with the `jupyter labextension list` command.

Also since the 2.0 is quite recent all third-party extensions might not be compatible yet.
