### ISSUE TITLE
JupyterLab Error Message

### ISSUE THREAD

**Issue by al3hishek** [jupyterlab/jupyterlab#8282]
Hi All,

I get this huge error message every time I open jupyterlab. 

[I 10:03:39.112 LabApp] The port 8888 is already in use, trying another port.
[I 10:03:39.114 LabApp] The port 8889 is already in use, trying another port.
[W 10:03:39.148 LabApp] Error loading server extension jupyter_http_over_ws
Traceback (most recent call last):
File "C:\Users\abhishek.shetty\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1670, in init_server_extensions
mod = importlib.import_module(modulename)
File "C:\Users\abhishek.shetty\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jupyter_http_over_ws'
[I 10:03:39.243 LabApp] JupyterLab extension loaded from C:\Users\abhishek.shetty\Anaconda3\lib\site-packages\jupyterlab
[I 10:03:39.243 LabApp] JupyterLab application directory is C:\Users\abhishek.shetty\Anaconda3\share\jupyter\lab
[I 10:03:39.300 LabApp] Serving notebooks from local directory: C:\Users\abhishek.shetty
[I 10:03:39.300 LabApp] The Jupyter Notebook is running at:
[I 10:03:39.300 LabApp] http://localhost:8890/?token=cd8b71cbfc28e046eda0b4823600ced614c116e78e73c480
[I 10:03:39.300 LabApp] or http://127.0.0.1:8890/?token=cd8b71cbfc28e046eda0b4823600ced614c116e78e73c480
[I 10:03:39.300 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:03:39.514 LabApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/abhishek.shetty/AppData/Roaming/jupyter/runtime/nbserver-20612-open.html
Or copy and paste one of these URLs:
http://localhost:8890/?token=cd8b71cbfc28e046eda0b4823600ced614c116e78e73c480
or http://127.0.0.1:8890/?token=cd8b71cbfc28e046eda0b4823600ced614c116e78e73c480
[W 10:03:43.835 LabApp] Could not determine jupyterlab build status without nodejs
[I 10:03:46.439 LabApp] Kernel started: 8736bd39-1e40-4b20-9f47-588c2e148fbe
Traceback (most recent call last):
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\site-packages\ipykernel\connect.py", line 10, in 
from subprocess import Popen, PIPE
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\subprocess.py", line 126, in 
import threading
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\threading.py", line 8, in 
from traceback import format_exc as _format_exc
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\traceback.py", line 5, in 
import linecache
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\linecache.py", line 11, in 
import tokenize
File "C:\Users\abhishek.shetty\Desktop\Abhishek\Courses\Plural\Building Features from Text Data\tokenize.py", line 1, in 
import nltk
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\site-packages\nltk\__init__.py", line 128, in 
from nltk.collocations import *
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\site-packages\nltk\collocations.py", line 36, in 
from nltk.util import ngrams
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\site-packages\nltk\util.py", line 14, in 
import pydoc
File "C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\pydoc.py", line 75, in 
from traceback import format_exception_only
ImportError: cannot import name 'format_exception_only' from 'traceback' (C:\Users\abhishek.shetty\Anaconda3\envs\newbase\lib\traceback.py)

Can someone help me understand this?

**Comment by FungluiKoo** [comment]
Hi, would you share your system and Jupyterlab version, and other configurations?
By the way, I would suggest to make the post in the following style:

## Description



## Reproduce



1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error '...'



## Expected behavior



## Context



- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
This looks like an error in your environment (not JupyterLab). The error seems to be from nltk importing the pydoc package. You may be able to see it just by starting python from the command line.

You can try reproducing this in a clean environment? Perhaps the problem is a version problem in the libraries and packages you've installed.

**Comment by al3hishek** [comment]
the most stupidest thing..I created a python file called tokenize.py..turns out it conflicts with nltk's tokenize.py and hence this huge mess.. A simple file re-name fixed the thing..Thanks for all your comments.Closing the issue.

**Comment by jasongrout** [comment]
You're definitely not the first person to run into import paths being unexpectedly overridden in Python. I think we all have stories like that (I certainly do!). Glad you figured it out.
