### ISSUE TITLE
Node not found at JupyterLab start up in combination with JupyterHUb

### ISSUE THREAD

**Issue by rragundez** [jupyterlab/jupyterlab#8412]
If JupyterLab + some extension is used in combination with JupyterHub at startup JupyterLab tries to look for nodejs but since JupyterHub hides some environment variables (which of course can be exposed via `c.Spawner.env_keep` but I do not want to do that for security), is does not find`npm`(it is installed as before putting up the service I did jupyter lab build succesfully after installing some extensions), which results in:

```
[E 2020-05-11 22:43:01.588 SingleUserNotebookApp web:1792] Uncaught exception GET /user/rodrigo_agundez/lab/api/extensions?1589236981511 (::ffff:172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:9443', method='GET', uri='/user/rodrigo_agundez/lab/api/extensions?1589236981511', version='HTTP/1.1', remote_ip='::ffff:172.17.0.1')
    Traceback (most recent call last):
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 194, in _load_outdated
        app_options=self.app_options
      File "/opt/miniconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/miniconda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
        return self.__get_result()
      File "/opt/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/miniconda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 541, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1679, in latest_compatible_package_versions
        ret = self._run([which('npm'), 'pack'] + keys, cwd=tempdir)
      File "/opt/miniconda/lib/python3.7/site-packages/jupyterlab_server/process.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
[W 2020-05-11 22:43:01.590 SingleUserNotebookApp handlers:608] Unhandled error
[E 2020-05-11 22:43:01.591 SingleUserNotebookApp log:166] {
      "X-Forwarded-Host": "localhost:9443",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "9443",
      "X-Forwarded-For": "::ffff:172.17.0.1",
      "Cookie": "jupyterhub-user-rodrigo_agundez=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
      "Accept-Language": "en-US,en;q=0.9,nl;q=0.8,es;q=0.7,de;q=0.6,fr;q=0.5",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "http://localhost:9443/user/rodrigo_agundez/lab",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Site": "same-origin",
      "Accept": "*/*",
      "Content-Type": "application/json",
      "Authorization": "token [secret]",
      "X-Xsrftoken": "2|18dc2d27|db49181929c02da7f1a0c38f54a179d7|1587727229",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
      "Connection": "close",
      "Host": "localhost:9443"
    }
```

So i do not want JupyterLab to try to check if my extensions were added to the build, I tried 
```
c.LabApp.tornado_settings = {
    'page_config_data': {
        'buildCheck': False,
        'buildAvailable': False
    }
}
```
in the `jupyterhub_config.py` which accepts as a property of the configuration but the problem persist.
I think is related to #5189, in my case I do not have two Python versions.
BTW it does not happen if I do not install any extension.

**Comment by rragundez** [comment]
Found the problem, in this case if JupyterLab is installed in miniconda or anaconda for example and then nodejs is installed via `conda install nodejs` or using conda-forge all works well using jupyter lab build etc., but the JH starts blocks the PATH environment variable but pipes a minimize version of it. So then nodejs is not in the path as it is in the miniconda/anaconda environment. 
Solution is not to install nodejs there but in the system in my case `yum install nodejs -y`, then it will be in that minimize PATH used by JH.

![image](https://user-images.githubusercontent.com/16643700/81643124-35785200-9425-11ea-8e10-69d6eae64b02.png)
