### ISSUE TITLE
RuntimeError: npm dependencies failed to install

### ISSUE THREAD

**Issue by Spencerai** [jupyterlab/jupyterlab#8423]
failed install the extensions:
"https://registry.npm.taobao.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.13.0.tgz: Request failed "404 Not Found"".

below is the log:
spencer@spencer work % jupyter labextension install @jupyterlab/github
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details: /var/folders/r4/sqyp9pmj7sl8lc7q5grjvdh80000gn/T/jupyterlab-debug-8j8rfory.log

in the log:
Node v12.16.3

Yarn configuration loaded.

/usr/local/bin/npm pack @jupyterlab/github
npm notice
npm notice 📦 @jupyterlab/github@2.0.0
npm notice === Tarball Contents ===
npm notice 2.3kB package.json
npm notice 1.5kB LICENSE
npm notice 6.2kB README.md
npm notice 2.3kB lib/browser.d.ts
npm notice 13.0kB lib/browser.js
npm notice 6.5kB lib/contents.d.ts
npm notice 23.0kB lib/contents.js
npm notice 4.8kB lib/github.d.ts
npm notice 3.1kB lib/github.js
npm notice 251B lib/index.d.ts
npm notice 5.4kB lib/index.js
npm notice 679B schema/drive.json
npm notice 2.4kB style/binder.svg
npm notice 2.7kB style/index.css
npm notice 35.4kB style/octocat_error.png
npm notice 2.1kB style/octocat-dark.svg
npm notice 2.1kB style/octocat-light.svg
npm notice === Tarball Details ===
npm notice name: @jupyterlab/github
npm notice version: 2.0.0
npm notice filename: jupyterlab-github-2.0.0.tgz
npm notice package size: 54.3 kB
npm notice unpacked size: 113.9 kB
npm notice shasum: ca86cba6c136b9b3b138b1c8f7c50e576630e650
npm notice integrity: sha512-OeE6CUicyqg1p[...]/FxdT+/s8b/WQ==
npm notice total files: 17
npm notice
jupyterlab-github-2.0.0.tgz

Node v12.16.3

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)

node /Users/spencer/software/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.npm.taobao.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.13.0.tgz: Request failed "404 Not Found"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/spencer/software/anaconda3/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

File "/Users/spencer/software/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
yield

File "/Users/spencer/software/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
command=command, app_options=app_options)

File "/Users/spencer/software/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
command=command, clean_staging=clean_staging)

File "/Users/spencer/software/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: jupyter

**Comment by EricCacciavillani** [comment]
I am getting the same problem.

**Comment by gioarma** [comment]
Same problem here, did someone find a solution?

**Comment by shadow150519** [comment]
i encounter the same problem, so how to fix it

**Comment by shadow150519** [comment]
i installed jupyterlab by anaconda, i was using notebook before, when i run ` jupyter labextension install @jupterlab/XXX` ,i also encounter the same problem, maybe it's due to `https://registry.npm.taobao.org`?
```
(base) PS C:\Users\Lenovo> jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.3
qtconsole        : not installed
ipython          : 7.26.0
ipykernel        : 5.3.4
jupyter client   : 6.1.12
jupyter lab      : 3.1.7
nbconvert        : 6.1.0
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

**Comment by goanpeca** [comment]
@shadow150519 what extension are you trying to install? if it is already available as a pip package then you could use that

**Comment by shadow150519** [comment]
emm..., in fact, i can't install any extension except the debugger extension. even when i run `jupyter lab build`, it also fails. i open the log file and the error is the same as the issue. i change the npm registry to ` https://registry.npmjs.org`, but it sill says `"error An unexpected error occurred: "https://registry.npm.taobao.org/@types/react/-/react-17.0.18.tgz: Request failed \"404 Not Found\"".`

**Comment by shadow150519** [comment]
i'm a newb to jupyterlab, so maybe it has something to do with me,too

**Comment by shadow150519** [comment]
below is the log
```
Node v14.16.0

Yarn configuration loaded.
> D:\Nodejs\npm.CMD pack @jupyterlab/git
npm notice 
npm notice package: @jupyterlab/git@0.32.2
npm notice === Tarball Contents === 
npm notice 1.5kB   LICENSE                                   
npm notice 19.3kB  README.md                                 
npm notice 1.7kB   lib/commandsAndMenu.d.ts                  
npm notice 39.9kB  lib/commandsAndMenu.js                    
npm notice 70.2kB  lib/commandsAndMenu.js.map                
npm notice 671B    lib/components/ActionButton.d.ts          
npm notice 592B    lib/components/ActionButton.js            
npm notice 1.8kB   lib/components/ActionButton.js.map        
npm notice 1.7kB   lib/components/Alert.d.ts                 
npm notice 3.5kB   lib/components/Alert.js                   
npm notice 7.1kB   lib/components/Alert.js.map               
npm notice 2.8kB   lib/components/BranchMenu.d.ts            
npm notice 10.4kB  lib/components/BranchMenu.js              
npm notice 19.2kB  lib/components/BranchMenu.js.map          
npm notice 3.0kB   lib/components/CommitBox.d.ts             
npm notice 7.2kB   lib/components/CommitBox.js               
npm notice 15.6kB  lib/components/CommitBox.js.map           
npm notice 1.1kB   lib/components/CommitMessage.d.ts         
npm notice 2.8kB   lib/components/CommitMessage.js           
npm notice 5.9kB   lib/components/CommitMessage.js.map       
npm notice 4.4kB   lib/components/diff/mergeview.d.ts        
npm notice 49.1kB  lib/components/diff/mergeview.js          
npm notice 106.5kB lib/components/diff/mergeview.js.map      
npm notice 1.3kB   lib/components/diff/model.d.ts            
npm notice 2.0kB   lib/components/diff/model.js              
npm notice 4.1kB   lib/components/diff/model.js.map          
npm notice 2.0kB   lib/components/diff/NotebookDiff.d.ts     
npm notice 9.6kB   lib/components/diff/NotebookDiff.js       
npm notice 17.0kB  lib/components/diff/NotebookDiff.js.map   
npm notice 1.7kB   lib/components/diff/PlainTextDiff.d.ts    
npm notice 4.7kB   lib/components/diff/PlainTextDiff.js      
npm notice 8.9kB   lib/components/diff/PlainTextDiff.js.map  
npm notice 1.1kB   lib/components/Feedback.d.ts              
npm notice 2.8kB   lib/components/Feedback.js                
npm notice 6.4kB   lib/components/Feedback.js.map            
npm notice 1.7kB   lib/components/FileItem.d.ts              
npm notice 3.6kB   lib/components/FileItem.js                
npm notice 8.8kB   lib/components/FileItem.js.map            
npm notice 5.1kB   lib/components/FileList.d.ts              
npm notice 21.9kB  lib/components/FileList.js                
npm notice 40.8kB  lib/components/FileList.js.map            
npm notice 371B    lib/components/FilePath.d.ts              
npm notice 901B    lib/components/FilePath.js                
npm notice 2.1kB   lib/components/FilePath.js.map            
npm notice 4.9kB   lib/components/GitPanel.d.ts              
npm notice 15.9kB  lib/components/GitPanel.js                
npm notice 30.2kB  lib/components/GitPanel.js.map            
npm notice 755B    lib/components/GitStage.d.ts              
npm notice 1.7kB   lib/components/GitStage.js                
npm notice 4.0kB   lib/components/GitStage.js.map            
npm notice 931B    lib/components/HistorySideBar.d.ts        
npm notice 4.7kB   lib/components/HistorySideBar.js          
npm notice 9.0kB   lib/components/HistorySideBar.js.map      
npm notice 3.0kB   lib/components/NewBranchDialog.d.ts       
npm notice 11.0kB  lib/components/NewBranchDialog.js         
npm notice 20.7kB  lib/components/NewBranchDialog.js.map     
npm notice 2.1kB   lib/components/PastCommitNode.d.ts        
npm notice 4.2kB   lib/components/PastCommitNode.js          
npm notice 8.9kB   lib/components/PastCommitNode.js.map      
npm notice 3.2kB   lib/components/ResetRevertDialog.d.ts     
npm notice 7.6kB   lib/components/ResetRevertDialog.js       
npm notice 14.6kB  lib/components/ResetRevertDialog.js.map   
npm notice 3.2kB   lib/components/SinglePastCommitInfo.d.ts  
npm notice 7.0kB   lib/components/SinglePastCommitInfo.js    
npm notice 14.5kB  lib/components/SinglePastCommitInfo.js.map
npm notice 1.2kB   lib/components/StatusWidget.d.ts          
npm notice 5.5kB   lib/components/StatusWidget.js            
npm notice 8.6kB   lib/components/StatusWidget.js.map        
npm notice 952B    lib/components/SuspendModal.d.ts          
npm notice 1.2kB   lib/components/SuspendModal.js            
npm notice 2.4kB   lib/components/SuspendModal.js.map        
npm notice 2.0kB   lib/components/TagMenu.d.ts               
npm notice 7.1kB   lib/components/TagMenu.js                 
npm notice 13.5kB  lib/components/TagMenu.js.map             
npm notice 3.1kB   lib/components/Toolbar.d.ts               
npm notice 9.9kB   lib/components/Toolbar.js                 
npm notice 18.9kB  lib/components/Toolbar.js.map             
npm notice 754B    lib/git.d.ts                              
npm notice 2.6kB   lib/git.js                                
npm notice 3.8kB   lib/git.js.map                            
npm notice 510B    lib/index.d.ts                            
npm notice 6.9kB   lib/index.js                              
npm notice 12.4kB  lib/index.js.map                          
npm notice 607B    lib/logger.d.ts                           
npm notice 647B    lib/logger.js                             
npm notice 1.4kB   lib/logger.js.map                         
npm notice 21.9kB  lib/model.d.ts                            
npm notice 43.1kB  lib/model.js                              
npm notice 69.9kB  lib/model.js.map                          
npm notice 477B    lib/server.d.ts                           
npm notice 1.7kB   lib/server.js                             
npm notice 2.8kB   lib/server.js.map                         
npm notice 216B    lib/style/ActionButtonStyle.d.ts          
npm notice 788B    lib/style/ActionButtonStyle.js            
npm notice 1.7kB   lib/style/ActionButtonStyle.js.map        
npm notice 461B    lib/style/BranchMenu.d.ts                 
npm notice 2.9kB   lib/style/BranchMenu.js                   
npm notice 5.2kB   lib/style/BranchMenu.js.map               
npm notice 524B    lib/style/CommitBox.d.ts                  
npm notice 2.7kB   lib/style/CommitBox.js                    
npm notice 4.7kB   lib/style/CommitBox.js.map                
npm notice 49B     lib/style/common.d.ts                     
npm notice 648B    lib/style/common.js                       
npm notice 1.2kB   lib/style/common.js.map                   
npm notice 454B    lib/style/FileItemStyle.d.ts              
npm notice 1.7kB   lib/style/FileItemStyle.js                
npm notice 3.1kB   lib/style/FileItemStyle.js.map            
npm notice 51B     lib/style/FileListStyle.d.ts              
npm notice 217B    lib/style/FileListStyle.js                
npm notice 522B    lib/style/FileListStyle.js.map            
npm notice 136B    lib/style/FilePathStyle.d.ts              
npm notice 531B    lib/style/FilePathStyle.js                
npm notice 1.1kB   lib/style/FilePathStyle.js.map            
npm notice 315B    lib/style/GitPanel.d.ts                   
npm notice 1.8kB   lib/style/GitPanel.js                     
npm notice 3.2kB   lib/style/GitPanel.js.map                 
npm notice 263B    lib/style/GitStageStyle.d.ts              
npm notice 1.3kB   lib/style/GitStageStyle.js                
npm notice 2.6kB   lib/style/GitStageStyle.js.map            
npm notice 45B     lib/style/GitWidgetStyle.d.ts             
npm notice 314B    lib/style/GitWidgetStyle.js               
npm notice 661B    lib/style/GitWidgetStyle.js.map           
npm notice 155B    lib/style/HistorySideBarStyle.d.ts        
npm notice 683B    lib/style/HistorySideBarStyle.js          
npm notice 1.4kB   lib/style/HistorySideBarStyle.js.map      
npm notice 814B    lib/style/icons.d.ts                      
npm notice 2.7kB   lib/style/icons.js                        
npm notice 5.4kB   lib/style/icons.js.map                    
npm notice 1.1kB   lib/style/NewBranchDialog.d.ts            
npm notice 6.1kB   lib/style/NewBranchDialog.js              
npm notice 10.5kB  lib/style/NewBranchDialog.js.map          
npm notice 578B    lib/style/PastCommitNode.d.ts             
npm notice 1.9kB   lib/style/PastCommitNode.js               
npm notice 3.5kB   lib/style/PastCommitNode.js.map           
npm notice 575B    lib/style/ResetRevertDialog.d.ts          
npm notice 4.5kB   lib/style/ResetRevertDialog.js            
npm notice 7.6kB   lib/style/ResetRevertDialog.js.map        
npm notice 484B    lib/style/SinglePastCommitInfo.d.ts       
npm notice 1.8kB   lib/style/SinglePastCommitInfo.js         
npm notice 3.4kB   lib/style/SinglePastCommitInfo.js.map     
npm notice 100B    lib/style/StatusWidget.d.ts               
npm notice 690B    lib/style/StatusWidget.js                 
npm notice 1.4kB   lib/style/StatusWidget.js.map             
npm notice 54B     lib/style/SuspendModal.d.ts               
npm notice 256B    lib/style/SuspendModal.js                 
npm notice 578B    lib/style/SuspendModal.js.map             
npm notice 624B    lib/style/Toolbar.d.ts                    
npm notice 3.0kB   lib/style/Toolbar.js                      
npm notice 5.2kB   lib/style/Toolbar.js.map                  
npm notice 1.7kB   lib/taskhandler.d.ts                      
npm notice 3.4kB   lib/taskhandler.js                        
npm notice 5.5kB   lib/taskhandler.js.map                    
npm notice 28.4kB  lib/tokens.d.ts                           
npm notice 3.6kB   lib/tokens.js                             
npm notice 29.9kB  lib/tokens.js.map                         
npm notice 399B    lib/utils.d.ts                            
npm notice 916B    lib/utils.js                              
npm notice 1.8kB   lib/utils.js.map                          
npm notice 41B     lib/version.d.ts                          
npm notice 95B     lib/version.js                            
npm notice 257B    lib/version.js.map                        
npm notice 427B    lib/widgets/AuthorBox.d.ts                
npm notice 1.0kB   lib/widgets/AuthorBox.js                  
npm notice 2.3kB   lib/widgets/AuthorBox.js.map              
npm notice 598B    lib/widgets/CredentialsBox.d.ts           
npm notice 1.6kB   lib/widgets/CredentialsBox.js             
npm notice 3.5kB   lib/widgets/CredentialsBox.js.map         
npm notice 271B    lib/widgets/gitClone.d.ts                 
npm notice 790B    lib/widgets/gitClone.js                   
npm notice 2.0kB   lib/widgets/gitClone.js.map               
npm notice 472B    lib/widgets/GitCloneForm.d.ts             
npm notice 1.1kB   lib/widgets/GitCloneForm.js               
npm notice 2.2kB   lib/widgets/GitCloneForm.js.map           
npm notice 1.3kB   lib/widgets/GitWidget.d.ts                
npm notice 2.4kB   lib/widgets/GitWidget.js                  
npm notice 5.5kB   lib/widgets/GitWidget.js.map              
npm notice 5.8kB   package.json                              
npm notice 5.3kB   schema/plugin.json                        
npm notice 382B    style/base.css                            
npm notice 3.4kB   style/diff-common.css                     
npm notice 1.8kB   style/diff-nb.css                         
npm notice 1.5kB   style/diff-text.css                       
npm notice 260B    style/icons/add.svg                       
npm notice 1.4kB   style/icons/branch.svg                    
npm notice 519B    style/icons/clock.svg                     
npm notice 1.3kB   style/icons/clone.svg                     
npm notice 307B    style/icons/deletions.svg                 
npm notice 258B    style/icons/desktop.svg                   
npm notice 517B    style/icons/diff.svg                      
npm notice 603B    style/icons/discard.svg                   
npm notice 650B    style/icons/git.svg                       
npm notice 326B    style/icons/insertions.svg                
npm notice 518B    style/icons/open-file.svg                 
npm notice 173B    style/icons/plus.svg                      
npm notice 661B    style/icons/pull.svg                      
npm notice 642B    style/icons/push.svg                      
npm notice 240B    style/icons/remove.svg                    
npm notice 352B    style/icons/rewind.svg                    
npm notice 809B    style/icons/tag.svg                       
npm notice 247B    style/icons/trash.svg                     
npm notice 650B    style/icons/vertical-more.svg             
npm notice 488B    style/index.css                           
npm notice 21B     style/index.js                            
npm notice 494B    style/variables.css                       
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/git                         
npm notice version:       0.32.2                                  
npm notice filename:      @jupyterlab/git-0.32.2.tgz              
npm notice package size:  251.4 kB                                
npm notice unpacked size: 1.2 MB                                  
npm notice shasum:        f2f8728f8a147a02bb23f49c9e8433cd748fd34d
npm notice integrity:     sha512-fIY+tamz3NQXE[...]IxaNJL3KWQZPg==
npm notice total files:   204                                     
npm notice 
jupyterlab-git-0.32.2.tgz

Node v14.16.0

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node D:\deepin\Anaconda\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.npm.taobao.org/@types/react/-/react-17.0.18.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "D:\\deepin\\Anaconda\\share\\jupyter\\lab\\staging\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\debuglog.py", line 48, in debug_logging
    yield

  File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\labextensions.py", line 141, in start
    production = production, minimize = self.minimize, app_options=app_options)

  File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\commands.py", line 483, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

  File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\commands.py", line 688, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: lab

```

**Comment by shadow150519** [comment]
when i run `jupyter lab build `,  below is the log 
```
[LabBuildApp] Building in D:\deepin\Anaconda\share\jupyter\lab
[LabBuildApp] Node v14.16.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node D:\deepin\Anaconda\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.npm.taobao.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.15.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "D:\\deepin\\Anaconda\\share\\jupyter\\lab\\staging\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\debuglog.py", line 48, in debug_logging
    yield

[LabBuildApp]   File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\labapp.py", line 176, in start
    raise e

[LabBuildApp]   File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\labapp.py", line 173, in start
    app_options=app_options, production = production, minimize=self.minimize)

[LabBuildApp]   File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\commands.py", line 483, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

[LabBuildApp]   File "D:\deepin\Anaconda\lib\site-packages\jupyterlab\commands.py", line 688, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by krassowski** [comment]
@shadow150519 I cannot help you with npm registry configuration, but if you use JupyterLab 3.x I can encourage you to abandon `jupyter labextension install` and use `pip install extension-name` or `conda install -c conda-forge extension-name` instead. This will eliminate npm out of equation completely; most major extensions support both ways of installing, but the `pip`/`conda` way is much simpler. The exact name of the extension package may differ between the two ways of installing the extensions. Please see [this answer](https://stackoverflow.com/questions/67390716/unable-to-install-jupyterlab-execute-time-extension/67391886#67391886) for more details.

If you do not use JupyterLab 3.x, I would encourage you to switch to JupyterLab 3.x ;)

**Comment by shadow150519** [comment]
my jupyter lab version is 3.1.7.  i think i can download the extension but i can't successfully run `jupyter lab build`. 

![image](https://user-images.githubusercontent.com/55205022/130494937-2ced9fa7-6807-42e0-ba18-c497d9594091.png)

**Comment by krassowski** [comment]
Once, again please try the `pip` way. To reiterate in simple steps:

1. `jupyter labextension uninstall @jupyterlab/git @jupyterlab/geojson-extension`
2. `pip install jupyterlab-geojson jupyterlab-git` **or** if using conda: `conda install -c conda-forge jupyterlab-geojson jupyterlab-git`
