### ISSUE TITLE
Missing Node.js error message unclear

### ISSUE THREAD

**Issue by big-o** [jupyterlab/jupyterlab#8459]
## Description

I've just made the move over from Jupyter Notebook to JupyterLab. Really impressed so far, but I had one issue that took me a little while to debug, and I believe a more clear error message would have resolved this for me straight away.

## Reproduce

Try installing an extension on a machine without nodejs/npm installed and you'll get an error message saying "please install Node.js". However, a simple `sudo apt install nodejs` is not enough. You also need to install `npm`. With node and no npm, JupyterLab still fails to install the extension and you don't get an error message.

## Expected behavior

Amend the error message to say `Please install Node.js AND npm`.

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: Chromium 81
- JupyterLab version: 2.1.2

**Comment by blink1073** [comment]
Hi @big-o, which version of `nodejs` is this (`node --version`)?  AFAIK all supported versions of `node` come with `npm` bundled.

**Comment by big-o** [comment]
I just ran `sudo apt install nodejs` which gave me:

```
$ node --version
v10.19.0
```

I couldn't install extensions until I also installed npm (via apt) separately.

**Comment by blink1073** [comment]
Thanks for confirming!  We do support node 10+.  PRs welcome!

The error message is here: https://github.com/jupyterlab/jupyterlab/blob/a0d1dc7cae02f256ebc0deeaa50c1c6f9caff57b/jupyterlab/commands.py#L1765

**Comment by jasongrout** [comment]
On Debian, IIRC, nodejs and npm are separately packaged as Debian packages, so if you do `apt-get install nodejs`, you do *not* get npm.

If you install the official NodeJS from the nodejs project, you do get npm.

**Comment by rpanai** [comment]
I've the same problem on a fresh install. My node version within the environment is `v14.4.0`. I understand that I can install extentions as long as i install node at OS level but in this case the following message is unclear.

```bash
An error occured.
ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
```
Another possible solution is using a symbolic link as suggested [here](https://github.com/jupyterlab/jupyterlab/issues/3640#issuecomment-369947701)

**Comment by giorgoslytos** [comment]
> On Debian, IIRC, nodejs and npm are separately packaged as Debian packages, so if you do `apt-get install nodejs`, you do _not_ get npm.
> 
> If you install the official NodeJS from the nodejs project, you do get npm.

Thank you very much! I lost 2+ hours trying to make it work on pop!os and the problem was that I didn't have npm installed as a separate package. I use nvm but it seems that conda couldn't see the npm from the nvm for some reason. You have to install npm from apt for conda to be able to see it

**Comment by dat-linux** [comment]
Jupyter extensions are a mess.

I have node and npm installed on my Ubuntu 22.04 system, and also on the virtual python env that I'm running jupyter from. Yet any attempt at installing a Lab extension fails.

**ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org/).**

This message is vague, and does not report what binary or where it is looking for it.

**Comment by Bazmundi** [comment]
> Thanks for confirming! We do support node 10+. PRs welcome!
> 
> The error message is here:
> 
> [jupyterlab/jupyterlab/commands.py](https://github.com/jupyterlab/jupyterlab/blob/a0d1dc7cae02f256ebc0deeaa50c1c6f9caff57b/jupyterlab/commands.py#L1765)
> 
> Line 1765 in [a0d1dc7](/jupyterlab/jupyterlab/commit/a0d1dc7cae02f256ebc0deeaa50c1c6f9caff57b)
> 
>  msg = 'Please install nodejs %s before continuing. nodejs may be installed using conda or directly from the nodejs website.' % ver

Yep, I was getting `Could not determine jupyterlab build status without nodejs`, so took the advice above and used conda install condaforge::nodejs.

That now results in:

```
(jupyter) asterion@MonstaPC:~/AI/fasttrack$ jupyter lab                                                                                                                                      
Traceback (most recent call last):
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 14, in <module>
    import sqlite3
  File "/home/asterion/miniconda3/envs/jupyter/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/asterion/miniconda3/envs/jupyter/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /home/asterion/miniconda3/envs/jupyter/lib/python3.11/lib-dynload/_sqlite3.cpython-311-x86_64-linux-gnu.so: undefined symbol: sqlite3_deserialize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asterion/miniconda3/envs/jupyter/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyterlab/__init__.py", line 8, in <module>
    from .handlers.announcements import (
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyterlab/handlers/announcements.py", line 15, in <module>
    from jupyterlab_server.translation_utils import translator
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyterlab_server/__init__.py", line 6, in <module>
    from .app import LabServerApp
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyterlab_server/app.py", line 10, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 17, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 108, in <module>
    from jupyter_server.gateway.managers import (
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyter_server/gateway/managers.py", line 32, in <module>
    from ..services.sessions.sessionmanager import SessionManager
  File "/home/asterion/.local/lib/python3.11/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 17, in <module>
    from pysqlite2 import dbapi2 as sqlite3  # type:ignore[no-redef]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pysqlite2'
``` 

Which is actually the problem I was trying to sort out.  That is, I had built an env with jupyter, numpy, scipy, pandas, yadda. When I tried running `jupyter lab`, I got the error immediately above.  I ripped out the env and installed jupyter to get the missing nodejs prompt.

Running:
conda 24.11.1

Post `conda install condaforge::jupyterlab` then `conda install condaforge::nodejs' I have:

```
(jupyter) asterion@MonstaPC:~/AI/fasttrack$ jupyter --version
Selected Jupyter core packages...
IPython          : not installed
ipykernel        : 6.29.5
ipywidgets       : not installed
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.15.0
jupyterlab       : not installed
nbclient         : 0.10.2
nbconvert        : 7.16.5
nbformat         : 5.10.4
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.14.3

```
I'll rip out the env and try installing in different order (who knows, I may need grab some aluminium and wrap it around me head as well 😄 )

**Comment by anupamdwivedi98** [comment]
Hi, I am a beginner contributor.
I would like to work on improving the documentation/error message clarity for this issue.
Can you please assign it to me?

Thanks!

**Comment by jasongrout** [comment]
We typically don't assign issues. Feel free to submit a PR!

**Comment by MohammedSaad2701** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by toby-bridges** [comment]
I’m taking a look at this and plan to submit a small fix for the node/npm error message plus a targeted regression test.
