### ISSUE TITLE
Chokidar missing in 1.2.x

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#8515]
**Edit:**
`jupyter lab --watch` is broken in version `1.2.16`. The workaround is to use version `1.2.15`

## Description
Same problem as https://github.com/jupyterlab/jupyterlab/issues/8469 so maybe of interest to @blink1073 

Chokidar used to be picked up a dependency for 1.2.x but no longer is. I tried to fix this the same way as https://github.com/jupyterlab/jupyterlab/pull/8492 by running `jlpm add --dev chokidar` inside the `dev_mode` folder. But I kept getting a build error about lumino when I can `jupyter lab --watch --dev-mode`. I tried `rm -rf node_modules` in both the top level and in `dev_mode` but this did not seem to help. We're now solidly at the end of knowledge about javascript build systems so I may be unable to fix this sorry.

```
conda create -n jlab1 python nodejs
conda install -c conda-forge notebook
pip install -e .
jlpm install
jlpm build (or jupyter lab --watch --dev-mode)
```

results in this error (from the --watch version):
```
yarn run v1.15.2
$ webpack --watch
/home/ian/Documents/jupyter/jupyterlab-1/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module '@lumino/coreutils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ian/Documents/jupyter/jupyterlab-1/buildutils/lib/utils.js:9:19)
    at Module._compile (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ian/Documents/jupyter/jupyterlab-1/buildutils/lib/build.js:18:28)
    at Module._compile (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ian/Documents/jupyter/jupyterlab-1/buildutils/lib/index.js:10:10)
    at Module._compile (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ian/Documents/jupyter/jupyterlab-1/dev_mode/webpack.config.js:15:13)
    at Module._compile (/home/ian/Documents/jupyter/jupyterlab-1/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ianhi** [comment]
If anyone else comes across this problem `jupyter lab --watch` **will** work in version `1.2.15`

**Comment by blink1073** [comment]
Thanks for looking into this one @ianhi.  I think your workaround is sufficient as we start to focus more on 3.0.

**Comment by ianhi** [comment]
sounds good. Should I close this? Or leave open to ease someone else finding the workraround?

**Comment by blink1073** [comment]
I'd say leave it open

**Comment by jtpio** [comment]
Closing as this issue was opened for JupyterLab 1 which is not supported anymore.

Also `chokidar` is currently at version `^3.4.0`:

https://github.com/jupyterlab/jupyterlab/blob/696751e7cfbaca0d60801cef323282562b26fa1f/dev_mode/package.json#L190

Feel free to re-open if you still notice the issue, thanks!
