### ISSUE TITLE
"Linux usage" CI step randomly hangs

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8535]
## Description

GitHub Actions runs `Linux Usage` and randomly hangs forever (killed after 120 minutes).

## Reproduce

Open a PR and check the logs of the `Linux Usage` step, `Run test usage` may hang. Select the `Linux Usage` on the left and leave your tab open to see the logs (if you close and want to reopen the `Run test usage`, GitHub Actions will not respond to your click...).

For example a hanging job shows the following as last log.

```
>> Starting example
[I 05:51:08.382 Browser-requireTest] Kernel started: fa13879d-748b-4f5e-b4ee-567a54a43300
>> Starting WebSocket: ws://127.0.0.1:8888/foo/api/kernels/fa13879d-748b-4f5e-b4ee-567a54a43300
>> Kernel started: JSHandle@object
>> Kernel: connected (fa13879d-748b-4f5e-b4ee-567a54a43300)
>> Kernel info: JSHandle@object
>> Example started!
[I 05:51:08.949 Browser-requireTest] Starting buffering for fa13879d-748b-4f5e-b4ee-567a54a43300:426ba407d9bff4a5dcd48d87839b0e72
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Example test complete!
[I 05:51:08.964 Browser-requireTest] Test Complete
[I 05:51:08.964 Browser-requireTest] Exiting normally
[I 05:51:08.964 Browser-requireTest] Stopping server...
[I 05:51:08.967 Browser-requireTest] Shutting down 1 kernel
[I 05:51:09.168 Browser-requireTest] Kernel shutdown: fa13879d-748b-4f5e-b4ee-567a54a43300
```

**Comment by blink1073** [comment]
https://github.com/jupyterlab/jupyterlab/pull/8464 was my latest attempt to fix this thorny problem.

**Comment by jtpio** [comment]
@echarles do you think this can now be closed?

The Linux Usage test seems to be passing more often than not nowadays.

**Comment by echarles** [comment]
I have not monitored recently, but if you think it can be closed, just click on the button.

**Comment by jtpio** [comment]
OK thanks for checking :+1:
