### ISSUE TITLE
jupyter labextension install Failed

### ISSUE THREAD

**Issue by JackHsuan** [jupyterlab/jupyterlab#8667]
I'm using python3.8.3 in Windows 10，
I always get Error when I using jupyter labextension install xxx:
for example when I type in cmd :
$jupyter labextension install jupyter-matplotlib
I always get the Error : UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 269:
Building jupyterlab assets (build:prod:minimize)
|Exception in thread Thread-10:
Traceback (most recent call last):
  File "c:\users\jackhsuan\appdata\local\programs\python\python38\lib\threading.py", line 934, in _bootstrap_inner
    self.run()
  File "c:\users\jackhsuan\appdata\local\programs\python\python38\lib\threading.py", line 872, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\jackhsuan\appdata\local\programs\python\python38\lib\subprocess.py", line 1366, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 269: illegal multibyte sequence
An error occured.
IndexError: list index out of range
See the log file for details:  C:\Users\JACKHS~1\AppData\Local\Temp\jupyterlab-debug-6rvxxfbt.log

I try some method like npm config set unicode false and not worked for me 

Any idea how this can be solved?

Rgds,
Jack

**Comment by Xuzhengfu** [comment]
Does this work for you?

https://github.com/jupyterlab/jupyterlab/issues/5345#issuecomment-546798837

**Comment by MagicJack** [comment]
You may need to reinstall node.js, once the error occure.
It may leave some errors in '\nodejs\node_modules\npm', so the 'Extension Manager' cannot operate.
