### ISSUE TITLE
No kernel after update jupyter lab

### ISSUE THREAD

**Issue by jshcht** [jupyterlab/jupyterlab#8685]
After updating the jupyter lab via `conda update jupyterlab`, jupyter lab kernel cannot be connected anymore. The condition is shown in the picture. Command cannot be executed (no output).
![image](https://user-images.githubusercontent.com/48586099/87245578-f4c6a480-c478-11ea-8ff1-4ff722d6ab23.png)
`jupyter kernelspec list` gave the following message:
`python3    D:\professional\Anaconda_install\share\jupyter\kernels\python3`.
Could anyone help me please?

**Comment by jshcht** [comment]
I just found the spyder cannot start too, with the error:
`Traceback (most recent call last):
  File "D:\professional\Anaconda_install\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\professional\Anaconda_install\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "D:\professional\Anaconda_install\lib\site-packages\spyder\app\mainwindow.py", line 3748, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\professional\Anaconda_install\lib\site-packages\spyder\app\mainwindow.py", line 3623, in run_spyder
    main.setup()
  File "D:\professional\Anaconda_install\lib\site-packages\spyder\app\mainwindow.py", line 945, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "D:\professional\Anaconda_install\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in <module>
    from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
  File "D:\professional\Anaconda_install\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in <module>
    from .debugging import DebuggingWidget
  File "D:\professional\Anaconda_install\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 15, in <module>
    from IPython.core.history import HistoryManager
  File "D:\professional\Anaconda_install\lib\site-packages\IPython\__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "D:\professional\Anaconda_install\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "D:\professional\Anaconda_install\lib\site-packages\IPython\terminal\interactiveshell.py", line 19, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
ModuleNotFoundError: No module named 'prompt_toolkit'`

**Comment by jshcht** [comment]
And ipython cannot work either, with the same error message as spyder.

**Comment by agoose77** [comment]
It looks like your env is broken. Without freezing the env and looking at it, the easiest solution is just to recreate your environment.

**Comment by jshcht** [comment]
Ok, thanks a lot for your advice.
