### ISSUE TITLE
Failed to get yarn configuration while installing Jupyter Lab in Cygwin

### ISSUE THREAD

**Issue by beastSL** [jupyterlab/jupyterlab#8760]
## Description

I am trying to install some extensions for jupyterlab in Cygwin. So I type, for example, `jupyter labextension install @jupyter-widgets/jupyterlab-manager` in the Cygwin command prompt. But I get an error. Here's the log:

```
Fail to get yarn configuration. internal/module/cjs/loader.js:968
    throw err;
    ^

Error: Cannot find module 'C:\home\user\repo\venv\lib\python3.8\site-packages\jupyterlab\staging\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND,
  requireStack: []
}

Fail to get yarn configuration. internal/module/cjs/loader.js:968
    throw err;
    ^

Error: Cannot find module 'C:\home\user\repo\venv\lib\python3.8\site-packages\jupyterlab\staging\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND,
  requireStack: []
}

An error occured.
OSError: [Errno 16] Device or resource busy: '/tmp/tm1da390j3'
See the log file for details: /tmp/jupyterlab-debug-mgr2ux9k.log

```
I understand the error: instead of looking for `C:\cygwin64\home\user\repo\venv\lib\python3.8\site-packages\jupyterlab\staging\yarn.js` the installation manager looks for `C:\home\user\repo\venv\lib\python3.8\site-packages\jupyterlab\staging\yarn.js`. I just don't know how to fix it. Maybe I need to edit some configuration files. I would be very grateful for your help.

## Expected behavior

`Yarn configuration loaded.`

## Context

- Operating System and version: Cygwin under Windows 10 Enterprise N 2016 LTSB
- JupyterLab version: 2.2.2

<details><summary>Command Line Output</summary>
<pre>
$ jupyter lab --debug
Fail to get yarn configuration. internal/module/cjs/loader.js:968
    throw err;
    ^

Error: Cannot find module 'C:\home\user\repo\venv\lib\python3.8\site-packages\jupyterlab\staging\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND,
  requireStack: []
}

[D 12:40:57.254 LabApp] Searching ['/home/user/repo', '/home/user/.jupyter', '/home/user/repo/venv/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 12:40:57.255 LabApp] Looking for jupyter_config in /etc/jupyter
[D 12:40:57.255 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 12:40:57.256 LabApp] Looking for jupyter_config in /home/user/repo/venv/etc/jupyter
[D 12:40:57.256 LabApp] Looking for jupyter_config in /home/user/.jupyter
[D 12:40:57.256 LabApp] Looking for jupyter_config in /home/user/repo
[D 12:40:57.258 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 12:40:57.258 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 12:40:57.259 LabApp] Looking for jupyter_notebook_config in /home/user/repo/venv/etc/jupyter
[D 12:40:57.259 LabApp] Looking for jupyter_notebook_config in /home/user/.jupyter
[D 12:40:57.260 LabApp] Loaded config file: /home/user/.jupyter/jupyter_notebook_config.py
[D 12:40:57.260 LabApp] Looking for jupyter_notebook_config in /home/user/repo
[D 12:40:57.261 LabApp] Default value for min_open_files_limit is ignored (hard=3200, soft=256)
[D 12:40:57.266 LabApp] Paths used for configuration of jupyter_notebook_config:
    /etc/jupyter/jupyter_notebook_config.json
[D 12:40:57.266 LabApp] Paths used for configuration of jupyter_notebook_config:
    /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 12:40:57.267 LabApp] Paths used for configuration of jupyter_notebook_config:
    /home/user/repo/venv/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    /home/user/repo/venv/etc/jupyter/jupyter_notebook_config.json
[D 12:40:57.268 LabApp] Paths used for configuration of jupyter_notebook_config:
    /home/user/.jupyter/jupyter_notebook_config.json
Fail to get yarn configuration. internal/module/cjs/loader.js:968
    throw err;
    ^

Error: Cannot find module 'C:\home\user\repo\venv\lib\python3.8\site-packages\jupyterlab\staging\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND,
  requireStack: []
}

[I 12:40:58.111 LabApp] JupyterLab extension loaded from /home/user/repo/venv/lib/python3.8/site-packages/jupyterlab
[I 12:40:58.111 LabApp] JupyterLab application directory is /home/user/repo/venv/share/jupyter/lab
[I 12:40:58.113 LabApp] Serving notebooks from local directory: /home/user/repo
[I 12:40:58.113 LabApp] Jupyter Notebook 6.1.1 is running at:
[I 12:40:58.113 LabApp] http://localhost:888/?token=token or http://127.0.0.1:8888/?token=token
[I 12:40:58.113 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 12:40:58.145 LabApp] No web browser found: could not locate runnable browser.
[C 12:40:58.145 LabApp]

    To access the notebook, open this file in a browser:
        file://home/user/.local/share/jupyter/runtime/nbserver-1773-open.html
    Or copy and paste on of these URLs:
        http://localhost:8888/?token=token
      or http://127.0.0.1:8888/?token=token

**Comment by dmarteau** [comment]
This error occurs also at startup on Linux with the python package jupyterlab ( version 4.3.6, python 3.12). 
There is many report of this problem on the web but no clear solution to fix it. 
 
Following https://jupyter.org/install,  there is no mention to other third party dependencies.

**Comment by krassowski** [comment]
> This error occurs also at startup on Linux with the python package jupyterlab ( version 4.3.6, python 3.12).

@dmarteau what exact error do you get? Are you also using Cygwin under Windows?

JupyterLab should not need to check yarn configuration on startup.
