### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by ahmadmustafaanis** [jupyterlab/jupyterlab#8771]
## Description
Hi, I installed Kite extension for jupyter lab and it required to rebuild the lab. But it is giving errors.

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context
The error is
```
 "jupyterlab-dash@0.3.0" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension      Package
    >=1.2.8 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/application
    >=1.2.9 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
    >=1.2.9 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/console


[W 13:43:18.582 LabApp] Build recommended
[W 13:43:18.582 LabApp] @kiteco/jupyterlab-kite needs to be included in build
[I 13:43:19.814 LabApp] Kernel started: 00f24bbb-debc-4fbd-ac61-e79506aef755
[W 13:43:20.921 LabApp] Got events for closed stream None
[I 13:43:24.817 LabApp] Building jupyterlab assets (build:dev)
[W 13:43:24.859 LabApp]
    "jupyterlab-dash@0.3.0" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension      Package
    >=1.2.8 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/application
    >=1.2.9 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
    >=1.2.9 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/console


\[W 13:43:32.506 LabApp] Failed to fetch package metadata for '@kiteco/jupyterlab-kite': <HTTPError 404: 'Not Found'>
[W 13:43:39.188 LabApp] Build failed, running a clean and rebuild
[I 13:43:39.211 LabApp] Cleaning C:\Users\Ahmad Mustafa Anis\anaconda3\share\jupyter\lab...
[I 13:43:39.214 LabApp] Success!
[I 13:43:39.287 LabApp] Building jupyterlab assets (build:dev)
[W 13:43:39.307 LabApp]
    "jupyterlab-dash@0.3.0" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension      Package
    >=1.2.8 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/application
    >=1.2.9 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
    >=1.2.9 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/console


[W 13:45:00.593 LabApp] 500 POST /lab/api/build?1596703404503 (::1): npm dependencies failed to install
[W 13:45:00.595 LabApp] npm dependencies failed to install
[E 13:45:00.597 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
      "X-Xsrftoken": "2|5677c925|744eed25e12450625024a27e9e9bde04|1596043376",
      "Authorization": "token ba339399649ca3a7dd595cc948694bcd14e66538e67e41d5",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,ur;q=0.8",
      "Cookie": "_xsrf=2|5677c925|744eed25e12450625024a27e9e9bde04|1596043376; username-localhost-8888=\"2|1:0|10:1596703403|23:username-localhost-8888|44:N2U5MzJkM2Q1NDMyNDE2MmI0OWE2NmUyMmU0MmY2N2E=|302f466b1440830d399908650a80b6cac99016f8e0ca9d8f764e73c84429bb6b\""
```

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by ahmadmustafaanis** [comment]
The error output from
```
See the log file for details:  C:\Users\AHMADM~1\AppData\Local\Temp\jupyterlab-debug-6x8wokew.log
```
is 
```
[LabBuildApp] Building in C:\Users\Ahmad Mustafa Anis\anaconda3\share\jupyter\lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v10.13.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node "C:\Users\Ahmad Mustafa Anis\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js" install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@krassowski/jupyterlab_go_to_definition@~1.0.0" required by "@kiteco/jupyterlab-kite@file:../extensions/kiteco-jupyterlab-kite-1.0.0.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\Users\Ahmad Mustafa Anis\anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\Users\Ahmad Mustafa Anis\anaconda3\lib\site-packages\jupyterlab\labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "C:\Users\Ahmad Mustafa Anis\anaconda3\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "C:\Users\Ahmad Mustafa Anis\anaconda3\lib\site-packages\jupyterlab\commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by krassowski** [comment]
Three quick points:
- I think that you are more likely to get a quick response if you post extension-specific issues in the repositories of respective extensions, like [jupyterlab-kite](https://github.com/kiteco/jupyterlab-kite) which has failed here.
- in this particular instance installation of `@kiteco/jupyterlab-kite`  dependencies has failed because the npm had temporary issues about 7-8 hours ago, see https://status.npmjs.org/incidents/cksjqc1w11v5?u=mdkvwtx1zxnn - you should be find if you manage to uninstall the broken one and install it clean again
- jupyterlab-dash is not supported for JupyterLab 2.0, uninstall it and have a try of [jupyter-dash](https://github.com/plotly/jupyter-dash) instead

I hope this helps!
