### ISSUE TITLE
BUG: Failed to create entry into the history log

### ISSUE THREAD

**Issue by andreamoro** [jupyterlab/jupyterlab#8914]
## Description

Since I had to mode the homebrew location to a custom folder to circumnavigate IT security restrictions, I started to have problems also jupyter and jupyterlab.
I assume this is due to the fact I have python installed via pyenv which is managed via homebrew, but cannot be 100% sure.

The error message that I get from time to time is as follow:

```
/[IPKernelApp] ERROR | Failed to create history session in /Users/andreamoro/.ipython/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "$HOME/.pyenv/versions/3.8.5/lib/python3.8/site-packages/IPython/core/history.py", line 543, in __init__
    self.new_session()
  File "<decorator-gen-22>", line 2, in new_session
  File "$HOME/.pyenv/versions/3.8.5/lib/python3.8/site-packages/IPython/core/history.py", line 58, in needs_sqlite
    return f(self, *a, **kw)
  File "$HOME/.pyenv/versions/3.8.5/lib/python3.8/site-packages/IPython/core/history.py", line 568, in new_session
    cur = conn.execute("""INSERT INTO sessions VALUES (NULL, ?, NULL,
sqlite3.OperationalError: database is locked
```

I gave the database full permission in reading, writing and executing as I thought the problem could have been due to the process running under a separate process with no privileges on my folder, but that's not the case.

Any hint on how to solve?

On a separate side, when shutting down the framework, I also get errors connected to kernels that are attempted to be shut down but in-fact were not even running. This is preceded by 404 error messages in the console which attempts to open project no longer existing and removed.
I'm trying to understand where the "history" file is, but cannot find it.

## Expected behaviour

No error messages in the terminal

## Context

- Python package version:

- Extension version:

JupyterLab v2.2.6
Known labextensions:
   app dir: /Users/andreamoro/.pyenv/versions/3.8.5/share/jupyter/lab
        @jupyterlab/toc v4.0.0  enabled  OK

Mac OS X 10.15.6

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
@andreamoro I transferred your issue in the core repository as it is not linked to _@jupyterlab/git_ extension.

The history database IPython is trying to write into is `/Users/andreamoro/.ipython/profile_default/history.sqlite` according to your log as you already figured out. As I don't know anything about MacOS and homebrew. Hopefully someone here may know why you cannot write in a file in your home directory.

**Comment by andreamoro** [comment]
Thanks, so the history file is only that SQL database, for which I granted rights already then. I thought there were something more.

That's another example of an error I just got.

```
[E 09:54:12.833 LabApp] Exception in callback <bound method KernelRestarter.poll of <jupyter_client.ioloop.restarter.IOLoopKernelRestarter object at 0x103fcf7c0>>
    Traceback (most recent call last):
      File "/Users/andreamoro/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/Users/andreamoro/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jupyter_client/restarter.py", line 113, in poll
        self.kernel_manager.restart_kernel(now=True, newports=newports)
      File "/Users/andreamoro/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jupyter_client/manager.py", line 442, in restart_kernel
        self.shutdown_kernel(now=now, restart=True)
      File "/Users/andreamoro/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jupyter_client/manager.py", line 383, in shutdown_kernel
        self._kill_kernel()
      File "/Users/andreamoro/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jupyter_client/manager.py", line 487, in _kill_kernel
        raise RuntimeError("Cannot kill kernel. No kernel is running!")
    RuntimeError: Cannot kill kernel. No kernel is running!
```

**Comment by jasongrout** [comment]
This original issue is in IPython - transferring it to that repo.

@andreamoro - it looks like your other error is something completely different and unrelated (and from the traceback, in the jupyter_client repo).

**Comment by jasongrout** [comment]
Ah, looks like I cannot transfer the issue out of the org. Can you open a new issue in IPython? https://github.com/ipython/ipython/. Thanks!

As for your other issue about trying to shut down a kernel that isn't running - it's probably best to try to determine why the kernel died before the system knew about it. Perhaps there are other messages from the kernel above that error saying that the kernel died?

**Comment by andreamoro** [comment]
I'd say that the most consistent error is the one about the impossibility to write on the database.

Other than that, possible cause why a kernel died, I can only see me trying to manually shut them down or restart.

**Comment by andreamoro** [comment]
Just to be clear @jasongrout you want me to create the issue on that repo just for the history log file or for the error [here](https://github.com/jupyterlab/jupyterlab/issues/8914#issuecomment-681729668)?

**Comment by jasongrout** [comment]
The history log file error should be an issue in the IPython repo.

**Comment by andreamoro** [comment]
Done. Here the [URL](https://github.com/ipython/ipython/issues/12513) for reference. 

Can you tell anything about the other errors?

**Comment by jasongrout** [comment]
> Can you tell anything about the other errors?

Just that it looks like the kernel died somehow? I would start by looking at where it died and why.

**Comment by andreamoro** [comment]
Cheers @jasongrout. 

Minor other errors, which doesn't make sense. I've just started again the Jupyter lab to amend a project.
The project was left open since last interaction, so it re-opened consequently.

The log shown these 2 404 errors, one of it doesn't make sense as the image is in the project folder and it's correctly rendered on screen.

![image](https://user-images.githubusercontent.com/5256583/91661363-cdd13a00-eadb-11ea-92d7-ab24cddad144.png)

The custom.css, a murder mystery from where it comes from.
