### ISSUE TITLE
[LabBuildApp] Building jupyterlab assets (build:prod:minimize) Build failed.

### ISSUE THREAD

**Issue by RainliFu** [jupyterlab/jupyterlab#8984]
jupyter lab build fail 
```
➜  ~ jupyter lab build
[LabBuildApp] JupyterLab 2.2.7
[LabBuildApp] Building in /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /var/folders/3b/bfkw9z6n0n12wvs2290b4_lr0000gn/T/jupyterlab-debug-zo818djv.log
```
jupyter version
```
➜  ~ jupyter --v
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.17.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.7
nbconvert        : 6.0.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
```

`/var/folders/3b/bfkw9z6n0n12wvs2290b4_lr0000gn/T/jupyterlab-debug-zo818djv.log` info 

```
[LabBuildApp] Building in /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab
[LabBuildApp] Node v14.10.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /usr/local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Couldn't find package "@krassowski/jupyterlab_go_to_definition@~1.0.0" required by "@krassowski/jupyterlab-lsp@file:../extensions/krassowski-jupyterlab-lsp-2.0.4.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "lsp-ws-connection@~0.5.1" required by "@krassowski/jupyterlab-lsp@file:../extensions/krassowski-jupyterlab-lsp-2.0.4.tgz" on the "npm" registry.
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:310:30)
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@krassowski/completion-theme@~2.0.0" required by "@krassowski/jupyterlab-lsp@file:../extensions/krassowski-jupyterlab-lsp-2.0.4.tgz" on the "npm" registry.
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:310:30)
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@krassowski/theme-vscode@~2.0.0" required by "@krassowski/jupyterlab-lsp@file:../extensions/krassowski-jupyterlab-lsp-2.0.4.tgz" on the "npm" registry.
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:310:30)
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@krassowski/theme-material@~2.0.0" required by "@krassowski/jupyterlab-lsp@file:../extensions/krassowski-jupyterlab-lsp-2.0.4.tgz" on the "npm" registry.
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:310:30)
    at /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

```
➜  ~ jupyter labextension list
JupyterLab v2.2.7
Known labextensions:
   app dir: /usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab
        @krassowski/jupyterlab-lsp v2.0.4  enabled  OK
        jupyterlab-code-snippets v1.0.4  enabled  OK

Build recommended, please run `jupyter lab build`:
    @krassowski/jupyterlab-lsp needs to be included in build
```
I try `pip install -U jupyterlab ` and `brew upgrade nodejs`  but the error still.

thanks for help.

**Comment by RainliFu** [comment]
I  fix  this error  by unset proxy  and `jupyter lab clean && jupyter lab build `.

it's my proxy problem.
