### ISSUE TITLE
No Kernel! Python 3 | Dead. Threading has no module thread.

### ISSUE THREAD

**Issue by ed-muthiah** [jupyterlab/jupyterlab#9013]
## Description

Running on Windows 10 x64 and Google Chrome.

## Reproduce

1. Open Jupyter Lab using terminal command
2. print("Hello")
3. Shift + Enter

Result:
Nothing happens for a while, kernel keeps restarting then kernel not found. 

Error output:
````[I 04:09:48.212 LabApp] Writing notebook server cookie secret to C:\Users\Annamalai\AppData\Roaming\jupyter\runtime\notebook_cookie_secret
[I 04:09:48.724 LabApp] JupyterLab extension loaded from C:\Users\Annamalai\anaconda3\lib\site-packages\jupyterlab
[I 04:09:48.724 LabApp] JupyterLab application directory is C:\Users\Annamalai\anaconda3\share\jupyter\lab
[I 04:09:48.761 LabApp] Serving notebooks from local directory: C:\Users\Annamalai
[I 04:09:48.761 LabApp] The Jupyter Notebook is running at:
[I 04:09:48.761 LabApp] http://localhost:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
[I 04:09:48.761 LabApp] or http://127.0.0.1:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
[I 04:09:48.763 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:09:48.856 LabApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/Annamalai/AppData/Roaming/jupyter/runtime/nbserver-4948-open.html
Or copy and paste one of these URLs:
http://localhost:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
or http://127.0.0.1:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
[W 04:09:51.237 LabApp] Failed validating settings (@jupyterlab/extensionmanager-extension:plugin): Additional properties are not allowed ('disclaimed' was unexpected)

Failed validating 'additionalProperties' in schema:
{'additionalProperties': False,
'description': 'Extension manager settings.',
'jupyter.lab.setting-icon-class': 'jp-SettingsIcon',
'jupyter.lab.setting-icon-label': 'Extension Manager',
'properties': {'enabled': {'default': False,
'description': 'Enables extension manager '
'(requires Node.js/npm).\n'
'WARNING: installing '
'untrusted extensions may '
'be unsafe.',
'title': 'Enabled Status',
'type': 'boolean'}},
'title': 'Extension Manager',
'type': 'object'}

On instance:
{'disclaimed': True}
[W 04:09:52.159 LabApp] Could not determine jupyterlab build status without nodejs
[I 04:09:53.021 LabApp] Writing notebook-signing key to C:\Users\Annamalai\AppData\Roaming\jupyter\notebook_secret
[W 04:09:53.023 LabApp] Notebook Documents/Untitled4.ipynb is not trusted
[I 04:09:53.298 LabApp] Kernel started: 67dd395f-eb5e-4bcf-9c72-62fbb8c26165
Traceback (most recent call last):
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\connect.py", line 10, in 
from subprocess import Popen, PIPE
File "C:\Users\Annamalai\anaconda3\lib\subprocess.py", line 126, in 
import threading
File "C:\Users\Annamalai\Documents\threading.py", line 5, in 
class myThread(threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'
[I 04:09:56.282 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\connect.py", line 10, in 
from subprocess import Popen, PIPE
File "C:\Users\Annamalai\anaconda3\lib\subprocess.py", line 126, in 
import threading
File "C:\Users\Annamalai\Documents\threading.py", line 5, in 
class myThread(threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'
[I 04:09:59.282 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\connect.py", line 10, in 
from subprocess import Popen, PIPE
File "C:\Users\Annamalai\anaconda3\lib\subprocess.py", line 126, in 
import threading
File "C:\Users\Annamalai\Documents\threading.py", line 5, in 
class myThread(threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'```

@takluyver @afshin @ellisonbg

**Comment by ed-muthiah** [comment]
`[I 04:09:48.212 LabApp] Writing notebook server cookie secret to C:\Users\Annamalai\AppData\Roaming\jupyter\runtime\notebook_cookie_secret
[I 04:09:48.724 LabApp] JupyterLab extension loaded from C:\Users\Annamalai\anaconda3\lib\site-packages\jupyterlab
[I 04:09:48.724 LabApp] JupyterLab application directory is C:\Users\Annamalai\anaconda3\share\jupyter\lab
[I 04:09:48.761 LabApp] Serving notebooks from local directory: C:\Users\Annamalai
[I 04:09:48.761 LabApp] The Jupyter Notebook is running at:
[I 04:09:48.761 LabApp] http://localhost:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
[I 04:09:48.761 LabApp] or http://127.0.0.1:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
[I 04:09:48.763 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:09:48.856 LabApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/Annamalai/AppData/Roaming/jupyter/runtime/nbserver-4948-open.html
Or copy and paste one of these URLs:
http://localhost:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
or http://127.0.0.1:8888/?token=40388d91c08907b6e5ca5751a23d6702b2feea00e6d2d26c
[W 04:09:51.237 LabApp] Failed validating settings (@jupyterlab/extensionmanager-extension:plugin): Additional properties are not allowed ('disclaimed' was unexpected)

Failed validating 'additionalProperties' in schema:
{'additionalProperties': False,
'description': 'Extension manager settings.',
'jupyter.lab.setting-icon-class': 'jp-SettingsIcon',
'jupyter.lab.setting-icon-label': 'Extension Manager',
'properties': {'enabled': {'default': False,
'description': 'Enables extension manager '
'(requires Node.js/npm).\n'
'WARNING: installing '
'untrusted extensions may '
'be unsafe.',
'title': 'Enabled Status',
'type': 'boolean'}},
'title': 'Extension Manager',
'type': 'object'}

On instance:
{'disclaimed': True}
[W 04:09:52.159 LabApp] Could not determine jupyterlab build status without nodejs
[I 04:09:53.021 LabApp] Writing notebook-signing key to C:\Users\Annamalai\AppData\Roaming\jupyter\notebook_secret
[W 04:09:53.023 LabApp] Notebook Documents/Untitled4.ipynb is not trusted
[I 04:09:53.298 LabApp] Kernel started: 67dd395f-eb5e-4bcf-9c72-62fbb8c26165
Traceback (most recent call last):
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\connect.py", line 10, in 
from subprocess import Popen, PIPE
File "C:\Users\Annamalai\anaconda3\lib\subprocess.py", line 126, in 
import threading
File "C:\Users\Annamalai\Documents\threading.py", line 5, in 
class myThread(threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'
[I 04:09:56.282 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\connect.py", line 10, in 
from subprocess import Popen, PIPE
File "C:\Users\Annamalai\anaconda3\lib\subprocess.py", line 126, in 
import threading
File "C:\Users\Annamalai\Documents\threading.py", line 5, in 
class myThread(threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'
[I 04:09:59.282 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Annamalai\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Annamalai\anaconda3\lib\site-packages\ipykernel\connect.py", line 10, in 
from subprocess import Popen, PIPE
File "C:\Users\Annamalai\anaconda3\lib\subprocess.py", line 126, in 
import threading
File "C:\Users\Annamalai\Documents\threading.py", line 5, in 
class myThread(threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'
`

**Comment by agoose77** [comment]
This is because you've named a script `threading.py`, which is being found by `ipykernel` instead of the built-in threading module. You should rename that script, or move it out of the Python search path.

**Comment by jasongrout** [comment]
Closing as answered. Thanks!
