### ISSUE TITLE
terminado_settings/shell_command behaves confusingly and perhaps wrongly

### ISSUE THREAD

**Issue by athornton** [jupyterlab/jupyterlab#9014]
## Description

All I really want to do (in JL 2.2) is make the shell act like a login shell: specifically I want it to display the motd when the terminal session starts.

The documentation strongly hints that setting shell_command to `[ "/bin/bash", "-l" ]` should do the trick.  And indeed it seems that that's what's being run.

But then when I spawn a shell, no output prior to the prompt is printed.

## Reproduce

Put a `shell_command` in `terminado_settings` in `/usr/etc/jupyter/jupyter_notebook_config.json` forcing shell to `[ "/bin/bash", "-li" ]` to ensure that you get an interactive login shell.

Put something in ${HOME}/.bash_profile that echoes output to stdout and also echoes output to a file.  Such as:

```
#!/bin/bash
s="Eyecatcher output from .bash_profile"
date >> /tmp/shell-log.txt
echo $s >> /tmp/shell-log.txt
echo "----" >> /tmp/shell-log.txt
echo $s
```

## Expected behavior

I expected starting a terminal session to show the output  from .bash_profile.  It does not show output prior to the first prompt, although the existence of the file and its correct contents mean that `.bash_profile` was executed.

## Context

- Operating System and version:
Google COS, Kubernetes 1.17.9. 

- Browser and version:
Firefox 80.0.1

- JupyterLab version:
2.2.7
<details><summary>Troubleshoot Output</summary>
<pre>
[athornto@nb-athornto-exp-w-2020-37-motd ~]$ jupyter troubleshoot
$PATH:
        /home/athornto/bin
        /home/athornto/.local/bin
        /usr/local/texlive/2020/bin/x86_64-linux
        /usr/local/bin
        /home/athornto/bin
        /home/athornto/.local/bin
        /usr/local/texlive/2020/bin/x86_64-linux
        /usr/local/bin
        /sbin
        /bin
        /usr/sbin
        /usr/bin
        /usr/local/sbin
        /home/athornto/.local/bin
        /home/athornto/bin

sys.path:
        /usr/local/bin
        /usr/lib64/python36.zip
        /usr/lib64/python3.6
        /usr/lib64/python3.6/lib-dynload
        /usr/local/lib64/python3.6/site-packages
        /usr/local/lib/python3.6/site-packages
        /opt/lsst/src/thirdparty/jjs9
        /usr/lib64/python3.6/site-packages
        /usr/lib/python3.6/site-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.6.8 (default, Apr  2 2020, 13:34:55) 
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

platform.platform():
        Linux-4.19.112+-x86_64-with-centos-7.8.2003-Core

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        Package                     Version     Location
        --------------------------- ----------- -----------------------------
        aggdraw                     1.3.11
        aiocontextvars              0.2.2
        aiohttp                     3.6.2
        aioinflux                   0.9.0
        alembic                     1.4.3
        ansiwrap                    0.8.4
        aplus                       0.11.0
        appdirs                     1.4.4
        argo-workflows              3.2.0
        argon2-cffi                 20.1.0
        arrow                       0.16.0
        asgiref                     3.2.10
        astropy                     4.0.1.post1
        astropy-healpix             0.5
        astroquery                  0.4.1
        astrowidgets                0.1.1
        async-generator             1.10
        async-timeout               3.0.1
        attrs                       20.2.0
        awkward                     0.13.0
        awkward-numba               0.13.0
        backcall                    0.2.0
        beautifulsoup4              4.9.1
        binaryornot                 0.4.4
        black                       20.8b1
        bleach                      3.1.5
        bokeh                       2.2.1
        boltons                     20.2.1
        boto3                       1.14.60
        botocore                    1.17.60
        bqplot                      0.12.17
        branca                      0.4.1
        cachetools                  4.1.1
        certifi                     2020.6.20
        certipy                     0.1.3
        cffi                        1.14.2
        chardet                     3.0.4
        ciso8601                    2.1.3
        click                       7.1.2
        cloudpickle                 1.6.0
        colorama                    0.4.3
        colorcet                    2.0.2
        colored                     1.4.2
        contextvars                 2.4
        cookiecutter                1.7.2
        coverage                    5.2.1
        cryptography                3.1
        cycler                      0.10.0
        Cython                      0.29.21
        dask                        2.26.0
        dask-kubernetes             0.10.1
        dask-labextension           3.0.0
        dataclasses                 0.7
        datashader                  0.11.1
        datashape                   0.5.2
        decorator                   4.4.2
        defusedxml                  0.6.0
        distlib                     0.3.1
        distributed                 2.26.0
        docutils                    0.15.2
        ecdsa                       0.14.1
        eliot                       1.12.0
        eliot-tree                  19.0.1
        entrypoints                 0.3
        escapism                    1.0.1
        falcon                      2.0.0
        fastparquet                 0.4.1
        filelock                    3.0.12
        firefly-client              2.4.2
        fsspec                      0.8.2
        future                      0.18.2
        gcsfs                       0.7.1
        ginga                       3.1.0
        gitdb                       4.0.5
        GitPython                   3.1.8
        google                      3.0.0
        google-auth                 1.21.1
        google-auth-oauthlib        0.4.1
        graphviz                    0.14.1
        grpcio                      1.32.0
        h5py                        2.10.0
        healpy                      1.14.0
        HeapDict                    1.0.1
        holoviews                   1.13.3
        html5lib                    1.1
        hvplot                      0.6.0
        idna                        2.10
        idna-ssl                    1.1.0
        immutables                  0.14
        importlib-metadata          1.7.0
        importlib-resources         3.0.0
        iniconfig                   1.0.1
        intake                      0.6.0
        intake-parquet              0.2.3
        ipydatawidgets              4.0.1
        ipyevents                   0.8.0
        ipykernel                   5.3.4
        ipyleaflet                  0.13.3
        ipympl                      0.5.8
        ipython                     7.16.1
        ipython-genutils            0.2.0
        ipyvolume                   0.5.2
        ipyvue                      1.4.0
        ipyvuetify                  1.5.1
        ipywebrtc                   0.5.0
        ipywidgets                  7.5.1
        iso8601                     0.1.13
        jedi                        0.17.2
        jeepney                     0.4.3
        Jinja2                      2.11.2
        jinja2-time                 0.2.0
        jjs9                        1.0.0.dev0  /opt/lsst/src/thirdparty/jjs9
        jmespath                    0.10.0
        json5                       0.9.5
        jsonschema                  3.2.0
        jupyter                     1.0.0
        jupyter-client              6.1.7
        jupyter-console             6.2.0
        jupyter-core                4.6.3
        jupyter-firefly-extensions  2.0.1
        jupyter-server-proxy        1.5.0
        jupyter-telemetry           0.1.0
        jupyterhub                  1.1.0
        jupyterhub-jwtauthenticator 0.1
        jupyterhub-kubespawner      0.13.0
        jupyterlab                  2.2.7
        jupyterlab-iframe           0.2.2
        jupyterlab-pygments         0.1.1
        jupyterlab-server           1.2.0
        kapteyn                     2.3.1
        keyring                     21.4.0
        kiwisolver                  1.2.0
        kubernetes                  11.0.0
        kubernetes-asyncio          11.3.0
        llvmlite                    0.34.0
        locket                      0.2.0
        lsst-efd-client             0.5.0
        lxml                        4.5.2
        Mako                        1.1.3
        maproxy                     0.0.12
        Markdown                    3.2.2
        MarkupSafe                  1.1.1
        matplotlib                  3.3.1
        mimeparse                   0.1.3
        mistune                     0.8.4
        mock                        4.0.2
        modin                       0.8.0
        more-itertools              8.5.0
        msgpack                     1.0.0
        multidict                   4.7.6
        multipledispatch            0.6.0
        mypy-extensions             0.4.3
        mysqlclient                 2.0.1
        nbclient                    0.5.0
        nbconvert                   6.0.1
        nbdime                      2.0.0
        nbformat                    5.0.7
        nbreport                    0.7.4
        nbval                       0.9.6
        nclib                       1.0.0
        nest-asyncio                1.4.0
        notebook                    6.1.4
        numba                       0.51.2
        numexpr                     2.7.1
        numpy                       1.19.2
        oauthenticator              0.11.0
        oauthlib                    3.1.0
        packaging                   20.4
        pamela                      1.0.0
        pandas                      1.1.2
        pandocfilters               1.4.2
        panel                       0.9.7
        papermill                   2.1.3
        param                       1.9.3
        paramnb                     2.0.4
        parso                       0.8.0
        partd                       1.1.0
        pathspec                    0.8.0
        pbr                         5.5.0
        pexpect                     4.8.0
        pickleshare                 0.7.5
        Pillow                      7.2.0
        pip                         20.2.3
        pipenv                      2020.8.13
        pluggy                      0.13.1
        poyo                        0.5.0
        progressbar2                3.53.1
        prometheus-client           0.8.0
        prompt-toolkit              3.0.7
        protobuf                    3.13.0
        psutil                      5.7.2
        ptyprocess                  0.6.0
        py                          1.9.0
        py-spy                      0.3.3
        pyarrow                     1.0.1
        pyasn1                      0.4.8
        pyasn1-modules              0.2.8
        pycparser                   2.20
        pyct                        0.4.6
        Pygments                    2.7.0
        pyjs9                       3.1
        pyOpenSSL                   19.1.0
        pypandoc                    1.5
        pyparsing                   2.4.7
        pyrsistent                  0.16.0
        pyshp                       2.1.2
        pytest                      6.0.2
        python-dateutil             2.8.1
        python-editor               1.0.4
        python-engineio             3.13.2
        python-jose                 3.2.0
        python-json-logger          0.1.11
        python-slugify              4.0.1
        python-snappy               0.5.4
        python-socketio             4.6.0
        python-utils                2.4.0
        pythreejs                   2.2.0
        pytz                        2020.1
        pyviz-comms                 0.7.6
        pyvo                        1.1
        pywwt                       0.9.0
        PyYAML                      5.3.1
        pyzmq                       19.0.2
        qtconsole                   4.7.7
        QtPy                        1.9.0
        ray                         0.8.6
        redis                       3.4.1
        regex                       2020.7.14
        reproject                   0.7.1
        requests                    2.24.0
        requests-oauthlib           1.3.0
        rsa                         4.6
        ruamel.yaml                 0.16.12
        ruamel.yaml.clib            0.2.2
        rubin-jupyter-utils.config  0.30.2
        rubin-jupyter-utils.helpers 0.30.1
        rubin-jupyter-utils.hub     0.30.3
        rubin-jupyter-utils.lab     0.10.2
        s3fs                        0.2.2
        s3transfer                  0.3.3
        scipy                       1.5.2
        SecretStorage               3.1.2
        semver                      2.10.2
        Send2Trash                  1.5.0
        setuptools                  50.3.0
        sidecar                     0.4.0
        simpervisor                 0.3
        six                         1.15.0
        smmap                       3.0.4
        socketIO-client             0.7.2
        sortedcontainers            2.2.2
        soupsieve                   2.0.1
        SQLAlchemy                  1.3.19
        stevedore                   3.2.2
        swifter                     1.0.3
        tables                      3.6.1
        tabulate                    0.8.7
        tblib                       1.7.0
        tenacity                    6.2.0
        terminado                   0.8.3
        testpath                    0.4.4
        text-unidecode              1.3
        textwrap3                   0.9.2
        thrift                      0.13.0
        toml                        0.10.1
        toolz                       0.10.0
        tornado                     6.0.4
        tqdm                        4.48.2
        traitlets                   4.3.3
        traittypes                  0.2.1
        typed-ast                   1.4.1
        typing-extensions           3.7.4.3
        urllib3                     1.25.10
        vaex-arrow                  0.5.1
        vaex-astro                  0.7.0
        vaex-core                   2.0.3
        vaex-distributed            0.3.0
        vaex-hdf5                   0.6.0
        vaex-jupyter                0.5.2
        vaex-server                 0.3.1
        vaex-viz                    0.4.0
        virtualenv                  20.0.31
        virtualenv-clone            0.5.4
        virtualenvwrapper           4.8.4
        wcwidth                     0.2.5
        webencodings                0.5.1
        websocket-client            0.57.0
        wfdispatcher                0.4.0
        wheel                       0.35.1
        widgetsnbextension          3.5.1
        ws4py                       0.5.1
        WSGIserver                  1.3
        xarray                      0.16.0
        yarl                        1.5.1
        zict                        2.0.0
        zipp                        3.1.0
        zope.interface              5.1.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>

[W 2020-09-15 17:21:10.037 RubinLabApp configurable:168] Config option `open_browser` not recognized by `RubinLabApp`.  Did you mean one of: `browser, expose_app_in_browser`?
[W 2020-09-15 17:21:10.043 RubinLabApp configurable:168] Config option `open_browser` not recognized by `RubinLabApp`.  Did you mean one of: `browser, expose_app_in_browser`?
[W 2020-09-15 17:21:10.048 RubinLabApp configurable:168] Config option `open_browser` not recognized by `RubinLabApp`.  Did you mean one of: `browser, expose_app_in_browser`?
[W 2020-09-15 17:21:10.051 RubinLabApp configurable:168] Config option `open_browser` not recognized by `RubinLabApp`.  Did you mean one of: `browser, expose_app_in_browser`?
Inside terminal/init/initialize()!
User shell is ['/usr/local/bin/motdshell']
[W 2020-09-15 17:21:11.081 RubinLabApp notebookapp:1950] Error loading server extension js9server.js9ext
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'js9server'
2020-09-15 17:21:11,171 - INFO - firefly URL: https://nublado.lsst.codes/portal/app/
2020-09-15 17:21:11,172 - INFO - firefly Channel: ffChan-nb-athornto-exp-w-2020-37-motd-1600190471-49
[I 2020-09-15 17:21:12.049 RubinLabApp extension:162] JupyterLab extension loaded from /usr/local/lib/python3.6/site-packages/jupyterlab
[I 2020-09-15 17:21:12.049 RubinLabApp extension:163] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2020-09-15 17:21:12.733 RubinLabApp __init__:19] Loading Rubin hub_comm server extension.
[I 2020-09-15 17:21:12.754 RubinLabApp __init__:18] Loading Rubin Jupyter server Query extension.
[I 2020-09-15 17:21:12.755 RubinLabApp __init__:19] Loading rubinsettings server extension.
[I 2020-09-15 17:21:12.756 RubinLabApp notebookapp:1989] Will shut down after 43200 seconds with no kernels or terminals.
[I 2020-09-15 17:21:12.758 RubinLabApp singleuser:561] Starting jupyterhub-singleuser server version 1.1.0
[I 2020-09-15 17:21:12.773 RubinLabApp notebookapp:2209] Serving notebooks from local directory: /home/athornto
[I 2020-09-15 17:21:12.774 RubinLabApp notebookapp:2209] Jupyter Notebook 6.1.4 is running at:
[I 2020-09-15 17:21:12.774 RubinLabApp notebookapp:2209] http://nb-athornto-exp-w-2020-37-motd:8888/nb/user/athornto/
[I 2020-09-15 17:21:12.774 RubinLabApp notebookapp:2210] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2020-09-15 17:21:12.792 RubinLabApp singleuser:542] Updating Hub with activity every 300 seconds
2020-09-15 17:21:16,694 - INFO - get_firefly_url_data: returning: {"fireflyLabExtension": "true", "fireflyURL": "https://nublado.lsst.codes/portal/app/", "fireflyChannel": "ffChan-nb-athornto-exp-w-2020-37-motd-1600190471-49"}
[I 2020-09-15 17:21:19.937 RubinLabApp build_handler:47] Build is up to date
[I 2020-09-15 17:21:26.320 RubinLabApp kernelmanager:179] Kernel started: f2d9e395-ac8e-4d7f-a682-d2f757d2ce08, name: lsst
[I 2020-09-15 17:21:26.320 RubinLabApp kernelmanager:436] Culling kernels with idle durations > 43200 seconds at 300 second intervals ...
[I 2020-09-15 17:21:26.321 RubinLabApp kernelmanager:440] Culling kernels even with connected clients
[I 2020-09-15 17:21:26.362 RubinLabApp kernelmanager:179] Kernel started: 5248c421-d6a1-47f8-9976-aa613043b7e8, name: lsst
[I 2020-09-15 17:21:26.390 RubinLabApp kernelmanager:179] Kernel started: 61216a06-0b37-41a5-9ffa-0181c1f4bab0, name: python3
[I 2020-09-15 17:21:27.545 RubinLabApp kernelmanager:222] Starting buffering for 61216a06-0b37-41a5-9ffa-0181c1f4bab0:66923885-ba3b-4dd3-9ae6-995abd5563c4
Installing jupyterlab_iframe handler on path /nb/user/athornto/iframes
Handling iframes: []
Installing jupyterlab_iframe handler on path /nb/user/athornto/iframes
Handling iframes: []
[I 2020-09-15 17:21:37.694 RubinLabApp management:320] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Connection lost, reconnecting in 0 seconds. react_devtools_backend.js:2273:24
Starting WebSocket: wss://nublado.lsst.codes/nb/user/athornto/api/kernels/61216a06-0b37-41a5-9ffa-0181c1f4bab0 default.js:51
WebSocket is closed: {"isTrusted":true} WebSocketClient.js:97:12
Connection lost, reconnecting in 0 seconds. 2 react_devtools_backend.js:2273:24
Starting WebSocket: wss://nublado.lsst.codes/nb/user/athornto/api/kernels/f2d9e395-ac8e-4d7f-a682-d2f757d2ce08 default.js:51
Starting WebSocket: wss://nublado.lsst.codes/nb/user/athornto/api/kernels/5248c421-d6a1-47f8-9976-aa613043b7e8 default.js:51
Terminal websocket closed: 1001 react_devtools_backend.js:2273:24
Connection lost, reconnecting in 0 seconds. react_devtools_backend.js:2273:24
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. checkDeprecatedMixinEvents@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:43628:49
4R65/</Class.extend@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:43556:31
OTXi@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:195194:32
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
mGYY@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:381579:20
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
MIrW@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:187427:30
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
O3wJ@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:191774:32
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
xtrE@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:503626:18
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
12aA@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:16461:42
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
main@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:1311:14
EventListener.handleEvent*ANye@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:1829:8
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
1@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:238:18
__webpack_require__@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:85:30
checkDeferredModules@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:46:23
webpackJsonpCallback@https://nublado.lsst.codes/nb/user/athornto/static/lab/main.27dd662493faebc70833.js:33:19
@https://nublado.lsst.codes/nb/user/athornto/static/lab/vendors~main.feb87a2a0dc9c316b534.js:1:57
leaflet-src.js:395
Plugin 'jupyter.extensions.datawidgets' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1467
    ANye index.out.js:1516
    Webpack 6
index.es6.js:283
hub-extension: Found configuration  
Object { hubHost: "", hubPrefix: "/nb/hub/" }
index.js:31
Starting application in workspace: "/lab" index.js:50
JupyterLab extension jupyterlab_iframe is activated! index.js:166
Rubin query extension: activated index.js:39
rubin-labextensions-savequit: loaded. index.js:27
Starting WebSocket: wss://nublado.lsst.codes/nb/user/athornto/api/kernels/61216a06-0b37-41a5-9ffa-0181c1f4bab0 default.js:51
Connecting to wss://nublado.lsst.codes/portal/app//sticky/firefly/events?channelID=ffChan-nb-athornto-exp-w-2020-37-motd-1600190471-49 WebSocketClient.js:57:12
WebSocket connected.  connId:b channel:ffChan-nb-athornto-exp-w-2020-37-motd-1600190471-49 WebSocketClient.js:161:16
Starting WebSocket: wss://nublado.lsst.codes/nb/user/athornto/api/kernels/5248c421-d6a1-47f8-9976-aa613043b7e8 default.js:51
Starting WebSocket: wss://nublado.lsst.codes/nb/user/athornto/api/kernels/61216a06-0b37-41a5-9ffa-0181c1f4bab0 default.js:51
Starting WebSocket: wss://nublado.lsst.codes/nb/user/athornto/api/kernels/f2d9e395-ac8e-4d7f-a682-d2f757d2ce08 default.js:51
Error: widget model not found
    get_model manager.js:375
    renderModel renderer.js:38
    _rerender renderer.js:99
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    restoreWidgets manager.js:143
    manager_WidgetManager manager.js:77
    registerWidgetManager plugin.js:65
    createNew plugin.js:21
    _initializeWidget widgetmanager.js:75
    each index.es6.js:1561
    _initializeWidget widgetmanager.js:74
    createWidget widgetmanager.js:61
    _createOrOpenDocument manager.js:458
    open manager.js:276
    openOrReveal manager.js:300
    execute index.js:316
    promise callback*execute index.js:316
    execute index.es6.js:357
    values restorablepool.js:236
    restore restorablepool.js:228
    restore widgettracker.js:203
    restore layoutrestorer.js:182
    activateNotebookHandler index.js:359
    promise index.es6.js:162
    promise callback*N4GV/Application.prototype.activatePlugin index.es6.js:161
    resolveRequiredService index.es6.js:205
    required index.es6.js:155
    activatePlugin index.es6.js:155
    resolveRequiredService index.es6.js:205
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1467
    ANye index.out.js:1516
    Webpack 6
react_devtools_backend.js:2273:24
    overrideMethod react_devtools_backend.js:2273
    renderModel renderer.js:45
    _rerender renderer.js:99
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    restoreWidgets manager.js:143
    manager_WidgetManager manager.js:77
    registerWidgetManager plugin.js:65
    createNew plugin.js:21
    _initializeWidget widgetmanager.js:75
    each index.es6.js:1561
    _initializeWidget widgetmanager.js:74
    createWidget widgetmanager.js:61
    _createOrOpenDocument manager.js:458
    open manager.js:276
    openOrReveal manager.js:300
    execute index.js:316
    (Async: promise callback)
    execute index.js:316
    execute index.es6.js:357
    values restorablepool.js:236
    restore restorablepool.js:228
    restore widgettracker.js:203
    restore layoutrestorer.js:182
    activateNotebookHandler index.js:359
    promise index.es6.js:162
    (Async: promise callback)
    activatePlugin index.es6.js:161
    resolveRequiredService index.es6.js:205
    required index.es6.js:155
    activatePlugin index.es6.js:155
    resolveRequiredService index.es6.js:205
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1467
    (Async: EventListener.handleEvent)
    ANye index.out.js:1516
    Webpack 6
</pre>
</details>

**Comment by athornton** [comment]
Trying locally on a Mac, and `bash -l` doesn't display the motd, but a new iTerm2 session *does*, and neither a new terminal nor `bash -l` do within JupyterLab.  Responsibility for displaying the `motd` appears to rest with `/bin/login` which would be fine except that it *does* show up when `bash -l` is invoked in my actual target environment, which makes me suspect this is one of those things that BSD does differently from Linux, and The Internets are vague about what should happen.

**Comment by athornton** [comment]
Indeed, in my target environment, running just `bash` from a terminal window...prints the motd.  It does not when running locally.

**Comment by athornton** [comment]
Maybe the workaround is to move /etc/motd contents to a different file and put something in /etc/profile.d such that I test for interactivity, and if HAVE_SHOWN_JL_MOTD is empty, set and export it, and cat the file?  Gaaaah.

**Comment by athornton** [comment]
.....this may be crazy, but could terminado be suppressing/erasing all content prior to the shell prompt?

**Comment by athornton** [comment]
....that indeed seems to be what is happening.  With an updated file in /etc/profile.d, that looks like (execcing into a fresh container):

```
bash-4.2$ cd /tmp
bash-4.2$ ls
bash-4.2$ # Now I will go start a terminal session from JL...
bash-4.2$ # ...done
bash-4.2$ ls
npm-2006-bee35d50  terminal-log.txt
bash-4.2$ cat terminal-log.txt
Wed Sep 16 21:59:51 UTC 2020
Welcome to the Rubin Observatory Science Platform Notebook Aspect.

Find useful documentation for the software and Notebook Aspect at:
        https://pipelines.lsst.io
        https://nb.lsst.io

The Rubin Observatory Science Pipelines environment is in:

        /opt/lsst/software/stack

If you want to add your own configuration to LSST environment startup in the
LSST iPython kernel, create a sourceable shell fragment in:

        ${HOME}/notebooks/.user_setups

and it will be sourced during kernel startup.

To create a Rubin Observatory environment in a terminal session and set up
the full set of packages:

        source /opt/lsst/software/stack/loadLSST.bash
        setup lsst_distrib


------
```

One could replicate this (output prior to the shell prompt is swallowed, even though you can write files) with ${HOME}/.bash_profile, of course....which I am about to see if I can do locally.

**Comment by athornton** [comment]
Local replication.  Local JupyterLab (pip-installed).  No extras, no K8s, no funny launcher classes.

Nothing is displayed prior to the shell prompt when I open a new terminal, but ${HOME}/.bash_profile is being executed, and it does/should print something to stdout.

```
#!/bin/bash
s="Eyecatcher output from .bash_profile"
date >> /tmp/shell-log.txt
echo $s >> /tmp/shell-log.txt
echo "----" >> /tmp/shell-log.txt
echo $s
air-wired:tmp adam$ ls -l /tmp/shell*
ls: /tmp/shell*: No such file or directory
air-wired:tmp adam$ # Now I will open a terminal in JL
air-wired:tmp adam$ # ....done
air-wired:tmp adam$ ls -l /tmp/shell*
-rw-r--r--  1 adam  wheel  71 Sep 16 15:21 /tmp/shell-log.txt
air-wired:tmp adam$ cat /tmp/shell-log.txt
Wed Sep 16 15:21:03 MST 2020
Eyecatcher output from .bash_profile
----
air-wired:tmp adam$ bash -l
Eyecatcher output from .bash_profile

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
air-wired:tmp adam$ cat /tmp/shell-log.txt
Wed Sep 16 15:21:03 MST 2020
Eyecatcher output from .bash_profile
----
Wed Sep 16 15:21:20 MST 2020
Eyecatcher output from .bash_profile
----
```

**Comment by athornton** [comment]
Closing: opening new issue with minimal reproduction case.
