### ISSUE TITLE
JupyterLab failed to build

### ISSUE THREAD

**Issue by RGBYCP** [jupyterlab/jupyterlab#9016]
## Description

JupyterLab failed to build

## Reproduce

When I open jupyter-lab, it asks for build:
Build Recommended
JupyterLab build is suggested:
@jupyterlab/latex needs to be included in build
@jupyterlab/github needs to be included in build
nbdime-jupyterlab needs to be included in build
@jupyter-widgets/jupyterlab-manager needs to be included in build

I type in terminal: 
jupyter lab build

It fails: 

[LabBuildApp] JupyterLab 2.2.8
[LabBuildApp] Building in /anaconda3/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /var/folders/hy/lpgvb6d920s1g6_knj5sryc00000gn/T/jupyterlab-debug-sbn5zmrw.log

Content of log file:
[LabBuildApp] Building in /anaconda3/share/jupyter/lab
[LabBuildApp] Node v10.13.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
warning "nbdime-jupyterlab > nbdime@6.0.0" has unmet peer dependency "codemirror@^5.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 4.20s.

[LabBuildApp] > node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /anaconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.73s.

[LabBuildApp] > node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve 'module' in '/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/node'
    at factory.create (/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10)
    at factory (/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn42 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at resolver.doResolve (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at args (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn43 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve 'module' in '/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/node'
  Parsed request is a module
  using description file: /anaconda3/share/jupyter/lab/staging/node_modules/webpack/package.json (relative path: ./lib/node)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/node/node_modules doesn't exist or is not a directory
      /anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/node_modules doesn't exist or is not a directory
      /anaconda3/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /anaconda3/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /anaconda3/share/jupyter/node_modules doesn't exist or is not a directory
      /anaconda3/share/node_modules doesn't exist or is not a directory
      /anaconda3/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /anaconda3/share/jupyter/lab/staging/node_modules/webpack/node_modules
        using description file: /anaconda3/share/jupyter/lab/staging/node_modules/webpack/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /anaconda3/share/jupyter/lab/staging/node_modules
        using description file: /anaconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /anaconda3/share/jupyter/lab/staging/node_modules/webpack/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: /anaconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/webpack/node_modules/module doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/module doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/webpack/node_modules/module.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/module.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/webpack/node_modules/module.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/module.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/webpack/node_modules/module.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/module.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /anaconda3/share/jupyter/lab/staging/node_modules/webpack/node_modules/module.json doesn't exist
              /anaconda3/share/jupyter/lab/staging/node_modules/module.json doesn't exist
            as directory
              /anaconda3/share/jupyter/lab/staging/node_modules/webpack/node_modules/module doesn't exist
            as directory
              /anaconda3/share/jupyter/lab/staging/node_modules/module doesn't exist
child_process.js:632
    throw err;
    ^

Error: Command failed: /anaconda3/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Object.<anonymous> (/anaconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/anaconda3/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

## Context

- Operating System and version: macOS Mojave. 10.14.6
- Browser and version: Safari, Version 12.1.2 (14607.3.9)
- JupyterLab version: 2.2.8

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/anaconda3/bin
	/anaconda3/condabin
	/opt/local/bin
	/opt/local/sbin
	/usr/local/opt/openssl/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Applications/VMware Fusion.app/Contents/Public
	/Library/TeX/texbin
	/opt/X11/bin

sys.path:
	/anaconda3/bin
	/anaconda3/lib/python36.zip
	/anaconda3/lib/python3.6
	/anaconda3/lib/python3.6/lib-dynload
	/anaconda3/lib/python3.6/site-packages

sys.executable:
	/anaconda3/bin/python

sys.version:
	3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
	[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

platform.platform():
	Darwin-18.7.0-x86_64-i386-64bit

which -a jupyter:
	/anaconda3/bin/jupyter
	/usr/local/bin/jupyter
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by MagicJack** [comment]
If you're in windows env. Issue #9171 has the answer.

**Comment by jtpio** [comment]
@RGBYCP @MagicJack have you been able to update to JupyterLab 3+?

The latest version should not require rebuilding JupyterLab as often as before.

**Comment by MagicJack** [comment]
@RGBYCP Sorry for respond late.
Yes,
I can build JupyterLab 3.2.2 with python 3.9.7 and python 3.8.10 successfully, without any modification.
