### ISSUE TITLE
Cannot install extensions: RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by gioxc88** [jupyterlab/jupyterlab#9126]
## Description
whenever I try to install an extension I got this error:

`RecursionError: maximum recursion depth exceeded while calling a Python object`
See the log file for details:  C:\Users\******\AppData\Local\Temp\jupyterlab-debug-prbp2smb.log

After that if I try to start the lab with `jupyter-lab` the server starts and then suddenly gets automatically shut down saying "Failed to fetch" so I need to recreate the virtual environment but I cannot install any extension otherwise I will have same problem.

## Reproduce
I freshly installed python 3.8 and created a virtual env only installing jupyter and jupyterlab in it.
Then I do the following:
```
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
The second command generates the problem (I also tried with other extensions with the same outcome)

## Context
- Operating System and version:
- OS: Windows10
- Python 3.8.6 (also tried with 3.8.5)
- JupyterLab version: last version

## Log
Below I attach the log of the error

```
Node v12.16.1

Yarn configuration loaded.
> "C:\Program Files\nodejs\npm.CMD" pack @jupyter-widgets/jupyterlab-manager

Traceback (most recent call last):

  File "C:\Users\*******\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)

PermissionError: <unprintable PermissionError object>


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\*******\AppData\Local\Programs\Python\Python38\lib\tempfile.py", line 802, in onerror
    _os.unlink(path)

PermissionError: [WinError 5] Access is denied: 'C:\\Users\\*******\\AppData\\Local\\Temp\\tmp7b2t2w9d'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\*******\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\*******\\AppData\\Local\\Temp\\tmp7b2t2w9d'

```

**Comment by gioxc88** [comment]
any update on this?

**Comment by jasongrout** [comment]
I searched our issues for "windows permission error" (https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+is%3Aopen+windows+permission+error), and saw this similar-looking issue. Does the discussion there help you?

https://github.com/jupyterlab/jupyterlab/issues/7025

**Comment by gioxc88** [comment]
Sorry to bring this up but are there any update on this.
I tried to search on the internet for a long time but at the moment the only temporary fix, which is not a solution, seems to manually patch the `shutil` module as explained [here](https://github.com/jupyter-widgets/ipywidgets/issues/2365).

They said the fix should have been fixed with Python 3.8 but as I explained above I am using 3.8 and still got the error.

Thanks
