### ISSUE TITLE
Installing on Ubuntu 18 works, installing on Ubuntu 20 fails

### ISSUE THREAD

**Issue by adamgit** [jupyterlab/jupyterlab#9128]
## Description

I installed Ubuntu 18, installed jupyter-lab from apt -- all worked fine.

Upgrade to Ubuntu 20, and now jupyter-lab crashes on startup.

## Reproduce

With ubuntu 18 I was launching jupyter-lab like this:

~/.local/bin/jupyter-lab --port 8888

Several Jupyter-lab extensions require the latest Node.js, which requires Ubuntu 20, so I upgraded Ubuntu, and ... now Jupyter-lab crashes on startup:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
ModuleNotFoundError: No module named 'jupyterlab'

...nothing else has changed.

## Expected behavior

Presumably something in the OS upgrade now has created an incompatibility inside jupyter-lab - possibly the ubuntu package has a bug? - but I would expect a more meaningful error-message from jupyter-lab.

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: n/a
- JupyterLab version: 4.6.3

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/ubuntu/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/ubuntu/.local/bin
	/usr/lib/python38.zip
	/usr/lib/python3.8
	/usr/lib/python3.8/lib-dynload
	/usr/local/lib/python3.8/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.8.2 (default, Jul 16 2020, 14:00:26) 
	[GCC 9.3.0]

platform.platform():
	Linux-5.4.0-1025-aws-x86_64-with-glibc2.29

which -a jupyter:
	/home/ubuntu/.local/bin/jupyter
	/usr/bin/jupyter

pip list:
	Package                Version             
	---------------------- --------------------
	attrs                  19.3.0              
	Automat                0.8.0               
	backcall               0.1.0               
	bleach                 3.1.1               
	blinker                1.4                 
	certifi                2019.11.28          
	chardet                3.0.4               
	Click                  7.0                 
	cloud-init             20.3                
	colorama               0.4.3               
	command-not-found      0.3                 
	configobj              5.0.6               
	constantly             15.1.0              
	cryptography           2.8                 
	dbus-python            1.2.16              
	decorator              4.4.2               
	defusedxml             0.6.0               
	distro                 1.4.0               
	distro-info            0.23ubuntu1         
	ec2-hibinit-agent      1.0.0               
	entrypoints            0.3                 
	hibagent               1.0.1               
	html5lib               1.0.1               
	httplib2               0.14.0              
	hyperlink              19.0.0              
	idna                   2.8                 
	importlib-metadata     1.5.0               
	incremental            16.10.1             
	ipykernel              5.2.0               
	ipython                7.13.0              
	ipython-genutils       0.2.0               
	ipywidgets             6.0.0               
	jedi                   0.15.2              
	Jinja2                 2.10.1              
	jsonpatch              1.22                
	jsonpointer            2.0                 
	jsonschema             3.2.0               
	jupyter-client         6.1.2               
	jupyter-console        6.0.0               
	jupyter-core           4.6.3               
	keyring                18.0.1              
	language-selector      0.1                 
	launchpadlib           1.10.13             
	lazr.restfulclient     0.14.2              
	lazr.uri               1.0.3               
	MarkupSafe             1.1.0               
	mistune                0.8.4               
	more-itertools         4.2.0               
	nbconvert              5.6.1               
	nbformat               5.0.4               
	netifaces              0.10.4              
	notebook               6.0.3               
	oauthlib               3.1.0               
	pandocfilters          1.4.2               
	parso                  0.5.2               
	pexpect                4.6.0               
	pickleshare            0.7.5               
	pip                    20.0.2              
	prometheus-client      0.7.1               
	prompt-toolkit         2.0.10              
	pyasn1                 0.4.2               
	pyasn1-modules         0.2.1               
	Pygments               2.3.1               
	PyGObject              3.36.0              
	PyHamcrest             1.9.0               
	PyJWT                  1.7.1               
	pyOpenSSL              19.0.0              
	pyrsistent             0.15.5              
	pyserial               3.4                 
	python-apt             2.0.0+ubuntu0.20.4.1
	python-dateutil        2.7.3               
	python-debian          0.1.36ubuntu1       
	PyYAML                 5.3.1               
	pyzmq                  18.1.1              
	requests               2.22.0              
	requests-unixsocket    0.2.0               
	SecretStorage          2.3.1               
	Send2Trash             1.5.0               
	service-identity       18.1.0              
	setuptools             45.2.0              
	simplejson             3.16.0              
	six                    1.14.0              
	sos                    4.0                 
	ssh-import-id          5.10                
	systemd-python         234                 
	terminado              0.8.2               
	testpath               0.4.4               
	tornado                5.1.1               
	traitlets              4.3.3               
	Twisted                18.9.0              
	ubuntu-advantage-tools 20.3                
	ufw                    0.36                
	unattended-upgrades    0.1                 
	urllib3                1.25.8              
	wadllib                1.3.3               
	wcwidth                0.1.8               
	webencodings           0.5.1               
	wheel                  0.34.2              
	widgetsnbextension     2.0.0               
	zipp                   1.0.0               
	zope.interface         4.7.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
jupyter lab --debug
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
ModuleNotFoundError: No module named 'jupyterlab'
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by adamgit** [comment]
After some more investigation ... it seems that ubuntu20's upgrade process wiped both pip3 and everything pip had installed.

The jupyter-lab script was there as before, but I had to do:

sudo apt install python3-pip

and

pip3 install jupyter-lab

...and then everything worked as before, no further changes needed.
