### ISSUE TITLE
CP949 encoding error on Windows

### ISSUE THREAD

**Issue by hyungjun010** [jupyterlab/jupyterlab#9171]
## Description

When i was going to build jupyter lab, I faced an encoding error related to cp949 encoding for representing Korean character. 
I've debugged some code and now it runs well. 

I want to share my solution for Korean users, maybe it'll help more users.

## Reproduce

1. Go to Jupyter Lab Extension manager or Terminal on Windows 10 using Korean
2. Build some extension
3. Build Error 

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome
- JupyterLab version: 2.2.8

## Error messages
```
PS C:\Services\jupyterLab> Scripts\python -m jupyter lab build
[LabBuildApp] JupyterLab 2.2.8
[LabBuildApp] Building in c:\services\jupyterlab\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
|Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1267, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 263: illegal multibyte sequence

Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
IndexError: list index out of range
```

## Solution
1. Go to Jupyter Lab Installation Path(ex. Lib\site-packages\jupyterlab)
2. Insert the code to 88 line of [commands.py](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/commands.py#L88)
### Insert this line
```encoding="utf-8",```
### To
```
class ProgressProcess(Process):

    def __init__(self, cmd, logger=None, cwd=None, kill_event=None,
                 env=None):
        """Start a subprocess that can be run asynchronously.

        Parameters
        ----------
        cmd: list
            The command to run.
        logger: :class:`~logger.Logger`, optional
            The logger instance.
        cwd: string, optional
            The cwd of the process.
        kill_event: :class:`~threading.Event`, optional
            An event used to kill the process operation.
        env: dict, optional
            The environment for the process.
        """
        if not isinstance(cmd, (list, tuple)):
            raise ValueError('Command must be given as a list')

        if kill_event and kill_event.is_set():
            raise ValueError('Process aborted')

        self.logger = _ensure_logger(logger)
        self._last_line = ''
        self.cmd = cmd
        self.logger.debug('> ' + list2cmdline(cmd))

        self.proc = self._create_process(
            cwd=cwd,
            env=env,
            stderr=subprocess.STDOUT,
            stdout=subprocess.PIPE,
            [Insert Code]
            universal_newlines=True,
        )
        self._kill_event = kill_event or Event()

        Process._procs.add(self)
```

**Comment by jasongrout** [comment]
Can you submit a PR to jupyterlab with this change? It seems like we should have this fixed in core.

Thanks

**Comment by tpfmqks** [comment]
This works!
Thank you

**Comment by BrianKang-Webtools** [comment]
I'm using MacBook Pro and have the same problem, but I couldn't find the file named "commands.py" as I installed Jupyter notebook through Anaconda. Where is it?

**Comment by hyungjun010** [comment]
I'm sorry to my too late response.

I close this issue because I think that this issue is [resolved](https://github.com/jupyterlab/jupyterlab_server/pull/158) by these cool developers.

Thank you for your hard work.
