### ISSUE TITLE
Adding a new kernel - ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by ghuname** [jupyterlab/jupyterlab#9195]
I tried to install a new kernel. In order to do so I have done the following:

```
conda create -n test python=3.8.5
conda activate test
conda install -c anaconda ipykernel
python -m ipykernel install --user --name=test
```

I can see the new kernel "test" in jupyterlab, but after selecting that kernel for a  ipynb notebook, when executing `print('x')` in the notebook I get following:

```
[E 14:49:37.222 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 5a571e71-8b8a-42f9-a0f6-27db93607935)
[I 15:12:40.090 LabApp] Kernel started: c65411d9-b151-401e-a0b5-30002fb805dd
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
[I 15:12:43.083 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
[I 15:12:46.091 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
[I 15:12:49.101 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
[I 15:12:52.114 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Miniconda3\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
[W 15:12:55.128 LabApp] KernelRestarter: restart failed
[W 15:12:55.128 LabApp] Kernel c65411d9-b151-401e-a0b5-30002fb805dd died, removing from map.
```

- Operating System and version: Windows 10
- Browser and version: Any browser
- JupyterLab version: 2.0.0

After some searching I have found another example for creating a new environment on https://stackoverflow.com/a/53546634/3225309, but with no success.

What is the procedure for integration condas environments as jupyterlab's kernels?

**Comment by ghuname** [comment]
Can someone help with this?
I have uninstalled miniconda, installed it again and installed jupyter lab.
Everything works, but if I add new kernel as I described above, I get the same error.
How to trace this problem?
