### ISSUE TITLE
TAB completion failing

### ISSUE THREAD

**Issue by CodeCox** [jupyterlab/jupyterlab#9511]
TAB code completion is not working in v3.0 - only see a corresponding error in the log. 

1. edit a code cell
2. type `impo<TAB>`
3. code does not complete but error shows in log
(it errors for any code text in Step2)

Code should complete to `import` as it does in v2.  
(I have a freshly working jlab3 conda env and a existing jlab2 conda env so was able to verify!)

- Windows 10
- Brave 1.18 & Firefox 84.0
- jlab v3.0

<details><summary>Command Line Output</summary>
<pre>
[I 2020-12-26 21:27:17.271 ServerApp] jupyterlab | extension was successfully linked.
[I 2020-12-26 21:27:17.641 ServerApp] nbclassic | extension was successfully linked.
[I 2020-12-26 21:27:17.678 LabApp] JupyterLab extension loaded from C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\jupyterlab
[I 2020-12-26 21:27:17.678 LabApp] JupyterLab application directory is C:\Users\dev\Miniconda3\envs\jlab3\share\jupyter\lab
[I 2020-12-26 21:27:17.694 ServerApp] jupyterlab | extension was successfully loaded.
[I 2020-12-26 21:27:17.694 ServerApp] nbclassic | extension was successfully loaded.
[I 2020-12-26 21:27:17.972 ServerApp] Serving notebooks from local directory: C:\Users\dev
[I 2020-12-26 21:27:17.972 ServerApp] Jupyter Server 1.1.3 is running at:
[I 2020-12-26 21:27:17.972 ServerApp] http://localhost:8888/lab?token=b5598971dfe553081a14b94ffed60b2e303afc3bf0b99aa4
[I 2020-12-26 21:27:17.972 ServerApp]  or http://127.0.0.1:8888/lab?token=b5598971dfe553081a14b94ffed60b2e303afc3bf0b99aa4
[I 2020-12-26 21:27:17.972 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2020-12-26 21:27:18.085 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/dev/AppData/Roaming/jupyter/runtime/jpserver-276-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=b5598971dfe553081a14b94ffed60b2e303afc3bf0b99aa4
     or http://127.0.0.1:8888/lab?token=b5598971dfe553081a14b94ffed60b2e303afc3bf0b99aa4
[I 2020-12-26 21:27:23.157 LabApp] Build is up to date
[I 2020-12-26 21:27:36.184 ServerApp] Creating new notebook in /rad/pythin/lab
[I 2020-12-26 21:27:39.793 ServerApp] Kernel started: 8fc36b2a-790e-4dce-bac0-c70ade6ec16b
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\ipykernel\kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\ipykernel\kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\ipykernel\ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\ipykernel\ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\IPython\core\completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\IPython\core\completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\IPython\core\completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\IPython\core\completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\IPython\core\completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "C:\Users\dev\Miniconda3\envs\jlab3\lib\site-packages\jedi\api\__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'
</pre>
</details>

**Comment by hackengineer** [comment]
I had a similar issue which was solved by [rolling back jedi ](https://github.com/davidhalter/jedi/issues/1717) which was updated a couple days ago

**Comment by CodeCox** [comment]
Thanks @hackengineer -  resolved by rolling back `Jedi 0.18.0` to `0.17.2` as per your comment/link! 

_(Closing this issue - the incompatible dependancies hopefully will resolve in the near future.)_
