### ISSUE TITLE
tab completion of surrogate pairs causes error, possible regression of #2255

### ISSUE THREAD

**Issue by xzackli** [jupyterlab/jupyterlab#9524]
## Description

Attempting to tab-complete multiple surrogate pairs (i.e. 𝐚𝐚𝐚𝐚𝐚) in Jupyter leads to an AssertionError, probably related to https://github.com/jupyter/jupyter_client/issues/259, #2255, #2404.

## Reproduce

1. Fresh installation of anaconda/jupyter
2. Attempt to tab complete `\bfa{tab}\bfa{tab}` in jupyterlab. The first character is properly inserted, but not the second.

## Expected behavior

Typing 𝐚𝐚𝐚𝐚𝐚

## Context

- Operating System and version: tried on both Linux and WSL2
- Browser and version: Chrome, Edge
- JupyterLab version: 2.2.6 and 3.0

<details><summary>Command Line Output</summary>

<pre>
jupyter lab --debug --no-browser
</pre>
Then I enter `\bfa{tab}\bfa{tab}` into a Python notebook.
<pre>
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1859, in _completions
    cursor_line, cursor_column = position_to_cursor(full_text, offset)
  File "/home/zequnl/bin/anaconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 873, in position_to_cursor
    assert 0 <= offset <= len(text) , "0 <= %s <= %s" % (offset , len(text))
AssertionError: 0 <= 6 <= 5
</pre>
</details>

**Comment by stevengj** [comment]
`nbclassic` still seems like it has the surrogate-pair fix:  https://github.com/jupyter/nbclassic/blob/77cc49fc107e56437aa85a2038940ad80fdfcd14/nbclassic/static/notebook/js/completer.js#L157
