### ISSUE TITLE
lab extension vs labextension

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#9539]
With `jupyter_server` one needs to use `jupyter server extension list` to see extensions enabled at the server endpoint (`jupyter_server_config.d`) and not enable at the notebook endpoint (`jupyter_notebook_config.d`); it does not really matter for jupyter lab, because it enables itself on both:

https://github.com/jupyterlab/jupyterlab/blob/63c5989cddf6c3f519f3098a0c7fe376b5be064e/setup.py#L36-L39

However the 3.0 extensions by default enable themselves by default only on server, as per [cookicutter](https://github.com/jupyterlab/extension-cookiecutter-ts/blob/master/%7B%7Bcookiecutter.python_name%7D%7D/setup.py)). This means that the output of `jupyter server extension list` and `jupyter serverextension list` is different. I understand that this is expected, but lost too much time learning that - I wish it was mentioned in migration documentation (the confusing part was that I was seeing jupyterlab as enabled and ok so I thought that I am looking in the right place).

Now, it is not unexpected that a new user will do `jupyter lab extension list` after seeing `jupyter server extension list` instead of `jupyter labextension list`. I just did that out of curiosity. It worked but returned an error too:

```python
$ jupyter lab extension list
Config dir: /home/krassowski/.jupyter

Config dir: /home/krassowski/.pyenv/versions/3.7.9/envs/jupyterlab-lsp-lab3/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 0.9.3 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.0 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK

Config dir: /usr/local/etc/jupyter

Traceback (most recent call last):
  File "/~/.pyenv/versions/jupyterlab-lsp-lab3/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/~/.pyenv/versions/3.7.9/envs/jupyterlab-lsp-lab3/lib/python3.7/site-packages/jupyter_server/extension/application.py", line 486, in launch_instance
    serverapp.start()
  File "/~/.pyenv/versions/3.7.9/envs/jupyterlab-lsp-lab3/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 1846, in start
    self.start_app()
  File "/~/.pyenv/versions/3.7.9/envs/jupyterlab-lsp-lab3/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 1785, in start_app
    super(ServerApp, self).start()
  File "/~/.pyenv/versions/3.7.9/envs/jupyterlab-lsp-lab3/lib/python3.7/site-packages/jupyter_core/application.py", line 243, in start
    self.subapp.start()
  File "/~/.pyenv/versions/3.7.9/envs/jupyterlab-lsp-lab3/lib/python3.7/site-packages/jupyter_server/extension/serverextension.py", line 347, in start
    super(ServerExtensionApp, self).start()
  File "/~/.pyenv/versions/3.7.9/envs/jupyterlab-lsp-lab3/lib/python3.7/site-packages/jupyter_core/application.py", line 244, in start
    raise NoStart()
jupyter_core.application.NoStart
```

## Expected behavior

- If it is a supported command, no errors should be shown and documentation should be updated.
- If it is not supported, "use jupyter labextension (note no space in between)" should be shown.

## Context

- Operating System and version: Ubuntu
- JupyterLab version: 3.0.0

**Comment by rraadd88** [comment]
Hi, I am not sure if I should make a new issue for this, but I am getting the same error message (`jupyter_core.application.NoStart`) when I try to set up password. It seems that because of this error, I am unable to set password.
```
$ jupyter lab password
Enter password: 
Verify password: 
[JupyterPasswordApp] Wrote hashed password to /path/to/.jupyter/jupyter_server_config.json
Traceback (most recent call last):
  File "/path/to/anaconda3/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/path/to/anaconda3/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 500, in launch_instance
    serverapp.start()
  File "/path/to/anaconda3/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1966, in start
    self.start_app()
  File "/path/to/anaconda3/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1905, in start_app
    super(ServerApp, self).start()
  File "/path/to/anaconda3/lib/python3.8/site-packages/jupyter_core/application.py", line 244, in start
    raise NoStart()
jupyter_core.application.NoStart
```

**Comment by s-rog** [comment]
Finding this confusing as well

**Comment by haugstve** [comment]
Spent almost a day down the rabbit whole because of this. Maybe a warning or hint in the commands about the other lists to make it easier to understand and search for help?

**Comment by jtpio** [comment]
> It worked but returned an error too

In the case of entering `jupyter lab extension list` there should ideally be a warning like "Did you mean jupyter labextension?".
