### ISSUE TITLE
Tab Autocompletion Error with the latest jedi

### ISSUE THREAD

**Issue by BenjaminChoou** [jupyterlab/jupyterlab#9569]
Jupyter lab is not compatible with the latest jedi-0.18.0.

## Reproduce
1. use Tab to autocomplete code
2. See error 
```Traceback (most recent call last):
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/Users/benjaminchou/miniforge3/lib/python3.9/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column' 
```

## Context
- Operating System and version: Mac big sur 11.1
- Browser and version: Microsoft Edge Mac, Version 87.0.664.66
- JupyterLab version: 3.0.1

**Comment by blink1073** [comment]
This is being tracked in https://github.com/ipython/ipython/issues/12740, which has some recommended workarounds until another version of `ipython` is released.

**Comment by jasongrout** [comment]
> This is being tracked in [ipython/ipython#12740](https://github.com/ipython/ipython/issues/12740), which has some recommended workarounds until another version of `ipython` is released.

Thanks. Let's close this, then.
