### ISSUE TITLE
'tornado.web' has no attribute 'asynchronous' in jupyterlab==3.0.1

### ISSUE THREAD

**Issue by And370** [jupyterlab/jupyterlab#9573]
## Description

'tornado.web' has no attribute 'asynchronous'

It seems causing by the API upadation of tornado,but if I use tornado5,jupyterlab does not allowed.
It is replace @tornado.web.asynchronous to @tornado.gen.coroutine while tornado5 updating to tornado6.

## Reproduce

1. I use ```pip install jupyterlab==3.0.1``` in anaconda(python3.7.0) environment to install jupyterlab.
2. ```jupyterlab```
3. See error ```AttributeError: module 'tornado.web' has no attribute 'asynchronous'```

err detail info:
```
[I 2021-01-08 17:28:59.620 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-01-08 17:28:59.620 ServerApp] Serving notebooks from local directory: C:\Users\xxxx
[I 2021-01-08 17:28:59.621 ServerApp] Jupyter Server 1.2.0 is running at:
[I 2021-01-08 17:28:59.621 ServerApp] http://localhost:8888/lab?token=d475643b277657f71c451024934d1c63f464f22bdcfeec72
[I 2021-01-08 17:28:59.621 ServerApp]  or http://127.0.0.1:8888/lab?token=d475643b277657f71c451024934d1c63f464f22bdcfeec72
[I 2021-01-08 17:28:59.622 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-01-08 17:28:59.706 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/xxxx/AppData/Roaming/jupyter/runtime/jpserver-24800-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=d475643b277657f71c451024934d1c63f464f22bdcfeec72
     or http://127.0.0.1:8888/lab?token=d475643b277657f71c451024934d1c63f464f22bdcfeec72
[W 2021-01-08 17:29:06.966 LabApp] Could not determine jupyterlab build status without nodejs
[E 2021-01-08 17:29:07.033 ServerApp] Uncaught exception GET /api/nbconvert?1610098146120 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1610098146120', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\xxxx\Anaconda3\lib\site-packages\tornado\web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\xxxx\Anaconda3\lib\site-packages\tornado\web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\jupyter_server\services\nbconvert\handlers.py", line 13, in get
        from nbconvert.exporters import base
      File "C:\Users\xxxx\Anaconda3\lib\site-packages\nbconvert\__init__.py", line 7, in <module>
        from . import postprocessors
      File "C:\Users\xxxx\Anaconda3\lib\site-packages\nbconvert\postprocessors\__init__.py", line 5, in <module>
        from .serve import ServePostProcessor
      File "C:\Users\xxxx\Anaconda3\lib\site-packages\nbconvert\postprocessors\serve.py", line 19, in <module>
        class ProxyHandler(web.RequestHandler):
      File "C:\Users\xxxx\Anaconda3\lib\site-packages\nbconvert\postprocessors\serve.py", line 21, in ProxyHandler
        @web.asynchronous
    AttributeError: module 'tornado.web' has no attribute 'asynchronous'
[W 2021-01-08 17:29:07.045 ServerApp] Unhandled error
```

## Context

- Operating System and version: Windows10 1803
- Browser and version: Google Chrome 87.0.4280.88
- JupyterLab version: 3.0.1

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
What tornado version do you have installed?

**Comment by And370** [comment]
> What tornado version do you have installed?

6.1

**Comment by jasongrout** [comment]
Looks like the error is from nbconvert. Can you upgrade nbconvert too?

**Comment by And370** [comment]
> Looks like the error is from nbconvert. Can you upgrade nbconvert too?

I update nbconvert to 6.0.7,there's no err but a config warning 
```
[I 2021-01-08 18:04:29.644 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-01-08 18:04:29.720 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/xxxx/AppData/Roaming/jupyter/runtime/jpserver-18292-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=1c380b782c12db9cd6c7c25b249c7d5b3c124e3ee84304d1
     or http://127.0.0.1:8888/lab?token=1c380b782c12db9cd6c7c25b249c7d5b3c124e3ee84304d1
[W 2021-01-08 18:04:35.514 LabApp] Could not determine jupyterlab build status without nodejs
[W 2021-01-08 18:04:35.855 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-08 18:04:35.869 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-08 18:04:35.931 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-08 18:04:35.940 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-08 18:04:35.969 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-08 18:04:35.982 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
......
```

**Comment by jasongrout** [comment]
This is looking like an nbconvert upgrade issue now, not a jlab issue? Those Exporter things are nbconvert, not jlab.

**Comment by jasongrout** [comment]
Googling that error message lists a few helpful resources:

https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529
https://nbconvert.readthedocs.io/en/latest/changelog.html#significant-changes

**Comment by And370** [comment]
Thanks!

**Comment by jasongrout** [comment]
Closing as answered. If you have questions about the nbconvert upgrade, please ask in that repo.

Thanks!
