### ISSUE TITLE
`jupyter-labhub --help` fails with trace: `Failed collecting help-message for alias 'base-url', due to: 'base_url'`

### ISSUE THREAD

**Issue by dchirikov** [jupyterlab/jupyterlab#9608]
## Description

Unable to get description of available options of the `jupyter-labhub` executable:
```
$ jupyter-labhub --help
[E 2021-01-12 22:51:10.895 OverrideSingleUserNotebookApp application:421] Failed collecting help-message for alias 'base-url', due to: 'base_url'
Traceback (most recent call last):
  File "/home/user/venv/bin/jupyter-labhub", line 8, in <module>
    sys.exit(main())
  File "/home/user/venv/lib64/python3.9/site-packages/jupyterlab/labhubapp.py", line 530, in main
    return OverrideSingleUserNotebookApp.launch_instance(argv)
  File "/home/user/venv/lib64/python3.9/site-packages/jupyter_server/extension/application.py", line 492, in launch_instance
    _preparse_for_stopping_flags(cls, args)
  File "/home/user/venv/lib64/python3.9/site-packages/jupyter_server/extension/application.py", line 70, in _preparse_for_stopping_flags
    app.print_help('--help-all' in interpreted_argv)
  File "/home/user/venv/lib64/python3.9/site-packages/traitlets/config/application.py", line 511, in print_help
    print('\n'.join(self.emit_help(classes=classes)))
  File "/home/user/venv/lib64/python3.9/site-packages/traitlets/config/application.py", line 522, in emit_help
    for l in self.emit_options_help():
  File "/home/user/venv/lib64/python3.9/site-packages/traitlets/config/application.py", line 471, in emit_options_help
    for l in self.emit_alias_help():
  File "/home/user/venv/lib64/python3.9/site-packages/traitlets/config/application.py", line 406, in emit_alias_help
    trait = cls.class_traits(config=True)[traitname]
KeyError: 'base_url'

```

## Reproduce

```
jupyter-client==6.1.11
jupyter-core==4.7.0
jupyter-server==1.2.1
jupyter-telemetry==0.1.0
jupyterhub==1.3.0
jupyterlab==3.0.3
jupyterlab-pygments==0.1.2
jupyterlab-server==2.1.1
traitlets==5.0.5
```

`jupyter-labhub --help`

## Expected behavior

`--help` returns list of available options

**Comment by blink1073** [comment]
We just released https://pypi.org/project/jupyterlab/3.0.4/, which should fix this error.

**Comment by dchirikov** [comment]
Yes, this one is fixed. Thanks!
