### ISSUE TITLE
tornado error: uncaght exception, kernel does not exist, stream is closed

### ISSUE THREAD

**Issue by jwhendy** [jupyterlab/jupyterlab#9625]
Moving from [#5947](https://github.com/jupyter/notebook/issues/5947) where I opened in error initially.

---

Potentially related: [#2651](https://github.com/tornadoweb/tornado/issues/2651) (old/seems fixed?), [#2448](https://github.com/jupyterhub/jupyterhub/issues/2448) (related to jupyterhub which I'm not using), [#2834](https://github.com/tornadoweb/tornado/issues/2834) (seems resolved), [#401](https://github.com/jupyter/jupyter/issues/401) (suggests downgrading tornado or upgrading jupyter), [#4549](https://github.com/jupyter/notebook/issues/4549) (references [#2670](https://github.com/tornadoweb/tornado/pull/2670) which seems to indicate this was fixed).

I was just using jupyter lab yesterday for the first time in a while and had some packages to update due to my arch linux system having recently gone from python 3.8 to 3.9. I state this as it was functioning fine, however after closing my session and trying to open a new one, I'm now getting this error:
```
$ jupyter lab
[I 2021-01-15 12:09:21.142 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-01-15 12:09:21.166 LabApp] JupyterLab extension loaded from /home/jwhendy/.local/lib/python3.9/site-packages/jupyterlab
[I 2021-01-15 12:09:21.166 LabApp] JupyterLab application directory is /home/jwhendy/.local/share/jupyter/lab
[I 2021-01-15 12:09:21.169 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-01-15 12:09:21.172 ServerApp] Serving notebooks from local directory: /mnt/vault/projects/robots/paint-lines
[I 2021-01-15 12:09:21.173 ServerApp] Jupyter Server 1.2.1 is running at:
[I 2021-01-15 12:09:21.173 ServerApp] http://localhost:8888/lab?token=58a1e220042991e8e56d40958b5b2aae9c0c7d6125f14ffe
[I 2021-01-15 12:09:21.173 ServerApp]  or http://127.0.0.1:8888/lab?token=58a1e220042991e8e56d40958b5b2aae9c0c7d6125f14ffe
[I 2021-01-15 12:09:21.173 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-01-15 12:09:21.445 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jwhendy/.local/share/jupyter/runtime/jpserver-2105-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=58a1e220042991e8e56d40958b5b2aae9c0c7d6125f14ffe
     or http://127.0.0.1:8888/lab?token=58a1e220042991e8e56d40958b5b2aae9c0c7d6125f14ffe
[E 2021-01-15 12:09:23.486 ServerApp] Uncaught exception GET /lab/api/settings?1610734163295 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/settings?1610734163295', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/jwhendy/.local/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
    tornado.iostream.StreamClosedError: Stream is closed
[W 2021-01-15 12:09:24.838 ServerApp] 404 GET /api/kernels/5e49fe42-ee0d-48c7-82e3-547ed91f14cd/channels?session_id=8d2894df-6a26-4d66-b200-6573d1311ae1 (127.0.0.1): Kernel does not exist: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd
[W 2021-01-15 12:09:24.865 ServerApp] 404 GET /api/kernels/5e49fe42-ee0d-48c7-82e3-547ed91f14cd/channels?session_id=8d2894df-6a26-4d66-b200-6573d1311ae1 (127.0.0.1) 30.92ms referer=None
[I 2021-01-15 12:09:26.257 LabApp] Build is up to date
[W 2021-01-15 12:09:30.620 ServerApp] 404 GET /api/kernels/5e49fe42-ee0d-48c7-82e3-547ed91f14cd/channels?session_id=7cb96be5-d3ee-420a-9a50-8c3abb71adca (127.0.0.1): Kernel does not exist: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd
[W 2021-01-15 12:09:30.622 ServerApp] 404 GET /api/kernels/5e49fe42-ee0d-48c7-82e3-547ed91f14cd/channels?session_id=7cb96be5-d3ee-420a-9a50-8c3abb71adca (127.0.0.1) 6.22ms referer=None
[I 2021-01-15 12:09:32.460 ServerApp] Kernel started: 04e05056-81a8-4835-a2f2-d5a8f0552b20
[W 2021-01-15 12:09:39.248 ServerApp] Replacing stale connection: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd:8d2894df-6a26-4d66-b200-6573d1311ae1
[I 2021-01-15 12:09:51.344 ServerApp] Creating new notebook in 
[I 2021-01-15 12:09:51.650 ServerApp] Kernel started: f312ace4-188c-4bdd-94ad-8ba3fe3d0462
[W 2021-01-15 12:09:59.000 ServerApp] 404 GET /api/contents/Untitled4.ipynb?content=0&1610734198997 (127.0.0.1): No such file or directory: Untitled4.ipynb
[W 2021-01-15 12:09:59.000 ServerApp] No such file or directory: Untitled4.ipynb
[W 2021-01-15 12:09:59.000 ServerApp] 404 GET /api/contents/Untitled4.ipynb?content=0&1610734198997 (127.0.0.1) 1.11ms referer=http://localhost:8888/lab/tree/Untitled4.ipynb
[I 2021-01-15 12:09:59.005 ServerApp] Uploading file to /Untitled4.ipynb
g[W 2021-01-15 12:10:12.192 ServerApp] Replacing stale connection: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd:7cb96be5-d3ee-420a-9a50-8c3abb71adca
[W 2021-01-15 12:10:15.203 ServerApp] Got events for closed stream None
[W 2021-01-15 12:10:32.611 ServerApp] Replacing stale connection: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd:8d2894df-6a26-4d66-b200-6573d1311ae1
[W 2021-01-15 12:10:53.014 ServerApp] Replacing stale connection: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd:7cb96be5-d3ee-420a-9a50-8c3abb71adca
[W 2021-01-15 12:11:22.858 ServerApp] Replacing stale connection: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd:7cb96be5-d3ee-420a-9a50-8c3abb71adca
[I 2021-01-15 12:11:32.523 ServerApp] Saving file at /paint-lines.ipynb
[W 2021-01-15 12:11:43.726 ServerApp] Replacing stale connection: 5e49fe42-ee0d-48c7-82e3-547ed91f14cd:8d2894df-6a26-4d66-b200-6573d1311ae1
[I 2021-01-15 12:11:52.517 ServerApp] Saving file at /Untitled2.ipynb
```

Code blocks never finish running and syntax highlighting doesn't work either.

```
$ pip freeze ## kindly let me know if other packages are relevant
jupyter==1.0.0
jupyter-client==6.1.11
jupyter-console==6.2.0
jupyter-core==4.7.0
jupyter-server==1.2.1
jupyterlab==3.0.5
jupyterlab-pygments==0.1.2
jupyterlab-server==2.1.1
jupyterlab-widgets==1.0.0
ipykernel==5.4.3
ipython==7.19.0
ipython-genutils==0.2.0
tornado==6.1

$ python --version
Python 3.9.1
```

Things I've tried:
- [update](https://stackoverflow.com/a/3452888/495990) all pip packages
- `jupyter lab clean` and `jupyter lab build`
- the above, after deleting `~/.local/share/jupyter` completely
- uninstalling all local pip packages and reinstalling jupyterlab
- tried to piece together versions that can work with tornado 5.1.1 as downgrading was widely suggested as the workaround circa 2019

With the last one, I'm still stuck. Nothing runs and I get:
```
[W 12:38:39.292 LabApp] 404 GET /api/kernels/04e05056-81a8-4835-a2f2-d5a8f0552b20/channels?session_id=1fca15ef-7555-4157-a2e4-3ccbaf884c70 (127.0.0.1): Kernel does not exist: 04e05056-81a8-4835-a2f2-d5a8f0552b20
```

Any insights into how I can get out of this mess?

**Comment by jwhendy** [comment]
I was rebuilding various Robot Operating System (ROS) things and went to debug again, updating tornado back to 6.1 as I'd left it at 5.1.1 trying to revert to a magical ecosystem that would play nicely. So far, it's working. After a `jupyter lab clean` and `jupyter lab build`, the only lingering [non-critical] errors are:
```
[W 10:16:13.306 LabApp] 404 GET /api/contents/Untitled3.ipynb?content=0&1610986573047 (127.0.0.1): No such file or directory: Untitled3.ipynb
[W 10:16:13.307 LabApp] No such file or directory: Untitled3.ipynb
[W 10:16:13.307 LabApp] 404 GET /api/contents/Untitled3.ipynb?content=0&1610986573047 (127.0.0.1) 3.29ms referer=http://localhost:8888/lab
[W 10:16:13.644 LabApp] Notebook Untitled.ipynb is not trusted
[W 10:16:13.665 LabApp] Notebook Untitled1.ipynb is not trusted
[W 10:16:13.687 LabApp] Notebook Untitled4.ipynb is not trusted
```

I'll give this a week and if all goes well, close as a "who knows." If anyone has suggestions/bread crumbs from past experience so that someone searching in the future could pinpoint and understand the cause, that would still be awesome. I had a really hard time sorting through the Venn diagram of output to find exactly this (could find tornado errors, but not "kernel does not exist"; "kernel does not exist" but not "await result", etc.).

**Comment by jasongrout** [comment]
> `[W 10:16:13.306 LabApp] 404 GET /api/contents/Untitled3.ipynb?content=0&1610986573047 (127.0.0.1): No such file or directory: Untitled3.ipynb`

These often happen if jlab was started and the closed while that file was open. Next time jlab comes up, it will try to bring up that file so you can pick up where you left off, but sometimes that file does not exist anymore (or jlab was not started in the same directory, so it can't find the file).

**Comment by kaddkaka** [comment]
I installed jupyter-notebook and some packages like this:

```
pipx install notebook
cd ~/.local/share/pipx/venvs/notebook
source bin/activate
python3 -m pip install matplotlib
python3 -m pip install pandas
python3 -m pip install seaborn
```

Now when I start jupyter-notebook from this activated virtualenv, it sarts but I get a lot of warnings and errors:
```
[W 2025-02-28 13:57:35.562 ServerApp] 404 GET /api/kernels/23fdb3e0-fbb1-4c02-8f1c-0f5a144e86a8?1740747455560 (127.0.0.1): Kernel does not exist: 23fdb3e0-fbb1-4c02-8f1c-0f5a144e86a8
[W 2025-02-28 13:57:35.562 ServerApp] wrote error: 'Kernel does not exist: 23fdb3e0-fbb1-4c02-8f1c-0f5a144e86a8'
    Traceback (most recent call last):
      File "~/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "~/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "~/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "~/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 23fdb3e0-fbb1-4c02-8f1c-0f5a144e86a8)
```

```
[E 2025-02-28 14:01:44.943 ServerApp] nbconvert failed: PandocMissing("Pandoc wasn't found.\nPlease check that pandoc is installed:\nhttps://pandoc.org/installing.html")
```

I post this here as the similar issue created at https://github.com/jupyter/notebook/issues/5947 was moved here.

I know too little to judge if this is related to notebook or jupyterlab.

**Comment by alexander-esser** [comment]
Some ideas for solving this issue:

1. **Upgrade / re-install the corresponding Python packages**
As said before, uninstall `jupyter`, all `jupyter`-related packages and also `anyio` and `tornado`, as they also seem to be involved:

```
pip uninstall -y jupyter jupyter_client jupyter-console jupyter_core jupyter-events jupyter-lsp jupyter_server jupyter_server_terminals jupyterlab jupyterlab_pygments jupyterlab_server jupyterlab_widgets anyio tornado
```

Then, re-install them:

```
pip install -y jupyter jupyter_client jupyter-console jupyter_core jupyter-events jupyter-lsp jupyter_server jupyter_server_terminals jupyterlab jupyterlab_pygments jupyterlab_server jupyterlab_widgets
```


Compatible versions of `anyio` and `tornado` will be installed automatically, as they are dependencies of `jupyter`.

2. **Code in network / cloud drive?**
In my case, an additional reason was that the code was located in a network folder / synchronized cloud folder.

3. **Deleting *.ipynb_checkpoints***
ChatGPT recommended to delete the *.ipynb_checkpoints* subfolder with old checkpoints, as loading them can cause the issue on start-up.

4. **Reference to [https://github.com/python/cpython/issues/70647](https://github.com/python/cpython/issues/70647)**
In the Jupyter error logs, there is also a reference to this open issue: https://github.com/python/cpython/issues/70647
