### ISSUE TITLE
Opening JupyterLab 3.0 in Chrome app mode

### ISSUE THREAD

**Issue by gioarma** [jupyterlab/jupyterlab#9676]
With Jupyterlab 2.0 I used to open the application in the Chrome app mode with (as suggested in #5317):

`c.LabApp.browser = '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app=%s'`

And it used to work perfectly launching Jupyter Lab from the terminal.
Since installing Jupyterlab 3.0, this is what happens instead:

- If Firefox (default browser on my pc) is already open, JupyterLab opens in a new Firefox tab, instead of Chrome app mode
- If Firefox is not open, Jupyterlab does not even open in the browser, even if on the terminal I see printed the usual info. For it to work I have to open up Firefox and launch JupyterLab again.

So in any case I'm not able to launch JupyterLab in app mode on Chrome.

I get a series of errors printed out on the terminal when I launch the app, I post them here in case they could help solve the issue:

<details>
<summary>Terminal output when launching JupyterLab</summary>

```bash
[W 2021-01-26 16:04:11.989 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:12.010 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:12.070 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:12.079 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:12.110 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:12.125 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:12.156 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:12.171 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[E 2021-01-26 16:04:13.239 ServerApp] Uncaught exception GET /api/nbconvert?1611673450469 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1611673450469', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_server/services/nbconvert/handlers.py", line 17, in get
        exporters = base.get_export_names()
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/opt/anaconda3/lib/python3.7/site-packages/nbinteract/exporters.py", line 125, in __init__
        self.template_path.insert(
    AttributeError: 'InteractExporter' object has no attribute 'template_path'
[W 2021-01-26 16:04:13.245 ServerApp] Unhandled error
[E 2021-01-26 16:04:13.246 ServerApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0",
      "Accept": "*/*",
      "Accept-Language": "it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token a3abc6550b99e6b418b5c8a4f82f9d19fc05747d12323d17",
      "X-Xsrftoken": "2|2f8edee6|3d1e678e5d3e53ad35b49391cc47a20e|1611526861",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1611673449|23:username-localhost-8888|44:YmUyNDBjMDBjMmNiNGFhYThiZjdlOTgxZmYzZWEzOWM=|61d5185c2561c31d4f74bf6d1a362b22393de941ac3a4bc9e4775c669808eb05\"; _xsrf=2|2f8edee6|3d1e678e5d3e53ad35b49391cc47a20e|1611526861",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 2021-01-26 16:04:13.246 ServerApp] 500 GET /api/nbconvert?1611673450469 (127.0.0.1) 1614.10ms referer=http://localhost:8888/lab
[W 2021-01-26 16:04:13.354 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:13.371 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:13.424 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:13.432 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:13.451 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:13.467 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:13.492 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-01-26 16:04:13.505 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[E 2021-01-26 16:04:13.551 ServerApp] Uncaught exception GET /api/nbconvert?1611673450500 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1611673450500', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_server/services/nbconvert/handlers.py", line 17, in get
        exporters = base.get_export_names()
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/opt/anaconda3/lib/python3.7/site-packages/nbinteract/exporters.py", line 125, in __init__
        self.template_path.insert(
    AttributeError: 'InteractExporter' object has no attribute 'template_path'
[W 2021-01-26 16:04:13.552 ServerApp] Unhandled error
[E 2021-01-26 16:04:13.552 ServerApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0",
      "Accept": "*/*",
      "Accept-Language": "it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token a3abc6550b99e6b418b5c8a4f82f9d19fc05747d12323d17",
      "X-Xsrftoken": "2|2f8edee6|3d1e678e5d3e53ad35b49391cc47a20e|1611526861",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1611673449|23:username-localhost-8888|44:YmUyNDBjMDBjMmNiNGFhYThiZjdlOTgxZmYzZWEzOWM=|61d5185c2561c31d4f74bf6d1a362b22393de941ac3a4bc9e4775c669808eb05\"; _xsrf=2|2f8edee6|3d1e678e5d3e53ad35b49391cc47a20e|1611526861",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 2021-01-26 16:04:13.552 ServerApp] 500 GET /api/nbconvert?1611673450500 (127.0.0.1) 1918.73ms referer=http://localhost:8888/lab
Generating grammar tables from /opt/anaconda3/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /Users/giovanni/Library/Caches/black/20.8b1/Grammar3.7.8.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/Users/giovanni/Library/Caches/black/20.8b1/tmpjdil70ry'
Generating grammar tables from /opt/anaconda3/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /Users/giovanni/Library/Caches/black/20.8b1/PatternGrammar3.7.8.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/Users/giovanni/Library/Caches/black/20.8b1/tmpxpbof0pz'
```

</details>

**Comment by krassowski** [comment]
I use JupyterLab 3.x in Chrome app mode without issues, although I pass my config via command line arguments.

Where do you put the line of code that you provided? The location of config files has changed with the [migration](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#jupyter-server) to `jupyter_server`; if you have not done so I would recommend you to migrate your config as [described here](https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html).

I would also make sure that you have the latest `jupyter_server` version installed, as there were [recent improvements](https://github.com/jupyterlab/jupyterlab_server/commit/f35feff814a109184452d536ab43425ac74ea6a8) on the browser opening handling.

**Comment by gioarma** [comment]
Yes, following the migration guide I solved the issue.
Thanks a lot!
