### ISSUE TITLE
Error starting kernel: Unhandled error

### ISSUE THREAD

**Issue by yanniskatsaros** [jupyterlab/jupyterlab#9726]
## Description

Upon starting `jupyter lab` from the command line and clicking on a new (or existing) notebook, I get the following error message:

![image](https://user-images.githubusercontent.com/32942328/106661557-f36cde80-6566-11eb-8869-653dbc02305b.png)

Any attempt to restart the kernel, select a new kernel etc. results in the same issue.

## Reproduce

Run `jupyter lab` from the command line, open a new new (or existing) notebook, when prompted select "Python 3" for the kernel.

## Context

- Operating System and version: Windows 10 Pro, Version 10.0.18363 Build 18363
- Browser and version: Firefox 84.0.1
- Python version: 3.7.1
- JupyterLab version: 2.2.9

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\Library\mingw-w64\bin
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\Library\usr\bin
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\Library\bin
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\Scripts
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\bin
        C:\Users\Yannis.Katsaros\Miniconda3\condabin
        C:\Program Files (x86)\Common Files\Oracle\Java\javapath
        C:\Program Files\Git\mingw64\bin
        C:\Program Files\Git\usr\bin
        C:\Program Files\Git\cmd
        C:\Python39\Scripts
        C:\Python39
        C:\ProgramData\chocolatey\bin
        C:\Program Files\nodejs
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        _C:\WINDOWS\System32\OpenSSH
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn
        C:\Program Files\Azure Data Studio\bin
        C:\Program Files\Microsoft SQL Server\110\Tools\Binn
        C:\Program Files\dotnet
        C:\Program Files\Microsoft SQL Server\130\Tools\Binn
        C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn
        C:\Users\Yannis.Katsaros\Miniconda3
        C:\Users\Yannis.Katsaros\Miniconda3\Library\mingw-w64\bin
        C:\Users\Yannis.Katsaros\Miniconda3\Library\usr\bin
        C:\Users\Yannis.Katsaros\Miniconda3\Library\bin
        C:\Users\Yannis.Katsaros\Miniconda3\Scripts
        C:\Users\Yannis.Katsaros\AppData\Local\Microsoft\WindowsApps
        C:\Users\Yannis.Katsaros\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Users\Yannis.Katsaros\AppData\Roaming\npm
        C:\Users\Yannis.Katsaros\.dotnet\tools

sys.path:
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\Scripts
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\python37.zip
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\DLLs
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\win32
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\win32\lib
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\Pythonwin

sys.executable:
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\python.exe

sys.version:
        3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 13:32:59) [MSC v.1900 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.18362-SP0

where jupyter:
        C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\Scripts\jupyter.exe

pip list:
        Package                       Version
        ----------------------------- -------------------
        argon2-cffi                   20.1.0
        async-generator               1.10
        attrs                         20.3.0
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.1
        bleach                        3.3.0
        brotlipy                      0.7.0
        certifi                       2020.12.5
        cffi                          1.14.4
        chardet                       4.0.0
        colorama                      0.4.4
        cryptography                  3.3.1
        decorator                     4.4.2
        defusedxml                    0.6.0
        entrypoints                   0.3
        idna                          2.10
        importlib-metadata            3.4.0
        ipykernel                     5.1.0
        ipython                       7.20.0
        ipython-genutils              0.2.0
        jedi                          0.18.0
        Jinja2                        2.11.3
        json5                         0.9.5
        jsonschema                    3.2.0
        jupyter-client                6.1.11
        jupyter-core                  4.7.1
        jupyterlab                    2.2.9
        jupyterlab-pygments           0.1.2
        jupyterlab-server             1.2.0
        MarkupSafe                    1.1.1
        mistune                       0.8.4
        nbclient                      0.5.1
        nbconvert                     6.0.7
        nbformat                      5.1.2
        nest-asyncio                  1.4.3
        notebook                      6.2.0
        numpy                         1.15.4
        packaging                     20.8
        pandas                        0.23.4
        pandocfilters                 1.4.2
        parso                         0.8.1
        pickleshare                   0.7.5
        pip                           20.3.3
        prometheus-client             0.9.0
        prompt-toolkit                3.0.14
        pycparser                     2.20
        Pygments                      2.7.4
        pyOpenSSL                     20.0.1
        pyparsing                     2.4.7
        pyrsistent                    0.17.3
        PySocks                       1.7.1
        python-dateutil               2.8.1
        pytz                          2021.1
        pywin32                       300
        pywinpty                      0.5.7
        pyzmq                         22.0.1
        requests                      2.25.1
        scikit-learn                  0.20.2
        scipy                         1.1.0
        Send2Trash                    1.5.0
        setuptools                    52.0.0.post20210125
        six                           1.15.0
        terminado                     0.9.2
        testpath                      0.4.4
        tornado                       6.1
        traitlets                     5.0.5
        typing-extensions             3.7.4.3
        urllib3                       1.26.3
        wcwidth                       0.2.5
        webencodings                  0.5.1
        wheel                         0.36.2
        win-inet-pton                 1.1.0
        wincertstore                  0.2
        zipp                          3.4.0

conda list:
        # packages in environment at C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql:
        #
        # Name                    Version                   Build  Channel
        argon2-cffi               20.1.0           py37hcc03f2d_2    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     20.3.0             pyhd3deb0d_0    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                        py_2    conda-forge
        backports.functools_lru_cache 1.6.1                      py_0    conda-forge
        blas                      1.0                         mkl
        bleach                    3.3.0              pyh44b312d_0    conda-forge
        brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge
        ca-certificates           2020.12.5            h5b45459_0    conda-forge
        certifi                   2020.12.5        py37h03978a9_1    conda-forge
        cffi                      1.14.4           py37hd8e9650_1    conda-forge
        chardet                   4.0.0            py37h03978a9_1    conda-forge
        colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
        cryptography              3.3.1            py37hd8e9650_1    conda-forge
        decorator                 4.4.2                      py_0    conda-forge
        defusedxml                0.6.0                      py_0    conda-forge
        entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
        icc_rt                    2019.0.0             h0cc432a_1
        idna                      2.10               pyh9f0ad1d_0    conda-forge
        importlib-metadata        3.4.0            py37h03978a9_0    conda-forge
        importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
        intel-openmp              2020.2                      254
        ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
        ipython                   7.20.0           py37heaed05f_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        jedi                      0.18.0           py37h03978a9_2    conda-forge
        jinja2                    2.11.3             pyh44b312d_0    conda-forge
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonschema                3.2.0                      py_2    conda-forge
        jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
        jupyter_core              4.7.1            py37h03978a9_0    conda-forge
        jupyterlab                2.2.9              pyhd8ed1ab_0    conda-forge
        jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
        jupyterlab_server         1.2.0                      py_0
        libblas                   3.9.0                     7_mkl    conda-forge
        libcblas                  3.9.0                     7_mkl    conda-forge
        liblapack                 3.9.0                     7_mkl    conda-forge
        libsodium                 1.0.18               h8d14728_1    conda-forge
        m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
        m2w64-gcc-libs            5.3.0                         7    conda-forge
        m2w64-gcc-libs-core       5.3.0                         7    conda-forge
        m2w64-gmp                 6.1.0                         2    conda-forge
        m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
        markupsafe                1.1.1            py37hcc03f2d_3    conda-forge
        mistune                   0.8.4           py37hcc03f2d_1003    conda-forge
        mkl                       2020.4             hb70f87d_311    conda-forge
        msys2-conda-epoch         20160418                      1    conda-forge
        nbclient                  0.5.1                      py_0    conda-forge
        nbconvert                 6.0.7            py37h03978a9_3    conda-forge
        nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
        nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
        notebook                  6.2.0            py37h03978a9_0    conda-forge
        numpy                     1.15.4          py37h8078771_1002    conda-forge
        openssl                   1.1.1i               h8ffe710_0    conda-forge
        packaging                 20.8               pyhd3deb0d_0    conda-forge
        pandas                    0.23.4          py37h830ac7b_1000    conda-forge
        pandoc                    2.11.4               h8ffe710_0    conda-forge
        pandocfilters             1.4.2                      py_1    conda-forge
        parso                     0.8.1              pyhd8ed1ab_0    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pip                       20.3.3           py37haa95532_0
        prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
        prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
        pycparser                 2.20               pyh9f0ad1d_2    conda-forge
        pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
        pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
        pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
        pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge
        pysocks                   1.7.1            py37h03978a9_3    conda-forge
        python                    3.7.1             h9460c21_1003    conda-forge
        python-dateutil           2.8.1              pyhd3eb1b0_0
        python_abi                3.7                     1_cp37m    conda-forge
        pytz                      2021.1             pyhd3eb1b0_0
        pywin32                   300              py37hcc03f2d_0    conda-forge
        pywinpty                  0.5.7            py37hc8dfbb8_1    conda-forge
        pyzmq                     22.0.1           py37h0d95fc2_0    conda-forge
        requests                  2.25.1             pyhd3deb0d_0    conda-forge
        scikit-learn              0.20.2           py37h343c172_0
        scipy                     1.1.0            py37h29ff71c_2
        send2trash                1.5.0                      py_0    conda-forge
        setuptools                52.0.0           py37haa95532_0
        six                       1.15.0           py37haa95532_0
        terminado                 0.9.2            py37h03978a9_0    conda-forge
        testpath                  0.4.4                      py_0    conda-forge
        tornado                   6.1              py37hcc03f2d_1    conda-forge
        traitlets                 5.0.5                      py_0    conda-forge
        typing_extensions         3.7.4.3                    py_0    conda-forge
        urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
        vc                        14.2                 h21ff451_1
        vs2015_runtime            14.27.29016          h5e58377_2
        wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        wheel                     0.36.2             pyhd3eb1b0_0
        win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
        wincertstore              0.2                      py37_0
        winpty                    0.4.3                         4    conda-forge
        zeromq                    4.3.3                h0e60522_3    conda-forge
        zipp                      3.4.0                      py_0    conda-forge

conda env:
        name: mssql
        channels:
          - conda-forge
          - defaults
        dependencies:
          - argon2-cffi=20.1.0=py37hcc03f2d_2
          - async_generator=1.10=py_0
          - attrs=20.3.0=pyhd3deb0d_0
          - backcall=0.2.0=pyh9f0ad1d_0
          - backports=1.0=py_2
          - backports.functools_lru_cache=1.6.1=py_0
          - blas=1.0=mkl
          - bleach=3.3.0=pyh44b312d_0
          - brotlipy=0.7.0=py37hcc03f2d_1001
          - ca-certificates=2020.12.5=h5b45459_0
          - certifi=2020.12.5=py37h03978a9_1
          - cffi=1.14.4=py37hd8e9650_1
          - chardet=4.0.0=py37h03978a9_1
          - colorama=0.4.4=pyh9f0ad1d_0
          - cryptography=3.3.1=py37hd8e9650_1
          - decorator=4.4.2=py_0
          - defusedxml=0.6.0=py_0
          - entrypoints=0.3=pyhd8ed1ab_1003
          - icc_rt=2019.0.0=h0cc432a_1
          - idna=2.10=pyh9f0ad1d_0
          - importlib-metadata=3.4.0=py37h03978a9_0
          - importlib_metadata=3.4.0=hd8ed1ab_0
          - intel-openmp=2020.2=254
          - ipykernel=5.1.0=pyh24bf2e0_0
          - ipython=7.20.0=py37heaed05f_0
          - ipython_genutils=0.2.0=py_1
          - jedi=0.18.0=py37h03978a9_2
          - jinja2=2.11.3=pyh44b312d_0
          - json5=0.9.5=pyh9f0ad1d_0
          - jsonschema=3.2.0=py_2
          - jupyter_client=6.1.11=pyhd8ed1ab_1
          - jupyter_core=4.7.1=py37h03978a9_0
          - jupyterlab=2.2.9=pyhd8ed1ab_0
          - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
          - jupyterlab_server=1.2.0=py_0
          - libblas=3.9.0=7_mkl
          - libcblas=3.9.0=7_mkl
          - liblapack=3.9.0=7_mkl
          - libsodium=1.0.18=h8d14728_1
          - m2w64-gcc-libgfortran=5.3.0=6
          - m2w64-gcc-libs=5.3.0=7
          - m2w64-gcc-libs-core=5.3.0=7
          - m2w64-gmp=6.1.0=2
          - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
          - markupsafe=1.1.1=py37hcc03f2d_3
          - mistune=0.8.4=py37hcc03f2d_1003
          - mkl=2020.4=hb70f87d_311
          - msys2-conda-epoch=20160418=1
          - nbclient=0.5.1=py_0
          - nbconvert=6.0.7=py37h03978a9_3
          - nbformat=5.1.2=pyhd8ed1ab_1
          - nest-asyncio=1.4.3=pyhd8ed1ab_0
          - notebook=6.2.0=py37h03978a9_0
          - numpy=1.15.4=py37h8078771_1002
          - openssl=1.1.1i=h8ffe710_0
          - packaging=20.8=pyhd3deb0d_0
          - pandas=0.23.4=py37h830ac7b_1000
          - pandoc=2.11.4=h8ffe710_0
          - pandocfilters=1.4.2=py_1
          - parso=0.8.1=pyhd8ed1ab_0
          - pickleshare=0.7.5=py_1003
          - pip=20.3.3=py37haa95532_0
          - prometheus_client=0.9.0=pyhd3deb0d_0
          - prompt-toolkit=3.0.14=pyha770c72_0
          - pycparser=2.20=pyh9f0ad1d_2
          - pygments=2.7.4=pyhd8ed1ab_0
          - pyopenssl=20.0.1=pyhd8ed1ab_0
          - pyparsing=2.4.7=pyh9f0ad1d_0
          - pyrsistent=0.17.3=py37hcc03f2d_2
          - pysocks=1.7.1=py37h03978a9_3
          - python=3.7.1=h9460c21_1003
          - python-dateutil=2.8.1=pyhd3eb1b0_0
          - python_abi=3.7=1_cp37m
          - pytz=2021.1=pyhd3eb1b0_0
          - pywin32=300=py37hcc03f2d_0
          - pywinpty=0.5.7=py37hc8dfbb8_1
          - pyzmq=22.0.1=py37h0d95fc2_0
          - requests=2.25.1=pyhd3deb0d_0
          - scikit-learn=0.20.2=py37h343c172_0
          - scipy=1.1.0=py37h29ff71c_2
          - send2trash=1.5.0=py_0
          - setuptools=52.0.0=py37haa95532_0
          - six=1.15.0=py37haa95532_0
          - terminado=0.9.2=py37h03978a9_0
          - testpath=0.4.4=py_0
          - tornado=6.1=py37hcc03f2d_1
          - traitlets=5.0.5=py_0
          - typing_extensions=3.7.4.3=py_0
          - urllib3=1.26.3=pyhd8ed1ab_0
          - vc=14.2=h21ff451_1
          - vs2015_runtime=14.27.29016=h5e58377_2
          - wcwidth=0.2.5=pyh9f0ad1d_2
          - webencodings=0.5.1=py_1
          - wheel=0.36.2=pyhd3eb1b0_0
          - win_inet_pton=1.1.0=py37h03978a9_2
          - wincertstore=0.2=py37_0
          - winpty=0.4.3=4
          - zeromq=4.3.3=h0e60522_3
          - zipp=3.4.0=py_0
        prefix: C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 14:52:38.567 LabApp] JupyterLab extension loaded from C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyterlab
[I 14:52:38.567 LabApp] JupyterLab application directory is C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\share\jupyter\lab
[I 14:52:38.567 LabApp] Serving notebooks from local directory: C:\Users\Yannis.Katsaros\dev\temp
[I 14:52:38.567 LabApp] Jupyter Notebook 6.2.0 is running at:
[I 14:52:38.567 LabApp] http://localhost:8888/?token=1ac02920f8e4a37596650bb931e7484c99ab6f84d86ea65d
[I 14:52:38.567 LabApp]  or http://127.0.0.1:8888/?token=1ac02920f8e4a37596650bb931e7484c99ab6f84d86ea65d
[I 14:52:38.567 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:52:38.884 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Yannis.Katsaros/AppData/Roaming/jupyter/runtime/nbserver-11344-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=1ac02920f8e4a37596650bb931e7484c99ab6f84d86ea65d
     or http://127.0.0.1:8888/?token=1ac02920f8e4a37596650bb931e7484c99ab6f84d86ea65d
[I 14:52:44.580 LabApp] Build is up to date
[W 14:52:50.746 LabApp] Notebook Untitled.ipynb is not trusted
[E 14:52:52.554 LabApp] Failed to run command:
    ['C:/Users/Yannis.Katsaros/Miniconda3/envs/mssql/bin/python', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\Yannis.Katsaros\\AppData\\Roaming\\jupyter\\runtime\\kernel-fa61c885-e6e1-45a9-99e9-3af2a26a1dbf.json']
        PATH='...'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\Yannis.Katsaros\\dev\\temp', 'close_fds': False}

[E 14:52:52.554 LabApp] Uncaught exception POST /api/sessions?1612299172442 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1612299172442', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\manager.py", line 313, in start_kernel
        self.kernel = self._launch_kernel(kernel_cmd, **kw)
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\manager.py", line 222, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\launcher.py", line 134, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\subprocess.py", line 769, in __init__
        restore_signals, start_new_session)
      File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\subprocess.py", line 1172, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 14:52:52.601 LabApp] Unhandled error
[E 14:52:52.601 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Referer": "http://localhost:8888/lab",
      "Content-Type": "text/plain;charset=UTF-8",
      "Authorization": "token 1ac02920f8e4a37596650bb931e7484c99ab6f84d86ea65d",
      "X-Xsrftoken": "2|6c1732e8|d4ccba33fe83df711be0a84e48a21041|1610118405",
      "Origin": "http://localhost:8888",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1612299171|23:username-localhost-8888|44:ZmM3N2QxMzU4MjZmNGE2MmI3NjNlZjFmMjVkMDQ0YTM=|a282cefd80134a1f5ea07be9f5ff50e8a8edab4e3609df9dbeedc4e1a66a9a9c\"; _xsrf=2|6c1732e8|d4ccba33fe83df711be0a84e48a21041|1610118405",
      "Sec-Gpc": "1",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache",
      "Accept-Encoding": "gzip, deflate",
      "Content-Length": "117"
    }
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Traceback (most recent call last):
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\manager.py", line 313, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\manager.py", line 222, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\site-packages\jupyter_client\launcher.py", line 134, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Yannis.Katsaros\Miniconda3\envs\mssql\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
vendors~main.e39d4a65a871fe1cc8fa.js:2:2395922
    create http://localhost:8888/static/lab/vendors~main.e39d4a65a871fe1cc8fa.js:2

Uncaught (in promise) Error: Unhandled error
    r http://localhost:8888/static/lab/vendors~main.e39d4a65a871fe1cc8fa.js:2
    create http://localhost:8888/static/lab/vendors~main.e39d4a65a871fe1cc8fa.js:2

Uncaught (in promise) Error: No kernel to restart
    restart http://localhost:8888/static/lab/vendors~main.e39d4a65a871fe1cc8fa.js:2
</pre>
</details>

**Comment by thomasaarholt** [comment]
I'm getting the same issue on a fresh install of miniconda installed today, using `conda create --name test python=3.7 jupyterlab`.

**Comment by Emalude** [comment]
Had same issue and after several hours I've found this solution working for me https://discourse.jupyter.org/t/looking-for-help-with-a-kernel-error/4528

**Comment by trojanc1** [comment]
You can check the disk status by running a "df -h" if it is full. 

When I check using "jupyter kernelspec list --json"
it shows 
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/opt/conda/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/opt/conda/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3 (ipykernel)",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {
          "debugger": true
        }
      }
    }
So I manually run this command: 
/opt/conda/bin/python -m ipykernel_launcher -f /opt/conda/share/jupyter/kernels/python3/kernel.json
(the kernel json location you can find it in "jupyter kernelspec list")
it shows sqlite is full thus the kernel cannot be started, after I expanded the disk everything is working as expected.

**Comment by Sarvandani** [comment]
One of the reasons of errors is that an old kernelspec is related to a removed environment. We may rectify the problem by the following command:
jupyter kernelspec remove python3
