### ISSUE TITLE
Error when attempting to build jupyter lab in anaconda prompt

### ISSUE THREAD

**Issue by VanWieren** [jupyterlab/jupyterlab#9753]
## Description

when typing `jupyter lab build ` the following results:
`[LabBuildApp] Building in c:\users\cvanw\anaconda3\share\jupyter\lab
[LabBuildApp] Node v12.16.1

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.54s.

[LabBuildApp] > node c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ c:\users\cvanw\anaconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
Done in 0.45s.

[LabBuildApp] > node c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] [31mTypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (c:\users\cvanw\anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:119:10)
    at c:\users\cvanw\anaconda3\share\jupyter\lab\staging\node_modules\terser-webpack-plugin\dist\index.js:566:67
    at _next36 (eval at create (c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:38:1)
    at _next14 (eval at create (c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:95:1)
    at Hook.eval [as call] (eval at create (c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:127:1)
    at Hook.CALL_DELEGATE [as _call] (c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\Compiler.js:993:26)
    at c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\Compiler.js:1035:29
    at Hook.eval [as callAsync] (eval at create (c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (c:\Users\cvanw\Anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\Hook.js:18:14)[39m
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\labapp.py", line 168, in start
    raise e

[LabBuildApp]   File "c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\labapp.py", line 164, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\commands.py", line 463, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "c:\users\cvanw\anaconda3\lib\site-packages\jupyterlab\commands.py", line 675, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab`

## Reproduce

Open anaconda prompt, type jupyter lab build

## Expected behavior
the build should be successful 

## Context

- Operating System and version: windows 10
- Browser and version: chrome
- JupyterLab version: 3.0.6

**Comment by jasongrout** [comment]
This should be fixed in JupyterLab 3.0.7. Can you upgrade and try again?

**Comment by jasongrout** [comment]
(See #9709 for more details)

**Comment by VanWieren** [comment]
Fixed, thanks!
