### ISSUE TITLE
`ArgumentConflict` is not defined

### ISSUE THREAD

**Issue by andrewfulton9** [jupyterlab/jupyterlab#9759]
## Description
When I add 
```python
c.DevelopLabExtensionApp.labextensions_dir=<some_path>
```
to a custom configuration

I get the error:
```traceback
Traceback (most recent call last):

  File "/home/andrew/Dropbox/quansight/jupyter/jupyterlab-git/_build/pip_packages/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/andrew/Dropbox/quansight/jupyter/jupyterlab-git/_build/pip_packages/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 127, in start
    ans = self.run_task()

  File "/home/andrew/Dropbox/quansight/jupyter/jupyterlab-git/_build/pip_packages/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 199, in run_task
    develop_labextension_py(arg, user=self.user, sys_prefix=self.sys_prefix, labextensions_dir=self.labextensions_dir, logger=self.log, overwrite=self.overwrite,

  File "/home/andrew/Dropbox/quansight/jupyter/jupyterlab-git/_build/pip_packages/lib/python3.8/site-packages/jupyterlab/federated_labextensions.py", line 157, in develop_labextension_py
    full_dest = develop_labextension(

  File "/home/andrew/Dropbox/quansight/jupyter/jupyterlab-git/_build/pip_packages/lib/python3.8/site-packages/jupyterlab/federated_labextensions.py", line 83, in develop_labextension
    labext = _get_labextension_dir(user=user, sys_prefix=sys_prefix, labextensions_dir=labextensions_dir)

  File "/home/andrew/Dropbox/quansight/jupyter/jupyterlab-git/_build/pip_packages/lib/python3.8/site-packages/jupyterlab/federated_labextensions.py", line 332, in _get_labextension_dir
    raise ArgumentConflict(
```

It looks like this `ArgumentConflict` error isn't defined anywhere in jupyterlab.

I can submit a PR to fix this later today by adding an `ArgumentConflict` class that subclasses from `traitlets.TraitError`. I'm open to other recomendations as well though.

## Reproduce

add
```python
c.DevelopLabExtensionApp.labextensions_dir=<some_path>
```
to a `jupyter_config.py`  from a jupyter lab extension repo and run:
```bash
jupyter labextension develop .  --config jupyter_config.py
```

## Expected behavior
`ArgumentConflict` is properly raised

## Context

- Operating System and version: Ubuntu 18.04.5
- Browser and version: N/A
- JupyterLab version: 3.0.6

<details><summary>Command Line Output</summary>
<pre>
Installing /home/andrew/Dropbox/quansight/jupyter/jupyterlab-git/jupyterlab_git/labextension -> @jupyterlab/git
An error occured.
NameError: name 'ArgumentConflict' is not defined
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
N/A
</pre>
</details>

**Comment by telamonian** [comment]
Yep, I think you're right that the def of `ArgumentConflict` is missing. Previously, it looks like the def was in [`notebook.extensions`](https://github.com/jupyter/notebook/blob/7f7ea8e85c9c90b264317a7c2f4995ab99fd8f60/notebook/extensions.py#L15), but now that we've switched over to [`jupyter_server`](https://github.com/jupyter-server/jupyter_server/blob/b2e089506baf0723fe63112cb9df7ef8b493d093/jupyter_server/extension/serverextension.py#L72) we'll have to add:

```python
from jupyter_server.extension.serverextension import ArgumentConflict
```

@andrewfulton9 If you want the honors, could you please submit a PR that adds the above import right after the following lines:

https://github.com/jupyterlab/jupyterlab/blob/5340e7161b4c5b67cd3e8184a018e142af86b22c/jupyterlab/federated_labextensions.py#L19-L24

Thanks for spotting this!

**Comment by andrewfulton9** [comment]
Just made the [PR](https://github.com/jupyterlab/jupyterlab/pull/9760). Thanks @telamonian!
