### ISSUE TITLE
`jupyter lab build` fails because of UNC paths

### ISSUE THREAD

**Issue by genneth** [jupyterlab/jupyterlab#9819]
## Description

`jupyter lab build` fails because somewhere in webpack doesn't seem to recognise paths starting with `\\` on windows as legitimate paths.

## Reproduce

1. Use windows
2. Create python venv on a mapped network share
3. pip install jupyterlab
4. jupyter labextension install plotlywidget

## Expected behavior

Success

## Context

- Operating System and version: windows 10
- Browser and version: N/A
- JupyterLab version: 3.0.7
- Local nodejs version: 14.15.4

build log snippet:

````
[LabBuildApp] > node g:\python\jupyter-venv\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] [31mError: \\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules is neither a posix nor a windows path, and there is no 'join' method defined in the file system
    at join (\\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\webpack\lib\util\fs.js:161:9)
    at \\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\webpack\lib\FileSystemInfo.js:869:4
    at Array.map (<anonymous>)
    at new FileSystemInfo (\\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\webpack\lib\FileSystemInfo.js:868:50)
    at new Compilation (\\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\webpack\lib\Compilation.js:760:25)
    at Compiler.createCompilation (\\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\webpack\lib\Compiler.js:981:10)
    at Compiler.newCompilation (\\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\webpack\lib\Compiler.js:989:28)
    at \\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\webpack\lib\Compiler.js:1035:29
    at Hook.eval [as callAsync] (eval at create (\\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (\\fs-d-ws03.vgis.sites.uberit.net\Scratch\genz\python\jupyter-venv\share\jupyter\lab\staging\node_modules\tapable\lib\Hook.js:18:14)[39m
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by jasongrout** [comment]
Searching for this error yields these probably related reports:

- https://stackoverflow.com/questions/65824039/webpack-5-and-support-for-unc-paths-as-output
- https://github.com/webpack/webpack/issues/12305

The error seems to come from this code: https://github.com/webpack/webpack/blob/08562140d891d23e794fc14734995df111cb61b8/lib/util/fs.js#L150-L169

**Comment by jasongrout** [comment]
In particular, this check for a windows path looks like it does not handle the UNC path case (both here and other places in the file): https://github.com/webpack/webpack/blob/08562140d891d23e794fc14734995df111cb61b8/lib/util/fs.js#L161

**Comment by jasongrout** [comment]
I submitted a potential fix to webpack at https://github.com/webpack/webpack/pull/12714

**Comment by jasongrout** [comment]
FYI, the fix was merged into webpack just now, so we'll just need to upgrade webpack when it is next released.

**Comment by isabela-pf** [comment]
Thanks!

**Comment by isabela-pf** [comment]
Thanks!

**Comment by jasongrout** [comment]
Looks like we have not updated past webpack 5.37.1 yet in master.
