### ISSUE TITLE
jupyterlab3 issue on Ubuntu 20.04 

### ISSUE THREAD

**Issue by xinyu-dev** [jupyterlab/jupyterlab#9841]
**Environment:** 
1. Ubuntu 20.04 (64 bit, x86), g4dn.4xlarge instance
2. Clean install of Linux version of Anaconda (Anaconda3-2020.11-Linux-x86_64.sh)

**Operations to reproduce:**
1. In the above env, remove the existing 2.2.x jupyter lab that comes with Anaconda package using `conda uninstall jupyterlab`
2. Reinstall the 3.0.x jupyterlab pacakage using `conda install -c conda-forge jupyterlab `. This installs jupyterlab 3.0.8
3. Try launching `jupyter lab` from terminal, got this error: 

--------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2018, in launch_browser
    browser = webbrowser.get(self.browser or None)
  File "/home/ubuntu/anaconda3/lib/python3.8/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 520, in launch_instance
    serverapp.start()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2100, in start
    self.start_app()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2059, in start_app
    self.launch_browser()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2020, in launch_browser
    self.log.warning(_('No web browser found: %s.') % e)
UnboundLocalError: local variable '_' referenced before assignment

--------------------------------
**Solution**: 
1. The error is pointing to the files in `jupyter_server`. I downgraded jupyter_server from 2.3.0 to 1.2.2 and the issue was gone.

**Comment by Zsailer** [comment]
This is a bug in jupyter_server. It was fixed in jupyter-server/jupyter_server#421.

We'll cut a patch release today and update this issue once that's out.

**Comment by Zsailer** [comment]
Fixed in `jupyter_server` [1.4.1](https://pypi.org/project/jupyter-server/1.4.1/).

**Comment by Zsailer** [comment]
Closing this issue for now; feel free to re-open if the issue continues after upgrading jupyter_server:
```
pip install -U jupyter_server
```
Thanks!
