### ISSUE TITLE
Getting AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found Error On MacOS Big Sur

### ISSUE THREAD

**Issue by ashkan-leo** [jupyterlab/jupyterlab#9863]
## Description
After installing jupyter and juptyerlab, I get the following errors when running jupyter lab or jupyter notebook:
```
Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab_server/app.py", line 11, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 21, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 78, in <module>
    from .services.contents.filemanager import AsyncFileContentsManager, FileContentsManager
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py", line 16, in <module>
    from send2trash import send2trash
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found

```

After running `jupyter --version`, I get:
```
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.20.0
ipykernel        : 5.5.0
jupyter client   : 6.1.11
Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_core/command.py", line 202, in main
    mod = __import__(package)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab_server/app.py", line 11, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 21, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 78, in <module>
    from .services.contents.filemanager import AsyncFileContentsManager, FileContentsManager
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py", line 16, in <module>
    from send2trash import send2trash
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found

```

## Reproduce

1. Install jupyter and jupyterlab on MacOS 11.1.
2. Run jupyter lab
3. Run jupyter notebook
4. Observe both produce same error.

I have used poetry to reproduce this bug. The minimal `pyproject.toml` is:
```
[tool.poetry]
name = "example"
version = "0.1.0"
description = "Example"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.0.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Expected behavior

Jupyter lab and jupyter notebook should work on MacOS.

## Context

- Operating System and version: Mac OS Big Sur 11.1
- Browser and version: Firefox 
- JupyterLab version: 3.0.9 and 3.1.0a3

<details><summary>Troubleshoot Output</summary>
<pre>

$PATH:
/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/bin
/Users/me/.nix-profile/bin
/run/current-system/sw/bin
/nix/var/nix/profiles/default/bin
/usr/local/bin
/usr/bin
/usr/sbin
/bin
/sbin

sys.path:
/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/bin
/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python38.zip
/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8
/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/lib-dynload
/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages

sys.executable:
/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/bin/python3

sys.version:
3.8.7 (default, Jan 24 2021, 17:47:57) 
[Clang 7.1.0 (tags/RELEASE_710/final)]

platform.platform():
macOS-10.16-x86_64-i386-64bit

which -a jupyter:
/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/bin/jupyter
/usr/local/bin/jupyter

pip list:
Package             Version
------------------- ---------
anyio               2.1.0
appnope             0.1.2
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
Babel               2.9.0
backcall            0.2.0
bleach              3.3.0
certifi             2020.12.5
cffi                1.14.5
chardet             4.0.0
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
idna                2.10
ipykernel           5.5.0
ipython             7.20.0
ipython-genutils    0.2.0
jedi                0.18.0
Jinja2              2.11.3
json5               0.9.5
jsonschema          3.2.0
jupyter-client      6.1.11
jupyter-core        4.7.1
jupyter-packaging   0.7.12
jupyter-server      1.4.1
jupyterlab          3.1.0a3
jupyterlab-pygments 0.1.2
jupyterlab-server   2.3.0
MarkupSafe          1.1.1
mistune             0.8.4
nbclassic           0.2.6
nbclient            0.5.2
nbconvert           6.0.7
nbformat            5.1.2
nest-asyncio        1.5.1
notebook            6.2.0
packaging           20.9
pandocfilters       1.4.3
parso               0.8.1
pexpect             4.8.0
pickleshare         0.7.5
pip                 21.0.1
prometheus-client   0.9.0
prompt-toolkit      3.0.16
ptyprocess          0.7.0
pycparser           2.20
Pygments            2.8.0
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pytz                2021.1
pyzmq               22.0.3
requests            2.25.1
Send2Trash          1.5.0
setuptools          49.6.0
six                 1.15.0
sniffio             1.2.0
terminado           0.9.2
testpath            0.4.4
tornado             6.1
traitlets           5.0.5
urllib3             1.26.3
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.35.1

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
<Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab/labapp.py", line 16, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyterlab_server/app.py", line 11, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 21, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 78, in <module>
    from .services.contents.filemanager import AsyncFileContentsManager, FileContentsManager
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py", line 16, in <module>
    from send2trash import send2trash
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/example-HIqUKFBh-py3.8/lib/python3.8/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
N/A
</pre>
</details>

**Comment by ashkan-leo** [comment]
Also see https://github.com/arsenetar/send2trash/issues/51

**Comment by ashkan-leo** [comment]
Does anyone know a workaround? I really need Jupyter to work on my laptop.

**Comment by jasongrout** [comment]
A very hacky workaround until send2trash is fixed might be to comment out the import in `/Users/me/Library/Caches/pypoetry/virtualenvs/example-project-HIqUKFBh-py3.8/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py` line 16, then modify `_check_trash` in the same file to always return False (so it doesn't ever try to call send2trash).

**Comment by bergkvist** [comment]
This worked for me on MacOS Big Sur:
```sh
$ pip install jupyterlab==3.0.16 pyobjc-framework-Cocoa==7.3 send2trash==1.7.0a1
$ jupyter lab
```

**Comment by idontgetoutmuch** [comment]
I also have this problem

```
[nix-shell:~/data-analytics]$ jupyter --version
jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.3
qtconsole        : 5.1.1
ipython          : 7.24.1
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

```
[nix-shell:~/data-analytics]$ jupyter-notebook 
jupyter-notebook 
Traceback (most recent call last):
  File "/nix/store/9qwb5cqwj56ab19kyk205b98l2im4wgi-python3.9-notebook-6.4.3/bin/.jupyter-notebook-wrapped", line 6, in <module>
    from notebook.notebookapp import main
  File "/nix/store/9qwb5cqwj56ab19kyk205b98l2im4wgi-python3.9-notebook-6.4.3/lib/python3.9/site-packages/notebook/notebookapp.py", line 81, in <module>
    from .services.contents.filemanager import FileContentsManager
  File "/nix/store/9qwb5cqwj56ab19kyk205b98l2im4wgi-python3.9-notebook-6.4.3/lib/python3.9/site-packages/notebook/services/contents/filemanager.py", line 17, in <module>
    from send2trash import send2trash
  File "/nix/store/binrgnllvpf4pildj3wriczyvihrh92z-python3.9-Send2Trash-1.5.0/lib/python3.9/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/nix/store/binrgnllvpf4pildj3wriczyvihrh92z-python3.9-Send2Trash-1.5.0/lib/python3.9/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/nix/store/amn854jw94m1cph654w91pfyvz5r5a6h-python3-3.9.6/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/nix/store/amn854jw94m1cph654w91pfyvz5r5a6h-python3-3.9.6/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found
```

Using

```
with import <nixpkgs> {};

let
  py = pkgs.python3;
in

stdenv.mkDerivation rec {
  name = "python-env";

  buildInputs = let
    py = pkgs.python3;
  in [
    py
    py.pkgs.matplotlib
    py.pkgs.pandas
    py.pkgs.numpy
    py.pkgs.jupyter
  ];

  shellHook = ''
  echo "using python: ${py.name}"
  '';

}
```

and


```
[nix-shell:~/data-analytics]$ jupyter-notebook 
```
