### ISSUE TITLE
Unexpected error while saving file, with python 3.8, on remote drive

### ISSUE THREAD

**Issue by PierreCe** [jupyterlab/jupyterlab#9868]
## Description

On a new installation of miniconda, and on a new environnement, passing the commands conda install jupyter and conda install jupyterlab result in an environment which can not replace an existing notebook on a remote drive.
The error is :
File Save Error for Brouillon_.ipynb
Unexpected error while saving file : Brouillon.ipynb [Error 22] invalid argument 'U:\\Mes Donnees\\VDD\\Brouillon_.ipynb'

jupyterlab can create a new notebook
"save as" function works well
if the notebook is renamed with the explorer, jupyterlab can save the notebook
if the notebook is on a local drive there is no error
In result auto-save and CTRL-S don't work on remote drive.

Of course, there is no issue with other application (Notepad++ can modify notebooks on my U:), after adding spyder to the environment, spyder can modify files on remote drive.

On other symptom I have '.~NameOFTheNoteBook.ipynb' files on my remote drive that I don't have on my local drive.

## Reproduce

Downgrading python version to 3.7.9 correct this error (by default 3.9.1 is installed)
Upgrading to 3.8.0 makes the error comes back.
conda output on upgrading to 3.8.0 is :
```
conda install python=3.8.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\S10500\Miniconda3\envs\juplab

  added / updated specs:
    - python=3.8.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.12.5          |   py38haa95532_0         141 KB
    cffi-1.14.5                |   py38hcd4344a_0         224 KB
    chardet-4.0.0              |py38haa95532_1003         211 KB
    cryptography-3.3.1         |   py38hcd4344a_1         542 KB
    entrypoints-0.3            |           py38_0          11 KB
    ipykernel-5.3.4            |   py38h5ca1d4c_0         182 KB
    ipython-7.20.0             |   py38hd4e2768_1        1012 KB
    jedi-0.17.2                |   py38haa95532_1         921 KB
    jupyter-1.0.0              |           py38_7           8 KB
    jupyter_core-4.7.1         |   py38haa95532_0          85 KB
    markupsafe-1.1.1           |   py38he774522_0          29 KB
    mistune-0.8.4              |py38he774522_1000          55 KB
    nbconvert-6.0.7            |           py38_0         500 KB
    notebook-6.0.3             |           py38_0         4.3 MB
    pandocfilters-1.4.3        |   py38haa95532_1          14 KB
    pip-21.0.1                 |   py38haa95532_0         1.8 MB
    pyqt-5.9.2                 |   py38ha925a31_4         3.2 MB
    pyrsistent-0.17.3          |   py38he774522_0          92 KB
    python-3.8.0               |       hff0d562_2        15.9 MB
    pywinpty-0.5.7             |           py38_0          52 KB
    pyzmq-20.0.0               |   py38hd77b12b_1         405 KB
    setuptools-52.0.0          |   py38haa95532_0         726 KB
    sip-4.19.13                |   py38ha925a31_0         262 KB
    terminado-0.9.2            |   py38haa95532_0          26 KB
    tornado-6.1                |   py38h2bbff1b_0         612 KB
    webencodings-0.5.1         |           py38_1          20 KB
    widgetsnbextension-3.5.1   |           py38_0         863 KB
    ------------------------------------------------------------
                                           Total:        32.1 MB

The following packages will be REMOVED:

  argon2-cffi-20.1.0-py37h2bbff1b_1

The following packages will be UPDATED:

  pyqt                                 5.9.2-py37h6538335_2 --> 5.9.2-py38ha925a31_4
  python                                   3.7.9-h60c2a47_0 --> 3.8.0-hff0d562_2
  sip                                 4.19.8-py37h6538335_0 --> 4.19.13-py38ha925a31_0

The following packages will be SUPERSEDED by a higher-priority channel:

  async_generator    pkgs/main/win-64::async_generator-1.1~ --> pkgs/main/noarch::async_generator-1.10-pyhd3eb1b0_0

The following packages will be DOWNGRADED:

  brotlipy                          0.7.0-py37h2bbff1b_1003 --> 0.7.0-py38h2bbff1b_1003
  certifi                          2020.12.5-py37haa95532_0 --> 2020.12.5-py38haa95532_0
  cffi                                1.14.5-py37hcd4344a_0 --> 1.14.5-py38hcd4344a_0
  chardet                           4.0.0-py37haa95532_1003 --> 4.0.0-py38haa95532_1003
  cryptography                         3.3.1-py37hcd4344a_1 --> 3.3.1-py38hcd4344a_1
  entrypoints                                    0.3-py37_0 --> 0.3-py38_0
  ipykernel                            5.3.4-py37h5ca1d4c_0 --> 5.3.4-py38h5ca1d4c_0
  ipython                             7.20.0-py37hd4e2768_1 --> 7.20.0-py38hd4e2768_1
  jedi                                0.17.2-py37haa95532_1 --> 0.17.2-py38haa95532_1
  jupyter                                      1.0.0-py37_7 --> 1.0.0-py38_7
  jupyter_core                         4.7.1-py37haa95532_0 --> 4.7.1-py38haa95532_0
  markupsafe                           1.1.1-py37hfa6e2cd_1 --> 1.1.1-py38he774522_0
  mistune                           0.8.4-py37hfa6e2cd_1001 --> 0.8.4-py38he774522_1000
  nbconvert                                    6.0.7-py37_0 --> 6.0.7-py38_0
  notebook                             6.2.0-py37haa95532_0 --> 6.0.3-py38_0
  pandocfilters                        1.4.3-py37haa95532_1 --> 1.4.3-py38haa95532_1
  pip                                 21.0.1-py37haa95532_0 --> 21.0.1-py38haa95532_0
  pyrsistent                          0.17.3-py37he774522_0 --> 0.17.3-py38he774522_0
  pysocks                                      1.7.1-py37_1 --> 1.7.1-py38haa95532_0
  pywin32                                227-py37he774522_1 --> 227-py38he774522_1
  pywinpty                                     0.5.7-py37_0 --> 0.5.7-py38_0
  pyzmq                               20.0.0-py37hd77b12b_1 --> 20.0.0-py38hd77b12b_1
  setuptools                          52.0.0-py37haa95532_0 --> 52.0.0-py38haa95532_0
  six                                 1.15.0-py37haa95532_0 --> 1.15.0-py38haa95532_0
  terminado                            0.9.2-py37haa95532_0 --> 0.9.2-py38haa95532_0
  tornado                                6.1-py37h2bbff1b_0 --> 6.1-py38h2bbff1b_0
  webencodings                                 0.5.1-py37_1 --> 0.5.1-py38_1
  widgetsnbextension                           3.5.1-py37_0 --> 3.5.1-py38_0
  win_inet_pton                        1.1.0-py37haa95532_0 --> 1.1.0-py38haa95532_0
  wincertstore                                   0.2-py37_0 --> 0.2-py38_0
```
Note : with python 3.9.1 notebook was on version 6.2.0-py39haa95532_0, so the downgrading from 6.2.0 to 6.0.3 doesn't seems relevant.

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome  88.0.4324.182
- JupyterLab version: 1.2.6

<details><summary>Troubleshoot Output</summary>
<pre>
File Save Error for Brouillon_.ipynb
Unexpected error while saving file : Brouillon.ipynb [Error 22] invalid argument 'U:\\Mes Donnees\\VDD\\Brouillon_.ipynb 
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 12:47:49.952 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:47:50.089 LabApp] Starting kernel: ['C:/Users/S10500/Miniconda3/envs/juplab\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\S10500\\AppData\\Roaming\\jupyter\\runtime\\kernel-8bc2d75c-b519-49ad-9bfc-830daf37b214.json']
[D 12:47:52.125 LabApp] Connecting to: tcp://127.0.0.1:64052
[D 12:47:52.132 LabApp] Connecting to: tcp://127.0.0.1:64049
[I 12:47:52.134 LabApp] Kernel started: 8bc2d75c-b519-49ad-9bfc-830daf37b214
[D 12:47:52.134 LabApp] Kernel args: {'kernel_name': 'python3', 'cwd': 'U:\\Mes Donnees\\VDD'}
[D 12:47:52.136 LabApp] 201 POST /api/sessions?1614167269944 (127.0.0.1) 2184.20ms
[D 12:47:52.141 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:47:52.144 LabApp] 204 PUT /lab/api/workspaces/lab?1614167270238 (127.0.0.1) 2.99ms
[D 12:47:52.154 LabApp] Initializing websocket connection /api/kernels/8bc2d75c-b519-49ad-9bfc-830daf37b214/channels
[D 12:47:52.156 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:47:52.157 LabApp] Requesting kernel info from 8bc2d75c-b519-49ad-9bfc-830daf37b214
[D 12:47:52.157 LabApp] Connecting to: tcp://127.0.0.1:64048
[D 12:47:52.475 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:47:52.482 LabApp] 200 GET /metrics?1614167272472 (127.0.0.1) 6.98ms
[D 12:47:53.779 LabApp] activity on 8bc2d75c-b519-49ad-9bfc-830daf37b214: status (starting)
[D 12:47:53.782 LabApp] activity on 8bc2d75c-b519-49ad-9bfc-830daf37b214: status (busy)
[D 12:47:53.784 LabApp] activity on 8bc2d75c-b519-49ad-9bfc-830daf37b214: status (idle)
[D 12:47:53.785 LabApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.3', 'implementation': 'ipython', 'implementation_version': '7.20.0', 'language_info': {'name': 'python', 'version': '3.8.0', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]\nType 'copyright', 'credits' or 'license' for more information\nIPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.8'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[D 12:47:53.787 LabApp] 101 GET /api/kernels/8bc2d75c-b519-49ad-9bfc-830daf37b214/channels?session_id=6430d2db-60fb-4750-b03b-d19a396829f4&token=3b20cc52f604bc1f1b6f349b50c28dda553e7b15486cef49 (127.0.0.1) 1633.83ms
[D 12:47:53.788 LabApp] Opening websocket /api/kernels/8bc2d75c-b519-49ad-9bfc-830daf37b214/channels
[D 12:47:53.788 LabApp] Getting buffer for 8bc2d75c-b519-49ad-9bfc-830daf37b214
[D 12:47:53.789 LabApp] Connecting to: tcp://127.0.0.1:64048
[D 12:47:53.791 LabApp] Connecting to: tcp://127.0.0.1:64052
[D 12:47:53.798 LabApp] Connecting to: tcp://127.0.0.1:64049
[D 12:47:53.799 LabApp] Connecting to: tcp://127.0.0.1:64050
[D 12:47:53.803 LabApp] Initializing websocket connection /api/kernels/8bc2d75c-b519-49ad-9bfc-830daf37b214/channels
[D 12:47:53.805 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:47:53.809 LabApp] activity on 8bc2d75c-b519-49ad-9bfc-830daf37b214: status (busy)
[D 12:47:53.810 LabApp] activity on 8bc2d75c-b519-49ad-9bfc-830daf37b214: status (idle)
[D 12:47:53.814 LabApp] 101 GET /api/kernels/8bc2d75c-b519-49ad-9bfc-830daf37b214/channels?session_id=f1cc1413-c99f-4d57-8757-c91c79dd2d23&token=3b20cc52f604bc1f1b6f349b50c28dda553e7b15486cef49 (127.0.0.1) 10.97ms
[D 12:47:53.815 LabApp] Opening websocket /api/kernels/8bc2d75c-b519-49ad-9bfc-830daf37b214/channels
[D 12:47:53.815 LabApp] Getting buffer for 8bc2d75c-b519-49ad-9bfc-830daf37b214
[D 12:47:53.816 LabApp] Connecting to: tcp://127.0.0.1:64048
[D 12:47:53.818 LabApp] Connecting to: tcp://127.0.0.1:64052
[D 12:47:53.822 LabApp] Connecting to: tcp://127.0.0.1:64049
[D 12:47:53.824 LabApp] Connecting to: tcp://127.0.0.1:64050
[D 12:47:53.832 LabApp] Path base\images\favicon-busy-1.ico served from C:\Users\S10500\Miniconda3\envs\juplab\lib\site-packages\notebook\static\base\images\favicon-busy-1.ico
[D 12:47:53.836 LabApp] 304 GET /static/base/images/favicon-busy-1.ico (127.0.0.1) 5.98ms
[D 12:47:53.841 LabApp] activity on 8bc2d75c-b519-49ad-9bfc-830daf37b214: status (busy)
[D 12:47:53.843 LabApp] activity on 8bc2d75c-b519-49ad-9bfc-830daf37b214: status (idle)
[D 12:47:53.857 LabApp] 304 GET /static/base/images/favicon-busy-1.ico (127.0.0.1) 2.00ms
[D 12:47:53.862 LabApp] Websocket closed 8bc2d75c-b519-49ad-9bfc-830daf37b214:f1cc1413-c99f-4d57-8757-c91c79dd2d23
[D 12:47:53.880 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:47:53.882 LabApp] 200 GET /api/sessions?1614167273877 (127.0.0.1) 1.99ms
[D 12:47:54.024 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:47:54.028 LabApp] 200 GET /api/contents/Brouillon_.ipynb?content=0&1614167274021 (127.0.0.1) 4.99ms
[D 12:47:54.040 LabApp] Accepting token-authenticated connection from 127.0.0.1
[I 12:47:54.042 LabApp] Saving file at /Brouillon_.ipynb
[D 12:47:54.042 LabApp] Saving U:\Mes Donnees\VDD\Brouillon_.ipynb
[E 12:47:54.051 LabApp] Error while saving file: Brouillon_.ipynb [Errno 22] Invalid argument: 'U:\\Mes Donnees\\VDD\\.~Brouillon_.ipynb'
    Traceback (most recent call last):
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\site-packages\notebook\services\contents\filemanager.py", line 467, in save
        self._save_notebook(os_path, nb)
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\site-packages\notebook\services\contents\fileio.py", line 290, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\site-packages\notebook\services\contents\fileio.py", line 210, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\site-packages\notebook\services\contents\fileio.py", line 100, in atomic_writing
        copy2_safe(path, tmp_path, log=log)
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\site-packages\notebook\services\contents\fileio.py", line 48, in copy2_safe
        shutil.copyfile(src, dst)
      File "C:\Users\S10500\Miniconda3\envs\juplab\lib\shutil.py", line 259, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    OSError: [Errno 22] Invalid argument: 'U:\\Mes Donnees\\VDD\\.~Brouillon_.ipynb'
[W 12:47:54.062 LabApp] 500 PUT /api/contents/Brouillon_.ipynb?1614167274033 (127.0.0.1): Unexpected error while saving file: Brouillon_.ipynb [Errno 22] Invalid argument: 'U:\\Mes Donnees\\VDD\\.~Brouillon_.ipynb'
[W 12:47:54.068 LabApp] Unexpected error while saving file: Brouillon_.ipynb [Errno 22] Invalid argument: 'U:\\Mes Donnees\\VDD\\.~Brouillon_.ipynb'
[E 12:47:54.068 LabApp] {
      "Host": "127.0.0.1:8888",
      "Connection": "keep-alive",
      "Content-Length": "1226",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
      "X-Xsrftoken": "2|ceb3752f|ef9a6f87bc5d7842db720fe7ca6db673|1614158301",
      "Authorization": "token 3b20cc52f604bc1f1b6f349b50c28dda553e7b15486cef49",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://127.0.0.1:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://127.0.0.1:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "_xsrf=2|ceb3752f|ef9a6f87bc5d7842db720fe7ca6db673|1614158301; username-127-0-0-1-8888=\"2|1:0|10:1614167274|23:username-127-0-0-1-8888|44:ODJlYzI1NmE2ZmMyNGZkY2IxZDk2YjRlMGYyMmJkYmE=|e025246248ad891ddee3f472aeb030567feb54be649192293076e48fce36e3fd\""
    }
[E 12:47:54.069 LabApp] 500 PUT /api/contents/Brouillon_.ipynb?1614167274033 (127.0.0.1) 31.91ms referer=http://127.0.0.1:8888/lab
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
vendors~main.d058a93d0bcdd36e2223.js:1 Kernel: connected (8bc2d75c-b519-49ad-9bfc-830daf37b214)
api/contents/Brouillon_.ipynb?1614167274033:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendors~main.d058a93d0bcdd36e2223.js:1 Uncaught (in promise) Error: Invalid response: 500 Internal Server Error
    at vendors~main.d058a93d0bcdd36e2223.js:1
</pre>
</details>

**Comment by LittleSix1** [comment]
I had the same problem. Did anyone else solve it?

Unexpected error while saving file: Untitled.ipynb [Errno 22] Invalid argument: 'D:\\jupyter\\.~Untitled.ipynb'

win10,  pyhton3.8,  Anaconda3-2021.05-Windows-x86_64
I suspect it's a system problem, but I don't know how to solve it .

**Comment by PierreCe** [comment]
I "solved" the problem by dropping conda and using pip.
