### ISSUE TITLE
Jupyter Lab build: RuntimeError: npm dependencies failed to install

### ISSUE THREAD

**Issue by RobertYang95** [jupyterlab/jupyterlab#9924]
## Description

I installed mitosheet extension for Jupyter Lab and got "Build failed with 500, please run 'jupyter lab build' on the server for full output" error when I start Jupyter Lab.

I followed the recommendation to run "jupyter lab build" but got "RuntimeError: npm dependencies failed to install" error.

I'm using company internet so I guess it is a firewall problem. If so, I wonder how/where to set a proxy to bypass it?

Log file detail as below:
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>
[LabBuildApp] Building in C:\Users\r051122\Anaconda3\share\jupyter\lab
[LabBuildApp] Node v14.16.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node C:\Users\r051122\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Couldn't find package "@jupyter-widgets/base@^1.1.10 || ^2 || ^3" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
Error: Couldn't find package "@types/fscreen@^1.0.1" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "ag-grid-react@^24.0.0" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@types/react-dom@^16.9.8" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "fscreen@^1.1.0" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "ag-grid-community@^24.0.0" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@types/react@^16.9.49" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@types/analytics-node@^3.1.3" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "react-joyride@^2.3.0" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "react-intercom@^1.0.15" required by "mitosheet@file:../extensions/mitosheet-0.1.144.tgz" on the "npm" registry.
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:310:30)
    at C:\Users\r051122\Anaconda3\share\jupyter\lab\staging\yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\Users\r051122\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\Users\r051122\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "C:\Users\r051122\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 134, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "C:\Users\r051122\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "C:\Users\r051122\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 652, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by agoose77** [comment]
If this is a firewall issue, can you try configuring the npm proxy settings? https://stackoverflow.com/a/54447150
