### ISSUE TITLE
ImportError with encodestring from package base64

### ISSUE THREAD

**Issue by Alonoparag** [jupyterlab/jupyterlab#9941]
**Describe the bug**
Jupyter experiences a fatal error on startup. ImportError: cannot import name 'encodestring' from 'base64' (/usr/lib/python3.9/base64.py). 'encodestring is a removed function in python 3.9.
There's a workaround, to downgrade python to version <= 3.8, but I believe that Jupyter should be updated to current python version.

**To Reproduce**
1. Python version 3.9
2. Run any Jupyter product (Notebook, lab).

**Expected behavior**
Traceback (most recent call last):
  File "/home/user/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/user/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 83, in <module>
    from .services.contents.manager import ContentsManager
  File "/home/user/.local/lib/python3.9/site-packages/notebook/services/contents/manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "/home/user/.local/lib/python3.9/site-packages/nbformat/__init__.py", line 14, in <module>
    from . import v1
  File "/home/user/.local/lib/python3.9/site-packages/nbformat/v1/__init__.py", line 19, in <module>
    from .nbjson import reads as reads_json, writes as writes_json
  File "/home/user/.local/lib/python3.9/site-packages/nbformat/v1/nbjson.py", line 19, in <module>
    from base64 import encodestring
ImportError: cannot import name 'encodestring' from 'base64' (/usr/lib/python3.9/base64.py)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro 20.12.2 Gnome 3.38.4
 - Browser Firefox 86.0.01-01
 - Jupyter 4.4.0

**Additional context**

**Comment by jasongrout** [comment]
This line in your stack trace indicates this is an issue with nbformat, not JupyterLab:

>  File "/home/user/.local/lib/python3.9/site-packages/nbformat/v1/nbjson.py", line 19, in
> from base64 import encodestring

Would you mind filing an issue at https://github.com/jupyter/nbformat/issues?
