### ISSUE TITLE
Advice around the xonsh shell kernel for Jupyter

### ISSUE THREAD

**Issue by anki-code** [jupyterlab/jupyterlab#9971]
Hi! Thank you very much for the JupyterLab!

The [xonsh shell](https://xon.sh/) has the [kernel for Jupyter Notebook](https://github.com/xonsh/xonsh/blob/main/xonsh/jupyter_kernel.py). It works perfect in Jupyter but in JupyterLab 3 I have no response from the backend when try to run some code.

Could anyone please take a short look on [the code of the kernel](https://github.com/xonsh/xonsh/blob/main/xonsh/jupyter_kernel.py) and give me an advice how far this code from the working in JupyterLab as well as Jupyter Notebook?

Thanks!

**Comment by agoose77** [comment]
@anki-code I started to look at this, and it seems that I can talk to the kernel directly using `jupyter console`, which supports the idea that it's something happening in the application. However, I don't think this necessarily means that the application has a `bug` - it might be that the kernel is doing something that it shouldn't be, and the app doesn't know how to handle it. 

Instead of finding the cause of this bug, I wonder if this would be a good time to inherit from an existing kernel scaffold, e.g. `metakernel` - `https://github.com/Calysto/xonsh_kernel`

**Comment by anki-code** [comment]
Hi @agoose77 !
I've tried Calisto/xonsh_kernel (last commit was 5 years ago) and got the similar error in JupyterLab like I've got for the builtin xonsh kernel:

<details>

```python
pip install xonsh_kernel
python -m xonsh_kernel.install
jupyter lab
# create notebook and run a command
```
```
/opt/miniconda3/lib/python3.8/site-packages/ipykernel/iostream.py:9: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import lock_held as import_lock_held
/opt/miniconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py:57: DeprecationWarning: ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub
  from ipykernel.datapub import ZMQDataPublisher
/opt/miniconda3/lib/python3.8/site-packages/ipykernel/datapub.py:21: DeprecationWarning: ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize
  from ipykernel.serialize import serialize_object
/opt/miniconda3/lib/python3.8/site-packages/ipykernel/serialize.py:25: DeprecationWarning: ipykernel.pickleutil is deprecated. It has moved to ipyparallel.
  from ipykernel.pickleutil import (
/opt/miniconda3/lib/python3.8/site-packages/ipykernel/pickleutil.py:26: DeprecationWarning: ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize
  from ipykernel import codeutil
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/opt/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 536, in execute_request
    self.do_execute(
  File "/opt/miniconda3/lib/python3.8/site-packages/metakernel/_metakernel.py", line 397, in do_execute
    retval = self.do_execute_direct(code)
  File "/opt/miniconda3/lib/python3.8/site-packages/xonsh_kernel/kernel.py", line 45, in do_execute_direct
    out, err, interrupted = self._do_execute_direct(code)
  File "/opt/miniconda3/lib/python3.8/site-packages/xonsh_kernel/kernel.py", line 60, in _do_execute_direct
    shell = builtins.__xonsh_shell__
AttributeError: module 'builtins' has no attribute '__xonsh_shell__'
```
</details>

I prefer to use [xonsh builtin kernel](https://github.com/xonsh/xonsh/blob/main/xonsh/jupyter_kernel.py) and it will be great if you have a steps to improve it.

**Comment by agoose77** [comment]
Ah, to clarify, I mean that it might be worth inheriting from a metakernel-like implementation that means xonsh doesn't need to handle the various low-level details. I suspect this is being caused by the protocol difference, but I'm not an expert on this.

**Comment by anki-code** [comment]
It will be great to have more detailed steps.

**Comment by anki-code** [comment]
@blink1073 could you please take a short look to this issue! 🙏
